-- Curated illustrated starter selection. Sources and checksums: content/artworks/selection-2026-09.json.
-- Append-only additions; existing text, edited associations and selected images are preserved.
-- All new records remain in review. Image availability does not imply publication readiness.
INSERT INTO sources(slug,name,source_type,base_url,priority) VALUES
 ('nga-washington','National Gallery of Art, Washington','collection_page','https://www.nga.gov',10),
 ('met-museum','The Metropolitan Museum of Art','museum_api','https://www.metmuseum.org',10),
 ('uffizi','Uffizi Galleries','collection_page','https://www.uffizi.it',10),
 ('guggenheim','Solomon R. Guggenheim Museum','collection_page','https://www.guggenheim.org',10),
 ('nasjonalmuseet','National Museum, Norway','collection_page','https://www.nasjonalmuseet.no',10)
ON CONFLICT(slug) DO NOTHING;

INSERT INTO artworks(slug,title,normalized_title,date_display,creation_year_start,creation_year_end,date_precision,work_type,medium_text,dimensions_text,creation_place_display,creation_place_unknown_reason,current_location_text,accession_number,location_checked_at,status)
VALUES
 ('van-eyck-annunciation','The Annunciation','the annunciation','c. 1434–1436',1434,1436,'circa_range','painting','Oil on canvas transferred from panel','90.2 × 34.1 cm (painted surface)',NULL,'The cited object record does not establish a specific place of execution.','National Gallery of Art, Washington, DC','1937.1.39','2026-09-08T00:00:00Z','review'),
 ('leonardo-ginevra-de-benci','Ginevra de’ Benci (obverse)','ginevra de’ benci (obverse)','c. 1474–1478',1474,1478,'circa_range','painting','Oil on panel','38.1 × 37 cm (original panel)',NULL,'The cited object record does not establish a specific place of execution.','National Gallery of Art, Washington, DC','1967.6.1.a','2026-09-08T00:00:00Z','review'),
 ('artemisia-judith-beheading-holofernes','Judith Beheading Holofernes','judith beheading holofernes','c. 1620',1620,1620,'circa','painting','Oil on canvas','146.5 × 108 cm','Rome, Italy',NULL,'Uffizi Galleries, Florence','1890 no. 1567','2026-09-08T00:00:00Z','review'),
 ('rembrandt-self-portrait-1660','Self-Portrait','self-portrait','1660',1660,1660,'exact','painting','Oil on canvas','80.3 × 67.3 cm',NULL,'The cited object record does not establish a specific place of execution.','The Metropolitan Museum of Art, New York','14.40.618','2026-09-08T00:00:00Z','review'),
 ('hokusai-great-wave','Under the Wave off Kanagawa (The Great Wave)','under the wave off kanagawa (the great wave)','c. 1830–1832',1830,1832,'circa_range','print','Woodblock print; ink and color on paper','25.7 × 37.9 cm',NULL,'The cited object record does not establish a specific place of execution.','The Metropolitan Museum of Art, New York','JP1847','2026-09-08T00:00:00Z','review'),
 ('monet-bridge-over-a-pond-of-water-lilies','Bridge over a Pond of Water Lilies','bridge over a pond of water lilies','1899',1899,1899,'exact','painting','Oil on canvas','92.7 × 73.7 cm','Giverny, France',NULL,'The Metropolitan Museum of Art, New York','29.100.113','2026-09-08T00:00:00Z','review'),
 ('kroyer-summer-evening-skagen','Summer Evening on Skagen Sønderstrand','summer evening on skagen sønderstrand','1893',1893,1893,'exact','painting','Oil on canvas','100 × 150 cm',NULL,'The museum identifies the depicted place; the place of execution has not been established in this catalogue.','Skagens Museum, Skagen',NULL,'2026-09-08T00:00:00Z','review'),
 ('anna-ancher-sunlight-blue-room','Sunlight in the Blue Room','sunlight in the blue room','1891',1891,1891,'exact','painting','Oil on canvas','65.2 × 58.8 cm',NULL,'The museum identifies the depicted place; the place of execution has not been established in this catalogue.','Skagens Museum, Skagen',NULL,'2026-09-08T00:00:00Z','review'),
 ('hilma-ten-largest-childhood-2','The Ten Largest, No. 2, Childhood','the ten largest, no. 2, childhood','1907',1907,1907,'exact','painting','Tempera on paper mounted on canvas','315 × 234 cm',NULL,'The cited object record does not establish a specific place of execution.','Hilma af Klint Foundation, Stockholm','HAK103','2026-09-08T00:00:00Z','review'),
 ('munch-the-scream-1893','The Scream','the scream','1893',1893,1893,'exact','painting','Tempera and wax crayon on cardboard','91 × 73.5 cm',NULL,'The cited object record does not establish a specific place of execution.','National Museum, Oslo','NG.M.00939','2026-09-08T00:00:00Z','review')
ON CONFLICT(slug) DO NOTHING;

INSERT INTO artwork_artists(artwork_id,artist_id,attribution_role,representative_order)
SELECT aw.id,a.id,'primary',1 FROM (VALUES
 ('van-eyck-annunciation','jan-van-eyck'),
 ('leonardo-ginevra-de-benci','leonardo-da-vinci'),
 ('artemisia-judith-beheading-holofernes','artemisia-gentileschi'),
 ('rembrandt-self-portrait-1660','rembrandt'),
 ('hokusai-great-wave','katsushika-hokusai'),
 ('monet-bridge-over-a-pond-of-water-lilies','claude-monet'),
 ('kroyer-summer-evening-skagen','p-s-kroyer'),
 ('anna-ancher-sunlight-blue-room','anna-ancher'),
 ('hilma-ten-largest-childhood-2','hilma-af-klint'),
 ('munch-the-scream-1893','edvard-munch')
) seed(work_slug,artist_slug) JOIN artworks aw ON aw.slug=seed.work_slug JOIN artists a ON a.slug=seed.artist_slug
WHERE NOT EXISTS(SELECT 1 FROM artwork_artists existing WHERE existing.artwork_id=aw.id AND existing.artist_id=a.id)
ON CONFLICT DO NOTHING;

INSERT INTO media_assets(storage_kind,storage_path,source_page_url,provider_name,mime_type,width,height,byte_size,checksum_sha256,alt_text,rights_status,license_label,license_url,creator_credit,attribution_text,retrieved_at,verified_at)
VALUES
 ('local','/assets/artworks/van-eyck-annunciation.jpg','https://commons.wikimedia.org/wiki/File:Annunciation_-_Jan_van_Eyck_-_1434_-_NG_Wash_DC.jpg','Wikimedia Commons','image/jpeg',1920,5065,3663317,'1902074c40487b0d35961773d1f436454683dd573cd83e3963fdefbad8104212','A richly dressed angel greets Mary, who kneels in blue robes beside an open book inside a tall, sunlit church.','public_domain','Public Domain Mark 1.0 / PD-Art','https://creativecommons.org/publicdomain/mark/1.0/','Jan van Eyck','Jan van Eyck, The Annunciation. National Gallery of Art, Washington, DC. Reproduction via Wikimedia Commons (PD-Art).','2026-09-08T00:00:00Z','2026-09-08T00:00:00Z'),
 ('local','/assets/artworks/leonardo-ginevra.jpg','https://commons.wikimedia.org/wiki/File:Leonardo_da_Vinci_-_Ginevra_de%27_Benci_-_Google_Art_Project.jpg','Wikimedia Commons','image/jpeg',1920,2035,1257554,'ed2a2d2ce05b1c56c510563a9c137839bc8d1a5b9d4d8e7416bbaa945b08ac67','A young woman with curled hair faces the viewer before a dark juniper bush, with water and distant trees to the right.','public_domain','Public Domain Mark 1.0 / PD-Art','https://creativecommons.org/publicdomain/mark/1.0/','Leonardo da Vinci','Leonardo da Vinci, Ginevra de’ Benci (obverse). National Gallery of Art, Washington, DC. Reproduction via Wikimedia Commons (PD-Art).','2026-09-08T00:00:00Z','2026-09-08T00:00:00Z'),
 ('local','/assets/artworks/artemisia-judith.jpg','https://commons.wikimedia.org/wiki/File:Artemisia_Gentileschi_-_Giuditta_decapita_Oloferne_-_Google_Art_Project-Adjust.jpg','Wikimedia Commons','image/jpeg',1920,2360,872559,'c3454b05e7de4c53413e17bf0866fb442ddc887a52f85dfc61b7979db0a52a8c','Judith and her attendant restrain Holofernes on a bed as Judith cuts his neck with a sword, illuminated against a dark background.','public_domain','Public Domain Mark 1.0 / PD-Art','https://creativecommons.org/publicdomain/mark/1.0/','Artemisia Gentileschi','Artemisia Gentileschi, Judith Beheading Holofernes. Uffizi Galleries, Florence. Reproduction via Wikimedia Commons (PD-Art). Source reproduction has a levels adjustment.','2026-09-08T00:00:00Z','2026-09-08T00:00:00Z'),
 ('local','/assets/artworks/rembrandt-self.jpg','https://www.metmuseum.org/art/collection/search/437397','The Metropolitan Museum of Art','image/jpeg',3298,4000,3745892,'fa35e574a0130457a547f4236d1b8534cdd63861cd95c9d35933bc9bc5f104ec','Rembrandt faces the viewer in a dark cap and brown coat; thick paint catches the light on his forehead, nose, and aging face.','cc0','CC0 1.0 — Met Open Access','https://creativecommons.org/publicdomain/zero/1.0/','Rembrandt van Rijn','Rembrandt van Rijn, Self-Portrait. The Metropolitan Museum of Art, New York. Bequest of Benjamin Altman, 1913. Image: The Metropolitan Museum of Art, CC0.','2026-09-08T00:00:00Z','2026-09-08T00:00:00Z'),
 ('local','/assets/artworks/hokusai-wave.jpg','https://www.metmuseum.org/art/collection/search/45434','The Metropolitan Museum of Art','image/jpeg',3859,2594,2342637,'cbb9988f2f18b9180a1cc0cf5dbb0e3bbf8f2e85d17930cf6ca9ab36fac36303','A towering blue wave curls above three narrow boats, with small Mount Fuji visible in the distance beneath its crest.','cc0','CC0 1.0 — Met Open Access','https://creativecommons.org/publicdomain/zero/1.0/','Katsushika Hokusai','Katsushika Hokusai, Under the Wave off Kanagawa (The Great Wave). The Metropolitan Museum of Art, New York. H. O. Havemeyer Collection, Bequest of Mrs. H. O. Havemeyer, 1929. Image: The Metropolitan Museum of Art, CC0.','2026-09-08T00:00:00Z','2026-09-08T00:00:00Z'),
 ('local','/assets/artworks/monet-bridge.jpg','https://commons.wikimedia.org/wiki/File:Bridge_Over_a_Pond_of_Water_Lilies,_Claude_Monet_1899.jpg','Wikimedia Commons','image/jpeg',1920,2398,2195252,'825ea90549766c45adcbdcd9f0a7552f2d851a6df3b8f725117d9dca96e3259c','A pale green arched bridge crosses a pond filled with water lilies, surrounded by dense trees and their reflections.','public_domain','Public Domain Mark 1.0 / PD-Art','https://creativecommons.org/publicdomain/mark/1.0/','Claude Monet','Claude Monet, Bridge over a Pond of Water Lilies. The Metropolitan Museum of Art, New York. Reproduction: Daniel Schwen, via Wikimedia Commons (PD-Art).','2026-09-08T00:00:00Z','2026-09-08T00:00:00Z'),
 ('local','/assets/artworks/kroyer-evening.jpg','https://commons.wikimedia.org/wiki/File:P.S._Kr%C3%B8yer_-_Summer_evening_on_Skagen%27s_Beach._Anna_Ancher_and_Marie_Kr%C3%B8yer_walking_together._-_Google_Art_Project.jpg','Wikimedia Commons','image/jpeg',1920,1250,491324,'98349099ea13d55b91b2de166189d75f678f79307f38a4fdb34acaeeabe2726f','Two women in pale dresses walk along a beach beside a calm blue sea beneath a softly glowing evening sky.','public_domain','Public Domain Mark 1.0 / PD-Art','https://creativecommons.org/publicdomain/mark/1.0/','P. S. Krøyer','P. S. Krøyer, Summer Evening on Skagen Sønderstrand. Skagens Museum, Skagen. Reproduction via Wikimedia Commons (PD-Art).','2026-09-08T00:00:00Z','2026-09-08T00:00:00Z'),
 ('local','/assets/artworks/anna-blue.jpg','https://commons.wikimedia.org/wiki/File:Anna_Ancher_-_Sunlight_in_the_blue_room_-_Google_Art_Project.jpg','Wikimedia Commons','image/jpeg',1920,2156,1957721,'9b4fbc8cb6e88cb98609329068497ef6c84ac24090ad43a71e4b7c865f58775c','A child in a blue dress sits beside a window in a blue room, while sunlight falls across the wall and patterned floor.','public_domain','Public Domain Mark 1.0 / PD-Art','https://creativecommons.org/publicdomain/mark/1.0/','Anna Ancher','Anna Ancher, Sunlight in the Blue Room. Skagens Museum, Skagen. Reproduction via Wikimedia Commons (PD-Art).','2026-09-08T00:00:00Z','2026-09-08T00:00:00Z'),
 ('local','/assets/artworks/hilma-childhood.jpg','https://commons.wikimedia.org/wiki/File:Hilma_af_Klint_-_The_Ten_Largest_No._2_-_Childhood_-_1907.jpg','Wikimedia Commons','image/jpeg',1337,1800,2189117,'65b5f640496e631e2333522d272a716d56860a1d8805d1d05dcb549bdcc4e7f4','Large orange, pink, and white botanical shapes and looping lines float across a deep blue abstract field.','public_domain','Public Domain Mark 1.0 / PD-Art','https://creativecommons.org/publicdomain/mark/1.0/','Hilma af Klint','Hilma af Klint, The Ten Largest, No. 2, Childhood. Hilma af Klint Foundation, Stockholm. Reproduction via Wikimedia Commons (PD-Art).','2026-09-08T00:00:00Z','2026-09-08T00:00:00Z'),
 ('local','/assets/artworks/munch-scream.png','https://commons.wikimedia.org/wiki/File:The_Scream_by_Edvard_Munch,_1893_-_Nasjonalgalleriet.png','Wikimedia Commons','image/png',1611,2000,6427449,'9cd1a9fa114eb8b98e0f219df727307cf3b7b81f33806d65ac8f19ae60c1568c','A figure on a bridge holds both hands to its head, mouth open, beneath a swirling red-orange sky above a dark blue fjord.','public_domain','Public Domain Mark 1.0 / PD-Art','https://creativecommons.org/publicdomain/mark/1.0/','Edvard Munch','Edvard Munch, The Scream. National Museum, Oslo. Reproduction via Wikimedia Commons (PD-Art).','2026-09-08T00:00:00Z','2026-09-08T00:00:00Z'),
 ('local','/assets/artworks/giotto-lamentation.jpg','https://commons.wikimedia.org/wiki/File:Giotto_-_Scrovegni_-_-36-_-_Lamentation_(The_Mourning_of_Christ)_adj.jpg','Wikimedia Commons','image/jpeg',1000,925,780635,'4a2cd6732b58926d9561f21ac2096ae019076da2e9fc859eb1293fda2f53b6d0','Mourners gather around the body of Christ beneath a sloping rock, while grieving angels fill a deep blue sky.','public_domain','Public Domain Mark 1.0 / PD-Art','https://creativecommons.org/publicdomain/mark/1.0/','Giotto di Bondone','Giotto di Bondone, Lamentation. Scrovegni Chapel, Padua. Reproduction via Wikimedia Commons (PD-Art).','2026-09-08T00:00:00Z','2026-09-08T00:00:00Z'),
 ('local','/assets/artworks/giotto-gate.jpg','https://commons.wikimedia.org/wiki/File:Giotto_-_Scrovegni_-_-06-_-_Meeting_at_the_Golden_Gate.jpg','Wikimedia Commons','image/jpeg',694,676,83735,'ddc339c71cefdd0d9695ad940b20eb7014cb86136a4d4001ce6769e011fb895b','Joachim and Anna embrace before a gateway, with a shepherd to the left and a group of women standing behind them.','public_domain','Public Domain Mark 1.0 / PD-Art','https://creativecommons.org/publicdomain/mark/1.0/','Giotto di Bondone','Giotto di Bondone, Meeting at the Golden Gate. Scrovegni Chapel, Padua. Reproduction via Wikimedia Commons (PD-Art).','2026-09-08T00:00:00Z','2026-09-08T00:00:00Z'),
 ('local','/assets/artworks/giotto-massacre.jpg','https://commons.wikimedia.org/wiki/File:Giotto_-_Scrovegni_-_-21-_-_Massacre_of_the_Innocents.jpg','Wikimedia Commons','image/jpeg',850,852,192425,'27a007195d6b44f2a38bc63233c8f1aa7112f873ac787fb29cc1098ccd66e813','Soldiers seize children as women grieve beneath a raised ruler and a round building, against a blue sky.','public_domain','Public Domain Mark 1.0 / PD-Art','https://creativecommons.org/publicdomain/mark/1.0/','Giotto di Bondone','Giotto di Bondone, Massacre of the Innocents. Scrovegni Chapel, Padua. Reproduction via Wikimedia Commons (PD-Art).','2026-09-08T00:00:00Z','2026-09-08T00:00:00Z'),
 ('local','/assets/artworks/giotto-judgement.jpg','https://commons.wikimedia.org/wiki/File:LastJudgmentGiotto.jpg','Wikimedia Commons','image/jpeg',513,600,326125,'b7883fac4b7c53b82d0927221b80a31143598e6199313332e9093b661d7773e1','Christ sits within a radiant oval at the center of a chapel wall, surrounded by angels, saints, the blessed, and scenes of punishment.','public_domain','Public Domain Mark 1.0 / PD-Art','https://creativecommons.org/publicdomain/mark/1.0/','Giotto di Bondone','Giotto di Bondone, Last Judgement. Scrovegni Chapel, Padua. Reproduction via Wikimedia Commons (PD-Art).','2026-09-08T00:00:00Z','2026-09-08T00:00:00Z')
ON CONFLICT(storage_path) DO NOTHING;

UPDATE artworks aw SET primary_media_id=ma.id,updated_at=now(),revision=aw.revision+1
FROM (VALUES
 ('van-eyck-annunciation','/assets/artworks/van-eyck-annunciation.jpg'),
 ('leonardo-ginevra-de-benci','/assets/artworks/leonardo-ginevra.jpg'),
 ('artemisia-judith-beheading-holofernes','/assets/artworks/artemisia-judith.jpg'),
 ('rembrandt-self-portrait-1660','/assets/artworks/rembrandt-self.jpg'),
 ('hokusai-great-wave','/assets/artworks/hokusai-wave.jpg'),
 ('monet-bridge-over-a-pond-of-water-lilies','/assets/artworks/monet-bridge.jpg'),
 ('kroyer-summer-evening-skagen','/assets/artworks/kroyer-evening.jpg'),
 ('anna-ancher-sunlight-blue-room','/assets/artworks/anna-blue.jpg'),
 ('hilma-ten-largest-childhood-2','/assets/artworks/hilma-childhood.jpg'),
 ('munch-the-scream-1893','/assets/artworks/munch-scream.png'),
 ('giotto-lamentation','/assets/artworks/giotto-lamentation.jpg'),
 ('giotto-meeting-at-the-golden-gate','/assets/artworks/giotto-gate.jpg'),
 ('giotto-massacre-of-the-innocents','/assets/artworks/giotto-massacre.jpg'),
 ('giotto-last-judgement','/assets/artworks/giotto-judgement.jpg')
) seed(slug,path) JOIN media_assets ma ON ma.storage_path=seed.path
WHERE aw.slug=seed.slug AND aw.primary_media_id IS NULL AND aw.status='review' AND aw.revision=1;

INSERT INTO citations(entity_type,entity_id,field_name,source_id,source_url,evidence_note,retrieved_at)
SELECT 'artwork',aw.id,seed.field_name,s.id,seed.url,seed.note,'2026-09-08T00:00:00Z'::timestamptz FROM (VALUES
 ('van-eyck-annunciation','identity','nga-washington','https://www.nga.gov/artworks/46-annunciation','Object identity, displayed date, medium, dimensions, and holding collection checked against this institutional record.'),
 ('van-eyck-annunciation','date','nga-washington','https://www.nga.gov/artworks/46-annunciation','Object identity, displayed date, medium, dimensions, and holding collection checked against this institutional record.'),
 ('van-eyck-annunciation','medium','nga-washington','https://www.nga.gov/artworks/46-annunciation','Object identity, displayed date, medium, dimensions, and holding collection checked against this institutional record.'),
 ('van-eyck-annunciation','dimensions','nga-washington','https://www.nga.gov/artworks/46-annunciation','Object identity, displayed date, medium, dimensions, and holding collection checked against this institutional record.'),
 ('van-eyck-annunciation','current_location','nga-washington','https://www.nga.gov/artworks/46-annunciation','Object identity, displayed date, medium, dimensions, and holding collection checked against this institutional record.'),
 ('van-eyck-annunciation','image_rights','wikimedia-commons','https://commons.wikimedia.org/wiki/File:Annunciation_-_Jan_van_Eyck_-_1434_-_NG_Wash_DC.jpg','The file page marks this reproduction as public domain / PD-Art. Image identity matched to the cited institutional object record.'),
 ('leonardo-ginevra-de-benci','identity','nga-washington','https://www.nga.gov/artworks/50724-ginevra-de-benci-obverse','Object identity, displayed date, medium, dimensions, and holding collection checked against this institutional record.'),
 ('leonardo-ginevra-de-benci','date','nga-washington','https://www.nga.gov/artworks/50724-ginevra-de-benci-obverse','Object identity, displayed date, medium, dimensions, and holding collection checked against this institutional record.'),
 ('leonardo-ginevra-de-benci','medium','nga-washington','https://www.nga.gov/artworks/50724-ginevra-de-benci-obverse','Object identity, displayed date, medium, dimensions, and holding collection checked against this institutional record.'),
 ('leonardo-ginevra-de-benci','dimensions','nga-washington','https://www.nga.gov/artworks/50724-ginevra-de-benci-obverse','Object identity, displayed date, medium, dimensions, and holding collection checked against this institutional record.'),
 ('leonardo-ginevra-de-benci','current_location','nga-washington','https://www.nga.gov/artworks/50724-ginevra-de-benci-obverse','Object identity, displayed date, medium, dimensions, and holding collection checked against this institutional record.'),
 ('leonardo-ginevra-de-benci','image_rights','wikimedia-commons','https://commons.wikimedia.org/wiki/File:Leonardo_da_Vinci_-_Ginevra_de%27_Benci_-_Google_Art_Project.jpg','The file page marks this reproduction as public domain / PD-Art. Image identity matched to the cited institutional object record.'),
 ('artemisia-judith-beheading-holofernes','identity','uffizi','https://www.uffizi.it/en/artworks/judith-beheading-holofernes','The Uffizi object record dates this version to about 1620 and states it was completed in Rome. Commons uses a broader 1614–1620 range.'),
 ('artemisia-judith-beheading-holofernes','date','uffizi','https://www.uffizi.it/en/artworks/judith-beheading-holofernes','The Uffizi object record dates this version to about 1620 and states it was completed in Rome. Commons uses a broader 1614–1620 range.'),
 ('artemisia-judith-beheading-holofernes','medium','uffizi','https://www.uffizi.it/en/artworks/judith-beheading-holofernes','The Uffizi object record dates this version to about 1620 and states it was completed in Rome. Commons uses a broader 1614–1620 range.'),
 ('artemisia-judith-beheading-holofernes','dimensions','uffizi','https://www.uffizi.it/en/artworks/judith-beheading-holofernes','The Uffizi object record dates this version to about 1620 and states it was completed in Rome. Commons uses a broader 1614–1620 range.'),
 ('artemisia-judith-beheading-holofernes','current_location','uffizi','https://www.uffizi.it/en/artworks/judith-beheading-holofernes','The Uffizi object record dates this version to about 1620 and states it was completed in Rome. Commons uses a broader 1614–1620 range.'),
 ('artemisia-judith-beheading-holofernes','creation_place','uffizi','https://www.uffizi.it/en/artworks/judith-beheading-holofernes','The Uffizi object record dates this version to about 1620 and states it was completed in Rome. Commons uses a broader 1614–1620 range.'),
 ('artemisia-judith-beheading-holofernes','image_rights','wikimedia-commons','https://commons.wikimedia.org/wiki/File:Artemisia_Gentileschi_-_Giuditta_decapita_Oloferne_-_Google_Art_Project-Adjust.jpg','The file page marks this reproduction as public domain / PD-Art. Image identity matched to the cited institutional object record.'),
 ('rembrandt-self-portrait-1660','identity','met-museum','https://www.metmuseum.org/art/collection/search/437397','Object identity, displayed date, medium, dimensions, and holding collection checked against this institutional record.'),
 ('rembrandt-self-portrait-1660','date','met-museum','https://www.metmuseum.org/art/collection/search/437397','Object identity, displayed date, medium, dimensions, and holding collection checked against this institutional record.'),
 ('rembrandt-self-portrait-1660','medium','met-museum','https://www.metmuseum.org/art/collection/search/437397','Object identity, displayed date, medium, dimensions, and holding collection checked against this institutional record.'),
 ('rembrandt-self-portrait-1660','dimensions','met-museum','https://www.metmuseum.org/art/collection/search/437397','Object identity, displayed date, medium, dimensions, and holding collection checked against this institutional record.'),
 ('rembrandt-self-portrait-1660','current_location','met-museum','https://www.metmuseum.org/art/collection/search/437397','Object identity, displayed date, medium, dimensions, and holding collection checked against this institutional record.'),
 ('rembrandt-self-portrait-1660','image_rights','met-museum','https://www.metmuseum.org/art/collection/search/437397','Museum object API marks this specific image public domain; downloaded under Met Open Access (CC0).'),
 ('hokusai-great-wave','identity','met-museum','https://www.metmuseum.org/art/collection/search/45434','Metadata and image refer to the Met impression JP1847, not a later reprint. Displayed approximate dates follow the museum catalogue, not the API’s broader indexing bounds.'),
 ('hokusai-great-wave','date','met-museum','https://www.metmuseum.org/art/collection/search/45434','Metadata and image refer to the Met impression JP1847, not a later reprint. Displayed approximate dates follow the museum catalogue, not the API’s broader indexing bounds.'),
 ('hokusai-great-wave','medium','met-museum','https://www.metmuseum.org/art/collection/search/45434','Metadata and image refer to the Met impression JP1847, not a later reprint. Displayed approximate dates follow the museum catalogue, not the API’s broader indexing bounds.'),
 ('hokusai-great-wave','dimensions','met-museum','https://www.metmuseum.org/art/collection/search/45434','Metadata and image refer to the Met impression JP1847, not a later reprint. Displayed approximate dates follow the museum catalogue, not the API’s broader indexing bounds.'),
 ('hokusai-great-wave','current_location','met-museum','https://www.metmuseum.org/art/collection/search/45434','Metadata and image refer to the Met impression JP1847, not a later reprint. Displayed approximate dates follow the museum catalogue, not the API’s broader indexing bounds.'),
 ('hokusai-great-wave','image_rights','met-museum','https://www.metmuseum.org/art/collection/search/45434','Museum object API marks this specific image public domain; downloaded under Met Open Access (CC0).'),
 ('monet-bridge-over-a-pond-of-water-lilies','identity','met-museum','https://www.metmuseum.org/art/collection/search/437127','Object identity, displayed date, medium, dimensions, and holding collection checked against this institutional record.'),
 ('monet-bridge-over-a-pond-of-water-lilies','date','met-museum','https://www.metmuseum.org/art/collection/search/437127','Object identity, displayed date, medium, dimensions, and holding collection checked against this institutional record.'),
 ('monet-bridge-over-a-pond-of-water-lilies','medium','met-museum','https://www.metmuseum.org/art/collection/search/437127','Object identity, displayed date, medium, dimensions, and holding collection checked against this institutional record.'),
 ('monet-bridge-over-a-pond-of-water-lilies','dimensions','met-museum','https://www.metmuseum.org/art/collection/search/437127','Object identity, displayed date, medium, dimensions, and holding collection checked against this institutional record.'),
 ('monet-bridge-over-a-pond-of-water-lilies','current_location','met-museum','https://www.metmuseum.org/art/collection/search/437127','Object identity, displayed date, medium, dimensions, and holding collection checked against this institutional record.'),
 ('monet-bridge-over-a-pond-of-water-lilies','creation_place','met-museum','https://www.metmuseum.org/art/collection/search/437127','Object identity, displayed date, medium, dimensions, and holding collection checked against this institutional record.'),
 ('monet-bridge-over-a-pond-of-water-lilies','image_rights','wikimedia-commons','https://commons.wikimedia.org/wiki/File:Bridge_Over_a_Pond_of_Water_Lilies,_Claude_Monet_1899.jpg','The file page marks this reproduction as public domain / PD-Art. Image identity matched to the cited institutional object record.'),
 ('kroyer-summer-evening-skagen','identity','skagens-museum','https://artsandculture.google.com/asset/summer-evening-on-skagen-s%C3%B8nderstrand-peder-severin-kr%C3%B8yer/_gEOHIMEsC_EQg','Object identity, displayed date, medium, dimensions, and holding collection checked against this institutional record.'),
 ('kroyer-summer-evening-skagen','date','skagens-museum','https://artsandculture.google.com/asset/summer-evening-on-skagen-s%C3%B8nderstrand-peder-severin-kr%C3%B8yer/_gEOHIMEsC_EQg','Object identity, displayed date, medium, dimensions, and holding collection checked against this institutional record.'),
 ('kroyer-summer-evening-skagen','medium','skagens-museum','https://artsandculture.google.com/asset/summer-evening-on-skagen-s%C3%B8nderstrand-peder-severin-kr%C3%B8yer/_gEOHIMEsC_EQg','Object identity, displayed date, medium, dimensions, and holding collection checked against this institutional record.'),
 ('kroyer-summer-evening-skagen','dimensions','skagens-museum','https://artsandculture.google.com/asset/summer-evening-on-skagen-s%C3%B8nderstrand-peder-severin-kr%C3%B8yer/_gEOHIMEsC_EQg','Object identity, displayed date, medium, dimensions, and holding collection checked against this institutional record.'),
 ('kroyer-summer-evening-skagen','current_location','skagens-museum','https://artsandculture.google.com/asset/summer-evening-on-skagen-s%C3%B8nderstrand-peder-severin-kr%C3%B8yer/_gEOHIMEsC_EQg','Object identity, displayed date, medium, dimensions, and holding collection checked against this institutional record.'),
 ('kroyer-summer-evening-skagen','image_rights','wikimedia-commons','https://commons.wikimedia.org/wiki/File:P.S._Kr%C3%B8yer_-_Summer_evening_on_Skagen%27s_Beach._Anna_Ancher_and_Marie_Kr%C3%B8yer_walking_together._-_Google_Art_Project.jpg','The file page marks this reproduction as public domain / PD-Art. Image identity matched to the cited institutional object record.'),
 ('anna-ancher-sunlight-blue-room','identity','skagens-museum','https://artsandculture.google.com/asset/sunlight-in-the-blue-room/mwE3yo7ZLwPcHA','Object identity, displayed date, medium, dimensions, and holding collection checked against this institutional record.'),
 ('anna-ancher-sunlight-blue-room','date','skagens-museum','https://artsandculture.google.com/asset/sunlight-in-the-blue-room/mwE3yo7ZLwPcHA','Object identity, displayed date, medium, dimensions, and holding collection checked against this institutional record.'),
 ('anna-ancher-sunlight-blue-room','medium','skagens-museum','https://artsandculture.google.com/asset/sunlight-in-the-blue-room/mwE3yo7ZLwPcHA','Object identity, displayed date, medium, dimensions, and holding collection checked against this institutional record.'),
 ('anna-ancher-sunlight-blue-room','dimensions','skagens-museum','https://artsandculture.google.com/asset/sunlight-in-the-blue-room/mwE3yo7ZLwPcHA','Object identity, displayed date, medium, dimensions, and holding collection checked against this institutional record.'),
 ('anna-ancher-sunlight-blue-room','current_location','skagens-museum','https://artsandculture.google.com/asset/sunlight-in-the-blue-room/mwE3yo7ZLwPcHA','Object identity, displayed date, medium, dimensions, and holding collection checked against this institutional record.'),
 ('anna-ancher-sunlight-blue-room','image_rights','wikimedia-commons','https://commons.wikimedia.org/wiki/File:Anna_Ancher_-_Sunlight_in_the_blue_room_-_Google_Art_Project.jpg','The file page marks this reproduction as public domain / PD-Art. Image identity matched to the cited institutional object record.'),
 ('hilma-ten-largest-childhood-2','identity','guggenheim','https://www.guggenheim.org/wp-content/uploads/2018/10/guggenheim-education-hilma-af-klint-teacher-resource-unit-10-5.pdf','Dimensions and medium follow the Guggenheim teacher resource, HAK103. The Commons structured dimensions differ; that discrepancy remains documented for editorial review. Collection refers to the Foundation, not a current exhibition venue.'),
 ('hilma-ten-largest-childhood-2','date','guggenheim','https://www.guggenheim.org/wp-content/uploads/2018/10/guggenheim-education-hilma-af-klint-teacher-resource-unit-10-5.pdf','Dimensions and medium follow the Guggenheim teacher resource, HAK103. The Commons structured dimensions differ; that discrepancy remains documented for editorial review. Collection refers to the Foundation, not a current exhibition venue.'),
 ('hilma-ten-largest-childhood-2','medium','guggenheim','https://www.guggenheim.org/wp-content/uploads/2018/10/guggenheim-education-hilma-af-klint-teacher-resource-unit-10-5.pdf','Dimensions and medium follow the Guggenheim teacher resource, HAK103. The Commons structured dimensions differ; that discrepancy remains documented for editorial review. Collection refers to the Foundation, not a current exhibition venue.'),
 ('hilma-ten-largest-childhood-2','dimensions','guggenheim','https://www.guggenheim.org/wp-content/uploads/2018/10/guggenheim-education-hilma-af-klint-teacher-resource-unit-10-5.pdf','Dimensions and medium follow the Guggenheim teacher resource, HAK103. The Commons structured dimensions differ; that discrepancy remains documented for editorial review. Collection refers to the Foundation, not a current exhibition venue.'),
 ('hilma-ten-largest-childhood-2','current_location','guggenheim','https://www.guggenheim.org/wp-content/uploads/2018/10/guggenheim-education-hilma-af-klint-teacher-resource-unit-10-5.pdf','Dimensions and medium follow the Guggenheim teacher resource, HAK103. The Commons structured dimensions differ; that discrepancy remains documented for editorial review. Collection refers to the Foundation, not a current exhibition venue.'),
 ('hilma-ten-largest-childhood-2','image_rights','wikimedia-commons','https://commons.wikimedia.org/wiki/File:Hilma_af_Klint_-_The_Ten_Largest_No._2_-_Childhood_-_1907.jpg','The file page marks this reproduction as public domain / PD-Art. Image identity matched to the cited institutional object record.'),
 ('munch-the-scream-1893','identity','nasjonalmuseet','https://www.nasjonalmuseet.no/en/collection/object/NG.M.00939','Object identity, displayed date, medium, dimensions, and holding collection checked against this institutional record.'),
 ('munch-the-scream-1893','date','nasjonalmuseet','https://www.nasjonalmuseet.no/en/collection/object/NG.M.00939','Object identity, displayed date, medium, dimensions, and holding collection checked against this institutional record.'),
 ('munch-the-scream-1893','medium','nasjonalmuseet','https://www.nasjonalmuseet.no/en/collection/object/NG.M.00939','Object identity, displayed date, medium, dimensions, and holding collection checked against this institutional record.'),
 ('munch-the-scream-1893','dimensions','nasjonalmuseet','https://www.nasjonalmuseet.no/en/collection/object/NG.M.00939','Object identity, displayed date, medium, dimensions, and holding collection checked against this institutional record.'),
 ('munch-the-scream-1893','current_location','nasjonalmuseet','https://www.nasjonalmuseet.no/en/collection/object/NG.M.00939','Object identity, displayed date, medium, dimensions, and holding collection checked against this institutional record.'),
 ('munch-the-scream-1893','image_rights','wikimedia-commons','https://commons.wikimedia.org/wiki/File:The_Scream_by_Edvard_Munch,_1893_-_Nasjonalgalleriet.png','The file page marks this reproduction as public domain / PD-Art. Image identity matched to the cited institutional object record.'),
 ('giotto-lamentation','image_rights','wikimedia-commons','https://commons.wikimedia.org/wiki/File:Giotto_-_Scrovegni_-_-36-_-_Lamentation_(The_Mourning_of_Christ)_adj.jpg','The file page marks this reproduction as public domain / PD-Art. Displayed dates follow the chapel’s 1303–1305 cycle date. Some image records use 1304–1306 or 1306; panel chronology remains under review.'),
 ('giotto-meeting-at-the-golden-gate','image_rights','wikimedia-commons','https://commons.wikimedia.org/wiki/File:Giotto_-_Scrovegni_-_-06-_-_Meeting_at_the_Golden_Gate.jpg','The file page marks this reproduction as public domain / PD-Art. Displayed dates follow the chapel’s 1303–1305 cycle date. Some image records use 1304–1306 or 1306; panel chronology remains under review.'),
 ('giotto-massacre-of-the-innocents','image_rights','wikimedia-commons','https://commons.wikimedia.org/wiki/File:Giotto_-_Scrovegni_-_-21-_-_Massacre_of_the_Innocents.jpg','The file page marks this reproduction as public domain / PD-Art. Displayed dates follow the chapel’s 1303–1305 cycle date. Some image records use 1304–1306 or 1306; panel chronology remains under review.'),
 ('giotto-last-judgement','image_rights','wikimedia-commons','https://commons.wikimedia.org/wiki/File:LastJudgmentGiotto.jpg','The file page marks this reproduction as public domain / PD-Art. Displayed dates follow the chapel’s 1303–1305 cycle date. Some image records use 1304–1306 or 1306; panel chronology remains under review.')
) seed(slug,field_name,source_slug,url,note)
JOIN artworks aw ON aw.slug=seed.slug JOIN sources s ON s.slug=seed.source_slug
WHERE NOT EXISTS(SELECT 1 FROM citations c WHERE c.entity_type='artwork' AND c.entity_id=aw.id AND c.field_name=seed.field_name AND c.source_url=seed.url);
