import {expect,test,type Page,type Locator} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
async function open(page:Page,type:string){await page.goto('/all');await page.getByRole('button',{name:'+ Add',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Add a layer'});await dialog.getByRole('button',{name:type,exact:true}).click();return dialog}
async function choose(dialog:Locator,label:string,value:string){await dialog.locator('summary').filter({hasText:label}).click();await dialog.getByRole('group',{name:label,exact:true}).getByRole('checkbox',{name:value,exact:true}).check();await dialog.locator('details[open]').getByRole('button',{name:'Done',exact:true}).click()}
async function count(dialog:Locator){await expect(dialog.getByText('Finding entries…',{exact:true})).toHaveCount(0,{timeout:20000});return Number((await dialog.getByText(/^[\d,]+ matching entries$/).textContent())!.replace(/[^\d]/g,''))}
async function ready(page:Page){await expect(page.locator('.all-explorer .timeline-stage')).toHaveAttribute('aria-busy','false',{timeout:20000});await expect(page.locator('.all-explorer').getByRole('alert')).toHaveCount(0)}
test('Russian books retain the native count and filters without an Add catalogue',async({page,request})=>{
 const dialog=await open(page,'Books');await expect(dialog.getByRole('checkbox',{name:'Top 100 books',exact:true})).toBeChecked();
 for(const name of ['Authors','Regions','Countries','Languages'])await expect(dialog.locator('summary').filter({hasText:name})).toBeVisible();
 await dialog.getByRole('checkbox',{name:'Top 100 books',exact:true}).uncheck();await choose(dialog,'Languages','Russian');
 const native=await (await request.get('/api/backend/v1/books?top100=false&language=Q7737')).json();expect(await count(dialog)).toBe(native.total-native.undatedTotal);
 await expect(dialog.locator('.atlas-picker-list,.atlas-picker-pages')).toHaveCount(0);
 await dialog.getByRole('button',{name:'Add books layer',exact:true}).click();await ready(page);await expect(page).toHaveURL(/book_language=Q7737/);await expect(page).toHaveURL(/book_top100=false/);
 await expect(page.locator('.all-lane>header>span')).toHaveText(String(native.total-native.undatedTotal));await page.reload();await ready(page);await expect(page.locator('.all-lane>header>span')).toHaveText(String(native.total-native.undatedTotal));
 await page.getByRole('button',{name:'+ Add',exact:true}).click();await dialog.getByRole('button',{name:'Books',exact:true}).click();await expect(dialog.getByRole('checkbox',{name:'Top 100 books',exact:true})).not.toBeChecked();await expect(dialog.locator('summary').filter({hasText:'Languages'})).toContainText('Russian');
 await dialog.getByRole('button',{name:'Remove Russian filter',exact:true}).click();await dialog.locator('summary').filter({hasText:'Authors'}).click();await dialog.getByLabel('Search authors',{exact:true}).fill('Tolstoy');await dialog.getByRole('checkbox',{name:'Leo Tolstoy',exact:true}).check();await dialog.locator('details[open]').getByRole('button',{name:'Done',exact:true}).click();await dialog.getByRole('button',{name:'Update books layer',exact:true}).click();await ready(page);await expect(page).toHaveURL(/book_author=Leo/);await expect(page).not.toHaveURL(/book_language=/);
});
test('event topics and regions combine; switching types keeps separate choices',async({page,request})=>{
 const dialog=await open(page,'Events');await dialog.getByRole('checkbox',{name:'Top 100 events',exact:true}).uncheck();await choose(dialog,'Topics','Conflict');await choose(dialog,'Regions','Eastern Europe');
 const native=await (await request.get('/api/backend/v1/events?top100=false&topic=Conflict&region=Eastern+Europe')).json();expect(await count(dialog)).toBe(native.total-native.undatedTotal);
 await dialog.getByRole('button',{name:'Books',exact:true}).click();await expect(dialog.getByRole('checkbox',{name:'Top 100 books',exact:true})).toBeChecked();await expect(dialog.locator('summary').filter({hasText:'Regions'})).toContainText('All regions');
 await dialog.getByRole('button',{name:'Events',exact:true}).click();await expect(dialog.locator('summary').filter({hasText:'Topics'})).toContainText('Conflict');await expect(dialog.locator('summary').filter({hasText:'Regions'})).toContainText('Eastern Europe');
 await dialog.getByRole('button',{name:'Add events layer',exact:true}).click();await ready(page);await expect(page.locator('.all-lane>header>span')).toHaveText(String(native.total-native.undatedTotal));await page.reload();await ready(page);await expect(page).toHaveURL(/event_topic=Conflict/);
});
test('art offers native painter, movement, geography and work type controls',async({page})=>{
 const dialog=await open(page,'Artworks');for(const name of ['Painters','Movements','Regions','Countries','Work types'])await expect(dialog.locator('summary').filter({hasText:name})).toBeVisible();
 await expect(dialog.getByRole('checkbox',{name:'Top 100 painters',exact:true})).toBeChecked();await expect(dialog.getByRole('checkbox',{name:'Women artists',exact:true})).not.toBeChecked();
 await dialog.locator('summary').filter({hasText:'Painters'}).click();await dialog.getByLabel('Search painters',{exact:true}).fill('Monet');await dialog.getByRole('checkbox',{name:'Claude Monet',exact:true}).check();await dialog.locator('details[open]').getByRole('button',{name:'Done',exact:true}).click();await choose(dialog,'Work types','painting');
 expect(await count(dialog)).toBeGreaterThan(0);await expect(dialog.locator('.atlas-picker-list,.atlas-picker-pages')).toHaveCount(0);await dialog.getByRole('button',{name:'Add artworks layer',exact:true}).click();await ready(page);await expect(page).toHaveURL(/artwork_painter=claude-monet/);await expect(page).toHaveURL(/artwork_work_type=painting/);await page.reload();await ready(page);
});
test('women, clear, reset, empty results and cancelling a layer update',async({page})=>{
 const dialog=await open(page,'Books');await dialog.getByRole('checkbox',{name:'Women authors',exact:true}).check();await expect(dialog.getByRole('button',{name:'Remove Women authors filter',exact:true})).toBeVisible();await dialog.getByRole('button',{name:'Clear filters',exact:true}).click();await expect(dialog.getByRole('checkbox',{name:'Women authors',exact:true})).not.toBeChecked();await expect(dialog.getByRole('checkbox',{name:'Top 100 books',exact:true})).not.toBeChecked();
 await dialog.getByLabel('Find a book or author',{exact:true}).fill('zzznosuchentryzzz');await expect(dialog.getByText('No matching entries.',{exact:false})).toBeVisible();await expect(dialog.getByRole('button',{name:'Add books layer',exact:true})).toBeDisabled();await dialog.getByRole('button',{name:'Reset view',exact:true}).click();await expect(dialog.getByRole('checkbox',{name:'Top 100 books',exact:true})).toBeChecked();await choose(dialog,'Languages','Russian');await dialog.getByRole('button',{name:'Add books layer',exact:true}).click();await ready(page);
 const before=await page.locator('.all-lane>header>span').textContent();await page.getByRole('button',{name:'+ Add',exact:true}).click();await dialog.getByRole('button',{name:'Books',exact:true}).click();await dialog.getByRole('button',{name:'Clear filters',exact:true}).click();await dialog.getByLabel('Find a book or author',{exact:true}).fill('Metamorphosis');expect(await count(dialog)).toBeGreaterThan(0);await expect(dialog.locator('.atlas-picker-list,.atlas-picker-pages')).toHaveCount(0);await dialog.getByRole('button',{name:'Close content picker',exact:true}).click();await ready(page);await expect(page.locator('.all-lane>header>span')).toHaveText(before!);await expect(page).toHaveURL(/book_language=Q7737/);await expect(page).not.toHaveURL(/book_q=|pick_/);

});
for(const width of [1440,390,320])test(`picker fits and is accessible at ${width}`,async({page},info)=>{
 await page.setViewportSize({width,height:900});const dialog=await open(page,'Books');if(width<760)await dialog.getByRole('button',{name:'Filters',exact:true}).click();await choose(dialog,'Languages','Russian');await count(dialog);await expect(dialog.locator('.atlas-picker-list,.atlas-picker-pages')).toHaveCount(0);
 expect((await new AxeBuilder({page}).include('dialog').withTags(['wcag2a','wcag2aa','wcag21aa']).analyze()).violations).toEqual([]);
 expect(await dialog.evaluate(el=>el.scrollWidth<=el.clientWidth)).toBe(true);await dialog.locator('summary').filter({hasText:'Languages'}).click();await dialog.getByLabel('Search languages',{exact:true}).focus();await page.keyboard.press('Escape');await expect(dialog).toBeVisible();await expect(dialog.locator('details[open]')).toHaveCount(0);await expect(dialog.locator('summary').filter({hasText:'Languages'})).toBeFocused();await dialog.evaluate(el=>el.scrollTop=0);await page.screenshot({path:info.outputPath(`add-filters-${width}.png`)});
});
