import { e2eEditorToken } from "./editor-token";
import { test, expect } from "@playwright/test";
test("painter drawer is right-aligned, scrolls independently, and adapts to phones", async ({ page }) => {
  await page.goto("/");
  await expect(page.getByRole("status")).toContainText("11 painters");
  const node = page.locator(".artist-mark").first();
  await node.click();
  const drawer = page.getByRole("dialog", { name: "Painter details" });
  await expect(drawer.getByRole("heading", { name: "Giotto di Bondone" })).toBeVisible();
  await expect(drawer.locator(".dialog-toolbar")).toContainText("Painter 1 of 11");
  const bounds = await drawer.boundingBox();
  expect(bounds!.x).toBeGreaterThan(720);
  expect(bounds!.x + bounds!.width).toBeCloseTo(1440, 0);
  expect(bounds!.y).toBe(0);
  expect(bounds!.height).toBe(1000);
  await expect(drawer.locator(".work-row")).toHaveCount(5);
  await expect.poll(() => drawer.locator(".work-row img").first().evaluate(element => (element as HTMLImageElement).naturalWidth)).toBeGreaterThan(0);
  await page.screenshot({ path: "../../docs/screenshots/painter-drawer-desktop.png" });
  await drawer.getByRole("button", { name: "Close painter details" }).focus();
  await page.keyboard.press("Shift+Tab");
  expect(await drawer.evaluate(element => element.contains(document.activeElement))).toBe(true);
  await drawer.getByRole("button", { name: /The Arrest of Christ/ }).click();
  await expect(drawer.locator(".artwork-details h3")).toContainText("Kiss of Judas");
  await expect(drawer.getByRole("heading", { name: "Artwork record" })).toBeInViewport();
  await expect.poll(async () => (await drawer.locator(".artwork-panel").boundingBox())!.y).toBeCloseTo(80, 0);
  await expect(drawer.getByRole("button", { name: "Close painter details" })).toBeInViewport();
  expect(await page.evaluate(() => window.scrollY)).toBe(0);
  await expect(drawer.locator(".artwork-details img")).toHaveJSProperty("complete", true);
  await page.screenshot({ path: "../../docs/screenshots/painter-drawer-artwork.png" });
  await page.mouse.click(50, 200);
  await expect(drawer).toHaveCount(0);
  await expect(node).toBeFocused();
  await page.setViewportSize({ width: 390, height: 844 });
  await node.click();
  await expect(drawer.getByRole("heading", { name: "Giotto di Bondone" })).toBeVisible();
  const mobileBounds = await drawer.boundingBox();
  expect(mobileBounds!.x).toBe(0);
  expect(mobileBounds!.width).toBe(390);
  expect(mobileBounds!.height).toBe(844);
  expect(await drawer.evaluate(element => element.scrollWidth <= element.clientWidth)).toBe(true);
  await page.screenshot({ path: "../../docs/screenshots/painter-drawer-mobile.png" });
  await page.setViewportSize({ width: 320, height: 844 });
  expect(await drawer.evaluate(element => element.scrollWidth <= element.clientWidth)).toBe(true);
  await page.keyboard.press("Escape");
  await expect(drawer).toHaveCount(0);
  await expect(node).toBeFocused();
});
test("compact dark timeline contains working focus controls", async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.goto("/");
  await expect(page.getByRole("status")).toContainText("11 painters");
  const panel = page.locator(".timeline-dark");
  await expect(panel.getByRole("heading", { name: "Focus the timeline" })).toBeVisible();
  await expect(panel.getByLabel("Timeline start handle")).toBeVisible();
  await expect(panel.getByLabel("Timeline end handle")).toBeVisible();
  const bounds = await panel.boundingBox();
  expect(bounds!.x).toBe(0);
  expect(bounds!.width).toBe(1440);
  expect(bounds!.y + bounds!.height).toBeLessThan(900);
  await page.screenshot({ path: "../../docs/screenshots/timeline-compact.png" });
  await panel.getByRole("button", { name: "Century", exact: true }).click();
  await panel.getByLabel("Timeline start handle").focus();
  await page.keyboard.press("ArrowRight");
  await expect(panel.getByLabel("Start year", { exact: true })).toHaveValue("1501");
  await panel.getByLabel("Timeline end handle").focus();
  await page.keyboard.press("ArrowLeft");
  await expect(panel.getByLabel("End year", { exact: true })).toHaveValue("1599");
  await panel.getByRole("button", { name: "Move selected time range" }).focus();
  await page.keyboard.press("ArrowRight");
  await expect(panel.getByLabel("Start year", { exact: true })).toHaveValue("1511");
  await expect(panel.getByLabel("End year", { exact: true })).toHaveValue("1609");
  const selection = await panel.locator(".range-window").boundingBox();
  await page.mouse.move(selection!.x + selection!.width / 2, selection!.y + selection!.height / 2);
  await page.mouse.down();
  await page.mouse.move(selection!.x + selection!.width / 2 + 60, selection!.y + selection!.height / 2, { steps: 5 });
  await page.mouse.up();
  const from = Number(await panel.getByLabel("Start year", { exact: true }).inputValue());
  const to = Number(await panel.getByLabel("End year", { exact: true }).inputValue());
  expect(from).toBeGreaterThan(1511);
  expect(to - from).toBe(98);
  await page.getByRole("button", { name: "Reset view", exact: true }).click();
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(panel.getByRole("heading", { name: "Focus the timeline" })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  for (const width of [320, 768, 1024]) {
    await page.setViewportSize({ width, height: 900 });
    await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  }
});
test("timeline, filters, URL selection, keyboard dismissal and history", async ({ page }) => {
  const errors: string[] = [];
  page.on("pageerror", error => errors.push(error.message));
  await page.goto("/");
  await expect(page.getByRole("status")).toContainText("11 painters");
  await expect(page.getByRole("heading", { name: "No painters in this view" })).toHaveCount(0);
  await page.keyboard.press("Tab");
  await expect(page.getByRole("link", { name: "Skip to content" })).toBeFocused();
  await expect(page.getByRole("link", { name: "Skip to content" })).toHaveCSS("clip-path", "none");
  await page.keyboard.press("Tab");
  await page.screenshot({ path: "../../docs/screenshots/timeline-desktop.png", fullPage: true });
  await page.getByRole("button", { name: "Century", exact: true }).click();
  await expect(page.getByLabel("Start year", { exact: true })).toHaveValue("1500");
  await expect(page.getByLabel("End year", { exact: true })).toHaveValue("1600");
  await page.getByRole("button", { name: "Reset view", exact: true }).click();
  await page.getByRole("searchbox").fill("Giotto");
  await expect(page.getByRole("status")).toContainText("1 painter");
  const node = page.locator(".artist-mark").first();
  await node.click();
  await expect(page.getByRole("dialog")).toBeVisible();
  await expect(page).toHaveURL(/artist=giotto/);
  await expect(page.getByRole("dialog").getByRole("heading", { name: "Giotto di Bondone" })).toBeVisible();
  await page.getByRole("dialog").getByRole("button", { name: /The Arrest of Christ/ }).click();
  await expect(page.locator(".artwork-details h3")).toContainText("Kiss of Judas");
  await page.getByRole("button", { name: "Next work", exact: true }).click();
  await expect(page.locator(".artwork-details h3")).toContainText("Meeting at the Golden Gate");
  await page.keyboard.press("Escape");
  await expect(page.getByRole("dialog")).toHaveCount(0);
  await expect(node).toBeFocused();
  await page.goBack();
  await expect(page.getByRole("dialog")).toBeVisible();
  expect(errors).toEqual([]);
});
test("artist page, artwork deep link and mobile layout", async ({ page }) => {
  await page.goto("/artists/giotto");
  await expect(page.getByRole("heading", { name: "Giotto di Bondone" })).toBeVisible();
  await expect(page.locator(".work-card")).toHaveCount(5);
  await page.screenshot({ path: "../../docs/screenshots/artist-desktop.png", fullPage: true });
  await page.getByRole("button", { name: /The Arrest of Christ/ }).click();
  await expect(page.locator(".artwork-details img")).toBeVisible();
  const workId = new URL(page.url()).searchParams.get("work");
  await page.goto(`/artists/giotto/works/${workId}`);
  await expect(page.locator(".artwork-details h3")).toContainText("Kiss of Judas");
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: "../../docs/screenshots/artist-mobile.png", fullPage: true });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.goto("/");
  await expect(page.getByRole("status")).toContainText("11 painters");
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: "../../docs/screenshots/timeline-mobile.png", fullPage: true });
});
test("bookmark normalization, empty state and recovery", async ({ page }) => {
  await page.goto("/?start=2000&end=1100&status=review");
  await expect(page.getByRole("status")).toContainText("11 painters");
  await expect(page.getByLabel("Start year", { exact: true })).toHaveValue("1100");
  await page.getByRole("searchbox").fill("no-such-painter-xyz");
  await expect(page.getByRole("heading", { name: "No painters in this view" })).toBeVisible();
  await page.locator(".state-panel").getByRole("button", { name: "Remove filters" }).click();
  await expect(page.getByRole("status")).toContainText("11 painters");
  await expect(page.getByRole("heading", { name: "No painters in this view" })).toHaveCount(0);
});
test("catalogue loads, preserves rejected edits, and shows publication issues", async ({ page }) => {
  await page.goto("/catalogue");
  await expect(page.getByRole("link", { name: "Giotto di Bondone" })).toBeVisible();
  await page.getByLabel("Editor token", { exact: true }).fill(e2eEditorToken());
  const row = page.getByRole("row").filter({ has: page.getByRole("link", { name: "Giotto di Bondone" }) });
  await row.getByRole("button", { name: "Check", exact: true }).click();
  await expect(page.locator(".validation-panel")).toContainText("influences");
  await expect(page.getByRole("button", { name: "Publish record" })).toHaveCount(0);
  await row.getByRole("button", { name: "Edit", exact: true }).click();
  await expect(page.getByLabel("Display name", { exact: true })).toHaveValue("Giotto di Bondone");
  await page.getByLabel("Start year", { exact: true }).fill("1990");
  await page.getByRole("button", { name: "Save painter" }).click();
  await expect(page.getByRole("form").getByRole("alert")).toContainText("Life or activity dates");
  await expect(page.getByLabel("Start year", { exact: true })).toHaveValue("1990");
  await page.screenshot({ path: "../../docs/screenshots/catalogue-desktop.png", fullPage: true });
});
