import { expect, test } from '@playwright/test';

for (const width of [1440, 390]) test(`women’s rights connects global history and Japan at ${width}`, async ({ page }, info) => {
  test.setTimeout(60000);
  await page.setViewportSize({ width, height: 1000 });
  const writes: string[] = [];
  page.on('request', r => { if (r.url().includes('/api/') && r.method() !== 'GET') writes.push(r.url()); });
  await page.goto('/all');
  const start = page.getByRole('button', { name: 'Women’s rights', exact: true });
  await expect(start).toContainText('Global history, including Japan');
  await start.click();
  await expect(page.locator('.timeline-stage')).toHaveAttribute('aria-busy', 'false');
  await expect(page.locator('.all-lane')).toHaveCount(3);
  await expect(page.locator('.all-artwork-card')).toHaveCount(44);
  await expect(page.locator('main')).not.toContainText('In review');
  await expect(page.locator('main').getByRole('alert')).toHaveCount(0);
  expect(new URL(page.url()).searchParams.getAll('country')).toEqual([]);
  expect(new URL(page.url()).searchParams.get('highlights')).toBe('false');
  const first = page.locator('.all-artwork-card img').first();
  await expect.poll(() => first.evaluate((img: HTMLImageElement) => img.complete && img.naturalWidth > 0)).toBe(true);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: info.outputPath(`womens-rights-${width}.png`), fullPage: true });
  const drawing = page.locator('.all-artwork-card').filter({ hasText: 'Marie Gabrielle Capet and Marie Marguerite Carreaux de Rosemond' });
  await drawing.scrollIntoViewIfNeeded();
  await expect.poll(() => drawing.locator('img').evaluate((img: HTMLImageElement) => img.complete && img.naturalWidth > 0)).toBe(true);
  await drawing.click();
  await expect(page.getByRole('dialog')).toContainText('Adélaïde Labille-Guiard');
  await expect(page.getByRole('dialog')).not.toContainText('In review');
  await page.keyboard.press('Escape');
  await page.goto('/all?preset=womens-rights&start=1900&end=2000');
  await expect(page.locator('.timeline-stage')).toHaveAttribute('aria-busy', 'false');
  const election = page.getByRole('button', { name: 'Japanese women vote and enter the Diet, Event, 1946. Open event details', exact: true });
  await election.click();
  await expect(page.getByRole('dialog')).toContainText('39 women');
  await expect(page.getByRole('dialog').getByRole('link', { name: 'National Diet Library — General elections ↗', exact: true })).toHaveAttribute('href', 'https://www.ndl.go.jp/modern/e/cha5/description05.html');
  await expect(page.getByRole('dialog').getByRole('link', { name: 'Wikidata record ↗', exact: true })).toHaveCount(0);
  await expect(page.getByRole('dialog')).not.toContainText('In review');
  expect(writes).toEqual([]);
});
