export default function AboutPage() {
  return <main id="main-content" className="admin-page prose-page">
    <h1>A personal study atlas</h1>
    <p>Artline brings painters and their works into a shared chronology. Explore overlapping lives, follow a movement, and open a work to learn where it was made and where it is held.</p>
    <h2>How to explore</h2>
    <h3 id="popular-painters">Only popular painters</h3>
    <p>The atlas opens with a smaller starting selection: the top 100 in our imported Pantheon 2025 painter ranking, with documented editorial corrections. Hokusai is included despite the source’s occupation category; Donatello, primarily a sculptor, is not in this painter selection. Popularity is a discovery aid, not a ranking of artistic quality or the number of images available here.</p>
    <p>Uncheck “Only popular painters” to explore the full research catalogue. Your choice stays in the URL and survives reloads. “Reset view” restores the popular selection and full date range; “Clear filters” removes all filters, including popularity, while keeping the range. <a href="https://pantheon.world/data/datasets" target="_blank" rel="noreferrer">Read about the ranking source</a>.</p>
    <p>Ranking data: Pantheon 2025 / Datawheel, adapted for this atlas under <a href="https://creativecommons.org/licenses/by-sa/4.0/" target="_blank" rel="noreferrer">CC BY-SA 4.0</a>. This describes the source-derived selection, not the application’s code or artwork-image licences.</p>
    <p>Drag the date handles, edit the year fields, or choose a range preset. Move the selected range with Earlier and Later, or by dragging its middle; with the middle focused, the arrow keys move it ten years. Press / to search. Active filter chips show what is narrowing your view; remove one without resetting the date range.</p>
    <p>Choose several Regions to see painters associated with any of them. Country, movement, work type, search and dates narrow that selection further. Regions describe the painters’ country associations, not where their artworks are held. Clear regions leaves your other choices intact. Escape closes an open filter menu; record status belongs in the editorial Catalogue.</p>
    <p>Select a painter to open the right-hand panel. “Artworks by year” shows all catalogued works chronologically, not only the representative selection. Choose an artwork year to narrow the list; larger catalogues have pages. Date ranges are grouped at their first recorded year, and approximate or before/after dates keep their original labels. Undated works come last, with a separate dashed marker at the interval’s end. That marker indicates missing data, not a creation year.</p>
    <p>Use the panel’s arrows to browse painters in your current view. Open “About the painter and influences” for the biography. Select an artwork for its full record, use “View larger” to inspect the image, or copy a link to that specific work. “Artworks by year” returns you to the list. A year without records does not mean the painter created nothing in that year.</p>
    <p>In the enlarged viewer, use + and − to zoom, then scroll to explore the image. “Fit image” restores the whole composition. With the viewer controls or image focused, the +, − and 0 keys do the same; arrow keys scroll the focused image. Magnification is relative to the fitted view, not a claim of higher image resolution.</p>
    <p>Every painter is also available in the list below the timeline. Escape closes the enlarged image first, then the painter panel; focus returns to the control you used. On phones the panel fills the screen.</p>
    <h2>Explore museums and collections</h2>
    <p>Museums offers a place-based route into the atlas. Choose several museum regions or countries: choices within one field combine with “or”, while different fields narrow the results together. These locations describe physical museum venues, not painters’ nationalities. A foundation without a verified public venue remains a holding collection.</p>
    <p>Open a collection to browse its artworks, filter by painter, movement or creation date, and open the full record in the right-hand panel. Counts describe works catalogued in Artline, not the museum’s entire collection. Official visiting links provide current access and exhibition information.</p>
    <p>“Museum highlights” are selections supported by the museum’s own records. “My must-see works” is your separate personal list: enter your editor token, open an artwork, and save a note and its order in your selection. Changes remain in review; a selection never publishes an artwork automatically.</p>
    <p>“Confirmed on view” requires separate, dated display evidence. A holding record or highlight designation is not enough. Display reports older than 30 days, or past their stated end date, are excluded from this filter. Check the official museum record before a visit; even a recent report cannot guarantee future availability.</p>
    <h2>A catalogue in progress</h2>
    <p>Research records are shown in the research preview. An “In review” label means dates, writing, relationships, or selected works still need an editorial check. Images do not make a record publication-ready. Missing information stays marked as unknown.</p>
    <p>The catalogue is read-only until an editor token is provided. Changes must pass server checks; incomplete records cannot be published. Selected museum data is imported through a local, reviewed workflow; the web import scheduler is not yet available.</p>
    <h2>Images and sources</h2>
    <p>Artwork records link to museum sources and the source of each image. The current selection uses locally stored reproductions with recorded public-domain notices or open-access terms. Artwork copyright and image permissions are tracked separately. Where no permitted reproduction is available, details remain readable without an image.</p>
    <p>“Held at” describes the collection, not a promise that an artwork is on display. The location-check date is recorded with each sourced work. A place depicted in a painting is not automatically treated as the place where it was made.</p>
  </main>;
}
