package main

// Separate institution and exact object identities; never substitutes an NGA
// photograph for a blocked Chicago reproduction of a different painting.
var impressionistFollowupPicks = []coveragePick{
	{"nga", "177090", "Alfred Sisley", "Marly-le-Roi: selected popular-artist NGA painting; no museum masterpiece status inferred."},
	{"nga", "46689", "Alfred Sisley", "The Banks of the Oise: selected popular-artist NGA painting; no museum masterpiece status inferred."},
	{"nga", "46690", "Alfred Sisley", "The Road in the Woods: selected popular-artist NGA painting; no museum masterpiece status inferred."},
	{"nga", "62641", "Alfred Sisley", "First Snow at Veneux-Nadon: selected popular-artist NGA painting; no museum masterpiece status inferred."},
	{"nga", "66436", "Alfred Sisley", "Flood at Port-Marly: selected popular-artist NGA painting; no museum masterpiece status inferred."},
	{"nga", "155712", "Camille Pissarro", "Peasant Girl with a Straw Hat: selected popular-artist NGA painting; no museum masterpiece status inferred."},
	{"nga", "164952", "Camille Pissarro", "Young Peasant Girls Resting in the Fields near Pontoise: selected popular-artist NGA painting; no museum masterpiece status inferred."},
	{"nga", "195850", "Camille Pissarro", "The Louvre, Afternoon, Rainy Weather: selected popular-artist NGA painting; no museum masterpiece status inferred."},
	{"nga", "46529", "Camille Pissarro", "The Bather: selected popular-artist NGA painting; no museum masterpiece status inferred."},
	{"nga", "46673", "Camille Pissarro", "Boulevard des Italiens, Morning, Sunlight: selected popular-artist NGA painting; no museum masterpiece status inferred."},
	{"nga", "46674", "Camille Pissarro", "Peasant Woman: selected popular-artist NGA painting; no museum masterpiece status inferred."},
	{"nga", "52195", "Camille Pissarro", "Orchard in Bloom, Louveciennes: selected popular-artist NGA painting; no museum masterpiece status inferred."},
	{"nga", "52197", "Camille Pissarro", "Hampton Court Green: selected popular-artist NGA painting; no museum masterpiece status inferred."},
	{"nga", "52198", "Camille Pissarro", "The Artist's Garden at Eragny: selected popular-artist NGA painting; no museum masterpiece status inferred."},
	{"nga", "52199", "Camille Pissarro", "Place du Carrousel, Paris: selected popular-artist NGA painting; no museum masterpiece status inferred."},
	{"nga", "66427", "Camille Pissarro", "A Creek in St. Thomas (Virgin Islands): selected popular-artist NGA painting; no museum masterpiece status inferred."},
	{"nga", "66428", "Camille Pissarro", "Two Women Chatting by the Sea, St. Thomas: selected popular-artist NGA painting; no museum masterpiece status inferred."},
	{"nga", "66429", "Camille Pissarro", "The Fence: selected popular-artist NGA painting; no museum masterpiece status inferred."},
	{"nga", "66430", "Camille Pissarro", "Charing Cross Bridge, London: selected popular-artist NGA painting; no museum masterpiece status inferred."},
	{"nga", "72886", "Camille Pissarro", "Landscape at Les Pâtis, Pontoise: selected popular-artist NGA painting; no museum masterpiece status inferred."},
	{"nga", "89683", "Camille Pissarro", "The Gardener - Old Peasant with Cabbage: selected popular-artist NGA painting; no museum masterpiece status inferred."},
	{"nga", "1211", "Pierre-Auguste Renoir", "The Dancer: selected popular-artist NGA painting; no museum masterpiece status inferred."},
	{"nga", "164956", "Pierre-Auguste Renoir", "The Young Soldier: selected popular-artist NGA painting; no museum masterpiece status inferred."},
	{"nga", "195122", "Pierre-Auguste Renoir", "View of Monte Carlo from Cap Martin: selected popular-artist NGA painting; no museum masterpiece status inferred."},
	{"nga", "35083", "Pierre-Auguste Renoir", "Head of a Young Girl: selected popular-artist NGA painting; no museum masterpiece status inferred."},
	{"nga", "37637", "Pierre-Auguste Renoir", "Woman with a Cat: selected popular-artist NGA painting; no museum masterpiece status inferred."},
	{"nga", "39759", "Pierre-Auguste Renoir", "Oarsmen at Chatou: selected popular-artist NGA painting; no museum masterpiece status inferred."},
	{"nga", "42935", "Pierre-Auguste Renoir", "The Mussel Harvest: selected popular-artist NGA painting; no museum masterpiece status inferred."},
	{"nga", "43517", "Pierre-Auguste Renoir", "Girl with a Basket of Fish: selected popular-artist NGA painting; no museum masterpiece status inferred."},
	{"nga", "43518", "Pierre-Auguste Renoir", "Girl with a Basket of Oranges: selected popular-artist NGA painting; no museum masterpiece status inferred."},
	{"nga", "46090", "Pierre-Auguste Renoir", "Madame Henriot: selected popular-artist NGA painting; no museum masterpiece status inferred."},
	{"nga", "46533", "Pierre-Auguste Renoir", "Girl with a Hoop: selected popular-artist NGA painting; no museum masterpiece status inferred."},
	{"nga", "46534", "Pierre-Auguste Renoir", "Marie Murer: selected popular-artist NGA painting; no museum masterpiece status inferred."},
	{"nga", "46535", "Pierre-Auguste Renoir", "Suzanne Valadon: selected popular-artist NGA painting; no museum masterpiece status inferred."},
	{"nga", "46679", "Pierre-Auguste Renoir", "Bather Arranging Her Hair: selected popular-artist NGA painting; no museum masterpiece status inferred."},
	{"nga", "46680", "Pierre-Auguste Renoir", "Diana: selected popular-artist NGA painting; no museum masterpiece status inferred."},
	{"nga", "46681", "Pierre-Auguste Renoir", "A Girl with a Watering Can: selected popular-artist NGA painting; no museum masterpiece status inferred."},
	{"nga", "46682", "Pierre-Auguste Renoir", "Odalisque: selected popular-artist NGA painting; no museum masterpiece status inferred."},
	{"nga", "46684", "Pierre-Auguste Renoir", "Mademoiselle Sicot: selected popular-artist NGA painting; no museum masterpiece status inferred."},
	{"nga", "50748", "Pierre-Auguste Renoir", "Nude: selected popular-artist NGA painting; no museum masterpiece status inferred."},
	{"nga", "52201", "Pierre-Auguste Renoir", "Head of a Dog: selected popular-artist NGA painting; no museum masterpiece status inferred."},
	{"nga", "52202", "Pierre-Auguste Renoir", "Pont Neuf, Paris: selected popular-artist NGA painting; no museum masterpiece status inferred."},
	{"nga", "52203", "Pierre-Auguste Renoir", "Regatta at Argenteuil: selected popular-artist NGA painting; no museum masterpiece status inferred."},
	{"nga", "52204", "Pierre-Auguste Renoir", "Madame Monet and Her Son: selected popular-artist NGA painting; no museum masterpiece status inferred."},
	{"nga", "52205", "Pierre-Auguste Renoir", "Picking Flowers: selected popular-artist NGA painting; no museum masterpiece status inferred."},
	{"nga", "52207", "Pierre-Auguste Renoir", "Young Woman Braiding Her Hair: selected popular-artist NGA painting; no museum masterpiece status inferred."},
	{"nga", "52208", "Pierre-Auguste Renoir", "Georges Rivière: selected popular-artist NGA painting; no museum masterpiece status inferred."},
	{"nga", "52209", "Pierre-Auguste Renoir", "Landscape between Storms: selected popular-artist NGA painting; no museum masterpiece status inferred."},
	{"nga", "52210", "Pierre-Auguste Renoir", "Woman by a Fence: selected popular-artist NGA painting; no museum masterpiece status inferred."},
	{"nga", "52211", "Pierre-Auguste Renoir", "Woman Standing by a Tree: selected popular-artist NGA painting; no museum masterpiece status inferred."},
	{"nga", "52212", "Pierre-Auguste Renoir", "Woman in a Park: selected popular-artist NGA painting; no museum masterpiece status inferred."},
	{"nga", "52213", "Pierre-Auguste Renoir", "Child with Blond Hair: selected popular-artist NGA painting; no museum masterpiece status inferred."},
	{"nga", "52214", "Pierre-Auguste Renoir", "Child with Brown Hair: selected popular-artist NGA painting; no museum masterpiece status inferred."},
	{"nga", "52215", "Pierre-Auguste Renoir", "Young Girl Reading: selected popular-artist NGA painting; no museum masterpiece status inferred."},
	{"nga", "52216", "Pierre-Auguste Renoir", "Landscape at Vétheuil: selected popular-artist NGA painting; no museum masterpiece status inferred."},
	{"nga", "52217", "Pierre-Auguste Renoir", "Small Study for a Nude: selected popular-artist NGA painting; no museum masterpiece status inferred."},
	{"nga", "52218", "Pierre-Auguste Renoir", "Nude with Figure in Background: selected popular-artist NGA painting; no museum masterpiece status inferred."},
	{"nga", "52219", "Pierre-Auguste Renoir", "The Blue River: selected popular-artist NGA painting; no museum masterpiece status inferred."},
	{"nga", "52220", "Pierre-Auguste Renoir", "Young Spanish Woman with a Guitar: selected popular-artist NGA painting; no museum masterpiece status inferred."},
	{"nga", "52221", "Pierre-Auguste Renoir", "Maison de la Poste, Cagnes: selected popular-artist NGA painting; no museum masterpiece status inferred."},
	{"nga", "52222", "Pierre-Auguste Renoir", "Jeanne Samary: selected popular-artist NGA painting; no museum masterpiece status inferred."},
	{"nga", "52223", "Pierre-Auguste Renoir", "Peaches on a Plate: selected popular-artist NGA painting; no museum masterpiece status inferred."},
	{"nga", "61382", "Pierre-Auguste Renoir", "Flowers in a Vase: selected popular-artist NGA painting; no museum masterpiece status inferred."},
	{"nga", "66433", "Pierre-Auguste Renoir", "Claude Monet: selected popular-artist NGA painting; no museum masterpiece status inferred."},
	{"nga", "66434", "Pierre-Auguste Renoir", "Child with Toys - Gabrielle and the Artist's Son, Jean: selected popular-artist NGA painting; no museum masterpiece status inferred."},
}
