#!/usr/bin/env python3
"""Attach captured primary-source context without overwriting authority fields."""
import importlib.util,json
from pathlib import Path
spec=importlib.util.spec_from_file_location('b',Path(__file__).with_name('research-armenian-georgian-artworks.py'));b=importlib.util.module_from_spec(spec);spec.loader.exec_module(b)
s=b.s
entries=[('artist','Q718409','https://www.sarian.am/htmls_eng/sarian_biography_parts.html','House-Museum biography and travel context; no biography, life dates, holdings or display fields automatically overwritten.'),('artist','Q718409','https://www.sarian.am/htmls_eng/other_national_gallery_of_arm_main.html','House-Museum account of Saryan works in the National Gallery of Armenia; collection-level context, not a current display assertion.'),('artist','Q310896','https://art.gov.ge/en/portfolio/niko-pirosmanashvili/','Georgian archive painter context and source-captioned collection examples; undated examples remain undated.'),('artist','Q2655639','https://art.gov.ge/en/portfolio/gabashvili-gigo/','Georgian archive artist biography and dated examples; independent primary collection context.'),('artist','Q1694168','https://art.gov.ge/en/portfolio/gudiashvili-lado/','Georgian archive modernist artist context; painting, theatre and mural practices distinguished.'),('artist','Q2028362','https://art.gov.ge/en/portfolio/kakabadze-david/','Georgian archive artist context and international collection connections; sculpture and other media not recast as paintings.'),('artist','Q6761777','https://www.aslamazyanmuseum.com/arm/','Aslamazyan Sisters Gallery primary account of donated originals and women artists; reproduction rights remain separate.'),('artist','Q738117','https://art.thewalters.org/object/W.539/','Walters W.539, Toros Roslin Gospels (1262), provides a named-creator illumination research lead; no painting or folio record invented.'),('artwork','Q138349988','https://www.fondationbeyeler.ch/fileadmin/user_upload/Ausstellungen/Ausstellungen_2023/web2_Saalheft_PIROSMANI_EN.pdf','PDF page 18: Five Princes Carousing is dated 1906; selected Wikidata record gives 1909. Date/identity discrepancy remains review, with unknown date fields and no image attachment.')]
rows=[]
for kind,q,url,note in entries:
 key=s.core.sha(url.encode());receipt=json.loads((s.RUN/'primary-captures'/(key+'.receipt.json')).read_bytes());suffix='.pdf' if url.endswith('.pdf') else '.html';raw=(s.RUN/'primary-captures'/(key+suffix)).read_bytes();assert s.core.sha(raw)==receipt['sha256'];rows.append({'kind':kind,'qid':q,'url':url,'note':note,'receipt':receipt})
s.save(s.RUN/'primary-citation-selection.json',rows)
for target in ['local','production']:
 output=[]
 with s.connect(target) as db:
  db.execute("INSERT INTO sources(slug,name,source_type,base_url) VALUES('armenian-georgian-primary-sources','Armenian and Georgian primary museum research','collection_page','https://art.gov.ge/') ON CONFLICT DO NOTHING");sid=db.execute("SELECT id FROM sources WHERE slug='armenian-georgian-primary-sources'").fetchone()['id'];db.commit()
  for e in rows:
   entity=db.execute('SELECT entity_id::text FROM external_identifiers WHERE scheme=\'wikidata\' AND entity_type=%s AND external_id=%s',(e['kind'],e['qid'])).fetchone()
   if not entity:db.commit();output.append({'qid':e['qid'],'status':'authority_not_linked'});continue
   db.execute("INSERT INTO citations(entity_type,entity_id,field_name,source_id,source_record_id,source_url,evidence_note,retrieved_at,created_by) SELECT %s,%s,'primary_museum_research',%s,%s,%s,%s,%s,'local-european-research' WHERE NOT EXISTS(SELECT 1 FROM citations WHERE entity_type=%s AND entity_id=%s AND source_id=%s AND source_url=%s)",(e['kind'],entity['entity_id'],sid,e['qid'],e['url'],e['note']+' Capture SHA-256: '+e['receipt']['sha256'],e['receipt'].get('retrieved_at',e['receipt'].get('at')),e['kind'],entity['entity_id'],sid,e['url']));db.commit();output.append({'qid':e['qid'],'entity_id':entity['entity_id'],'source_url':e['url'],'status':'attached'})
 s.save(s.RUN/('primary-citations-'+target+'.json'),{'at':s.core.now(),'rows':output});print(target,'primary citations',len(output),flush=True)
