#!/usr/bin/env python3
"""Scan this round's evidence, code and delivered files without printing secret values."""
import argparse
import collections
import datetime
import hashlib
import json
import re
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
TEXT = {'.json', '.jsonl', '.csv', '.tsv', '.xml', '.html', '.htm', '.log', '.md', '.txt', '.py'}
CREDENTIALS = {
    'private_key': re.compile(rb'-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----'),
    'google_access_token': re.compile(rb'ya29\.[A-Za-z0-9_-]{30,}'),
    'google_api_key': re.compile(rb'AIza[0-9A-Za-z_-]{35}'),
    'github_token': re.compile(rb'(?:gh[pousr]_[A-Za-z0-9]{30,}|github_pat_[A-Za-z0-9_]{60,})'),
    'database_password_url': re.compile(rb'postgres(?:ql)?://[^\s:@/]+:[^\s@]+@'),
}
PRIVATE_REFERENCE = {
    'private_dataset_archive': re.compile(rb'art500k\.tar(?:\.gz)?', re.I),
    'private_dataset_directory': re.compile(rb'[/\\]art500k(?:-work)?[/\\]', re.I),
    'private_dataset_source_url': re.compile(rb'deepart\.hkust\.edu\.hk/ART500K', re.I),
}


def findings(path, patterns):
    found = set()
    tail = b''
    with path.open('rb') as source:
        while chunk := source.read(1024 * 1024):
            data = tail + chunk
            found.update(name for name, pattern in patterns.items() if pattern.search(data))
            tail = data[-1024:]
    return [{'path': str(path.relative_to(ROOT)), 'pattern': name} for name in sorted(found)]


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--run', required=True, type=Path)
    parser.add_argument('--output', required=True, type=Path)
    args = parser.parse_args()
    run = args.run.resolve()
    assert run.is_relative_to(ROOT) and run.is_dir()
    code = set(ROOT.glob('ops/*followup*.py'))
    code.update(ROOT.glob('ops/*austria*.py'))
    code.update(ROOT.glob('ops/*belvedere*.py'))
    code.update(ROOT.glob('ops/*wien*.py'))
    code.update(ROOT.glob('ops/*popular*.py'))
    for name in ('apply-night-prepared-local.py', 'audit-overnight-local-images.py',
                 'upload-overnight-prepared-images.py', 'research-overnight-alternate-commons.py',
                 'import-overnight-nga-selection.py', 'overnight-image-campaign.py',
                 'recover-nationalmuseum-commons.py', 'report-image-coverage.py',
                 'research-popular-painting-photos.py', 'test_popular_painting_photos.py',
                 'overnight-commons-images.py', 'overnight-commons-origin.py', 'overnight-joconde-images.py', 'commons-photograph-licence.py',
                 'refresh-verified-image-evidence.py', 'test_refresh_verified_image_evidence.py',
                 'test_overnight_commons_origin.py'):
        code.add(ROOT / 'ops' / name)
    paths = sorted(set(run.rglob('*')) | code)
    secrets, private, scanned, binary = [], [], [], collections.Counter()
    for path in paths:
        if path.is_symlink():
            raise AssertionError('Unexpected campaign symlink: ' + str(path.relative_to(ROOT)))
        if not path.is_file() or path == args.output.resolve():
            continue
        if path.suffix.lower() not in TEXT:
            binary[path.suffix.lower() or '(no suffix)'] += 1
            continue
        secrets.extend(findings(path, CREDENTIALS))
        private.extend(findings(path, PRIVATE_REFERENCE))
        scanned.append({'path': str(path.relative_to(ROOT)), 'bytes': path.stat().st_size})
    journal = {}
    for line in (run / 'local-attachments.jsonl').read_text().splitlines():
        row = json.loads(line)
        if row['outcome'] in ('attached', 'already_attached'):
            journal[row['artwork_id']] = row
        elif row['outcome'] == 'withdrawn':
            journal.pop(row['artwork_id'], None)
    image_errors = []
    for aid, row in journal.items():
        receipt = json.loads(Path(row['receipt']).read_text())
        path = (ROOT / 'apps/web/public' / receipt['path'].lstrip('/')).resolve()
        assert path.is_relative_to(ROOT / 'apps/web/public/assets/artworks')
        try:
            assert hashlib.sha256(path.read_bytes()).hexdigest() == receipt['sha256']
            with Image.open(path) as image:
                assert image.format == 'JPEG' and not image.getexif(), 'Unexpected format or EXIF metadata'
                assert not image.info.get('xmp'), 'Unexpected embedded XMP'
                # NGA's IIIF renderer adds this harmless encoder label. It is
                # source provenance, not an EXIF payload or a private path.
                assert image.info.get('comment', b'') in (b'', b'Generated by IIPImage'), 'Embedded comment requires review'
        except Exception as exc:
            image_errors.append({'artwork_id': aid, 'error': str(exc)[:160]})
    result = {
        'at': datetime.datetime.now(datetime.timezone.utc).isoformat(),
        'scope': 'This follow-up run, its operational code and all delivered JPEGs. '
                 'Unrelated existing work, environment secrets and backups were not copied into this output.',
        'text_files_scanned': len(scanned), 'text_bytes_scanned': sum(x['bytes'] for x in scanned),
        'scanned_file_inventory_sha256': hashlib.sha256(json.dumps(scanned, sort_keys=True).encode()).hexdigest(),
        'binary_files_not_text_scanned': dict(binary), 'approved_image_files_checked': len(journal),
        'image_embedded_metadata_errors': image_errors,
        'permitted_encoder_comment': 'Generated by IIPImage',
        'credential_pattern_findings': secrets, 'private_reference_findings': private,
        'limitations': 'Pattern-based scan, supplemented by source identity and rights audits. '
                       'Binary institutional metadata archives retain their separate source receipts; '
                       'an empty pattern result is not a universal proof that arbitrary content contains no secret.',
    }
    with args.output.open('x') as output:
        json.dump(result, output, indent=2)
    print(json.dumps({key: len(value) if isinstance(value, list) else value
                      for key, value in result.items()}, indent=2))
    if secrets or private or image_errors:
        raise SystemExit(1)


if __name__ == '__main__':
    main()
