-- Existing local catalogue only; no migrations, fixtures or mutations.
\set ON_ERROR_STOP on
BEGIN READ ONLY;
SET LOCAL statement_timeout='15s';
\copy (SELECT jsonb_build_object('id',id,'title',title,'start',start_year,'end',end_year,'top',top100,'topics',topics,'countries',countries,'regions',regions,'sources',record->'sources','url',record->'sourceUrl') FROM event_records WHERE status<>'archived' AND (top100 OR title ~* 'song dynasty|ashoka|songhai|ghana empire|buddhis|renaissance|romanticism|sputnik|apollo|space race|internet|world wide web|computer|suez crisis|civil rights act|brown v|selma|montgomery bus|march on washington|abbasid caliphate|ghana independence|indian independence') ORDER BY start_year,id LIMIT 500) TO 'docs/research/preset-review-20260922/event-candidates.jsonl'
\copy (SELECT jsonb_build_object('id',b.id,'title',b.title,'author',b.author_label,'start',b.start_year,'end',b.end_year,'countries',d.countries,'regions',d.regions,'top',d.top100,'url',b.record->'sourceUrl') FROM book_records b JOIN book_discovery d ON d.book_id=b.id AND d.book_checksum=b.source_checksum WHERE b.status<>'archived' AND (d.top100 OR b.title ~* 'Newton|Opticks|Principia|Dialogue Concerning|Origin of Species|Dhammapada|Lotus Sutra|Secret History|Sundiata|Souls of Black Folk|Notes of a Native Son|Letter from Birmingham|Double Helix|Cybernetics') ORDER BY b.start_year,b.id LIMIT 300) TO 'docs/research/preset-review-20260922/book-candidates.jsonl'
\copy (SELECT jsonb_build_object('kind',kind,'key',key,'name',name) FROM book_discovery_terms WHERE kind='country' ORDER BY name) TO 'docs/research/preset-review-20260922/book-countries.jsonl'
\copy (SELECT jsonb_build_object('id',a.id,'title',a.title,'start',a.creation_year_start,'end',a.creation_year_end,'creator',a.unlinked_creator_label,'tradition',a.cultural_context,'image',a.primary_media_id,'sources',(SELECT jsonb_agg(jsonb_build_object('url',c.source_url,'note',left(c.evidence_note,500))) FROM citations c WHERE c.entity_type='artwork' AND c.entity_id=a.id)) FROM artworks a WHERE a.status<>'archived' AND a.creation_year_start<=1500 AND a.creation_year_end>=250 AND a.primary_media_id IS NOT NULL AND a.cultural_context ~* 'byzantin' ORDER BY a.creation_year_start,a.id LIMIT 120) TO 'docs/research/preset-review-20260922/byzantine-candidates.jsonl'
COMMIT;
