#!/usr/bin/env python3
"""Individually reviewed Cesi records; uncertainty and sheet identity retained."""
import importlib.util,json
from pathlib import Path
s=importlib.util.spec_from_file_location('campaign',Path(__file__).with_name('cesi-top100-20261010.py'));m=importlib.util.module_from_spec(s);s.loader.exec_module(m)
AID='07441bd8-6663-4e16-963d-f16fc6cd35ba'
pages={d['url']:d for p in (m.RUN/'cesi-pages').glob('*.json') for d in [m.load(p)]}
rows=[]
def add(url,key,title,museum,date,kind='drawing',medium=None,dimensions=None,accession=None,role='primary',note='',image=None,rights=None,licence=None):
    page=pages[url];assert page['receipt']['status']==200
    raw,_=m.capture(url);assert b'Cesi' in raw or b'CESI' in raw
    rows.append(dict(provider='cesi-native',source_url=url,source_id=key,scheme='cesi-source-object',title=title,date=date,creator='Bartolomeo Cesi' if role=='primary' else 'Attributed to Bartolomeo Cesi',artist_id=AID,artist_name='Bartolomeo Cesi',artist_url=None,metadata=dict(source_page_file=str((m.RUN/'cesi-pages'/(m.sha(url.encode())[:16]+'.json')).relative_to(m.ROOT)),editorial_note=note),fields=dict(Media=medium,Dimensions=dimensions),receipt=page['receipt'],image_url=image,rights_label=rights or 'Image reuse not established; metadata only',rights_status='cc0' if licence and '/zero/' in licence else 'public_domain' if image else 'unknown',license_url=licence,rights_basis='Explicit native museum image reuse statement retained with object record.' if image else None,artwork_id=m.uid('artwork/'+key),state='new',image_needed=bool(image),add_holding=True,institution_id=museum,work_type=kind,attribution_role=role,accession=accession,selection_basis='User-requested deep Cesi review; documented institutional collection object.',identity_confidence=.98,identity_basis='Individually read institutional object/collection record; original inventory, physical sheet identity, qualifications and unknown dates preserved.',editorial_note=note))
def dated(first,last,display,precision='range'):return dict(first=first,last=last,display=display,precision=precision)
u='https://www.getty.edu/art/collection/object/107VNY'
raw,rc=m.capture(u);sp=m.BeautifulSoup(raw,'html.parser');d=json.loads(sp.select_one('script[type="application/ld+json"]').get_text())
assert d['identifier']==['98.GB.1'] and d['creator'][0]['name']=='Bartolomeo Cesi' and d['license']=='http://creativecommons.org/publicdomain/zero/1.0/'
add(u,'getty/107VNY',d['name'],'62fb1e52-07ff-50bd-8eeb-95ea5bf4af1c',dated(1590,1599,'about 1590s','circa_range'),medium=d['material'],dimensions=d['size'],accession='98.GB.1',image=d['thumbnailUrl'].replace('!300,300','!1600,1600'),rights='Getty Open Content: CC0',licence='https://creativecommons.org/publicdomain/zero/1.0/')
u='https://collections.lacma.org/object/20912'
add(u,'lacma/20912','Madonna and Child with SS. Benedict, John the Baptist and Francis','9f04a7f4-91ac-5f94-ad81-a28958da2760',dated(1595,1598,'circa 1595–1598','circa_range'),medium='Pen and brown ink over red chalk on faded blue paper',dimensions='Sheet: 9 x 7 in. (22.86 x 17.78 cm)',accession='59.25.3',note='Per-object photograph is credited © Museum Associates/LACMA without an explicit reuse licence in the captured record; no image attached.')
u='https://www.museedegrenoble.fr/oeuvre/2572/1922-etude-d-un-homme-drape-assis-les-mains-appuyees-sur-un-baton.htm'
add(u,'grenoble/2572',"Etude d'un homme drapé assis, les mains appuyées sur un bâton",'76d4de95-1650-486a-ba44-45461b8d44da',dated(1601,1700,'XVIIe siècle','century'),medium='Red chalk with white chalk highlights; brown-ink framing line on lined green-grey laid paper',dimensions='18.5 × 13.3 cm',note='Source gives a century, retained without narrowing to the artist lifespan. No exact corresponding painting is established by the museum. Photo credit: VILLE DE GRENOBLE / MUSÉE DE GRENOBLE-J.L. LACROIX.',image='https://images.navigart.fr/1000/5C/86/5C86052.jpg',rights='Domaine public, Domaine public',licence='https://creativecommons.org/publicdomain/mark/1.0/')
u='https://www.rijksmuseum.nl/nl/collectie/object/Studie-van-een-jongeman--4a080e0e117760ebde60000614a3028a'
add(u,'rijksmuseum/200118126','Studie van een jongeman','b6a5755d-157e-4ebe-a5a9-3bc52964ebf5',dated(1607,1615,'1607–1615'),medium='Red and white chalk on blue paper',dimensions='353 × 240 mm',accession='RP-T-1967-68(R)',note='Recto of a physical sheet with a related verso study. One catalogue object retained, no separate verso artwork created. Probable preparation for a fresco, not an asserted identification.',image='https://iiif.micr.io/seAsX/full/!1600,1600/0/default.jpg',rights='Publiek domein',licence='https://creativecommons.org/publicdomain/mark/1.0/')
u='https://collections.louvre.fr/en/ark:/53355/cl020004994'
add(u,'louvre/cl020004994','Jeune homme assis, tenant un livre','355fdf89-aee5-4066-a0f3-fd4cfc2a13ae',None,medium='Red chalk and white chalk on blue paper, squared in black chalk',dimensions='17.1 × 15.9 cm',accession='INV 8035, Recto',note='Museum identifies this as a study for a singer in the Certosa di Maggiano vault completed in 1594. Completion of the fresco is contextual evidence, not an exact drawing creation date. Former Carracci-school attribution preserved in source. Photograph rights not cleared.')
u='https://collections.augustins.toulouse.fr/fr/notice/2004-1-118-portrait-d-un-religieux-c38ba34f-1209-42be-ad95-c004c147ef68'
add(u,'augustins/2004-1-118',"Portrait d'un religieux",'b7d95c21-3494-4883-8922-a9d4dd21749c',None,'painting','Oil on canvas','59 × 45 cm','2004 1 118','attributed_to','Attributed to Cesi by Axel Hémery in 2003. Older French, Italian anonymous, and Prospero Fontana attributions remain source history. Date fields describe periods of artist activity and conflicting older attribution; creation date left unknown.')
u='https://catalogo.museidigenova.it/oggetti/48256-studio-per-la-figura-di-san-paolo-delle-mani-e-di-un-piede'
add(u,'genova/48256','Studio per la figura di San Paolo, delle mani e di un piede','396e1957-9e64-525c-86e4-7e85d422ffc6',None,medium='Red chalk and white heightening on backed blue paper, squared in black pencil',dimensions='347 × 208 mm',accession='D 1934',note='Study for the Bologna Saint Paul panel. Native structured date bounds repeat the artist lifespan (1556–1629), while its commentary discusses a later date; do not convert those bounds into an artwork date. Source thumbnail is labelled verso; no image attached.')
u='https://catalogo.museidigenova.it/oggetti/47771-compianto-su-cristo-morto-recto-una-testa-e-un-volto-virili-di-profilo-verso'
add(u,'genova/47771','Compianto su Cristo morto (recto) / Una testa e un volto virili di profilo (verso)','396e1957-9e64-525c-86e4-7e85d422ffc6',None,medium='Pen and ink on beige paper, squared in black pencil',dimensions='187 × 272 mm',accession='D 1226',role='attributed_to',note='Native AUTS field says attribuito. Recto and verso remain one sheet, related to the Certosa Lamentation painting. Native bounds repeat the artist lifespan and are retained only as source evidence, not creation years.')
u='https://pinacotecabologna.cultura.gov.it/eventi-mostre/bartolomeo-cesi-1556-1629-pittura-del-silenzio-nelleta-dei-carracci'
for key,title,note in [
 ('madonna-santomobono','Madonna col Bambino e i santi Giacinto, Agostino e Filippo Benizzi',"Official 2025–2026 museum article identifies the altarpiece from the internal church of the Sant’Omobono nuns. Saint names differ in an older room-list caption; preserve this source wording and do not create a second work from that variant."),
 ('immacolata-santanna','Incarnazione della Vergine in sant’Anna come Immacolata Concezione','Altarpiece from San Francesco; also titled L’Immacolata appare a Sant’Anna. Do not duplicate that alternate title.'),
 ('san-pietro','San Pietro','Separate lateral panel of the San Francesco altarpiece, named with Saint Paul in the official museum article.'),
 ('san-paolo','San Paolo','Separate lateral panel of the San Francesco altarpiece. The Genoa D 1934 study is a separate drawing, not this painting.')]:
    add(u,'bologna-caption/'+key,title,'1cfa0c7f-e32b-54ac-9bfc-362fe6c7f4c3',None,'painting',note=note+' No creation date or inventory is given by this source. Exhibition ended in April 2026; no present-display assertion.')
m.save(m.RUN/'cesi-candidates.json',dict(at=m.now(),rows=rows,excluded=[
 dict(source_url='https://collections.louvre.fr/en/ark:/53355/cl020102634',title='Saint Antoine de Padoue en prière',reason='The museum commentary rejects Cesi and identifies Calvaert; title/header alone is misleading. No primary Cesi link added.'),
 dict(source_url='https://collections.louvre.fr/en/ark:/53355/cl020201957',title='Jeune homme nu, agenouillé, tourné vers la droite, implorant',reason='Current principal attribution is Girolamo Macchietti; Cesi appears only among proposals. No primary Cesi link added.'),
 dict(source_url='https://www.britishmuseum.org/collection/object/P_Ff-4-57',reason='Exact object found, direct source access denied; retained as a follow-up lead.'),
 dict(source_url='https://www.themorgan.org/drawings/item/279302',reason='Exact double-sided object found, direct source access denied; no bypass or duplicate sheet inserted.'),
 dict(source_url='https://www.museodelprado.es/en/the-collection/art-work/the-annunciation/98105e3c-d726-49ec-aac1-943d4df3bad4',reason='Qualified attribution and direct source access denied; retained as a follow-up lead.')]))
print('Individually reviewed Cesi candidates',len(rows),'images',sum(r['image_needed'] for r in rows))
