#!/usr/bin/env python3
"""Copy the verified local Books/Events catalogue into absent production tables.

Explicit --apply required. Refuses existing tables, changed source fingerprints,
unexpected migration history, publication and an unsuccessful recovery backup.
No local writes, fixtures, deletes, account changes or implicit deployment.
"""
import argparse
import hashlib
import importlib.util
import json
import subprocess
from pathlib import Path

from psycopg import sql

spec = importlib.util.spec_from_file_location('release', Path(__file__).with_name('audit-production-release.py'))
release = importlib.util.module_from_spec(spec)
spec.loader.exec_module(release)
TABLES = ['book_records', 'book_creators', 'book_creator_links', 'book_discovery_terms', 'book_discovery', 'event_records']
MIGRATIONS = ['0020_books_catalogue.sql', '0021_book_discovery_filters.sql',
              '0022_events_catalogue.sql', '0024_atlas_intake.sql']


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument('--snapshot', type=Path, required=True)
    p.add_argument('--backup-id', required=True)
    p.add_argument('--output', type=Path, required=True)
    p.add_argument('--port', type=int, default=55434)
    p.add_argument('--apply', action='store_true')
    a = p.parse_args()
    baseline = json.loads(a.snapshot.read_text())
    migration_dir = release.ROOT / 'apps/server/db/migrations'
    plan = {'at': release.core.now(), 'tables': {t: {'count': baseline['tables'][t]['count'],
            'digest': baseline['tables'][t]['digest']} for t in TABLES}, 'migrations':
            {m: hashlib.sha256((migration_dir / m).read_bytes()).hexdigest() for m in MIGRATIONS}}
    if not a.apply:
        print(json.dumps(plan, indent=2)); return
    assert not a.output.exists(), 'Do not overwrite an application receipt'
    backup = json.loads(subprocess.check_output(['gcloud', 'sql', 'backups', 'describe', a.backup_id,
        '--instance=artline-postgres', '--project=artline-508319', '--format=json'], text=True))
    assert backup['status'] == 'SUCCESSFUL'
    with release.connect('local', a.port) as source, release.connect('cloud', a.port, readonly=False) as dest:
        source.execute('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ READ ONLY')
        dest.execute("SET LOCAL lock_timeout='5s'")
        dest.execute('SELECT pg_advisory_xact_lock(20250907001)')
        existing = {r[0] for r in dest.execute('SELECT filename FROM schema_migrations')}
        expected = set(baseline['migrations']) - set(MIGRATIONS)
        assert existing == expected, 'Production migration history changed'
        for table in TABLES + ['atlas_drafts']:
            assert dest.execute('SELECT to_regclass(%s)', (table,)).fetchone()[0] is None, 'Existing table: ' + table
        for table in ('book_records', 'event_records'):
            assert source.execute(sql.SQL("SELECT count(*) FROM {} WHERE status<>'review'").format(sql.Identifier(table))).fetchone()[0] == 0
        for migration in MIGRATIONS:
            dest.execute((migration_dir / migration).read_text())
            dest.execute('INSERT INTO schema_migrations(filename) VALUES(%s)', (migration,))
        for table in TABLES:
            meta = baseline['tables'][table]
            cols = [c[0] for c in meta['columns'] if c[2] == 'NEVER']
            key = sql.SQL('jsonb_build_array({})::text').format(sql.SQL(',').join(map(sql.Identifier, meta['primary_key'])))
            query = sql.SQL('SELECT {},md5((to_jsonb(t)-%s::text[])::text) FROM {} t').format(key, sql.Identifier(table))
            current = dict(source.execute(query, (release.CLOCKS,)).fetchall())
            assert current == meta['rows'], 'Local source changed: ' + table
            column_sql = sql.SQL(',').join(map(sql.Identifier, cols))
            with source.cursor().copy(sql.SQL('COPY (SELECT {} FROM {}) TO STDOUT').format(column_sql, sql.Identifier(table))) as read:
                with dest.cursor().copy(sql.SQL('COPY {} ({}) FROM STDIN').format(sql.Identifier(table), column_sql)) as write:
                    for block in read:
                        write.write(block)
            # lower() is locale-dependent (e.g. local Ō versus production ō).
            # Compare every source field, status, date and other generated field;
            # the search projection is correctly regenerated by each database.
            ignored = release.CLOCKS + ['search_text']
            expected_content = dict(source.execute(query, (ignored,)).fetchall())
            copied = dict(dest.execute(query, (ignored,)).fetchall())
            assert copied == expected_content, 'Production content mismatch: ' + table
            plan['tables'][table]['verified_content_digest'] = hashlib.sha256(json.dumps(copied, sort_keys=True).encode()).hexdigest()
            print('Verified copied', table, len(copied), flush=True)
        plan['backup_id'] = a.backup_id
        plan['verified'] = True
        plan['publication_changes'] = 0
        plan['search_projection_note'] = 'Locale-generated lower(search_text) differs for some Unicode capitals; all other content fields verified identical.'
    release.core.save_new(a.output, plan)


if __name__ == '__main__':
    main()
