#!/usr/bin/env python3
"""Import a pinned, source-evidenced selection of missing named museum artists."""
import argparse,importlib.util,json
from pathlib import Path
import psycopg
from psycopg.rows import dict_row
s=importlib.util.spec_from_file_location('research',Path(__file__).with_name('research-overnight-smk-new-artists.py'));research=importlib.util.module_from_spec(s);s.loader.exec_module(research);core=research.core;smk=research.smk
SOURCE='overnight-smk-new-artist-authorities-20260915'
def apply(run,target):
 data=json.loads((run/'plan.json').read_text());manifest=json.loads((run/'plan-manifest.json').read_text());assert core.sha((run/'plan.json').read_bytes())==manifest['sha256'];records=data['records'];backup=Path.home()/'Library/Application Support/Artline/backups/overnight-images-20260915'/run.name;dsn='postgres://localhost/artline' if target=='local' else core.cloud_dsn();out=[]
 with psycopg.connect(dsn,autocommit=True,row_factory=dict_row) as db:
  with db.transaction():
   db.execute('SELECT pg_advisory_xact_lock(559220260915)');people=db.execute("SELECT a.id::text,a.display_name,a.birth_year,a.death_year,ARRAY(SELECT al.alias FROM artist_aliases al WHERE al.artist_id=a.id) aliases FROM artists a WHERE a.status<>'archived'").fetchall()
   before=db.execute("SELECT to_jsonb(a) artist FROM artists a WHERE a.slug=ANY(%s) OR a.id IN (SELECT entity_id FROM external_identifiers WHERE entity_type='artist' AND scheme='smk-person' AND external_id=ANY(%s))",([c['slug'] for c in records],[c['source_creator_id'] for c in records])).fetchall();p=backup/(target+'-new-artist-preimages.json')
   if not p.exists():core.save_new(p,{'at':core.now(),'existing':before,'plan_sha256':manifest['sha256']})
   codes={r['code'].strip() for r in db.execute('SELECT code FROM countries').fetchall()};db.execute("INSERT INTO sources(slug,name,source_type,base_url,terms_url) VALUES(%s,'SMK: independently verified named artist authorities','museum_api','https://api.smk.dk/api/v1/person',%s) ON CONFLICT(slug) DO NOTHING",(SOURCE,smk.METADATA_TERMS));sid=db.execute('SELECT id FROM sources WHERE slug=%s',(SOURCE,)).fetchone()['id']
   for c in records:
    pid=c['source_creator_id'];aid=c['artist_id'];facts=c['person_facts'];assert facts['id']==pid and c['source_record_url']=='https://api.smk.dk/api/v1/person?id='+pid;assert c['selected_source_objects'];assert c['birth']==research.life_interval(facts,'birth') and c['death']==research.life_interval(facts,'death');assert set(c['countries'])<=codes and c['countries']==sorted({research.COUNTRIES[n] for n in facts.get('nationality',[]) if n in research.COUNTRIES})
    existing=db.execute('SELECT id::text,slug,display_name,birth_year,death_year,status FROM artists WHERE id=%s OR slug=%s FOR UPDATE',(aid,c['slug'])).fetchall();native=db.execute("SELECT entity_id::text FROM external_identifiers WHERE entity_type='artist' AND scheme='smk-person' AND external_id=%s",(pid,)).fetchall();assert not native or native==[{'entity_id':aid}]
    conflicts=research.identity_conflicts(facts,[x for x in people if x['id']!=aid]);assert not conflicts,'Possible existing painter requires reconciliation: '+pid
    if existing:
     assert len(existing)==1 and existing[0]['id']==aid and existing[0]['slug']==c['slug'] and existing[0]['display_name']==c['display_name'] and existing[0]['status']=='review' and native;out.append({'artist_id':aid,'source_creator_id':pid,'outcome':'already_present'});continue
    birth=c['birth'];death=c['death'];timeline=(birth['display']+' – '+death['display']) if birth['year'] and death['year'] else ('born '+birth['display']+'; died '+death['display']);basis='life' if birth['year'] and death['year'] else 'estimated'
    db.execute("""INSERT INTO artists(id,slug,display_name,sort_name,normalized_name,entity_type,birth_year,death_year,birth_display,death_display,birth_precision,death_precision,timeline_start_year,timeline_end_year,timeline_display,timeline_basis,geography_review_state,status,created_by,updated_by)
     VALUES(%s,%s,%s,%s,%s,'person',%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,'classified','review',%s,%s)""",(aid,c['slug'],c['display_name'],c['sort_name'],c['normalized_name'],birth['year'],death['year'],birth['display'],death['display'],birth['precision'],death['precision'],birth['lo'],death['hi'],timeline,basis,core.ACTOR,core.ACTOR))
    db.execute("INSERT INTO external_identifiers(entity_type,entity_id,scheme,external_id,canonical_url,source_id,retrieved_at) VALUES('artist',%s,'smk-person',%s,%s,%s,%s)",(aid,pid,c['source_record_url'],sid,c['metadata_capture']['retrieved_at']))
    db.execute("INSERT INTO artist_aliases(artist_id,alias,normalized_alias,alias_type) VALUES(%s,%s,%s,'alternate') ON CONFLICT DO NOTHING",(aid,facts['name'],smk.norm(facts['name'])))
    for country in c['countries']:db.execute("INSERT INTO artist_countries(artist_id,country_code,relationship_type,is_primary,note) VALUES(%s,%s,'cultural_affiliation',false,%s) ON CONFLICT DO NOTHING",(aid,country,'SMK person authority nationality labels: '+', '.join(facts['nationality'])+'. Cultural affiliation; not a museum-location or exclusive citizenship claim.'))
    evidence={'person_facts':facts,'person_capture':c['metadata_capture'],'country_mapping':{n:research.COUNTRIES[n] for n in facts['nationality'] if n in research.COUNTRIES},'country_note':'Original source nationality labels retained; mapped as cultural affiliations, never inferred from museum country.','corroborating_selected_objects':c['selected_source_objects'][:3],'chronology_note':'Original museum person life intervals retained. A ranged birth does not become an invented exact birth year. Artwork creation dates are verified separately.','identity_note':'Exact and similar existing names with overlapping life years checked; no existing identity was merged. Only source facts, no authored biography.'}
    db.execute("INSERT INTO citations(entity_type,entity_id,source_id,field_name,source_record_id,source_url,evidence_note,retrieved_at,created_by) VALUES('artist',%s,%s,'museum_person_identity_country_chronology',%s,%s,%s,%s,%s)",(aid,sid,pid,c['source_record_url'],json.dumps(evidence,ensure_ascii=False),c['metadata_capture']['retrieved_at'],core.ACTOR));people.append({'id':aid,'display_name':c['display_name'],'birth_year':birth['year'],'death_year':death['year'],'aliases':[facts['name']]});out.append({'artist_id':aid,'source_creator_id':pid,'outcome':'inserted'})
  checked=db.execute("SELECT count(*) n,count(*) FILTER(WHERE status='review' AND published_at IS NULL AND geography_review_state='classified') ok FROM artists WHERE id=ANY(%s::uuid[])",([c['artist_id'] for c in records],)).fetchone();assert checked['n']==checked['ok']==len(records)
 core.save_new(run/(target+'-artists-verified.json'),{'at':core.now(),'counts':checked,'records':out});print(target,'New source artists verified',len(out),flush=True)
if __name__=='__main__':
 p=argparse.ArgumentParser();p.add_argument('--run',type=Path,required=True);p.add_argument('--target',choices=['local','cloud'],required=True);a=p.parse_args();apply(a.run,a.target)
