"""Explicit editorial dispositions for all180 selected native Ferens objects."""
import collections,importlib.util,json
from pathlib import Path
z=importlib.util.spec_from_file_location('f',Path(__file__).with_name('museum-expansion-ferens-facts-20261009.py'));f=importlib.util.module_from_spec(z);z.loader.exec_module(f);m=f.m;RUN=f.RUN;ref=f.ref;checked=f.checked
HOLDS=dict(f.SOURCE_HOLDS)
HOLDS.update({
 3:'Attributed Stevens landscape requires comparison with existing Forest Landscape with Hermitage1614. The two Ferens February objects have distinct scenes and inventories, but external identity remains unresolved.',
 5:'Second attributed Stevens February landscape has a different scene from6189; external Stevens/Hermitage version comparison remains unresolved.',
 8:'Anonymous Dutch Nativity has cross-catalogue seventeenth-century and undated northern Nativity leads; attribution history and physical identity unresolved.',
 10:'Gheeraerts female portrait variants require direct physical comparison; named sitter in later inscription is not authoritative identity.',
 11:'Ribera philosopher versus existing musician portrait requires object-version comparison.',
 13:'De Keyser named portrait versus existing Scholar1631 requires physical identity review.',
 17:'Attributed van der Helst young-woman/girl variants and other northern portrait leads need physical comparison.',
 18:'Champaigne Annunciation1644 has exact same-maker/title/date lead2004.31 plus French variants; do not duplicate.',
 20:'De Blieck church interiors1652/1654/1655 need composition and version comparison.',
 21:'Ruisdael wooded landscape and wheatfield variants need physical comparison beyond translated titles.',
 25:'Gijsbrechts studio-wall/vanitas variants need physical comparison; missing structured maker supplied only by literal native narrative.',
 27:'Bakhuizen rough-sea/yacht variants1692/1694/1695 require physical comparison.',
 28:'Follower-of-Canaletto canal view has numerous Canaletto/Bellotto and Venetian variants; attribution history/version unresolved.',
 30:'Anonymous English Farm Scene has named nineteenth-century generic-title candidates; attribution/identity unresolved.',
 33:'Wilson Italian Landscape Morning and classical landscape versions need physical comparison.',
 34:'Wilson Dinas Bran from Llangollen1772 overlaps native circa1770 composition; physical identity unresolved.',
 36:'Zais ruined-tower landscape may overlap native birdcatchers composition; physical identity unresolved.',
 50:'Follower-of-Wilson waterfall/river-valley variants and attribution histories need physical comparison.',
 61:'Attributed Romeyn landscape/animals variant requires physical comparison; false monogram is not creator identity.',
 82:'Existing John Russell George Birkbeck1805 is a likely same-work lead; reconcile instead of adding.',
 87:'Harlow Portrait of a Head1805–1815 may be an alternate identity for Rebecca Feltham1811; compare objects.',
 94:'Multiple Constable cloud studies include1821/1822 works; exact versions unresolved.',
 99:'Existing Carmichael Shipyard at Hessle Cliff has exact title but1820 versus native1829; likely duplicate needs reconciliation.',
 119:'Chambers Shipping off the Mumbles1838 versus Shipping on the Medway1838 needs composition and title history.',
 122:'Bright windmill landscape1841 overlaps native1840–1848 work; identity unresolved.',
 131:'Binks PS Kingston1824 versus native1843 paddle-steamer scene requires comparison; Hull museum network context retained.',
 132:'Herring Horse1842 and native brown horse1844 require physical comparison.',
 140:'Shayer Coast Scene1822 versus native1846 Dutch fishing craft requires physical comparison.',
 148:'Herring Horse1842 and native chestnut horse1852 require physical comparison.',
 151:'Johnson Alicante Spain1853 matches native Alicante Sakkia1853 locality/date; compare watercolor versions.',
 160:'Van Schendel candlelight markets1857/1869 require physical comparison.',
 176:'Generic Cole landscape has George Vicat and George/Thomas/Ethel Cole identity leads; version and creator reconciliation needed.',
 199:'Redmore Calm on the Humber1868 versus Hull from the Humber1874 needs composition comparison.',
 201:'Existing artwork009b5b58-fff5-52de-abfd-89532c8d8d86 has same2005.6058 inventory, maker and1874 date under Coach in a Snowstorm; reconcile Hull institutional evidence instead of duplicating.',
 203:'Existing artworkdce9c3e7-3d56-5691-bb46-6bc31e9efc2d has same2005.6057 inventory, maker,title and1875 date; reconcile Hull institutional evidence instead of duplicating.',
 204:'Existing artwork026a2863-31f4-558b-ae0c-15385ab4cbe1 has same2006.2666 inventory,maker,title and1875 date; reconcile Hull institutional evidence instead of duplicating.',
})
NOTES={
 2:'One accessioned three-panel ensemble, counted once. Native narrative identifies adult Christ with Benedict and Baptist; the Beccafumi lead is Madonna and infant John. No component entry added. Preserve follower qualification.',
 6:'Inscribed1581 infant Cornelia Burch, aged two months. Retain attributed Dutch School, without a named artist.',
 9:'Retain source Durtch School spelling. Native landscape inventory4885 differs from Swift watermill1860 inventory6205; qualified school label does not create an artist.',
 16:'Narrative explicitly calls the artwork seventeenth century; do not use suspicious structured1641–1692 endpoints as creation. No named-yacht candidate found.',
 19:'Exact generic Still Life leads have different named makers; no Janssens/Elinga object match or Ferens accession collision. Museum narrative identifies the jug,glass,silver tray and citrus composition.',
 31:'Native attributed Richardson1704 portrait is separate from Ramsay Lady Holland1766; preserve attribution.',
 35:'Native1739 monochrome oval Ganymede with eagle differs from existing1733 Jupiter disguised as Diana with Callisto.',
 38:'Unknown copyist after Reynolds, not a work assigned to Reynolds. Generic Supper/Press Gang title-similarity leads have different subjects and makers.',
 39:'Source explicitly says late eighteenth century. Exclude repeated Rathbone lifespan1750–1807; retain full century bounds and qualifier.',
 40:'Source explicitly says late eighteenth century. Distinct house/bridge composition versus Rathbone cattle/lakeside scene; separate inventories and descriptions.',
 41:'Named double portrait with standing man,seated woman and dog differs from single Portrait of a Lady lead. Count full work once; source photo detail is not a separate artwork.',
 44:'Joseph/Claude-Joseph Vernet coastal painting; title lead Four Battle Scenes belongs to Emile-Jean-Horace Vernet and has a different subject/date. Same surname is not same creator.',
 45:'Benjamin West1763 copy after Guido Reni retained as qualified label. Baldung,Altdorfer and Cranach subject repeats are separate named sixteenth-century works.',
 46:'Native signed1764 standing male Francis Burdett differs from Cotes Portrait of a Lady1768.',
 54:'Marlow1787 painted bridge differs from Buhot1884 print entries.',
 62:'Native Claes Molenaer winter scene is explicitly attributed by museum; generic winter-title leads carry other maker identities. No Molenaer version or accession match found.',
 63:'John Raphael Smith pastel of named Thompson couple1800. Matsys Moneylender and Wife1514 is a token/alias false creator hit with different maker,medium and subjects.',
 64:'Date/Period1800–1814 retained;1809 in title describes the view and is not substituted as an exact creation year.',
 66:'English School with possible Norwich School qualification retained. No named painter is invented.',
 69:'Russian School nineteenth-century icon on panel with oil,gilding and incising. Saint John with severed hand and Virgin icon; no object identity match found.',
 70:'Russian School nineteenth-century painted/gilded panel. Other Birth of the Virgin leads are named earlier European paintings,drawings or prints,including distinct Anagnostou1704 tempera icon; no shared inventory or physical identity.',
 71:'Keep Girtin attributed qualification; source explicitly distinguishes this1801 work from1799 original sketch and other compositions.1851 church rebuilding is not artwork creation.',
 72:'Unknown artist preserved. Compact-inventory lead1981.14.3 is Labourers, not KINCM:1981.143; punctuation is semantically significant and source title/creator differ.',
 73:'Native Chinese School label is cultural attribution; narrative unknown artist retained. About1810 lies within published1802–1822 range.',
 75:'Distinct miniature on ivory of East Indies procession; exact shortened Procession lead is Stefano Della Bella drawing, not this school-labelled miniature.',
 76:'School of George Chinnery, unknown individual maker. Three Hustwick Loss of a Merchantman panels are unrelated title-similarity hits with different maker and scene.',
 81:'One watercolor depicts Dauntless in three positions. This is one composition, not three artworks; existing General Coote by Holman is a different ship and maker.',
 85:'Native narrative explicitly names Charles James Sartorius and1810; unlike earlier1787 leads, this date does not precede supplied1794 birth. Keep unlinked source label; no painter authority added.',
 91:'Artwork date1819 remains separate from depicted event23April1642.',
 93:'Haydon1830-era painted teak panel is distinct from Maes,Voorhout and Cranach repeats of this biblical subject.',
 96:'Leprince1824 coastal painting has different native maker from Bonington and Rodney Burn title repeats; no shared accession or creator evidence.',
 108:'Native De Noter life-date typo1779–1943 retained only as evidence, not used as artwork creation; literal artwork1833 retained.',
 124:'Smetham medieval-costume couple differs from Ferdinand von Wright Surprise1880; source mid-nineteenth-century statement retained.',
 125:'Retain attributed David Roberts rather than upgrading the structured maker.',
 135:'Bannister1844 Savile Street scene differs from Willoughby Westerdales Yard circa1810, distinct maker and inventory.',
 146:'Native1850 left-profile Mr Wright and1851 Francis Wright have distinct accession5009/5008 and portrait descriptions. Equal dimensions alone do not merge them.',
 147:'Native1851 half-length balding Francis Wright differs from1850 left-profile younger Mr Wright; separate accession and described poses.',
 149:'1852 architectural design painting is separate from opening1854,wartime destruction1943 and demolition1947. No creation year inferred from those events.',
 153:'Native signed/named Henshaw lake landscape; other exact-title leads are Ander1854 and Olin Dows1930s, different maker identities.',
 156:'Native1855 watercolor date, not whole1853–1856 depicted-war interval.',
 165:'Sidney Richard Percy1858 and Douglas Percy Bliss unknown-date work are different artists; Percy token is a false same-creator lead.',
 168:'George Clarkson Stanfield1859 pastel/gouache coastal sketch distinct from Paul Maze,John Absolon and Theo van Rysselberghe title repeats.',
 178:'Baxter1864–1865 rural-costume sisters distinct from named other artists in exact-title pool; no shared maker/inventory match.',
 180:'One native Nibbs Ann barque1866; Binks Halcyon1832 is a different vessel and maker.',
 182:'Ralph Stubbs1866 beached brig composition differs from1869 wreck at sea and1868 old hulks. Preserve separate inventories and described scenes, not generic Marine titles alone.',
 183:'Thomas Pelham Hall1868 literary scene differs from Leslie1842 and Frith1865 versions; source maker retained.',
 186:'Explicit1868 study retained as study in title. Existing Meissonier Defense of Paris1870/71 has different subject. Source mistaken play identification remains evidence only.',
 187:'Charles Hunt1868 children playing differs from William Morris Hunt1857–1858 Fortune Teller; shared Hunt surname is a false creator hit.',
 188:'Brooks signed1868 work and full reverse inscription retained; reverse contains writing, not a second artwork. Howgate title repeat has a different named maker.',
 190:'Duncan1869 watercolor coastal view differs from Vernet1760s Coast Scene and Ferens Redmore/Sampson works; distinct maker,media and accessions.',
 191:'Ralph Stubbs1869 wrecked ship floating offshore is separate from1866 beached brig and1868 hulks, with native differing scenes and accessions.',
 193:'Native unknown artist and1870–1930 range retained; narrative about1900 supports creation, not sitter lifespan.',
 196:'Native narrative about1872 qualifier retained as circa; not silently rendered exact1872.',
 197:'Native label explicitly calls this the first preliminary study for life-size Muck Rake.1872 signed date, oil panel and555×410 overall distinguish it from207,oil canvas2515×1575 circa1877.1889 is later label date.',
 205:'Provis1875 cottage reading scene differs from Mary McEvoy1901 Interior Girl Reading.',
 207:'Life-size canvas circa1877 and separate inventory5251 differ from preliminary panel5253. Count each physical painting once; do not add second unselected study mentioned in label.',
}
def build():
 rows=m.load(RUN/'native-candidates-001.json.gz')['rows'];identity=m.load(RUN/'native-identity-001.json.gz');comps={c['number']:c for c in identity['comparisons']};out=[]
 for row in rows:
  n=row['number'];record=m.load(checked(row['source_reference']));assert f.facts(record)==row['facts'];v=row['facts'];c=comps[n];hold=n in HOLDS;basis=HOLDS[n] if hold else NOTES.get(n,'Individually reviewed native accession, named subject, maker, date and description. No matching physical object found in museum scope or bounded creator/title/source comparison. Retain original source wording and unknown fields.')
  if not hold:assert row['state']=='candidate' and not c['source_hits']
  out.append(dict(number=n,source_id=row['source_id'],institution_id=f.IID,facts=v,index=row['index'],source_reference=row['source_reference'],comparison=c,state='editorial_hold' if hold else 'approved_review_only_addition',confidence=None if hold else .95,basis=basis,limitation=v['source_limitation'],retrieved_at=record['capture']['receipt']['retrieved_at']))
 assert len(out)==180 and len(HOLDS)==44;return out
def main():
 dest=RUN/'editorial-reviewed-001.json.gz';assert not dest.exists();rows=build();deps=[RUN/n for n in ['native-candidates-001.json.gz','native-identity-001.json.gz','identity-citations-001.json.gz','native-captured-001.json.gz','native-selection-001.json.gz']]
 m.save(dest,dict(at=m.now(),decisions=rows,dependencies=[ref(p) for p in deps],reviewer_reference=ref(Path(__file__).resolve()),policy='Explicit per-object editorial dispositions, not acceptance from similarity scores. Source holds and unresolved variants deferred. No changes to existing records,artist identities,images or statuses; native anonymous and qualified creators eligible when source supports the selected physical work. Confidence is editorial,not calibrated.'));print(json.dumps(dict(states=dict(collections.Counter(r['state'] for r in rows)))),flush=True)
if __name__=='__main__':main()
