"""Explicit wave71 selection and individual follow-up decisions, 8 October 2026."""
DEFERRED_ECOUEN={
519:'Retain CL347 with the unresolved sleeping-ivory CL348/349 physical-version comparison.',
531:'Keep the previously recorded OA431/ECL22282 attribution, size and description conflict open.',
577:'Finish the sparse Reni and Thévenin comparison identities; web leads are discovery only.',
580:'Keep the CL15226/15227 wax-profile physical-version question open.',
581:'Keep the CL15226/15227 wax-profile physical-version question open.',
583:'Finish source-sparse generic female-portrait comparisons before release.',
584:'New Louvre OA428 page for candidate586 uses historical CL22278, overlapping this ECL22278. Resolve the historical alias/sitter conflict between Francesco della Rovere and Anne de Montmorency; do not infer a typo.',
585:'Keep the OA427/ECL22279 sitter/date and measurement conflict open.',
586:'Louvre OA428 securely names current ECL22280 and supports Écouen deposit, but its historical CL22278 overlaps candidate584. National diameter12cm versus Louvre10cm also remains literal. Resolve cross-record historical inventory before release.',
587:'Finish sparse male-portrait comparisons and the former-Louvre wax identity review.',
589:'Finish sparse female-portrait comparisons and the former-Louvre wax identity review.',
590:'Finish sparse female-portrait comparisons and the former-Louvre wax identity review.',
598:'Keep the stated eighteenth-century sitter versus sixteenth-century manufacture contradiction open.',
610:'Keep the CL348/349 sleeping-ivory physical-version question open.',
611:'Keep the CL348/349 sleeping-ivory physical-version question open.',
615:'Resolve the two sparse Timoleonthos1951 Rouen records; do not describe them as Cyprus holdings.',
624:'Resolve the same sparse Timoleonthos1951 Rouen comparison records.',
627:'Resolve the sparse Louvre Agostino Carracci Annunciation identity; current search results are related drawings, not the selected comparator.',
628:'Resolve the sparse Louvre Ludovico Carracci Virgin identity; current search results do not establish the exact painting.',
632:'Keep plural furniture supports/object-unit question open.',
644:'Finish the sparse Agostino Carracci comparison before release; preserve former door/parent inventories.'}
SELECTED=set(range(511,651))-set(DEFERRED_ECOUEN)|{439,488}
FOLLOWUP={
439:'Exact existing WikiArt c1748 Pompadour page and its selected image checked. Image is a close-up female head/neck without a mask or ball costume; this is physically/compositionally different from native J120, the116x90cm1742 pastel portrait of Suzanne Marie Henriette de Rieux in ball dress holding a mask. Do not substitute the separate1755 Louvre Pompadour. Native J120 names the Getty94PC39 portrait as her husband, not this work. Existing WikiArt record remains unchanged.',
470:'Exact preserved V&A primary record O84952/DYCE.76 individually read and citation response hash verified. Attributed Hamilton oil sketch of Sarah Siddons has estimated13.375x11.25in work dimensions and535x485x50mm frame measurements, neutral brown background and Dyce bequest. Cognacq-Jay J75 is51x40.5cm and Cognacq1928 legacy, with Romney attributed/Lawrence former labels. The specific Hamilton comparison is distinct; other generic portrait comparisons remain unresolved.',
488:'Exact preserved Finnish National Gallery object390567/AI548 individually read and original response hash verified. Attributed-Boucher oil canvas41.5x32.5cm, Antell1893 bequest, is distinct from the French-school copy J15,33.5x29cm, Cognacq1928 legacy. The native page explicitly identifies Boucher as model author and his workshop as former attribution; it dates the lost prototype1750–1760, while this copy retains the literal18th-century object period. J14 Psyché is a separately titled and described companion, not a second notice for J15.',
511:'Sparse Chagall Noah title lead has a different named creator and stated1961–1966 date, versus attributed Bair bronze medallion19.8cm1601–1625. It has no shared source/inventory identity. Existing sparse fields remain unverified; distinctness is an editorial assessment using these combined signals, not a newly verified Chagall holding.',
524:'Sparse Breker La Force has named twentieth-century maker and stated1939 date versus Meit24.5cm carved wood1526–1550. No common inventory or source identity. Féron comparator is a nineteenth-century painted decoration. No missing medium is inferred for Breker.',
527:'Picasso MP3179 is an explicit1925 zinc monotype, distinct from the sixteenth-century23cm cast bronze dancer; Ingres studies are separate paper drawings.',
535:'Goltzius Marcus Curtius KKSgb8155 and Met49.97.691 are1586 copper engravings, distinct from this215x110cm painted/gilded leather panel1590–1600. Prototype attribution remains d’après.',
536:'Fontaine sparse child portrait has a different named nineteenth-century maker/date, no common source/inventory identity; it does not identify the seventeenth-century23cm terracotta Duquesnoy-attributed child. No unknown comparator medium is filled.',
538:'Brebiette etchings, Moreau1767 pen/watercolor, Masson1968 ink drawing and Baj1970 aquatint are physically different from the5.5cm fifteenth-century bronze. Corinth PNM1053 has a distinct named maker and1896 date with no shared identity; medium remains unknown in this comparator.',
540:'Clodion-manner1977-6 is a15.2x29.3x4cm relief of faunesse/little fauns, distinct from the43cm figure-and-child terracottaCL12534B. Rodin1955.657 is watercolor/graphite. Companion male faunCL12534 is distinguished by its male composition.',
542:'Exact WikiArt Desiderio1460 image inspected: broken rectangular shallow relief showing the Virgin cropped above the head and a large child held before her chest, not a full-length statue. National ECL11662 is an en-pied92cm marble Virgin with headdress/rosary, from Breuil-sous-Orbais,1520–1540. Composition and object form establish different works; do not assign the WikiArt photo to this statue. Wagner1950 is a72x59cm Isorel work, also distinct.',
543:'Manlius KKSgb18798/KKSgb18800 and Met49.97.694/51.501.39 are1586 engraved designs/printed impressions; this is a215x110cm painted/gilded leather panel1590–1600, separate from Curtius and Calpurnius by subject and e/f/g inventories.',
547:'Goltzius KKSgb18990 Calphurnius is a1586 copper engraving, distinct from the215x110cm painted/gilded leather panel after the design.',
567:'Exact National Gallery NG2092 primary page checked: Moretto Saint Joseph is oil on wood153.6x54.1cm, about1540, part of painted shutters and Cohen1906 bequest. ÉcouenCL11249 is an eighteenth-century42cm carved wooden statuette with estoffage. Ballin is an etching/roulette and Yale2018.69.1 a tempera/gold panel; none represents this sculpture.',
571:'Bellange1977.586.1 is a trimmed30.1x17.1cm etching1595–1616, physically different from87cm carved wooden Saint Jude(?)CL21305. Questioned Jude/Matthias subjects stay qualified.',
572:'Sparse Delacroix1824 Sainte Catherine896.1.8 is a different named/date identity with no common source/inventory; the Écouen object is anonymous17th-century carved wood14cm. Other primary matches are paintings or a15th-century50cm stone figure. No medium is invented for the sparse record.',
574:'Sparse Laparra Judith has a named late19th/early20th-century identity, no common accession/source, versus anonymous16th-century16x22cm carved wooden group. Its unverified sparse metadata is not promoted to accepted holding.',
579:'GaultierP957 is an engraved paper portrait with distinct sheet/image dimensions, not the12cm polychrome terracotta medallion inscribed1580.',
588:'All six Diana comparisons are explicit oil paintings with substantially larger canvases/panels; none is a13cm wax relief with bow/dog in a wooden frame. Fresh searches include literalINV432, CL/ECL22283 and discovery-onlyOA432; no source, inventory or related-inventory hit. Do not assert OA432 as an established alias.',
591:'Fresh literalINV439, CL/ECL22293 and discovery-onlyOA439 search returns no identity/inventory hit. The9cm seventeenth-century framed wax female relief differs from selected6cm sixteenth-centuryCL22291. Picasso works are graphic/painted two-dimensional objects, Drivier a44.5cm bronze and Schalcken a78.5x64cm oil canvas.',
592:'Fresh literalINV437, CL/ECL22291 and discovery-onlyOA437 search returns no identity/inventory hit. This6cm sixteenth-century lace-collar female wax profile remains distinct from the9cm seventeenth-centuryCL22293; no dimensions silently interpreted as frame dimensions.',
593:'Fresh literalINV2782, CL/ECL22288 and discovery-onlyOA2782 search returns no identity/inventory hit. The framed7x5cm sixteenth-century wax child relief differs from Puvis paper drawing15x11cm and Cordier/Romain oil paintings. Davillier provenance and unknown acquisition date remain literal.',
608:'Bonington WallaceP323 HenriIII is an1828 oil canvas54x64.4cm, not the10cm sixteenth-century wax portrait medallion.',
625:'Tura is a tempera painting on poplar, Lucas a paper etching, and LechevallierPE741 a nineteenth-century painting on stone118x91.5cm; none is the110cm seventeenth-century carved wood figure.',
631:'GuifardPE7001-4 is a set of1877 canvas paintings, not this14x39cm sixteenth-century wood relief with questioned wax/modeling technique. Literal question marks retained.',
635:'Fresh related-inventory search for the dismantled buffetDS1445/CL127 and individual panel aliases finds no existing object identity. This10x33cm walnut cherub panel is a separate physical piece; the full buffet is not added.',
642:'Fresh related-inventory search includes ECL12024 and currentECL21347, no existing match. The national record explicitly identifies12024 as another panel in the same ensemble; retain that relationship, add only this32.5x27.7cm fabulous-animal relief.',
645:'Fresh parent/related inventory search includes218 and218C with no existing identity. Add only the35x23cm figurative Diana/deer panel218A; the plural structural supports218C remain held.',
646:'Source history for companion648 explicitly records the buffetDS1445/CL127 dismantled by1887. This46x39cm walnut adolescent Cupid panel is separately described; no whole-buffet artwork is counted.',
647:'Walnut57x45cm11575A depicts Mars/Venus undressed by nymphs; B depicts discovery by gods. These are separately described panels of the dismantled buffet, not two titles for the same panel.',
648:'Walnut57x45cm11575B depicts discovery by gods, unlike11575A undressing by nymphs. Full source history identifies dismantled buffet and marked pieces; historical design labels do not create executing-artist links.',
650:'Lemoyne92.2.1 is a25.8x31cm oil canvas1717–1720, not this26x20cm sixteenth-century carved wood relief.'}
for n in [512,537,544,545]:FOLLOWUP[n]='Bellows1936.566 is a1917 lithograph, physically different from this catalogued cast-bronze or carved-ivory figurine. Distinct within-batch figurines retain their specific size, composition and qualified maker labels.'
for n in [560,564,637,641]:FOLLOWUP[n]='Full generic male-head pool checked. Primary comparisons are paintings/drawings/prints with explicit other physical media; sparse Torrents, Picasso1908 and Chassériau records have different named nineteenth/twentieth-century identities without common source/inventory. Their unknown media remain unknown. The selected17th-century18/24cm terracotta heads and16th-century45x19/36x16cm carved wood panels are distinguished within batch by size, treatment and composition.'
for n in [573,616,617,621]:FOLLOWUP[n]='Primary Tommasi732 and VenezianoMI395 comparisons are tempera paintings on wood, physically distinct from the selected silver-over-wood or ivory Virgin groups. Each sculpture retains its individual height, treatment and child pose; source creation/period contradictions in comparator paintings are not repaired.'
FOLLOWUP[639]='Picasso MP1990-12 is81x64.7cm dated1926; MP2046 is a1925 zinc etching. Neither shares identity with the16th-century38x20cm carved wood female medallion; other primary comparisons have physically different media.'
FOLLOWUP[640]='Full female-head pool checked: SMK KMSr33 and Scott1952.13.150 are oil canvases; Matisse is pencil on paper, Monet5126 a52x41cm canvas; Picasso graphic/painted works and sparse nineteenth-century Henner identity have no common inventory/source with the16th-century36x16cm carved wooden profile. Other primary works include HenryCros wax painting on paper/card, not a carved wooden relief.'
GENERAL='Fresh source-ID, URL, inventory/alias, related-object, title and maker comparisons checked. Explicit material exclusions were reviewed against physical-object descriptions; all date-only triage cases in this Écouen release were individually displayed and also have distinct object media/forms or substantially different named creator/period identities. Broad chronology alone does not settle same-object source contradictions. Empty comparison results mean no match in the bounded search, not proof that no duplicate exists anywhere. Sparse unrelated named-creator matches retain their unknown fields; they are assessed editorially, without inventing a medium or accepted holding. Selected national source facts, earlier object notes, comparison reasons and limitations remain preserved.'
