"""Individual physical-object decisions from current captured Joconde records."""
NOTES={
1:'Unknown maker and medium remain null. This 97.3 by72.9cm seated Baylon with two angels, hut and monstrance differs from existing46.5 by37cm copper and the separately inventoried kneeling/bust compositions selected here.',
5:'Anonymous98 by135cm canvas: seated Christ gives both species to Peter, basin in foreground. Distinct from existing Cattaneo77.5 by44.5cm upright canvas and selected77.5 by63.1cm version held for further comparison.',
7:'One independently inventoried copper panel22 by16.6cm, Vierge de Pitie, paired with separately numbered Ecce Homo1.8.1. Count this panel once; existing same-title works are wood40.8 by27.3 and canvas113 by85cm.',
10:'Anonymous109.8 by92.8cm wooden Mass of Gregory panel, documented as first museum acquisition in1879. Passion instruments distinguish composition; no exact-title or native counterpart.',
11:'Small15.7 by12.2cm copper panel of pilgrims meeting on the road, not an Emmaus meal. Existing named-creator same-title works have different supports/formats and makers; preserve anonymous label.',
12:'Anonymous35.5cm square canvas of Jesus on steps with six men and two books, source sixteenth century. Other same-title works have named creators and different documented large or upright formats.',
16:'One seventeenth-century oil painting on marble31.9 by23.1 by1cm, Helena with cross and Constantine behind. Existing Ingres same-title sheets are pencil/tracing-paper drawings. Dates306/313/326 belong to represented history.',
17:'Anonymous74.1 by38.2cm arched-top canvas: Baylon kneeling with open arms, chalice and village. Existing same-title46.5 by37cm copper and selected bust/seated canvases are distinct supports and compositions.',
19:'Anonymous93.5 by72cm canvas: bust-length Baylon with hands at chest and angel with monstrance. Separate from seated97.3 by72.9cm composition and kneeling arched-top canvas despite same subject.',
20:'Anonymous94.5 by51.2cm eighteenth-century canvas of Claire and nuns repelling soldiers with monstrance. Same-title Lorenzo work is54 by20cm gilded poplar, a different object.',
24:'Anonymous109.5 by83.5cm wooden Catherine stigmatization panel, nun reading and golden rays from altar crucifix. Existing Matteo panel is87 by54cm; original anonymous label and date retained.',
25:'Anonymous196 by167cm Trinity canvas89.1, explicit museum gift. Related1688 Semur painting is another canvas; source independently places this work in first-half eighteenth century.',
26:'Anonymous91 by46cm Thomas of Cori levitation canvas. Source explicitly distinguishes nearby Cavallucci composition; existing Cavallucci work is310 by200cm. Count only this smaller separately inventoried version.',
29:'Anonymous56.3 by45cm sixteenth-century wooden Golgotha panel with three crosses, collecting angels and soldier breaking a leg. Existing named-creator versions have different formats/media; Pordenone prototype reference stays evidence, not an attribution.',
31:'One nineteenth-century oil-painted wooden panel shaped like a cloth,36.3 by30.7cm. It is not a textile; existing Matisse paper and Mellan engraved Sainte Face are different physical works.',
33:'Alophe charcoal portrait of Mme Desfini49 by32.5cm. Existing Alophe Vigier portrait is210 by140cm oil canvas, a different sitter and medium.',
34:'One Alophe/Lemercier/Goupil lithographic Eugenie sheet57.6 by40.8cm. Preserve printer/publisher roles and nineteenth-century creation; sitter life dates1826–1920 are not creation bounds.',
35:'One Albert Ardail1890 etched portrait of his mother Melanie Pageot,32.7 by23.8cm Japan paper. No maker/title/native counterpart.',
36:'One Ardail etching after Loir,1897, image28 by44.5cm on50 by64.7cm paper. The1896 event in its title is not the print date; existing Loir Seine-flood paintings are different objects.',
37:'One1890 Ardail watercolor of the Loing by Fontaine Saint-Jean,22.3 by14.1cm paper. No same creator/title/native counterpart.',
39:'One Bejot1892 nurse etching,12.6 by9.4cm plate on31.5 by21.1cm sheet. Existing Le Prince nurse has different maker and14.5 by18cm image; Duval Le Camus is another maker. Count this impression only, not all15 mentioned.',
40:'One Bejot1893 Nemours-market etching,20 by14.9cm plate on27.5 by17.2cm sheet. No same-title or native counterpart; other Bejot city views are different subjects.',
41:'One Bernard/Monnier colored lithograph Les Cartes circa1828,22.1 by25cm. Existing Cocteau ink-card work is a different maker and medium; preserve contributor labels.',
42:'One Blery1870 Nemours-view etching,22.3 by38cm plate on42.5 by55.6cm paper. Different site from existing woodland works and from the selected Loing river sheet.',
43:'One Blery1860 Bords du Loing etching,26 by39.9cm plate on33.7 by43.8cm paper. Its river location, date and inventory distinguish it from1870 Nemours view.',
44:'One Bocourt/Salmon circa1882 Corot portrait etching,44 by30.7cm, after-letter state. No corresponding named sitter/native print in creator scope.',
45:'One Boilot print after Lhermitte,1882,49.6 by65cm. Source explicitly distinguishes Orsay painting and other institutional impressions. Existing harvest works are oil canvases, not this paper impression.',
46:'One Boulard etching after Meissonier circa1890,57 by44.8cm Japan paper, before-letter proof. Existing Meissonier mounted dragoon is26 by18.5cm oil on wood; exact-title Janin/Cotelle canvases also differ.',
47:'One Bernard Boutet de Monvel1904 colored print,27 by35.7cm plate on31.6 by48cm sheet. Mentioned12/60 auction impression is another example, not an edition number assigned here; Maurice is a different family creator.',
48:'One Maurice Boutet de Monvel1896 Jeanne at Orleans print sheet25 by32cm, individually inventoried. Count the sheet, not the whole illustrated book.',
52:'One Bodmer1886 Fontainebleau etching28 by33.6cm. Existing same-creator charcoal drawing42.5 by60cm has a different medium and support format; other exact-title works are different makers.',
53:'One Chifflart1877 Melancolie print40.7 by28.6cm. Same-title Cranach, Van Loo, Corot, Durer, Vincent and Fetti works have other makers and physical descriptions.',
55:'One Clairet1903 Boyarde lithograph after Wenig,48.4 by33.8cm. Source identifies Wenig1889 Russian Girl oil prototype; existing Wenig title lead has incomplete physical details but names the prototype maker. Preserve explicit reproducer/model roles and1903 print date.',
56:'One De Nittis1875 Derriere un eventail etching35 by25.2cm. Creator scope includes De Nittis aliases; fan/eventail/ventaglio title search found no same-object lead.',
59:'One Didier burin portrait after Delaunay of Gounod circa1879,44 by32.2cm. Source cites other institutional impressions with distinct measurements; no matching named-sitter native object.',
60:'One Doigneau1889 gouache of an old woman spinning,33.2 by24.1cm. Existing Doigneau hunting/dog paintings are different subjects and media.',
66:'One Jouas1917 sheet2022.0.1,45 by29cm, Notre-Dame seen from chapelle Vendome, dated17September.',
67:'One Jouas1917 sheet2022.0.2,28.3 by26.5cm, collégiale seen from Saint-Maclou; distinct full facade view.',
68:'One Jouas1927 sheet2022.0.3,30.8 by24.2cm, Saint-Maclou tower pinnacle, dated2August.',
69:'One Jouas1917 sheet2022.0.4,29.2 by32.2cm, quays and bridge, dated14September.',
70:'One Jouas1927 sheet2022.0.5,25.8 by33.8cm, Ile aux Ormes, dated2August.',
71:'One Jouas1917 sheet2022.0.7,32.1 by24cm, southern buttress of the collegiale, dated September.',
72:'One Jouas1927 sheet2022.0.8,33 by24.3cm, Gothic arch at Limay; individually inventoried architectural drawing.',
73:'One Jouas1917 sheet2022.0.9,32.8 by39.6cm, Hommage a Miguet, Seine and houses from cathedral, dated September.',
74:'One Jouas1917 sheet2022.0.10,29.2 by45.5cm, Hotel de Ville, dated10September.',
75:'One Jouas1917 sheet2022.0.11,36.5 by28.8cm, towers seen from Pardinel property, dated September.',
76:'One Jouas1917 sheet2022.0.12,37.5 by28.8cm, apse from Pardinel property, dated17September; distinct format from the next morning view.',
77:'One Jouas1917 sheet2022.0.13,30.8 by31cm, Caffot house, dated17September.',
78:'One Jouas1917 sheet2022.0.14,29 by35.7cm, walkway between southern buttresses, dated7September.',
79:'One Jouas1917 sheet2022.0.15,24 by39.8cm, Seine islands and Robert property, dated September.',
80:'One Jouas1917 sheet2022.0.16,32.4 by23.6cm, Saint-Maclou and Belle Gabrielle, dated8September.',
81:'One Jouas1917 sheet2022.0.17,29 by38.8cm, title names west facade and Ile aux Dames; description identifies south-tower base balustrade and gargoyles,8September. Preserve both source descriptions.',
82:'One Jouas1917 sheet2022.0.18,46.2 by29.8cm, apse from Pardinel property,18September9am; date and format distinguish17September sheet.',
83:'One Jouas1917 sheet2022.0.19,29.2 by45.3cm, northern tower summit,13September. Landscape orientation differs from6September upright northern-tower view.',
84:'One Jouas1917 sheet2022.0.20,45.3 by29.2cm, north tower seen from south tower,6September. Reversed dimensions are a distinct orientation, date and accession, not a duplicate of2022.0.19.',
85:'One Jouas1917 sheet2022.0.21,47 by30cm, south tower seen from Saint-Maclou,7September6pm.',
86:'One Jouas1917 sheet2022.0.22,30.7 by45cm, northern buttresses,7September; separately catalogued from9September view with different accession and slightly different format.',
87:'One Jouas1917 sheet2022.0.23,37.8 by30.3cm, Saint-Maclou seen from Pardinel balcony, dated September.',
88:'One Jouas1917 sheet2022.0.24,37 by51cm, Notre-Dame roof/buttresses, river, bridge and boats, dated September.',
89:'One Jouas1917 sheet2022.0.25,39.5 by49.3cm, southern balustrade,14September.',
90:'One Jouas1917 sheet2022.0.26,39.3 by28.8cm, south-tower bases,18September8pm.',
91:'One Jouas1917 sheet2022.0.27,31 by48cm, Cercueil house, dated September.',
92:'One Jouas1917 sheet2022.0.28,31 by45.5cm, place de lEtape,14September.',
93:'One Jouas1917 sheet2022.0.29,32.5 by49.2cm, Hotel-Dieu,15September.',
94:'One Jouas1917 sheet2022.0.30,30.5 by45.2cm, northern buttresses,9September. Similar subject to7September sheet2022.0.22; separate signed dates, source inventories and measured sheets retained.',
95:'One Jouas1917 sheet2022.0.31,28.5 by37.8cm, study of Notre-Dame from Limay, dated September.',
96:'One Jouas1917 sheet2022.0.32,29 by45.3cm, vieux pont de Limay,14September. Description says pont de Limeil; preserve this source place-name discrepancy without silently correcting it.',
97:'One Jouas1917 sheet2022.0.33,30.6 by45.4cm, apse,1September; distinct from later Pardinel views.',
98:'One Jouas1883 pencil sheet2022.0.34,13 by29cm, old tower on return from Trouville to Paris,25September. Do not assign the1917 date of neighboring sheets.',
99:'One Biard-related81 by116.5cm canvas of travelling actors, source allows autograph or other reduction of1833 Salon work. Existing Biard134 by193cm canvas is another format; preserve uncertain source role, no artist link.',
100:'One Buthaud faience vase1934–40,29.5cm high16.4cm diameter, oval with abstract discs. Existing Venus glass work145 by200cm is a different object.',
101:'One Callet1803 pastel Aurore45 by100cm. Exact-title Berthelemy work is400 by460cm oil on plaster, another maker and physical version.',
102:'One Caussy faience pagoda dish, second-half eighteenth century,39.5cm diameter6.2cm high. No creator/title/native counterpart; count one vessel.',
103:'One Chabal-Dussurgey1855 floral canvas184 by112cm. Current source documents communal ownership transferred from the state; former state inventory does not make it a current deposit or display claim.',
105:'One Charles Antoine Coypel1730–35 pastel self-portrait60 by51cm. Added right-hand paper strip and fragments form one restored work. Existing same-maker oil portrait92 by73cm is another physical object.',
106:'One Julie Charpentier1791 terracotta male bust,56cm without pedestal66cm total. Same-title database leads are Giacometti/Picasso prints and a Daumier drawing; source identifies a finished terracotta, no bronze cast date inferred.',
107:'One Francois de La Tour1712 Saint-Quentin view,sepia24 by59cm paper mounted on canvas/card. Preserve Francois, not Maurice Quentin; restored support is one physical object.',
108:'One attributed Maurice Quentin de La Tour eighteenth-century hand-study pastel40.8 by24.7cm. Qualified attribution remains literal; expanded DE LA TOUR surname scope has no corresponding hand study.',
109:'One Surugue1755 engraved Jeanne Benozzi portrait after La Tour,41.5 by29cm plate48.2 by35.5cm sheet. Full creator-pool Benozzi/Silvia search found no matching named sitter; preserve model and engraver roles.',
110:'One anonymous-after-La-Tour Jean Paris de Montmartel pastel39 by30cm, source explicitly a rectangular replica of oval LT10. Distinct shape, inventory LT45 and copy attribution retained.',
113:'One Leon Delvigne1942 pastel self-portrait62.2 by49cm, cap, beard and palette. No creator counterpart;346 exact generic-title leads are other named creators, with no anonymous/unlabelled counterpart in this scope.',
114:'One J. Lecourt1820 gouache-on-ivory diadem portrait miniature. Source frame5.4 by4.3cm is smaller than stated object6.6 by5.6cm: retain both literal measurements without correcting them. Other Lecourt creator leads are different named landscape makers.',
115:'One Lemasle1828 black-chalk bedeau study42.8 by18.2cm,2002.35.1FA, for later Messe des Relevailles. Separately inventoried from priest study2002.35.2FA; existing male oil portrait54 by36cm is different.',
116:'One Lemasle1827 graphite/sanguine Oh Mahomet study27.7 by33.2cm, with preparatory grid for Salon painting675. Existing Lemasle portraits are other subjects.',
118:'One Jean Baptiste Lemoyne eighteenth-century terracotta portrait of La Tour,60.5cm with marble base. Other Lemoyne-name results concern Francois/Serge; no matching native object.',
119:'One Leroy1910 charcoal Tendresse53 by45cm. Existing same-title Leroy54 by65cm oil canvas has another medium and landscape orientation.',
120:'One Lematte Scene galante183 by152cm canvas before1887, two women reading, man with rose and Cupid statue. Same-title leads have other creators and different smaller formats/media. Unknown lower creation bound retained.',
121:'One Moreau le Jeune/Saugrain1773 engraved Alexandrine Fanier portrait,34.3 by26.5cm sheet. Gustave Moreau Alexandrine Dureux is another maker and sitter.',
122:'One Ozenfant1960 sea-storm/cloud pastel58 by71cm. Existing Hudson storm painting is150 by104cm oil, a different physical composition.',
123:'One Parant1813 Napoleon left-profile gouache on paper,15 by11.5cm oval. No maker/title/native counterpart; count one miniature.',
124:'One attributed Jan Peeters1650 Saint-Quentin ink view9.7 by30cm. Source says unsigned drawing for an engraving and inconsistently names BA353/BA553; keep attribution and inventory discrepancy, not an engraved-object classification.',
125:'One Perronneau1750 La Tour pastel56 by48cm, Salon portrait in black overcoat. Full creator pool has no La Tour titled counterpart; other portraits depict other sitters.',
126:'One attributed PrudHon first-quarter nineteenth-century pastel43.5 by31cm, presumed Mlle George. Exact-title Riesener record is oil on canvas; qualification and presumed sitter preserved.',
130:'One Valade1763 pastel of engineer Loriot80 by70cm, Salon103. Joined paper strips and partly fixed pastel describe one work. Existing Valade Lemoyne/Silvestre portraits are other sitters.',
131:'One Vincent1773 Tivoli bridge chalk drawing29.5 by41.2cm. Source documents physical separation in2005 from academy fragment2001.36.2FA; count bridge sheet2001.36.1FA once. Creator pool bridge/Tivoli leads have other media or makers.',
132:'One attributed Hans Van Sant seventeenth-century ham still-life canvas,108 by120cm framed, with bread, nuts, wine and beer. Exact-title Van Es wooden39 by56.2cm and Glacon canvas65.4 by92.4cm works differ; preserve attributed maker.',
133:'One anonymous eighteenth-century Voltaire canvas62 by51cm. Exact-title Jules de Goncourt paper etching is another physical medium. Related source inventory1995.6.1 remains evidence, not another addition.',
135:'One Sevres/Merigot1863 painted-porcelain Coupe Rivoli,37cm high45.7cm diameter. Source references companion versions; this specifically inventoried L608 vessel counted once and contributor roles retained.',
136:'One La Tour1739 Frere Fiacre pastel62 by50cm, Salon1739,2005.8.1. Joined papers form one support. Expanded La Tour pool has no Fiacre/Friacre counterpart.',
137:'One Lemasle1828 black-chalk priest study42.5 by29cm,2002.35.2FA, for central figure of later Messe. Separate from narrower bedeau study with distinct figure and inventory.',
139:'One Edmond Alet1909 ink/watercolor fisher portrait on23.2 by39.5cm card. Existing Edmond bridge painting and Maurice Alet works differ in subject, medium or maker.',
140:'One Pierre Andrieu circa1850 oil copy40.7 by32.2cm after Delacroix Scio, explicitly commissioned via Delacroix. Existing Delacroix titled lead represents prototype maker; source copyist and small support distinguish this version and selected Planet100 by81cm copy.',
141:'One Aubeges1833 pencil/gouache paper drawing31 by78cm depicting Lucas1775 Ponts-Jumeaux relief in trompe-loeil. It is a drawing, not the actual sculpture;1775 is prototype date.',
142:'One Andrieu-Geze1935–36 black/gray-wash market sheet24 by19.8cm,88.1.1. Distinct from brown-wash sheet88.1.2 by medium, accession and source title/inscription. Other Andrieu leads are Pierre/Lucien works.',
143:'One Renee Aspe1955 gouache Capitole snow view64.7 by50cm. Existing Aspe corbillard is38 by46cm oil canvas, a different subject and support.',
144:'One Baysse1895 Garonnette oil canvas33 by46cm, signed and dated. No creator/title/native counterpart; literal single-name creator preserved.',
146:'One Benezet brown-ink street/geese sheet22.5 by16.8cm, second-half nineteenth century. Existing Benezet paintings show other subjects;1918 collector annotation and1945 gift are not creation dates.',
147:'One Bonneterre watercolor/ink guard drawing26.8 by18.5cm, explicitly March1959. The circa1900 uniforms in the title are represented history, not creation.',
148:'One Bouilliere circa1935 Marseille charcoal/watercolor37.5 by48cm drawing. Exact-title Vernet/Korovin/Kokoschka works have other makers; existing Bouilliere paintings depict Arles or Toulouse sites.',
149:'One nineteenth-century Belli oil portrait painted on palette-shaped wood31 by21cm. Preserve literal Belli label; existing Giovanni/Giuseppe Belli music-portrait leads have different named sitter/creator labels.',
150:'One Paul Bernadot1911 pencil self-portrait44 by30.5cm. Existing Bernadot family canvas is65 by81cm; generic exact-title leads are other named creators, none unlabelled/anonymous in this scope.',
151:'One M. Bertoin1947 rue Alsace-Lorraine oil painting60.6 by50cm plywood, signed/dated. No creator/title/native counterpart; incomplete creator lifespan preserved.',
152:'One Achille Blairsy nineteenth-century canal ink/watercolor14.7 by19cm drawing. Source1814 is memorial subject and1956 is gift; neither replaces nineteenth-century object dating.',
153:'One attributed Marius Cazeneuve1886 property-view watercolor20 by25.5cm on original layered mount. One drawing, not separate records for mount/underlay; existing Cazeneuve desert/crocodile/portrait paintings differ.',
155:'One tentatively attributed Costa early-twentieth-century Dalbade/Carmes watercolor55 by35cm. Preserve uncertain signature and creator; broad Costa leads are other family artists/subjects.',
156:'One Gabriel Cyrille1920 Dalbade pencil/watercolor61 by47.5cm, signed10June1920. Broad Cyrille results are Besset/Durand, other creators and subjects.',
157:'One Descazaux nineteenth-century copy of a fragment after Chalette,40.4 by32.3cm canvas.1633 belongs to represented capitoul and original, not copy date. Title identifies Vidal while old label says Supplicy1696; preserve both statements and literal frame-size inconsistency without identifying a new sitter authority.',
158:'One Gabriel Durand1880 Marie Barbaroux pastel105 by80cm on card. Retain former title Retour de messe and salon label; broad Durand/Carolus-Duran portraits are different makers/sitters.',
160:'One Foache/Cassan numbered artist-proof lithograph of regional costumes32.2 by64.9cm, second-half nineteenth century. Count sheet once, not figures represented; preserve edition number9 and maker/printer roles.',
161:'One Philippe Hardy fireworks-design drawing50.8 by37.8cm before1762, depicting one of four facades. Count this drawing only. Preserve unknown lower bound and literal source before-date despite1762 event inscription.',
163:'One Micheline Larrue early-twentieth-century Saint-Etienne watercolor55.5 by33.5cm. Existing Beaumont same-title work is37.7 by45.7cm oil canvas; Guillaume Larrue is another creator.',
164:'One Joseph Latour July1842 Barbazan pencil sheet44 by55cm. Other Latour scope leads concern Fantin-Latour lithographs; distinct signed maker/site/date.',
165:'One Malbos/Constantin/Avanzo1845 Redoutes lithograph30.7 by50.6cm image44.8 by58.4cm sheet,81.894. Source explicitly references a similar other impression81.899; only this inventoried measured sheet selected.',
166:'One Alexandre Moulis1952 charcoal figure-study sheet25 by16.5cm. Several represented figures remain one physical sheet; no maker/title/native counterpart.',
167:'One Pierre Medard1912 Hotel Dumay pencil/watercolor34 by25cm drawing,21June1912 inscription. Broad Medard leads concern Eugene/Klein, other creators; shared generic inventory tokens are unrelated museum objects.',
169:'One Raymond Pujol1883 Carmes pencil/watercolor26 by36cm on old mount, signed/dated. Broad Abel de Pujol leads are another creator; no exact/native counterpart.',
170:'One Louis de Planet circa1842 Scio oil copy100 by81cm after Delacroix. Different copyist, size, date and accession from Andrieu40.7 by32.2cm version; retain copy role rather than assigning original authorship.',
171:'One Jean Reme1932 Hers bathing pencil/color-pencil36.8 by50.5cm sheet. Broad Reme alias results are Dughet landscapes, different creator/material/site.',
172:'One Antoine Rivalz circa1726 sanguine/white-chalk academy sheet54.8 by35cm. Same-title Chifflart, Bodinier, Greuze, Fabre and Axilette works have different creators/physical descriptions; full Rivalz pool has no academy/nude counterpart.',
173:'One Maria Verdun1850 panoramic Tounis pencil/white-gouache36.5 by71cm drawing. Nicholas of Verdun shrine results are another maker and object type.',
175:'One anonymous nineteenth-century Pont de Tounis washerwomen oil canvas32.5 by40.5cm. No exact-title/native counterpart; preserve anonymous creator and historical collection labels.',
176:'One Andrieu-Geze1935–36 brown-wash market sheet24 by19.8cm,88.1.2, seated female seller. Different medium, title/inscription and accession from black/gray-wash88.1.1; count two separately catalogued sheets, not a doubled record.'
}
HOLDS={
2:'Existing after-Carracci same-title canvas75 by45.5cm may be another version or alternative measurements; resolve against89 by52cm candidate before adding.',
3:'Giordano workshop attribution with first-half seventeenth-century period requires chronology/qualification review; no silent date replacement.',
4:'Workshop Veronese Emmaus with several museum prototypes requires fuller translated-title/version comparison.',
6:'Existing anonymous Communion of Virgin142 by108cm may be another version or framed dimensions of129.5 by88cm candidate; resolve composition.',
8:'Generic Oliviers subject has22 exact-title leads including incomplete physical metadata; retain version review and historical missing-work distinctions.',
9:'Historical catalogue refers to an ancient copy30bis; resolve copy and current inventory relationship.',
13:'Small Oliviers panel and prototype references require comparison against incompletely described same-title versions.',
14:'Generic Crucifixion title has20 same-title leads, several without physical details; retain composition review.',
15:'Small Oliviers copper and related lost-work references require fuller same-subject version review.',
18:'Existing46.5 by37cm copper Baylon could be framed dimensions of39.5 by31.2cm candidate; resolve composition/measurement convention.',
21:'Same-title Cattaneo canvas shares height77.5cm with narrower width44.5cm; investigate attribution and measurement history before adding anonymous77.5 by63.1cm canvas.',
22:'Generic Crucifixion with incomplete same-title database versions requires further physical identity review.',
23:'Generic Oliviers subject with incomplete same-title versions requires fuller composition and provenance comparison.',
27:'Anonymous Last Supper has multiple incomplete same-title/prototype versions; preserve composition and copy uncertainty.',
28:'Paired copper Ecce Homo has91 title leads, including near-format works; resolve physical version and pair identity before selection.',
30:'Large anonymous Ecce Homo has91 title leads, many incomplete; retain physical/version review.',
32:'Existing Rosa Bonheur Pattes de felin charcoal63.5 by48.2cm is near-format of anonymous62.8 by49cm source; reconcile maker and measurements.',
38:'Existing Bastien-Lepage same-title etching lacks measurements; resolve impression before adding.',
49:'John Lewis Brown reconnaissance/Cossack subjects need full composition and impression comparison beyond different sheet dimensions.',
50:'Two existing Gaston Bussiere Jeanne records have incomplete physical metadata; resolve1908 model versus1911 impression.',
51:'Plaster cast before1870 related to1877 marble needs model/cast chronology review.',
54:'CHRISTOPHE creator identity for1889 Fontainebleau print remains unresolved; do not assume a namesake artist.',
57:'Ariane plaster cast has multiple documented versions and tentative exhibition history; resolve actual cast identity/date.',
58:'Generic Desvergnes female bas-relief has close-format existing Lily Trutzschler portrait; compare sitter/composition.',
61:'Donzel Auvers landscape has an incomplete same-maker river-landscape lead; compare composition before selecting.',
62:'Attributed Dughet Italian landscape overlaps incomplete same-maker generic landscape records; retain qualification and version review.',
63:'Duvivier/Millet Veillee impression and existing Millet evening etching require copy/edition comparison.',
64:'One service includes a dish and nine plates under grouped inventory. Resolve assembly/component identity; do not count ten artworks or infer a single vessel.',
65:'Ondine bronze version requires casting-date and edition review, independently of nineteenth-century model label.',
104:'Source alternates Cochin le Jeune and Cochin Pere on1760 La Tour portrait; preserve creator-role discrepancy pending research.',
111:'Existing same-maker Pompadour pastel32 by24cm is close to33 by25cm candidate; resolve study/version before adding.',
112:'Existing Devambez Poilu/Lettre has incomplete physical data; resolve preparatory soldier study versus finished work.',
117:'Domaine dessin conflicts with explicit roulette print and second-letter state. Resolve type and impression identity; do not import as a drawing.',
127:'Josephine portrait model and explicit first-half eighteenth-century dating conflict; preserve source and hold, no invented correction.',
128:'Existing Rossi old-man portrait lacks physical detail and may duplicate one of the paired46 by38cm canvases; resolve LT119/LT120. Shared92 is from different dated catalogues, not automatically an object match.',
129:'Schmidt plate1742 and Bihn later merchant/impression role need actual impression-date/state review; other LT134 impression known.',
134:'Anonymous/Ducreux tentative attribution and1750 versus related Salon1765 narrative need creator/date review.',
138:'Second Rossi old-man canvasLT120 overlaps incomplete existing same-maker portrait; reconcile both paired physical objects first.',
145:'1791 appears in collector wording describing cathedral state; distinguish depicted date from drawing creation and related1828 Boilly version.',
154:'1853 Clausade portrait inscription and later sculptor biography require maker chronology review; retain literal source without assumed authority.',
159:'Paired porcelain vases under86.21.34 1-2 require assembly/component review; do not add two objects from one grouped record.',
162:'Two differently engraved costume states mounted together, with disputed Pomone/Flore subject. Preserve compound unit and title uncertainty.',
168:'One reference includes measurements of three Saint Vincent impressions81.383 1/2/3. Resolve unit and exact impression before adding.',
174:'Existing Wallaert Pont Neuf Toulouse record lacks physical metadata and likely overlaps candidate; reconcile before adding attributed version.'
}
