"""Record verified WarMuseum delivery and retain the gap to200 and research holds."""
import csv,importlib.util,json
from pathlib import Path
spec=importlib.util.spec_from_file_location('d',Path(__file__).with_name('museum-expansion-war-delivery-20261010.py'))
d=importlib.util.module_from_spec(spec);spec.loader.exec_module(d)
a,c,m,RUN=d.a,d.c,d.m,d.RUN
NEXT='ecc56326-95ff-5063-9e7c-defe30001f0f'

def table(name,rows):
    with (RUN/name).open('x',encoding='utf-8-sig',newline='') as h:
        w=csv.DictWriter(h,fieldnames=list(rows[0]));w.writeheader();w.writerows(rows)

def main():
    assert not(RUN/'delivery-001.json').exists();checks=m.load(RUN/'checks-001.json');read=m.load(RUN/'readback-001.json');public=m.load(RUN/'public-delivery-001.json');assert checks['readback_passed'] and checks['replay_zero_writes'] and checks['local_unchanged'] and public['public_artwork_samples']==6
    p,digest=a.validate_plan();assert digest==d.EXPECTED;prior=m.load(c.CP);at=m.now();assert read['verification']['current_counts']=={c.IID:dict(linked=180,eligible=103)}
    rr=prior['production_institution_register_reference'];register=m.load(c.checked(rr))['rows'];target=next(x for x in register if x['id']==c.IID);assert target['verified_production_works']==12
    target.update(production_catalogue_count_to_200=180,production_date_eligible_count_to_200=103,production_catalogue_count_state='exact',production_date_eligible_count_state='exact',verified_production_works=180,verified_production_eligible_works=103,production_catalogue_count_at=read['at'],production_date_eligible_count_at=read['at'])
    m.save(RUN/'production-institution-register-001.json.gz',dict(at=at,rows=register,previous_register_reference=rr,read_only=True,updated_institutions=[c.IID],global_exact_counts_refreshed=False,global_thresholds_refreshed=False,policy='OnlyWarMuseumrefreshed:180catalogue,103numericeligible,9unknownand68crosscutoffranges. Other observations keep their own timestamps.'));table('production-institution-register-001.csv',register)
    qr=prior['priority_museum_queue_reference'];queue=m.load(c.checked(qr));assert len(queue['rows'])==225 and any(x['id']==c.IID for x in queue['rows']);queue['rows']=[x for x in queue['rows'] if x['id']!=c.IID]
    reached=dict(id=c.IID,at=read['at'],catalogue=180,date_eligible=103,basis='168newreviewworks;91numericeligible,9unknownand68crosscutoffranges. Minimum100catalogue threshold reached;20additionalcatalogueworks needed forpreferred200.')
    queue.setdefault('removed_threshold_reached',[]).append(reached);queue['latest_removed_threshold_reached']=reached;queue['latest_preferred_target_remaining']=dict(institution_id=c.IID,catalogue=180,gap_to100=0,gap_to200=20,target_reached=False,numeric_eligible=103)
    queue.setdefault('date_research_remaining',[]).append(dict(id=c.IID,catalogue=180,date_eligible=103,unknown_dates=9,crossing_cutoff=68,reason='Sourcecenturiescross1970;4mapversiondateconflicts,1officeyearand4medalmanufacturedatesunresolved. Oldmedaldateclaims preserved, notrevalidated as manufacturing dates.'))
    queue.update(at=at,previous_queue_reference=qr,policy='WarMuseum reached180catalogueworks and leaves inheritedunder100subset.224rowsremain,64Greek; notrefreshedglobalcensus. Warstill20shortofpreferred200.');m.save(RUN/'priority-museum-queue-001.json',queue)
    table('delivered-production-artworks-001.csv',[dict(artwork_id=v['artwork_id'],institution_id=c.IID,action='new_record',source_id=v['facts']['source_id'],title=v['facts']['title'],date_display=v['facts']['date_display'],creation_year_start=v['facts']['first'],creation_year_end=v['facts']['last'],source_url=v['facts']['source_url'],status='review') for v in p['records']])
    table('delivered-production-images-001.csv',[dict(artwork_id=x['artwork_id'],source_id=x['source_id'],number=x['number'],primary=x['set_primary'],storage_path=x['storage_path'],sha256=x['sha256'],bytes=x['bytes'],width=x['width'],height=x['height'],rights_status=x['rights_status'],rights_label=x['rights_label'],source_url=x['source_url']) for x in p['images']])
    protected=sorted(set(p['prior_ids'])|{x['artwork_id'] for x in p['records']});assert len(protected)==2683
    m.save(RUN/'protected-production-ids-001.json',dict(at=at,ids=protected,previous_protected_records=2515,new_records=168,new_existing_links=0,composition=dict(campaign_new_artworks=2659,campaign_existing_links=7,additional_existing_image_only_records=17),plan_reference=c.ref(a.PLAN)))
    remaining=dict(at=at,institution_id=c.IID,catalogue=180,preferred200_reached=False,catalogue_gap_to200=20,numeric_date_eligible=103,unknown_numeric_dates=9,crossing_cutoff=68,new_unknown_numbers=[v['facts']['number'] for v in p['records'] if v['facts']['first'] is None],source_total=1888,type_selected_distinct_index=233,individual_objects_reviewed=195,scope_holds=[10,11,44,53],identity_holds=[31,65,71,81,103,104,105,123,132,135,169],failed_metadata_numbers=[196,197,198,199,200],subsequent_unattempted_numbers=list(range(201,234)),unavailable_image_numbers=[103,104,105,138,149,170],unillustrated_added_numbers=[138,149,170],ready_candidates=0,resolution_gap='90delivered source-linked JPEGs are byte-identical to thumbnails, at most380pxwide or550pxhigh. Wrapper descriptive sizes may differ from actual decodedpixels. Higherresolution source originals remain unavailable in the reviewed filelinks; source pixelquantization and frames preserved.',next_priority='Spathario Shadow Theatre Museum, IID '+NEXT+'; last16catalogueworks. Freshlocal/productionbaseline and selectedpre1971shadowpuppet/artwork review needed. Discovery450searchableresults versus description453artifacts, dates1929–2019; source total is not eligibleobjectcount.',next_source_reference=c.ref(c.DISCOVERY))
    m.save(RUN/'remaining-research-001.json',remaining)
    backup=m.load(RUN/'cloud-backup-001.json');report=dict(at=at,goal_complete=False,production_only=True,local_unchanged=True,plan_sha256=digest,added=168,existing_links=0,date_eligible_new=91,new_unknown_numeric_dates=9,new_crossing_cutoff_dates=68,verification=read['verification'],museum_before=dict(works=12,eligible_works=12,primary_images=12),museum_after=dict(works=180,eligible_works=103,primary_images=102),minimum100_catalogue_reached=True,preferred200_catalogue_reached=False,catalogue_gap_to100=0,catalogue_gap_to200=20,production_campaign_totals=dict(new_artworks=2659,existing_links=7,museums=16),historical_local_totals_unchanged=prior['historical_local_campaign_totals'],cross_database_totals_combined=False,new_images=90,new_primary_images=90,new_alternate_images=0,new_artist_links=65,remaining_pending_candidates={},remaining_pending_total=0,global_production_counts_refreshed=False,global_production_thresholds_refreshed=False,backup_id=backup['id'],source_access='195objectpages,189thumbnails,90sourcefilewrappersand90JPEGs reviewed; officialAthensmuseum and2creatorauthoritypagescaptured. NativeexhibitionhostTLSmismatch remainsheld;5objectpagesHTTP500 stoppedmetadata stream and33subsequent pagesunattempted.6thumbnailresponsesHTTP200with0bytes. No failedroute retried or alternate bypass.',next_work=remaining['next_priority']);m.save(RUN/'delivery-001.json',report)
    text=f'''# Athens War Museum — 10 October 2026

Added **168 review artworks**, **90 authentic images** and **65 links to existing artist records** in production. The museum increased from **12 to 180 catalogue works**, passing the minimum 100 target and leaving **20 to reach 200**. The real local database is unchanged.

The catalogue has **103 numerically date-eligible works**, **9 unresolved creation dates**, **68 ranges crossing 1970**, and **102 illustrated works**. The 103 count includes the 12 unchanged existing records; older medal date claims were preserved and have not been newly validated as manufacturing dates. All additions remain in review.

- [Delivered artworks](delivered-production-artworks-001.csv)
- [Delivered images](delivered-production-images-001.csv)
- [Reviewed selection](reviewed-selection-001.csv)
- [Verification](checks-001.json)
- [Remaining research](remaining-research-001.json)

The [museum-supplied SearchCulture collection](https://www.searchculture.gr/aggregator/portal/collections/DigWAR?language=en) has 1,888 mixed records. Six selected visual and decorative art facets yielded 233 distinct leads. We read 195 individual bilingual object records, including all 12 old catalogue entries, before five object pages returned HTTP 500. The stream stopped; 33 further selected pages remain unattempted. Index totals do not establish eligible artwork counts. The separate native exhibition host failed TLS hostname verification and was not bypassed.

We reviewed 189 thumbnail frames, eight source contact sheets, seven focused source frames, six existing artwork images and their comparison sheet, plus all 90 source digital files on four further sheets. The 90 source-linked JPEGs are byte-identical to their reviewed thumbnails. They are preserved unchanged, with complete supplied frames and margins, at most 35,321 bytes each. Their actual resolution is at most 380 pixels wide or 550 pixels high. Descriptive pixel dimensions on file wrappers can differ from decoded pixels; actual file dimensions are recorded. Higher-resolution reproductions remain an improvement gap.

Item-level and digital-file licence panels both state **CC BY-SA 4.0**. This is object-specific evidence, separate from the website footer. The licence URL, museum credit, creator label, source pages, actual file URL and unchanged-file notice are retained. User approval for the Greek museum workflow is recorded separately. No new copyright-holder permission is claimed.

Four utility objects or tactical diagrams were excluded from this selection. Eleven entries remain held for object identity or physical-unit review: conflicting artillery/title images, the Otto record illustrated by a female portrait, a Lord Byron portrait requiring sitter corroboration, a Constantine sculpture unexpectedly attributed to Flora-Karavia, a grouped photograph record and three unillustrated Gerontas studies. No entries were invented to reach a numerical target. The Thessaloniki airport entry was resolved as an artwork drawing of an aircraft, rather than a technical plan.

The broad source centuries remain broad. Four historical maps have unresolved impression or reproduction dates; one portrait's 1919 date describes the sitter's office, and four medal dates may describe campaigns or designs rather than manufacture. These nine dates remain unknown. The Prokopiou soldier painting explicitly gives 1928 in its title and description. Approximate dates retain their qualifiers. Copies retain copyist labels and are not linked to prototype artists. English translation errors—including crayon terminology, artist names and a medal's “with/without swords”—remain documented against the Greek originals.

Bounded reconciliation checked 484 existing artworks and 1,032 citations. Exact source, informative title and image matches identified only the 12 old War Museum records. Related Flora-Karavia and Roilos works were compared by composition, subject, medium and version. Similar Constantine portraits, nurse studies and Bursa and Mudanya drawings were retained as separate compositions. Six illustrated existing Flora-Karavia comparators differ from the selected works. This is not an exhaustive global duplicate guarantee or a ten-million-row load test.

The [Flora-Karavia authority](https://www.searchculture.gr/aggregator/persons/-1091820013) and [Roilos authority](https://www.searchculture.gr/aggregator/persons/1652662752), linked from the museum object records, corroborate 61 and four new maker links respectively. Existing artist records and all 484 comparator records remain unchanged. Other unresolved names remain object labels; no artist, alias or biography was invented. Three added works remain unillustrated because their thumbnail responses were empty; all unknown or crossing-cutoff dates also have no new images.

Backup **{backup['id']}** succeeded before application. Sixteen offline checks, live preflight, atomic verification, independent readback and zero-write replay passed. All 90 public image checksums and six public artwork samples were verified. All 2,515 earlier protected campaign records remain unchanged. No publication or current-display claims were added. Plan SHA-256: `{digest}`.

The selected production campaign now totals **2,659 new artworks and seven existing-work links across 16 museums**. The extended protected set contains 2,683 records, including 17 prior image-only enrichments. Only this museum's count was refreshed. The inherited under-100 subset has 224 rows, including 64 Greek institutions; this is not a new global census. The every-museum goal remains active.

Next: a fresh baseline and selected source-backed artwork review for Spathario Shadow Theatre Museum. Its prior discovery records 450 searchable entries, while the description says 453 artifacts; creation dates span 1929–2019. Neither total guarantees 100 eligible artworks. The War Museum's remaining 20-work gap, date research, image-resolution gaps and held identities remain tracked.
'''
    (RUN/'README.md').open('x',encoding='utf-8').write(text)
    print(json.dumps(dict(added=168,images=90,catalogue=180,numeric_eligible=103,protected_ids=2683,priority_rows=len(queue['rows']),greek_rows=sum(x['country_code']=='GR' for x in queue['rows']))),flush=True)

if __name__=='__main__':main()
