"""Editorial notes for the selected Williamson and Perth objects."""
HOLDS={
12:'The exact Perth inventory 8/204 names Lord Provost Charles Scott in museum-supplied metadata, conflicting with the existing Archibald Ure Wotherspoon sitter. Preserve both identities pending reconciliation.',
23:'The museum explicitly qualifies Thomas Duncan as attributed; the source filename does likewise. Do not strengthen the unqualified current creator association.',
68:'Native title and place label say Portsea Bay,while the existing object title says Portree Bay. The exact inventory and maker match,but these are different places; preserve this geography/title conflict pending reconciliation.',
69:'Native Cemaes Farmstead framed dimensions61x71cm conflict with the saved source support55.8x76.2cm. A same-maker Cemaes Bridge comparison51x61.3cm also needs version review. Do not resolve the physical object from modest or inconsistent measurements alone.',
83:'The same accession 1999.39 occurs on a portrait and a silver jug. The portrait record itself contains jug object-type and Social History department fields. This is an unresolved source conflation, not a clean object-level branch basis.',
84:'Gear Composition 1949 has a same-maker Composition Blue Centre 1949 comparison at Towner,50x65cm versus51x62.5cm. The modest size difference does not independently resolve physical identity; retain the accepted network holding. Tate Composition116x89cm is a distinct format but does not resolve the Towner comparison.',
86:'Museum metadata explicitly describes Children Playing recto and The Fireplace verso as one double-sided canvas under2010.208. Preserve both current entries without accepting two separately counted museum objects; reconcile representation and version identity first.',
88:'Native Old Houses reports a horizontal75x93cm frame and a Penlee House label,while the saved source gives a vertical76.2x60.9cm support. Same-maker Old Harbour at Penlee71x92cm and Brighton Farm Scene56x76cm require physical-version reconciliation; the conflicting orientation invalidates a simple dimensions-based distinction.',
107:'The Fireplace verso is the reverse of selected Children Playing recto2010.208 in the museum record. The suffixed secondary inventory2010.208.b does not establish a second physical object. Preserve current entries pending component reconciliation.',
134:'The source filename qualifies Charles Eyes attribution. Preserve the unqualified existing creator link and defer its reconciliation.',
141:'Mirror Diptych II is an undated component/version lead. A title alone does not establish whether it is a complete two-panel work or one part,or whether creation is within1970. Preserve pending association until native object and scope identity are resolved.',
160:'Native maker is Alfred de Breanski1852-1928,while the existing creator is Alfred Fontville de Breanski,the son. Preserve the father/son authority conflict rather than assigning a holding through an unreconciled creator.',
171:'The exact native Metamorphosis Birds record dates creation1980. Preserve the existing unknown date and pending association; it is outside the selected pre1971 expansion.',
181:'Native Paice Mersey from Rock Ferry50.5x60.5cm is nearly identical in dimensions to the same-maker Rock Ferry,Cheshire1937 comparison51x60.8cm. Related title and format leave physical-version or transfer identity unresolved.',
216:'Native BIKGM.8495 is Mathew Snowden Plein air,Hilbre Island2007,not the imported Geoff Yeomans Woodside Station1954. Preserve this exact-inventory collision and conflicting creator,title,date and dimensions for reconciliation; no quota-based acceptance.',
198:'Perth primary metadata identifies an unknown Scottish-school maker after Alexander Robertson. Existing Alexander Duff Robertson is unqualified. Retain the conflicting attribution and unknown date for reconciliation.'}
for number in [25,39,47,231]:HOLDS[number]='The museum-supplied maker is James Sydney Steel (1863-1932),while the existing authority is John Sydney Steel with those life dates. Exact inventory and subject match,but the different first name remains an unresolved source-label conflict; preserve all fields and defer creator reconciliation.'
NOTES={
1:'Stirling Malloch differs from Ramsay Richard Reinagle; short accession2/145 is museum-scoped and does not identify Reinagle Man with Dog.',
6:'Monro tea tray2/154A and flowers/wine glasses1/154A have distinct subjects,inventories and formats36.2x41.2 versus43.2x52.7cm. Keep both unknown creation dates; conflicting museum artist life dates are not artwork dates.',
9:'Museum creation note1897(?) is uncertain; retain that qualification as evidence and the existing1897 unchanged in this holding-only update.',
10:'Noble An East Lothian River122.5x218.5cm differs from River Tyne34x26cm and Dirleton Church30.5x60.8cm in physical format. Museum1910(circa) retained separately from existing1910. Framed museum measurements are not substituted for support dimensions.',
13:'Richard Young differs from David Young Cameron; Large Interior is not Dutch Interior or St Mark.',
18:'Yeomans numbered Woodside Study I22x12.4cm,Study II49.3x40.1cm and Woodside Station90x69.7cm have distinct source inventories and formats. Do not merge these separately identified studies and painting.',
21:'Existing title explicitly preserves copy after George Reid. Museum maker Hugh Munro after Reid is retained separately from existing Hugh Monro; source life dates match and the exact1923 inventory and sitter identify the copy. Do not attribute it as a Reid original.',
27:'Walker Quarrymill Burn1/223A38.1x47cm and Scone Burn2/223A40.6x33.6cm have separate inventories and opposite landscape/portrait formats. Retain both unknown dates and native title variants.',
28:'Museum describes this44.3x69cm1874 sketch separately from the related1863 Dundee Lochaber No More painting124.5x191.1cm and another Crathes version. Preserve the specific sketch identity.',
30:'Native inscription Jameson48 is retained as evidence beside existing circa1950; no creation date is silently replaced.',
33:'Copeman John Finnie1907 is29.5x39.5cm (native framed37x47cm),distinct from the1903 Walker portrait92x102.2cm. Separate source inventories and physical scale establish different versions.',
35:'Woodside Study II has a distinct inventory and49.3x40.1cm format from Study I22x12.4 and Woodside Station90x69.7cm.',
43:'Albert Gordon Thomas differs from Thomas Rowlandson; the shared short numeric inventory is scoped to a different collection.',
44:'Norman Prescott Davies differs from Arthur B.Davies; the selected Irises painting is not the latter artist print.',
49:'Native Thomas Brassey by H.Carter is dated1878,while the exact source object and current catalogue say1874 and Hugh Carter. Preserve the abbreviated maker and conflicting creation years separately; exact inventory,title and large portrait format establish the same holding without rewriting metadata.',
50:'The flowers and wine glasses still life1/154A differs from Monro tea tray2/154A by explicit subject,inventory and format. Neither unknown artwork date is inferred from artist life dates.',
52:'George Hannah differs from Hannah Emma Palmer; these bridges are not the same maker or object.',
55:'The current catalogue lacks an accession and dates circa1874-1875,while the same exact Wikidata object gives BIKGM:212P and a decade-precision1874 statement. Title,Samuel Walters authority and museum-qualified source inventory agree; preserve both date representations and the null catalogue inventory. No native exact result is claimed.',
57:'Native inscription transcription says Carlton G.Smith while its maker field gives Carlton Alfred Smith. Retain both source strings and the exact1882 title/inventory; do not rewrite the existing creator authority from an initial transcription.',
58:'The native title calls Winifred a study; retain this additional specificity with the same exact inventory and creator,without changing catalogue text.',
63:'Select the exact Hargitt painting object e87d3967-3b84-3451-97a4-5ade3331525c. A University of Glasgow ticket has the same network inventory2002.11 but different maker and object type; it is explicitly excluded. The unrelated Francken accession collision also belongs to another institution.',
65:'Native calls the exact Talbot Kelly inventory The Outpost; the imported North African Scene is a broader subject label. Preserve both labels and the same small support format.',
66:'Native medium field says canvas and technique says panel. Retain this internal support discrepancy as evidence without changing current metadata; exact inventory,title,maker and1929 inscription identify the holding.',
70:'The exact museum record distinguishes Robertson,C.and Co.as canvas maker from Hugh Adam Crawford as artist. Preserve the two source roles; the supplier is not a second painter.',
71:'Robert Gibb View of Perth1/71 is the finished72.4x129.5cm work; native record4/132 explicitly identifies the separate33x101.6cm preparatory study. Hendrick van Steenwijck accession collision is another museum and maker.',
72:'Native1862 falls inside the existing1861-1864 range. Keep the explicit native year as evidence without narrowing the catalogue date.',
73:'Native maker label Charles Pettitt,Jnr is retained beside the existing Charles Pettitt1831-1885 authority. No senior designation is present in the current identity,and the exact source inventory,title and maker name match; no creator or biographical field is rewritten.',
75:'John Sanderson-Wells differs from James Wells Champney; the hunt meeting and letter subject are separate objects.',
87:'Museum creation1899-1900(circa) retains uncertainty beside the existing range; no date rewrite.',
88:'Maidment Old Houses76.2x60.9cm vertical format differs from Old Harbour71x92cm and Brighton Farm Scene56x76cm horizontal formats. Preserve distinct source inventories and building/farm subjects.',
93:'Museum calls2/223A Scone Burn. Its40.6x33.6cm portrait format differs from selected Quarrymill Burn1/223A38.1x47cm landscape format; retain both exact inventories and title variants.',
99:'After Dunkirk belongs to the historical subject,not a copy attribution. The short inventory3/9 in unrelated Charles Philips/Thomas Couture records is not global identity.',
102:'Native Breton? qualification identifies uncertainty in the depicted women,not an artist attribution. Retain the question mark as evidence without expanding the catalogue claim.',
100:'Duncan Cameron differs from David Young Cameron. The unrelated John Gardiner Crawford accession2/29 is scoped to another museum. Preserve verified unlinked Duncan Cameron label.',
103:'Thomas Duncan differs from the anonymous Netherlandish and Henry Sandham records with similar short numeric inventories.',
105:'Native description spells the steamer Emile Delmas while its title/current title use Delmar. Preserve both spellings and the1928 event date as subject history; no artwork creation year is inferred.',
106:'Stirling Malloch differs from Charles Hodge Mackie; short accession3/145 is collection-scoped.',
110:'Berrie portraits of John Farley,C.Heweston Nelson and E.G.Parkinson have distinct named sitters and exact inventories; mayoral titles do not merge their object identities.',
111:'George Hannah Self Portrait is distinct from the Proudfoot,Spence Smith and Kennaway self portraits. Museum places this exact object in the JD Fergusson Collection; the official2023 gallery transition explicitly includes that collection. No current display is inferred.',
114:'Museum mentions a separately inventoried explanatory key1991.123; this exact1991.122 painting is not that key or an aggregate record.',
116:'The museum explicitly describes the1900 Sellar replica after the Barclay portrait destroyed in1895. Existing title already preserves copy after Barclay. Retain the copied-work identity and historical location text without treating it as fresh display.',
120:'Tom Robertson differs from Alexander Duff Robertson and the unknown maker after Robertson in held198; these labels are not interchangeable.',
124:'William Alison Martin differs from Kenneth Martin,John Martin,Martin Friedman,Martin Schongauer,Agnes Martin and Henri Jean Guillaume Martin.',
125:'Adam Highland Bull120x75cm vertical format differs from Highland Cattle65.8x106.7cm horizontal format and has a separate inventory and1880 versus1878 source date.',
126:'Cecile Walton differs from Edward Landon; shared numeric inventory1993.249 is institution-scoped.',
130:'James Hall Cranstoun differs from David Graham; PCF42 does not join separate museum authorities.',
131:'Museum title Birkhill is a shorter description of the exact Geddes family-on-lawn inventory. Preserve native circa1867-1869 and the imported range separately.',
133:'Phillips Woman Holding a Corn Bushel and Woman Holding a Shrimping Net share dimensions but depict explicitly different held objects and have distinct W135/W136 inventories. Preserve these separate works without collapsing the pair.',
142:'Charles William Oliver differs from Peter Oliver and Oliver Tarbell Eddy; the art student is not their portrait work.',
143:'Robert Henderson Blyth differs from Eleanor Winslow Baker; inventory1/9 is not globally unique. War Baby1918 is a subject title,while creation1945 remains unchanged.',
144:'Keith New differs from Bannister and Maurer; generic landscape words do not establish same creator or object.',
147:'John Guthrie Spence Smith differs from Gordon A.Smith. The red-tile cottages are not Structure with Red Sun.',
150:'Berrie C.Heweston Nelson is a different named sitter and exact inventory from John Farley and E.G.Parkinson.',
156:'Thomas Callender Campbell Mackie differs from Hokusai; inventory1985.327 is collection-scoped. Unknown artwork date remains unknown.',
159:'Phillips shrimping-net figureW136 differs in explicit subject and inventory from corn-bushel figureW135 despite equal support dimensions.',
162:'The museum cross-reference1993.407 points to an inscription/story,not a replacement identity for the exact Sun on a House inventory1/185. Keep source context and1937.',
172:'Dougald Walker differs from Robert Walker Macbeth; harvest scenes by these makers are distinct.',
173:'Colvin Smith differs from Fragonard; inventory2011.91 is institution-scoped.',
174:'Paice Birkenhead Priory and Mersey from Rock Ferry depict different named sites and carry distinct inventories. The latter comparison with another Rock Ferry work is reviewed separately.',
175:'Native title A bridge across a river is less specific than the imported Old Shoreham Toll Bridge. Exact Paice inventory and support dimensions identify the work; retain the different levels of location specificity without rewriting.',
177:'Native inscription includes February1840. Retain this creation evidence and the existing unknown date unchanged; holding reconciliation does not silently enrich chronology.',
180:'Museum maker lifespan b.1914,d.1912 is internally inconsistent; retain it verbatim in evidence without importing it. Exact Louise Annand,inventory and1943 Sleep identify the painting; no biography or date change.',
183:'Native notes another canvas behind this painting depicting a white house. The selected record is the named Fishermen canvas only; no additional artwork or duplicate count is created for the undescribed backing canvas.',
186:'Philip Steer (artist) differs from Philip Wilson Steer. The selected portrait depicts the former artist father Philip Steer1779-1860; those sitter dates are not creation dates.',
189:'Archibald Russell Watson Allan differs from Macartney Saunders and Panini; inventory1/3 is museum-scoped.',
195:'Native Arlecchino is oil and monotype on paper in the JD Fergusson Collection. Preserve the explicit mixed technique and source collection alongside existing painting type; no format or artist rewrite.',
197:'Tonge Landscape21x28cm1849 differs in format from Landscape with a Distant Town25.7x56.2cm and Sefton52.6x115.8cm,both1848. Preserve distinct inventories and dates.',
199:'Native1993.21 describes one board with an interior figure on the front and a house on the reverse. The current record represents the recto; no other representation of this inventory or matching same-maker House exists in the scoped identity pool. Link this single existing record only and preserve the native reverse description. Girodet inventory collision is another collection and maker.',
201:'Thomas Bromley Blacklock differs from John Haynes Williams; inventory2/8 is institution-scoped.',
207:'Berrie E.G.Parkinson differs from the named Nelson and Farley sitters,with a separate exact inventory.',
215:'Museum dates the Duchess portrait approximately around the1938/9 election; preserve this uncertainty and existing circa1938. Manzana Pissarro inventory2011.81 is a different collection.',
214:'Native1889 is retained as explicit creation evidence; the existing unknown date remains unknown in this holding-only update. Conflicting secondary subject keyword Peel Castle is retained without rewriting the Ravenscar title.',
216:'Yeomans Woodside Station90x69.7cm is distinct from numbered Woodside studies22x12.4 and49.3x40.1cm and has its own8495 inventory.',
220:'William Bromley differs from Valentine Walter Bromley; the bird-nesting and resting-girl works are not merged.',
223:'Museum retains Replica inscriptions on the reverse of exact1909 Kennaway portrait. No competing same-maker/sitter object was found in the scoped identity review. Preserve the native replica designation as evidence; no original-only claim is made.',
224:'Museum explicitly identifies4/132 as the preparatory study for1/71 View of Perth;33x101.6cm and72.4x129.5cm are separate formats. Historical purchase as Horatio McCulloch is superseded by its documented Gibb identification and retained as history.',
225:'Proudfoot Self Portrait1935 is not the Hannah,Spence Smith or Kennaway self portrait; creators and inventories differ.',
226:'Spence Smith self portrait12/210 has no other same-maker representation of this inventory or verso in the scoped identity pool. Other generic Smith self portraits belong to Grace Cossington,Thomas,Garden Grant,Frank Jameson,John Raphael,Albert Alexander,Arthur Hall,Moishe and Matthew Smith. Preserve the selected recto label and do not invent a reverse record.',
229:'Kennaway1902 self portraitFA26/78 is separate from museum cross-referenced1923 self portrait2002.281 and the other makers self portraits. Exact inventory and date retained.',
236:'Ewan Geddes differs from Govert Flinck; accession1998.426 is collection-scoped. Native circa1890-1900 stays evidence and the catalogue unknown date remains unknown.',
239:'Lindsay Grandison MacArthur differs from Edward John Poynter;2011.98 is scoped to its collection.',
240:'James Cowie differs from the anonymous maker of a Katar dagger;1985.119 is institution-scoped.'}
