"""Document verified wave80 and preserve every outstanding museum/source queue."""
import hashlib,importlib.util,json
from pathlib import Path
z=importlib.util.spec_from_file_location('a',Path(__file__).with_name('museum-expansion-milan-apply-20261009.py'));a=importlib.util.module_from_spec(z);z.loader.exec_module(a);m=a.m
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 report=m.load(m.RUN/'verification-after-wave-80.json');assert(report['verified_new_artworks'],report['verified_existing_artworks_linked'],report['institutions_with_new_records_or_reconciled_holdings'])==(10259,1450,220);p,d=a.validate_plan()
 with m.connect() as db:verified=a.verify(db,p,d)
 cp=m.load(a.CHECKPOINT);root=m.RUN/'README.md';pin=next(v for v in cp['artifacts'] if v['path']==str(root.relative_to(m.ROOT)));assert sha(root)==pin['sha256'];backup=m.BACKUP/'milan-root-readme-before-001.json.gz';assert not backup.exists()
 assert all(not(a.RUN/n).exists() for n in ['checks-001.json','remaining-research-001.json.gz','next-museum-pass-001.json','README.md','readme-supersessions-001.json'])
 lr=Path('/Users/vadimdulub/Library/Logs');test=(lr/'artline-milan-tests-20261009.log').read_text();assert 'Ran 18 tests' in test and test.rstrip().endswith('OK');assert (lr/'artline-milan-replay-20261009.log').read_text().strip()=='Unchanged replay: zero writes'
 logs={v.name:dict(path=str(v),sha256=sha(v)) for v in sorted(lr.glob('artline-milan-*-20261009*.log')) if 'delivery' not in v.name and 'checkpoint' not in v.name}
 ds=m.load(a.REVIEW)['decisions'];held=[v for v in ds if v['state']!='approved_existing_holding'];assert len(held)==29;target_urls={d['facts']['native_url'] for d in ds};assert len(target_urls)==151
 natives=m.load(a.RUN/'native-objects-001.json.gz')['rows']+m.load(a.RUN/'native-followup-001.json.gz')['rows'];allobjects={n['index']['url']:n for r in natives for n in r.get('objects',[])};extras=[v for k,v in allobjects.items() if k not in target_urls]
 m.save(a.RUN/'native-addition-leads-001.json.gz',dict(at=m.now(),rows=extras,source_references=[a.reference(a.RUN/'native-objects-001.json.gz'),a.reference(a.RUN/'native-followup-001.json.gz')],policy='Already captured incidental results of selected-object searches. Unapproved leads only: perform date, object type, creator/version, duplicate and museum checks before any addition. Ensemble parents must not duplicate their individually inventoried components. No images captured.'))
 m.save(a.RUN/'checks-001.json',dict(at=m.now(),new_offline_tests_passed=18,historical_tests_passed=1520,cumulative_verified_tests=1538,historical_tests_rerun=False,replay_zero_writes=True,source_objects_reviewed=151,new_artworks=0,existing_links=122,duplicate_candidate_holds=23,version_holds=6,unknown_dates_preserved=60,logs=logs,other_job_totals_separate=True,matched_native_object_pages=151,unique_selected_native_pages=len(allobjects),additional_native_leads=len(extras),previous_failed_read_only_runs_preserved=True))
 m.save(a.RUN/'remaining-research-001.json.gz',dict(at=m.now(),rows=held,review_reference=a.reference(a.REVIEW),previous_remaining_research_reference=a.reference(a.prior.RUN/'remaining-research-001.json.gz'),additional_native_leads_reference=a.reference(a.RUN/'native-addition-leads-001.json.gz'),native_probe_reference=a.reference(a.RUN/'native-probes-001.json'),policy='23 probable existing duplicates and6 unresolved versions remain pending, unchanged. Preserve all prior British, Italian and wider queues and source access holds. Milan147linked/87eligible needs13 additional eligible works or separate evidence-backed date review for100eligible, and53 further linked works for200. No quota-based approvals.'))
 oldq=m.load(a.checked(cp['next_museum_pass_reference']));live=m.load(m.RUN/'after-wave-80.json');by={v['id']:v for v in live['institutions']};italian=[dict(v,current_linked=by[v['institution_id']]['works'],current_eligible=by[v['institution_id']]['eligible_works']) for v in oldq['italian_museums']];assert len(italian)==225
 targets=[by[k] for k in ['e9875e7e-6531-50fe-8236-8fc98663ce03','e70682a7-16ed-5ad7-bee5-83773756899c']];network='022bf39a-6bac-5a80-a905-e603077e3718'
 with m.connect() as db:
  pending=db.execute("SELECT h.institution_id::text,a.current_institution_id::text,a.status,count(*) AS n FROM artwork_location_assertions h JOIN artworks a ON a.id=h.artwork_id WHERE h.institution_id=ANY(%s::uuid[]) AND h.review_state='review' AND h.superseded_by IS NULL AND h.claim_type='holding' GROUP BY h.institution_id,a.current_institution_id,a.status ORDER BY h.institution_id,a.current_institution_id,a.status",([v['id'] for v in targets],)).fetchall()
 m.save(a.RUN/'next-museum-pass-001.json',dict(at=m.now(),previous_queue_reference=cp['next_museum_pass_reference'],italian_museums=italian,existing_holding_review_targets=targets,upcoming_pending_by_current_institution=pending,ulster_network_authority=by[network],milan_remaining=by[a.IID],remaining_research_reference=a.reference(a.RUN/'remaining-research-001.json.gz'),native_discovery_reference=a.reference(a.RUN/'native-probes-001.json'),policy='Continue Brighton and Ulster exact saved object evidence. Ulster119 pending includes53 already accepted under National Museums Northern Ireland network; these are not automatically missing works or interchangeable museum branches. Fresh branch/object evidence required. Native collection services discovered from official links:collections.brightonmuseums.org.uk andcollections.nationalmuseumsni.org. They have not yet been probed in this pass. Preserve every prior source restriction; do not retry blocked Art UK, ArCo or regional endpoints. Milan and broader goal remain unfinished.',database_writes=0))
 text=f'''# Milan holding review — 9 October 2026

Accepted **122 museum links for existing local artworks** at Museo Nazionale della Scienza e della Tecnologia Leonardo da Vinci. No new artwork records were created.

| Measure | Before | After |
| --- | ---: | ---: |
| Linked artworks | 25 | 147 |
| Eligible creation dates | 25 | 87 |
| Pending associations | 151 | 29 |

The 100 linked-record milestone is met. **60 newly linked works retain unknown date classifications**; Milan still needs 13 more eligible works or a separate supported date review to reach 100 eligible, and 53 more linked works to reach the preferred 200. No creation date was invented or silently corrected.

All 151 pending records were individually checked against exact saved Italian national-catalogue evidence and 151 matched native museum object pages. The first search pass was limited to these 151 existing claims; five gaps were resolved through narrower searches or exact observed links. Native inventory, creator, description, dates, materials, measurements, acquisition and location wording are preserved. Primary response hashes and derived triples were verified; native pages were parsed again before writes. Comparison-only normalization covered literal escaped whitespace and three documented typographic corrections. A life-size wooden portrait of Amanzia Guerillot is explicitly matched to IGB8492 despite the museum's revised date (1856–1859 versus imported circa1850) and dress-color description (blue versus black); original catalogue values remain unchanged.

[The decisions](editorial-reviewed-001.json.gz) retain **23 probable duplicates** of already linked Milan works and **six unresolved version comparisons**. No duplicate was added to inflate coverage. Distinct small paintings sharing frames keep their individual component inventory suffixes; ensemble parents are not added. Literal private ownership labels remain distinct from museum holdings, and native storage or room labels do not create display claims.

The [plan](milan-existing-holdings-001-plan-001.json.gz) and [receipt](milan-existing-holdings-001-applied.json) verify 122 citations and accepted holding assertions. Original pending assertions retain their evidence and point to the accepted assertions. Only museum projection and update timestamps changed. Exact readback protects 5,545 scoped records and 11,587 earlier campaign records. Eighteen offline guards and a zero-write replay passed. No metadata, dates, artist links, images or review statuses changed; no commits or deployment.

The [remaining research](remaining-research-001.json.gz) preserves all 29 held records and earlier queues. {len(extras)} separately captured native object pages remain [unapproved addition leads](native-addition-leads-001.json.gz); they need fresh eligibility and duplicate review. The [next queue](next-museum-pass-001.json) retains 225 Italian museums and selects Brighton and Ulster. Official public overview pages were captured for both. Ulster's network-level holdings must remain separate from its museum branch. All previous source access holds remain in force.

Campaign total: **10,259 new artworks and 1,450 reconciled existing holdings across 220 institutions**, or **11,709 distinct records**. **{report['after']['museums_below_100']:,} canonical museums remain below 100 linked works** and **{report['after']['museums_below_200']:,} below 200**. The full goal remains active.
'''
 (a.RUN/'README.md').write_text(text)
 before=root.read_text();split=before.index('\n## Added works');intro=before[:split].replace('1,328 existing','1,450 existing').replace('expand 219 institutions','expand 220 institutions').replace('1,243',format(report['after']['museums_below_100'],',')).replace('after-wave-79','after-wave-80').replace('Cardiff and Bristol passes','Cardiff, Bristol and Milan passes');contents=intro+before[split:]+'\n\n## Milan holding reconciliation\n\nThe [Milan review](native/milan-holdings-20261009/README.md) accepted **122 existing-artwork museum links**, bringing the science and technology museum to **147 linked works / 87 with eligible dates**. Twenty-three probable duplicates and six unresolved versions remain pending. Sixty accepted works retain unknown dates. The preferred 200 and the 100 eligible-date threshold remain unfinished.\n\nThe [wave80 verification](verification-after-wave-80.json) records **10,259 additions and 1,450 reconciliations across 220 institutions**. **'+format(report['after']['museums_below_100'],',')+' canonical museums remain below 100 linked works**. The full goal remains active.\n'
 oldsha=sha(root);m.save(backup,dict(at=m.now(),path=str(root.relative_to(m.ROOT)),sha256=oldsha,text=before));root.write_text(contents);m.save(a.RUN/'readme-supersessions-001.json',dict(at=m.now(),changes=[dict(path=str(root.relative_to(m.ROOT)),before_sha256=oldsha,after_sha256=sha(root),backup_path=str(backup),backup_sha256=sha(backup))]));print(json.dumps(dict(documented_existing_links=122,campaign_new=10259,campaign_links=1450,institutions=220,remaining_below100=report['after']['museums_below_100'],native_extra_leads=len(extras))),flush=True)
if __name__=='__main__':main()
