"""Freeze verified wave79 and preserve the entire unfinished all-museum goal."""
import csv,hashlib,importlib.util,json
from pathlib import Path
z=importlib.util.spec_from_file_location('a',Path(__file__).with_name('museum-expansion-britain-three-apply-20261009.py'));a=importlib.util.module_from_spec(z);z.loader.exec_module(a);m=a.m
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 dest=a.RUN/'delivery-checkpoint-001.json';assert not dest.exists();assert sha(a.CHECKPOINT)=='3549d2a58984862b897a730fa68f00dd8ce49f4825a6f46819ca6ae6dc2d441c';previous=m.load(a.CHECKPOINT);assert (len(previous['artifacts']),len(previous['external_artifacts']))==(25716,507)
 changes=m.load(a.RUN/'readme-supersessions-001.json')['changes'];changed={v['path']:v for v in changes};assert set(changed)=={str((m.RUN/'README.md').relative_to(m.ROOT))}
 for c in changes:
  assert sha(Path(c['backup_path']))==c['backup_sha256'];x=m.load(Path(c['backup_path']));assert hashlib.sha256(x['text'].encode()).hexdigest()==x['sha256']==c['before_sha256'];assert sha(m.ROOT/c['path'])==c['after_sha256']
 for dep in previous['artifacts']:
  if dep['path'] in changed:assert dep['sha256']==changed[dep['path']]['before_sha256']
  else:a.checked(dep)
 plan,digest=a.validate_plan();assert digest=='7ebda40a62a85d90bf09bb55d1fa977b1f00da836b500a39dc99ee7f4af90672'
 with m.connect() as db:verified=a.verify(db,plan,digest)
 assert verified['protected_existing_records']==4820 and verified['prior_campaign_records_preserved']==11432
 assert m.load(a.RUN/(a.KEY+'-applied.json'))['plan_sha256']==digest
 report=m.load(m.RUN/'verification-after-wave-79.json');assert (report['verified_new_artworks'],report['verified_existing_artworks_linked'],report['institutions_with_new_records_or_reconciled_holdings'])==(10259,1328,219);changes_by={v['institution_id']:v for v in report['britain_three_museum_changes']};assert {k:(v['existing_linked'],v['linked_after'],v['eligible_after']) for k,v in changes_by.items()}==dict(zip(a.IIDS,[(131,158,112),(24,24,21)]));assert (report['after']['museums_below_100'],report['after']['museums_below_200'])==(1243,1389)
 checks=m.load(a.RUN/'checks-001.json');assert (checks['new_offline_tests_passed'],checks['historical_tests_passed'],checks['cumulative_verified_tests'])==(20,1500,1520) and checks['replay_zero_writes'];audit=m.load(m.RUN/'after-wave-79.json');csvcounts={};ids=[]
 for name,count in [('added-artworks-after-wave-79.csv',10259),('reconciled-artworks-after-wave-79.csv',1328),('gac-date-enrichments-after-wave-79.csv',6),('museum-coverage-after-wave-79.csv',len(audit['institutions']))]:
  with (m.RUN/name).open(newline='') as fp:rows=list(csv.DictReader(fp))
  assert len(rows)==count;csvcounts[name]=count
  if name.startswith(('added-artworks','reconciled-artworks')):ids.extend(v['artwork_id'] for v in rows)
 assert len(ids)==len(set(ids))==11587
 external=previous['external_artifacts']+list(checks['logs'].values())+[dict(path=v['backup_path'],sha256=v['backup_sha256']) for v in changes]+[dict(path=plan['backup_path'],sha256=plan['backup_sha256'])]
 reviewed=m.BACKUP/(a.KEY+'-reviewed-plan-001.json.gz');assert m.load(reviewed)==plan;external.append(dict(path=str(reviewed),sha256=sha(reviewed)));proof=m.BACKUP/(a.KEY+'-transaction-identity-001.json.gz');x=m.load(proof);assert x['comparisons_equal'] and len(x['comparisons'])==284;external.append(dict(path=str(proof),sha256=sha(proof)))
 revision=m.load(a.RUN/'review-revision-001.json');a.checked(revision['previous_review_reference']);b=revision['previous_reviewer_backup'];external.append(b);x=m.load(Path(b['path']));assert hashlib.sha256(x['text'].encode()).hexdigest()==x['sha256']==revision['previous_reviewer_sha256'];assert m.load(a.checked(revision['previous_review_reference']))['reviewer_reference']['sha256']==x['sha256'];assert (revision['before_approved'],revision['after_approved'],revision['database_writes'])==(157,155,0)
 log=Path('/Users/vadimdulub/Library/Logs/artline-britain-three-delivery-20261009.log');assert '"documented_existing_links": 155' in log.read_text();external.append(dict(path=str(log),sha256=sha(log)));unique={}
 for dep in external:
  assert dep['path'] not in unique or unique[dep['path']]==dep;unique[dep['path']]=dep;assert sha(Path(dep['path']))==dep['sha256']
 refs=[]
 for name,count in [('source-context-001.json.gz',162),('comparison-source-context-001.json.gz',43),('bristol-network-context-001.json.gz',123)]:
  v=m.load(a.RUN/name);assert len(v['body_references'])==count;refs+=v['body_references']
 refs += [v['body_reference'] for v in m.load(a.RUN/'bristol-multiple-creators-context-001.json.gz')['rows']];assert len({v['path'] for v in refs})==324
 native=m.load(a.RUN/'cardiff-native-001.json.gz');assert len(native['rows'])==134 and sum(v['state']=='captured_exact_inventory' for v in native['rows'])==133 and not native['requests_stopped'];assert sum(v['existing_status']=='published' and v['state']=='approved_existing_holding' for v in m.load(a.REVIEW)['decisions'])==1
 a.checked(previous['other_job_status_reference']);paths={m.ROOT/v['path'] for v in previous['artifacts']}|{a.CHECKPOINT,Path(__file__).resolve()};paths|={v for v in a.RUN.rglob('*') if v.is_file()};paths|={v for pattern in ['*britain-three*20261009.py','*britain_three*20261009.py'] for v in (m.ROOT/'ops').glob(pattern)};paths|={v for v in m.RUN.glob('*after-wave-79*')};paths|={a.checked(v) for v in refs};artifacts=[a.reference(v) for v in sorted(paths)]
 queue=m.load(a.RUN/'remaining-research-001.json.gz');assert len(queue['rows'])==129;nextq=m.load(a.RUN/'next-museum-pass-001.json');assert len(nextq['italian_museums'])==225 and len(nextq['existing_holding_review_targets'])==3
 result=dict(at=m.now(),goal_complete=False,local_only=True,new_additions=0,new_existing_links=155,campaign_new_artworks=10259,campaign_existing_links=1328,distinct_campaign_artwork_ids=11587,institutions_with_new_records_or_reconciled_holdings=219,verification=verified,museum_changes=report['britain_three_museum_changes'],museums_below_100=1243,museums_below_200=1389,global_coverage_snapshot_at=report['global_coverage_snapshot_at'],external_registry_growth_reference=report['external_registry_growth_reference'],new_tests_passed=20,historical_tests_passed=1500,cumulative_verified_tests=1520,plan_sha256=digest,csv_counts_verified=csvcounts,artifacts=artifacts,external_artifacts=list(unique.values()),prior_checkpoint_reference=a.reference(a.CHECKPOINT),prior_artifacts_verified=len(previous['artifacts']),intentional_supersessions=changes,review_revision_reference=a.reference(a.RUN/'review-revision-001.json'),other_job_status_reference=previous['other_job_status_reference'],other_job_totals_separate=True,editorial_holds=129,network_holds=123,other_holds=6,unknown_dates_preserved=41,existing_published_record_preserved=1,review_reference=a.reference(a.REVIEW),remaining_research_reference=a.reference(a.RUN/'remaining-research-001.json.gz'),next_museum_pass_reference=a.reference(a.RUN/'next-museum-pass-001.json'),new_source_access_hold_reference=a.reference(a.RUN/'source-access-holds-001.json'),native_probe_reference=a.reference(a.RUN/'native-probes-001.json'),runtime=previous['runtime'],next_work='155 verified existing links:131 Cardiff,24 Bristol;0new artworks. Cardiff158linked/112eligible,Bristol specific branch24/21;Bristol network123/111 preserved as a separate authority. 41unknown dates and one existing published status preserved. Six object/version/attribution holds plus123 network-to-branch claims remain pending. Native shared-authorship evidence for Bristol85and157 revised the initial draft before writes. Campaign10259new+1328links=11587 distinct protected records. Continue Milan science-and-technology museum,Brighton and Ulster selected saved-source review;retain225 Italian museums,all earlier object queues and every source access hold. Bristol native403/robots,Art UK403,ArCo timeouts,regionalTLS,MuseiReali403 remain. Current source worker terminal;concrete155-link progress,no repeated global blocker. The all-museum100minimum/200preferred goal remains active.')
 m.save(dest,result);print(json.dumps(dict(checkpoint=str(dest.relative_to(m.ROOT)),sha256=sha(dest),artifacts=len(artifacts),external_artifacts=len(unique),existing_links=155,campaign_new=10259,campaign_links=1328,below100=1243)),flush=True)
if __name__=='__main__':main()
