"""Reviewed exact-code collection destinations; no institution merges or display claims."""
import hashlib,importlib.util,json
from pathlib import Path
s=importlib.util.spec_from_file_location('n',Path(__file__).with_name('museum-expansion-france-thirteenth-native-20261008.py'));n=importlib.util.module_from_spec(s);s.loader.exec_module(n);m=n.m
CONTEXTS={
'M0537':dict(source='epinal',city='Epinal',names=["musée de l'image"],locations=["Epinal ; musée de l'image",'Epinal ; musée de l’image'],owners=["Epinal;musée de l'image",'Epinal;musée de l’image'],basis='Official M0537 explicitly distinguishes the municipal Musée de l’Image from the private Imagerie business. Exact code, city, object destination and municipal owner required. Departmental MUDAAC ownership and deposits remain excluded; the common city does not establish municipal ownership.'),
'M1098':dict(source='tomi-ungerer',city='Strasbourg',names=['musée Tomi Ungerer'],locations=["Strasbourg ; musée Tomi Ungerer centre international de l'illustration",'Strasbourg ; musée Tomi Ungerer'],owners=["Strasbourg;musée Tomi Ungerer centre international de l'illustration",'Strasbourg;musée Tomi Ungerer'],basis='Official M1098 gives Musée Tomi Ungerer - Centre international de l’Illustration as an alternate name and describes the municipal museum drawing collection. Exact code, city and municipal owner distinguish held original drawings from related published illustrations or other Strasbourg institutions.'),
'M0634':dict(source='roubaix',city='Roubaix',names=["La Piscine - musée d'art et d'industrie André Diligent de Roubaix"],locations=["Roubaix ; La Piscine – musée d'art et d'industrie André Diligent de Roubaix","Roubaix ; La Piscine - musée d'art et d'industrie André Diligent"],owners=["Roubaix;La Piscine  u2013 musée d'art et d'industrie André Diligent de Roubaix","Roubaix;La Piscine - musée d'art et d'industrie André Diligent"],basis='Official M0634 identifies the same La Piscine / André Diligent institution in Roubaix. Literal source owner token u2013 is an encoding/punctuation anomaly between identical La Piscine and musée names; exact city, code and full current destination corroborate this municipal holding. Preserve the anomaly verbatim; no institution merge or legal-title rewrite.'),
'M0081':dict(source='despiau-wlerick',city='Mont-de-Marsan',names=['musée Despiau-Wlérick','musée Despiau Wlérick'],locations=['Mont-de-Marsan ; musée de la ville','Mont-de-Marsan ; musée Despiau Wlérick'],owners=['Mont-de-Marsan;musée de la ville','Mont-de-Marsan;musée Despiau Wlérick','Mont-de-Marsan;musée Despiau-Wlérick'],basis='Official M0081 identifies Despiau-Wlérick at Mont-de-Marsan and describes its history from the municipal collection at the Hôtel de Ville to Lacataye. Current object notices bearing that same code and explicit Despiau-Wlérick museum name use the generic musée de la ville destination and municipal owner. Accept only this exact code/city/name combination; generic municipal wording alone is insufficient.'),
'M0784':dict(source='la-fontaine',city='Château-Thierry',names=['musée Jean de la Fontaine'],locations=['Château-Thierry ; musée Jean de La Fontaine'],owners=['Château-Thierry;musée Jean de La Fontaine'],basis='Official M0784 names the Jean de La Fontaine museum in Château-Thierry and distinguishes original artworks from its illustrated-book library. Exact municipal holding accepted; books, their physically bound components and independent prints require separate unit review.')}

def main():
 dest=n.RUN/'museum-name-reconciliation-001.json';assert not dest.exists();x=m.load(n.DISCOVERY);targets={v['slug'].removeprefix('joconde-').upper():v for v in x['targets']};out={}
 for code,c in CONTEXTS.items():
  target=targets[code];stem=n.RUN/'museum-context-001'/(c['source']+'-museofile');text=stem.with_suffix('.txt').read_text();receipt=m.load(stem.with_suffix('.receipt.json'));assert receipt['status']==200 and code in text and m.norm(c['city']) in m.norm(text)
  assert all(m.norm(name) in m.norm(text) for name in c['names']);assert target['slug']=='joconde-'+code.lower()
  value=dict(c,institution_id=target['id'],owner_prefixes=['propriete de la commune'],evidence=[n.ref(stem.with_suffix(ext)) for ext in ['.txt','.html.gz','.receipt.json']],legal_title_claim=False,current_display_claim=False);out[code]=value
 m.save(dest,dict(at=m.now(),museums=out,discovery_reference=n.ref(n.DISCOVERY),reviewer_reference=n.ref(Path(__file__).resolve()),policy='Exact source museum code, city, names and municipal collection owner destinations. Holding only; no current-display claim, institution merge or legal-title determination.'))
 print(json.dumps({k:dict(name=targets[k]['name'],eligible=targets[k]['eligible_works']) for k in out}),flush=True)
if __name__=='__main__':main()
