"""Document wave93, prior queues and the corrected, fully verified selected addition."""
import collections,hashlib,importlib.util,json
from pathlib import Path
z=importlib.util.spec_from_file_location('a',Path(__file__).with_name('museum-expansion-leeds-additions-apply-v2-20261009.py'));a=importlib.util.module_from_spec(z);z.loader.exec_module(a);m=a.m;RUN=a.RUN;ref=a.reference;sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 report=m.load(m.RUN/'verification-after-wave-93.json');assert(report['verified_new_artworks'],report['verified_existing_artworks_linked'])==(10521,2806);assert sha(a.CHECKPOINT)=='26a8108923c90d2c86b4eaa6220145072d6e61dfe0d4a1683f483b98d697832c';cp=m.load(a.CHECKPOINT);applied=m.load(RUN/(a.KEY+'-applied.json'));assert applied['created']==49 and applied['existing_links']==0 and applied['verification']==report['leeds_cotmania_additions'];root=m.RUN/'README.md';pin=next(v for v in cp['artifacts'] if v['path']==str(root.relative_to(m.ROOT)));assert sha(root)==pin['sha256'];backup=m.BACKUP/'leeds-additions-root-readme-before-001.json.gz';assert not backup.exists()
 for name in ['checks-001.json','remaining-research-001.json.gz','next-museum-pass-001.json','README.md','readme-supersessions-001.json','source-availability-001.json','new-source-access-holds-001.json']:assert not(RUN/name).exists()
 logsroot=Path('/Users/vadimdulub/Library/Logs');test=(logsroot/'artline-leeds-additions-tests-v2-20261009.log').read_text();assert 'Ran 22 tests' in test and test.rstrip().endswith('OK');assert(logsroot/'artline-leeds-additions-replay-20261009.log').read_text().strip()=='Unchanged replay: zero writes';logs={v.name:dict(path=str(v),sha256=sha(v)) for v in sorted(logsroot.glob('artline-leeds-additions-*-20261009.log')) if not any(x in v.name for x in ['delivery','checkpoint'])};rollback=m.load(RUN/'rolled-back-attempt-001.json');assert rollback['committed_writes']==0 and rollback['scoped_and_prior_state_unchanged'];ctx=m.load(RUN/'comparison-source-context-001.json.gz');identity=m.load(RUN/'identity-003.json.gz');citations=m.load(RUN/'identity-citations-003.json.gz')
 m.save(RUN/'checks-001.json',dict(at=m.now(),new_offline_tests_passed=22,historical_tests_passed=1824,cumulative_verified_tests=1846,historical_tests_rerun=False,replay_zero_writes=True,source_objects_reviewed=50,new_artworks=49,existing_links=0,preserved_existing_gallery_holdings=88,editorial_holds=1,identity_artworks=len(identity['state']['artworks']),identity_citations=len(citations['citations']),verified_native_capture_checks=54,verified_native_raw_bodies=53,comparison_raw_bodies=len(ctx['body_references']),comparison_unreconstructed_bodies=len(ctx['unreconstructed_bodies']),logs=logs,other_job_totals_separate=True,rollback_reference=ref(RUN/'rolled-back-attempt-001.json'),source_refinements='Eight explicit creator qualifications based on exact native essays. First write failed object_form constraint and completely rolled back; corrected native Watercolour/ Drawing mapping to supported work_type watercolor/drawing with null icon-only object_form. Earlier20-check run superseded by22 checks and not added twice to cumulative total. No schema migration or legacy rewrite.'))
 m.save(RUN/'new-source-access-holds-001.json',dict(at=m.now(),rows=[],previous_source_hold_reference=cp['new_source_access_hold_reference'],policy='No source access refusals in this wave. All prior IWM,RCT,ArtUK,Navigator and other provider holds persist without retries or workarounds. Browser/web extractor failures on already captured public pages are not evidence of source permission.'))
 m.save(RUN/'source-availability-001.json',dict(at=m.now(),new_source_access_holds=[],new_source_access_hold_reference=ref(RUN/'new-source-access-holds-001.json'),previous_source_availability_reference=cp['source_availability_reference'],previous_source_hold_reference=cp['new_source_access_hold_reference'],native_probe_reference=ref(RUN/'native-probes-001.json'),comparison_context_reference=ref(RUN/'comparison-source-context-001.json.gz'),public_search_script_reference=ref(RUN/'public-search-script-001.json'),selected_object_references=[ref(RUN/n) for n in ['cotmania-objects-001.json.gz','cotmania-extra-objects-001.json.gz']],policy='Museum-commissioned public Cotmania object catalogue and research guide are primary evidence for Leeds Art Gallery. Public frontend search-only configuration used for bounded metadata discovery:40 of44 watercolour index records and10 selected dated drawings from a previously captured mixed40-hit search. Fifty exact object pages selected before fetching; no archive documents counted as artworks.54 native raw bodies and29 comparison bodies verified.12 older comparison citation bodies not reconstructed,not fresh confirmations. No image requests,PDFs,private access or held-provider workarounds.'))
 decisions=m.load(a.REVIEW)['decisions'];held=[v for v in decisions if v['state']=='editorial_hold'];assert len(held)==1 and held[0]['number']==18;oldremaining=m.load(a.checked(cp['remaining_research_reference']));oldq=m.load(a.checked(cp['next_museum_pass_reference']));live=m.load(m.RUN/'after-wave-93.json');by={v['id']:v for v in live['institutions']}
 m.save(RUN/'remaining-research-001.json.gz',dict(at=m.now(),rows=held,review_reference=ref(a.REVIEW),previous_remaining_research_reference=cp['remaining_research_reference'],additional_lead_review_reference=oldremaining['additional_lead_review_reference'],gallery_linked=137,gallery_eligible=111,remaining_to_100_linked=0,remaining_to_100_eligible=0,remaining_to_200_linked=63,remaining_to_200_eligible=89,policy='One new missing-object hold,no accepted holding. Four prior Leeds identity holds and16 selected GAC further-review leads with4specific gaps and2known matches persist via previous references. Gallery has reached100 linked and100eligible but not200. Source attributions and unknown dimensions preserved. No implied current display or revalidation of88 prior holdings.'))
 italian=[dict(v,current_linked=by[v['institution_id']]['works'],current_eligible=by[v['institution_id']]['eligible_works']) for v in oldq['italian_museums']];assert len(italian)==225;excluded=['Glasgow Museums Resource Centre','Kelvingrove Art Gallery and Museum','Burrell Collection','Bristol City Museum & Art Gallery','Imperial War Museum London'];nexttargets=sorted([v for v in live['institutions'] if v['kind']=='museum' and v['status']!='archived' and not v['canonical_institution_id'] and v['works']<100 and v['pending_associations']>0 and v['name'] not in excluded],key=lambda v:(-v['pending_associations'],v['id']))[:20];native_ids=list(dict.fromkeys([a.IID]+[v['id'] for v in oldq['native_addition_targets']]));current_ids=sorted({v['id'] for v in oldq['current_museums']}|{a.IID})
 m.save(RUN/'next-museum-pass-001.json',dict(at=m.now(),previous_queue_reference=cp['next_museum_pass_reference'],italian_museums=italian,existing_holding_review_targets=nexttargets,native_addition_targets=[by[iid] for iid in native_ids],current_museums=[by[iid] for iid in current_ids],southampton_pdf_leads_reference=oldq['southampton_pdf_leads_reference'],edinburgh_portrait_leads=oldq['edinburgh_portrait_leads'],leeds_selected_metadata_reference=oldq['leeds_selected_metadata_reference'],leeds_selected_lead_review_reference=oldq['leeds_selected_lead_review_reference'],leeds_cotmania_selected_reference=ref(RUN/'cotmania-selected-001.json.gz'),leeds_cotmania_extra_selection_reference=ref(RUN/'cotmania-extra-selection-001.json.gz'),remaining_research_reference=ref(RUN/'remaining-research-001.json.gz'),source_availability_reference=ref(RUN/'source-availability-001.json'),policy='Leeds now137linked/111eligible. Prefer a further bounded selection of eligible native Cotmania drawings and the4unfetched watercolour index leads,with exact accession/creator/date/missing/version review,to approach200eligible;89more needed. Do not download all930objects or images. Continue16GACleads with gallery-specific evidence. Other next institutions include TheBox,York,Harris from fresh under100 pending-association queue. All prior IWM,Royal,Glasgow,Southampton,Edinburgh,Guildhall and225Italian museum queues and access holds persist. Full goal active.',database_writes=0))
 text=f'''# Leeds Art Gallery Cotmania additions — 9 October 2026

Added **49 artworks** from the museum-commissioned [Cotmania catalogue](https://cotmania.org/). Leeds Art Gallery increased from **88 to 137 linked records**, including **111 with eligible pre-1971 creation dates**. Every addition remains in review. The gallery has passed the 100 minimum; 89 more eligible works are needed for 200.

The selection contains 39 watercolours and 10 drawings, subject to exact source classification counts in the reviewed plan. Fifty physical objects were reviewed. One, *Cottage on Yarmouth Denes*, is explicitly scheduled as missing since a December1973 audit and was excluded from accepted holdings. Archive pages were not counted as artworks. Public search metadata was bounded to selected leads; no exhaustive catalogue or image download took place.

Eight creator labels were explicitly qualified using the catalogue essays: Cooke instead of the old composite attribution, pupil drawings on three reverse sides, uncertain Thirtle authorship, a Cotman-circle lake scene and two works whose Cotman attribution the curator rejects. A separate tree study already retained its unidentified-pupil label. Munn and John Joseph Cotman remain distinct creators. Paired recto/verso images count as one sheet; two former Spanish Arquebusier titles describe separate accessioned musketeer drawings with different poses and reverses. Source model/engraving dates were not substituted for creation dates. No painter links were guessed.

The [review](editorial-reviewed-002.json.gz), [plan](leeds-cotmania-additions-001-plan-002.json.gz) and [transaction receipt](leeds-cotmania-additions-001-applied.json) retain exact object URLs, native fields, provenance, qualified attributions and physical-version decisions. Fresh bounded identity checks covered **{len(identity['state']['artworks']):,} artworks and {len(citations['citations']):,} citations**.54 native capture checks (53 unique bodies) and29 available comparison bodies were checksum-verified;12 older comparison bodies could not be reconstructed and are not presented as fresh confirmations. Numeric source-ID collisions from other collections were rejected as matches.

**22 offline checks, atomic database readback and zero-write replay passed.** All13,278 previous campaign records and381 scoped existing records were preserved. The first attempted transaction rolled back completely on an unsupported object-form value; the corrected plan uses the existing watercolor/drawing work types and leaves the icon-only object-form field empty. The failed attempt and correction remain [auditable](rolled-back-attempt-001.json). No schema changes, images, publication or current-display claims were added.

Campaign totals: **10,521 new artworks +2,806 reconciled existing artworks =13,327 distinct records across {report['institutions_with_new_records_or_reconciled_holdings']} institutions**. **{report['after']['museums_below_100']:,} canonical museums remain below100 linked records** and **{report['after']['museums_below_200']:,} below200**. [Continuing research](next-museum-pass-001.json) preserves the four older Leeds identity holds,16 selected GAC further-review leads and every other museum queue/source hold. The all-museum goal remains active.
'''
 counts=collections.Counter(v['facts']['work_type'] for v in decisions if v['state']=='approved_review_only_addition');assert counts=={'watercolor':39,'drawing':10}
 m.save(backup,dict(at=m.now(),path=str(root),text=root.read_text(),sha256=sha(root)));(RUN/'README.md').write_text(text);old=root.read_text();intro,rest=old.split('## Added works',1);intro=intro.replace('10,472','10,521').replace('1,231',f"{report['after']['museums_below_100']:,}").replace('after-wave-92','after-wave-93');root.write_text(intro+'## Added works'+rest+'\n\n## Leeds Art Gallery Cotmania additions — wave93\n\nAdded49 selected native catalogue works in review:39watercolours and10drawings. Gallery137linked/111eligible,above100;89moreeligible needed for200. One missing work excluded; qualified creators and physical sheet identity preserved. [Evidence and continuing work](native/leeds-additions-20261009/README.md). Campaign10,521new +2,806reconciled =13,327distinct across236institutions.22offline checks,atomic readback and zero-write replay passed after a fully rolled-back classification-mapping correction. Every earlier queue and source hold persists. Full goal active.\n');m.save(RUN/'readme-supersessions-001.json',dict(at=m.now(),changes=[dict(path=str(root.relative_to(m.ROOT)),before_sha256=pin['sha256'],after_sha256=sha(root),backup_path=str(backup),backup_sha256=sha(backup))]));print(json.dumps(dict(documented_new_records=49,documented_existing_links=0,held=1,tests=22,institutions_expanded=report['institutions_with_new_records_or_reconciled_holdings'],goal_complete=False)),flush=True)
if __name__=='__main__':main()
