"""Wave126 checkpoint after verified Kilkis production additions and images."""
import hashlib
import importlib.util
import json
from pathlib import Path

spec=importlib.util.spec_from_file_location('d',Path(__file__).with_name('museum-expansion-kilkis-delivery-20261010.py'))
d=importlib.util.module_from_spec(spec);spec.loader.exec_module(d)
a,c,m,RUN=d.a,d.c,d.m,d.RUN
sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest()

def main():
    dest=RUN/'delivery-checkpoint-001.json';assert not dest.exists()
    report=m.load(RUN/'delivery-001.json');checks=m.load(RUN/'checks-001.json');public=m.load(RUN/'public-delivery-001.json')
    assert report['added']==38 and report['existing_links']==0 and checks['readback_passed'] and checks['replay_zero_writes']
    assert public['public_image_hashes_matched']==53 and public['public_artwork_samples']==4
    plan,digest=a.validate_plan();assert digest==d.EXPECTED and c.ref(c.CP)['sha256']==c.CP_SHA
    prior=m.load(c.CP);oldpins={v['path']:v for v in prior['artifacts']};oldext={v['path']:v for v in prior['external_artifacts']}
    pins=dict(oldpins);external=dict(oldext)
    def add(pin,target):
        assert pin['path'] not in target or target[pin['path']]==pin,pin['path'];target[pin['path']]=pin
    paths={c.CP,c.RESEARCH_CP,a.PLAN,Path(__file__).resolve()}
    paths|={v for v in RUN.rglob('*') if v.is_file()}
    paths|={v for v in (m.ROOT/'ops').glob('*kilkis*20261010.py')}
    for path in sorted(paths):add(c.ref(path),pins)
    for pin in plan['evidence']:add(pin,pins)
    for pin in plan['external_evidence']:add(pin,external)
    for path in sorted(m.BACKUP.glob('kilkis-production-*.json*')):add(dict(path=str(path),sha256=sha(path)),external)
    add(dict(path=plan['backup_path'],sha256=sha(plan['backup_path'])),external)
    newpins=[v for v in pins.values() if oldpins.get(v['path'])!=v]
    newext=[v for v in external.values() if oldext.get(v['path'])!=v]
    for pin in newpins:c.checked(pin)
    for pin in newext:assert sha(pin['path'])==pin['sha256'],pin['path']
    protected=m.load(RUN/'protected-production-ids-001.json')['ids']
    expected=set(plan['prior_ids'])|{v['artwork_id'] for v in plan['records']}|{v['artwork_id'] for v in plan['images']}
    assert len(protected)==1837 and set(protected)==expected
    assert report['remaining_pending_candidates']=={} and report['remaining_pending_total']==0
    next_work='''Wave126 made verified production progress: Kilkis38 new review objects and53 authentic primary images,36 on new records and17 on existing records. Museum18 catalogue/0 numeric/0 primary to56 catalogue/0 numeric/53 primary.44 more documented works needed for100,144 for200. Campaign1815 new+5 existing links across12 museums. Preserve1837 IDs:1820 campaign additions/links plus17 existing Kilkis image-only updates. Real local unchanged; overall goal ACTIVE and incomplete.

Plan native/kilkis-delivery-20261010/kilkis-production-001-plan-001.json.gz SHA dd8da2ee896f6aba7981bbf4a0b0a75792402cad9770513215ddad136cbf39c5. Use ops/museum-expansion-kilkis-apply-20261010.py directly for validate_plan/verify.23 offline tests, atomic transaction verification, independent readback, zero-write replay,53 public image hashes and4 public directory samples passed. Backup1791645611635 SUCCESSFUL, operation905b4507-7eeb-40c1-aa10-6d6a00000024, ended2026-10-10T15:22:03.219Z. Applied15:26:02Z. Public undated directory search works; all records have null numeric dates, so do not use the dated atlas route to certify visibility. No artist links, publication changes, invented dates or current-display claims.

All65 SearchCulture Kilkis objects now metadata-reviewed, plus3 additional scholarly entries.38 new=24 earlier online candidates+12 newly selected index objects+2 book torsos. New types13 sculpture+25 unknown; actual decorative vessel/jewellery/epigraphic/architectural/armour forms preserved in native evidence. All creators unknown. Historical periods establish ancient/Byzantine scope, not precise years. Specific ancient/Byzantine periods support pre1956 image selection without numeric fabrication. NativeCC BY-NC-ND4 label preserved restricted; generic NC-SA footer kept separate and user Greek approval separate from any copyright-holder permission claim.53 complete frames compressed/resized proportionally at most99957bytes. All4 contacts and remaining-object contacts were viewed. Full originals/proofs Library only.

Twelve source-entry holds remain: bone1594/1595 parent-bed relationship; grape5859/5862 possible joining; AEMK3 description/image conflict; truncated book134; six5044A/B/G/D/E/ST components with unresolved assemblage identity. Existing AEMK2 has reciprocal image conflict and remains unillustrated; no swap/merge. AEMK3 new record not added. Existing1593 bone hands was already a record and gets a matched image; do not create1594/1595 to inflate counts. Old4461 smaller Aphrodite differs from new4460. Existing122 carved larnakidion photographed with inventory; native description empty preserved. Greave pair784 countsonce; fragment-joined vessels countonce; reused block128 and statuebase929 each countonce. No absent parent statue fabricated. NativeRoman vsSC Hellenistic forstele27 explicit conflict, numericnull. Activity42-31BCE for MarcusInsteius not creation date. Source names on inscriptions and mints not creators.

Book EleniPapagianni2025 ISBN9789601226781 public7-page excerpt https://sitestatic.shopster.gr/6150c0d864787b561e67912f/051223_de.pdf SHA b2b84770d2a9f89e4d763544c9ec16d89495cca706fd7a2765215d1a32747e7d. Newtorso331:36cm fine-white marble, unknown provenance, longneck/chestcurls,possibleApollo/Dionysus.2046:36cm coarse-offwhite marble,Europosacropolis discovery19Sept1994,twistingtorso/fittedrightshoulder,possiblewarrior/Heracles/satyr/centaur. Separateaccessions/form,not sameobject despiteequalheight. BothpossiblyLateHellenistic, numericnull. Requiredplate5absent so noimages. IDs kilkis-isbn9789601226781-inventory-331 and2046 with scheme museum-catalogue-isbn-9789601226781. SharedPDF URL not object identity. Entry134 incompleteheld; discovery1967 notcreation. BookApollo201 andAphrodite11 enrich sameonlineobjects,notduplicates.87sculptures bookclaim doesnotprovide87publicobjectentries.

Fresh boundedidentity267 artworks152 creatorlinks363 citations:26 exacttitle hits241 accessioncollisions18sourcecites18sourceIDs0imagehashhits.26 fullsnapshots=all18 oldKilkis+8 foreigncomparators.5existingpublicframes+4Kilkiscomparisonframes reviewed. SilverClevelandamphoriskos1986.183 API153210 is11.7cm silver; distinctclay1091/4154. LarnacaK-AD811(6f17b255-a9d7-5c29-ab18-5bbb6e1e45fb) glass11.7x5.2cm threehandles blue/yellow/whitefestoons, Egypt18thdynasty, CypruscataloguePDFpage166 sourceverified+renderedviewed. It is LARNACA, notKyoto. Othercomparators4Chaniavessels plusBellows1916lithograph andTamayo1969oil/sandtorso, allpreserved.241bareaccessioncollisions notidentity; noall241visualclaim. Sourcequery3.712s accession.740s title.549s recorded; not10Mloadproof.1782prior campaignIDs preserved.17oldimageIDs newly included in futureprotectedset, totals1837 not1820.

Only Kilkis institutional count refreshed.228 inherited under100 queue rows remain; notglobalcensus. Pendingresearchedready candidates0: oldKilkis26 plus12newnowdelivered. Sourceholds are not ready candidates. Kilkis needs genuinely new scholarly/nativeinventorysources because65publicindex exhausted. Chania192/117 still8below200 with108unreviewedentries14scopeholds; nativeamch.gr403 remains. Theocharakis215/137 andZongolopoulos216/67 catalogue200targets reached; Zong149unknown and63sourceidentityholds remain.

NEXT AthensCity Museum IID f575847e-47eb-59e4-b558-32d8723bc3c9, last18catalogue/16numeric at2026-10-09 (notfresh). Newdiscovery in thisRUN next-source-discovery-001.json.gz. SearchCulture https://www.searchculture.gr/aggregator/portal/collections/DigAthensMuseum?language=en returned200; observed2405items includes1634photos and numerous furnishings/documents/replicas/post1970works. Collectioncount not eligibleartworkcount. Defaultindex is variable order. Form GET /aggregator/portal/collections/DigAthensMuseum/search with keywords[0].value,page.page,resultsMode=GRID,sortResults=YEAR_ASC/TITLE/SCORE/YEAR_DESC. Native observed https://portal.athenscitymuseum.gr/artworks returned200SPA shell17302bytes, not parsedobjectrecords; no native image/object review yet. Use bounded metadata-first selection, prioritize specific originalpaintings/prints/sculpture; contemporary replicas and subjectdate titles not evidence ofcreationdate. Freshproduction identity/counts needed before additions. No Athens candidate or image downloaded yet.

Averoff IID ea977842-2f6e-5020-a853-d300b507aca0 last18/9. Native /zografiki403 W125 remains; do not retryprovider/alternateaccess. IndependentSearchCultureAveroffMuseum71 and retained earlierhomepage>700claim may aid laterresearch. Shopreproductions notoriginals. ALL inheritedprovider holds preserved, including journalMorrylos403,Zongnative403/eMuseumPlustimeout/XMLerrorHTML,Chania403,AIC159136403,Larissanative404/timeouts. W126SC5044A webtoolinaccessible internalerror was notHTTP403/429; observedrequests200, no new providerhold. No accessbypass.

Taskproxy127.0.0.1:55519 PID7614 --gcloud-auth revalidatedliveW126, leaveit and unrelated55445/55478 alone. Workinggcloudidentity; no credentialsprinting. Real localpostgresql://localhost/artline read-only, nofixtures/testDB/testURL. ResearchPython Libraryvenv containsbs4/PIL/psycopg butnotpypdf; systemPopplerworks. PDFskill wasreadandused W126; source7pages andLarnacapage166 werevisually inspected. AGENTSSHA ad0d8067ebf9a99e3198d1d6d0c9853e6acdd8932c5a5a0a9e5bb006416d0241 unchanged. Noagents,commits,deployments. Executed/pinnedwriters immutable; newversionsforcorrections. Originalimageinputs script failed after25 valid receipts onlybecause doublewhitespace in alt; v2normalizeswhitespace and completed53 usingreceipts. No sourcefailureorDBwrite occurredthen. Inherit fullarchiveproof a0480d7954d528917245e1a8158bcc542078d9346d5aae701a4ace2666ba3205; verifyonlynewpins/relevantsnapshots. W12545247 artifact3546externalpins inherited, notrehashentirehistory. Selectedproductionadditions/imagesalreadyauthorized; no repeatedapproval.'''
    result=dict(prior)
    result.update(at=m.now(),wave=126,goal_complete=False,goal_status='active',previous_goal_turn='progress',production_only=True,local_unchanged=True,new_additions=38,new_existing_links=0,new_images=53,verification=report['verification'],production_museum_before=report['museum_before'],production_museum_after=report['museum_after'],production_campaign_totals=report['production_campaign_totals'],global_production_counts_refreshed=False,global_production_thresholds_refreshed=False,new_tests_passed=23,plan_sha256=digest,plan_reference=c.ref(a.PLAN),prior_checkpoint_reference=c.ref(c.CP),previous_research_checkpoint=c.ref(c.RESEARCH_CP),artifacts=list(pins.values()),external_artifacts=list(external.values()),baseline_reference=c.ref(RUN/'baseline-verification-001.json'),review_reference=c.ref(a.REVIEW),checks_reference=c.ref(RUN/'checks-001.json'),public_delivery_reference=c.ref(RUN/'public-delivery-001.json'),production_institution_register_reference=c.ref(RUN/'production-institution-register-001.json.gz'),priority_museum_queue_reference=c.ref(RUN/'priority-museum-queue-001.json'),protected_production_ids_reference=c.ref(RUN/'protected-production-ids-001.json'),pending_candidates={},pending_candidate_total=0,global_threshold_summary_note='Only Kilkis refreshed to56 catalogue/0 numeric eligible. Other observations retain timestamps;228 priority rows are a subset.',source_availability=report['source_access'],remaining_research_reference=c.ref(RUN/'source-review-001.json.gz'),next_source_discovery_reference=c.ref(RUN/'next-source-discovery-001.json.gz'),preferred_target_remaining=dict(institution_id=c.IID,catalogue=56,gap_to100=44,gap_to200=144,target_reached=False,numeric_eligible=0),public_api_date_scope=public['date_scope_note'],next_work=next_work)
    result.pop('additional_research_checkpoint',None)
    m.save(dest,result)
    m.save(RUN/'final-checkpoint-verification-001.json',dict(at=m.now(),checkpoint=c.ref(dest),verified_new_artifact_pins=len(newpins),verified_new_external_pins=len(newext),inherited_unchanged_artifact_pins=len(pins)-len(newpins),inherited_unchanged_external_pins=len(external)-len(newext),full_historical_proof=prior['initial_full_historical_verification_reference'],plan_sha256=digest,goal_complete=False,actual_added=38,actual_existing_links=0,actual_images=53,protected_production_ids=1837,pending_candidates=0,local_unchanged=True))
    print(json.dumps(dict(checkpoint=c.ref(dest),artifacts=len(pins),external=len(external),verified_new=len(newpins),verified_external=len(newext),added=38,links=0,images=53,pending=0)),flush=True)

if __name__=='__main__':main()
