"""Freeze wave100 evidence, accounting and continuing museum research queue."""
import collections,gzip,hashlib,importlib.util,json
from pathlib import Path
z=importlib.util.spec_from_file_location('a',Path(__file__).with_name('museum-expansion-augustiner-apply-20261009.py'));a=importlib.util.module_from_spec(z);z.loader.exec_module(a);m=a.m;RUN=a.RUN;ref=a.reference;sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 report=m.load(m.RUN/'verification-after-wave-100.json');cp=m.load(a.CHECKPOINT);applied=m.load(RUN/(a.KEY+'-applied.json'));assert(report['verified_new_artworks'],report['verified_existing_artworks_linked'])==(11018,3036);assert applied['created']==129 and applied['verification']==report['augustiner_additions'];root=m.RUN/'README.md';pin=next(v for v in cp['artifacts'] if v['path']==str(root.relative_to(m.ROOT)));assert sha(root)==pin['sha256'];backup=m.BACKUP/'augustiner-root-readme-before-001.json.gz';assert not backup.exists()
 logsroot=Path('/Users/vadimdulub/Library/Logs');assert 'Ran 20 tests' in (logsroot/'artline-augustiner-tests-20261009-001.log').read_text();assert (logsroot/'artline-augustiner-tests-20261009-001.log').read_text().rstrip().endswith('OK');assert (logsroot/'artline-augustiner-replay-20261009-001.log').read_text().strip()=='Unchanged replay: zero writes'
 logs={p.name:dict(path=str(p),sha256=sha(p)) for p in sorted(logsroot.glob('artline-augustiner-*-20261009-*.log')) if not any(t in p.name for t in ['delivery','checkpoint'])};caps=[]
 for p in sorted((RUN/'captures').glob('*.json')):
  rc=m.load(p);body=p.with_suffix('.body.gz');assert hashlib.sha256(gzip.decompress(body.read_bytes())).hexdigest()==rc['sha256'];caps.append(dict(receipt_reference=ref(p),body_reference=ref(body),url=rc['url'],status=rc['status']))
 identity=m.load(RUN/'identity-003.json.gz');citations=m.load(RUN/'identity-citations-003.json.gz');ctx=m.load(RUN/'comparison-source-context-003.json.gz');ds=m.load(a.REVIEW)['decisions'];v=applied['verification'];assert(v['protected_existing_records'],v['prior_campaign_records_preserved'])==(173,13925)
 m.save(RUN/'checks-001.json',dict(at=m.now(),new_offline_tests_passed=20,historical_tests_passed=2005,cumulative_verified_tests=2025,historical_tests_rerun=False,replay_zero_writes=True,selected_candidates=130,new_artworks=129,existing_links=0,already_catalogued=0,editorial_holds=1,source_fact_holds=0,unknown_date_additions=3,date_eligible_additions=126,date_eligible_existing_links=0,identity_artworks=len(identity['state']['artworks']),identity_citations=len(citations['citations']),capture_status_counts=dict(collections.Counter(str(x['status']) for x in caps)),comparison_raw_bodies=len(ctx['body_references']),comparison_unreconstructed_citations=len(ctx['unreconstructed_bodies']),version_comparator_reference=ref(RUN/'version-comparators-001.json.gz'),logs=logs,other_job_totals_separate=True))
 proofs=m.load(RUN/'annual-report-visual-review-001.json')['pages']
 for dep in proofs:assert sha(Path(dep['path']))==dep['sha256']
 m.save(RUN/'retained-research-proofs-001.json',dict(at=m.now(),external_artifacts=proofs,visual_review_reference=ref(RUN/'annual-report-visual-review-001.json'),policy='Eleven visually reviewed museum report pages outsideDocuments. PDFs retainedcompressed withreceipts inresearch evidence. Noimageattachments.'))
 hold=dict(provider='Freiburg online collection',host='onlinesammlung.freiburg.de',status=None,observation='Explicit Access Denied / BotStopper (Anubis) fromwebtool;numericHTTPstatusnotprovided.',url='https://onlinesammlung.freiburg.de/de/search',evidence_reference=ref(RUN/'portal-access-hold-001.json'),reason='Stopportalaccess;noalternatepath,proxy,browserorprivateendpointattempts. Independentpublicmuseumannualreportsareseparatelypublishedresources.')
 m.save(RUN/'new-source-access-holds-001.json',dict(at=m.now(),rows=[hold],previous_source_hold_reference=cp['new_source_access_hold_reference']))
 m.save(RUN/'source-availability-001.json',dict(at=m.now(),new_source_access_holds=[hold],new_source_access_hold_reference=ref(RUN/'new-source-access-holds-001.json'),previous_source_availability_reference=cp['source_availability_reference'],previous_source_hold_reference=cp['new_source_access_hold_reference'],native_captures=caps,comparison_context_reference=ref(RUN/'comparison-source-context-003.json.gz'),policy='Fourselectedpublicmuseumreports2021–2024 andfourpublicHTMLpages. Legacy2022reportURL404;currentreportlinkedbyofficialpresspageavailable. Blockedonlinecollectionnotretried. Allprioraccessholdspersist. Searchcache/Commonslistusedasleadsonly,notacceptedobjectfacts.'))
 live=m.load(m.RUN/'after-wave-100.json');by={v['id']:v for v in live['institutions']};museum=by[a.IID];oldq=m.load(a.checked(cp['next_museum_pass_reference']))
 gaps=[dict(topic='Three accepted undated artworks',reason='KirnerweepingItalianoilsketch,LudwigZornBurkheim,EvaEisenlohrsmallunsignedlandscape remain review/unknown. Do not invent dates toreach200eligible.'),dict(topic='Unnamed groups',reason='About500Thomaprints,29Hasemannsketchbooks,GuidoSchreiber21Freiburgmotifs andotheralbums requireindividualobjectids/titles/physicalcount;notexpanded intoplaceholders.'),dict(topic='Remaining individually named report acquisitions',reason='Selectedpassdoesnotexhaustreports. Openendeddates,photographs,ceramics,miniatures,multipartworks andreproductions needseparateobject/versionreview.'),dict(topic='Museum highlights and medieval collection',reason='Nativeportaldenied. Minsterwindows,sculptures andaltarcomponents requireexactobjectidentity/groupcount. ExhibitionloansfromLouvre,Lindenau,privateGoiny,NewYork,etc arenotAugustinerholdings.')]
 m.save(RUN/'remaining-research-001.json.gz',dict(at=m.now(),rows=[v for v in ds if v['state']=='editorial_hold'],source_fact_holds=gaps,already_catalogued=[],reconciled_existing=[],review_reference=ref(a.REVIEW),previous_remaining_research_reference=cp['remaining_research_reference'],current_museums=[museum],source_gap='Augustiner215linked/199dateeligible. Linked100and200targetsmet;oneadditionaldatedworkneededfor200eligible. Fourannualreportsarenotcompletecollectioncoverage.',policy='Allpriorresearchqueues remain; noquotaoverridesevidence ormissingdates.'))
 queue=dict(oldq);queue.update(at=m.now(),previous_queue_reference=cp['next_museum_pass_reference'],italian_museums=[dict(v,current_linked=by[v['institution_id']]['works'],current_eligible=by[v['institution_id']]['eligible_works']) for v in oldq['italian_museums']],native_addition_targets=[by[v['id']] for v in oldq['native_addition_targets']],current_museums=[by[v['id']] for v in oldq['current_museums']],current_pass_museums=[museum],remaining_research_reference=ref(RUN/'remaining-research-001.json.gz'),source_availability_reference=ref(RUN/'source-availability-001.json'),policy='Augustiner215linked/199eligible;continueotherunder100museumsandprior200targets. Preserve225Italianinstitutions,allolderqueues,andproviderholds. Goalactive.',queue_database_writes=0);m.save(RUN/'next-museum-pass-001.json',queue)
 text=f'''# Augustiner Museum expansion — 9 October 2026

Added **129 source-backed artworks in review**. Augustiner Museum, Freiburg, rose from **86 to 215 linked artworks**, meeting both linked-record targets. **126 additions have documented pre-1971 dates; three remain undated.** Date-eligible coverage rose from **73 to 199**.

The museum’s own [annual reports, linked from its press page](https://museen.freiburg.de/presse), document individual acquisitions and gifts in 2021–2024. Four PDFs and eleven rendered pages were checked to distinguish the Augustiner sections from other municipal museums and temporary loans. [The decision ledger](editorial-reviewed-001.json.gz) retains source pages, creator roles, dates, object boundaries and uncertainty.

The selection includes Kirner paintings and studies, Morat views, Sandhaas portraits, Schuster watercolours, Rose posters, Dürr-Grossmann portraits and individual prints. Print impressions remain separate physical museum objects; original drawings and later reproductions are not interchanged. The repeated Gräßel acquisition was counted once. A mixed-technique work retains unknown type because the report does not supply one.

Feuerbach’s *Bacchische Szene* remains held: the report narrative says 1852/53 while its acquisition list says circa 1855. Three accepted works retain unknown dates: Kirner’s weeping Italian woman oil sketch, Zorn’s *Burkheim* and Eisenlohr’s unsigned small landscape. The online collection portal explicitly denied access; it was not retried. Independent museum reports supplied the accepted evidence.

**20 offline checks, atomic readback and zero-write replay passed.** All **173 scoped existing records** and **13,925 previous campaign records** were preserved. The expanded duplicate search covered **20,077 artworks and 42,525 citations**; 112 selected comparators received explicit version review. The source-context pass reconstructed one raw body and retained twelve unreconstructed citation bodies as a stated limitation. Existing citation evidence is not described as freshly verified external content.

No catalogue images, artist-authority links, publication or current-display claims were added. The pass meets linked-record targets but does not claim complete museum coverage. Further research can add the one dated work needed for 200 eligible records.

Campaign totals: **11,018 new + 3,036 reconciled = 14,054 distinct artworks across {report['institutions_with_new_records_or_reconciled_holdings']} institutions**. **{report['after']['museums_below_100']:,} canonical museums remain below 100 linked works**, and **{report['after']['museums_below_200']:,} remain below 200**. [The continuing queue](next-museum-pass-001.json) preserves all prior institutions and unresolved evidence. The full goal remains active.
'''
 assert not(RUN/'README.md').exists();m.save(backup,dict(at=m.now(),path=str(root),text=root.read_text(),sha256=sha(root)));(RUN/'README.md').write_text(text)
 old=root.read_text();intro,rest=old.split('## Added works',1);intro=intro.replace('10,889','11,018').replace('1,226','1,225').replace('after-wave-99','after-wave-100').replace('expand 239 institutions',f"expand {report['institutions_with_new_records_or_reconciled_holdings']} institutions").replace('The latest pass adds 11 works with eligible dates, three with dates still unknown, and one existing dated holding link.','The latest pass adds 126 works with eligible dates and three with dates still unknown.')
 table='| Distinct new-record campaign total | **10,889** | **220 collections** |';assert table in rest;newcols=sum(int(v['added_this_campaign'])>0 for v in __import__('csv').DictReader((m.RUN/'museum-coverage-after-wave-100.csv').open()));rest=rest.replace(table,f'| Augustiner Museum — selected annual-report acquisitions | 129 | 1 museum |\n| Distinct new-record campaign total | **11,018** | **{newcols} collections** |',1)
 root.write_text(intro+'## Added works'+rest+'\n\n## Augustiner Museum — wave100\n\nAdded 129 review works: 126 dated and three undated. Freiburg’s Augustiner Museum now has 215 linked / 199 date-eligible works, up from 86 / 73; both linked-record targets are met. One Feuerbach date conflict remains held. Twenty offline checks, atomic readback and zero-write replay preserved 173 scoped existing and 13,925 prior campaign records. Four museum annual reports and eleven rendered pages were reviewed; no images were attached. The blocked collection portal was not retried. [Evidence and continuing queue](native/augustiner-20261009/README.md). Campaign: 11,018 new + 3,036 reconciled = 14,054 distinct records. All prior queues persist and the goal remains active.\n')
 m.save(RUN/'readme-supersessions-001.json',dict(at=m.now(),changes=[dict(path=str(root.relative_to(m.ROOT)),before_sha256=pin['sha256'],after_sha256=sha(root),backup_path=str(backup),backup_sha256=sha(backup))]));print(json.dumps(dict(documented_new_records=129,documented_existing_links=0,held=1,tests=20,goal_complete=False)))
if __name__=='__main__':main()
