"""Record verified delivery and retain preferred200/date/image/source gaps."""
import csv,importlib.util,json
from pathlib import Path
spec=importlib.util.spec_from_file_location('d',Path(__file__).with_name('museum-expansion-spathario-delivery-20261010.py'))
d=importlib.util.module_from_spec(spec);spec.loader.exec_module(d)
a,c,m,RUN=d.a,d.c,d.m,d.RUN
NEXT='760b0104-19ee-5ad1-94f0-0ceb8dcea09e'

def table(name,rows):
    with (RUN/name).open('x',encoding='utf-8-sig',newline='') as h:
        w=csv.DictWriter(h,fieldnames=list(rows[0]));w.writeheader();w.writerows(rows)

def main():
    assert not(RUN/'delivery-001.json').exists();checks=m.load(RUN/'checks-001.json');read=m.load(RUN/'readback-001.json');public=m.load(RUN/'public-delivery-001.json')
    assert checks['readback_passed'] and checks['replay_zero_writes'] and checks['local_unchanged'] and public['public_artwork_samples']==6
    p,digest=a.validate_plan();assert digest==d.EXPECTED;prior=m.load(c.CP);at=m.now();assert read['verification']['current_counts']=={c.IID:dict(linked=131,eligible=123)}
    rr=prior['production_institution_register_reference'];register=m.load(c.checked(rr))['rows'];target=next(x for x in register if x['id']==c.IID);assert target['verified_production_works']==16
    target.update(production_catalogue_count_to_200=131,production_date_eligible_count_to_200=123,production_catalogue_count_state='exact',production_date_eligible_count_state='exact',verified_production_works=131,verified_production_eligible_works=123,production_catalogue_count_at=read['at'],production_date_eligible_count_at=read['at'])
    m.save(RUN/'production-institution-register-001.json.gz',dict(at=at,rows=register,previous_register_reference=rr,read_only=True,updated_institutions=[c.IID],global_exact_counts_refreshed=False,global_thresholds_refreshed=False,policy='OnlySpathariorefreshed:131catalogue,123numericdateeligible,8unknown. Otherobservations retain theirtimestamps.'));table('production-institution-register-001.csv',register)
    qr=prior['priority_museum_queue_reference'];queue=m.load(c.checked(qr));assert len(queue['rows'])==224 and any(x['id']==c.IID for x in queue['rows']);queue['rows']=[x for x in queue['rows'] if x['id']!=c.IID]
    reached=dict(id=c.IID,at=read['at'],catalogue=131,date_eligible=123,basis='115newreview artworkunits from117sourceentries;107dateeligible8unknown. Minimum100 reached;69morecatalogueworks needed forpreferred200.')
    queue.setdefault('removed_threshold_reached',[]).append(reached);queue['latest_removed_threshold_reached']=reached;queue['latest_preferred_target_remaining']=dict(institution_id=c.IID,catalogue=131,gap_to100=0,gap_to200=69,target_reached=False,numeric_eligible=123)
    queue.setdefault('date_research_remaining',[]).append(dict(id=c.IID,catalogue=131,date_eligible=123,unknown_dates=8,crossing_cutoff=0,reason='SixAthanasopoulospuppetunits:source1930versusdocumented1931performance;two photographicframes/assemblages have unresolvedactualcreation.'))
    queue.update(at=at,previous_queue_reference=qr,policy='Spatharioreached131catalogue and leaves inheritedunder100subset.223rowsremain,63Greek;notfreshglobalcensus.69workpreferred200gapremains.');m.save(RUN/'priority-museum-queue-001.json',queue)
    table('delivered-production-artworks-001.csv',[dict(artwork_id=v['artwork_id'],institution_id=c.IID,action='new_record',source_ids=' | '.join(v['facts']['source_ids']),title=v['facts']['title'],date_display=v['facts']['date_display'],creation_year_start=v['facts']['first'],creation_year_end=v['facts']['last'],source_url=v['facts']['source_url'],status='review') for v in p['records']])
    table('delivered-production-images-001.csv',[dict(artwork_id=x['artwork_id'],source_id=x['source_id'],number=x['number'],primary=True,storage_path=x['storage_path'],sha256=x['sha256'],bytes=x['bytes'],width=x['width'],height=x['height'],rights_status=x['rights_status'],rights_label=x['rights_label'],source_url=x['source_url']) for x in p['images']])
    protected=sorted(set(p['prior_ids'])|{x['artwork_id'] for x in p['records']});assert len(protected)==2798
    totals=dict(new_artworks=prior['production_campaign_totals']['new_artworks']+115,existing_links=prior['production_campaign_totals']['existing_links'],museums=prior['production_campaign_totals']['museums']+1);assert totals==dict(new_artworks=2774,existing_links=7,museums=17)
    m.save(RUN/'protected-production-ids-001.json',dict(at=at,ids=protected,previous_protected_records=2683,new_records=115,new_existing_links=0,composition=dict(campaign_new_artworks=2774,campaign_existing_links=7,additional_existing_image_only_records=17),plan_reference=c.ref(a.PLAN)))
    decisions=m.load(RUN/'editorial-source-decisions-001.json.gz')['rows']
    remaining=dict(at=at,institution_id=c.IID,catalogue=131,preferred200_reached=False,catalogue_gap_to200=69,numeric_date_eligible=123,unknown_numeric_dates=8,new_unknown_numbers=[v['facts']['number'] for v in p['records'] if v['facts']['first'] is None],source_total=450,description_artifact_count=453,individual_objects_reviewed=156,later_index_only=294,scope_holds=[x['number'] for x in decisions if x['decision']=='scope_hold'],identity_holds=[124],merged_source_units={24:[24,151],149:[149,125]},ready_candidates=0,resolution_gap='64delivered sourcepreviews max380pxwide or550pxhigh, completeJPEGbytesunchanged, maximum51113bytes. NativeobjectpageHTTP200frontend shell; no higherresolutionimageobserved. No imagegeneration orenlargement.',next_priority='Jewish Museum of Greece, IID '+NEXT+'; last8catalogueworks. Freshbaseline and bounded art-type/date selection required.1044searchableresults versusdescription1046assets,1642–2009,640photographicarchiveentries; archive/document counts are not eligibleartwork counts.',next_source_reference=c.ref(RUN/'next-source-discovery-001.json.gz'),inherited_nikaia_reference=c.ref(c.DISCOVERY));m.save(RUN/'remaining-research-001.json',remaining)
    backup=m.load(RUN/'cloud-backup-001.json');report=dict(at=at,goal_complete=False,production_only=True,local_unchanged=True,plan_sha256=digest,added=115,existing_links=0,date_eligible_new=107,new_unknown_numeric_dates=8,new_crossing_cutoff_dates=0,verification=read['verification'],museum_before=dict(works=16,eligible_works=16,primary_images=7),museum_after=dict(works=131,eligible_works=123,primary_images=71),minimum100_catalogue_reached=True,preferred200_catalogue_reached=False,catalogue_gap_to100=0,catalogue_gap_to200=69,production_campaign_totals=totals,historical_local_totals_unchanged=prior['historical_local_campaign_totals'],cross_database_totals_combined=False,new_images=64,new_primary_images=64,new_alternate_images=0,new_artist_links=0,remaining_pending_candidates={},remaining_pending_total=0,global_production_counts_refreshed=False,global_production_thresholds_refreshed=False,backup_id=backup['id'],source_access='All15Spathariometadataindexpages,156objectpages and156sourcepreviewsHTTP200. Nativepublicobject182returnsfrontend shell. SecondarychronologyvmrebetikoTLSfailurebeforeHTTP(webtool502);independentLiFOpublishedmemoirresearch available. NextTossitzacollectionHTTP500held,no retry; JewishcollectionHTTP200.',next_work=remaining['next_priority']);m.save(RUN/'delivery-001.json',report)
    text=f'''# Spathario Shadow Theatre Museum — 10 October 2026

Added **115 review artwork units** and **64 authentic images** in production. Spathario increased from **16 to 131 catalogue works**, including **123 date-eligible works**, **eight unresolved creation dates**, and **71 illustrated works**. The minimum 100 target is met; **69 more catalogue works** are needed for the preferred 200. The real local database remains unchanged.

- [Delivered artworks](delivered-production-artworks-001.csv)
- [Delivered images](delivered-production-images-001.csv)
- [Candidate review](candidate-review-001.csv)
- [Verification](checks-001.json)
- [Remaining research](remaining-research-001.json)

The [museum-supplied SearchCulture collection](https://www.searchculture.gr/aggregator/portal/collections/Mar_Spathareio?language=en) has 450 searchable records, while its description says 453 artifacts. All 450 index entries were reviewed as bounded museum metadata. The 294 entries with index dates after 1970 were excluded from this selection before individual-object or image retrieval. We read 156 individual records dated through 1970 or undated, including all 16 existing catalogue entries, then reviewed their 156 authentic preview images on seven contact sheets and four focused frames. All those source requests succeeded.

The additions include original shadow puppets, theatrical scenery, painted posters, selected illustrated prints, intact papercraft sheets, and two framed photographic assemblages. Ordinary tickets, text-led leaflets, sound and lighting equipment, a generic award, a letter reproduction and a plain text publication were not selected as artworks. The aircraft record titled Stukas remains held for object/title reconciliation. No works were invented to meet the target.

The 115 artwork units preserve **117 source records**. Two police-puppet entries show opposite sides of the same object; both source IDs and titles remain in citations for one artwork. The skeleton-on-a-spit scene and its separately photographed operating figure are retained as one ensemble. Papercraft sheets with two serial numbers remain single printed objects. A group of two children, a dog-and-catcher scene and a four-design scenery collage each remain one documented unit. The two skeleton puppets and two mistranslated Manolopoulos characters have visibly distinct compositions.

Six index entries without dates explicitly say **19th century** in their museum descriptions; their catalogue ranges remain 1801–1900. Seven source records for the Athanasopoulos drama say 1930, while [published research on the memoirs](https://www.lifo.gr/culture/vivlio/sotiris-spatharis-ta-apomnimoneymata-enos-karagkiozopaihti) dates the performance poster to 1931. Reuse of older puppets versus a source error remains unresolved. These become six physical units after reconciling the opposite-side police images, with unknown execution dates; 1931 was not invented as an artwork date. Two photographic assemblages also have unresolved manufacture/assembly dates, separate from their source photograph dates.

Literal maker fields distinguish Sotiris and Evgenios Spatharis from the earlier character designers named in titles. No matching existing artist records were found in the bounded name/alias check, so maker names remain object-level labels. Publisher names are not treated as illustrators, and a frame carver is distinguished from the unidentified photographer. No artists, aliases or biographies were created. The museum's Chinese Figure5 title is retained with an explicit unresolved-origin note rather than an inferred geographic attribution. Original bilingual metadata and title/description conflicts remain in the evidence.

All **64 delivered JPEGs are byte-identical to the reviewed source previews**, with complete supplied frames and margins, at most **51,113 bytes** each. Their actual resolution is at most 380 pixels wide or 550 pixels high. The source object pages supply no separate digital-file links; the observed native object page returns a JavaScript frontend shell. Higher-resolution originals remain an improvement gap. No authenticated native endpoint, client credentials, enlargement, retouching or generated image was used.

The actual item-level preview licence is **CC BY-NC-SA 4.0**, retained as **restricted** with museum credits, source links and an unchanged-file notice. It is separate from the website footer licence. Existing user approval for the Greek museum workflow is recorded separately and is not represented as copyright-holder permission or public-domain status. No new image was delivered for an unknown creation date or a work created after 1955. Existing seven images remain unchanged.

Bounded source-ID, informative-title, creator-label and image-checksum reconciliation returned only the 16 existing Spathario artworks and 23 citations. These records and all **2,683 previously protected campaign records** remain unchanged. Query plans and timings were saved; this is not an exhaustive global duplicate guarantee or a ten-million-row performance test.

Backup **{backup['id']}** succeeded before the atomic transaction. Seventeen evidence and read-only backend checks passed, followed by atomic verification, independent readback and a zero-write replay. All 64 public image hashes and six public artwork samples were verified. Every addition remains in review, with accepted collection holdings and no current-display or publication claims. Plan SHA-256: `{digest}`.

The selected production campaign now totals **2,774 new artworks and seven existing-work links across 17 museums**. The protected set contains 2,798 records, including 17 earlier image-only enrichments. Only Spathario's totals were refreshed; the inherited under-100 subset has 223 rows, including 63 Greek institutions. It is not a fresh global census. The every-museum goal remains active.

Next: the Jewish Museum of Greece, with eight previously observed catalogue works. Its SearchCulture collection returned 1,044 searchable records and describes 1,046 assets, including 640 photographic archive entries, across 1642–2009. Mixed archive totals do not establish eligible artwork coverage. Tossizza Mansion's collection landing page returned HTTP500 and remains held without a retry. The previously discovered Nikaia collection and all inherited research/access gaps remain tracked.
'''
    with (RUN/'README.md').open('x',encoding='utf-8') as h:h.write(text)
    print(json.dumps(dict(added=115,images=64,catalogue=131,numeric_eligible=123,protected_ids=2798,priority_rows=len(queue['rows']),greek_rows=sum(x['country_code']=='GR' for x in queue['rows']))),flush=True)

if __name__=='__main__':main()
