"""Document verified wave74 and preserve the research queue."""
import collections,hashlib,importlib.util,json
from pathlib import Path
z=importlib.util.spec_from_file_location('a',Path(__file__).with_name('museum-expansion-italy-third-apply-20261008.py'));a=importlib.util.module_from_spec(z);z.loader.exec_module(a);m=a.m
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 report=m.load(m.RUN/'verification-after-wave-74.json');assert report['verified_new_artworks']==9913;plan,digest=a.validate_plan()
 with m.connect() as db:verified=a.verify(db,plan,digest)
 logsroot=Path('/Users/vadimdulub/Library/Logs');prefix='artline-italy-third-';testlog=(logsroot/(prefix+'tests-20261008.log')).read_text();assert 'Ran 13 tests' in testlog and testlog.rstrip().endswith('OK');assert (logsroot/(prefix+'replay-20261008.log')).read_text().strip()=='Unchanged replay: zero writes'
 logs={p.name:dict(path=str(p),sha256=sha(p)) for p in sorted(logsroot.glob(prefix+'*-20261008.log')) if p.name not in [prefix+'delivery-20261008.log',prefix+'checkpoint-20261008.log']}
 ds=m.load(a.REVIEW)['decisions'];states=collections.Counter(v['state'] for v in ds);assert states=={'approved_review_only_addition':242,'editorial_hold':65,'deferred_identity_review':217}
 checks=a.RUN/'checks-001.json';assert not checks.exists();m.save(checks,dict(at=m.now(),new_offline_tests_passed=13,historical_tests_passed=1431,cumulative_verified_tests=1444,historical_tests_rerun=False,replay_zero_writes=True,source_notices_assessed=524,successful_object_responses_reparsed=524,added=242,editorial_holds=65,deferred_identity_candidates=217,logs=logs,other_job_totals_separate=True))
 original={v['number']:v for v in m.load(a.RUN/'native-candidates-002.json.gz')['rows']};comps={v['number']:v for v in m.load(a.RUN/'native-identity-002.json.gz')['comparisons']};queue=[]
 for d in ds:
  if d['state']=='approved_review_only_addition':continue
  row=original[d['number']];queue.append(dict(d,source_issues=row['issues'],source_reference=row.get('source_reference'),source_url=row['index_record']['source_url'],existing_source_hits=comps.get(d['number'],{}).get('source_hits',[])))
 m.save(a.RUN/'remaining-research-001.json.gz',dict(at=m.now(),rows=queue,review_reference=a.reference(a.REVIEW),inventory_audit_reference=a.reference(a.RUN/'comparison-source-context-002.json.gz'),policy='282 notices retained for further research. Shared inventory/support and recatalogue questions must be reconciled before counting another physical object. Malformed dates, crossed histories, qualified attributions and external custody narratives remain explicit. No quota-based approvals.'))
 cp=m.load(a.CHECKPOINT);priority=cp['next_museum_pass_reference'];a.checked(priority);oldqueue=m.load(m.ROOT/priority['path']);live={v['id']:v for v in m.load(m.RUN/'after-wave-74.json')['institutions']};nextm=[]
 for v in oldqueue['italian_museums']:
  cur=live[v['institution_id']]
  if cur['eligible_works']<100:nextm.append(dict(v,current_linked=cur['works'],current_eligible=cur['eligible_works']))
 m.save(a.RUN/'next-museum-pass-001.json',dict(at=m.now(),previous_queue_reference=priority,italian_museums=nextm,current_five_museum_research_reference=a.reference(a.RUN/'remaining-research-001.json.gz'),policy='Prioritize underfilled museums toward100. These five now meet100eligible; preserve their unresolved queue and preference for200. Cached leads require current exact object,city,custody,version and creation-date checks.',database_writes=0))
 changes=report['italy_third_museum_changes'];table='| Museum | Added | Linked before → after | Eligible before → after |\n| --- | ---: | ---: | ---: |\n'+'\n'.join('| '+v['name']+' | '+str(v['new'])+' | '+str(v['linked_before'])+' → '+str(v['linked_after'])+' | '+str(v['eligible_before'])+' → '+str(v['eligible_after'])+' |' for v in changes)
 text='''# Third Italian minimum pass — 8 October 2026

Added **242 real local artwork records**. All five museums now have at least100 eligible works. Each addition has an exact national-catalogue identifier, source citation and accepted museum-holding assertion; all artworks remain in review.

'''+table+'''

The bounded source selection comprised524 notices:124 Oderzo,37 ManlioTrucco,123 Bari,121 Mansi and119 Pisa. All524 object pages returned successfully and were reconstructed together with exact ArCo RDF responses. Six Bari graph batches hit a10000-row truncation because a shared Address node had thousands of inverse links. The original HTTP200 bodies are preserved. Narrower queries omitted Address-node traversal while keeping exact root,current museum/city and HTML address checks;90 object graphs were repaired. No access denial was bypassed and no failed object page retried. The [source adjustments](source-review-adjustments-001.json) document this and the custody interpretation: detenzione means custody, not ownership; an exact deposito room label at a verified museum means storage, not current display or an external loan.

The full identity screen covered29,993 existing artworks and61,740 citations. The final selected274-object comparison used18,289 artworks, adding search-only English titles and former/related maker names. It also included111 objects in five related Pisa collection records. These were comparison scopes, not institution mergers. Original titles and school/qualified maker labels remain unchanged.

The [historical inventory audit](comparison-source-context-002.json.gz) reconstructed637 source contexts from166 pinned response bodies. It found four collisions invisible in the existing sparse artwork fields; two further selected paintings shared inventory2101. All six were withdrawn before writes. The [final242 decisions](editorial-reviewed-002.json.gz) supersede the preliminary248. Shared-support Martini sheets, conflicting source dates, crossed illustration histories, Mansi recatalogued family trees and Pisa inventory4456 sitter reidentifications remain outside the release.

Physical distinctions include separate Martini illustration/design sheets, four separately inventoried Massoni still-life canvases, copies versus prototypes, a preparatory cartoon versus the finished altarpiece, and panel versus canvas Sebastian paintings. Whole cycles and their components are not counted twice. Cretan and Byzantine school paintings remain first-class records without invented named creators. Explicit measurement units are retained and absent units remain unknown. Holdings do not establish current display.

**65 source/editorial holds and217 deferred identities remain** in the [research queue](remaining-research-001.json.gz). These museums still have work toward200. The [next-museum queue](next-museum-pass-001.json) prioritizes'''+str(len(nextm))+''' other Italian museums below100eligible works. Existing source-access holds elsewhere in the campaign remain in force.

The [transaction plan](italy-third-additions-001-plan-001.json.gz) and [application receipt](italy-third-additions-001-applied.json) verify242 artworks,identifiers,citations and holding assertions. All426 initial target objects,3,911 scoped comparison objects and10,456 prior campaign records were preserved. A fresh comparison ran inside the transaction. Thirteen offline checks and a zero-write replay passed;1,431 historical checks remain pinned and were not rerun. Backups are in the Artline Library backup directory. No images,painter links,publication or display claims were added; no commits or deployment.

Campaign totals: **9,913 new artworks and785 reconciled holding links across'''+str(report['institutions_with_new_records_or_reconciled_holdings'])+''' institutions**. The live audit still has **'''+format(report['after']['museums_below_100'],',')+''' canonical museums below100linked artworks** and'''+format(report['after']['museums_below_200'],',')+''' below200. The global goal remains active. The separate minimum100 job is separately counted. Next work must rebase to668 target records and10,698 prior campaign records, not reuse this pass's426/10,456 initial scopes.
'''
 targets=[(a.RUN/'README.md',text)];root=m.RUN/'README.md';pin=next(v for v in cp['artifacts'] if v['path']==str(root.relative_to(m.ROOT)));assert sha(root)==pin['sha256'];before=root.read_text();split=before.index('\n## Added works');intro=before[:split].replace('9,671','9,913').replace('202 local museums',str(report['museums_expanded'])+' local museums').replace('expand 205 institutions','expand '+str(report['institutions_with_new_records_or_reconciled_holdings'])+' institutions').replace('1,254',format(report['after']['museums_below_100'],',')).replace('after-wave-73','after-wave-74')
 lines=before[split:].splitlines();ix=next(n for n,v in enumerate(lines) if v.startswith('| Italian national catalogue / ArCo — second'));lines.insert(ix+1,'| Italian national catalogue / ArCo — third minimum pass | 242 | 5 museums |');ix=next(n for n,v in enumerate(lines) if v.startswith('| Distinct new-record campaign total |'));lines[ix]='| Distinct new-record campaign total | **9,913** | **'+str(report['institutions_expanded'])+' collections** |'
 targets.append((root,intro+'\n'.join(lines)+'\n\n## Third Italian minimum pass\n\nThe [third Italian pass](native/italy-third-minimum-20261008/README.md) added **242 review records**, bringing all five targets above100eligible works.\n\n'+table+'\n\nExact readback,13 offline checks and a zero-write replay passed. The [wave74 verification](verification-after-wave-74.json) records **9,913 additions and785 holding reconciliations across'+str(report['institutions_with_new_records_or_reconciled_holdings'])+' institutions**. '+format(report['after']['museums_below_100'],',')+' canonical museums remain below100linked works. Research continues; the all-museum goal is unfinished.\n'))
 supers=[]
 for index,(path,contents) in enumerate(targets):
  backup=m.BACKUP/('italy-third-readme-before-'+str(index+1).zfill(3)+'.json.gz');assert not backup.exists();oldhash=sha(path);m.save(backup,dict(at=m.now(),path=str(path.relative_to(m.ROOT)),sha256=oldhash,text=path.read_text()));path.write_text(contents);supers.append(dict(path=str(path.relative_to(m.ROOT)),before_sha256=oldhash,after_sha256=sha(path),backup_path=str(backup),backup_sha256=sha(backup)))
 m.save(a.RUN/'readme-supersessions-001.json',dict(at=m.now(),changes=supers,policy='Campaign root README and this pass in-progress README replaced with verified delivery. Exact previous texts preserved. No policy or previous delivery source artifacts changed.'))
 print(json.dumps(dict(documented=242,campaign_total=9913,expanded=report['institutions_with_new_records_or_reconciled_holdings'],museums_expanded=report['museums_expanded'],remaining_below100=report['after']['museums_below_100'],next_underfilled_italian_museums=len(nextm))),flush=True)
if __name__=='__main__':main()
