"""Document wave73 and preserve the outstanding source/identity queue."""
import collections,hashlib,importlib.util,json
from pathlib import Path
s=importlib.util.spec_from_file_location('a',Path(__file__).with_name('museum-expansion-italy-second-apply-20261008.py'));a=importlib.util.module_from_spec(s);s.loader.exec_module(a);m=a.m
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 report=m.load(m.RUN/'verification-after-wave-73.json');assert report['verified_new_artworks']==9671;plan,digest=a.validate_plan()
 with m.connect() as db:verified=a.verify(db,plan,digest)
 logsroot=Path('/Users/vadimdulub/Library/Logs');prefix='artline-italy-second-';testlog=(logsroot/(prefix+'tests-20261008.log')).read_text();assert 'Ran 10 tests' in testlog and testlog.rstrip().endswith('OK');assert (logsroot/(prefix+'replay-20261008.log')).read_text().strip()=='Unchanged replay: zero writes'
 logs={p.name:dict(path=str(p),sha256=sha(p)) for p in sorted(logsroot.glob(prefix+'*-20261008.log')) if p.name not in [prefix+'delivery-20261008.log',prefix+'checkpoint-20261008.log']}
 ds=m.load(a.REVIEW)['decisions'];states=collections.Counter(v['state'] for v in ds);assert states=={'approved_review_only_addition':88,'editorial_hold':416,'deferred_identity_review':389}
 checks=a.RUN/'checks-001.json';assert not checks.exists();m.save(checks,dict(at=m.now(),new_offline_tests_passed=10,historical_tests_passed=1421,cumulative_verified_tests=1431,historical_tests_rerun=False,replay_zero_writes=True,source_notices_assessed=893,successful_object_responses_reparsed=891,object_timeouts_retained=2,added=88,editorial_holds=416,deferred_identity_candidates=389,logs=logs,other_job_totals_separate=True))
 remaining=[v for v in ds if v['state']!='approved_review_only_addition'];original={v['number']:v for v in m.load(a.RUN/'native-candidates-001.json.gz')['rows']};comps={v['number']:v for v in m.load(a.RUN/'native-identity-001.json.gz')['comparisons']};queue=[]
 for d in remaining:
  row=original[d['number']];queue.append(dict(d,source_issues=row['issues'],source_reference=row.get('source_reference'),source_url=row['index_record']['source_url'],existing_source_hits=comps.get(d['number'],{}).get('source_hits',[])))
 m.save(a.RUN/'remaining-research-001.json.gz',dict(at=m.now(),rows=queue,review_reference=a.reference(a.REVIEW),policy='805 notices are retained, not approved. Pavia159 empty object-page shells are source-unavailable despite RDF metadata. Six Pavia exact regional URLs already match database works; reconcile, never duplicate. Fano532 matches a sparse existing Ceccarini record. Historical external deposits are collection research, not fresh physical custody. Timeouts are preserved without retry.'))
 priority=m.load(a.CHECKPOINT)['next_museum_pass_reference'];a.checked(priority);oldqueue=m.load(m.ROOT/priority['path']);live={v['id']:v for v in m.load(m.RUN/'after-wave-73.json')['institutions']};nextm=[]
 for v in oldqueue['italian_museums']:
  cur=live[v['institution_id']]
  if cur['eligible_works']<100:nextm.append(dict(v,current_linked=cur['works'],current_eligible=cur['eligible_works']))
 m.save(a.RUN/'next-museum-pass-001.json',dict(at=m.now(),previous_queue_reference=priority,italian_museums=nextm,current_five_museum_research_reference=a.reference(a.RUN/'remaining-research-001.json.gz'),policy='Prioritize other underfilled museums toward minimum100. Cached leads require exact source/physical/city/creation checks; no automatic quota approvals. Four Italian targets now exceed100eligible; retained queue supports later work toward200. Pavia has291linked but80eligible and remains under date/identity review.',database_writes=0))
 changes=report['italy_second_museum_changes'];table='| Museum | Added | Linked before → after | Eligible before → after |\n| --- | ---: | ---: | ---: |\n'+'\n'.join('| '+v['name']+' | '+str(v['new'])+' | '+str(v['linked_before'])+' → '+str(v['linked_after'])+' | '+str(v['eligible_before'])+' → '+str(v['eligible_after'])+' |' for v in changes)
 text='''# Second Italian minimum pass — 8 October 2026

Added **88 real local artwork records**, each with a primary-source citation, external identifier and accepted museum holding. **Four more museums now meet100 eligible works**. All additions remain in review.

'''+table+'''

The bounded research selection covered893 notices:177 Estense,190 Albertina,164 Corsini,182 Fano and180 Pavia. The Italian Ministry object pages and exact ArCo RDF subject responses were captured, with891 successful page responses and two retained timeouts. Of the successful pages,159 Pavia responses were empty catalogue shells; these are not approvals. Source receipt hashes and actual SPARQL responses were independently reconstructed. An initial query exceeded the endpoint's documented10000-row sorted limit; the preserved server error was diagnosed and the corrected bounded query succeeded. No access denial was bypassed and no failed object request was retried.

The first identity scope included41,615 existing artworks and83,287 citations. The selected93-object supplemental pass used4,779 existing artworks, adding comparison-only English titles and former/related maker names from source histories. Five additional cases were deferred, leaving88 additions. A separate museum-local inventory audit reconstructed140 pinned historical source bodies and found no selected inventory collisions. Existing regional Lombardia URL aliases identified six Pavia records already in the database. Those are not duplicated.

The [editorial review](editorial-reviewed-001.json.gz) records individual physical-unit and comparison reasons. It distinguishes the two Calori Cesis portraits by canvas/panel, size and inventory; separated Scandiano frescoes; paintings copied after lost or extant prototypes; distinct Vacca theatrical sheets; and separate Fano canvases within a twelve-picture group. Vernier floor plans and structurally similar sheets remain deferred where orientation alone would not establish a separate leaf. Anonymous schools, attributed authors and workshop/manner qualifiers remain object labels. No painter authority was invented. Explicit units and frame notes are retained; missing measurement units remain explicitly unknown. Museum holdings do not assert present display.

**416 source/editorial holds and389 deferred identities remain**. These include historical external deposits needing qualified holding interpretation, empty Pavia pages, existing-object reconciliations, date/attribution issues and unresolved physical versions. The [remaining queue](remaining-research-001.json.gz) and [next-museum queue](next-museum-pass-001.json) preserve the work. Four targets meet100eligible; their200-work preference remains open. Pavia has291linked records, including80eligible; linked counts are not invented eligible dates.

The [transaction plan](italy-second-additions-001-plan-001.json.gz) and [application receipt](italy-second-additions-001-applied.json) verify88 artworks, identifiers, citations and holding assertions. All807 initial target objects,1,040 scoped comparison objects and10,368 prior campaign records were preserved. A fresh identity comparison ran inside the write transaction. Ten offline checks and a zero-write replay passed;1,421 historical checks remain pinned and were not rerun. Backups are under the Artline Library backup directory. No catalogue images, display claims, publication changes, commits or deployment.

Preparation initially stopped before writes because another workflow added the museum-browsing paragraph to AGENTS.md. The exact old text was reconstructed and its previous hash verified; the [policy supersession](policy-supersession-001.json) preserves both versions. The new instruction does not authorize invented works or change this review-only catalogue scope. All remaining prior artifact pins verified.

Campaign totals are **9,671 new artworks and785 reconciled holding links across'''+str(report['institutions_with_new_records_or_reconciled_holdings'])+''' institutions**. The live audit still has **'''+format(report['after']['museums_below_100'],',')+''' canonical museums below100linked works**, and'''+format(report['after']['museums_below_200'],',')+''' below200. The global goal remains active. The separate minimum100 job remains separately counted. Next work should start from895 target objects and10,456 campaign records, not reuse this pass's807-object initial snapshot.
'''
 target=a.RUN/'README.md';assert not target.exists();target.write_text(text)
 root=m.RUN/'README.md';cp=m.load(a.CHECKPOINT);pin=next(v for v in cp['artifacts'] if v['path']==str(root.relative_to(m.ROOT)));assert sha(root)==pin['sha256'];before=root.read_text();backup=m.BACKUP/'italy-second-root-readme-before-001.json.gz';assert not backup.exists();m.save(backup,dict(at=m.now(),path=str(root.relative_to(m.ROOT)),sha256=sha(root),text=before))
 split=before.index('\n## Added works');intro=before[:split].replace('9,583','9,671').replace('199 local museums',str(report['museums_expanded'])+' local museums').replace('expand 202 institutions','expand '+str(report['institutions_with_new_records_or_reconciled_holdings'])+' institutions').replace('1,255',format(report['after']['museums_below_100'],',')).replace('after-wave-72','after-wave-73')
 lines=before[split:].splitlines();ix=next(n for n,v in enumerate(lines) if v.startswith('| Italian national catalogue / ArCo |'));lines.insert(ix+1,'| Italian national catalogue / ArCo — second minimum pass | 88 | 4 museums |');ix=next(n for n,v in enumerate(lines) if v.startswith('| Distinct new-record campaign total |'));lines[ix]='| Distinct new-record campaign total | **9,671** | **'+str(report['institutions_expanded'])+' collections** |'
 root.write_text(intro+'\n'.join(lines)+'\n\n## Second Italian minimum pass\n\nThe [second Italian pass](native/italy-second-minimum-20261008/README.md) added **88 review records**, bringing four museums above100eligible works.\n\n'+table+'\n\nExact readback, ten offline checks and a zero-write replay passed. The [wave73 verification](verification-after-wave-73.json) records **9,671 additions and785 holding reconciliations across'+str(report['institutions_with_new_records_or_reconciled_holdings'])+' institutions**. '+format(report['after']['museums_below_100'],',')+' canonical museums remain below100linked works. Research continues; the all-museum goal is unfinished.\n')
 m.save(a.RUN/'readme-supersessions-001.json',dict(at=m.now(),changes=[dict(path=str(root.relative_to(m.ROOT)),before_sha256=pin['sha256'],after_sha256=sha(root),backup_path=str(backup),backup_sha256=sha(backup))],policy='Only campaign README changed by this delivery; earlier text preserved. Concurrent AGENTS addition separately audited.'))
 print(json.dumps(dict(documented=88,campaign_total=9671,expanded=report['institutions_with_new_records_or_reconciled_holdings'],museums_expanded=report['museums_expanded'],remaining_below100=report['after']['museums_below_100'],next_underfilled_italian_museums=len(nextm))),flush=True)
if __name__=='__main__':main()
