"""Document verified wave87 holdings and carry all unresolved research forward."""
import hashlib,importlib.util,json
from pathlib import Path
z=importlib.util.spec_from_file_location('a',Path(__file__).with_name('museum-expansion-britain-eight-apply-20261009.py'));a=importlib.util.module_from_spec(z);z.loader.exec_module(a);m=a.m
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 report=m.load(m.RUN/'verification-after-wave-87.json');assert(report['verified_new_artworks'],report['verified_existing_artworks_linked'],report['institutions_with_new_records_or_reconciled_holdings'])==(10417,2481,230);plan,digest=a.validate_plan()
 with m.connect() as db:verified=a.verify(db,plan,digest)
 cp=m.load(a.CHECKPOINT);root=m.RUN/'README.md';pin=next(v for v in cp['artifacts'] if v['path']==str(root.relative_to(m.ROOT)));assert sha(root)==pin['sha256'];backup=m.BACKUP/'britain-eight-root-readme-before-001.json.gz';assert not backup.exists()
 for name in ['checks-001.json','remaining-research-001.json.gz','next-museum-pass-001.json','README.md','readme-supersessions-001.json','source-availability-001.json','new-source-access-holds-001.json']:assert not(a.RUN/name).exists()
 logsroot=Path('/Users/vadimdulub/Library/Logs');test=(logsroot/'artline-britain-eight-tests-20261009.log').read_text();assert 'Ran 31 tests' in test and test.rstrip().endswith('OK');assert(logsroot/'artline-britain-eight-replay-20261009.log').read_text().strip()=='Unchanged replay: zero writes'
 logs={v.name:dict(path=str(v),sha256=sha(v)) for v in sorted(logsroot.glob('artline-britain-eight-*-20261009.log')) if 'delivery' not in v.name and 'checkpoint' not in v.name}
 m.save(a.RUN/'checks-001.json',dict(at=m.now(),new_offline_tests_passed=31,historical_tests_passed=1689,cumulative_verified_tests=1720,historical_tests_rerun=False,replay_zero_writes=True,source_objects_reviewed=191,pending_assertions_reviewed=191,new_artworks=0,existing_links=184,editorial_holds=7,logs=logs,other_job_totals_separate=True,source_recovery='Official current Southampton and Culture Edinburgh redirects observed. Gulbenkian and Flowers web-reader cache misses were not access denials; one bounded ordinary request per exact page succeeded. No prior source access hold retried.'))
 m.save(a.RUN/'new-source-access-holds-001.json',dict(at=m.now(),rows=[],policy='No new access denials. Preserve all prior access holds; no ArtUK requests.'))
 m.save(a.RUN/'source-availability-001.json',dict(at=m.now(),new_source_access_holds=[],previous_source_availability_reference=cp['source_availability_reference'],previous_source_hold_reference=cp['new_source_access_hold_reference'],native_object_reference=a.reference(a.RUN/'native-objects-001.json'),native_overview_reference=a.reference(a.RUN/'native-selected-001.json'),kidner_reference=a.reference(a.RUN/'kidner-selected-native-001.json'),policy='Southampton exact catalogue pages and Culture Edinburgh collection pages accessible. Six selected exact object pages captured,including two held conflicts. Official Southampton leaflet and Gulbenkian object plus artist-estate gallery distinguish Kidner versions. ArtUK and every earlier denial/timeout hold remain unchanged. No images downloaded.'))
 decisions=m.load(a.REVIEW)['decisions'];held=[v for v in decisions if v['state']=='editorial_hold'];assert len(held)==7
 m.save(a.RUN/'remaining-research-001.json.gz',dict(at=m.now(),rows=held,unknown_date_artwork_ids=[v['existing_artwork_id'] for v in decisions if v['state']=='approved_existing_holding' and v['facts']['date_precision']=='unknown'],review_reference=a.reference(a.REVIEW),previous_remaining_research_reference=cp['remaining_research_reference'],source_availability_reference=a.reference(a.RUN/'source-availability-001.json'),policy='Three Howard triptych panels share one inventory; Wells accession56/2006 versus native2006/57; Bigge unresolved1933 CSV version and source width conflict; Barker attribution; Gore close versions.104 accepted unknown dates still need creation evidence and do not count as date eligible. All previous queues persist.'))
 oldq=m.load(a.checked(cp['next_museum_pass_reference']));live=m.load(m.RUN/'after-wave-87.json');by={v['id']:v for v in live['institutions']};italian=[dict(v,current_linked=by[v['institution_id']]['works'],current_eligible=by[v['institution_id']]['eligible_works']) for v in oldq['italian_museums']];assert len(italian)==225
 context=m.load(a.RUN/'native-selected-001.json');cards=[]
 for row in context['rows']:
  if '/collection/' not in row['url']:continue
  for link in row['parsed']['links']:
   if '/object/' in link['href'] and link['text'] and not any(v['url']==link['href'] for v in cards):cards.append(dict(title=link['text'],url=link['href'],index_url=row['url']))
 assert len(cards)==38
 remaining=sorted((v for v in live['institutions'] if v['kind']=='museum' and v['status']!='archived' and not v['canonical_institution_id'] and v['works']<100 and v['pending_associations']>0 and v['id'] not in a.IIDS),key=lambda v:(-v['pending_associations'],v['name']))
 m.save(a.RUN/'next-museum-pass-001.json',dict(at=m.now(),previous_queue_reference=cp['next_museum_pass_reference'],italian_museums=italian,existing_holding_review_targets=remaining[:8],native_addition_targets=[by[k] for k in a.IIDS]+[by['03058adb-4b2a-5a45-849d-2393f4229f9b']],current_museums=[by[k] for k in a.IIDS],southampton_selected_cards=cards,edinburgh_portrait_leads=[dict(title='Katherine Hall of Dunglass',creator='Allan Ramsay',source_date='c.1736'),dict(title='Lady with Japanese Screen and Goldfish',creator='James Cadenhead',source_date='1886'),dict(title='The Black Hat',creator='Francis Campbell Boileau Cadell',source_date='1914')],additional_source_references=[a.reference(a.RUN/'native-probes-001.json'),a.reference(a.RUN/'native-selected-001.json')],remaining_research_reference=a.reference(a.RUN/'remaining-research-001.json.gz'),source_availability_reference=a.reference(a.RUN/'source-availability-001.json'),policy='Prioritize selected eligible native additions from38 observed Southampton cards,Edinburgh portrait collection evidence and Southampton Assembly article. Check existing/new physical identities first; six native Southampton cards were reviewed here,four linked and two held. Percy Delf Smith1919 print-series chronology does not date a specific impression; source versions needed. Acquisition/life/event years do not establish creation. Southampton101linked/53eligible and Edinburgh88linked/29eligible still need eligible dated objects toward100/200. Preserve225 Italian museums,Guildhall17 held,Ferens,RWA and all earlier queues. Current source leads are not approved additions. Goal active.',database_writes=0))
 text=f'''# Southampton and Edinburgh holdings — 9 October 2026

Linked **184 existing review artworks** to their documented collections.

| Museum | Links added | Linked records before → after | Eligible dates before → after |
| --- | ---: | ---: | ---: |
| Southampton City Art Gallery | 96 | 5 → 101 | 2 → 53 |
| Edinburgh City Art Centre | 88 | 0 → 88 | 0 → 29 |

**104 newly linked records retain unknown creation dates.** They count as catalogue items but not as dated pre1971 works. Both museums still need eligible additions toward 100 and preferably 200. Southampton crossing 100 linked records does not resolve physical-object deduplication or creation-date gaps.

Of 191 selected objects, [seven remain held](remaining-research-001.json.gz): three Ian Howard triptych panels sharing CAC1985/25; John Wells *Air, Water, Stone* with source 56/2006 versus native 2006/57; a John Selby-Bigge *Composition* with unresolved CSV-version and measurement conflicts; Joseph Barker attribution; and close Frederick Gore versions. Nothing was merged, redated or deleted.

Four accepted Southampton works have exact museum object-page corroboration: [Good Shooting](https://southamptoncityartgallery.com/object/sotag-197748/), [Untitled](https://southamptoncityartgallery.com/object/sotag-198216/), [Time for Tea](https://southamptoncityartgallery.com/object/sotag-20023/) and [The Hermit Discovered](https://southamptoncityartgallery.com/object/sotag-20024/). Kidner’s [official collection leaflet](https://www.southamptoncityartgallery.com/wp-content/uploads/2020/10/Shadows-and-Light-leaflet-pages.pdf) and [estate-gallery article](https://www.flowersgallery.com/news/889-michael-kidner-featured-in-shadows-and-light/) explicitly support Southampton’s *Brown, Blue and Violet No.2*. The [Gulbenkian work with the same title](https://gulbenkian.pt/cam/en/works/brown-blue-and-violet-no-2/) has a different medium and format. The Southampton date remains unknown.

The other 179 accepted links use exact retained Wikidata object statements with museum-scoped inventory, creator identity and referenced ArtUK evidence. These are correlated secondary sources; ArtUK was not fetched and general museum pages do not prove individual holdings. Editorial confidence is 0.8 for these 179, 0.9 for four exact native objects, and 0.85 for Kidner’s collection corroboration. These judgments are not calibrated probabilities.

Physical evidence distinguishes Andrew Williams’s large finished canvas from its small paper study, Florence Martin student paintings, Larry Wakefield colour compositions and Craxton’s Southampton painting from Tate’s larger *Dark Landscape*. Five existing unlinked creator labels were checked against exact source authorities; the modern Allan Ramsay was not assigned to the eighteenth-century painter. Historical HH registrations remain intact, and City Art Centre collection holdings do not assert present building, legal ownership or current display.

[Reviewed plan](britain-eight-existing-holdings-001-plan-001.json.gz) and [transaction receipt](britain-eight-existing-holdings-001-applied.json): 184 holding citations and 184 accepted assertions, with 184 prior pending claims superseded. All {verified['protected_existing_records']:,} scoped existing records and 12,714 prior campaign objects were protected. **31 offline tests, atomic readback and zero-write replay passed.** No new artwork records, images, painter links, metadata edits, publication or display claims were made in this wave.

Campaign total: **10,417 new artworks + 2,481 reconciled existing artworks = 12,898 distinct records across 230 institutions**. The audit retains **{report['after']['museums_below_100']:,} museums below 100 linked records** and **{report['after']['museums_below_200']:,} below 200**. [Next work](next-museum-pass-001.json) retains all earlier queues, 38 Southampton cards and selected Edinburgh portrait leads. The all-museum goal remains unfinished.
'''
 m.save(backup,dict(at=m.now(),path=str(root),text=root.read_text(),sha256=sha(root)));(a.RUN/'README.md').write_text(text)
 old=root.read_text();intro,rest=old.split('## Added works',1);intro=intro.replace('2,297','2,481').replace('expand 228 institutions','expand 230 institutions').replace('1,234',f"{report['after']['museums_below_100']:,}").replace('after-wave-86','after-wave-87').replace('Salford and Guildhall passes','Salford, Guildhall, Southampton and Edinburgh passes');root.write_text(intro+'## Added works'+rest+'\n\n## Southampton and Edinburgh holdings — wave87\n\nLinked 184 existing review artworks: 96 Southampton and 88 Edinburgh City Art Centre. Totals 101 and 88 linked records, 53 and 29 eligible dates. 104 unknown dates remain unchanged; seven candidates held. [Evidence and limits](native/britain-eight-holdings-20261009/README.md). Campaign 10,417 new + 2,481 reconciled = 12,898 distinct records across 230 institutions. The all-museum 100–200 goal remains unfinished.\n')
 m.save(a.RUN/'readme-supersessions-001.json',dict(at=m.now(),changes=[dict(path=str(root.relative_to(m.ROOT)),before_sha256=pin['sha256'],after_sha256=sha(root),backup_path=str(backup),backup_sha256=sha(backup))]));print(json.dumps(dict(documented_new_records=0,documented_existing_links=184,held=7,tests=31,goal_complete=False)),flush=True)
if __name__=='__main__':main()
