"""Wave109 evidence checkpoint; every-museum objective remains active."""
import hashlib,importlib.util,json
from pathlib import Path
z=importlib.util.spec_from_file_location('a',Path(__file__).with_name('museum-expansion-rhodes-apply-20261009.py'));a=importlib.util.module_from_spec(z);z.loader.exec_module(a);m=a.m;RUN=a.RUN
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 dest=RUN/'delivery-checkpoint-001.json';assert not dest.exists();report=m.load(RUN/'delivery-001.json');assert report['added']==86 and report['local_unchanged'];p,digest=a.validate_plan();prior=m.load(a.CHECKPOINT);checks=m.load(RUN/'checks-001.json');assert checks['replay_zero_writes']and checks['offline_tests_passed']==13
 root=m.RUN/'README.md';old=root.read_text();before=sha(root);oldpin=next(v for v in prior['artifacts']if v['path']==str(root.relative_to(m.ROOT)));assert oldpin['sha256']==before
 backup=m.BACKUP/'rhodes-root-readme-before-001.json';m.save(backup,dict(at=m.now(),text=old,sha256=before));title,body=old.split('\n\n',1)
 prefix='''The latest continuation added **86 production review artworks to the Municipal Art Gallery of Rhodes / Museum of Modern Greek Art**, taking it from **21 to107 catalogue works** and from **15 to101 date-eligible works**. Both now meet the100-work minimum; continue toward200. [Delivery and source decisions](native/rhodes-20261009/README.md). The selected production phase totals **712 additions across six museums**. The real local catalogue remains read-only. The full all-museum objective remains active.

'''
 root.write_text(title+'\n\n'+prefix+body.replace('The latest continuation added','The preceding continuation added',1));change=dict(path=str(root.relative_to(m.ROOT)),before_sha256=before,after_sha256=sha(root),backup_path=str(backup),backup_sha256=sha(backup));m.save(RUN/'readme-supersessions-001.json',dict(at=m.now(),changes=[change]))
 pins={v['path']:v for v in prior['artifacts']if v['path']!=change['path']};paths={root,a.CHECKPOINT,Path(__file__).resolve()}|{v for v in RUN.rglob('*')if v.is_file()}|{v for v in(m.ROOT/'ops').glob('*rhodes*20261009.py')}|{m.ROOT/v['path']for v in p['evidence']}
 for path in sorted(paths):
  ref=a.reference(path);assert ref['path']not in pins or pins[ref['path']]==ref;pins[ref['path']]=ref
 external={v['path']:v for v in prior['external_artifacts']}
 for path in sorted(m.BACKUP.glob('rhodes-*.json*')):external[str(path)]=dict(path=str(path),sha256=sha(path))
 for path in sorted((Path.home()/'Library/Application Support/Artline/research-proofs/rhodes-20261009').glob('*')):
  if path.is_file():external[str(path)]=dict(path=str(path),sha256=sha(path))
 next_work='''Wave109 verified progress:86new production review works in Rhodes,21to107catalogue/15to101dateeligible. Both100minimums reached;93catalogue/99eligible short of200. Selected productionphase712new across6museums; historical local totals remain separate. Real localRhodes3/1unchanged. Fullgoalactive, notcomplete/blocked.
Continue Rhodes toward200. Reuse60indexleads numbers120–179 from pages6–8 captured in next-source-discovery-001.json.gz; no individual details/images fetched for these leads. Then bounded metadata selection from page9,size20, parent37532a1a-6753-4111-8b0b-434cb8131deb, public API https://repox.mgamuseum.gr/api/public/containers/{parent}/children . Official frontend calls /v2/public/containers/{uuid}. Use captured frontend configuration through rhodes-source helper; do not print authorization or irrelevant administrative identities. Created/updated/onlineAt are repository dates, not artwork dates.120ofreported1502objects classified;1382unexamined, no exhaustivefetch. Current publicsourceavailable; inheritedproviderholds persist. Next source script should use newrun rhodes-more-20261009, not mutate these pins.
Institution f02b4c48-dd69-5319-8d22-e0de34436933, oldnameMunicipalArtGallery ofRhodes, iscollection-levelMuseumModernGreekArt accordingofficialhistory. AndreasIoannou gallery,OldSyssitio,NestorideionandNewWing arevenues; no building/display claims. Museumoverview1832start doesnotexcludeindividuallydocumented earlierprint holdings.
Review120states86added/4existing/9holds/18unknown-dateleads/3post1970excluded. SourceIDs/numbers preserved in ledger. Holds26Mallet4091repeat4043;37combinedharbour4056contains4030;67Clouet4086date1767vs1776–1793;70MalletColossus4089repeat4036;73Mayer4095repeat4082;76Graecia4097circa1650vsAtlas1662–65;84LeBrun4104possiblepanoramaboundary;105queue4126date1950vs4124date1946;115Demonstration4136linocutvs4135. Existing22Hogenberg4018/30Porro4050/41Chronicle4060/68anonymous4087skippedbyexactSearchCultureUUID. Unknowns12,28,36,87–95,97–102retained; post1970n1Luna1993/n4Flowers1971/n119StFrancis2010excluded. Use exact ledger.
Datesn13,14,15,19,20,23retainMallet1683/1685vs1783/1785sourceconflicts asboundedintervals; German1686prints explicitn16,18,21,24remain1686. n32Porro4052probably1620differentexisting1576impression;n77probably1584Ortelius;n81probably1640–1643Blaeu;n78plate1752vs1757editionrange;n75publication1841–42;n86catalogue1841vsnarrative1837range. n74ink-marker5037isnormalizeddrawing. Tarsouli4063–65creditGrammatopoulos lithographicexecution. Historicalprint copies distinguished fromTurnerYaleoriginal,oldermodels,books,ancientdepictionsandcreatordeathyears. Semertzidis4138flute1948differs revisedreversed4139flute1950;study4140separate. BigDemonstration4137etchingdifferentfromsmalllinocut4135. LeBrun4070easternviewtowerleft and4105westernviewtowerright distinct;4104held. Panorama4078–80separate lithographicplates, no fullparentadded. Composite4083oneartworknotthreeviews.
Identity query initialbroadfirstnames exceeded20000cap; secondILIKEANY120stimeout; correctedregex1197unlinkedrows7.906s. Capturedplans/timings not10millionperformanceproof. Identity001emptytitlebugproducedfalsepositives; authoritative002recomputes115hits, noSQLrefresh/noearlierwrite. Snapshot4097works/9196citations,73focusedcomparators.86existingfullrows and626prioradditionsprotectedunchanged.13offlinetests,successfulCloudbackup,atomicreadback andzerowritereplaydone. Noimages/artistlinks/publication/displaychanges/merges/existingmetadataedits. OnlyRhodesregisterrowrefreshed; othersretaindates. Under100priorityqueuenow233, nextNikosKazantzakisMuseumbutcontinueRhodes200first. Literarydocumentsnotautomaticallyartworks. Allothermuseumsremaininregister. Inheritwave101fullhistoryproof; validateonlynew/supersededpins.'''
 result=dict(prior);result.update(at=m.now(),goal_complete=False,previous_goal_turn='progress',production_only=True,local_unchanged=True,new_additions=86,new_existing_links=0,verification=report['verification'],production_museum_before=report['museum_before'],production_museum_after=report['museum_after'],production_campaign_totals=dict(new_artworks=712,existing_links=0,museums=6),global_production_counts_refreshed=False,global_production_thresholds_refreshed=False,new_tests_passed=13,plan_sha256=digest,artifacts=list(pins.values()),external_artifacts=list(external.values()),prior_checkpoint_reference=a.reference(a.CHECKPOINT),baseline_reference=a.reference(RUN/'baseline-verification-001.json'),intentional_supersessions=[change],review_reference=a.reference(a.REVIEW),remaining_research_reference=a.reference(RUN/'all-source-decisions-001.csv'),production_institution_register_reference=a.reference(RUN/'production-institution-register-001.json.gz'),priority_museum_queue_reference=a.reference(RUN/'priority-museum-queue-001.json'),global_threshold_summary_note='Inherited wave104 global snapshots. Rhodes refreshed107/101 only; all other observations retain timestamps.',source_availability=report['source_access'],next_work=next_work)
 m.save(dest,result);oldpins={v['path']:v for v in prior['artifacts']};oldext={v['path']:v for v in prior['external_artifacts']};newpins=[v for v in result['artifacts']if oldpins.get(v['path'])!=v];newext=[v for v in result['external_artifacts']if oldext.get(v['path'])!=v]
 for v in newpins:a.checked(v)
 for v in newext:assert sha(Path(v['path']))==v['sha256']
 m.save(RUN/'final-checkpoint-verification-001.json',dict(at=m.now(),checkpoint=a.reference(dest),verified_new_or_superseded_artifact_pins=len(newpins),verified_new_external_pins=len(newext),inherited_unchanged_artifact_pins=len(result['artifacts'])-len(newpins),inherited_unchanged_external_pins=len(result['external_artifacts'])-len(newext),full_historical_proof=prior['initial_full_historical_verification_reference'],plan_sha256=digest,goal_complete=False));print(json.dumps(dict(checkpoint=a.reference(dest),artifacts=len(pins),external_artifacts=len(external),verified_new=len(newpins),verified_external=len(newext))),flush=True)
if __name__=='__main__':main()
