"""Reconcile exact museum identities and custody vocabulary; no display or title inference."""
import gzip,hashlib,importlib.util,json
from pathlib import Path
s=importlib.util.spec_from_file_location('d',Path(__file__).with_name('museum-expansion-france-fifteenth-discovery-20261008.py'));d=importlib.util.module_from_spec(s);s.loader.exec_module(d)
m=d.m;RUN=d.RUN;ref=d.prior.reference
AVELINES="musée des Avelines - musée d'art et d'histoire de Saint-Cloud"
RENAISSANCE='musée national de la Renaissance'
CONTEXTS={
 'M0231':dict(source='esteve',city='Bourges',names=['musée Estève'],locations=[''],mode='municipal_owner',owner_prefixes=['propriete de la commune'],owners=['Bourges;musée Estève'],basis='Exact museum code M0231, official name and city together with explicit Bourges municipal ownership naming musée Estève establish this collection. Museofile documents the artist donation and municipal museum. The source location field is blank and stays unknown; no physical gallery or display is inferred.'),
 'M0416':dict(source='avelines',city='Saint-Cloud',names=[AVELINES],locations=[AVELINES,'Saint-Cloud ; '+AVELINES,'Saint-Cloud ; musée des Avelines'],mode='municipal_owner',owner_prefixes=['propriete de la commune','propriete publique propriete de la commune'],owners=[AVELINES,'Saint-Cloud;musée des Avelines','musée des Avelines'],basis='Exact M0416, city, complete official museum identity and named collection location agree with Museofile. The museum combines municipal history and Charles Oulmont foundation collections; only explicit municipal owner labels in this selection support holding. Other private ownership and external deposits remain unresolved. Source wording is unchanged.'),
 'M0745':dict(source='dobree',city='Nantes',names=['musée Dobrée'],locations=['Nantes ; musée Dobrée','Nantes ; musée départemental Dobrée'],mode='department_owner',owner_prefixes=['propriete du departement'],owners=['Loire-Atlantique;musée Dobrée','Nantes;musée Dobrée'],basis='Exact M0745, Nantes and musée Dobrée identify the departmental collection described by Museofile. The two location labels identify this same institution. Unqualified departmental ownership labels support the collection association; questioned ownership, deposits and missing-object flags remain held.'),
 'M5012':dict(source='renaissance',city='Ecouen',names=["musée de la Renaissance - château d'Ecouen"],locations=['Ecouen ; '+RENAISSANCE,"Ecouen ; musée de la Renaissance - château d'Ecouen",'affecté ; Ecouen ; '+RENAISSANCE],mode='state_assignment',accepted_deposit_labels=['','affectation;'+RENAISSANCE,'affectation;Ecouen;'+RENAISSANCE,'affecté;Ecouen;'+RENAISSANCE,'dépôt;Ecouen;'+RENAISSANCE,'dépôt;'+RENAISSANCE,'affectation;Musée de Cluny;affectation;Ecouen;'+RENAISSANCE,'affectation;Musée de Cluny;affecté;Ecouen;'+RENAISSANCE,'affectation;musée de Cluny;dépôt;Ecouen;'+RENAISSANCE,'dépôt;musée de Cluny;affecté;Ecouen;'+RENAISSANCE],basis='Exact M5012, official museum name, Ecouen city and Renaissance collection location identify the receiving institution. Museofile explicitly documents collections originating at Cluny. Exact source assignment/deposit chains ending at musée national de la Renaissance support holding while state ownership, Cluny and Louvre collection provenance remain literal and distinct. A Cluny-only deposit field is not accepted. Neither legal ownership transfer nor current physical display is inferred.'),
 'M1107':dict(source='cognacq-jay',city='Paris',names=['musée Cognacq-Jay, musée du XVIIIe siècle de la ville de Paris'],locations=['Musée Cognacq-Jay, le goût du XVIIIe'],mode='named_collection',accepted_acquisition_labels=['','legs','achat en vente publique',"mode d'acquisition inconnu",'don manuel','achat après commande','achat par préemption en vente publique'],basis='Exact M1107, official Cognacq-Jay identity and Paris city reconcile the catalogue collection label Musée Cognacq-Jay, le goût du XVIIIe. Museofile documents the Cognacq legacy to the City of Paris and the same museum collection. Acquisition-only and blank item legal fields remain unchanged and do not establish individual legal title. Qualified creators and multiple attributions need object-level native review.')
}
def main():
 dest=RUN/'museum-name-reconciliation-001.json';assert not dest.exists()
 targets={v['slug'].removeprefix('joconde-').upper():v for v in m.load(d.DISCOVERY)['targets']};out={}
 for code,c in CONTEXTS.items():
  stem=RUN/'museum-context-001'/(c['source']+'-museofile');text=stem.with_suffix('.txt').read_text();receipt=m.load(stem.with_suffix('.receipt.json'))
  assert receipt['status']==200 and hashlib.sha256(gzip.decompress(stem.with_suffix('.html.gz').read_bytes())).hexdigest()==receipt['sha256']
  assert code in text and m.norm(c['city']) in m.norm(text) and all(m.norm(v) in m.norm(text) for v in c['names'])
  if code=='M5012':assert 'cluny' in m.norm(text)
  out[code]=dict(c,institution_id=targets[code]['id'],evidence=[ref(stem.with_suffix(ext)) for ext in ['.txt','.html.gz','.receipt.json']],legal_title_claim=False,current_display_claim=False)
 m.save(dest,dict(at=m.now(),museums=out,discovery_reference=ref(d.DISCOVERY),reviewer_reference=ref(Path(__file__).resolve()),policy='Museum-level source reconciliation only. Each selected object still needs current metadata, date, attribution, custody, physical-unit and duplicate review. Original source fields remain literal; no publication or image changes.'))
 print(json.dumps({code:dict(name=targets[code]['name'],mode=c['mode']) for code,c in out.items()},ensure_ascii=False),flush=True)
if __name__=='__main__':main()
