"""Document York's verified additions and preserve every earlier museum queue."""
import csv,gzip,hashlib,importlib.util,json
from pathlib import Path
z=importlib.util.spec_from_file_location('a',Path(__file__).with_name('museum-expansion-york-additions-apply-20261009.py'));a=importlib.util.module_from_spec(z);z.loader.exec_module(a);m=a.m;RUN=a.RUN;ref=a.reference;sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 report=m.load(m.RUN/'verification-after-wave-96.json');assert(report['verified_new_artworks'],report['verified_existing_artworks_linked'])==(10783,3035);cp=m.load(a.CHECKPOINT);applied=m.load(RUN/(a.KEY+'-applied.json'));assert applied['created']==160 and applied['existing_links']==0 and applied['verification']==report['york_native_paintings'];root=m.RUN/'README.md';pin=next(v for v in cp['artifacts'] if v['path']==str(root.relative_to(m.ROOT)));assert sha(root)==pin['sha256'];backup=m.BACKUP/'york-additions-root-readme-before-001.json.gz';assert not backup.exists()
 for name in ['checks-001.json','remaining-research-001.json.gz','next-museum-pass-001.json','README.md','readme-supersessions-001.json','source-availability-001.json','new-source-access-holds-001.json']:assert not(RUN/name).exists()
 logsroot=Path('/Users/vadimdulub/Library/Logs');test=(logsroot/'artline-york-additions-tests-20261009.log').read_text();assert 'Ran 30 tests' in test and test.rstrip().endswith('OK');assert(logsroot/'artline-york-additions-replay-20261009.log').read_text().strip()=='Unchanged replay: zero writes';logs={v.name:dict(path=str(v),sha256=sha(v)) for v in sorted(logsroot.glob('artline-york-additions-*-20261009.log')) if not any(x in v.name for x in ['delivery','checkpoint'])};ctx=m.load(RUN/'comparison-source-context-001.json.gz');identity=m.load(RUN/'identity-001.json.gz');citations=m.load(RUN/'identity-citations-001.json.gz');decisions=m.load(a.REVIEW)['decisions'];caps=[]
 for path in sorted((RUN/'york/captures').glob('*.json')):
  rc=m.load(path);body=path.with_suffix('.body.gz');raw=gzip.decompress(body.read_bytes());assert rc['status']==200 and hashlib.sha256(raw).hexdigest()==rc['sha256'];caps.append(dict(receipt_reference=ref(path),body_reference=ref(body),url=rc['url']))
 assert len(caps)==191;assert len(ctx['body_references'])==932 and len(ctx['unreconstructed_bodies'])==579
 m.save(RUN/'checks-001.json',dict(at=m.now(),new_offline_tests_passed=30,historical_tests_passed=1900,cumulative_verified_tests=1930,historical_tests_rerun=False,replay_zero_writes=True,source_objects_reviewed=177,new_artworks=160,existing_links=0,preserved_existing_gallery_holdings=90,editorial_holds=17,identity_artworks=len(identity['state']['artworks']),identity_citations=len(citations['citations']),successful_native_html_captures=191,reused_prior_index_captures=1,comparison_raw_bodies=932,comparison_unreconstructed_citations=579,logs=logs,other_job_totals_separate=True,source_refinements='Two sitter-conflict titles qualified,source maker relationships retained unresolved,month dates preserved.17holds include16version/identity comparisons and1conflicting production-date page.13already-linked index objects excluded. Triptych,joined panels and paired sides count once; separately accessioned saint roundels count individually.'))
 attempt=m.load(RUN/'comparison-native-extra-attempt-001.json');assert attempt['status']==403;newholds=[dict(provider='www.nga.gov',status=403,scope='Selected NGA496 primary webpage metadata request',evidence_reference=ref(RUN/'comparison-native-extra-attempt-001.json'),policy='Stopped after refusal; no alternate path,search-tool fetch or retry after403.')];m.save(RUN/'new-source-access-holds-001.json',dict(at=m.now(),rows=newholds,previous_source_hold_reference=cp['new_source_access_hold_reference']))
 m.save(RUN/'source-availability-001.json',dict(at=m.now(),new_source_access_holds=newholds,new_source_access_hold_reference=ref(RUN/'new-source-access-holds-001.json'),previous_source_availability_reference=cp['source_availability_reference'],previous_source_hold_reference=cp['new_source_access_hold_reference'],native_captures=caps,discovery_references=[ref(RUN/'native-index-001.json.gz'),ref(RUN/'date-band-index-001.json.gz')],failed_selected_requests=[attempt],comparison_context_reference=ref(RUN/'comparison-source-context-001.json.gz'),policy='191fresh successful York HTML captures:177selected objects,13bounded date-band first pages and1repeating next-page response. One earlier index capture reused. Repeated native pagination stopped; no guessed pagination endpoint. Date-band parser flagged valid month forms1943-08/1933-08; literal object parser supports these, final1950-1970band remained unrequested. These two discovery limitations are not access refusals. NGA403 stopped,all prior provider holds persist. No image/PDF downloads or attachments.'))
 held=[v for v in decisions if v['state']!='approved_review_only_addition'];assert len(held)==17;oldq=m.load(a.checked(cp['next_museum_pass_reference']));live=m.load(m.RUN/'after-wave-96.json');by={v['id']:v for v in live['institutions']};museum=by[a.IID];assert(museum['works'],museum['eligible_works'])==(250,228)
 m.save(RUN/'remaining-research-001.json.gz',dict(at=m.now(),rows=held,review_reference=ref(a.REVIEW),previous_remaining_research_reference=cp['remaining_research_reference'],gallery_linked=250,gallery_eligible=228,current_museums=[museum],remaining_to_100_linked=0,remaining_to_200_linked=0,remaining_to_200_eligible=0,policy='York meets200 linked and eligible; stop selected additions here rather than exhaust1099painting index.17current holds and all17previous Box/York/Harris holds remain, including prior John Burton duplicate and qualified/date-scope cases. Existing WikiArt Baburen/Herman potential same-object leads require version completion. Keep225Italian museums,Leeds gaps/GAC leads and all historical queues.'))
 italian=[dict(v,current_linked=by[v['institution_id']]['works'],current_eligible=by[v['institution_id']]['eligible_works']) for v in oldq['italian_museums']];assert len(italian)==225;harris='30bd4651-027d-5454-83b9-d74459aa632b';box='6bf81770-e092-5332-95f8-09d4c0b3c96b';native_ids=list(dict.fromkeys([harris,box]+[v['id'] for v in oldq['native_addition_targets'] if v['id']!=a.IID]));queue=dict(oldq);queue.update(at=m.now(),previous_queue_reference=cp['next_museum_pass_reference'],italian_museums=italian,native_addition_targets=[by[iid] for iid in native_ids],current_museums=[by[v['id']] for v in oldq['current_museums']],current_pass_museums=[museum],completed_target_this_wave=museum,remaining_research_reference=ref(RUN/'remaining-research-001.json.gz'),source_availability_reference=ref(RUN/'source-availability-001.json'),policy='York250linked/228eligible meets200. Prioritize Harris83/72 and TheBox75/30 supported native additions,then next under100 pending targets. Keep every earlier institution,225Italian museum queue and source/identity hold. No exhaustive index or image downloads; full all-museum goal active.',queue_database_writes=0);queue.pop('database_writes',None);m.save(RUN/'next-museum-pass-001.json',queue)
 verified=applied['verification'];assert verified['protected_existing_records']==2612 and verified['prior_campaign_records_preserved']==13658
 text=f'''# York Art Gallery additions — 9 October 2026

Added **160 selected paintings in review** from the [York Museums Trust native collection](https://www.yorkmuseumstrust.org.uk/collections/). York now has **250 linked artworks and 228 with eligible pre-1971 dates**, up from 90 and 68. This completes the 200-work target for this museum in both measures.

Reviewed 177 selected object pages after excluding 13 already-linked index items. **17 remain held**: 16 unresolved identity/version comparisons and one Blanche page with conflicting 1903/1913 production dates. Likely WikiArt matches for Baburen’s *Roman Charity* and Herman’s *Digging for Roots* were retained for version checks; no duplicate records or unsupported museum links were created. [All decisions and source evidence](editorial-reviewed-001.json.gz) remain available.

Anonymous and qualified makers remain explicit. Multiple source creator labels remain unresolved rather than being interpreted as joint authorship. Two Etty copies after Lawrence now use neutral study titles because the source’s alternative sitter names conflict; the original names remain in citations. Source dates `1943-08` and `1933-08` retain their month information. One triptych, ten joined panels and paintings with reverse studies each count as one accessioned object. Two separately accessioned saint roundels count separately.

**30 offline checks, atomic database readback and zero-write replay passed.** The transaction rechecked 26,380 candidate catalogue rows and 54,896 citations, protected 2,612 comparison/gallery records and all 13,658 earlier campaign records. Existing metadata, images, painter links and publication states were preserved. No images or current-display claims were added.

Captured 191 successful York HTML responses: 177 objects, 13 bounded date-band searches and one repeating next-page response. Reused one earlier index page. Pagination repeated the first page, so it was stopped. A conservative index parser flagged valid month dates; object-level verification resolved those two dates. These are discovery limitations, not source refusals. A selected NGA page returned 403 and was not retried. The retained comparison archive contains 932 raw bodies; 579 citation bodies could not be reconstructed and are not claimed as fresh confirmation.

Campaign totals: **10,783 new artworks + 3,035 reconciled existing artworks = 13,818 distinct records across 239 institutions**. **{report['after']['museums_below_100']:,} canonical museum entries remain below 100 linked works** and **{report['after']['museums_below_200']:,} below 200**. The full goal remains active. Next: Harris Museum (83 linked / 72 eligible) and The Box (75 / 30). [The continuing queue](next-museum-pass-001.json) preserves every prior institution, unresolved object and provider hold.
'''
 m.save(backup,dict(at=m.now(),path=str(root),text=root.read_text(),sha256=sha(root)));(RUN/'README.md').write_text(text);old=root.read_text();intro,rest=old.split('## Added works',1);intro=intro.replace('10,623','10,783').replace('13,658','13,818').replace('1,230','1,229').replace('after-wave-95','after-wave-96').replace('Imperial War Museums Leeds Art Gallery','Imperial War Museums, Leeds Art Gallery');table='| Distinct new-record campaign total | **10,472** | **215 collections** |';assert table in rest;rest=rest.replace(table,'| Leeds Art Gallery — selected native additions and Cotmania drawings | 151 | 1 museum |\n| York Art Gallery — selected native paintings | 160 | 1 museum |\n| Distinct new-record campaign total | **10,783** | **217 collections** |',1);root.write_text(intro+'## Added works'+rest+'\n\n## York Art Gallery additions — wave96\n\nAdded 160 selected native paintings in review. York is now at 250 linked artworks, including 228 with eligible creation dates, exceeding 200 in both measures. Seventeen source/identity holds remain; original maker qualifications, month dates and conflicting sitter labels are explicit. Thirty offline checks, atomic readback and zero-write replay passed. All 2,612 comparison/gallery records and 13,658 earlier campaign records were preserved. [Evidence and next museums](native/york-additions-20261009/README.md). Campaign total: 10,783 new + 3,035 reconciled = 13,818 distinct artworks across 239 institutions. Next: Harris (83 linked / 72 eligible) and The Box (75 / 30). All prior queues/source holds remain; full goal active.\n');m.save(RUN/'readme-supersessions-001.json',dict(at=m.now(),changes=[dict(path=str(root.relative_to(m.ROOT)),before_sha256=pin['sha256'],after_sha256=sha(root),backup_path=str(backup),backup_sha256=sha(backup))]));print(json.dumps(dict(documented_new_records=160,documented_existing_links=0,held=17,tests=30,institutions_expanded=239,goal_complete=False)),flush=True)
if __name__=='__main__':main()
