"""Explicit editorial decisions for the 201 Salford/Guildhall existing objects."""
HOLDS = {
 3:'Explicit verso,1947-215A: identify the other side and physical-support grouping before another museum count.',
 13:'VE Day fiftieth-anniversary subject implies a post1970 event. Creation is unknown; do not invent a date or accept as a pre1971 selection.',
 17:'Source creation range1819–1906 duplicates Fitzgerald life dates; its central1862 value has millennium precision. Hold for real object-date evidence; preserve catalogue unchanged.',
 22:'Adrian Oscar Abstraction1947-217,61x46cm,versus Abstract1950/2/30,47.8x63.3cm: transposed dimensions could overlap after measurement differences. Different accession alone does not resolve physical identity.',
 26:'Undated portrait of Recorder James Miskin requires object-date review for this pre1971 pass; sitter life years are not creation dates.',
 42:'Source image filename says attributed to Charles Martin,while existing creator is unqualified. Preserve and hold attribution discrepancy.',
 49:'Explicit verso Abstract1946-19A shares50x61cm support with recto Bricks at Night1946-19(number85). Hold both until physical-object grouping is resolved.',
 53:'Janet Kirk Tulips1952-49,49.5x61cm,versus BOLMG:2005.4.12,44x55cm: generic same-maker title and close dimensions do not conclusively exclude transfer/framing differences.',
 66:'Explicit Holroyd copy after Cope609,c1895,127x94cm,versus Balliol118,1897,124.5x91.4cm. Keep after qualifier; close dimensions and related copy identity need stronger version evidence.',
 69:'Source filename explicitly says after Francis Parsons,while existing maker is unqualified. Other Brindley versions include NPG6170 and1954.FA.186; do not collapse copies into original.',
 77:'Source filename says attributed to John Bettes. Existing unqualified creator must not be strengthened by a holding-only operation.',
 85:'Explicit recto Bricks at Night1946-19 shares50x61cm support with verso Abstract1946-19A(number49). Hold paired sides for grouping.',
 102:'KH0087 a belongs to an unresolved Keats House versus Guildhall administrative mapping. Fanny portrait by Brockmann1890 is distinct from the Llanos1880 lead; preserve both historical pending assertions on this one object.',
 103:'Witherop Polperro1953-2,1948,59.5x75cm,versus WalkerWAG10433,1949,67x79cm. Close dimensions and one-year date difference require stronger physical-version evidence.',
 107:'KH0146: Keats House branch/collection mapping remains unresolved. Do not count City of London administration as exact Guildhall holding.',
 126:'800th Mayoralty-anniversary subject raises a post1970 event/date conflict. No object creation date is supplied; preserve and hold.',
 127:'KH0316: Keats House branch/collection mapping remains unresolved. Do not count City of London administration as exact Guildhall holding.',
 138:'Undated portrait of Illtyd Harrington in a Greater London Council deputy-chair role requires object-date review for this pre1971 pass; no creation year inferred.',
 139:'KH0421: Keats House branch/collection mapping remains unresolved; explicit after Murillo copy must remain distinct from Murillo originals.',
 158:'Source filename explicitly says after Eugenio Latilla,while existing maker is unqualified. Preserve and hold qualification discrepancy;1838 is inventory,not a creation year.',
 164:'KH0087: official Keats House article identifies an1880 old-age Fanny portrait with its own K/PZ/05/019 accession. Confirm crosswalk and branch before link; do not merge with Brockmann1890KH0087 a.',
 167:'KH0414: Keats House branch/collection mapping remains unresolved. Do not count City of London administration as exact Guildhall holding.',
 182:'Undated portrait of Recorder Michael Hyam needs object-date evidence before this pre1971 selection; no year invented from sitter or artist biography.',
}
NOTES = {
 5:'Ghislaine Howard Evening Interior is not Howard Cook Wood Interior; the token overlap is unrelated creator evidence. Creation remains unknown,not inferred eligible from artist age or accession.',
 2:'No ArtUK identifier property is present,but saved creation,maker,collection and inventory statements all cite the same exact artwork URL ending51017/search/keyword:old-drury-lane-theatre-on-fire. This is a referenced object path,not a generic search result. The denied site was not fetched.',
 7:'School in the title describes the Medburn Street School subject,not an attribution qualification.',
 8:'Returned George Frederic Watts portrait of Mrs Arthur Sassoon is a different maker and sitter from Leonard Watts and Sir Arthur Arnold.',
 9:'Boy Cricketers1947-214 and Girl Cricketers1947-213 are separately named Stockley compositions,with separate accession records. Neither is labelled a side or detail; retained as separate works,not inferred to be one support.',
 11:'Emma Magnus is not Magnus Enckell; shared token produced unrelated portrait hits.',
 12:'Dunington Barton Aqueduct1894MH95-1967,23x33cm,is materially different in size and chronology from1876MH10-1960,96.5x122cm,and1893accession1936.119,51.6x76.5cm. Distinct museum-qualified object records,not a title-only merge.',
 20:'Reckitt House in Catalonia1939-18,61x75cm,has an explicit alternate subject and different dimensions from The Farm1948/7/35,51.4x61.6cm. Keep separate source objects; creation stays unknown.',
 54:'After Thornton Rippingille is already explicit in the title. Maker Samuel Sidley,1862,1868-29,79x61cm describes the copy; no claim that Rippingille painted this object.',
 56:'Girl Cricketers1947-213 and Boy Cricketers1947-214 have separate titled Stockley records and accessions. No recto/verso or component relationship is asserted.',
 60:'Museum-published Google Arts & Culture corroborates the exact procession subject and1789–1792 date and names both Richard Paton and Francis Wheatley,explaining their background/figure contributions. Existing Paton link is preserved; joint credit is evidence,not silently reduced to sole authorship or used to create another object.',
 72:'Museum-published Google Arts & Culture explicitly gives Temptation in the Wilderness,Briton Rivière,1898,Guildhall. Accent/title article variation preserves identity; native object evidence resolves the missing ArtUK-reference issue without visiting the denied site.',
 78:'Returned Francis Coates Jones and George Jones works are not Lucy Jones. Unknown creation is preserved and does not count as eligible.',
 79:'James Burrell Smith Waterfall1890F20-1975 is not an unrelated four-panel screen returned through generic landscape terms.',
 84:'Exact Q20018580 authority supports existing unlinked Charles Collins text. This does not resolve homonymous painter records or authorize a painter link; no artist metadata is changed.',
 86:'Salford A London Street Scene1930,68.5x183cm,1933-46 is distinct from TateN05201 Street Scene1933–9,1829x2146mm support in the retained official dataset. Date and materially different aspect/size resolve returned version lead.',
 87:'Flora Lion is not Léon Bonnat; all returned Bonnat portraits arise from broad creator-term matching.',
 89:'William Collins Pet Lamb is not Cecil Collins The Poet; different makers and subjects.',
 91:'John Francis Rigaud Providence is not Hyacinthe Rigaud LouisXIV. Exact unlinked authority retained; no painter link.',
 95:'Two publisher assets present The Blessed Damozel under Byam Shaw and John Byam Liston Shaw. Dated1895 museum page corroborates the existing object; the second undated presentation is not another physical artwork or independent corroboration.',
 113:'Museum-published page exactly corroborates title,George Percy Jacomb-Hood,1885 and Guildhall. No fresh on-view claim follows from the location label.',
 117:'Egg Winter’s Tale1845accession662 and TateN00444 Devil upon Two Sticks1844 are different named literary scenes. Retained primary comparison confirms the latter title and support; no merge.',
 122:'Edward Frederick Green portrait of a young man is not Mary Green portrait of a young lady. Former sitter identification remains qualified in the existing title.',
 125:'Bale1891F119-1975,61.5x74cm,fruit and pheasants is distinct from1882WakefieldA1.715/A1.716 dead-game panels,about45.7x35.6cm. Separate title,chronology,orientation and accession evidence.',
 129:'Colonel Samuel Wilson and Harvey Christian Combe(number154) are different named Lord Mayors,makers and accession numbers; generic title similarity is not identity.',
 141:'November1966 in the title is a depicted event,not an asserted creation year. Keep creation unknown.',
 144:'After1648 occurs inside Gilbert Jackson’s biographical filename dates,not a copy attribution.1615 remains the explicit object-creation statement.',
 148:'Samuel Scott Pool of London1769 is not David Scott Fire of London1843. Different makers and subjects.',
 154:'Harvey Christian Combe and Colonel Samuel Wilson(number129) are different named sitters with distinct makers and accessions.',
 165:'Dunington1876MH10-1960,96.5x122cm,is materially different from1894MH95-1967,23x33cm,and1893accession1936.119,51.6x76.5cm. Retain distinct dated source objects.',
 176:'Townley Park1962-56 and Lane in Burnley1962-4(number194) are different named scenes with distinct accession records; acquisition-like numbers are not creation dates.',
 186:'Guildhall927 Wounded Cavalier1855,89x104cm,is distinct from TateN03389 Detail of Two Figures1871,support419x305mm in retained primary metadata. The two returned Tate records may themselves be duplicates and remain untouched; this does not make their later physical detail painting the Guildhall original.',
 189:'Henry Turner Munns Sir Thomas Dakin is not Bernard Munns Sir Thomas Beecham; different makers and sitters.',
 193:'Steggles Norfolk Landscape1949-101,22x28cm,and Essex Landscape1931.2,36x45.9cm have different named places,dimensions and accessions. Norfolk creation remains unknown.',
 194:'Lane in Burnley1962-4 and Townley Park1962-56(number176) remain distinct named scenes; no year inferred from accession.',
 201:'All returned other self-portraits name different creators: Grace Cossington Smith,Thomas Smith,Garden Grant Smith,Frank Jameson-Smith,John Raphael Smith,Albert Alexander Smith,Arthur Hall Smith,Moishe Smith and the sourceQ21289269. None is Matthew SmithQ3299800; generic title/surname do not establish identity.',
}
