"""Document wave91 and retain every earlier museum queue and source hold."""
import hashlib,importlib.util,json
from pathlib import Path
z=importlib.util.spec_from_file_location('s',Path(__file__).with_name('museum-expansion-iwm-common-20261009.py'));s=importlib.util.module_from_spec(z);z.loader.exec_module(s);m=s.m;RUN=s.RUN;ref=s.ref;KEY='iwm-existing-holdings-001';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 report=m.load(m.RUN/'verification-after-wave-91.json');assert(report['verified_new_artworks'],report['verified_existing_artworks_linked'])==(10472,2726);assert sha(s.CP)=='d03a57c1b196c1340222c63ce31b8a27cfb38a08790cb6cf616209281fd02956';cp=m.load(s.CP);applied=m.load(RUN/(KEY+'-applied.json'));assert applied['created']==0 and applied['existing_links']==99 and applied['verification']==report['iwm_holdings'];root=m.RUN/'README.md';pin=next(v for v in cp['artifacts'] if v['path']==str(root.relative_to(m.ROOT)));assert sha(root)==pin['sha256'];backup=m.BACKUP/'iwm-root-readme-before-001.json.gz';assert not backup.exists()
 for name in ['checks-001.json','remaining-research-001.json.gz','next-museum-pass-001.json','README.md','readme-supersessions-001.json','source-availability-001.json','new-source-access-holds-001.json']:assert not(RUN/name).exists()
 logsroot=Path('/Users/vadimdulub/Library/Logs');test=(logsroot/'artline-iwm-tests-20261009.log').read_text();assert 'Ran 25 tests' in test and test.rstrip().endswith('OK');assert(logsroot/'artline-iwm-replay-20261009.log').read_text().strip()=='Unchanged replay: zero writes';logs={v.name:dict(path=str(v),sha256=sha(v)) for v in sorted(logsroot.glob('artline-iwm-*-20261009.log')) if not any(x in v.name for x in ['delivery','checkpoint'])}
 m.save(RUN/'checks-001.json',dict(at=m.now(),new_offline_tests_passed=25,historical_tests_passed=1779,cumulative_verified_tests=1804,historical_tests_rerun=False,replay_zero_writes=True,source_objects_reviewed=103,new_artworks=0,existing_links=99,preserved_existing_network_holdings=34,preserved_existing_london_holdings=13,unresolved_london_assertions_preserved=88,editorial_holds=4,logs=logs,other_job_totals_separate=True,source_refinements='Initial extractor selected88 Wikidata sources and held15 native-format assertions. A separate retained-source adapter recovered all15 exact official pages and their original Wikidata bodies without rewriting initial artifacts. Commons metadata resolves equal-format Wheatley portraits. Four other composition questions remain held. No failed write transaction.'))
 access=[dict(host='www.iwm.org.uk',state='access_hold',reason='Official collections and London overview URLs returned403 through web.run. Both were submitted before the refusal was observed; all subsequent provider requests stopped.',retry_policy='Do not retry via direct HTTP,browser,media host or aliases as a workaround. Retained primary bodies and independent references remain usable with honest dates.',evidence_reference=ref(RUN/'native-probes-001.json'))];m.save(RUN/'new-source-access-holds-001.json',dict(at=m.now(),rows=access,previous_source_hold_reference=cp['new_source_access_hold_reference'],policy='IWM provider stopped after refusal. Every earlier access hold persists.'))
 m.save(RUN/'source-availability-001.json',dict(at=m.now(),new_source_access_holds=access,new_source_access_hold_reference=ref(RUN/'new-source-access-holds-001.json'),previous_source_availability_reference=cp['source_availability_reference'],previous_source_hold_reference=cp['new_source_access_hold_reference'],native_probe_reference=ref(RUN/'native-probes-001.json'),retained_primary_context_reference=ref(RUN/'retained-institution-context-001.json.gz'),comparison_context_reference=ref(RUN/'comparison-source-context-001.json.gz'),fresh_authority_references=[ref(RUN/n) for n in ['institution-authorities-001.json.gz','selected-authorities-001.json.gz']],commons_references=[ref(RUN/n) for n in ['selected-commons-discovery-001.json.gz','selected-commons-discovery-002.json.gz','selected-commons-descriptions-001.json.gz']],policy='No fresh successful IWM request.96 unique raw bodies verified,including retained5October official pages. Independent Wikidata authorities and selected Commons wikitext were captured without image downloads. Two broader Commons metadata searches yielded unrelated results,which were not used. Referenced Wikidata/ArtUK evidence remains secondary and correlated. No browser retry,images or provider workaround.'))
 decisions=m.load(RUN/'editorial-reviewed-001.json.gz')['decisions'];held=[v for v in decisions if v['state']=='editorial_hold'];assert len(held)==4;m.save(RUN/'remaining-research-001.json.gz',dict(at=m.now(),rows=held,unresolved_london_assertions=88,review_reference=ref(RUN/'editorial-reviewed-001.json.gz'),previous_remaining_research_reference=cp['remaining_research_reference'],network_linked=133,network_eligible=130,london_linked=13,london_eligible=13,remaining_network_to_200_eligible=70,policy='Four Gledstanes and Flint physical-version candidates remain held. London-specific claims remain unresolved even where wider network membership was accepted. Existing thirteen London and34 network holdings are preserved,not newly revalidated for venue or display. Three unknown dates remain excluded from eligible totals. All previous queues persist.'))
 oldq=m.load(m.ROOT/cp['next_museum_pass_reference']['path']);live=m.load(m.RUN/'after-wave-91.json');by={v['id']:v for v in live['institutions']};italian=[dict(v,current_linked=by[v['institution_id']]['works'],current_eligible=by[v['institution_id']]['eligible_works']) for v in oldq['italian_museums']];assert len(italian)==225;excluded=['Glasgow Museums Resource Centre','Kelvingrove Art Gallery and Museum','Burrell Collection','Bristol City Museum & Art Gallery','Imperial War Museum London'];nexttargets=sorted([v for v in live['institutions'] if v['kind']=='museum' and v['status']!='archived' and not v['canonical_institution_id'] and v['works']<100 and v['pending_associations']>0 and v['name'] not in excluded],key=lambda v:(-v['pending_associations'],v['id']))[:20];current_ids=sorted({v['id'] for v in oldq['current_museums']}|set(s.IIDS))
 m.save(RUN/'next-museum-pass-001.json',dict(at=m.now(),previous_queue_reference=cp['next_museum_pass_reference'],italian_museums=italian,existing_holding_review_targets=nexttargets,native_addition_targets=[by[v['id']] for v in oldq['native_addition_targets']],current_museums=[by[iid] for iid in current_ids],southampton_pdf_leads_reference=oldq['southampton_pdf_leads_reference'],edinburgh_portrait_leads=oldq['edinburgh_portrait_leads'],remaining_research_reference=ref(RUN/'remaining-research-001.json.gz'),source_availability_reference=ref(RUN/'source-availability-001.json'),policy='IWMnetwork133linked/130eligible crosses100 but needs70eligible works for200. London13/13 remains below100,with88unresolved branch claims and no quota-driven branch assignment. Continue Leeds,TheBox,York,Harris and other independent museum sources. Royal161/151 with12holds,Glasgow branch gaps and227 Resource Centre claims,Southampton15datedPDFleads,Edinburgh88/29,Guildhall115/86,225Italian museums and every earlier queue and access hold persist. Full goal active.',database_writes=0))
 total=report['institutions_with_new_records_or_reconciled_holdings'];text=f'''# Imperial War Museums holding review — 9 October 2026

Linked **99 existing artworks** to the wider Imperial War Museums collection after reviewing 103 exact source objects. The network increased from **34 to 133 linked records**, including **130 with eligible pre-1971 dates**. Three newly linked works remain undated. IWM London stays at **13 linked records**; all **88 pending London-specific claims remain unresolved**. Four candidates remain held. No new artwork rows were created.

Evidence includes 15 retained official IWM object pages, a retained official collection overview distinguishing its five branches, referenced Wikidata statements, fresh selected creator authorities and Commons descriptions. The official pages were captured on 5 October, not freshly fetched in this pass. IWM returned 403 when its collection and London pages were requested; further provider requests stopped. ArtUK’s earlier access hold also remains in force. Secondary references are correlated, not independent native confirmations.

Dodgson’s 29.1×34.9cm preparatory study remains distinct from his 182.8×220cm finished painting. Exact Commons descriptions distinguish Wheatley’s skipper portrait from his able seaman despite equal formats. The retained Alexander portrait page identifies Leigh-Pemberton’s copy after Birley; the original and copy were not confused. Native date precision and conflicting wording remain evidence alongside unchanged catalogue dates. Second World War subject matter does not supply missing creation dates.

The [four holds](remaining-research-001.json.gz) concern two Gledstanes Greenwich courtyard scenes and two Flint Walcheren paintings whose compositions still need comparison. William Thomas Wood remains an existing object-level creator label. Fresh authority checks distinguish Cecil Constant Philip Lawson from the earlier landscape painter. No artist links, attribution edits, images, publication or display assertions were added.

The [reviewed plan](iwm-existing-holdings-001-plan-001.json.gz) and [transaction receipt](iwm-existing-holdings-001-applied.json) verify **99 new citations and accepted network holding assertions**, superseding only **15 pending assertions for that same network**. Fresh identity checks covered **5,500 artworks and 11,914 citations**; all prior 13,099 campaign records and scoped legacy fields were preserved. **25 offline tests, atomic readback and zero-write replay passed.**

Campaign totals: **10,472 new artworks + 2,726 reconciled existing artworks = 13,198 distinct records across {total} institutions**. **{report['after']['museums_below_100']:,} canonical museums remain below 100 linked records**, and **{report['after']['museums_below_200']:,} below 200**. The network still needs 70 eligible dated works for 200, and London remains under the minimum. [Continuing research](next-museum-pass-001.json) preserves every earlier queue and source hold. The all-museum goal remains active.
'''
 m.save(backup,dict(at=m.now(),path=str(root),text=root.read_text(),sha256=sha(root)));(RUN/'README.md').write_text(text);old=root.read_text();intro,rest=old.split('## Added works',1);intro=intro.replace('2,627','2,726').replace('expand 234 institutions',f'expand {total} institutions').replace('1,232','1,231').replace('after-wave-90','after-wave-91').replace('Glasgow and Royal Collection passes','Glasgow, Royal Collection and Imperial War Museums passes');root.write_text(intro+'## Added works'+rest+'\n\n## Imperial War Museums holdings — wave91\n\nLinked 99 existing works to the wider IWM collection after reviewing103 objects. Network totals133linked/130eligible; London13/13 remains unchanged with88 pending branch claims. Fifteen retained native pages support selected objects;96 links have eligible dates and3remain unknown. Four Gledstanes/Flint composition holds remain. [Evidence and continuing work](native/iwm-holdings-20261009/README.md). Campaign:10,472new +2,726reconciled =13,198distinct across '+str(total)+' institutions. IWM access stopped after403; every earlier source hold and queue persists. Full all-museum goal active.\n');m.save(RUN/'readme-supersessions-001.json',dict(at=m.now(),changes=[dict(path=str(root.relative_to(m.ROOT)),before_sha256=pin['sha256'],after_sha256=sha(root),backup_path=str(backup),backup_sha256=sha(backup))]));print(json.dumps(dict(documented_new_records=0,documented_existing_links=99,held=4,preserved_network=34,preserved_london=13,london_claims_preserved=88,tests=25,institutions_expanded=total,goal_complete=False)),flush=True)
if __name__=='__main__':main()
