"""Record wave89 outcomes, source availability and every continuing research queue."""
import hashlib,importlib.util,json
from pathlib import Path
z=importlib.util.spec_from_file_location('n',Path(__file__).with_name('museum-expansion-glasgow-native-20261009.py'));n=importlib.util.module_from_spec(z);z.loader.exec_module(n);m=n.m;RUN=n.RUN;ref=n.ref;KEY='glasgow-existing-holdings-001';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 report=m.load(m.RUN/'verification-after-wave-89.json');assert(report['verified_new_artworks'],report['verified_existing_artworks_linked'])==(10472,2548);cp_path=m.RUN/'native/southampton-additions-20261009/delivery-checkpoint-001.json';assert sha(cp_path)=='0425429512c9853f754a1561f502c1ddab12ec19470f44a1bab9011fd27f059b';cp=m.load(cp_path);applied=m.load(RUN/(KEY+'-applied.json'));assert applied['created']==0 and applied['existing_links']==61 and applied['verification']==report['glasgow_holdings'];root=m.RUN/'README.md';pin=next(v for v in cp['artifacts'] if v['path']==str(root.relative_to(m.ROOT)));assert sha(root)==pin['sha256'];backup=m.BACKUP/'glasgow-root-readme-before-001.json.gz';assert not backup.exists()
 for name in ['checks-001.json','remaining-research-001.json.gz','next-museum-pass-001.json','README.md','readme-supersessions-001.json','source-availability-001.json','new-source-access-holds-001.json']:assert not(RUN/name).exists()
 logsroot=Path('/Users/vadimdulub/Library/Logs');test=(logsroot/'artline-glasgow-tests-20261009.log').read_text();assert 'Ran 18 tests' in test and test.rstrip().endswith('OK');assert(logsroot/'artline-glasgow-replay-20261009.log').read_text().strip()=='Unchanged replay: zero writes';logs={v.name:dict(path=str(v),sha256=sha(v)) for v in sorted(logsroot.glob('artline-glasgow-*-20261009.log')) if not any(x in v.name for x in ['delivery','checkpoint'])}
 m.save(RUN/'checks-001.json',dict(at=m.now(),new_offline_tests_passed=18,historical_tests_passed=1738,cumulative_verified_tests=1756,historical_tests_rerun=False,replay_zero_writes=True,source_objects_reviewed=253,new_artworks=0,existing_links=61,preserved_existing_network_holdings=183,editorial_holds=9,logs=logs,other_job_totals_separate=True,source_refinements='Before review artifact: duplicate citations to the same native URL/body initially triggered an overstrict one-citation guard. Guard now requires one unique native object/body and retains all citation references. Earlier source/context parser failures remain logged. No failed write transaction.'))
 access=[dict(host='collections.glasgowmuseums.com',state='access_hold',reason='Three distinct selected inventory searches each reached45second read timeout. Requests stopped.',retry_policy='Do not retry or bypass Navigator; retain saved evidence and seek independently available official sources.',evidence_reference=ref(RUN/'native-selected-searches-001.json'))];m.save(RUN/'new-source-access-holds-001.json',dict(at=m.now(),rows=access,previous_source_hold_reference=cp['new_source_access_hold_reference'],policy='Navigator host on hold after three timeouts. Every prior source hold persists.'))
 m.save(RUN/'source-availability-001.json',dict(at=m.now(),new_source_access_holds=access,new_source_access_hold_reference=ref(RUN/'new-source-access-holds-001.json'),previous_source_availability_reference=cp['source_availability_reference'],previous_source_hold_reference=cp['new_source_access_hold_reference'],native_capture_reference=ref(RUN/'native-probes-001.json'),session_probe_reference=ref(RUN/'navigator-session-probe-001.json'),comparison_context_reference=ref(RUN/'comparison-source-context-001.json.gz'),dali_reference=ref(RUN/'dali-native-001.json'),browser_environment_error='In-app browser bootstrap and simple connection check failed with codex/sandbox-state-meta missing field sandboxPolicy. No browser control or substitute browser used.',policy='Ordinary public HTTP metadata requests only. Anonymous session cookies were exact public bootstrap defaults,not credentials or invented roles. Navigator requests stopped after third timeout; observed Dalí object1 link not fetched.548 retained raw bodies verified, including official historical object pages. Fresh Glasgow Life collection,Resource Centre and Dalí context; no images downloaded or attached. Correlated Wikidata/ArtUK statements are not independent confirmations.'))
 decisions=m.load(RUN/'editorial-reviewed-001.json.gz')['decisions'];held=[v for v in decisions if v['state']=='editorial_hold'];preserved=[v for v in decisions if v['state']=='preserved_existing_network_holding'];assert len(held)==9 and len(preserved)==183;m.save(RUN/'remaining-research-001.json.gz',dict(at=m.now(),rows=held,preserved_network_records=[dict(number=v['number'],artwork_id=v['existing_artwork_id'],resource_centre_pending_assertion_id=v['pending_assertion_id'],reason='Existing network holding preserved; specific storage remains unresolved.') for v in preserved],unresolved_resource_centre_assertions=227,unreviewed_source_groups_reference=ref(RUN/'source-context-001.json.gz'),review_reference=ref(RUN/'editorial-reviewed-001.json.gz'),previous_remaining_research_reference=cp['remaining_research_reference'],policy='Nine holds retain scope,qualified creator,co-creator and duplicate/version questions. Preserve227 Resource Centre claims.57 non-unique/no-structured-source assertion groups are not extra objects and remain separately tracked. All previous research queues remain active.'))
 oldq=m.load(m.ROOT/cp['next_museum_pass_reference']['path']);live=m.load(m.RUN/'after-wave-89.json');by={v['id']:v for v in live['institutions']};italian=[dict(v,current_linked=by[v['institution_id']]['works'],current_eligible=by[v['institution_id']]['eligible_works']) for v in oldq['italian_museums']];assert len(italian)==225;nexttargets=sorted([v for v in live['institutions'] if v['kind']=='museum' and v['status']!='archived' and not v['canonical_institution_id'] and v['works']<100 and v['pending_associations']>0 and v['name'] not in ['Glasgow Museums Resource Centre','Kelvingrove Art Gallery and Museum','Burrell Collection','Bristol City Museum & Art Gallery']],key=lambda v:(-v['pending_associations'],v['id']))[:20];glasgowids=['85cac2f9-413c-55fe-adfd-8cc3ed4a20ee','89b28271-8a23-594a-b1c6-9f1697c3ed3e','dfd2cc76-46d4-5ac0-9775-528ad15a13e4','eb9d51d2-026c-5ca4-8414-3f0ed82ae46b']
 m.save(RUN/'next-museum-pass-001.json',dict(at=m.now(),previous_queue_reference=cp['next_museum_pass_reference'],italian_museums=italian,existing_holding_review_targets=nexttargets,native_addition_targets=[by[v['id']] for v in oldq['native_addition_targets']],current_museums=[by[iid] for iid in glasgowids],southampton_pdf_leads_reference=oldq['southampton_pdf_leads_reference'],edinburgh_portrait_leads=oldq['edinburgh_portrait_leads'],remaining_research_reference=ref(RUN/'remaining-research-001.json.gz'),source_availability_reference=ref(RUN/'source-availability-001.json'),policy='Glasgow network224linked/165eligible crosses200linked but still needs35date-eligible works for preferred200. Kelvingrove21/21,Burrell3/2,ResourceCentre22/17 remain below100. Do not move existing network holdings to fill branch quotas. Continue independent-source museum research; do not retry Navigator or earlier held hosts. Southampton15datedPDFleads,Edinburgh88/29,Guildhall115/86,225Italian museums and every prior queue persist. Full goal active.',database_writes=0))
 total=report['institutions_with_new_records_or_reconciled_holdings'];text=f'''# Glasgow holding review — 9 October 2026

Linked **61 existing artworks** after reviewing 253 exact source objects: **40 to Glasgow Museums**, **19 to Kelvingrove**, and **two to the Burrell Collection**. Preserved 183 already accepted Glasgow Museums holdings; nine further objects remain held. No new artwork rows were created in this pass.

| Collection | Linked before | Linked now | Eligible pre-1971 dates now |
| --- | ---: | ---: | ---: |
| Glasgow Museums | 184 | 224 | 165 |
| Kelvingrove | 2 | 21 | 21 |
| Burrell Collection | 1 | 3 | 2 |
| Resource Centre | 22 | 22 | 17 |

The [official Resource Centre page](https://www.glasgowlife.org.uk/museums/venues/glasgow-museums-resource-centre-gmrc) explains its relationship to the wider collection. An object page saying “In storage” and a footer address do not establish storage in that particular building. All 227 pending Resource Centre claims remain unresolved. Glasgow Museums exceeds 200 linked records but has 165 eligible dated works; the branch museums remain below the minimum.

Evidence includes 548 checksum-verified saved bodies, retained official Navigator object records and explicitly labelled Wikidata statements with ArtUK references. Those correlated secondary references are not newly fetched ArtUK confirmations. The [official Dalí page](https://www.glasgowlife.org.uk/museums/venues/kelvingrove-art-gallery-and-museum/salvador-dalis-christ-of-st-john-of-the-cross) independently supports the 1951 work’s Kelvingrove association. Two pending Dalí assertions were reconciled to one existing object.

Of the 61 links, **49 have eligible creation dates and 12 remain undated**. Native date differences, the alternative sitter names for Aikman’s inventory3139 and the custody label “Out on Loan” for Purvis’s T.2008.8 are retained in citations. None establishes a current display claim. John Gibson and James Hamilton remain existing object-level creator labels. Cadell’s two Reflections paintings have substantially different physical dimensions. The [nine holds](remaining-research-001.json.gz) retain unresolved Denune, Lavery, Mackintosh and Knox versions, qualified creators, co-creators and a modern portrait’s date scope.

The [reviewed plan](glasgow-existing-holdings-001-plan-001.json.gz) and [transaction receipt](glasgow-existing-holdings-001-applied.json) verify 61 new citations and accepted holding assertions, with only 23 same-target pending assertions superseded. Fresh identity checking covered 28,912 artworks and 59,408 citations. Every prior campaign object and scoped legacy field was preserved. **18 offline tests, atomic readback and zero-write replay passed.** No artist links, images, publication, commit or deployment.

Navigator searches timed out three times; requests to that host stopped. Browser connection also failed with an environment error. Saved primary evidence supported this pass; neither issue blocks research elsewhere. All earlier source holds remain in force.

Campaign: **10,472 new artworks + 2,548 existing-artwork reconciliations = 13,020 distinct records across {total} institutions**. **{report['after']['museums_below_100']:,} canonical museums remain below 100 linked records** and **{report['after']['museums_below_200']:,} below 200**. [Next research](next-museum-pass-001.json) retains the Glasgow gaps, 15 dated Southampton PDF leads, Edinburgh, Guildhall, 225 Italian museums and all earlier queues. The all-museum goal remains active.
'''
 m.save(backup,dict(at=m.now(),path=str(root),text=root.read_text(),sha256=sha(root)));(RUN/'README.md').write_text(text);old=root.read_text();intro,rest=old.split('## Added works',1);intro=intro.replace('2,487','2,548').replace('expand 230 institutions',f'expand {total} institutions').replace('after-wave-88','after-wave-89').replace('Southampton and Edinburgh passes','Southampton, Edinburgh and Glasgow passes');root.write_text(intro+'## Added works'+rest+'\n\n## Glasgow holdings — wave89\n\nLinked 61 existing works: 40 to Glasgow Museums, 19 to Kelvingrove and two to Burrell. Glasgow Museums now has 224 linked records and 165 with eligible dates; Kelvingrove has 21/21 and Burrell 3/2. Preserved 183 accepted network holdings and 227 unresolved Resource Centre claims. Nine attribution,version or scope holds remain. [Evidence and continuing work](native/glasgow-holdings-20261009/README.md). Campaign: 10,472 new + 2,548 reconciled = 13,020 distinct records across'+str(total)+' institutions. Navigator access hold after three timeouts; all earlier queues and holds persist. Full all-museum goal remains active.\n');m.save(RUN/'readme-supersessions-001.json',dict(at=m.now(),changes=[dict(path=str(root.relative_to(m.ROOT)),before_sha256=pin['sha256'],after_sha256=sha(root),backup_path=str(backup),backup_sha256=sha(backup))]));print(json.dumps(dict(documented_new_records=0,documented_existing_links=61,held=9,preserved=183,tests=18,institutions_expanded=total,goal_complete=False)),flush=True)
if __name__=='__main__':main()
