"""Wave124 immutable checkpoint after actual verified Theocharakis delivery."""
import hashlib
import importlib.util
import json
from pathlib import Path
spec=importlib.util.spec_from_file_location('d',Path(__file__).with_name('museum-expansion-theocharakis-delivery-20261010.py'))
d=importlib.util.module_from_spec(spec);spec.loader.exec_module(d)
a,c,m,RUN=d.a,d.c,d.m,d.RUN
sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest()

def main():
    dest=RUN/'delivery-checkpoint-001.json';assert not dest.exists();report=m.load(RUN/'delivery-001.json');checks=m.load(RUN/'checks-001.json');public=m.load(RUN/'public-delivery-001.json')
    assert report['added']==196 and report['existing_links']==1 and checks['readback_passed']and checks['replay_zero_writes']and public['public_image_hashes_matched']==114 and public['public_artwork_samples']==6
    plan,digest=a.validate_plan();assert digest==d.EXPECTED and c.ref(c.CP)['sha256']==c.CP_SHA
    prior=m.load(c.CP);oldpins={v['path']:v for v in prior['artifacts']};oldext={v['path']:v for v in prior['external_artifacts']};pins=dict(oldpins);external=dict(oldext)
    def add(pin,target):
        assert pin['path']not in target or target[pin['path']]==pin,pin['path'];target[pin['path']]=pin
    paths={c.CP,c.RESEARCH_CP,c.DATED/'research-checkpoint-001.json',a.PLAN,Path(__file__).resolve()}
    paths|={v for v in RUN.rglob('*')if v.is_file()};paths|={v for v in(m.ROOT/'ops').glob('*theocharakis*20261010.py')}
    for path in sorted(paths):add(c.ref(path),pins)
    for pin in plan['evidence']:add(pin,pins)
    for pin in plan['external_evidence']:add(pin,external)
    for path in sorted(m.BACKUP.glob('theocharakis-production-*.json*')):add(dict(path=str(path),sha256=sha(path)),external)
    add(dict(path=plan['backup_path'],sha256=sha(plan['backup_path'])),external)
    newpins=[v for v in pins.values()if oldpins.get(v['path'])!=v];newext=[v for v in external.values()if oldext.get(v['path'])!=v]
    for pin in newpins:c.checked(pin)
    for pin in newext:assert sha(pin['path'])==pin['sha256'],pin['path']
    protected=m.load(RUN/'protected-production-ids-001.json')['ids'];assert len(protected)==1584 and set(protected)==set(plan['prior_ids'])|{v['artwork_id']for v in plan['records']+plan['holdings']}
    pending=report['remaining_pending_candidates'];assert sum(pending.values())==225
    next_work='''Wave124 made verified production progress. Theocharakis196new review artworks+1existing-work museum link+114authentic images. Actual museum18catalogue/12numeric eligible/12primary images to215catalogue/137numeric eligible/123primary-image works. Preferred200catalogue reached, numeric100minimum reached. Campaign1579new+5existing links across10museums;1584protected IDs. Real local catalogue unchanged; goal ACTIVE/incomplete.

Current immutable plan theocharakis-delivery-20261010/theocharakis-production-001-plan-001.json.gz SHA79734d55e12a1ee86f87cb03f5c7984c215c9f772caeb07e9064a6b7a42f7080. Use ops/museum-expansion-theocharakis-apply-20261010.py directly for validate_plan/verify; no adapter. Backup1791642599796SUCCESSFUL, operation7b235487-f7af-4e24-bef9-278800000024.23offline checks, atomic verification, independent readback, zero-write replay,114public image hashes and6API samples passed. New196artist links to unique existingSpyrosPapaloukas96c93b65-37db-4879-9bf7-3bf5a9d8178e; exact native/Englishname1892–1957matchesNationalGalleryauthority; authority row/aliases/identifier unchanged.65full existing comparators and1387previouscampaign IDs protected. All old target18dates/statuses/images/creatorlinks preserved,6unknown dates retained. No new published/current-display claims.

The197Theocharakis candidates resolve196new+existingWikiArtBoat1948 ID733bd5c0-a88e-535d-9e06-e383ce9b3883. NativeBoat atParos103169 confirms same redhull/benches/waves/shoreline/signature; source1948agrees. Existing titleBoat,unknown type,1948date andprimaryb8760fa6-091c-5ccd-a343-710a7a12e2c6preserved; native imagealternate. Existing matchconfidence.99editorial. New196have124numeric72unknown; actual controlled work types are recorded in the editorial review. Eighttwo-sided sheets countonce,196canonicalexternalIDs;all205candidate sourcepages inmetadata.13sourceidentityholds remain excluded. Fourreverse references toolder sheets remainresearch evidence, notextra works ormetadata rewrites. Dated30pear103308imageheld dimensions/title mismatch;13post1955newworks and72unknown newworks metadata-only. BroadernativeMarinatos1950–55/Danae1948–49retained.114images=110newprimary+3new-sheetalternate sides+Boat alternate,111physical works. ActualCCBYSA4.0source labels; media rights_statuscc_by_sa. Source metadata rightslabel anduserGreekapproval remain distinct; originalsarchived,completeframesJPEG<=100000B.114framesreviewed8contacts;18existingPapaloukasimagescontact+Boatpairfullframes+post1955selfportrait103449checked. WikiArt1941selfportraitdistinctfrom5selectedlaterportraits. ExistingGreekBoywithSuspenders andWikiArtBoywearingsuspenders visuallyduplicate; unrelatedtoTheoadditions,notmerged/reassigned.

Fresh source/creator/title/image query3766artworks7452citations3134creatorlinks; uniquePapaloukas37existingworks=18target+19other; all18oldsourceIDs matched,0checksumhits.65focused=same37+28unresolved-creatortitleleads. Mostother exact-titlehits differentattributedcreators.28unresolvedleadsarewood/metalsculptures,Asianperiodscrolls,Byzantineicons/wallpaintings. KyotoA671describesIsshiKii2scrolls;BXM01803Egypticon84x59cm differsfrom17.5cmpencilstudies;AsinouArchangeliswallpainting. Fullmetadata,cites,creatorlinks remain insearch evidence. Globalidentity preflight verifies broadprojections plus65fullsnapshots. One-offquerytimings/plans aren't10millionloadproof. No code/servicequerychanges.

Fresh sourcecaptures foundationprofile,NationalGalleryartistauthority andWikiArtBoat allsuccessful. Native114selectedimage captures/reusedoriginals successful; no newaccessholds. KeepALLinherited403/429/timeout restrictions inclChaniaamch.gr andArtInstitute403W123, Zongolopoulos403/eMuseumPlustimeout/error, andLarissanativeimage46/67/92 failures/image7timeout. Do notretry/bypassrestrictedproviders. CP123Chania6271b1b69d41f9aeb0f9aab4fc42b3478baae6cb9639e9c7e8993f69a0e671d8 remainspriorcheckpoint; Chania192/117stillneeds8catalogue works for200 and108unreviewedsource records/14scopeholds; no promise108eligibleobjects.

Next deliver225reviewed candidates:Zongolopoulos199 andKilkis26, after fresh scoped/globalidentity checks,newdeliveryruns/scripts. ZongCP117native/zongolopoulos-20261010 SHA32b31e616cf63bd20a1edc62468fe01fb6c23fea9a8474e4b8aa91419402582e49dated; CP118native/zongolopoulos-paintings-20261010 SHAb62abdfbe4fa05e5309431b9e78baae7baea6859403f47f9a4d3d58ef060c49c150further.199physicalcandidates,19imagesprepared,two-sided supports countonce,physicalunknownsexplicit. Nativezongolopoulos.gr403andcollectioneMuseumPlusoneexplicitentrytimeout;SPARQLrecordsourceavailableearlier, neverbypass. KilkisCP114native/kilkis-review-20261010 SHAb224245951d11814db9dcc2104b868f2b2600c7f7998c066097b4c6000a07f9e26selected6holds; revisitoverbroadNCNDimagehold underGreekapproval. Candidatecountsaren'tguaranteednewIDs. TheoCP115/116researchREADME pendingcounts remainhistorical, supersededbythisdelivery; no197pendingTheo afteractualdelivery.

Next freshmuseumresearchAveroffIIDea977842-2f6e-5020-a853-d300b507aca0,last18/9. Source discovery kazantzakis-more-delivery-20261010/next-source-discovery-001.json.gz native https://www.averoffmuseum.gr/ advertises>700 vsSC71. Observed /zografiki /glyptiki /haraktiki /shedio /fotografia /nea-mesa-ekfrasis; noobjectreviewyet.700collectionclaimnoteligiblecount;shopreproductionsnotoriginals. AthensCityIIDf575847e-47eb-59e4-b558-32d8723bc3c9SC DigAthensMuseum,last18/16follows.229-row priorityqueue ishistoricalunder100subset, notglobalcensus;onlyTheocharakis registerrowrefreshedthiswave.

Taskproxy127.0.0.1:55519PID7614 --gcloud-auth checkedliveW124;existinggcloudidentityworks.Leaveunrelated55445/55478proxies/jobsuntouched. Observeauthoritativehandlebefore recovery; neverrestart becauseobservationtimeout. No credentialsprinting, alternateidentity, subagents, commits, deployment, localwrites orfixtures. Executedwriters/pinnedartifactsimmutable;newversionsforcorrections. Inheritfullhistoricalarchiveproof;verifynewpins/relevantsnapshots only. Productionselected additions/imagesalready authorized,no repeatedapproval.'''
    result=dict(prior)
    result.update(at=m.now(),wave=124,goal_complete=False,goal_status='active',previous_goal_turn='progress',production_only=True,local_unchanged=True,new_additions=196,new_existing_links=1,new_images=114,verification=report['verification'],production_museum_before=report['museum_before'],production_museum_after=report['museum_after'],production_campaign_totals=report['production_campaign_totals'],global_production_counts_refreshed=False,global_production_thresholds_refreshed=False,new_tests_passed=23,plan_sha256=digest,plan_reference=c.ref(a.PLAN),prior_checkpoint_reference=c.ref(c.CP),previous_research_checkpoint=c.ref(c.RESEARCH_CP),additional_research_checkpoint=c.ref(c.DATED/'research-checkpoint-001.json'),artifacts=list(pins.values()),external_artifacts=list(external.values()),baseline_reference=c.ref(RUN/'baseline-verification-001.json'),review_reference=c.ref(a.REVIEW),checks_reference=c.ref(RUN/'checks-001.json'),public_delivery_reference=c.ref(RUN/'public-delivery-001.json'),production_institution_register_reference=c.ref(RUN/'production-institution-register-001.json.gz'),priority_museum_queue_reference=c.ref(RUN/'priority-museum-queue-001.json'),protected_production_ids_reference=c.ref(RUN/'protected-production-ids-001.json'),pending_candidates=pending,pending_candidate_total=225,global_threshold_summary_note='Only Theocharakis refreshed to215/137. Other observations retain timestamps;229priorityrowsare a subset.',source_availability=report['source_access'],remaining_research_reference=c.ref(m.RUN/'native/zongolopoulos-paintings-20261010/research-checkpoint-001.json'),preferred_target_remaining=dict(institution_id=c.IID,catalogue=215,gap_to200=0,target_reached=True),public_api_date_scope=public['date_scope_note'],next_work=next_work)
    for key in ['superseded_plan_reference','identifier_reconciliation_reference','replay_contention_note','new_source_access_hold_reference']:result.pop(key,None)
    m.save(dest,result)
    m.save(RUN/'final-checkpoint-verification-001.json',dict(at=m.now(),checkpoint=c.ref(dest),verified_new_artifact_pins=len(newpins),verified_new_external_pins=len(newext),inherited_unchanged_artifact_pins=len(pins)-len(newpins),inherited_unchanged_external_pins=len(external)-len(newext),full_historical_proof=prior['initial_full_historical_verification_reference'],plan_sha256=digest,goal_complete=False,actual_added=196,actual_existing_links=1,actual_images=114,protected_production_ids=1584,pending_candidates=225,local_unchanged=True))
    print(json.dumps(dict(checkpoint=c.ref(dest),artifacts=len(pins),external=len(external),verified_new=len(newpins),verified_external=len(newext),added=196,links=1,images=114,pending=225)),flush=True)
if __name__=='__main__':main()
