"""Individual physical-object decisions for the frozen 265-record eighth queue."""
HOLDS = {
17: 'Cadel labourer is called a drawing but also a reproduction, marked 1/24; physical reproduction type and execution date require reconciliation.',
26: 'Solange Sand flower sheet has 1863 headline and 1864 inscription, with a close existing flower drawing c12e20ba; reconcile physical sheet and dates before adding.',
37: 'Desmoulin Rollinat is explicitly a reproduction after an engraving after a Melandri photograph; circa 1882 may date the model rather than this impression.',
54: '1844 Salon print names a publisher with source lifespan 1850–1928. Preserve the source discrepancy and resolve publisher/model/impression chronology.',
68: 'Sparse existing b222a03e-80a7-41ca-b0ff-f7095c1d0f20 has the same Janssens gallery title. It cannot yet be assigned securely to 874.62 or 874.63.',
70: 'Second Janssens gallery canvas 874.63 likewise overlaps sparse b222a03e-80a7-41ca-b0ff-f7095c1d0f20; no duplicate addition until the two versions are reconciled.',
71: 'Two Gien vases share one inventory and have separate dimensions and marks; physical object-unit treatment needs reconciliation before counting.',
75: 'Anonymous doctor panel in the genre of Andrea del Sarto has sixteenth-century headline but seventeenth-century frame label; preserve the unresolved date/attribution evidence.',
78: 'Source explicitly reports two identical lithographs but only one inventory entry; resolve which physical impression this record identifies.',
84: 'Méditation is attributed to Mlle Burdy in older inventories, while two different Burdy women appear as makers. Alternative attribution versus joint authorship is unresolved.',
94: 'Sparse existing 50023a2b-3c4a-479c-931d-8c5a61b6625a has the same Donzel river subject with 1888 versus this signed 1885 sheet; physical identity remains unresolved.',
106: 'Sparse existing 10fa5684-c7a8-40bc-9a59-0c9fa0ff89f4 has the same Garneray Marine title and century, without enough physical metadata to exclude duplication.',
111: '1795 publication inscription accompanies a lithography classification; physical technique/impression chronology needs verification.',
131: 'Functional 1881 vineyard survey by a géomètre requires separate artwork-scope review; no quota-based inclusion.',
137: 'Asselin creation headline 1837 contradicts source birth 1882 and a signature ending 37; do not silently correct to 1937.',
152: 'Flandrin saint study is close in medium and dimensions to existing 20494c04-85d6-5656-9a74-641786516b21 Standing Female Saint. Physical figure/version comparison remains outstanding.',
249: 'Toshikata Temari has 1893 headline and narrative execution in 1891; retain date conflict pending reconciliation.',
251: 'Kunichika actors print has 1874 creation and a Meiji-eight title. Whether this is an advance-season announcement or erroneous date is unresolved.',
257: 'Incomplete Fusatane triptych lists left and central sheets plus a second central impression under one inventory. Resolve the physical units before addition.'
}
NOTES = {
1: 'Anonymous Coudray chromolithograph dated April 1869, 25.6 by 36.3 cm; unnamed maker stays unknown.',
2: 'Adam/Arnout/Godard funeral chromolithograph, circa 1848, 40.3 by 51.4 cm; event dates and maker roles retained.',
3: 'Adam/Courtin/Godard Lamartine speech chromolithograph, circa 1848; differing February event dates do not replace the source execution period.',
4: 'Allier/Villeneuve/Desrosiers Roche Guillebauld lithograph dated 1833–1835; one 31.2 by 42.7 cm sheet.',
5: 'Barriot Motte Feuilly print before 1970, 14.2 by 12 cm; exclusive upper bound and unknown lower date retained.',
6: 'Barriot old La Châtre houses print before 1970, 14.3 by 11.4 cm, separate from the Motte Feuilly sheet.',
7: 'Baugniet/Dewasme 1837 Calamatta portrait print; source burin medium and lithographic inscription discrepancy retained in evidence, no technique correction.',
8: 'Bayot/Lemercier circa 1848 Affre barricade print, 45.6 by 58.7 cm; historical narrative is depicted-event context.',
9: 'Beaumont 1848 Vésuviennes Charivari impression 815.1; related inventory list identifies other sheets, not additional objects imported here.',
10: 'Bellangé 1830 barricade charcoal-burner lithograph, signed and dated 1830, 47.3 by 38.7 cm.',
11: 'A. Blanchet 1874 La Châtre Rochaille chromolithograph; unresolved initial remains literal.',
12: 'Boncoeur/Ed. Leveque 1944 Mignaton graphite sheet, 50.3 by 32.6 cm; author-note name included in comparison.',
13: 'Bonnart Louis de Bourbon equestrian intaglio before 1710; seventeenth-century biographical events are not substituted as creation dates.',
14: 'Bonnat circa 1866 Dumas fils lithograph; paper impression distinguished from the Louvre drawing model RF 6837 and later oil portraits.',
15: 'Boschère Eagle and Beetle fable gouache before 1953, 32 by 24.4 cm, specific subinventory 632.2.',
16: '1895 Pavie print after Boutigny, 46.3 by 56.3 cm; E. F. Deblois inscription searched as an additional comparison name, without authority assignment.',
18: 'Calamatta Lina 1866 charcoal portrait, 48.5 by 33 cm; different from the 1848 childhood portrait by Joséphine Calamatta.',
19: 'Calamatta Sand 1837 impression dedicated to Piffoël Rollinat, framed 23 by 19 cm, 2004.2.1; distinct from proof and small impression below.',
20: 'Calamatta Sand 1836 proof before letters, 34 by 22 cm, inventory 15; 1834 is the Delacroix model date.',
21: 'Calamatta/Delacroix Sand 1837 small impression, 17 by 12.7 cm, inventory 33; kept distinct from inventory 15 and the dedicated impression.',
22: 'Charpentier/Domnec circa 1848 flag-blessing chromolithograph; literal sheet and mounting dimensions retained.',
23: 'Charpentier/Bosio circa 1848 May-accused lithograph; multiple portraits occur on one catalogued sheet.',
24: 'Chatel/Riester/Puchot decorated 1848 decree lithograph, 61.4 by 45.8 cm; allegorical border and text form one print.',
25: 'Clésinger 1870 hanging-scene ink drawing, with December 1870 Bordeaux annotation; distinct from a photograph or later reproduction.',
27: 'Collette/Delarue/Kaep­pelin 1848 Delavau lithograph, 33.7 by 23.9 cm.',
28: 'Collette 1848 Fleury lithograph, 30 by 22.2 cm; different maker and physical dimensions from Llanta inventory 115.',
29: 'Collette/Domnec heroism lithograph of 1848, 35.7 by 42.3 cm, 2009.0.28.',
30: 'Combes Nohant pavilion charcoal dated 14 June 1904, 48.8 by 31.7 cm.',
31: 'Couture/Manceau Sand 1850 lithograph, 48.5 by 40.3 cm; print remains distinct from its drawing model and Versailles oil portrait.',
32: 'Couture/Quesnel nineteenth-century Sand intaglio, 20 by 13 cm, inventory 8; distinct from the larger 1850 lithograph and original painting.',
33: 'Pierre Dejean Montipouret wash dated 1958 on card back, 21 by 26.7 cm.',
34: 'Delarmessin Louis Duc de Bourbon 1685 intaglio; unresolved maker spelling remains literal.',
35: 'André des Gachons 1918 Limousin house watercolour, 24 by 31.2 cm.',
36: 'Desmadryl Sand print of 1841 after Auguste Charpentier; 1839 Salon refers to the original painting.',
38: 'Desrochers Jeanne de France etching before 1741; sitter dates 1498/1504 are not execution dates.',
39: 'Devéria Ajasson 1832 lithograph, 50.3 by 34.2 cm.',
40: 'Devéria/Motte Liszt lithograph with August 1832 publication inscription, 49.3 by 35.4 cm.',
41: 'Devéria/Thierry Pauline 1840 impression, La Châtre inventory 96 and window 38 by 28 cm; Cleveland 2009.521 is a separately acquired physical impression, not this sheet.',
42: 'Devéria/Thierry Eugénie Garcia chromolithograph of 1840, 49.2 by 36 cm; different named sitter from Pauline.',
43: 'Fauchier cooper pencil drawing before 1965, 40.4 by 28.8 cm.',
44: 'Choisy butterfly-service plate 1992.1.4.1, diameter 24 cm, source 1863–1878; one marked ceramic plate, not the entire service or the later commercial porcelain mentioned in contextual history.',
45: 'Foussereau/Charpentier/Lemercier 1848 guards chromolithograph, 52.5 by 36.5 cm.',
46: 'Gaudet gothic-well watercolour signed 1921, 31.1 by 16 cm.',
47: 'Gavarni circa 1831 student-costume print, 22.8 by 17.3 cm; presumed Sand sitter remains qualified.',
48: 'Gigoux/Frey Tony and Alfred Johannot lithograph, source 1831–1894 range retained; printer biography does not create a new precise date.',
49: 'Gigoux Marie Dorval lithograph before 1849; possible Delaroche model remains uncertain source history, not an assigned maker authority.',
50: 'Hollebecque 1941 timber-house watercolour and ink; fifteenth-century architecture is the subject, not execution date.',
51: 'Hédouin Quinet portrait proof before 1889, 16.6 by 11.4 cm.',
52: 'Jarnoux apple-harvest graphite sheet dated 25 November 1970; creation at the cutoff remains eligible despite the later artist death.',
53: 'Jbm Plaut July Revolution monumental print of 1830, one large 71 by 105 cm paper sheet; maker label not expanded.',
55: 'Julien/Aubert Sand lithograph of 1837, 18 by 13 cm; distinct from Vieusseux 1876 oil portrait.',
56: 'Lafosse 1866 Clésinger lithograph after Pierre Petit photograph; inscribed photo, lithographer and printer roles retained.',
57: 'Eugène Lambert circa 1846 graphite south façade of Nohant, dedicated to Fleury; not another Lambert landscape by surname alone.',
58: 'Bonaventure Laurens 1840 graphite woman portrait; presumed Solange identification remains qualified.',
59: 'Bonaventure Laurens circa 1840 Valldemosa pencil sheet, with Aurore Sand attribution note; publication plate context preserved separately.',
60: 'Lauth Aurore graphite portrait before 1922, 14.7 by 9.8 cm, with F.L. signature.',
61: 'Lefèvre/Delpech Duc de La Châtre portrait print; source 1817–1824 range and explicitly unknown exact date retained.',
62: 'Metzmacher Sandeau intaglio dated 1858 after Lehmann 1850 drawing; short inventory 107 collision is Couturier horse review of 1885, a different subject and maker.',
63: 'Lessore young Balzac intaglio before 1895, 26 by 20.1 cm; widow Cadart printer retained as a role.',
64: 'Marcenay de Ghuy Marshal Saxe 1766 engraving after Liotard; paper impression distinguished from painted model.',
65: 'Llanta/Lemercier circa 1848 Fleury lithograph, 37.4 by 28.7 cm, source inventory 115; distinct from Collette impression.',
66: 'Duret Saint Gabriel bronze statuette, 37.5 cm high, signed Duret and Quesnel founder; related 003.3.1 is not imported as another object.',
67: 'Girodet male-portrait study recto and family sketch verso, one 19.6 by 14.3 cm sheet, 982.14.1/2; not two records.',
69: 'Triqueti martyr above altar plaster relief, 18.6 by 8.3 by 2.5 cm, with signature on side.',
72: 'Vinkeles Pichegru nineteenth-century burin after unresolved A.S.; initials remain unexpanded and one measured print is added.',
73: 'André Allard Coin de salon canvas signed and labelled FNAC 1774, source before 1895; pending ownership transfer remains literal custody evidence, without a legal-title claim.',
74: 'Anonymous eighteenth-century Port oriental canvas in the genre of Gabriel Allegrain; former Claude Gellée pastiche description retained, distinct from small Claude print and original seventeenth-century compositions.',
76: 'D’Astanières Antoine-Albert Sarret de Grozon marble bust, 77 cm high; single signed nineteenth-century sculpture.',
77: 'Pointurier nineteenth-century Charles IX and Ambroise Paré lithograph after Baille, 70.9 by 53.7 cm; historical event is depicted subject.',
79: 'Vernier Jules Grévy lithograph after Bonnat, 52 by 40 cm, FNAC 423; distinct from Bonnat paintings of other public figures.',
80: 'Becquet Firmin Javel terracotta bust, 41 by 30 by 15 cm, inventory 90.',
81: 'Marcel Bloch pastel presumed Sarah Bernhardt, 32 by 37 cm; source biographical spelling/year discrepancies and presumed sitter remain evidence without authority assignment.',
82: 'Pauline Bouchardy young-woman pastel and pencil signed Bouchardi 1836; literal signature spelling retained.',
83: 'Brouardel Rue St Dominique watercolour inscribed 29 January 1910, 44 by 35.3 cm; Lisieux 06650001814 is a smaller board inscribed 28 January, a distinct sheet.',
85: 'Émile Béranger young-woman pastel signed 1847, 59 by 44.5 cm; distinct from Bouchardy 1836 portrait.',
86: 'Greux Castel Gandolfo etching explicitly engraved 1903 after Corot; Louvre circa 1865 painting and earlier oil study are separate objects.',
87: 'Cain ducks and frogs bronze figurine, 10 by 11.5 by 7 cm, signed Cain; former Mène attribution remains historical evidence.',
88: '1854 Sarret de Grozon communion commemorative sheet, with lithograph and ink inscriptions; source drawing classification and literal print medium both preserved.',
89: 'Gengembre/Cicéri nineteenth-century equestrian lithograph after de Dreux, reclining greyhounds; distinct composition from running-greyhounds companion.',
90: 'Eighteenth-century Delft polychrome plate, diameter 23.5 cm; uncertain DB mark reading C. de Berg preserved without stronger attribution.',
91: 'Levachez/Duplessi-Bertaux Pichegru etching, source 1801 with year-ten inscription; French republican date wording retained verbatim.',
92: 'Nineteenth-century Chalcographie du Louvre Ecce Homo impression after Van Dyck; seventeenth-century plate/model and Vorsterman completion remain separate history.',
93: 'Déchelle Arbois valley oil on cardboard before 1925, 56 by 73 cm; distinct from larger autumn landscape canvas.',
95: 'Paul Dubois Pasteur plaster bust, 53 cm high, inventory 113; surname-only Fernand Dubois portrait leads are different makers and subjects.',
96: 'Réveil nineteenth-century etching after Dürer retable drawing, 15.2 by 21.2 cm; not the larger sixteenth-century original drawing.',
97: 'Anonymous engraving after Edelfelt Pasteur, explicitly published 1 June 1886; reproduced 1885 signature belongs to the oil model.',
98: 'Alix Pichegru print after Alexandre-Evariste Fragonard, first quarter nineteenth century; father Jean-Honoré portrait leads are different works.',
99: 'Engelmann lithograph of a proposed Pichegru monument after Fragonard, 41.5 by 24.2 cm, inventory 16; source notes a related impression A2009.0.75 without adding it.',
100: 'Anonymous seventeenth-century fruit and sweets wood panel after Flegel, 64.1 by 49.3 cm; Antwerp assembly marks and former possible Daniel Soreau attribution retained.',
101: 'Coindre nineteenth-century Poligny reconstruction print; source explicitly flags contradiction between the supposed Frère Luc model and 1550. The physical print date is retained independently.',
102: 'Noël/Giraud first Manon meeting lithograph published 5 May 1844, 48.9 by 38.1 cm; one scene distinct from St Sulpice companion.',
103: 'Noël/Giraud Manon St Sulpice lithograph published 5 May 1844, 55.6 by 43.4 cm; companion, not duplicate of first meeting.',
104: 'Pointurier Atala lithograph of 1835 after Girodet; Louvre 1808 painting and Croneau canvas copy remain separate.',
105: 'Giroux Amazones colour lithograph mounted on cardboard; Sabatier/Cattier inscriptions retained and searched, one sheet with source nineteenth-century period.',
107: 'Gengembre/Cicéri equestrian lithograph after de Dreux with running greyhounds, inventory 241; distinct from reclining-greyhounds inventory 242.',
108: 'Grolleron watchman pen drawing, 29.5 by 16.5 cm; different from Brauner 1962 oil with the same short title.',
109: 'Jean-Louis Grégoire En avant bronze statuette, 52.5 cm high; companion La charge is a separately referenced object, and Forain print is unrelated.',
110: 'Uncertain Paulin Guérin Dame de Sarret attribution from faded signature; source reversed framed/unframed dimensions remain literal evidence, not silently fixed.',
112: 'Hamm Oswald de Bommarchand pastel, source 1850, 54 by 43 cm; incomplete maker lifespan stays incomplete.',
113: 'Martinet Homer burin engraved 1877 after Ingres 1827 painting; short inventory collision with Ingres Napoleon drawing is unrelated.',
114: 'Avril Coriolan and Véturie engraving dated 1790 after Le Barbier; original painting and literal dimension inconsistencies remain separate evidence.',
115: 'Nineteenth-century Chalcographie impression of half a cut Massacre des Innocents engraving after Le Brun, 68 by 46.7 cm; later physical impression is separate from Loir’s older plate and original painting.',
116: 'Daubigny nineteenth-century Ponte Molle mezzotint after Claude drawing; inventory-token overlap with Rousseau sandpit oil is unrelated.',
117: 'Marvy Bracciano mezzotint after Claude, 26.5 by 33 cm, inventory 19.38; related lighter pendant remains separate.',
118: 'Leroy St Jerome mezzotint after a drawing copied from Perugino; original attribution and uncertain model period retained without promoting the print to an original.',
119: 'Anonymous nineteenth-century St Bruno Chalcographie burin after Le Sueur drawing; inventory overlap with Courbet Ornans landscape is unrelated.',
120: 'Leclerc nineteenth-century illustrated Jura map with landscape, portrait medallions and regional still life, one decorative print from Atlas National Illustré; cartographic subject retained.',
121: 'Grégoire/Deneux Delort lithograph after Alexandre Legrand, 30 by 25 cm; no inference from unrelated Louis Legrand portraits.',
122: 'Gustave Lévy Lamartine impression dedicated by the sitter to Arbois library, source before 1869; literal Maurice Leloir model attribution retained with its biographical uncertainty.',
123: 'Solange Lardier snow near Pontarlier oil on hardboard before 1935; literal dimension reversal preserved, and short 400 collision with Maillaud Rollinat is unrelated.',
124: 'Masson Dead Christ etching and burin engraved 1875 after Ribera; conflicting model-period commentary is retained without changing this explicit print date.',
125: 'Leroy nineteenth-century Judith mezzotint after Mantegna drawing, 39 by 29 cm; not the fifteenth-century original.',
126: 'Daniel Marot seventeenth-century Besançon battle engraving, 62 by 57 cm; 6 May 1674 is the represented siege date, not a newly inferred exact execution.',
127: 'Jacque pastoral etching signed 1862 after an uncertain van der Meer model; model identity remains explicitly qualified.',
128: 'Dole siege engraving after van der Meulen with Hurtenburg/Boudewyns signatures, circa 1685; depicted 1668 campaign is not execution date.',
129: 'Boudewyns Salins siege print after van der Meulen, one wide seventeenth-century impression; not Versailles oil battle paintings.',
130: 'Gray siege print after van der Meulen, source circa 1685 and 1685 publication inscription; separate from Dole and Salins.',
132: 'Leroy nineteenth-century Virgin and Child burin after Michelangelo drawing; tentative relation to Medici statue retained as source context.',
133: 'Monsaldy French Army Triumph etching, first quarter nineteenth century, one decorated sheet with generals around a map.',
134: 'Victor Maire Julien Guillon charcoal portrait signed 1852, with Pointelin dedication to Arbois; sitter and donor are not assigned as artists.',
135: 'André Marchand Eléonor Lacroix pastel on paper mounted wood, 48.3 by 30 cm; source nineteenth-century date and later school label retained without inferring a precise year.',
136: 'Hector Allemand Rhône graphite and white chalk drawing dated 1863, 21.7 by 33.4 cm; not the 1869 quay oil panel.',
138: 'Question-mark Jules Robert Auguste Arab-chief-head watercolour before 1850; Monsieur Auguste alias and uncertainty remain literal.',
139: 'Bellenger landscape pencil sheet signed 1867, 28 by 40.3 cm; album history describes this individually inventoried sheet.',
140: 'Bourdelle Isadora Duncan seen from back, 1911 pen drawing, 26.1 by 17.9 cm; distinct from larger dancing watercolour and flower drawing.',
141: 'Castelnau Ceprano graphite landscape inscribed 9 October 1853, 20 by 41 cm.',
142: 'Chaplin girl entering a stream watercolour before 1891, 35 by 27 cm; distinct pose from other Chaplin figure sheets.',
143: 'Coronat mail players sanguine and white chalk drawing before 1897, 29.5 by 43.7 cm.',
144: 'Courdouan Africa graphite and white chalk drawing dated 1849 and dedicated to Canonge, 12 by 16.9 cm.',
145: 'Caillebotte Madame X pastel signed 1878, 63 by 50 cm; unidentified sitter stays unknown, separate from Daurelle portraits and oil canvases.',
146: 'Caruelle d’Aligny Sorrento ravines pen drawing inscribed 18 August 1834, 78.2 by 57.5 cm.',
147: 'Courbet François Sabatier black-pencil portrait before 1873, 34.5 by 26.8 cm; distinct from other named sitters in oils.',
148: 'Doumenjou Alfred Bruyas as child pencil/watercolour dated 1835 at Sorèze; maker name not expanded.',
149: 'Doze Holy Family graphite drawing dedicated to Canonge in 1856, 18 by 27.6 cm; one religious study.',
150: 'Eymar nude warming herself, sanguine and watercolour before 1944, 21 by 29.4 cm.',
151: 'Paul Flandrin grotesque pen sheet dated 1851, 18.2 by 13.3 cm.',
153: 'Harpignies Morvan autumn watercolour dated 1868, 30.4 by 22 cm; distinguished from oil landscapes and later autumn titles.',
154: 'Jalabert Italian woman watercolour/gouache signed C.J. 1846, 12.3 by 16.7 cm; other makers’ same-title objects are unrelated.',
155: 'Laprade Alyscamps watercolour before 1931, 38.7 by 27.8 cm; not a generic countryside-rest composition.',
156: 'Joseph Latour wild-pine pencil study signed 1839, 55 by 46 cm; distinct from Carlone oil and Fantin-Latour prints.',
157: 'Bonaventure Laurens rocks watercolour signed 1837, 23.6 by 30.9 cm; not rock studies by Brascassat, Bodinier, Brun or Moreau.',
158: 'Jules Laurens young-woman sanguine/black-pencil drawing dedicated to Bruyas, Rome 1846, 36 by 26.6 cm.',
159: 'Jules Laurens small graphite drawing after Bonvin poor bench, circa 1865, 10 by 6.5 cm; 54 by 37 and 1864 in inscription describe the model.',
160: 'Marilhat Hakim mosque graphite preparatory drawing, 29.3 by 46.3 cm; Louvre RF 184 is an 84.5 by 130.7 cm oil canvas confirmed in saved primary evidence.',
161: 'Millet La Bouillie black-pencil and white chalk drawing before 1875, 36.5 by 29.9 cm; existing 1861 impressions are prints, not this drawing.',
162: 'Charles Node Cévennes gorge watercolour signed 1882, 79.7 by 67.2 cm.',
163: 'Puvis bearded-man profile black-pencil drawing, 38.1 by 27.5 cm, inventory 899 3 1; distinct dimensions from other Puvis portraits and different maker from Picasso exact-title sheet.',
164: 'Papety blessing Christ pencil/brown wash study dated 1835, 44 by 24.5 cm; paternal inscription retained, no additional creator invented.',
165: 'Ribot seated old woman pen and watercolour, 11.5 by 9.3 cm, dedicated to Biguin; not the larger oil portraits.',
166: 'Jules Salles Arlésienne pastel signed at Arles in 1845, 23.4 by 18.7 cm.',
167: 'Sigalon Cupid drawing bow pen study before 1837, 20.5 by 13.5 cm; Canonge initials refer to provenance, not maker.',
168: 'Tassaert Bible-reading black-pencil drawing signed 1851, 22 by 25.3 cm.',
169: 'Traviès cabaret watercolour signed 1854, 25.3 by 19.1 cm; not Moormans large 1885 oil panel.',
170: 'Henri Usquin Spanish-street pen and watercolour, nineteenth century, with respectful dedication to Madame Bouisson.',
171: 'Anonymous Alps pencil and watercolour inscribed 10 December 1869; no maker inferred from travel note.',
172: 'Allemand Ain pen and wash drawing signed 1870, dedicated to Bruyas, 23.5 by 33.2 cm; Carrand 1880 canvas is different.',
173: 'Bourdelle Duncan dancing watercolour signed 1911, 54.8 by 37.2 cm, inventory 51 4 5; one large sheet distinct from two smaller pen drawings.',
174: 'Castelnau river drawing in pencil and white chalk, 1854, 26 by 64.7 cm; St Michel inscription retained.',
175: 'Chaplin girl plucking a daisy watercolour before 1891, 33 by 21 cm; different pose, inventory and dimensions from stream and sleeping-woman sheets.',
176: 'Courdouan Africa pastel dated 1850 and dedicated to Canonge, 25 by 34.5 cm; separate from 1849 graphite landscape.',
177: 'Doze Saints Philip and Bartholomew graphite drawing signed and dated 1864, 30 by 17.9 cm; two saints on one sheet.',
178: 'Eymar woman at toilette watercolour before 1944, 28.2 by 19.6 cm; unrelated same-title objects by other makers remain separate.',
179: 'Paul Flandrin draughtsmen pen drawing inscribed 24 November 1851, 18.4 by 14.8 cm.',
180: 'Harpignies woman walking in a wood watercolour dated March 1869 and dedicated to Dr Paulet, 16.3 by 13 cm.',
181: 'Bonaventure Laurens young Bouisson brown-wash portrait signed 1840, 16.4 by 20.3 cm.',
182: 'Jules Laurens Auvergne interior pencil and watercolour signed 1859, 45.4 by 35.9 cm; not Jean-Pierre Laurens 1907 interior.',
183: 'Marilhat méharistes graphite on canvas, 32 by 40 cm; close-size Clermont-Ferrand Halte d’arabes 978.10.1 is oil on canvas in saved primary evidence, a separate version.',
184: 'Puvis adult and young-man head studies on one squared black-pencil sheet, 36.8 by 40.7 cm, 899 3 2.',
185: 'Papety Via Gregorio graphite and blue-wash drawing dated August 1838, 33 by 45 cm.',
186: 'Allemand Beaunand valley drawing signed 1872; title’s 1831 describes the represented view and is not substituted as execution year.',
187: 'Bourdelle Duncan dancing with flowers pen drawing, 1911, 21.1 by 13.9 cm, 51 4 6; distinct from back-view and large watercolour.',
188: 'Castelnau Vidourle pencil drawing, 29.9 by 45.7 cm; source third-quarter-century period retained alongside May 56 inscription.',
189: 'Chaplin sleeping young woman watercolour before 1891, 46.5 by 33.1 cm; different medium/maker from Corinth oil and Gromaire ink sheet.',
190: 'Eymar round-hat girl black-wash drawing before 1944, 34.5 by 25.5 cm.',
191: 'Paul Flandrin Hippolyte portrait pencil drawing signed 1873, 32.9 by 25 cm; not Hippolyte’s oil self-portraits or paired portraits.',
192: 'Harpignies river and mountainous-horizon watercolour dated 1871, 24 by 33 cm; National Gallery NG2256 is a 21 by 23.2 cm oil canvas in saved primary evidence.',
193: 'Bonaventure Laurens Georges d’Albenas sanguine portrait signed 1856, 26 by 19.1 cm.',
194: 'Jules Laurens cat Mamette violet-ink drawing inscribed 1879, 7.3 by 6.3 cm.',
195: 'Puvis old-woman-head study for Panthéon Geneviève decoration, black pencil 30.7 by 23 cm; not the fresco, smaller head sheet or narrower figure studies.',
196: 'Papety Forum graphite and blue-wash view dated April 1839, 26.1 by 42.2 cm; separate from other artists’ Forum views.',
197: 'Allemand Grangeau view pen and wash dated April 1873, dedicated to Bruyas; 68 in inscription retained as context, not a creation year.',
198: 'Bourdelle dying-centaur pen and blue-wash study circa 1912, 49.2 by 60 cm; a preparatory sheet for theatre decoration, not the fresco itself.',
199: 'Castelnau Lez landscape pencil and white chalk inscribed June 1856, 23 by 44.5 cm.',
200: 'Eymar society conversation pen and black-wash drawing before 1944, 25.1 by 32.5 cm.',
201: 'Anonymous Kirino Toshiaki battle-death woodblock print, last quarter nineteenth century, one 36.5 by 24.5 cm sheet; maker remains unknown.',
202: 'Adachi Ginkō Nakamura Shikan as Tadanobu Rihei woodblock print of 1874, 23.9 by 34.4 cm; actor and role are subjects.',
203: 'Yōshū Chikanobu flower-watching print of 1896, one surviving 23.6 by 35.6 cm sheet of an incomplete triptych; complete QAG comparison is not this object.',
204: 'Morikawa Chikashige celebrity gathering of 1881, complete triptych under one inventory, 74.9 by 34.7 cm; signature Morikawa Otojirō preserved.',
205: 'Chinsai Rosetsu Port Arthur battle print of 1904, one surviving 25.9 by 37.5 cm sheet; incomplete triptych status retained.',
206: 'Endō Kyōzō Yamato-e landscape print, first half twentieth century, one 39.7 by 28.3 cm sheet from the eight-views series.',
207: 'Ogata Gekkō Agemaki Genji print of 1893, 21.8 by 34.6 cm; one chapter image, not all fifty-four.',
208: 'Tsukioka Gyokusei Shidō hōgaku print of 1927, signed Kōbun, 37.5 by 25.6 cm; different maker/composition from Yoshitoshi records sharing Tsukioka.',
209: 'Hasegawa Chikuyō Kanmangafuchi print of 1880, 16.1 by 21 cm; single image from twelve Nikkō views.',
210: 'Current source explicitly identifies Hasegawa Sadanobu III for Tamaori hime, second quarter twentieth century; previous index omitted III. Current literal generation retained with original evidence.',
211: 'Hasegawa Sadanobu I circa 1858 Fukagawa lumber-yard cut harimaze fragment, 11.3 by 10 cm; only the surviving fragment is catalogued.',
212: 'Hasegawa Sadanobu II tiger/rabbit actor print, late nineteenth century, 23.6 by 35.6 cm; Nakamura Komanosuke is the actor, not maker.',
213: 'Nakazawa Hiromitsu Miho Fuji print of 1907, 24.9 by 15.2 cm with separate mount dimensions; one of twelve series views.',
214: 'Ishida Gyokuzan Harumichi no Tsuraki poet print, first half nineteenth century, 16.8 by 25.7 cm; medieval poet biography is subject context.',
215: 'Kajita Hankō Young Warrior print of 1901, 31.4 by 22.3 cm.',
216: 'Kamisaka Sekka Kaminari woodblock print of 1910 from Momoyogusa, 44.8 by 29.8 cm; distinct from silk hanging-scroll leads.',
217: 'Katsukawa Shuntei Fuji hunt, first quarter nineteenth century; two surviving sheets of an incomplete triptych form one catalogued unit, damage retained in evidence.',
218: 'Kawabata Gyokushō Fukujin Noh/Kyōgen print of 1882, 25.2 by 18.4 cm; single book-series image.',
219: 'Kawanabe Kyōsai marital-proverbs print, source second half nineteenth century, 12.3 by 18.3 cm; distinct from wash demon drawings.',
220: 'Kyōsai Ōtsu-e games print, late nineteenth century, 12 by 18 cm; source 1831/1832 birth discrepancy retained without artist-authority changes.',
221: 'Kikugawa Eizan beauty with fan, first quarter nineteenth century, 24.3 by 35.9 cm; series-level title retained for this individual mounted sheet.',
222: 'Kinoshita Hironobu I Yoshiwara print, third quarter nineteenth century, 19.7 by 26.2 cm; literal generation retained.',
223: 'Kitamura Hōkoku Bizen-ya dance print, late nineteenth century, 51.4 by 37.4 cm; historical 1794 fire does not date this object.',
224: 'Kobayashi Eitaku Kagoshima print of 1877, two surviving sheets 49.7 by 36.6 cm, incomplete triptych retained as one catalogued unit.',
225: 'Kobayashi Ikuhide Pungdo victory print of 1894, complete triptych 69.2 by 35.8 cm mounted on calligraphy paper; one composition.',
226: 'Kobayashi Kiyochika Shizuka dance history print of 1883, 23.5 by 33.3 cm; medieval dancer dates are not object creation.',
227: 'Konishi/Gosōtei Hirosada Suikoden actor print of 1847, 11.8 by 16.9 cm; source format name and measured size retained without correction.',
228: 'Tsukioka Kōgyo Himuro Noh print of 1899, 35.8 by 24.2 cm; different artist and play from Yoshitoshi comparison leads.',
229: 'Ogata Gekkō Sino-Japanese victory print of 1894, complete triptych 72.9 by 37 cm; poor condition does not create extra objects.',
230: 'Twentieth-century physical copy of an Edo-period Eiri composition, 25.2 by 37.8 cm; derived after-label explicitly preserves the copy relationship and source first-half-twentieth-century date.',
231: 'Shibata Zeshin flower-comparison print of 1880 depicting a wagashi box, 25.7 by 19.1 cm; Model Boat–Hana Kurabe is a different image in the series.',
232: 'Shōtei Hokuju Futami beach print, early nineteenth century, 2023.1.19; current title ordering retained, no conflation with Takahashi Shōtei or other museums’ impressions.',
233: 'Nakamura Shūkō Haiyang naval victory print of 1894, complete triptych 72.4 by 37.2 cm; several ships are subjects within one work.',
234: 'Suga Tatehiko loyal-servant sword-forger print, first quarter twentieth century; missing dimensions stay unknown.',
235: 'Nakayama Sūgakudō dusky thrush, peas and broccoli print of 1859, 24.3 by 36.5 cm; literal translated series label retained.',
236: 'Taguchi Beisaku Haicheng snow-battle print of 1895, one surviving 23.7 by 35.6 cm sheet of incomplete triptych.',
237: 'Takagi Yasunosuke Kegon waterfall woodblock of 1928, 39.2 by 27.8 cm; one view from the series.',
238: 'Takahashi Tasaburō Chion temple monochrome print of 1955, 14.9 by 13.2 cm; artist death after 1970 does not exclude the work.',
239: 'Takeshita Kin’u New Year Edo scene, first half twentieth century, 42.1 by 28 cm; depicted Edo period is not the print date.',
240: 'Takeuchi Seihō shrimp drawing-guide plate, first half twentieth century, 26.8 by 18.8 cm; original versus 1935 reissue remains unknown within the documented period.',
241: 'Fujikawa Tamenobu Fukuroi print of 1918, 33.9 by 22.5 cm; older Hizakurige novel dates are subject context.',
242: 'Taniguchi Tōsen Tōru Noh print of 1919, 28.7 by 21.2 cm; current series-title wording retained with older index evidence.',
243: 'Terasaki Kōgyō festive-boat night print, first quarter twentieth century, 22.3 by 29.2 cm; 1911 publication note retained without narrowing the source period.',
244: 'Tokuriki Tomikichirō Hongan-ji print, second quarter twentieth century, 28.2 by 21.5 cm; later artist death is not a creation cutoff.',
245: 'Jinbo Tomoyo Prince Daibi series image of two people preparing tea, one monochrome 1965 sheet, 31 by 23.5 cm; scroll-series title does not imply a whole scroll.',
246: 'Torii Kiyosada Okina dance print of 1897, 23.4 by 35.9 cm; single theatre-calendar image.',
247: 'Torii Kiyosada and source-labelled Kiyotada IV Kamahige print of 1895, with two explicit signatures; source link’s alternative VII numbering retained only as evidence.',
248: 'Source-labelled Torii Kiyotada IV Onoe Kikujirō III death portrait of 1919, 25.9 by 38.4 cm; performer’s death date identifies the commemorative subject.',
250: 'Toyohara Chikayoshi imperial dance print of 1879, complete triptych 74.8 by 37.3 cm; signature supports literal Chikayoshi, source’s Chikashige biography link remains a discrepancy.',
252: 'Kunichika and Hiroshige III Fuchū Teranishi Kanshin print of 1867, 24.1 by 35.9 cm; signatures distinguish figure and landscape hands, no mapping to Hiroshige I.',
253: 'Tsukioka Kōgyo Daibutsu Kuyō Noh print, second quarter twentieth century, 34.4 by 25.5 cm; separate play and generation from other Tsukioka leads.',
254: 'Tsukioka Kōun Kusazuri-biki print of 1899, 25 by 36.5 cm, signed 耕耘; not Kōgyo or Yoshitoshi.',
255: 'Morizumi Tsurana miniature-portrait series print, nineteenth century, one 20.9 by 33.4 cm sheet; pasted cartouche is not another artwork.',
256: 'Tsutsui Toshimine Hagi no tsuki print of 1905, 30.3 by 22.5 cm; periodical publication context retained.',
258: 'Source-labelled Hiroshige II Futagawa print, third quarter nineteenth century, 16 by 20.9 cm; comparable Minneapolis Hiroshige I impressions have separate accession identities and earlier dates.',
259: 'Hiroshige III Sumida flowering-dike print of 1881, one surviving 25.4 by 37.4 cm sheet from an incomplete triptych.',
260: 'Hiroshige III Noto sōmen production print of 1877, 24 by 17.7 cm; one regional-products series sheet, distinct from Kunisada mochi imagery.',
261: 'Utagawa Kokunimasa Asan battle print of 1894, one surviving 24.7 by 37 cm sheet of incomplete triptych; ship construction dates remain subject context.',
262: 'Utagawa Kuniaki II Yasukuni imperial excursion print of 1880, complete triptych 70.9 by 35.2 cm, signed Hachisuka Kuniaki.',
263: 'Utagawa Kunimasa IV/Baidō Hōsai lion Kabuki print of 1894, complete triptych 71 by 36.4 cm, signed Kōchōrō Hōsai.',
264: 'Utagawa Kunisada II Hanachirusato Genji-card print of 1857, 25.6 by 37 cm, signed Baichōrō Kunisada; no merge with Kunisada I series sheets.',
265: 'Utagawa Kunisada III dragon-palace jōruri print of 1891, complete triptych 70.3 by 35.8 cm; five actors constitute one theatrical composition.'
}
INVENTORY_EXCEPTIONS = {
62: {'bd9af131-cd82-5ee5-ab1b-2f5ca4f989f6'},
113: {'a8c327bc-fd59-4b1e-80dc-81d660e04b35'},
116: {'42b32ea8-8c45-4df7-9912-3e269f33ce6b'},
119: {'312bca39-37b5-4701-9a16-dc893f6b9da5'},
123: {'8a971b8b-85db-4883-acca-9b72d9760451'}
}
UNTITLED_EXCEPTIONS = {}
QUALIFIED = {230: ('Rekisentei Eiri (actif 1790-1800) (d’après)', 'Description')}
