"""Complete comparison-only translations for named anonymous Pisa portraits."""
import importlib.util,json
from pathlib import Path
z=importlib.util.spec_from_file_location('base_supplement',Path(__file__).with_name('museum-expansion-italy-third-supplement-20261008.py'));base=importlib.util.module_from_spec(z);z.loader.exec_module(base)
i=base.i;m=base.m;RUN=base.RUN;ref=base.ref;checked=base.checked
MORE={406:['Portrait of Countess Caterina Closent'],407:['Portrait of Marchioness Aurora Zabarelli'],410:['Portrait of Baron Mariano da Scorno'],411:['Portrait of a Girl in a Red Dress'],412:['Portrait of Benevieni da Scorno'],413:['Portrait of Francesco Maria del Testa'],414:['Portrait of a Court Lady in a Red Cloak'],415:['Portrait of a Court Lady in a Blue Cloak'],416:['Portrait of Claudia de Medici'],417:['Portrait of Cosimo II de Medici'],418:['Portrait of Margherita de Medici'],419:['Portrait of Violante of Bavaria'],421:['Portrait of a Lady with Fruit'],422:['Portrait of Eleonora Gonzaga of Guastalla'],423:['Portrait of Cosimo III de Medici'],424:['Portrait of a Spanish Prince'],425:['Portrait of Princess Sophia Dorothea'],426:['Portrait of a Lady with a Walking Stick'],427:['Portrait of a Lady with Flowers'],429:['Portrait of Marie Louise of Austria'],431:['Portrait of Maria Carolina of Austria'],432:['Portrait of Ferdinand IV of Bourbon'],435:['Portrait of Alessandro Del Testa'],436:['Portrait of Jacopo Giuseppe Del Testa'],437:['Apostle'],438:['Coat of Arms of Ferdinand II de Medici'],439:['Portrait of Peter Leopold of Lorraine'],440:['Portrait of Maria Luisa of Bourbon, wife of Peter Leopold'],447:['Portrait of a Girl as Diana'],448:['Lady with Fruit and Flowers'],449:['Baptism of Nazaradeol'],450:['Portrait of Ferdinando de Medici, son of Cosimo III'],451:['Portrait of Francesco Maria de Medici'],452:['Prophet'],453:['Saint John Drawing Water from a Spring'],454:['Saint Nun'],460:['Saint Writing a Book'],461:['Saint John the Baptist'],465:['Saint Elizabeth with a Crown'],468:['Portrait of Maria Luisa of Bourbon'],471:['Female Martyr Holding a Palm'],474:['Young Woman with a Blue Ribbon in her Hair'],475:['Young Man'],477:['Seated Young Woman'],478:['Portrait of a Man in Armour'],482:['Portrait of Mr and Mrs Del Testa'],483:['Portrait of Maria Magdalena of Austria in Mourning'],485:['Portrait of Christina of Lorraine'],486:['Portrait of Ferdinando II de Medici in Armour'],488:['Lady in a Red Dress'],489:['Portrait of Stanislaw Jablonowski'],493:['Portrait of Anna Quaratesi Dazzi'],496:['Burgundian Gentleman'],504:['Lady in a White Dress'],505:['Portrait of an Army General'],508:['Lady in a Blue Dress']}
for n,titles in MORE.items():base.TITLE_ADDITIONS[n]=sorted(set(base.TITLE_ADDITIONS.get(n,[]))|set(titles))
SELECTED=base.SELECTED;rows=base.rows;queries=base.queries;comparisons=base.comparisons
def main():
 dest=RUN/'selected-identity-004.json.gz';assert not dest.exists();rs=rows();params=i.params_for(rs)
 with m.connect() as db,db.transaction():
  db.execute('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ');state=queries(db,params)
  citations=[v['row'] for v in db.execute("SELECT to_jsonb(c) row FROM citations c WHERE entity_type='artwork' AND entity_id=ANY(%s::uuid[]) ORDER BY entity_id,id",(state['artwork_ids'],))]
 comps=comparisons(rs,state);old={v['number']:v for v in m.load(RUN/'selected-identity-003.json.gz')['comparisons']};delta=[]
 for c in comps:
  before={h['id'] for h in old[c['number']]['hits']};new=[h for h in c['hits'] if h['id'] not in before]
  if new:delta.append(dict(number=c['number'],new_hits=new))
 m.save(dest,dict(at=m.now(),rows=rs,params=params,state=state,comparisons=comps,new_comparison_hits=delta,script_reference=ref(Path(__file__).resolve()),base_script_reference=ref(Path(base.__file__).resolve()),previous_reference=ref(RUN/'selected-identity-003.json.gz'),policy='Search-only completed English titles; no catalogue titles or attributions changed.',read_only=True))
 m.save(RUN/'selected-citations-004.json.gz',dict(at=m.now(),identity_reference=ref(dest),citations=citations,read_only=True));print(json.dumps(dict(selected=len(rs),scope=len(state['artwork_ids']),new_pairs=sum(len(v['new_hits']) for v in delta),source_hits=sum(len(v['source_hits']) for v in comps))),flush=True)
if __name__=='__main__':main()
