"""Freeze wave84 evidence and retain the active all-museum goal."""
import csv,hashlib,importlib.util,json
from pathlib import Path
z=importlib.util.spec_from_file_location('a',Path(__file__).with_name('museum-expansion-ferens-apply-v3-20261009.py'));a=importlib.util.module_from_spec(z);z.loader.exec_module(a);m=a.m
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 dest=a.RUN/'delivery-checkpoint-001.json';assert not dest.exists();assert sha(a.CHECKPOINT)=='2dd3a398f4c0248a5c747409864859f81551984925033956198242fb2120d5b9';previous=m.load(a.CHECKPOINT);assert(len(previous['artifacts']),len(previous['external_artifacts']))==(30410,642)
 changes=m.load(a.RUN/'readme-supersessions-001.json')['changes'];changed={v['path']:v for v in changes};assert set(changed)=={str((m.RUN/'README.md').relative_to(m.ROOT))}
 for c in changes:
  assert sha(Path(c['backup_path']))==c['backup_sha256'];x=m.load(Path(c['backup_path']));assert hashlib.sha256(x['text'].encode()).hexdigest()==x['sha256']==c['before_sha256'];assert sha(m.ROOT/c['path'])==c['after_sha256']
 for dep in previous['artifacts']:
  if dep['path'] in changed:assert dep['sha256']==changed[dep['path']]['before_sha256']
  else:a.checked(dep)
 plan,digest=a.validate_plan()
 with m.connect() as db:verified=a.verify(db,plan,digest)
 assert verified['current_counts']==dict(linked=228,eligible=215) and verified['prior_campaign_records_preserved']==12378;assert m.load(a.RUN/(a.KEY+'-applied.json'))['plan_sha256']==digest;report=m.load(m.RUN/'verification-after-wave-84.json');assert(report['verified_new_artworks'],report['verified_existing_artworks_linked'],report['institutions_with_new_records_or_reconciled_holdings'])==(10395,2119,226)
 checks=m.load(a.RUN/'checks-001.json');assert(checks['new_offline_tests_passed'],checks['historical_tests_passed'],checks['cumulative_verified_tests'])==(23,1615,1638) and checks['replay_zero_writes'];audit=m.load(m.RUN/'after-wave-84.json');csvcounts={};ids=[]
 for name,count in [('added-artworks-after-wave-84.csv',10395),('reconciled-artworks-after-wave-84.csv',2119),('gac-date-enrichments-after-wave-84.csv',6),('museum-coverage-after-wave-84.csv',len(audit['institutions']))]:
  with(m.RUN/name).open(newline='') as fp:rows=list(csv.DictReader(fp))
  assert len(rows)==count;csvcounts[name]=count
  if name.startswith(('added-artworks','reconciled-artworks')):ids.extend(v['artwork_id'] for v in rows)
 assert len(ids)==len(set(ids))==12514
 external=previous['external_artifacts']+list(checks['logs'].values())+[dict(path=v['backup_path'],sha256=v['backup_sha256']) for v in changes]
 for path in sorted(m.BACKUP.glob(a.KEY+'-*.json.gz')):external.append(dict(path=str(path),sha256=sha(path)))
 reviewed=m.BACKUP/(a.KEY+'-reviewed-plan-003.json.gz');assert m.load(reviewed)==plan;proof=m.load(m.BACKUP/(a.KEY+'-transaction-identity-003.json.gz'));assert proof['state_equal'] and proof['citations_equal'];log=Path('/Users/vadimdulub/Library/Logs/artline-ferens-delivery-20261009.log');assert '"documented_new_records": 136' in log.read_text();external.append(dict(path=str(log),sha256=sha(log)));unique={}
 for dep in external:
  assert dep['path'] not in unique or unique[dep['path']]==dep;unique[dep['path']]=dep;assert sha(Path(dep['path']))==dep['sha256']
 a.checked(previous['other_job_status_reference']);paths={m.ROOT/v['path'] for v in previous['artifacts']}|{a.CHECKPOINT,Path(__file__).resolve()};paths|={v for v in a.RUN.rglob('*') if v.is_file()};paths|={v for pattern in ['*ferens*20261009.py'] for v in(m.ROOT/'ops').glob(pattern)};paths|={v for v in m.RUN.glob('*after-wave-84*')};artifacts=[a.reference(v) for v in sorted(paths)]
 assert len(m.load(a.RUN/'remaining-research-001.json.gz')['rows'])==44;nextq=m.load(a.RUN/'next-museum-pass-001.json');assert len(nextq['italian_museums'])==225 and len(nextq['existing_holding_review_targets'])==2 and not nextq['native_addition_targets'];availability=a.RUN/'source-availability-001.json';assert not m.load(availability)['new_source_access_holds'];captured=m.load(a.RUN/'native-captured-001.json.gz');assert len(captured['rows'])==180 and not captured['requests_stopped'] and not captured['unprocessed_numbers']
 result=dict(at=m.now(),goal_complete=False,local_only=True,new_additions=136,new_existing_links=0,campaign_new_artworks=10395,campaign_existing_links=2119,distinct_campaign_artwork_ids=12514,institutions_with_new_records_or_reconciled_holdings=226,verification=verified,museum_changes=report['ferens_museum_changes'],museums_below_100=report['after']['museums_below_100'],museums_below_200=report['after']['museums_below_200'],global_coverage_snapshot_at=report['global_coverage_snapshot_at'],external_registry_growth_reference=report['external_registry_growth_reference'],new_tests_passed=23,historical_tests_passed=1615,cumulative_verified_tests=1638,plan_sha256=digest,csv_counts_verified=csvcounts,artifacts=artifacts,external_artifacts=list(unique.values()),prior_checkpoint_reference=a.reference(a.CHECKPOINT),prior_artifacts_verified=len(previous['artifacts']),intentional_supersessions=changes,other_job_status_reference=previous['other_job_status_reference'],other_job_totals_separate=True,editorial_holds=44,review_reference=a.reference(a.REVIEW),remaining_research_reference=a.reference(a.RUN/'remaining-research-001.json.gz'),next_museum_pass_reference=a.reference(a.RUN/'next-museum-pass-001.json'),source_availability_reference=a.reference(availability),new_source_access_holds=[],new_source_access_hold_reference=previous['new_source_access_hold_reference'],prior_source_access_hold_reference=previous['new_source_access_hold_reference'],native_probe_reference=a.reference(a.RUN/'native-search-probe-001.json'),runtime=previous['runtime'],next_work='136 verified new native Ferens records:228 linked/215 eligible,preferred200 reached.44 source/attribution/date/version/duplicate cases retained. Two Russian School icons included. Initial HTTP holding URL transaction rolled back; exact native HTTP URLs remain evidence and verified official HTTPS collection landing page supplies holding source_url. No images or legacy edits. Campaign10395 new+2119 reconciled=12514 distinct records across226 institutions. Continue Salford and Guildhall existing holdings; retain225 Italian museums and every earlier queue/access hold. Three exact existing Hull accession identities201/203/204 need reconciliation and are not assigned to Streetlife by current DB evidence. Capture,apply,replay,audit,report and delivery workers terminal before checkpoint. Concrete136-record progress,not a repeated global blocker. Full100minimum/200preferred all-museum goal remains active.')
 m.save(dest,result);print(json.dumps(dict(checkpoint=str(dest.relative_to(m.ROOT)),sha256=sha(dest),artifacts=len(artifacts),external_artifacts=len(unique),new_records=136,campaign_new=10395,campaign_links=2119,below100=result['museums_below_100'])),flush=True)
if __name__=='__main__':main()
