"""Reviewed exact-code collection destinations; no institution merges or display claims."""
import hashlib,importlib.util,json
from pathlib import Path
s=importlib.util.spec_from_file_location('n',Path(__file__).with_name('museum-expansion-france-twelfth-native-20261008.py'));n=importlib.util.module_from_spec(s);s.loader.exec_module(n);m=n.m
CONTEXTS={
'M0189':dict(source='sens',city='Sens',names=['musée municipal'],locations=['Sens ; musée municipal'],owners=['Sens;musée municipal'],basis='Official Museofile M0189 identifies Sens municipal museum, also Musées de Sens. Require literal municipal owner and exact city/museum destination; archaeological society, state, cathedral and Louvre ownership remain distinct.'),
'M0601':dict(source='lavaur',city='Lavaur',names=['musée du pays de Cocagne'],locations=['Lavaur ; musée du pays de Cocagne'],owners=['Lavaur;musée du pays vaurais','Lavaur;musée du pays de Cocagne'],basis='Official M0601 explicitly records former Musée du Pays Vaurais and its definitive municipal status from 2002, with Musée de Lavaur as another name. Current code and location plus municipal/local-authority ownership ending in either documented name identify the same museum holding. Literal ownership wording retained. No claim of present display; current overview states permanent collections are not visible.'),
'M0550':dict(source='rodez',city='Rodez',names=['musée des beaux-arts Denys Puech'],locations=['Rodez ; musée Denys-Puech'],owners=['Rodez;musée Denys-Puech'],basis='Official M0550 names the Beaux-Arts Denys Puech museum in Rodez and explicitly uses Musée Denys-Puech in its collection history. The hyphenated short name on object destinations is this same exact code and city. Private Aveyron learned-society/Fenaille holdings and state deposits remain excluded.'),
'M0435':dict(source='isle-adam',city="L'Isle-Adam",names=["musée d'art et d'histoire Louis Senlecq"],locations=["musée d'art et d'histoire Louis Senlecq","L'Isle-Adam ; musée d'Art et d'Histoire Louis Senlecq",'L’Isle-Adam ; Musée Louis Senlecq',"L'Isle Adam ; Musée Louis Senlecq",'L’Isle-Adam ; Musée d’Art et d’Histoire Louis Senlecq'],owners=["L'Isle-Adam;musée d'art et d'histoire Louis Senlecq"],basis='Official M0435 explicitly supplies the short name Musée Louis Senlecq in L’Isle-Adam. Exact code, city and municipal collection ownership reconcile the museum-only location field. State, Pontoise, private, church and Foundation-de-France deposits are excluded; no transfer or current-display inference.'),
'M0706':dict(source='louviers',city='Louviers',names=['musée municipal'],locations=['Louviers ; musée municipal'],owners=['Louviers;musée municipal'],basis='Official M0706 explicitly identifies the municipal museum of Louviers. Require exact city and municipal museum owner destination; state and other museum deposits excluded. Collection holdings do not establish display; the overview reports that most permanent collections are not visible.')}
def main():
 dest=n.RUN/'museum-name-reconciliation-001.json';assert not dest.exists();x=m.load(n.DISCOVERY);targets={v['slug'].removeprefix('joconde-').upper():v for v in x['targets']};out={}
 for code,c in CONTEXTS.items():
  target=targets[code];stem=n.RUN/'museum-context-001'/(c['source']+'-museofile');text=stem.with_suffix('.txt').read_text();receipt=m.load(stem.with_suffix('.receipt.json'));assert receipt['status']==200 and code in text and m.norm(c['city']) in m.norm(text)
  assert all(m.norm(name) in m.norm(text) for name in c['names']);assert target['slug']=='joconde-'+code.lower()
  value=dict(c,institution_id=target['id'],owner_prefixes=['propriete de la commune']+(['propriete de la collectivite locale'] if code=='M0601' else []),evidence=[n.ref(stem.with_suffix(ext)) for ext in ['.txt','.html.gz','.receipt.json']],legal_title_claim=False,current_display_claim=False);out[code]=value
 m.save(dest,dict(at=m.now(),museums=out,discovery_reference=n.ref(n.DISCOVERY),reviewer_reference=n.ref(Path(__file__).resolve()),policy='Exact source museum code, city, names and municipal collection owner destinations. Holding only; no current-display claim, institution merge or legal-title determination.'))
 print(json.dumps({k:dict(name=targets[k]['name'],eligible=targets[k]['eligible_works']) for k in out}),flush=True)
if __name__=='__main__':main()
