"""Concrete reviewed selection and auth-dependent handoff; no catalogue mutation."""
import collections,csv,hashlib,importlib.util,io,json
from pathlib import Path
z=importlib.util.spec_from_file_location('a',Path(__file__).with_name('museum-expansion-kazantzakis-more-apply-20261009.py'));a=importlib.util.module_from_spec(z);z.loader.exec_module(a);m=a.m;RUN=a.RUN
news,holds=a.records();assert len(news)==105 and not holds
assert not a.PLAN.exists() and not(RUN/(a.KEY+'-applied.json')).exists()
log=Path.home()/'Library/Application Support/Artline/research-proofs/kazantzakis-more-20261009/offline-tests-001.log';assert 'Ran 20 tests'in log.read_text()and log.read_text().strip().endswith('OK')
def csvfile(name,rows):
 out=io.StringIO(newline='');w=csv.DictWriter(out,fieldnames=list(rows[0]));w.writeheader();w.writerows(rows);path=RUN/name;assert not path.exists();path.write_text(out.getvalue())
csvfile('proposed-production-artworks-001.csv',[dict(proposed_artwork_id=v['artwork_id'],institution_id=a.IID,source_id=v['facts']['source_id'],title=v['facts']['title'],creator_label=v['facts']['creator_label'],date_display=v['facts']['date_display'],work_type=v['facts']['work_type'],source_url=v['facts']['source_url'],intended_status='review',delivery_state='NOT_APPLIED')for v in news])
ds=a.r.build();csvfile('all-source-decisions-001.csv',[dict(number=v['number'],source_id=v['source_id'],title=v['facts']['title'],state=v['state'],reason=v['basis'],source_url=v['facts']['source_url'])for v in ds])
baseline=m.load(RUN/'production-initial-scope-001.json.gz');m.save(RUN/'checks-001.json',dict(at=m.now(),offline_tests_passed=20,offline_log_path=str(log),offline_log_sha256=hashlib.sha256(log.read_bytes()).hexdigest(),atomic_verification_passed=False,replay_zero_writes=False,production_apply_attempted=False,production_read_only_baseline_at=baseline['at'],last_verified_counts=baseline['counts'],production_auth_error='gcloud.secrets.versions.access: current auth token refresh failed; reauthentication required; cannot prompt during non-interactive execution.',missing_requirements=['Fresh full128record comparator snapshot','Live baseline and identity preflight','Pinned execution plan and prewrite backup','Successful CloudSQL backup','Atomic write and readback','Zero-write replay'],policy='Offline success proves candidate invariants only,not a production delivery. No additional credential search or access-control bypass. Real local catalogue remains read-only.'))
m.save(RUN/'pending-delivery-001.json',dict(at=m.now(),goal_complete=False,previous_goal_turn='progress',proposed_additions=105,actual_additions=0,actual_existing_links=0,source_records_reviewed=110,reference_images_seen=110,reproduction_holds=4,source_identity_holds=1,last_verified_museum_counts=dict(catalogue=118,date_eligible=112),conditional_after_counts=dict(catalogue=223,date_eligible=217),production_campaign_totals_unchanged=dict(new_artworks=920,existing_links=1,museums=7),last_successful_production_checkpoint=a.reference(a.CHECKPOINT),editorial_reference=a.reference(a.REVIEW),checks_reference=a.reference(RUN/'checks-001.json'),plan_exists=False,cloud_backup_created=False,write_attempted=False,local_mutation=False,auth_blocker_observed=True,consecutive_no_progress_turns=0,independent_research_continues='Kilkis source discovery in native/kilkis-20261010',remaining_kazantzakis_leads_reference=a.reference(RUN/'selected-index-leads-001.json.gz'),next_work='Restore Google Cloud authentication via gcloud auth login. Do not rerun immutable review/visual capture scripts. Run the comparator script,then apply prepare; if existing state differs,make a new reconciled version instead of overwriting evidence. Prepare a successfulCloudSQLbackup,apply exact planhash,verify,replay,and write new delivery/checkpoint artifacts with actual counts. Meanwhile continue official-sourceKilkis research without assigning leads as new production records.'))
(RUN/'README.md').write_text('''# Nikos Kazantzakis Museum — reviewed continuation, pending production access

**105 artworks are fully reviewed but not yet added.** The last verified production count remains **118 catalogue works / 112 date-eligible works**. Applying this selection after fresh checks would bring those counts to **223 / 217**, above the preferred 200-work target. No production write or cloud backup was attempted in this continuation.

- [105 proposed artworks](proposed-production-artworks-001.csv)
- [All 110 source decisions](all-source-decisions-001.csv)
- [Pending-delivery state](pending-delivery-001.json)
- [Checks and remaining requirements](checks-001.json)

The selection comprises 104 drawings and one mixed-technique scenery detail whose physical type remains unknown, dated by dedicated object fields to 1940–1941. All retain review status and the literal unknown creator label. The separate EKT enrichment naming Giorgos Anemoyannis remains unresolved. Two corrupted title fields are corrected from clean title text on the same object page, with original strings and HTML preserved.

All 110 selected thumbnails were inspected, including 12 enlarged comparisons. Four records are explicit reproductions: **35035,35036,35037,35032**. Their production dates do not establish the copies’ creation dates. Copies35036 and35037 report their originals at ELIA; the visually distinct studies35057 and35056 are separately documented museum objects, not those originals. Record**35062** remains held because its Emma17 description conflicts with a jester-like thumbnail. Separate costume versions are distinguished by contours,pose,support and annotation. Reverse sketches,attached fabric samples,cut-paper proscenia and diptych panels remain one physical artwork. Source NC/ND labels are preserved; thumbnails are internal identity references, with no production image attachment.

The completed read-only identity check examined 128 existing artwork records and149citations, including all118museum works and10translated-title comparators. It found no exact source identities. The later full-row comparator snapshot could not run because Google Cloud token refresh requires reauthentication. No existing metadata,dates,images,statuses or holdings were changed. The real local database remains read-only.

Twenty offline regression tests passed. This is evidence for selection and preservation logic, not a successful delivery or a ten-million-row load test. The production phase remains920new artworks andoneexisting-work link acrosssevenmuseums. This pending selection is not included in those totals.

After `gcloud auth login` restores access, run `ops/museum-expansion-kazantzakis-more-comparators-20261009.py`, then `ops/museum-expansion-kazantzakis-more-apply-20261009.py prepare`. The preparation must recheck the live museum baseline,all128comparators,and921priorcampaignrecords. If state changed,create a reconciled new version; do not overwrite pinned evidence. A successful CloudSQL backup and pinned execution plan must precede atomic application. Verify the committed rows and a zero-write replay before issuing a delivery receipt or updating museum counts.

Do not rerun the original review main function: it produced institution and visual artifacts before stopping at the missing comparator snapshot. `museum-expansion-kazantzakis-more-review-complete-20261009.py` finished the immutable editorial artifact from those results without claiming a production snapshot. No execution plan exists yet.

The selected index manifest retains one further candidate from page6; additional archive pages were not fetched. Once this selection is applied,the museum has passed200 and attention can move to other institutions. Official-source research for the Archaeological Museum of Kilkis has begun in the adjacent `kilkis-20261010` directory while production authentication is unavailable. The full every-museum goal remains active.
''')
print(json.dumps(dict(proposed=105,actual_added=0,tests=20,last_verified=baseline['counts'],auth_required=True)),flush=True)
