"""Object-level holding decisions; preserve ownership, chronology and catalogue fields."""
import collections,importlib.util,json,re
from pathlib import Path
z=importlib.util.spec_from_file_location('x',Path(__file__).with_name('museum-expansion-verbania-identity-20261008.py'));x=importlib.util.module_from_spec(z);z.loader.exec_module(x);s=x.s;m=s.m;RUN=s.RUN;IID=s.IID;ref=s.ref;checked=s.checked
HOLDS={18:'Broad 1887–1953 period overlaps the existing Albertini winter landscape of1931; the present short source description cannot independently distinguish the physical support.',75:'Questioned summer title and1930 overlap an existing broad-dated Cascella autumn landscape; available descriptions do not resolve physical identity.',106:'The broadly dated mountain hut may be distinct from the circa1895 flock in a mountain rainstorm, but the brief target description cannot exclude an alternate title.',117:'Literal source date19346–1946 is malformed. Do not invent a correction.',133:'Literal source date1953–19453 is malformed. Do not invent a correction.',145:'Cinotti snow landscape has only a short description; the existing Laghestel record has conflicting broad dates. Physical identity needs more evidence.'}
NOTES={
2:'Tozzi composition1963 OA598 differs from the1965 man in a blue jacket.',17:'Gignous Lombard plain1871 precedes the returned lake, spring, winter and Valmaggia landscapes, all dated1885 or later.',23:'Tominetti path with people1910 differs from the circa1895 rainstorm and flock.',26:'De Stefani chrysanthemums1918 differ from the1889 Lisa figure with flowers.',32:'Federico Ashton is distinct from returned Luigi Ashton and Will Ashton records.',35:'Funi depicts Mario Tozzi1929, not Nino Zucchelli or a self-portrait1948.',36:'The source names Lake Marjelen; the other source names Foscagno Pass. Distinct named geographical compositions and catalogue objects.',39:'Arturo Martini1939 is distinct from Alberto Martini1899 dwarf drawings.',41:'Tozzi morning toilette1922 differs from the1965 stylized man.',46:'Tozzi Testina1970 OA600 differs from the1965 composition; exact1970 is within scope.',47:'Tozzi still life1955 OA596 differs from Visione metafisica1930.',59:'Tozzi La grande piazza1962 differs from Visione metafisica1930.',62:'Arturo Martini mother and child1944 is distinct from Francesco di Giorgio Martini, Simone Martini and Alberto Martini records.',73:'Dudreville names Mr Trincheri1953, distinct from the circa1920 Mr Dudreville portrait.',80:'Arturo Martini Siesta1946 differs from Simone Martini Maesta1321.',88:'Arturo Martini green landscape1946 is distinct from Alberto Martini landscapes.',89:'Bossoli Fraccia OA196 is oil on cardboard. Returned Bossoli landscape records describe pencil/pen drawings on paper, not this support/technique.',98:'Bossoli Arona OA195 is oil on cardboard, distinct from pencil/pen drawings on paper and from Fraccia OA196.',105:'Ranzoni questioned1863 woman precedes the circa1880 watercolor portrait; source uncertainty preserved.',112:'Tozzi still life1945 OA593 differs from1930 Visione metafisica and other separately inventoried1945 compositions.',124:'Cinotti questioned1907 Marina precedes the returned post1915–1920 country landscape; questioned date remains unknown.',130:'Tozzi mandolin1945 OA594 is a specific still-life composition, separate from OA593,OA595 and Visione metafisica1930.',132:'Arturo Martini calf1939 differs from Alberto Martini Paganini1907.',136:'Ranzoni Giuseppina Imperatori Orsenigo1877 is oil on canvas; the circa1880 unnamed woman is expressly watercolor in its primary description.',152:'Tozzi head and egg1945 OA595 is a specific still life, distinct from the mandolin, other still life and Visione metafisica1930.'}
COMMON='Exact national-catalogue object identifier resolves solely to this existing artwork. Literal title/subject, named creator and date agree. One current-location node identifies the exact Verbania museum URI, site and city. Private ownership is distinct from the documented museum holding. Unique museum OA inventory identifies one physical object.'
LIMIT='Editorial confidence, not calibrated probability. Evidence captured5 October2026; no fresh display claim or legal-ownership inference. All existing dates, unknowns, creator labels, attributions, images and historical review status preserved. No new artwork or painter authority.'
def facts(r):
 g=s.graph(r);root=g[r['root']];a=r['artwork'];aid=a['id'];assert a['current_institution_id'] is None and a['status']=='review'
 assert root[s.LOC+'hasCulturalInstituteOrSite']=={s.MURI} and root[s.DC+'coverage']=={'Verbania (VB)'}
 locs=root[s.LOC+'hasTimeIndexedTypedLocation'];assert len(locs)==1;loc=g[next(iter(locs))];assert loc[s.LOC+'hasLocationType']=={s.LOC+'CurrentPhysicalLocation'} and loc[s.LOC+'hasCulturalInstituteOrSite']=={s.MURI} and loc[s.LOC+'atSite']=={'https://w3id.org/arco/resource/Site/c76755ebdd56fe092a618e9029929264'}
 inv=sorted(set().union(*(g[u][s.CD+'inventoryIdentifier'] for u in root[s.CD+'hasInventorySituation'])));assert len(inv)==1 and re.fullmatch('OA[0-9]+',inv[0])
 dates=root[s.DC+'date'];assert len(dates)==1;date=next(iter(dates));assert a['date_display']=='Unverified date: '+date
 titles=root[s.CD+'title']|root[s.CD+'subject']|root[s.DC+'subject'];assert m.norm(a['title']) in {m.norm(t) for t in titles}
 assert any(m.norm(a['unlinked_creator_label']) in m.norm(t) for t in root[s.LABEL])
 assert r['identity_hits'] and {v['entity_id'] for v in r['identity_hits']}=={aid}
 h=r['pending_assertion'];assert h['artwork_id']==aid and h['institution_id']==IID and h['claim_type']=='holding' and h['review_state']=='review' and h['superseded_by'] is None
 legal=root[s.CD+'hasLegalSituation'];assert len(legal)==1;labels=sorted(set().union(*(g[u][s.LABEL] for u in legal)));assert labels and all('proprietà privata' in v for v in labels)
 return dict(source_id=r['source_id'],source_url=r['source_url'],title=a['title'],creator_label=a['unlinked_creator_label'],date_display=date,inventory=inv[0],museum_uri=s.MURI,coverage='Verbania (VB)',source_labels=sorted(root[s.LABEL]),source_titles=sorted(titles),source_descriptions=sorted(root[s.DC+'description']|root[s.CORE+'description']),legal_labels=labels,legal_owner_uris=sorted(set().union(*(g[u][s.CD+'hasOwner'] for u in legal))),source_location_type=s.LOC+'CurrentPhysicalLocation',existing_date_precision=a['date_precision'],existing_creation_year_start=a['creation_year_start'],existing_creation_year_end=a['creation_year_end'])
def build():
 src=m.load(RUN/'source-context-001.json.gz');identity=m.load(RUN/'identity-001.json.gz');comps={v['number']:v for v in identity['comparisons']};rows=src['rows'];own={r['artwork']['id'] for r in rows};out=[];invs=set()
 for r in rows:
  n=r['number'];f=facts(r);assert f['inventory'] not in invs;invs.add(f['inventory']);c=comps[n];assert {v['entity_id'] for v in c['source_hits']}=={r['artwork']['id']}
  external=[h for h in c['hits'] if h['same_creator'] and h['id'] not in own];assert not external or n in NOTES or n in HOLDS
  yrs=[int(v) for v in re.findall(r'\d+',f['date_display'])];assert yrs
  if n not in HOLDS:assert all(1000<=v<=1970 for v in yrs)
  note=NOTES.get(n,'No unresolved outside-target same-creator title/version comparison. Other generic-title hits identify different creators. Within-target works have separate OA inventories and literal object titles/dates; group subjects remain one source object.')
  if n in [19,85,120]:note+=' Multiple heads, pages or figures are subjects of one inventoried support, counted once.'
  if n in [101,128,155]:note+=' The three Browne young women have distinct OA214,OA210,OA211 inventories; Eva is the qualified title of OA211.'
  if n in [109,110,160]:note+=' Maggi snow scenes have distinct OA290,OA292,OA291 inventories and separate literal titles;1911 is distinct from the two1908 Engadine scenes.'
  out.append(dict(number=n,institution_id=IID,existing_artwork_id=r['artwork']['id'],facts=f,state='editorial_hold' if n in HOLDS else 'approved_existing_holding',confidence=None if n in HOLDS else .88,basis=HOLDS.get(n,COMMON+' '+note),limitation=LIMIT,derived_fields=[],retrieved_at=r['pending_assertion']['checked_at'],source_reference=r['body_reference'],source_raw_sha256=r['raw_sha256'],pending_assertion_id=r['pending_assertion']['id'],comparison=c))
 assert len(out)==161 and sum(v['state']=='approved_existing_holding' for v in out)==155;return out
def main():
 dest=RUN/'editorial-reviewed-001.json.gz';assert not dest.exists();ds=build();paths=[RUN/n for n in ['source-context-001.json.gz','identity-001.json.gz','identity-citations-001.json.gz','comparison-source-context-001.json.gz']];m.save(dest,dict(at=m.now(),decisions=ds,reviewer_reference=ref(Path(__file__).resolve()),dependencies=[ref(v) for v in paths],policy='Holdings-only review of161 existing objects;155 approved,6 held. No inferred creation dates or ownership; exact1970 included;15 approved unknown/qualified dates remain unknown and outside eligible-date count.'))
 print(json.dumps(dict(decisions=len(ds),approved=155,held=sorted(HOLDS))),flush=True)
if __name__=='__main__':main()
