"""Document wave85, explicit evidence limits and the remaining museum queues."""
import hashlib,importlib.util,json
from pathlib import Path
z=importlib.util.spec_from_file_location('a',Path(__file__).with_name('museum-expansion-britain-seven-apply-20261009.py'));a=importlib.util.module_from_spec(z);z.loader.exec_module(a);m=a.m
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 report=m.load(m.RUN/'verification-after-wave-85.json');assert(report['verified_new_artworks'],report['verified_existing_artworks_linked'],report['institutions_with_new_records_or_reconciled_holdings'])==(10395,2297,228);plan,digest=a.validate_plan()
 with m.connect() as db:verified=a.verify(db,plan,digest)
 cp=m.load(a.CHECKPOINT);root=m.RUN/'README.md';pin=next(v for v in cp['artifacts'] if v['path']==str(root.relative_to(m.ROOT)));assert sha(root)==pin['sha256'];backup=m.BACKUP/'britain-seven-root-readme-before-001.json.gz';assert not backup.exists()
 for name in ['checks-001.json','remaining-research-001.json.gz','next-museum-pass-001.json','README.md','readme-supersessions-001.json','source-availability-001.json']:assert not(a.RUN/name).exists()
 logsroot=Path('/Users/vadimdulub/Library/Logs');test=(logsroot/'artline-britain-seven-tests-20261009.log').read_text();assert 'Ran 31 tests' in test and test.rstrip().endswith('OK');assert(logsroot/'artline-britain-seven-replay-20261009.log').read_text().strip()=='Unchanged replay: zero writes'
 logs={v.name:dict(path=str(v),sha256=sha(v)) for v in sorted(logsroot.glob('artline-britain-seven-*-20261009.log')) if 'delivery' not in v.name and 'checkpoint' not in v.name}
 m.save(a.RUN/'checks-001.json',dict(at=m.now(),new_offline_tests_passed=31,historical_tests_passed=1638,cumulative_verified_tests=1669,historical_tests_rerun=False,replay_zero_writes=True,source_objects_reviewed=201,pending_assertions_reviewed=202,new_artworks=0,existing_links=178,editorial_holds=23,logs=logs,other_job_totals_separate=True,source_recovery='Original source parser encountered one legacy plain-text pending claim. V2 preserves both assertions on one Fanny Keats object. Facts v2 strips a trailing URL fragment for comparison only. Review v2 adds exact native-title guard; decisions identical to first review. No failed write transaction.'))
 access=m.load(a.RUN/'new-source-access-holds-001.json');m.save(a.RUN/'source-availability-001.json',dict(at=m.now(),new_source_access_holds=access['rows'],new_source_access_hold_reference=a.reference(a.RUN/'new-source-access-holds-001.json'),previous_source_availability_reference=cp['source_availability_reference'],previous_source_hold_reference=cp['new_source_access_hold_reference'],salford_catalogue_reference=a.reference(a.RUN/'salford-catalogue-probe-001.json'),guildhall_publisher_reference=a.reference(a.RUN/'guildhall-gac-selected-001.json.gz'),policy='London Picture Archive and Smartify returned 403; no retry or bypass. ArtUK and all earlier denied/unavailable sources remain held. Salford observed public catalogue refused connection once; no exact native object corroboration claimed. Guildhall-linked Google Arts and Culture accessible;46 short cards,5 selected asset pages,4 physical-object candidates. No images downloaded.'))
 held=[v for v in m.load(a.REVIEW)['decisions'] if v['state']=='editorial_hold'];assert len(held)==23;m.save(a.RUN/'remaining-research-001.json.gz',dict(at=m.now(),rows=held,review_reference=a.reference(a.REVIEW),previous_remaining_research_reference=cp['remaining_research_reference'],source_availability_reference=a.reference(a.RUN/'source-availability-001.json'),policy='Keep23 held objects,including the two historical pending claims on one Fanny portrait.83 newly linked unknown dates need creation evidence; accepted holding does not establish eligibility. Keats House crosswalk,close physical versions,attribution conflicts and paired sides remain unresolved. All earlier queues persist.'))
 oldq=m.load(a.checked(cp['next_museum_pass_reference']));live=m.load(m.RUN/'after-wave-85.json');by={v['id']:v for v in live['institutions']};italian=[dict(v,current_linked=by[v['institution_id']]['works'],current_eligible=by[v['institution_id']]['eligible_works']) for v in oldq['italian_museums']];assert len(italian)==225
 targets=[by[k] for k in ['f751c09d-2023-5b1b-935b-3aae9a3f842a','9c814fd2-038c-582e-b2b0-9dc8c2e0a00b']];native=[by['03058adb-4b2a-5a45-849d-2393f4229f9b']]
 m.save(a.RUN/'next-museum-pass-001.json',dict(at=m.now(),previous_queue_reference=cp['next_museum_pass_reference'],italian_museums=italian,existing_holding_review_targets=targets,native_addition_targets=native,current_museums=[by[k] for k in a.IIDS],remaining_research_reference=a.reference(a.RUN/'remaining-research-001.json.gz'),source_availability_reference=a.reference(a.RUN/'source-availability-001.json'),native_selection_index_reference=a.reference(a.RUN/'guildhall-gac-indexes-001.json.gz'),native_object_caveats_reference=a.reference(a.RUN/'next-native-object-caveats-001.json'),policy='Continue selected eligible native Guildhall candidates from46 already observed cards; exclude image documentation,details,duplicate presentations and existing objects before selected metadata requests; publisher branding alone does not prove holdings,especially exhibition loans. Review Southampton100 and Edinburgh City Art Centre91 pending objects. Salford101linked/40eligible and Guildhall93 linked/64 eligible remain below preferred 200 and need more dated source-backed works. Retain225 Italian museums,Ferens44 held,RWA date gap and every earlier queue. Goal active.',database_writes=0))
 text=f'''# Salford and Guildhall holdings — 9 October 2026

Linked **178 existing review artworks** to their documented museums. No new artwork records were created.

| Museum | Links added | Linked records before → after | Eligible dates before → after |
| --- | ---: | ---: | ---: |
| Salford Museum and Art Gallery | 94 | 7 → 101 | 1 → 40 |
| Guildhall Art Gallery | 84 | 9 → 93 | 8 → 64 |

**83 newly linked records retain unknown creation dates.** They count as visible catalogue items but not as date-eligible works. A linked-record threshold does not establish 100 distinct physical objects or 100 dated pre1971 works. The preferred 200 target remains unfinished for both museums.

Reviewed 201 exact objects and 202 historical pending assertions. [Twenty-three objects remain held](remaining-research-001.json.gz): attributed or after-maker conflicts, near-identical versions, recto/verso supports, modern-event or uncertain date cases, and six Keats House accession mappings. One Fanny Keats portrait has two pending assertions; both remain unchanged. The [official Keats House article](https://www.cityoflondon.gov.uk/things-to-do/attractions-museums-entertainment/keats-house/letters-fanny-keats-and-fanny-brawne/the-journey-of-the-letters) identifies the 1880 portrait under a Keats House accession; City of London administration does not establish a Guildhall branch holding.

The [official Guildhall page](https://www.cityoflondon.gov.uk/things-to-do/attractions-museums-entertainment/guildhall-art-gallery/collections/explore-online) links its [museum-published Google Arts & Culture collection](https://artsandculture.google.com/partner/guildhall-art-gallery). Four exact candidates are corroborated there: *The Blessed Damozel*, *The Raising of Jairus’ Daughter*, *The Temptation in the Wilderness* and *The Lord Mayor’s Procession by Water*. Two online Damozel assets count as one existing painting. The procession page credits both Richard Paton and Francis Wheatley; the evidence retains that joint credit without rewriting existing artist links. Rights labels remain City of London Corporation; no reproduction downloaded.

The other 174 accepted links use exact saved Wikidata object evidence and its ArtUK references, with museum-qualified inventory, creator, title, date and physical-version comparisons. These are **correlated secondary evidence**, not newly fetched ArtUK or independent primary confirmation. Editorial confidence is 0.8 for those links and 0.9 for the four corroborated objects; these are editorial judgments, not calibrated probabilities. Salford’s official collection overview is context only. Its linked native catalogue refused a connection; London Picture Archive and Smartify returned 403 and were not retried. All earlier source holds persist.

Distinct Dunington aqueduct paintings retain their separate sizes, dates and accessions. A qualified Sidley copy preserves “after Thornton Rippingille” in its title. Retained primary Tate metadata distinguishes the large Guildhall 1855 *Wounded Cavalier* from the 1871 physical detail painting. Generic surname/title matches do not merge Flora Lion with Léon Bonnat or Matthew Smith with other Smiths.

The [reviewed plan](britain-seven-existing-holdings-001-plan-001.json.gz) and [transaction receipt](britain-seven-existing-holdings-001-applied.json) verify 178 new holding citations and assertions, with the 178 earlier pending claims superseded. All {verified['protected_existing_records']:,} scoped artwork records and all 12,514 prior campaign objects were checked. **31 offline tests, atomic readback and zero-write replay passed.** Existing dates, images, creator links, statuses and museum records remain unchanged. No publication, current-display claim, commit, deployment or production write.

Campaign total: **10,395 new artworks + 2,297 reconciled existing artworks = 12,692 distinct records across 228 institutions**. The audit still has **{report['after']['museums_below_100']:,} museums below 100 linked records** and **{report['after']['museums_below_200']:,} below 200**. [Next work](next-museum-pass-001.json) includes selected Guildhall additions, Southampton and Edinburgh City Art Centre; all earlier museum queues remain active.
'''
 m.save(backup,dict(at=m.now(),path=str(root),text=root.read_text(),sha256=sha(root)));(a.RUN/'README.md').write_text(text)
 old=root.read_text();intro,rest=old.split('## Added works',1);intro=intro.replace('2,119','2,297').replace('expand 226 institutions','expand 228 institutions').replace('1,236',f"{report['after']['museums_below_100']:,}").replace('after-wave-84','after-wave-85').replace('RWA and Ferens passes','RWA, Ferens, Salford and Guildhall passes');root.write_text(intro+'## Added works'+rest+'\n\n## Salford and Guildhall holdings — wave85\n\nLinked 178 existing review artworks:94 Salford and84 Guildhall. Totals 101 and93 linked records,40 and64 eligible dates. 83 unknown dates remain unchanged; 23 candidates held. [Evidence and limits](native/britain-seven-holdings-20261009/README.md). Campaign 10,395 new + 2,297 reconciled = 12,692 distinct records across 228 institutions. The all-museum 100–200 goal remains unfinished.\n')
 m.save(a.RUN/'readme-supersessions-001.json',dict(at=m.now(),changes=[dict(path=str(root.relative_to(m.ROOT)),before_sha256=pin['sha256'],after_sha256=sha(root),backup_path=str(backup),backup_sha256=sha(backup))]));print(json.dumps(dict(documented_new_records=0,documented_existing_links=178,held=23,tests=31,goal_complete=False)),flush=True)
if __name__=='__main__':main()
