"""Object-specific editorial judgments for the RWA and Ferens pass."""
HOLDS={
6:'The primary maker is I. Tudgay, active1836-1865, while the existing authority is John Lashbrook Tudgay. Preserve this unresolved initial/creator identity instead of silently equating the labels.',
11:'Both the source filename and native description explicitly attribute the portrait to Margaret Sarah Carpenter. The existing creator link is unqualified; retain the qualification pending reconciliation.',
23:'Native Ferens Composition1936 is38x46cm, distinct from the documented1930,1939 and1940 versions. However a same-maker imported Composition with an unverified1933 date has no inventory or dimensions and remains an unresolved possible duplicate. Preserve the native evidence without assuming the date discrepancy proves a different physical object.',
29:'Left panel of the same Camilla Nock diptych875 as row238. Preserve both existing component records without counting them as two independently reconciled museum objects. Creation dates remain unknown.',
30:'Bridge over a River is the verso of Snow in My Garden, sharing base inventory2005.5077 with row232. Preserve both current representations pending one-object/component reconciliation.',
46:'Fedden Flowers1 at RWA is54.6x44.5cm1948,close to the same-maker Bristol Sicilian Flowers59x49cm1949. The modest size and date differences plus generic floral title leave physical-version/transfer identity unresolved. Preserve distinct source inventories without assuming they establish different physical works.',
61:'This is one wing of the David Cobley Academy officers2000-2004 triptych1192, shared with148/231. The title supplies a recent subject period, not an exact creation date. Preserve the unknown date and component scope; no quota-driven inclusion.',
74:'The native maker and description explicitly qualify Thomas Churchyard as attributed. Preserve the existing unqualified link pending creator reconciliation.',
99:'Native maker is Charles Allston Collins1828-1873, with creation1876, while the source image label identifies Charles Collins II1851-1921. This is an unresolved creator/chronology conflict despite exact inventory and title.',
102:'Spring in Provence recto and row189 garden verso share RWA423. Preserve both sides as existing records until physical-object representation is reconciled; do not count one support twice.',
116:'Hempton Stone,Staff and Triangle No.2 is229x183cm; the same-maker Bradford comparison is214x183cm with unknown date. The shared title and near size leave version/transfer identity unresolved; accession differences alone do not prove separate objects.',
148:'Centre panel of the Cobley Academy officers2000-2004 triptych1192. Preserve its component relation and unknown creation date; hold with61/231.',
153:'The exact native Head Tilting Forwards II record dates creation2002. Preserve the existing unknown date and pending holding; this is outside the selected pre1971 expansion.',
189:'Garden verso is the reverse of Spring in Provence recto under RWA423. Preserve both current records pending physical-object representation reconciliation.',
231:'Right wing of the Cobley Academy officers2000-2004 triptych1192. Preserve its component relation and unknown creation date; hold with61/148.',
232:'Snow in My Garden recto shares base inventory2005.5077 with Bridge over a River verso. Preserve the single-support issue and both existing records without double counting.',
238:'Right panel of Camilla Nock diptych875, also represented by row29. Unknown creation and component identity remain pending.'}
for number in [50,75,96,105]:HOLDS[number]='The native record repeats creation1787 but names Charles James Sartorius1794-after1821, an internally inconsistent artist/date combination also present in the source image label. Preserve both source claims and existing values pending creator/chronology reconciliation.'
NOTES={
4:'Native Westerdale\'s Yard from Saville Street is the exact6283 inventory. The overview explicitly distinguishes its companion view of the ship Wellington; select this painting only and preserve spelling/title variants.',
20:'Native maker field Olver,Kate E.agrees with the current authority; description spells Oliver. Retain both original strings. Its description says cardboard while the dimensions label says canvas; no support metadata is rewritten.',
31:'Native explicitly calls this one of a series of three paintings and assigns individual5067.3 inventory and panel dimensions. It is a separate physical panel, not an aggregate or a reverse. Preserve its panel3 designation and the distinct narrative scene.',
36:'Native date field circa1865 and description circa1860-1870 are retained alongside the existing range. No date is narrowed.',
46:'Fedden Flowers1 inventory13 is54.6x44.5cm; Flowers2 inventory26 is75x49.5cm. The numbered titles and different formats distinguish them. Cardiff Fruit and Flowers61x50.8 and Bristol Sicilian Flowers59x49 have different subjects/source identities; no merge.',
51:'The selected Starr Study92x56cm is distinct in scale from Tate T03643 A Study45.5x35.5cm. Exact saved primary Tate metadata confirms the smaller comparison, with Sidney Starr naming. Keep both original titles and date ranges.',
65:'This record explicitly represents the verso of RWA273. No other representation of273 or matching same-maker recto was returned by the scoped inventory/creator comparison. Link only this existing side; do not invent another object or infer a creation date.',
66:'Native medium includes scissors and hardboard panel while its dimensions row says canvas. Preserve the mixed-technique and support inconsistency as evidence without replacing catalogue metadata.',
67:'Native maker field Hemsley agrees with the source authority while its prose spells Helmsley. Retain both strings; exact inventory,title,1859 and object identity agree.',
69:'Pickard Ferens vegetables58.5x71cm differs from Tate Still Life by a Window81.3x101.6cm. Native circa1927 is explicit creation evidence but the existing unknown date stays unchanged in this holding-only pass. Codrington vegetables is a different maker.',
72:'Native explicitly describes one of three separate paintings,cross-referencing5067.2 and5067.3. Each has its own panel dimensions and different narrative scene. Preserve this individually inventoried panel1 rather than treating it as an aggregate.',
76:'Rollett Ferens landscape27.3x22.3cm portrait format differs from North Lincolnshire Museum landscape34.5x50cm horizontal format. Native Herebert Rollet spelling remains evidence beside its consistent maker field.',
81:'Janette Kerr differs from Kerr Eby. Night Sea1367 and Night Wood1776 have different subjects and scoped inventories; unknown dates remain unknown.',
83:'Lowther portraits of William Severn and John Beverley name different sitters with distinct U.10.1994.162 and161 inventories. Sitter ministry periods in the titles are not creation dates.',
85:'Native prose says canvas and dimensions say panel. Preserve the discrepancy as source evidence without changing the current support or object identity.',
90:'Nigel Ramsey Newton is not Kenneth Newton or Francis Newton Souza. The retained V&A Black Nude record identifies Souza; a shared name token and generic nude subject do not establish same maker.',
94:'Foster Delphiniums and Roses76x56cm1928 is distinct from Delphiniums102x77cm1914 at Bognor. Separate support size,subject specificity and inventory support physical identity.',
95:'Native maker field Parsons Knight,Charles differs from its prose Charles Knight1901-1990. Preserve both source forms; exact inventory and Llangollen1925 agree with the existing Charles Knight authority.',
129:'Hughes fruit35.5x45.5cm1865 differs from Ferens game75x62cm1868 and Ashmolean kitchen utensils24x20cm1868. Native date field1865 conflicts with description1863; retain both as evidence and leave catalogue1865 unchanged.',
135:'Janette Kerr Night Wood1776 differs from her Night Sea1367 and from Kerr Eby Night Loading. No creation date is inferred.',
138:'Native title identifies the Liverpool whaler specifically as Baffin. Preserve this added specificity and exact2007.4206 inventory alongside existing Liverpool Whaler and circa1834.',
161:'Native date field circa1875 conflicts with its description circa1871 and the current circa1871. Preserve the two source dates; exact Princes Dock inventory,maker and subject agree without a silent date rewrite.',
146:'Greig Entertainment,Show Day617 and Tea Ladies,Show Day609 depict different named activities with distinct inventories; preserve their unknown dates.',
147:'Gordon Ward is not James Ward. Slad Valley with Cattle and Landscape with Cattle do not establish the same maker or object.',
166:'David Carr is not Emily Carr; the generic self-portrait title does not establish same identity.',
167:'Margaret Thomas differs from Thomas Creswick,Thomas Barker and Thomas Rowlandson. Their generic lexical title hits do not establish common creator identity.',
171:'Lowther John Beverley portraitU.10.1994.161 is separate from William SevernU.10.1994.162. Preserve the named sitters and distinguish ministry dates from creation.',
176:'Native sitter Picard and catalogue Pickard are spelling variants on the same exact portrait inventory,with matching1797-1836 life dates and1813 creation. Preserve both names as source evidence without altering the catalogue.',
178:'Native has no separate Artist/Maker field,but its object description explicitly names James Kerr-Lawson with1913 and the exact Lavery portrait inventory. Do not confuse the named sitter Lavery with the maker.',
181:'Native exact inventory retains KINCM prefix absent from the current2005.5027 token. Comparison removes only that standard prefix,preserving numeric parts and suffixes. Native1830-1839 range and circa1835 description stay evidence; current circa1835 unchanged.',
183:'Native date field circa1850 conflicts with description1860,which agrees with the current date. Preserve both source dates with exact inventory,maker and mill/stream subject.',
185:'Native date field1886 conflicts with description1888,which agrees with the current date. Preserve the fantasy subtitle and both dates without changing catalogue fields.',
187:'Fedden Flowers2 inventory26 is75x49.5cm, distinct from Flowers1 inventory13 at54.6x44.5cm. Related floral works at Bristol and Cardiff have separately identified subjects and formats.',
192:'Greig Tea Ladies,Show Day609 differs from Entertainment,Show Day617 by named activity and inventory. No date is inferred.',
217:'Hughes game75x62cm1868 differs from fruit35.5x45.5cm1865 and Ashmolean kitchen utensils24x20cm1868. Preserve the verified existing unlinked maker label.',
227:'Native date field1822 agrees with the current record,but its description gives1830. Preserve this internal chronology conflict and exact Hull Whalers inventory without silently changing the date.',
235:'School is part of the painting title The Night School,not an attribution qualifier.',
240:'William Brooker differs from Harry Brooker. Sunday Afternoon and Afternoon Tea are not the same maker or painting.',
245:'Native describes this as one of three paintings with an individually inventoried panel5067.2. Preserve its separate narrative scene and support; no aggregate record is added.'}
