"""Document verified wave82, its unresolved cases and the continuing museum queue."""
import collections,hashlib,importlib.util,json
from pathlib import Path
z=importlib.util.spec_from_file_location('a',Path(__file__).with_name('museum-expansion-britain-five-apply-20261009.py'));a=importlib.util.module_from_spec(z);z.loader.exec_module(a);m=a.m
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 report=m.load(m.RUN/'verification-after-wave-82.json');assert(report['verified_new_artworks'],report['verified_existing_artworks_linked'],report['institutions_with_new_records_or_reconciled_holdings'])==(10259,1892,224);plan,digest=a.validate_plan()
 with m.connect() as db:verified=a.verify(db,plan,digest)
 assert verified['network_to_branch_refinements']==33 and verified['previously_unlinked']==191 and verified['unknown_date_records_preserved']==72
 cp=m.load(a.CHECKPOINT);root=m.RUN/'README.md';pin=next(v for v in cp['artifacts'] if v['path']==str(root.relative_to(m.ROOT)));assert sha(root)==pin['sha256'];backup=m.BACKUP/'britain-five-root-readme-before-001.json.gz';assert not backup.exists()
 assert all(not(a.RUN/n).exists() for n in ['checks-001.json','remaining-research-001.json.gz','next-museum-pass-001.json','README.md','readme-supersessions-001.json'])
 logsroot=Path('/Users/vadimdulub/Library/Logs');test=(logsroot/'artline-britain-five-tests-20261009.log').read_text();assert 'Ran 26 tests' in test and test.rstrip().endswith('OK');assert(logsroot/'artline-britain-five-replay-20261009.log').read_text().strip()=='Unchanged replay: zero writes'
 logs={v.name:dict(path=str(v),sha256=sha(v)) for v in sorted(logsroot.glob('artline-britain-five-*-20261009.log')) if 'delivery' not in v.name and 'checkpoint' not in v.name}
 native=a.r.native_rows();wstates=collections.Counter(v['state'] for n,v in native.items() if 'objects' not in v);assert wstates==dict(captured_exact_inventory=105,no_unique_exact_inventory_result=21)
 m.save(a.RUN/'checks-001.json',dict(at=m.now(),new_offline_tests_passed=26,historical_tests_passed=1560,cumulative_verified_tests=1586,historical_tests_rerun=False,replay_zero_writes=True,source_objects_reviewed=244,new_artworks=0,existing_links=224,previously_unlinked=191,network_to_branch_refinements=33,editorial_holds=20,unknown_dates_preserved=72,logs=logs,other_job_totals_separate=True,williamson_inventory_searches=126,williamson_exact_objects=105,retained_perth_inventory_searches=118,retained_perth_searches_with_exact_objects=92,retained_perth_object_records=94,retained_perth_requests_made=0,transport_retry_policy='Two isolated Williamson transport errors each succeeded on one same-URL retry. Initial parser failure retained and fixed using cached HTTP200 bodies. Perth catalogue stopped after three connection timeouts.'))
 held=[v for v in m.load(a.REVIEW)['decisions'] if v['state']=='editorial_hold'];assert len(held)==20
 m.save(a.RUN/'remaining-research-001.json.gz',dict(at=m.now(),rows=held,review_reference=a.reference(a.REVIEW),previous_remaining_research_reference=a.reference(a.prior.RUN/'remaining-research-001.json.gz'),network_context_reference=a.reference(a.RUN/'perth-network-context-001.json.gz'),new_source_hold_reference=a.reference(a.RUN/'perth-catalogue-availability-001.json'),policy='20 cases held for sitter/title,creator/qualification,source conflation,physical-version/component and date-scope conflicts. The Eardley recto/verso records describe one canvas; both remain unchanged pending representation reconciliation. Gear Composition remains at CPK network level. Preserve every earlier queue and source access hold. Unknown creation dates remain unknown; no placeholder or quota-based acceptance.'))
 oldq=m.load(a.checked(cp['next_museum_pass_reference']));live=m.load(m.RUN/'after-wave-82.json');by={v['id']:v for v in live['institutions']};italian=[dict(v,current_linked=by[v['institution_id']]['works'],current_eligible=by[v['institution_id']]['eligible_works']) for v in oldq['italian_museums']];assert len(italian)==225
 targets=[by[k] for k in ['71512d0a-3bc1-549f-80d1-708d14b3ee99','9172ebcd-f052-5736-a3ba-a8612ac75c60']];assert all(v['works']<100 and v['pending_associations']>=100 for v in targets)
 m.save(a.RUN/'next-museum-pass-001.json',dict(at=m.now(),previous_queue_reference=cp['next_museum_pass_reference'],italian_museums=italian,existing_holding_review_targets=targets,remaining_research_reference=a.reference(a.RUN/'remaining-research-001.json.gz'),current_museums=[by[k] for k in a.IIDS+[a.s.NETWORK]],new_source_hold_reference=a.reference(a.RUN/'perth-catalogue-availability-001.json'),policy='Next selected evidence review:Royal West of England Academy and Ferens Art Gallery. Williamson117linked/57eligible needs83 more linked records for200 and43 eligible for100. Perth113linked/96eligible needs87 more linked for200 and4 eligible for100. Preserve225 Italian museums and all prior source holds,including Art UK,ArCo,Bristol,regional TLS,Musei Reali and the Perth catalogue. No blind network/branch reassignment.',database_writes=0))
 text=f'''# Williamson and Perth holding review — 9 October 2026

Applied **224 reviewed links for existing local artworks**: **191 previously unlinked works and 33 refinements from Culture Perth & Kinross to Perth Art Gallery**. No new artwork records were created in this pass.

| Museum | Accepted links | Linked before → after | Eligible dates before → after |
| --- | ---: | ---: | ---: |
| Williamson Art Gallery and Museum | 117 | 0 → 117 | 0 → 57 |
| Perth Art Gallery | 107 | 6 → 113 | 1 → 96 |

Both museums now exceed 100 linked records. **72 accepted works retain unknown dates** and are excluded from eligible-date totals. Williamson still needs 43 eligible works or supported date reconciliations to reach 100 eligible; Perth needs four. The preferred 200 remains unfinished for both.

The review covers all 244 selected pending associations from 144 original Wikidata bodies, museum-qualified inventories, exact source IDs and creator identities. Fresh identity comparison covered 33,589 artworks and 69,440 citations. Five unlinked labels were verified against three creator authorities without adding painter links. Thirty-eight retained source contexts for 21 comparison artworks from 35 raw bodies support version comparisons. Referenced secondary claims are treated as correlated evidence; Art UK was not fetched through its access hold.

The [Williamson catalogue](https://williamsonartgallery.org/collections/) supplied **105 exact native objects from 126 selected inventory searches**. Twenty-one had no exact result and are not described as native confirmation. The parser was repaired for its special From field; the original failed run and cached HTTP200 bodies remain. Two isolated connection/reset errors succeeded on one same-URL retry each. All source titles, maker labels, dates, media, dimensions and rights labels remain separate evidence. No images were downloaded or attached.

For Perth, **118 previously captured museum-supplied MDS searches were re-parsed and hash-verified**, with no new MDS requests. Ninety-two searches contain 94 exact-inventory object records. One accession is shared by a Hargitt painting and a university ticket; the exact painting object was selected by its title, maker and object type. Another accession conflates a portrait with a silver jug and remains held. The separate Perth catalogue failed three connection attempts and is recorded as a source gap; requests stopped there.

The 33 Perth branch refinements are **editorial inferences**, combining each exact museum-supplied Fine Art object, the official [2023 gallery transition](https://www.culturepk.org.uk/news/new-year-new-gallery-much-loved-perth-institution-to-have-a-refresh/), the [collection-management framework](https://cdn.culturepk.org.uk/2025/09/collections-management-framework-v12.docx), and referenced object-level statements naming Perth Art Gallery. The transition expressly includes the Fergusson Collection. General policy alone does not establish an object's branch. The prior accepted network assertions remain in superseded history; 18 older unaccepted network assertions remain unchanged. Network and gallery authorities are not merged. The group retains the unresolved Gear Composition, one linked work with an eligible date. Holdings do not establish legal ownership, current custody or current display.

The [20 held cases](remaining-research-001.json.gz) preserve uncertainty. Eardley's Children Playing recto and The Fireplace verso are two representations of one canvas and are not counted as two new museum holdings. Other holds include a conflicting sitter, James/John Sydney Steel labels, attributed makers, father/son de Breanski identities, Portree/Portsea title geography, a diptych question and unresolved versions. Native Metamorphosis Birds is dated 1980. Native inventory BIKGM.8495 identifies Snowden's Hilbre Island painting from 2007, conflicting with imported Yeomans Woodside Station from 1954. Neither discrepancy is silently corrected or accepted to meet a quota.

The [plan](britain-five-existing-holdings-001-plan-001.json.gz) and [transaction receipt](britain-five-existing-holdings-001-applied.json) verify 224 citations and accepted assertions, 224 superseded pending assertions and 33 superseded network assertions. Native object metadata and original source entities were re-parsed from their raw bodies before applying. The transaction preserves {verified['protected_existing_records']:,} scoped records and all 11,927 earlier campaign artworks. **26 offline tests and zero-write replay passed**. Only holding projections and timestamps changed; metadata, images, creator links and review status remain intact. No commit or deployment.

Campaign total: **10,259 new artworks and 1,892 reconciled existing records across 224 institutions**, or **12,151 distinct artwork records**. The latest audit has **{report['after']['museums_below_100']:,} museums below 100 linked records** and **{report['after']['museums_below_200']:,} below 200**. [The next queue](next-museum-pass-001.json) selects the Royal West of England Academy and Ferens Art Gallery while preserving the 225 Italian museums and every earlier research queue and source hold. The full goal remains active.
'''
 m.save(backup,dict(at=m.now(),path=str(root),text=root.read_text(),sha256=sha(root)));(a.RUN/'README.md').write_text(text)
 old=root.read_text();intro,rest=old.split('## Added works',1);intro=intro.replace('1,668','1,892').replace('expand 222 institutions','expand 224 institutions').replace('1,240',f"{report['after']['museums_below_100']:,}").replace('after-wave-81','after-wave-82').replace('Cardiff, Bristol Milan, Brighton and Ulster passes','Cardiff, Bristol, Milan, Brighton, Ulster, Williamson and Perth passes');intro=intro.replace('This includes 47 documented refinements from the NMNI group to Ulster Museum; these are existing artworks,not new records.','This includes 47 documented NMNI-to-Ulster refinements and 33 Culture Perth & Kinross-to-Perth Art Gallery refinements; these are existing artworks, not new records.');root.write_text(intro+'## Added works'+rest+'\n\n## Williamson and Perth — wave82\n\nAccepted 224 existing-record links: 191 previously unlinked and 33 CPK-to-Perth branch refinements. Williamson 117 linked/57 eligible; Perth 113 linked/96 eligible. Preserve 72 unknown dates and 20 held cases. [Review and evidence](native/britain-five-holdings-20261009/README.md). The all-museum 100–200 goal remains unfinished.\n')
 m.save(a.RUN/'readme-supersessions-001.json',dict(at=m.now(),changes=[dict(path=str(root.relative_to(m.ROOT)),before_sha256=pin['sha256'],after_sha256=sha(root),backup_path=str(backup),backup_sha256=sha(backup))]));print(json.dumps(dict(documented_existing_links=224,previously_unlinked=191,branch_refinements=33,held=20,tests=26,goal_complete=False)),flush=True)
if __name__=='__main__':main()
