"""Individual object decisions; source facts and unresolved identities remain literal."""
NOTES={
4:'One Lorichon/Thibault nineteenth-century print after Girodet, image23.4 by31.6cm. Existing Revolt of Cairo sheets are drawings or oil sketches, different media;1798 is the represented event, not this print date.',
5:'One Triqueti1872 full-scale Homer drawing237.5 by145cm on paper mounted on canvas, inventory947.51. Related tarsia947.48 is another object; existing Triqueti pool contains other sculptural compositions.',
7:'One Girodet Galatea-head oil study46.2 by38.4cm,989.11, before1819 with unknown lower bound. Full Girodet pool has no Galatea/Pygmalion counterpart; existing Mardochee and Tydee heads are different subjects and larger canvases.',
9:'One Bottinelli marble Charlotte Corday, signed Milan1877 on its base,1919.1.25. Dimensions remain unknown; sitter dates1768–1793 are not creation dates. No maker/title/native counterpart.',
10:'One Morizet1919 Bagnoles thermal-park oil panel35 by26.5cm,1919.1.214. Verso identifies the place and date; no creator counterpart and generic Paysage exact-title leads have other named creators.',
12:'One Raffort nineteenth-century fishermen-house watercolor19 by28.5cm visible area. Existing Raffort pool consists of other named-site oil compositions, not this paper work.',
15:'One anonymous seventeenth-century guitarist oil painting36.3 by28cm. Existing Bonvin guitarist is an etched sheet36.2 by26.3cm, a different physical medium despite similar paper measurements.',
16:'One anonymous third-century marble Hercules,10368,41.5cm high, lion-skin subject. Literal third century gives201–300; maker stays unknown. Same-title Ingres/Moreau/Delhumeau works are drawings or paintings.',
17:'One Astruc1874 watercolor Paris interior36.4 by28.4cm,8102;758, woman beside piano/mirror. A painting depicted in the room is not counted as another object. Creator leads depict other objects.',
18:'One Alechinsky1970 wolf ink drawing39 by23cm on manuscript paper,95-3-1. Cutoff includes1970; full creator pool has no wolf counterpart and its untitled1962 aquatint has another technique/format. Related95-3-2 is another object.',
19:'One Brunier1837 Italian drawing8106;1736,30 by48cm, Castel Gondolfo. Distinct accession/site/composition from other selected Brunier sheets; exact-title leads have other creators.',
20:'One circa1864 ink sketch21.8 by15.4cm in the manner of Carpeaux. Preserve qualified maker and source comparison to Notre-Dame du Saint Cordon sculpture; do not turn a related sculpture into this drawing. Same-title leads have other makers/formats.',
22:'One Denet early-twentieth-century rainy clocktower charcoal drawing24.7 by17.4cm,8247. Existing Denet pool comprises other oil compositions; source-related drawings are not added here.',
23:'One Detaille1885 mounted-hussar watercolor25 by20.5cm. Existing mounted dragoons are1876 oil panels/canvas24.1 by13.7 and23.5 by13.2cm; Cavalryman lead is an etching, another medium.',
26:'One Hippolyte Flandrin graphite figure-study sheet13.1 by20.4cm,8192;3030. Male/female studies share one sheet. Existing apostle and Bonaiuto graphite sheets are upright28.1 by21.8 and27 by16.5cm with different subjects.',
27:'One Glinet1876 drawing8277,15.8 by10.6cm, charcoal with white gouache. Preserve source title Rocher alongside water/poplar subject description; no creator/title/native counterpart.',
28:'One Pierre Gombert eighteenth-century back-view woman sanguine42.8 by32cm,8272. Exact-title leads are paintings by other makers; no native counterpart.',
30:'One Guillaumin1886 Charenton pastel48 by63.5cm,7939. Existing Charenton works are oil paintings32.3 by40.1 and61 by100cm; unfinished/unsigned source details retained.',
31:'One Guirand de Scevola nineteenth-century female watercolor/graphite/gouache portrait26 by20cm,8193, red hair and flowers. No creator counterpart; generic exact-title pool has other named creators.',
32:'One Hassin1890 Evreux clocktower watercolor38.5 by27.7cm,93-5-1, rue des Lombards. No creator/title/native counterpart.',
33:'One1819 port watercolor/pen sheet24 by33.9cm,10576, inscribed Napoli fecit1819. Preserve literal incomplete HEFS creator label; no invented first name or authority link.',
34:'One Helion1948 Journalerie watercolor/pencil/ink59 by37cm,94.5.28, signed and dated. Full creator-pool title check found no newspaper-reader counterpart; other figural paintings retain their separate identity.',
35:'One Herbo1938 snow street watercolor/charcoal39.7 by57.4cm,8286;3192, St-Lucien in January. Existing Saint-Nazaire work is an oil canvas60 by81cm and another site.',
36:'One Herst nineteenth-century farmyard watercolor24.3 by33.2cm,10583. No creator counterpart; exact-title leads are other named makers, predominantly oil paintings.',
40:'One Eustache Hyacinthe Langlois circa1830 graphite studies sheet23.2 by26.7cm,8264. Actual Eustache pool has other oil subjects; broad Langlois results include other family makers. Maker lifespan is not substituted for creation.',
41:'One Monnier nineteenth-century sheet with two male portraits29.6 by19.4cm,8190;3145, brown ink on lined notebook paper. Existing single-man graphite portrait16.6 by11.7cm and Prudhomme watercolor27.9 by19.7cm differ in medium and composition.',
42:'One Amable Pinta nineteenth-century rue Saint-Dominique graphite sheet24.6 by16.1cm,8259. Preserve source title and inscription interpretation; existing Pinta works are other oils, including different maker Henri.',
43:'One Amable Pinta Marche neuf graphite sheet44.1 by30cm,8251. Keep catalogue nineteenth-century dating;8July1868 inscription remains evidence without silently replacing source date field.',
44:'One Queulvee1803 Charlotte Laslier pastel22.5 by18.7cm,7981;3324. Preserve Queulvee fils inscription and literal maker label; no creator/title/native counterpart.',
48:'One Brunier Italian graphite drawing8107;1737,31.4 by46.8cm on chamois paper, path beside bank/house. Different inventory, format and composition from selected8106/8108/8109/8110.',
49:'One Denet1887 iconographic-key drawing10586;1554,29.5 by46.4cm, ink/chalk. Existing Vafflard420 by520cm Bourlier painting is the model, not this explanatory drawing.1821 is depicted history; related11110 is another sheet.',
52:'One Amable Pinta nineteenth-century roaring tiger charcoal sheet32.5 by61.2cm,8262. No matching subject in Pinta pool; one animal drawing counted once.',
53:'One Amable Pinta1870 two-boat graphite drawing30.7 by44.7cm,8253, inscribed Marly25December70. Existing Promenade en bateau is an upright oil canvas46 by32.4cm, a different object.',
56:'One anonymous nineteenth-century Venus Callipyge copy drawing8095;24, black chalk27 by19.5cm. The depicted statue is a model, not the acquired object; no exact-title/native counterpart.',
57:'One Brunier Italian chalk/pastel sheet8108;1738,27.7 by42.5cm, tree on rock at right. Accession, format and composition distinguish other selected Italian landscapes.',
58:'One Amable Pinta1862 plant-study graphite/white-gouache sheet23.6 by30.6cm on blue paper,8257. Exact-title leads are Moreau/Michallon works; source11May1862 inscription retained.',
59:'One Amable Pinta1885 charcoal landscape32.6 by50cm,8254, Ecorchemont inscription. Existing Amable works are oils and other Pinta results are another maker; generic exact-title results have other named creators.',
60:'One anonymous nineteenth-century Japanese-woman ivory carving9154;3308,30 by9.5 by9.3cm. Depicted basket/cabinet details form one inventoried object; literal material retained.',
61:'One Brunier Italian landscape8109,35.7 by50.3cm charcoal/pastel, Arricia. Related8117 is another source object; selected8110 has a different accession, measured sheet and tree composition.',
62:'One Amable Pinta nineteenth-century young-mother squared drawing30.5 by44.6cm,8250. Dijon inscription refers to a model, while explicit collection is Evreux. Existing Boucher upright drawing and Goupil oil panel are physically different.',
63:'One anonymous seventeenth-century ivory Sebastian on wooden base9963;1024. Preserve literal conflicting object/base heights and qualified possible Philippine provenance without assigning a certain origin. Same-title leads are other named makers and painting/drawing subjects.',
64:'One Brunier1837 Italian charcoal drawing8110,35.9 by49.9cm, dated Arricia37 with hollow gnarled trunk. Separate from8109 and other selected Italian sheets by inventory, composition and source dating.',
65:'One Amable Pinta nineteenth-century horse-head anatomy tracing27 by37.6cm,8260, graphite/watercolor. Two views on one sheet are counted once; no creator/title/native counterpart.',
66:'One Louis Desmarest nineteenth-century Jules Laurens oil portrait56 by46cm,2009.0.14. Existing Cabanel Laurens oil32.5 by24.5cm is another maker and format.',
70:'One Louise Nevelson1935 untitled nude ink drawing40.6 by21.6cm,2002.2.9. Current Nevelson label supersedes old Berliawsky label only in this new source-backed record; both labels preserved in evidence and duplicate scope. Existing untitled work is a1967 four-sheet lithograph91.12 by177.96cm; other creator leads have other subjects.',
71:'One Marie Louise Adelaide Boizot1780 Little Reader print23.5 by19.2cm after Greuze,82.1728. Preserve the later publisher-address wording without inventing an impression date;1780 remains the literal catalogue date and plate inscription. No matching reader in expanded creator pool.',
72:'One Bouchardon circa1740 windmill-seller red-chalk drawing32.6 by18.3cm,2003.2.3. No creator/title/native counterpart.',
74:'One Cocteau1958 dancers-and-faun pencil drawing31 by40cm,2003.2.5, signed and dated. Existing Couple at Le Boeuf sur le Toit is upright ink27 by20.6cm circa1925; full pool has no corresponding faun/dancer composition.',
78:'One Maurice Esteve circa1926 back-view nude ink drawing40 by29.5cm,2004.1.4. Existing creator pool is dominated by oil canvases of other named subjects; no same-title/back-view drawing counterpart.',
79:'One Foujita1924 child-with-fruit watercolor/ink23 by17cm,2005.2.5, signed/dated. Existing little-girl-with-doll/cat titles depict different named objects; other child drawing39.1 by28.6cm is graphite, not this watercolor.',
84:'One Franquinet/Franquinot first-half-nineteenth-century Bazile blessing lithograph26.3 by37.9cm,82.2131, after Greuze. Referenced1769 drawing47 by37.5cm is a model, not this impression; no same-title counterpart in creator scope.',
85:'One Ingouf1766 engraved young-man head from the Paralytic,82.2072, plate15.3 by11.9cm. Existing Flipart full Paralytic print55.8 by66.7cm contains the whole scene. Other selected child/head sheets have different plate letters, inventories and subjects.',
86:'One Janinet eighteenth-century tricorne-head print82.2066, image43.2 by33.4cm and sheet50 by40.1cm. Different engraver, format and inventory from held Leroy version82.0.0.751; no tricorne counterpart in existing creator pool.',
88:'One Letellier eighteenth-century young-man/hand-to-forehead print82.2087, plate17.7 by11.6cm on26.3 by17.4cm sheet. Individual inventoried cahier head D, not the entire cahier; no matching print counterpart.',
89:'One Lucien second-half-eighteenth-century blind-old-man engraving82.2046, plate50.7 by35.7cm. Related anonymous sanguine82.1556 measures70 by54.9cm and is another medium; no existing blind-head counterpart in creator scope.',
90:'One Massard reversed Mother print82.1694,48.9 by62.6cm, signed by Greuze and Massard on verso. Catalogue1776 and engraved1775 both remain literal evidence; no invented explanation for the one-year difference. Existing Well-Loved Mother is upright pastel44 by32.2cm, a different physical object.',
93:'One Greuze Sombreuil-arrest drawing2010.1.1,39 by18cm, source September1792. Existing riot drawing21.3 by28.2cm is another format/composition;1794 narrative death date is not assigned as creation.',
95:'One Martenasie/Martenisie1759 Bible-reading print2004.2.1,36.3 by45.1cm, former Hottinguer collection. Related82-series impressions are explicitly separate inventories and are not added as more objects here; preserve contributor spellings and plate inscription.',
97:'One Ingouf/Crepy eighteenth-century boy-head print82.0.0.827, plate14.1 by10.7cm on26.3 by17.6cm sheet. Right profile with added grid distinguishes other selected head sheets; carton/cahier labels do not turn it into a multi-object addition.',
98:'One Max Jacob1924 small-port watercolor26 by42cm,2004.1.3. Full Max Jacob scope has other named city/religious/cattle compositions, with Paris gouaches of different sites and formats; broad Jacob results include other makers.',
100:'One Balthus1946 Horse and Wolf ink study31 by24cm,2001.3.7, explicit La Fontaine subject. Existing Cenci illustration study31.1 by39.7cm is another story and orientation; no horse/wolf counterpart in full creator pool.',
101:'One Lacasse1911 cubist colored-pencil drawing20 by15cm,2001.3.25, signed/dated/monogrammed. Existing Green Composition has1960 source dating and another title; preserve this early drawing and its literal evidence without inventing missing details of the existing work.',
102:'One anonymous/Le Brun expression print83.0.20, first-quarter nineteenth century, three anger heads on one12.8 by27.2cm sheet. Count one impression; old inventory521 versus inscribed529 remains unresolved source evidence. No matching anger/expression print in creator pool.',
104:'One Man Ray/Radinsky1936 Mme Tedesco ink portrait34.5 by25cm,2005.2.4. Existing Kiki and Marquis de Sade are different named sitters; Tedesco/Tedesko source spelling preserved.',
105:'One Marcoussis/Markus circa1930 three-figures pencil sheet18.5 by18.1cm,2001.3.26. Full maker pool has named still lifes, portraits and prints with different support formats; no three-figures counterpart.',
106:'One Mayo/Milliarakis1948 Profile oil canvas24 by19cm,2001.3.32, dedication to Jean-Louis Barrault and dated Paris reverse. Preserve both creator aliases; same-title Braque/Rouault works have different makers and media.',
109:'One Ivan Puni/Pougny1943 lady-with-hat-in-Nice gouache/pencil23 by16.5cm,2001.3.22. Expanded alias pool includes Russian titles;1914 portrait of the artist wife is another dated subject, other French figural examples are oil works. Literal Russian-born maker aliases retained.',
110:'One Odilon Roche early-twentieth-century female-nude watercolor/pencil18 by23cm,2002.3.3. Existing Two Nudes24.8 by32.4cm and Studies of Nude Dancers35.8 by26.2cm depict multiple figures and have different measured formats.',
115:'One anonymous eighteenth-century sanguine after Greuze82.1556,70 by54.9cm, blind-old-man head. Related Lucien print82.2046 differs in medium and size. Preserve conflicting source model references and anonymous-after label, not autograph attribution.',
118:'One Ingouf second-half-eighteenth-century engraved child head82.2074, plate15.5 by11.5cm, cahierA plate6. Different source plate/figure from82.2072 and82.0.0.827; full-scene Paralytic print is not this detail sheet.',
119:'One Girodet circa1783 Perseus/Medusa recto and helmeted-man verso sheet008.5.1.1/2,21.1 by40.2cm. Count one physical sheet. Existing Ulysses/Polyphemus charcoal25.7 by41.1cm is a different story/medium; no Perseus/Medusa counterpart in full creator pool.',
120:'One Lancelot/Dupuis1845 Dureau de la Malle tomb lithograph2024.2.3,26.5 by40.8cm. Individually inventoried illustration for the Orne volume, not the whole book; no named-tomb/native counterpart.',
121:'One Schwiter1843 Blanche de Triqueti oil canvas61 by50cm,2022.3.1, Salon1095 and documented family provenance. Existing Schwiter portraits depict men with different names/formats; source baron wording does not assign another maker.',
}
HOLDS={
1:'Duret bronze Saint Gabriel003.3.2: foundry/cast date and model-versus-cast identity need evidence before addition; companion Saint Michel is another inventory.',
2:'Girodet recto/verso male portrait study: existing generic male portraits include incomplete physical descriptions. Resolve the sitter/version before adding; one sheet would count once.',
3:'Janssens gallery874.62 and paired874.63 face existingb222a03e same creator/title with unknown physical dimensions. Reconcile both paintings and prior Dietrich attribution before creating another record.',
6:'Triqueti patinated plaster874.311: model/cast physical version remains unresolved; do not infer cast date from the model period.',
8:'Janssens gallery874.63 is paired with874.62, but existing same-titleb222a03e lacks physical details. No duplicate creation pending two-object reconciliation.',
11:'Noirot1909 Paysage has no detailed composition; existing Roanne gros-chene lead has unknown medium/dimensions and unverified1900 dating. Resolve image/composition before treating this generic landscape as distinct.',
13:'Anonymous eighteenth-century battle with partly illegible signature has multiple generic title leads; creator/version unresolved.',
14:'Anonymous seventeenth-century female portrait has unresolved sitter/coat of arms and many incomplete exact-title leads.',
21:'Decorchemont1877 bronze Chassant: actual cast date/version requires clarification, rather than treating a model date as the bronze creation date.',
24:'Attributed Ferdinand Elle portrait of Poussin includes contested attribution and annotation connecting other portraits/prints. Resolve specific drawing identity before adding.',
25:'Felon Three Graces is catalogued as drawing but source questions an underlying heliogravure; physical technique/version unresolved.',
29:'Attributed Goya undressing woman/La Mariee: uncertain signature and possible translated bride-title versions need further comparison.',
37:'Harpignies Menton watercolor faces an existing Menton olive-tree work without physical details; composition/version needs resolution.',
38:'Harpignies1897 Paysage wash faces incomplete same-creator generic landscapes; no automatic new object on title alone.',
39:'Anonymous-after-La-Tour Sebastian has Rouen/Orleans copy/prototype references and incomplete existing studio/autograph versions; resolve this canvas.',
45:'Ribot-after-Veronese draped figure has E. Ribot inscription versus Augustin Theodule maker label; preserve conflict pending creator/version research.',
46:'La Rome Antique7982;3325 has two current Joconde references, including candidate55, and existing same-title/creator aef85cd5-30a1-4d20-9a4d-007db29dee62. One object, no new record; Louis inscription versus Francisque label also unresolved.',
47:'Anonymous female portrait8079;2805 faces many generic incomplete portrait records; sitter/version unverified.',
50:'Harpignies1898 Paysage wash has same-creator generic incomplete landscape leads; sheet identity needs comparison.',
51:'Monnier masked woman1859 is close in format/subject to existing Femme en marmotte1839; resolve costume and signed dates before addition.',
54:'Queulvee pastel source explicitly disputes father/son sitter identity, while title and attribution labels differ. Keep research hold.',
55:'Duplicate reference for candidate46, same7982;3325 Rome canvas and existingaef85cd5-30a1-4d20-9a4d-007db29dee62. Do not count two source rows as two artworks.',
67:'Attributed Duplessis Bouchony portrait has ambiguous Denis Bonnet copy reference and former attribution. Resolve whether source describes this copy or a derivative version.',
68:'Anonymous Ecce Homo1757.1.82 has many same-title incomplete versions; paired Mater Dolorosa is a separate object, not evidence of uniqueness.',
69:'Arp1961 Alchimie Optique pencil51 by38cm is close in date/format to existing circa1960 untitled crayon46.8 by32.9cm; compare composition and sheet-versus-image measurements.',
73:'Chaissac shoe-imprint composition faces existing Untitled/Composition records without media/dimensions. Distinguish these before adding another version.',
75:'Cocteau Livre Blanc is a bound illustrated book in case, not one individual drawing. Physical-unit/type review required.',
76:'Del Marle1913 Catch study has existing generic Composition leads, including an undetermined first-half-twentieth-century work without physical metadata. Resolve composition/version.',
77:'David Menelaus/Patroclus drawing needs comparison with existing Patroclus lacking physical data. Shared2001-3-1 inventory with Cabanel in Evreux is a cross-museum false positive, not a same-object match; that does not resolve the creator/title lead.',
80:'Attributed Greuze Mme Abraham Piot portrait faces generic female portrait versions and uncertain attribution/dating; no new record yet.',
81:'After-Greuze masculine head is called drawing but has plate/cuve dimensions and sanguine-manner wording; technique/version unclear.',
82:'Badin-after-Greuze child head has unresolved maker identity and source creation chronology. Retain research hold.',
83:'Flipart Village Bride impression has several related inventories and existing Greuze prototype/version lacking physical metadata; reconcile edition and object identity.',
87:'Lasteyrie old-man lithograph has unresolved source period/impression chronology and generic head leads; do not infer a printing date.',
91:'Current Maury Rose1850?–1926 maker label conflicts with source eighteenth-century dating; two engraved heads are also classified as drawing. Preserve current/old labels and hold.',
92:'Anonymous-after-Greuze male-head counterproof requires original-versus-counterproof and generic portrait reconciliation.',
94:'Leroy tricorne print is dated eighteenth century but inscription says Greuze died1805. Actual impression cannot be assigned the source period without review.',
96:'Attributed Hondecoeter cockfight faces translated rooster/turkey-fighting leads with unknown physical details; larger measured versions alone do not resolve all candidates.',
99:'Le Corbusier Two Bottles watercolor faces existing Still Life without physical metadata; composition not securely distinguished.',
103:'Lingee print inscription names Mme Lingee and Terese Hemery; additional Hemery alias/creator scope needed before duplicate clearance.',
107:'Attributed Monnoyer vase-of-flowers canvas faces multiple incomplete same-creator flower versions; attribution and physical version remain uncertain.',
108:'Magnelli untitled1941 gouache has no composition description and several generic abstract/Gouache titles in creator pool. Physical counterpart comparison remains incomplete.',
111:'Attributed Schidone/Schedoni mother and child has many Madonna/Child versions with incomplete physical metadata; aliases checked but version unresolved.',
112:'Torres Garcia1930 locomotive/city drawing faces generic1931/1932 Composition records lacking dimensions/medium. Resolve these potential translated compositions.',
113:'Zadkine1964 Couple drawing faces existing1928 Couple a leventail under mistranslated English title and missing medium/dimensions. WikiArt confirms the earlier title/date but not enough physical evidence here to close version review.',
114:'Anonymous fifteenth-century Annunciation panel has same-period named-creator leads without physical details; compare composition before adding.',
116:'Attributed Greuze Chanoine Piot circa1745 portrait needs reconciliation with incomplete generic male-portrait versions and attribution.',
117:'Second Badin-after-Greuze child-head print has unresolved maker identity and source chronology; separate inventory does not settle eligibility.',
122:'Triqueti Monod plaster2022.4.1 has a former deposit number and current gift record; ownership changed but cast/model dating still needs review.',
123:'Coupin de la Couperie portrait medium says oil canvas while measurements identify paper/card supports; source physical-object conflict requires clarification.',
}
