"""Wave108 immutable evidence checkpoint; all-museum objective remains active."""
import hashlib,importlib.util,json
from pathlib import Path
z=importlib.util.spec_from_file_location('a',Path(__file__).with_name('museum-expansion-acropolis-more-apply-20261009.py'));a=importlib.util.module_from_spec(z);z.loader.exec_module(a);m=a.m;RUN=a.RUN
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 dest=RUN/'delivery-checkpoint-001.json';assert not dest.exists();report=m.load(RUN/'delivery-001.json');assert report['added']==75 and report['local_unchanged'];p,digest=a.validate_plan();prior=m.load(a.CHECKPOINT);checks=m.load(RUN/'checks-001.json');assert checks['replay_zero_writes']and checks['offline_tests_passed']==14
 root=m.RUN/'README.md';old=root.read_text();before=sha(root);oldpin=next(v for v in prior['artifacts']if v['path']==str(root.relative_to(m.ROOT)));assert oldpin['sha256']==before
 backup=m.BACKUP/'acropolis-more-root-readme-before-001.json';m.save(backup,dict(at=m.now(),text=old,sha256=before));title,body=old.split('\n\n',1)
 prefix='''The latest continuation added **75 further production review artworks to the Acropolis Museum**, taking it from **141 to 216 catalogue works** and from **135 to 208 date-eligible works**. This museum now exceeds the preferred 200-work target. [Delivery and combined source decisions](native/acropolis-more-20261009/README.md). The selected production phase totals **626 additions across five museums**. The real local catalogue remains read-only; the full all-museum objective remains active. Continue with the remaining museum register, beginning with Rhodes after institution and object checks.

'''
 root.write_text(title+'\n\n'+prefix+body.replace('The latest continuation added **116 production','The preceding continuation added **116 production',1));change=dict(path=str(root.relative_to(m.ROOT)),before_sha256=before,after_sha256=sha(root),backup_path=str(backup),backup_sha256=sha(backup));m.save(RUN/'readme-supersessions-001.json',dict(at=m.now(),changes=[change]))
 pins={v['path']:v for v in prior['artifacts']if v['path']!=change['path']};paths={root,a.CHECKPOINT,Path(__file__).resolve()}|{v for v in RUN.rglob('*')if v.is_file()}|{v for v in(m.ROOT/'ops').glob('*acropolis*20261009.py')}|{m.ROOT/v['path']for v in p['evidence']}
 for path in sorted(paths):
  ref=a.reference(path);assert ref['path']not in pins or pins[ref['path']]==ref;pins[ref['path']]=ref
 external={v['path']:v for v in prior['external_artifacts']}
 for path in sorted(m.BACKUP.glob('acropolis-more-*.json*')):external[str(path)]=dict(path=str(path),sha256=sha(path))
 for ref in p['external_evidence']:assert sha(Path(ref['path']))==ref['sha256'];external[ref['path']]=ref
 for path in sorted((Path.home()/'Library/Application Support/Artline/research-proofs/acropolis-more-20261009').glob('*')):
  if path.is_file():external[str(path)]=dict(path=str(path),sha256=sha(path))
 next_work='''Wave108 verified progress: 75 further production Acropolis additions, 141 to216 catalogue and135 to208 date eligible. Institution dbf69208-06db-516d-ae7d-adce63c6cadc now exceeds200 in both measures. 73 new eligible; two open after dates (Nike Acr.690 and Kritios Boy Acr.698) remain in review outside automatic eligibility. Acropolis passes total191 new, selected production phase626 new across five museums. Real LOCAL0/0 unchanged. Full all-museum objective active, not complete or blocked.
Next prioritize Municipal Art Gallery of Rhodes, IID f02b4c48-dd69-5319-8d22-e0de34436933, slug wikimedia-museum-q66058061. Last inherited global audit observed21 catalogue/15 eligible; recheck live baseline and possible duplicate institutions/venue boundaries before assignment. Official https://mgamuseum.gr/en/ and /en/permanent-collection/ link https://portal.mgamuseum.gr/ . All three accessible200; captures and next-museum-rhodes-discovery-001.json.gz in this RUN. Portal is Angular shell; public main.43d780f16ef2594a.js was captured as rhodes-portal-main-js-001.body.gz. Frontend calls https://repox.mgamuseum.gr/api public collection endpoints with its published client header configuration. First public children page returned200 and1502 total objects (20 per page,76 pages), parent37532a1a-6753-4111-8b0b-434cb8131deb. Evidence next-museum-rhodes-public-index-001.json.gz and next-museum-rhodes-js-discovery-001.json. Use only intended public endpoints; do not log client authorization values or propagate irrelevant publisher/admin identity fields. createdAt/updatedAt are repository timestamps, NOT artwork creation dates. The published frontend also exposes GET /v2/public/containers/{uuid} and POST /public/containers/search?page=&size=; inspect normal query shape before bounded dated selection. No individual Rhodes detail or image fetched. SearchCulture collection identifier TehnisRodou, example object https://www.searchculture.gr/aggregator/edm/TehnisRodou/000188-f5906f73-e605-4f40-bc07-a08671e881c7 is a2009 Vlazakis drawing and outside cutoff, NOT eligible simply because it depicts the museum. Museum website includes150 artists and post1970 works; creator lifespan is not artwork date. Verify institution mapping between Municipal Art Gallery, Museum of Modern Greek Art, Nestorideion Melathron and other venues. No Rhodes object additions yet. Keep all other Greek/Cypriot/Russian priorities and the complete museum register in scope.
Acropolis wave108 examined84 detail pages (76 followup index leads plus8 deferred heads),31 Greek fallback narratives;75 new and9 holds. Current combined255-source ledger:75new,116previous-wave additions,9initialknown,13total holds and42deferred fragments. Source reports256, one index discrepancy remains. No exhaustive further download needed after reaching200. New holds67 Athena headAcr661 linked possibly torso159/hand338;146 BlondeBoyAcr689 disputed torso6478;185 RampinRiderAcr590 headcast originalLouvre;188 ScribeAcr629 Fauvelheadcast originalLouvre;190 seatedgoddessAcr618 formerlylinked alreadycataloguedheadAcr659;215plinthAcr431 and241HeraklestorsoAcr638 possible samegroup;230unassignedriderhandAcr4330;231armAcr4246 ascribed to addedKourosAcr665. Prior fourholds remain, but Athena torsoAcr293 added here, so priorheldheadAcr658 must reconcile with this record before futureimport. NewAcr142Athena and priorAcr697horse possibly samepediment but distinctfigures, no completeparent added. GroupsHekateNMA166,ProkneItysAcr1358,AphroditeErosNMA294,NikeAcr690 pluscolumn countonce. Three unfinishedworkshophands NMA2517rightfemale,NMA160leftmale,NMA3593right are distinct physical pieces with no invented parent. Roman physical dates retained; BC/ADcentury envelopes and unknowns not overwritten. Euenor maker/Angelitos dedicator; PotterReliefAcr1332 Endoios inscription vs PhysiciansReliefEAM1332 separate namespace. EndoiosAthena,AlcamenesProkne,KritiosBoy attributed labels. ExistingHermesAcr2281alpha distinct newAcr14877; ClevelandHarpocratesbronzes distinct newNMA1807marble; SolomkoScribe/PiranesiSilenus are differentartworks.
Fourteen offline tests passed; backup, atomic readback and zero-write replay completed.144 protected existing rows,551 earlier production additions preserved;1019 identity candidates and320 supplementary full snapshots checked. No images, artist links, publication/display changes, merges or existing metadata edits. Only Acropolis register row refreshed to216/208; threshold columns cap200 and all other observations retain dates. Source access available; earlier provider holds persist. Inherit pinned wave101 historical proof; validate only new/superseded pins, do not reread archived35000files or mutate real LOCAL.'''
 result=dict(prior);result.update(at=m.now(),goal_complete=False,previous_goal_turn='progress',production_only=True,local_unchanged=True,new_additions=75,new_existing_links=0,verification=report['verification'],production_museum_before=report['museum_before'],production_museum_after=report['museum_after'],production_campaign_totals=dict(new_artworks=626,existing_links=0,museums=5),global_production_counts_refreshed=False,global_production_thresholds_refreshed=False,new_tests_passed=14,plan_sha256=digest,artifacts=list(pins.values()),external_artifacts=list(external.values()),prior_checkpoint_reference=a.reference(a.CHECKPOINT),baseline_reference=a.reference(RUN/'baseline-verification-001.json'),intentional_supersessions=[change],review_reference=a.reference(a.REVIEW),remaining_research_reference=a.reference(RUN/'all-source-decisions-001.csv'),production_institution_register_reference=a.reference(RUN/'production-institution-register-001.json.gz'),priority_museum_queue_reference=a.reference(RUN/'priority-museum-queue-001.json'),global_threshold_summary_note='Inherited wave104 global snapshots. Individual Acropolis row refreshed to216/208 in this wave; other observations retain timestamps.',source_availability=report['source_access'],next_work=next_work)
 m.save(dest,result);oldpins={v['path']:v for v in prior['artifacts']};oldext={v['path']:v for v in prior['external_artifacts']};newpins=[v for v in result['artifacts']if oldpins.get(v['path'])!=v];newext=[v for v in result['external_artifacts']if oldext.get(v['path'])!=v]
 for v in newpins:a.checked(v)
 for v in newext:assert sha(Path(v['path']))==v['sha256']
 m.save(RUN/'final-checkpoint-verification-001.json',dict(at=m.now(),checkpoint=a.reference(dest),verified_new_or_superseded_artifact_pins=len(newpins),verified_new_external_pins=len(newext),inherited_unchanged_artifact_pins=len(result['artifacts'])-len(newpins),inherited_unchanged_external_pins=len(result['external_artifacts'])-len(newext),full_historical_proof=prior['initial_full_historical_verification_reference'],plan_sha256=digest,goal_complete=False));print(json.dumps(dict(checkpoint=a.reference(dest),artifacts=len(pins),external_artifacts=len(external),verified_new=len(newpins),verified_external=len(newext))),flush=True)
if __name__=='__main__':main()
