"""Document wave84 and preserve unresolved Ferens and nationwide queues."""
import hashlib,importlib.util,json
from pathlib import Path
z=importlib.util.spec_from_file_location('a',Path(__file__).with_name('museum-expansion-ferens-apply-v3-20261009.py'));a=importlib.util.module_from_spec(z);z.loader.exec_module(a);m=a.m
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 report=m.load(m.RUN/'verification-after-wave-84.json');assert(report['verified_new_artworks'],report['verified_existing_artworks_linked'],report['institutions_with_new_records_or_reconciled_holdings'])==(10395,2119,226);plan,digest=a.validate_plan()
 with m.connect() as db:verified=a.verify(db,plan,digest)
 cp=m.load(a.CHECKPOINT);root=m.RUN/'README.md';pin=next(v for v in cp['artifacts'] if v['path']==str(root.relative_to(m.ROOT)));assert sha(root)==pin['sha256'];backup=m.BACKUP/'ferens-root-readme-before-001.json.gz';assert not backup.exists()
 for n in ['checks-001.json','remaining-research-001.json.gz','next-museum-pass-001.json','README.md','readme-supersessions-001.json','source-availability-001.json']:assert not(a.RUN/n).exists()
 logsroot=Path('/Users/vadimdulub/Library/Logs');test=(logsroot/'artline-ferens-tests-v3-20261009.log').read_text();assert 'Ran 23 tests' in test and test.rstrip().endswith('OK');assert(logsroot/'artline-ferens-replay-v3-20261009.log').read_text().strip()=='Unchanged replay: zero writes'
 logs={v.name:dict(path=str(v),sha256=sha(v)) for v in sorted(logsroot.glob('artline-ferens-*-20261009.log')) if 'delivery' not in v.name and 'checkpoint' not in v.name}
 m.save(a.RUN/'checks-001.json',dict(at=m.now(),new_offline_tests_passed=23,historical_tests_passed=1615,cumulative_verified_tests=1638,historical_tests_rerun=False,initial_20_tests_rerun_in_final_23=True,replay_zero_writes=True,source_objects_reviewed=180,new_artworks=136,existing_links=0,editorial_holds=44,logs=logs,other_job_totals_separate=True,source_capture_failures=0,initial_transaction_rolled_back=True,repair='Preserve actual HTTP native object URLs in citations/identifiers/holding notes; schema-constrained holding source_url uses verified official HTTPS collection page linking to native catalogue. No schema change or invented HTTPS object URL. Second write attempt rolled back on ISO timezone spelling comparison; timezone-aware instant comparison now preserves exact source times. Initial identity name query stopped at20000 unlinked bound; surname/alias search completed19576 artworks.'))
 m.save(a.RUN/'source-availability-001.json',dict(at=m.now(),new_source_access_holds=[],previous_source_hold_reference=cp['new_source_access_hold_reference'],holding_source_reference=a.reference(a.RUN/'holding-source-001.json'),next_source_probe_reference=a.reference(a.RUN/'next-source-probes-001.json'),policy='Official HTTPS collection page publishes HTTP native catalogue. Guildhall official collection landing page200 captured; Salford old collection link redirects to404, not an access denial. Stale Ferens search-result URL404 retained; observed current collections-ferens URL200 verified. No denied source retried. All prior access holds persist.'))
 held=[v for v in m.load(a.REVIEW)['decisions'] if v['state']=='editorial_hold'];assert len(held)==44
 m.save(a.RUN/'remaining-research-001.json.gz',dict(at=m.now(),rows=held,review_reference=a.reference(a.REVIEW),previous_remaining_research_reference=cp['remaining_research_reference'],existing_hull_reconciliation_reference=a.reference(a.RUN/'existing-hull-reconciliation-001.json'),source_availability_reference=a.reference(a.RUN/'source-availability-001.json'),policy='44 unresolved source/attribution/date/version/duplicate cases. Three exact existing Hull inventory matches201/203/204 need museum reconciliation; no accepted or pending museum assignment was found in a scoped read-only check. Native source covers1252 painting results;288 index rows reviewed,180 details selected. Untouched source remainder is not reviewed artwork coverage. Earlier queues remain active.'))
 oldq=m.load(a.checked(cp['next_museum_pass_reference']));live=m.load(m.RUN/'after-wave-84.json');by={v['id']:v for v in live['institutions']};italian=[dict(v,current_linked=by[v['institution_id']]['works'],current_eligible=by[v['institution_id']]['eligible_works']) for v in oldq['italian_museums']];assert len(italian)==225;targets=[by[k] for k in ['c519fc6e-b9b4-5037-a4b4-6d4f4a479157','03058adb-4b2a-5a45-849d-2393f4229f9b']]
 m.save(a.RUN/'next-museum-pass-001.json',dict(at=m.now(),previous_queue_reference=cp['next_museum_pass_reference'],italian_museums=italian,existing_holding_review_targets=targets,next_source_probe_reference=a.reference(a.RUN/'next-source-probes-001.json'),native_addition_targets=[],remaining_research_reference=a.reference(a.RUN/'remaining-research-001.json.gz'),current_museums=[by[a.IID]],source_availability_reference=a.reference(a.RUN/'source-availability-001.json'),policy='Ferens now228 linked/215 eligible,preferred200 reached. Continue Salford101 pending and Guildhall100 pending; retain Ferens44 held objects including three existing Hull accession matches. RWA139 linked/15 eligible remains a date/source gap. Preserve225 Italian museums and every earlier research/source hold. Full all-museum goal remains unfinished.',database_writes=0))
 text=f'''# Ferens native additions — 9 October 2026

Added **136 source-backed artworks** to the local review catalogue. Ferens now has **228 linked records, 215 with eligible creation dates**, up from 92 and 79. The preferred 200-record target is reached. The 13 older unknown dates remain unchanged; totals are catalogue records, not a new physical-object validation of every legacy entry.

The selected additions include two nineteenth-century **Russian School icons**, *St John Damaskinos (Damascene) with the Virgin (Hodogetria)* and *The Birth of the Virgin*. Named, anonymous, school and qualified creator labels remain explicit. No painter records or artist links were invented.

The [official Ferens collection page](https://www.hullmuseums.co.uk/collections-ferens) explicitly links to the [native public catalogue](http://museumcollections.hullcc.gov.uk/). A bounded survey inspected **288 short index entries from 1,252 painting results**, selected 180 objects, then captured their complete accession-level metadata. No images were downloaded. This is selected artwork coverage, not an exhaustive collection download.

Fresh identity review covers **19,576 existing artworks and 41,917 citations**. Forty-four cases remain [held for research](remaining-research-001.json.gz), including possible Champaigne, Constable, Ruisdael and Wilson versions; inconsistent native creators or dates; and exact existing Hull accession matches. The three Widdas matches already have artwork records but no museum assignments in the scoped query; Streetlife was not established. They were not duplicated.

Source descriptions preserve stronger qualifications than the structured maker field: attributed Richardson and Roberts, an unknown copyist after Reynolds, a follower of Beccafumi and a West copy after Reni. Rathbone's repeated lifespan is replaced only for these new records by the explicit native creation statement “late eighteenth century,” with full-century search bounds. Storck uses the explicit seventeenth-century creation statement. Conflicting source fields remain in citations. Historical events, prototypes and later inscriptions are not creation dates.

The three-panel ensemble by a follower of Beccafumi is represented once. Paton's signed 1872 preliminary oil-panel study and the separate circa-1877 life-size canvas have distinct accessions, supports, dimensions and an explicit source relationship. No unselected second study mentioned by the source was invented. The two Hardey Wright portraits retain separate inventories and described poses. Undated legacy display labels remain evidence, not current on-view claims.

The initial write transaction **rolled back completely** because holding URLs require HTTPS. The [source-chain repair](holding-source-001.json) uses the genuinely fetched HTTPS collection landing page for that field; exact HTTP object URLs remain in identifiers, citations and holding notes. No HTTPS object URL was manufactured and no database constraint changed. The retry also rolled back on equivalent ISO timezone spellings; the verifier now compares timezone-aware instants. All three plans and both failed transaction logs remain audit evidence.

The [applied plan](ferens-native-additions-001-plan-003.json.gz) and [transaction receipt](ferens-native-additions-001-applied.json) verify 136 distinct new inventories, citations and accepted holding assertions. **23 offline tests, atomic readback and zero-write replay passed.** All {verified['protected_existing_records']:,} scoped existing records and all 12,378 earlier campaign artworks were protected. Existing metadata, images, creator links, statuses and institution records remain unchanged. No commit, deployment or production change.

Campaign total: **10,395 new artworks plus 2,119 reconciled existing records**, or **12,514 distinct records across 226 institutions**. The latest audit still has **{report['after']['museums_below_100']:,} museums below 100 linked records** and **{report['after']['museums_below_200']:,} below 200**. [Salford and Guildhall are next](next-museum-pass-001.json); all earlier museum queues and access holds remain. The nationwide goal is unfinished.
'''
 m.save(backup,dict(at=m.now(),path=str(root),text=root.read_text(),sha256=sha(root)));(a.RUN/'README.md').write_text(text)
 old=root.read_text();intro,rest=old.split('## Added works',1);intro=intro.replace('10,259','10,395').replace('211 local museums','212 local museums').replace('1,237',f"{report['after']['museums_below_100']:,}").replace('after-wave-83','after-wave-84');rest=rest.replace('| Distinct new-record campaign total | **10,259** | **212 collections** |','| Ferens Art Gallery — selected native paintings, watercolors and icons | 136 | 1 museum |\n| Distinct new-record campaign total | **10,395** | **213 collections** |');root.write_text(intro+'## Added works'+rest+'\n\n## Ferens native additions — wave84\n\nAdded 136 review artworks, including two Russian icons. Ferens now has 228 linked records and 215 eligible dates; 44 source/identity cases remain held. [Review and evidence](native/ferens-additions-20261009/README.md). Campaign total: 10,395 new artworks and 2,119 reconciliations across 226 institutions. The all-museum 100–200 goal remains unfinished.\n')
 m.save(a.RUN/'readme-supersessions-001.json',dict(at=m.now(),changes=[dict(path=str(root.relative_to(m.ROOT)),before_sha256=pin['sha256'],after_sha256=sha(root),backup_path=str(backup),backup_sha256=sha(backup))]));print(json.dumps(dict(documented_new_records=136,held=44,tests=23,goal_complete=False)),flush=True)
if __name__=='__main__':main()
