"""Document wave71 with backed-up campaign README and preserved earlier evidence."""
import collections,hashlib,importlib.util,json
from pathlib import Path
s=importlib.util.spec_from_file_location('a',Path(__file__).with_name('museum-expansion-france-sixteenth-apply-20261008.py'));a=importlib.util.module_from_spec(s);s.loader.exec_module(a);m=a.m
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
    report=m.load(m.RUN/'verification-after-wave-71.json');assert report['verified_new_artworks']==9458;plan,digest=a.validate_plan()
    with m.connect() as db:verified=a.verify(db,plan,digest)
    logsroot=Path('/Users/vadimdulub/Library/Logs');prefix='artline-france-sixteenth-';testlog=(logsroot/(prefix+'release-tests-20261008.log')).read_text();assert 'Ran 9 tests' in testlog and testlog.rstrip().endswith('OK');assert (logsroot/(prefix+'replay-20261008.log')).read_text().strip()=='Unchanged replay: zero writes'
    ds=m.load(a.REVIEW)['decisions'];states=collections.Counter(d['state'] for d in ds);assert states=={'approved_review_only_addition':121,'editorial_hold':60,'deferred_identity_review':178}
    logs={p.name:dict(path=str(p),sha256=sha(p)) for p in sorted(logsroot.glob(prefix+'*-20261008.log')) if p.name not in [prefix+'delivery-20261008.log',prefix+'checkpoint-20261008.log']}
    target=a.RUN/'checks-001.json';assert not target.exists();m.save(target,dict(at=m.now(),new_offline_tests_passed=9,historical_tests_passed=1399,cumulative_verified_tests=1408,historical_tests_rerun=False,replay_zero_writes=True,source_facts_reparsed=359,comparisons_recomputed=True,added=121,editorial_holds=60,deferred_identity_candidates=178,logs=logs,all_workers_completed=True,other_job_totals_separate=True))
    changes=report['france_sixteenth_museum_changes'];table='| Museum | Added | Linked before → after | Eligible before → after |\n| --- | ---: | ---: | ---: |\n'+'\n'.join('| '+v['name']+' | '+str(v['new'])+' | '+str(v['linked_before'])+' → '+str(v['linked_after'])+' | '+str(v['eligible_before'])+' → '+str(v['eligible_after'])+' |' for v in changes if v['new'])
    after=report['after'];expanded=report['institutions_with_new_records_or_reconciled_holdings'];types=collections.Counter(v['facts']['work_type'] for v in plan['records'])
    readme=a.RUN/'README.md';assert not readme.exists()
    readme.write_text('''# Sixteenth French museum pass — Écouen and Cognacq-Jay

Added **121 real local artworks**, all in review: **119 at the Musée national de la Renaissance, Écouen, and 2 at Cognacq-Jay**. Écouen now exceeds the 100-work minimum. The all-museum 100–200 objective remains active.

'''+table+'''

Types: '''+', '.join(str(v)+' '+k for k,v in sorted(types.items()))+'''. Source periods are preserved; no sitter, acquisition or restoration date was substituted for creation. Unknown makers, materials and dimensions remain unknown. Anonymous, school, workshop and attributed makers are supported as object-level labels without invented painter authorities. Holdings are separate from current display.

The fresh identity scope covers **44,678 artworks and 96,226 citations** for the 359 notices remaining after wave70. All 359 source facts, comparisons and within-batch groups were independently recomputed. Physical-material triage retains literal primary records and individual reasons. Date-only triage cases for the Écouen release were also inspected for object-form/material distinctions; sparse named-creator title matches retain their uncertainty and were not promoted into newly verified holdings. Historical aliases and component relationships were searched separately. The two-piece CL15226/15227 and sleeping-ivory questions remain held/deferred.

Two selected WikiArt images were downloaded and visually inspected only as identity references: the broken Desiderio Virgin relief differs from Écouen’s full-length 92 cm statue, and the c.1748 Pompadour head differs from Cognacq-Jay’s 1742 Rieux portrait in ball costume. No catalogue images were attached. Exact primary NG2092 metadata distinguishes Moretto’s painted shutter from a carved wooden Saint Joseph. Preserved Finnish National Gallery object 390567 / AI548 differs in size and provenance from Cognacq-Jay J15. The J15 label now explicitly separates the French-school copy, Boucher model author and former workshop attribution; the national export remains verbatim in its citation.

The Louvre OA428 page corroborates ECL22280/Anne de Montmorency but gives historical CL22278, overlapping another selected wax portrait. Both candidates 584/586 are held until this cross-record alias is resolved; the 12 cm / 10 cm measurement discrepancy is preserved without guessing a frame measurement. Other wax sitter/date conflicts, structural furniture supports and unresolved sparse comparator identities remain visible. **60 notices are held and 178 deferred** across the remaining five-museum research queue. Earlier wave70’s 291 additions are excluded from this release.

Selected carved furniture panels are independently catalogued physical pieces. The source records describe the former buffet as dismantled; neither the whole furniture assembly nor depicted figures were added as extra artworks. CL/ECL inventory variants and old Louvre provenance remain literal, without changing legal ownership or making current-display claims.

The [review](editorial-reviewed-001.json.gz), [comparison coverage](supplemental-review-001.json.gz), [transaction plan](france-sixteenth-additions-001-plan.json.gz), [application receipt](france-sixteenth-additions-001-applied.json), [wave71 verification](../../verification-after-wave-71.json) and [delivery checkpoint](delivery-checkpoint-001.json) preserve the result and limitations. Exact readback checked 121 artworks, identifiers, citations and accepted holding assertions. All 570 initial target records, 3,161 protected comparison records and 10,122 earlier campaign records were preserved. Replay wrote nothing. Nine offline release checks passed; 1,399 historical checks remain pinned, not rerun. These checks are not evidence of ten-million-row query performance.

Campaign totals are **9,458 additions and 785 existing-record holding links across '''+str(expanded)+''' expanded institutions**. The current register still has **'''+str(after['museums_below_100'])+''' canonical museums below 100 linked works and '''+str(after['museums_below_200'])+''' below 200**. Eligible dates, linked counts, images and publication remain separate measures. Registry changes outside this batch are recorded in [coverage-registry-growth-001.json](coverage-registry-growth-001.json) and are not credited to the campaign.

Continue Cognacq-Jay toward 100–200, the remaining Écouen identities and the wider registry. Candidate 458 still needs its full generic portrait review; source details for 470, 398/490 and the old Louvre wax numbers are preserved for follow-up. Current access holds include the Met object 339838 HTTP429, Baltimore429, OrsayCoubertin403, the prior Hugo timeout and the Bourges city article403; no retry or bypass. Independent previously captured evidence may still be used. The separate minimum-100 job remains terminal and separately counted. No commits or deployment.
''')
    root=m.RUN/'README.md';cp=m.load(a.CHECKPOINT);pin=next(v for v in cp['artifacts'] if v['path']==str(root.relative_to(m.ROOT)));assert sha(root)==pin['sha256'];before=root.read_text();backup=m.BACKUP/'france-sixteenth-root-readme-before-001.json.gz';assert not backup.exists();m.save(backup,dict(at=m.now(),path=str(root.relative_to(m.ROOT)),sha256=sha(root),text=before))
    split=before.index('\n## Added works');intro=before[:split].replace('9,337','9,458').replace('197 local museums',str(report['museums_expanded'])+' local museums').replace('expand 200 institutions','expand '+str(expanded)+' institutions').replace('1,257',format(after['museums_below_100'],',')).replace('after-wave-70','after-wave-71')
    lines=before[split:].splitlines();ix=next(i for i,v in enumerate(lines) if v.startswith('| Joconde — fifteenth pass'));lines.insert(ix+1,'| Joconde — sixteenth pass, Écouen and Cognacq-Jay | 121 | 2 museums, 2 newly expanded |');ix=next(i for i,v in enumerate(lines) if v.startswith('| Distinct new-record campaign total |'));lines[ix]='| Distinct new-record campaign total | **9,458** | **'+str(report['institutions_expanded'])+' collections** |'
    root.write_text(intro+'\n'.join(lines)+'\n\n## Sixteenth pass — Écouen and Cognacq-Jay\n\nThe [sixteenth pass](native/france-sixteenth-minimum-20261008/README.md) added **121 review records**, bringing Écouen to 119 eligible artworks.\n\n'+table+'\n\nExact readback, nine offline release safeguards and a zero-write replay passed. The current [wave71 verification](verification-after-wave-71.json) records **9,458 additions and 785 holding reconciliations across '+str(expanded)+' institutions**. '+format(after['museums_below_100'],',')+' canonical museums remain below 100 linked works; the broader goal remains active. The five-museum research queue retains 60 held and 178 deferred notices.\n')
    m.save(a.RUN/'readme-supersessions-001.json',dict(at=m.now(),changes=[dict(path=str(root.relative_to(m.ROOT)),before_sha256=pin['sha256'],after_sha256=sha(root),backup_path=str(backup),backup_sha256=sha(backup))],policy='Only the campaign README superseded; the original is preserved in Library. Prior delivery evidence unchanged.'))
    print(json.dumps(dict(documented=121,campaign_total=9458,expanded=expanded,remaining_below100=after['museums_below_100'])),flush=True)
if __name__=='__main__':main()
