"""Protect title/creator comparators, including translated titles checked visually."""
import importlib.util,json,re
from pathlib import Path
z=importlib.util.spec_from_file_location('i',Path(__file__).with_name('museum-expansion-rhodes-more-identity-20261009.py'));i=importlib.util.module_from_spec(z);z.loader.exec_module(i);m=i.m;RUN=i.RUN
x=m.load(RUN/'production-identity-001.json.gz');ids={a['id']for c in x['comparisons']for a in c['hits']};links={}
for v in x['state']['links']:links.setdefault(v['artwork_id'],[]).append(v['display_name'])
for a in x['state']['artworks']:
 c=m.norm(a['unlinked_creator_label']or','.join(links.get(a['id'],[])))
 if re.search('semert|σεμερτ|asteriad|αστεριαδ|spyros vas|spiros vas|σπυροσ βασιλει|vakalo|βακαλο|grammat|γραμματ|parthen|παρθεν|basald|lidio|pentzi|πεντζ|lagana|λαγαν|bexiari|bekiari|μπεκιαρ|arliot|αρλιωτ|zepos|ζεπο|kontopoul|κοντοπουλ|βακιρτ|vakirt|smaragda|σμαραγδ|angelid|αγγελιδ|δημητρησ δαβ|dimitris dav',c,re.I):ids.add(a['id'])
ids=sorted(ids)
with i.prod.connect()as db,db.transaction():
 db.execute('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ,READ ONLY');snap=i.s.snapshot(db,ids)
m.save(RUN/'subject-comparators-001.json.gz',dict(at=m.now(),ids=ids,snapshot=snap,identity_reference=i.s.ref(RUN/'production-identity-001.json.gz'),script_reference=i.s.ref(Path(__file__).resolve()),assessment='Exact SearchCulture/native object158 is already catalogued and skipped. Inventory1018 Asteriadis1948 oil63x90cm is distinct from existing1002 tempera23x34.5cm. Semertzidis5020 mixed-media1966 landscape73x125cm differs from existing5037 ink-marker1967 drawing50x70cm. His large1946 partisan study5031 differs from print4131;1945 full-length Vlacha5032 differs from etched1947 head4140. His studies and sketches are individually inventoried physical supports; no finished painting, mural or complete-series parent is newly asserted. Source131/132 are different men in blue versus white shirts, although dimensions and titles agree. Kontopoulos One country1959 existing57e9f3eb is a sparse red-green drawing on pale paper; native1323 is a dense cream/black/red/blue oil painting1958. The related composition does not make these physical objects identical. Parthenis existing48ab45d0 is a wide still life with pears,bottles,glass,basket and blue framed rectangle; native1603 is a square oil with porcelain lidded dish and one pomegranate. See four selected visual references and visual-assessment receipt. Other existing Kontopoulos abstractions lack same native ID,title or physical evidence; no authority merge. Afro existing postwar paintings are distinct from four separately inventoried1938 wooden season panels. Existing Ghika/Oikonomou still lifes, Zongolopoulos landscapes, Miliadis flowers, Lekakis sculptures and ASFA orphan abstract painting differ in creators, objects, supports and subjects. Semertzidis ploughing is a1946 linocut, not Asteriadis before1948 watercolour. Romako inventory5032 and vanDyck inventory1038 are cross-museum number collisions. All source,metadata,media,status and holding rows protected.',read_only=True));print(json.dumps(dict(protected_comparators=len(ids))),flush=True)
visual=m.load(RUN/'visual-reference-captures-001.json');m.save(RUN/'visual-assessment-001.json',dict(at=m.now(),reference=i.s.ref(RUN/'visual-reference-captures-001.json'),images_seen=[dict(number=v['number'],provider=v['provider'],path=v['receipt']['path'],sha256=v['receipt']['sha256'])for v in visual['rows']],assessments=[dict(number=192,existing_id='57e9f3eb-37e9-5384-9510-cf8df46619f3',decision='distinct_physical_version',basis='Native dense painted cream upper field,black central opening,red right block and blue lower band; WikiArt sparse red-green sketch on pale paper with wide paper margins and a1959 signature. Related composition; different medium/state and surface. Native1958 preserved.'),dict(number=211,existing_id='48ab45d0-4a10-5c55-949b-7b73ada7bbc1',decision='different_composition',basis='Native near-square lidded porcelain dish at left and single pomegranate at right. WikiArt wide still life with pears,basket,bottles,stemmed glass and a blue rectangle. Distinct depicted objects and layout; native1930–1934 retained.')],policy='Four bounded reference-image reads, no new production images or local catalogue writes. WikiArt approval and actual Fair Use labels retained; museum CC0 label remains a source statement.'))
