"""Freeze City Art Centre accounting, preserved evidence, access holds and continuing queue."""
import collections,gzip,hashlib,importlib.util,json,shutil
from pathlib import Path
z=importlib.util.spec_from_file_location('a',Path(__file__).with_name('museum-expansion-city-art-additions-apply-20261009.py'));a=importlib.util.module_from_spec(z);z.loader.exec_module(a);m=a.m;RUN=a.RUN;ref=a.reference;sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 report=m.load(m.RUN/'verification-after-wave-99.json');assert(report['verified_new_artworks'],report['verified_existing_artworks_linked'])==(10889,3036);cp=m.load(a.CHECKPOINT);applied=m.load(RUN/(a.KEY+'-applied.json'));assert applied['created']==14 and applied['existing_links']==1 and applied['verification']==report['city_art_additions'];root=m.RUN/'README.md';pin=next(v for v in cp['artifacts'] if v['path']==str(root.relative_to(m.ROOT)));assert sha(root)==pin['sha256'];backup=m.BACKUP/'city-art-additions-root-readme-before-001.json.gz';assert not backup.exists()
 for name in ['checks-001.json','remaining-research-001.json.gz','next-museum-pass-001.json','README.md','readme-supersessions-001.json','source-availability-001.json','new-source-access-holds-001.json']:assert not(RUN/name).exists()
 logsroot=Path('/Users/vadimdulub/Library/Logs');test=(logsroot/'artline-city-art-additions-tests-20261009-001.log').read_text();assert 'Ran 22 tests' in test and test.rstrip().endswith('OK');assert(logsroot/'artline-city-art-additions-replay-20261009-001.log').read_text().strip()=='Unchanged replay: zero writes';logs={p.name:dict(path=str(p),sha256=sha(p)) for p in sorted(logsroot.glob('artline-city-art-additions-*-20261009-*.log')) if not any(t in p.name for t in ['delivery','checkpoint'])};ctx=m.load(RUN/'comparison-source-context-002.json.gz');identity=m.load(RUN/'identity-002.json.gz');citations=m.load(RUN/'identity-citations-002.json.gz');ds=m.load(a.REVIEW)['decisions'];caps=[]
 for p in sorted(list(RUN.glob('*/captures/*.json'))+list(RUN.glob('documents/*.json'))):
  rc=m.load(p);body=p.with_suffix('.body.gz');assert hashlib.sha256(gzip.decompress(body.read_bytes())).hexdigest()==rc['sha256'];caps.append(dict(receipt_reference=ref(p),body_reference=ref(body),url=rc['url'],status=rc['status']))
 m.save(RUN/'checks-001.json',dict(at=m.now(),new_offline_tests_passed=22,historical_tests_passed=1983,cumulative_verified_tests=2005,historical_tests_rerun=False,replay_zero_writes=True,selected_candidates=21,new_artworks=14,existing_links=1,already_catalogued=0,editorial_holds=6,source_fact_holds=5,unknown_date_additions=3,date_eligible_additions=11,date_eligible_existing_links=1,identity_artworks=len(identity['state']['artworks']),identity_citations=len(citations['citations']),capture_status_counts=dict(collections.Counter(str(v['status']) for v in caps)),comparison_raw_bodies=len(ctx['body_references']),comparison_unreconstructed_citations=len(ctx['unreconstructed_bodies']),extra_physical_comparison_reference=ref(RUN/'physical-object-review-001.json.gz'),logs=logs,other_job_totals_separate=True))
 proofdir=Path('/Users/vadimdulub/Library/Application Support/Artline/research-proofs/city-art-additions-20261009');proofdir.mkdir(parents=True,exist_ok=True);proofs=[]
 vis=m.load(RUN/'newsletter-visual-review-001.json');thumbnail=m.load(RUN/'selected-image-reference-001.json')
 for v in vis['rendered_proofs']+[thumbnail]:
  p=Path(v['path']);assert sha(p)==v['sha256'];target=proofdir/p.name;assert not target.exists();shutil.copyfile(p,target);proofs.append(dict(path=str(target),sha256=sha(target),page=v.get('page')))
 m.save(RUN/'retained-research-proofs-001.json',dict(at=m.now(),external_artifacts=proofs,visual_review_reference=ref(RUN/'newsletter-visual-review-001.json'),thumbnail_reference=ref(RUN/'selected-image-reference-001.json'),policy='Six source-PDF page proofs andone300pxcopyright-labelledreference outsideDocuments. Researchonly;notcatalogueimages. Existingtenlocalartassetsremainunchanged.'))
 holds=[dict(provider='National Galleries of Scotland',host='www.nationalgalleries.org',status=403,url=v['url'],receipt_reference=v['receipt_reference'],reason='ExplicitHTTP 403onselectedpubliccomparisonobject;stophostrequests. Noalternateendpoint/proxyretry. Secondselectedobjectunrequested.') for v in caps if v['status']==403];assert len(holds)==1
 m.save(RUN/'new-source-access-holds-001.json',dict(at=m.now(),rows=holds,previous_source_hold_reference=cp['new_source_access_hold_reference']))
 m.save(RUN/'source-availability-001.json',dict(at=m.now(),new_source_access_holds=holds,new_source_access_hold_reference=ref(RUN/'new-source-access-holds-001.json'),previous_source_availability_reference=cp['source_availability_reference'],previous_source_hold_reference=cp['new_source_access_hold_reference'],native_captures=caps,comparison_context_reference=ref(RUN/'comparison-source-context-002.json.gz'),pdf_source_reference=ref(RUN/'selected-documents-001.json.gz'),pdf_visual_reference=ref(RUN/'newsletter-visual-review-001.json'),policy='SelectedcurrentpublicCity/councilcollectionarticles,ArtFundobjects,Universitygallerylenderlist,threeSSAHnewslettersandPallantexhibitioncredit. Threehistoricalcouncil404URLsunavailable,notretried;currentdifferentresourcesworked. NewNGS403hold. Everypriorproviderholdpersists. Noexhaustivecollection/imagefetch.'))
 leads=[dict(title='Edinburgh from the Calton Hill',creator='Alexander Nasmyth',reason='Currentmuseumimagefilename1820isleadonly;compareexistingc1808HH48/1899andother1820versions beforeaddition.'),dict(title='Catterline landscape',creator='Joan Eardley',reason='Currentcouncilunnamedpaintingneedsactualtitle/objectidentity.'),dict(title='The Sou’Westers, Arbroath preparatory sketches',creator='Morris Grassie',reason='Unclearphysicalobjectcountandcreationdates;nogroupmultiplication.'),dict(title='First Edinburgh International Festival drawing',creator='Milein Cosman',reason='1947subjecteventnotautomaticallycreationdate;actualobjecttitleneeded.'),dict(title='Portrait miniature of Bonnie Prince Charlie',creator=None,reason='Currentarticlementionsresearch,butmaker/objectIDanddateunresolved. Noanonymousplaceholder.')]
 oldq=m.load(a.checked(cp['next_museum_pass_reference']));live=m.load(m.RUN/'after-wave-99.json');by={v['id']:v for v in live['institutions']};museums=[by[a.IID]]
 m.save(RUN/'remaining-research-001.json.gz',dict(at=m.now(),rows=[v for v in ds if v['state']=='editorial_hold'],source_fact_holds=leads,already_catalogued=[],reconciled_existing=[v for v in ds if v['state']=='approved_existing_holding'],review_reference=ref(a.REVIEW),previous_remaining_research_reference=cp['remaining_research_reference'],current_museums=museums,source_gap='CityArtCentre103linked/41eligible:97morelinkedfor200,and59moredatedfor100eligible. Threecurrentunknownrecordsremainreview. Fullmuseumcollection4800–5000notreviewedorimported. Modernworksidentifiedoutsidecutoffretainedonlyassourcecontext.',policy='Preserve6currentholds,5additionalsourcegaps andallolderqueues. Noquotaoverridesevidence.'))
 queue=dict(oldq);queue.update(at=m.now(),previous_queue_reference=cp['next_museum_pass_reference'],italian_museums=[dict(v,current_linked=by[v['institution_id']]['works'],current_eligible=by[v['institution_id']]['eligible_works']) for v in oldq['italian_museums']],native_addition_targets=[by[v['id']] for v in oldq['native_addition_targets']],current_museums=[by[v['id']] for v in oldq['current_museums']],current_pass_museums=museums,remaining_research_reference=ref(RUN/'remaining-research-001.json.gz'),source_availability_reference=ref(RUN/'source-availability-001.json'),policy='Cityminimum100linkedmet;103/41not100datedor200linked. Continue97moreCity,82Box,68Harris andotherunder100museums. Preserve225Italianmuseums,Yorkholds,olderqueuesandaccessholds. Goalactive.',queue_database_writes=0);m.save(RUN/'next-museum-pass-001.json',queue)
 v=applied['verification'];assert(v['protected_existing_records'],v['prior_campaign_records_preserved'])==(449,13910)
 text=f'''# City Art Centre additions — 9 October 2026

Added **14 source-backed artworks in review** and linked **one existing John Duncan painting** to the museum. City Art Centre now has **103 linked works**, up from 88. Its minimum of 100 linked records is met; 97 more are needed for 200.

**11 additions have supported pre-1971 dates; three remain undated.** The reconciled Duncan is dated 1912. Date-eligible works increased from **29 to 41**. Undated records are not counted as date-eligible.

Sources include the [council’s portrait collection article](https://www.edinburgh.gov.uk/news/article/14283/unmasked-exploring-scottish-portraiture-at-the-city-art-centre), [recent gifts](https://www.edinburgh.gov.uk/news/article/14491/city-art-centre-showcases-most-recent-additions-to-fine-art-collection), curator Helen Scott’s collection articles in the [2014](https://ssahistory.wordpress.com/wp-content/uploads/2015/07/ssah_newsletter_08-14.pdf) and [2022 newsletters](https://ssahistory.wordpress.com/wp-content/uploads/2023/03/ssah-spring-summer2022-newsletter.pdf), the [University of Edinburgh’s exact lender list](https://www.trg.ed.ac.uk/exhibition/wide-new-kingdom-celtic-revival-scotland), and selected Art Fund acquisition records. [The decision ledger](editorial-reviewed-001.json.gz) preserves each title, maker, date, source and limitation.

The existing *Tristan and Isolde* record was linked using the 1912 *Tristan and Iseult* lender entry, its original WikiArt evidence and its existing image. Its metadata, image and review status were preserved. Six candidates remain held: Ramsay’s Katherine Hall portrait, Cameron’s *A Garment of War*, Paolozzi’s bronze *Horse’s Head*, Pow’s *Fallen Angels*, Robb’s *Cool House* and Blackadder’s *Irises*. Versions, cast dates and possible post-1970 creation require further evidence.

Three newsletters were retained; six pages were rendered and visually inspected to distinguish captions and neighbouring articles. Ten existing catalogue images and one selected 300-pixel research thumbnail supported object comparisons. The winter 2014 article has no named byline; it is not described as curator-authored. No catalogue images were attached. A National Galleries of Scotland request returned HTTP 403 and further host requests stopped. Three historical council URLs returned 404; their cached search snippets were not promoted into fresh evidence.

**22 offline checks, atomic readback and zero-write replay passed.** All 449 scoped existing records were preserved apart from the one authorized museum link and its evidence; all **13,910 prior campaign records** were unchanged. The bounded identity pool held 2,715 artworks and 6,121 citations. The context pass reconstructed 153 raw bodies; 45 citation bodies remained unavailable there, with the Duncan raw body subsequently recovered in the separate physical-object review. No publication, current-display or ownership claims were added.

Campaign totals: **10,889 new + 3,036 reconciled = 13,925 distinct artworks across {report['institutions_with_new_records_or_reconciled_holdings']} institutions**. **{report['after']['museums_below_100']:,} canonical museums remain below 100 linked works**, and **{report['after']['museums_below_200']:,} remain below 200**. [The continuing queue](next-museum-pass-001.json) retains all previous institutions and unresolved cases. The full goal remains active.
'''
 m.save(backup,dict(at=m.now(),path=str(root),text=root.read_text(),sha256=sha(root)));(RUN/'README.md').write_text(text);old=root.read_text();intro,rest=old.split('## Added works',1);intro=intro.replace('10,875','10,889').replace('3,035','3,036').replace('1,227','1,226').replace('after-wave-98','after-wave-99').replace('The latest pass adds 13 works with eligible dates and eight with dates still unknown.','The latest pass adds 11 works with eligible dates, three with dates still unknown, and one existing dated holding link.');table='| Distinct new-record campaign total | **10,875** | **219 collections** |';assert table in rest;rest=rest.replace(table,'| City Art Centre — selected collection additions | 14 | 1 museum |\n| Distinct new-record campaign total | **10,889** | **220 collections** |',1);root.write_text(intro+'## Added works'+rest+'\n\n## City Art Centre additions — wave99\n\nAdded 14 review works: 11 dated and three undated, and linked one existing 1912 Duncan without changing its metadata. City Art Centre now has 103 linked / 41 date-eligible works, crossing 100 linked; 97 more are needed for 200. Six holds remain. Twenty-two offline checks, atomic readback and zero-write replay passed. All 449 scoped existing records were preserved apart from the authorized holding link; all 13,910 prior campaign records were unchanged. [Evidence and continuing queue](native/city-art-additions-20261009/README.md). Campaign: 10,889 new + 3,036 reconciled = 13,925 distinct records across 239 institutions; 1,226 canonical museums remain below 100. No catalogue images were attached. The NGS403 access hold was recorded; all prior queues persist and the goal remains active.\n');m.save(RUN/'readme-supersessions-001.json',dict(at=m.now(),changes=[dict(path=str(root.relative_to(m.ROOT)),before_sha256=pin['sha256'],after_sha256=sha(root),backup_path=str(backup),backup_sha256=sha(backup))]));print(json.dumps(dict(documented_new_records=14,documented_existing_links=1,held=6,tests=22,goal_complete=False)))
if __name__=='__main__':main()
