"""Wave86 evidence register, explicit remaining work and backed-up report update."""
import csv,hashlib,importlib.util,json
from pathlib import Path
z=importlib.util.spec_from_file_location('r',Path(__file__).with_name('museum-expansion-guildhall-review-20261009.py'));r=importlib.util.module_from_spec(z);z.loader.exec_module(r);m=r.m;RUN=r.RUN;ref=r.ref;KEY='guildhall-native-additions-001';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 report=m.load(m.RUN/'verification-after-wave-86.json');assert(report['verified_new_artworks'],report['verified_existing_artworks_linked'],report['institutions_with_new_records_or_reconciled_holdings'])==(10417,2297,228);cp_path=m.RUN/'native/britain-seven-holdings-20261009/delivery-checkpoint-001.json';assert sha(cp_path)=='1064b93d392810edd5276f43c30dcfcfa6fd03776d1f66eaddec63fc200c9b31';cp=m.load(cp_path);applied=m.load(RUN/(KEY+'-applied.json'));assert applied['created']==22 and applied['verification']==report['guildhall_additions'];root=m.RUN/'README.md';pin=next(v for v in cp['artifacts'] if v['path']==str(root.relative_to(m.ROOT)));assert sha(root)==pin['sha256'];backup=m.BACKUP/'guildhall-root-readme-before-001.json.gz';assert not backup.exists()
 for name in ['checks-001.json','remaining-research-001.json.gz','next-museum-pass-001.json','README.md','readme-supersessions-001.json','source-availability-001.json']:assert not(RUN/name).exists()
 logsroot=Path('/Users/vadimdulub/Library/Logs');test=(logsroot/'artline-guildhall-tests-20261009.log').read_text();assert 'Ran 20 tests' in test and test.rstrip().endswith('OK');assert(logsroot/'artline-guildhall-replay-20261009.log').read_text().strip()=='Unchanged replay: zero writes';logs={v.name:dict(path=str(v),sha256=sha(v)) for v in sorted(logsroot.glob('artline-guildhall-*-20261009.log')) if 'delivery' not in v.name and 'checkpoint' not in v.name}
 m.save(RUN/'checks-001.json',dict(at=m.now(),new_offline_tests_passed=20,historical_tests_passed=1669,cumulative_verified_tests=1689,historical_tests_rerun=False,replay_zero_writes=True,source_objects_reviewed=40,new_artworks=22,existing_links=0,already_catalogued=1,editorial_holds=17,logs=logs,other_job_totals_separate=True,source_refinements='Facts v2 tested collection-history leads;v3 resolves Constable via exact loan-story asset and replaces Dyce with a dated asset. Millais generic asset/watercolour crosswalk remains held. No failed write transaction.'))
 m.save(RUN/'new-source-access-holds-001.json',dict(at=m.now(),rows=[],previous_source_hold_reference=cp['new_source_access_hold_reference'],policy='No new access holds in this wave. Every historical source hold remains active.'))
 m.save(RUN/'source-availability-001.json',dict(at=m.now(),new_source_access_holds=[],new_source_access_hold_reference=ref(RUN/'new-source-access-holds-001.json'),previous_source_availability_reference=cp['source_availability_reference'],previous_source_hold_reference=cp['new_source_access_hold_reference'],native_capture_reference=ref(RUN/'native-captured-001.json.gz'),supplement_capture_reference=ref(RUN/'supplement-captured-001.json'),additional_capture_reference=ref(RUN/'additional-captured-001.json'),policy='Museum-published Google Arts and Culture pages and City of London collection texts accessible. Selected metadata only; no reproduction downloads. All prior source access holds remain; no denied source retried. Scholarly version evidence captured as web-tool PDF text,not a raw PDF or image download.'))
 held=[v for v in m.load(RUN/'editorial-reviewed-001.json.gz')['decisions'] if v['state']=='editorial_hold'];assert len(held)==17;m.save(RUN/'remaining-research-001.json.gz',dict(at=m.now(),rows=held,review_reference=ref(RUN/'editorial-reviewed-001.json.gz'),previous_remaining_research_reference=cp['remaining_research_reference'],policy='17 held leads include three post1970 exclusions,unknown creation dates,duplicate presentations and unresolved physical versions. Existing Lavery is separately recorded as already catalogued. Historical source dates are never replaced by artist lifetimes or event dates. Keep all previous research queues.'))
 oldq=m.load(r.checked(cp['next_museum_pass_reference']));live=m.load(m.RUN/'after-wave-86.json');by={v['id']:v for v in live['institutions']};italian=[dict(v,current_linked=by[v['institution_id']]['works'],current_eligible=by[v['institution_id']]['eligible_works']) for v in oldq['italian_museums']];assert len(italian)==225;targets=[by[v['id']] for v in oldq['existing_holding_review_targets']]
 m.save(RUN/'next-museum-pass-001.json',dict(at=m.now(),previous_queue_reference=cp['next_museum_pass_reference'],italian_museums=italian,existing_holding_review_targets=targets,native_addition_targets=[by[r.f.IID]],current_museums=[by[r.f.IID]],remaining_research_reference=ref(RUN/'remaining-research-001.json.gz'),source_availability_reference=ref(RUN/'source-availability-001.json'),policy='Continue Southampton100 and Edinburgh City Art Centre91 pending-object holding reviews. Guildhall115linked/86eligible still needs14 supported dated works to100eligible and more toward200; selected source stories and17 held leads retained. Official history also identifies Millais My Second Sermon1864 and Collins Nutting Party1831 for next exact-source/duplicate research,not automatically approved. Keep225 Italian museums,Salford101linked/40eligible,Ferens44 holds,RWA date gaps and every earlier queue. Full goal active.',database_writes=0))
 text=f'''# Guildhall additions — 9 October 2026

Added **22 source-backed artworks in review** to Guildhall Art Gallery. The catalogue now has **115 linked records**, up from 93, and **86 date-eligible records**, up from 64. The preferred 200 target and 100 date-eligible minimum remain unfinished.

Reviewed 40 selected object leads: 22 additions, 17 held and one already catalogued Lavery. Repeated Google Arts & Culture presentations, detail images and infrared documentation do not create extra artworks. Twenty-one additions retain unknown accession numbers; only Collier’s 1882 *Clytemnestra* has a supported inventory 577. An asset ID is not an accession number.

Sources include [Guildhall’s published collection](https://artsandculture.google.com/partner/guildhall-art-gallery), its [official collection history](https://www.cityoflondon.gov.uk/things-to-do/attractions-museums-entertainment/guildhall-art-gallery/collections/collections-history), and the City of London’s [Faith collection story](https://artsandculture.google.com/story/faith-city-of-london-corporation/TAVBbPVYBd2CJg?hl=en). Four selected paintings from that story are Goodall’s 1860 *Early Morning in the Wilderness of Shur*, Phillip’s 1864 *Faith*, Armitage’s 1868 *Herod’s Birthday Feast* and Fildes’s 1914 *Naomi*. Their exact object pages were captured before review. Rights labels and original source wording remain in the evidence; no image was downloaded or attached.

The Guildhall 1882 *Clytemnestra* is distinct from the Worcester c. 1914 painting already catalogued as FAO3. [Archival research on both paintings](https://journals.akademicka.pl/saac/article/download/6303/5843/8485) supplies separate inventories, dimensions and compositional differences. Guildhall’s full-size Constable oil sketch is identified by the explicit Guildhall lender credit in [Dordrecht’s historical exhibition story](https://artsandculture.google.com/story/in-the-light-of-cuyp-dordrechts-museum/2QXRF_i5lV-Lcw?hl=en), linked to the exact object asset; the 1829 asset date and Guildhall history’s 1829–31 range are both preserved. It is distinct from Tate’s small N01814 study. Dordrecht publishing the asset does not make the painting a Dordrecht holding or establish current display.

Hunt’s 1848 finished *Eve of Saint Agnes* and its oil study have different described compositions and count as separate physical paintings. The source’s Millais contribution to the finished painting remains in evidence. The anonymous bridge-demolition work preserves the qualified signature reading J.W.S. Griffier’s 1739/1739–40 date variation remains explicit. Stanley’s 1969 *Smithfield Market* and Howard’s 1962 *Billingsgate Market* meet the creation cutoff.

[Seventeen leads remain held](remaining-research-001.json.gz): unknown-date copies and other works, three post-1970 objects, repeated presentations, the exact Millais watercolour crosswalk and Nebot’s near-identical Covent Garden versions. The 1842 Royal Exchange ceremony and 1666 Great Fire are not creation dates. The already-linked Lavery 1922 portrait was not added again.

The [reviewed plan](guildhall-native-additions-001-plan-001.json.gz) and [transaction receipt](guildhall-native-additions-001-applied.json) verify 22 artworks, 22 source identifiers, 22 citations and 22 accepted collection-holding assertions. Fresh comparison covered 4,362 existing artworks and 8,927 citations. All 4,362 scoped records and 12,692 previous campaign objects were preserved. **20 offline tests, atomic readback and zero-write replay passed.** No existing metadata, status, image or artist link changed. No publication, current-display claim, commit, deployment or production write.

Campaign total: **10,417 new artworks + 2,297 reconciled existing artworks = 12,714 distinct records across 228 institutions**. The global audit still has **{report['after']['museums_below_100']:,} museums below 100 linked records** and **{report['after']['museums_below_200']:,} below 200**. [Next work](next-museum-pass-001.json) retains Southampton, Edinburgh City Art Centre, Guildhall and all earlier queues. Source access restrictions remain unchanged.
'''
 m.save(backup,dict(at=m.now(),path=str(root),text=root.read_text(),sha256=sha(root)));(RUN/'README.md').write_text(text)
 old=root.read_text();intro,rest=old.split('## Added works',1);intro=intro.replace('10,395','10,417').replace('212 local museums','213 local museums').replace('1,235',f"{report['after']['museums_below_100']:,}").replace('after-wave-85','after-wave-86');root.write_text(intro+'## Added works'+rest+'\n\n## Guildhall additions — wave86\n\nAdded 22 reviewed artworks with explicit eligible creation dates. Guildhall 115 linked / 86 date-eligible; 17 leads held and one Lavery already catalogued. Physical-version checks distinguish Collier 1882 from Worcester 1914 and the full-size Constable sketch from the Tate study. [Evidence and remaining work](native/guildhall-additions-20261009/README.md). Campaign 10,417 new + 2,297 reconciled = 12,714 distinct across 228 institutions. All-museum 100–200 goal remains unfinished.\n')
 m.save(RUN/'readme-supersessions-001.json',dict(at=m.now(),changes=[dict(path=str(root.relative_to(m.ROOT)),before_sha256=pin['sha256'],after_sha256=sha(root),backup_path=str(backup),backup_sha256=sha(backup))]));print(json.dumps(dict(documented_new_records=22,documented_existing_links=0,held=17,already_catalogued=1,tests=20,goal_complete=False)),flush=True)
if __name__=='__main__':main()
