"""Wave133delivery checkpoint; every-museum goal remains active and unfinished."""
import hashlib,importlib.util,json
from pathlib import Path
spec=importlib.util.spec_from_file_location('d',Path(__file__).with_name('museum-expansion-spathario-delivery-v2-20261010.py'))
d=importlib.util.module_from_spec(spec);spec.loader.exec_module(d)
a,c,m,RUN=d.a,d.c,d.m,d.RUN

def sha(path):return hashlib.sha256(Path(path).read_bytes()).hexdigest()

def main():
    dest=RUN/'delivery-checkpoint-001.json';assert not dest.exists();report=m.load(RUN/'delivery-001.json');checks=m.load(RUN/'checks-001.json');public=m.load(RUN/'public-delivery-001.json')
    assert report['added']==115 and report['new_images']==64 and checks['readback_passed'] and checks['replay_zero_writes'] and checks['local_unchanged'] and checks['offline_tests_passed']==19
    assert public['public_image_hashes_matched']==64 and public['public_artwork_samples']==6
    p,digest=a.validate_plan();assert digest==d.EXPECTED and c.ref(c.CP)['sha256']==c.CP_SHA;prior=m.load(c.CP)
    oldpins={x['path']:x for x in prior['artifacts']};oldext={x['path']:x for x in prior['external_artifacts']};pins,external=dict(oldpins),dict(oldext)
    def add(pin,target):assert pin['path'] not in target or target[pin['path']]==pin,pin['path'];target[pin['path']]=pin
    paths={c.CP,a.PLAN,Path(__file__).resolve()}|{x for x in RUN.rglob('*') if x.is_file()}|set((m.ROOT/'ops').glob('museum-expansion-spathario-*.py'))
    for path in sorted(paths):add(c.ref(path),pins)
    for pin in p['evidence']:add(pin,pins)
    for pin in p['external_evidence']:add(pin,external)
    for path in sorted({x for x in c.PROOF.rglob('*') if x.is_file()}|set(m.BACKUP.glob('spathario-production-*.json*'))):add(dict(path=str(path),sha256=sha(path)),external)
    newpins=[x for x in pins.values() if oldpins.get(x['path'])!=x];newext=[x for x in external.values() if oldext.get(x['path'])!=x]
    for pin in newpins:c.checked(pin)
    for pin in newext:assert sha(pin['path'])==pin['sha256']
    protected=m.load(RUN/'protected-production-ids-001.json')['ids'];assert len(protected)==2798 and set(protected)==set(p['prior_ids'])|{v['artwork_id'] for v in p['records']}
    queue=m.load(RUN/'priority-museum-queue-001.json');assert len(queue['rows'])==223 and sum(x['country_code']=='GR' for x in queue['rows'])==63 and not any(x['id']==c.IID for x in queue['rows'])
    next_work='''Wave133complete selecteddelivery forSpatharioShadowTheatreMuseum IIDecc56326-95ff-5063-9e7c-defe30001f0f:115newreviewartworkunits preserving117sourcerecords,64authenticsourceJPEGs. Museum16catalogue/16eligible/7primary ->131catalogue/123numericdateeligible/71primary.107newnumericeligible,8actualcreationunknown. Minimum100met;69catalogueworks remain topreferred200. Every-museumgoalACTIVEunfinished. Campaign2774new+7existinglinks across17museums.2798protectedIDs=2781campaignrecords+17oldKilkisimage-only.223inheritedunder100rows,63Greek; notglobalcensus. No readyunappliedSpathariocandidates remain.

Use ops/museum-expansion-spathario-apply-v2-20261010.py directly forvalidate_plan andverify. Plan002 SHA25df7c0e39487bc0e9551752b222be6a10cd7534247bb177eeb8c1aeaa14c5e6, review001.19offline/evidence/live-readonlychecks,atomicverification,readback,zerowritereplay,64publicimagehashes and6publicsamples passed.16oldcompletecataloguerecords and2683priorIDs preserved. Noartist/alias/biography,publication orcurrentdisplayclaims created. Allholdingscollectiononly. Localartlinereadonlyunchanged.

Originalwriter/plan001 SHA2e2fa3f0a4613a60e8e19026845f0a602ebc778c5115628367a37a80f5703aa9 lostconnectionduringtransaction beforecommit when oldlocalproxyPID5785exited. Firstrollbackqueryalsofailed because55519nolongerlistening. CloudSQLinstanceRUNNABLE;verifiedsameproxybinary restarted asPID19001on127.0.0.1:55519--gcloud-auth. rolled-back-apply-001 proves0newartworks/sources/media/audits,allpreflightold/priorstateunchanged. V2plan002preservesexactrecords/images/before/priorstate.64uploadedobjects reusedwithsamegenerations/hashes,storage-upload-002 created0; no duplicateupload. Backup1791657537611 op2459fc3d-ceb8-4f5d-bc8f-ffd700000024 SUCCESSFUL2026-10-10T18:41:19.537Z beforebothattempts. Publicverificationfirstpass hadtransientNameResolutionError onartlines.orgafter6successes. DNSsubsequentlyNOERROR136.110.174.158; sameHTTPSorigin resumed,all64hashes/6samplespassed,nonewsettingsoralternatehost. public-access-recovery-001 documents it. TwoLibraryreviewedplanversions preserved. AllV1/V2scripts/plans/receipts immutable; stagedV1delivery/report neverexecuted. UseV2delivery/report andchecks002. Runtimeproxylog/tmp/artline-spathario-cloud-sql-proxy-20261010.log islive,notpinned. Do notkillnewproxy.

SpatharioSearchCultureMar_Spathareio450searchableresults versus453descriptionartifacts. All450institutionmetadataindexentries captured15TITLEpages.294indexdatesafter1970 excludedbeforeobject/imagefetch.156individualbilingualrecords read,156sourceJPEGpreviews/7contacts reviewedplusoriginal24/125/149/151. NoSCaccess/imagefailures,all156decodeJPEG, no exacthashduplicates. No separatefilelinks;nativepublichomepage/museum/artists/object182HTTP200;archive/objectSPAfrontend shells, no clientcredentials/authenticatedAPIused.64selecteddate<=1955images preservedbyteidenticalcompleteframes,max51113B,atmost380pxwideor550pxhigh. SourceitempreviewpanelactualCCBYNCSA4.0,storedrestrictedwithcredits/licenseURLs/userapproval separate. Notpublicdomain orcopyright-holderpermission. Noimagesunknown/after1955. Higherresolutiongap64 remains.

Artworkunits:149source69and125source71showfront/backofsamepolicepuppet,mirroredperforations/joints/hatflower/cardboardprinting;oneartworkwithtwo fullsourcecitations.24source420skeletonspitscene includes151source421operatingredshortsfigure;oneensemblewithcomponent source preserved. Sourceidentifiers schemaoneperartwork/scheme usesprimaryID,secondaryIDs indexedincitationsandcompletefacts.115newartworks have117metadatacitations+64imagecitations,115acceptedholdings,115externalIDs. Noextraartistlinks. Papercraft102–107oneillustratedsheet/issueeach,notonepercharacter/serialnumber.23twochildrenand133dog/catcheronegroup;36fourdesignscenerycollageonework.119/120skeletonsdistinct;45/46ManolopoulosGreekKaragiozis/KopritisdistinctdespiteEnglishduplicate.22utility/text-led/ticket/letter/award/equipment sourceentriesheld, notartpadding.124Stukasaircrafttitle/depictionheld.

Dates:38–41Chinese-labelledleatherpuppets and82/112Javaneseleatherpuppets have noindexdate butliteraldescription19thcentury ->1801–1900century.41tree-shapedpropChineseoriginunverified,explicitdescriptionnote,noculturalattributioninvented. SixAthanasopoulosunits23/25/93/146/149/150:source1930 conflictswithpublished1931performancepostercontext;oldpuppetreuseversussourceerrorunresolved,actualcreationNULLunknown,notinvented1931. Sevenrawsourceentriesbecause125isbackof149.110/111framedphotographs source1960/1953 don'testablishphotographer/frame/finalassemblycreation,actualdateunknown.110Sotirisframecarver,photographerunknown;111Evgeniossourceroleunresolved,photographerunknown. PublisherlabelsHISMASTERSVOICE/AGKYRA/SALIVEROSqualifiednotartists.17weddingposterconfirmedvisually;descriptioncooktitleconflictretained. MuseumliteralmakersSotirisvsEvgenios distinctfromreferencedearliercharacterdesigners. SourceURLnumbersnotaccessions. Existing16dates/labels untouched.

SourcecreationresearchLiFO2021memoirarticlecaptured200 includes1931performanceposter caption. vmrebetiko.gr/item/?id=10236 web502 anddirectSSLErrorbeforeHTTP;no furtherretry. Sourceaccessholdartifact records it. Nativeobject182returnsfrontend shell, notdenial butnohigherresimageobserved. Boundedproductionidentitysource/title/creator/imagequeriesreturnedonly16oldworks/23citations/7images. Noexistingartistsmatchedliteralnames/aliases; noinventedartistrecords. Queryplans/timingsretained,not10million-rowloadproof or exhaustiveglobalduplicateguarantee.

NEXTJewishMuseumofGreeceIID760b0104-19ee-5ad1-94f0-0ceb8dcea09e,last8catalogue/8eligible. Freshlocal/productionbaselineand2798protectedIDs required. CurrentRUNnext-source-discovery-001.json.gz hasHTTP200collectionhttps://www.searchculture.gr/aggregator/portal/collections/DigJewish?language=en,1044searchableresults vs1046descriptionassets,1642–2009. Description640photographicarchive,164ephemera,83personalobjects plusMolho/MarcelYoelarchives,manuscripts,religiousartifacts,postcards/books/graphicarts. First30mixedphotos/manuscripts include1905,1942,1934 andbroad1901–2000. ActualsourceCCBYNCND4.0; preservecompleteframes/rights,Greekimage<=1955. NoindividualJewishobjects/imagesdownloaded. Nativeobservedhttps://artifacts.jewishmuseum.gr/ andhttps://www.jewishmuseum.gr/. ObjectIDsDigJewish/000192-oai%3Anewartifacts.jewishmuseum.gr%3A123456789_...; preserveencodedsourceidentity. Firstcard1498manuscript1901–2000,1447photo1901–2000,1469photo1905. Date,artscope,archivegroup/photonegative/albumidentity andholdingvsdisplay reviewneeded; mixed1044noteligiblecount. TossitzaMansioncollectionTositsasFoundationHTTP500at18:40:07Zheld,no retry. Nikaia101mixedlateworks remainsinNHMinheriteddiscovery,notforgotten.

Allinheritedsourceholds andhistoricalpinvariants remain as recorded in previousWar checkpoint and itschain; do notretryblockedroutes orusealternatebypasses. IncludesArtUK/ArCo/Lombardia/MuseiReali/Bristol/Perth/LondonPictureArchive/Smartify/Salford/Glasgow/RCT/IWM/Met/NGA/WatercolourWorld/NationalGalleries/Freiburg/Brest/ElGreco/Kazantzakis/Anemoyannis/ejournals/Zongolopoulos/Larissa/Chania/AIC/Averoff/Athensartlion/NHMEIM&HPS/War. War1888mixedrecords retained20workgap and5objectHTTP500 plus33unattempted; nativeexhibitionTLSmismatch. AthensnativeSPAclientauthmustnotreuse/print.

Larissacommonhelpers eachlostonefinalLF beforeNHM; oldexactbytes archivedNHMLibraryhistorical-helper-variants and reconciliationpinned; causeunknown,ASTidentical. Do notrestorelivehelpers orrewriteoldCPs. CurrentcommonSHAeee872b3c26eee76f76901a5f12d460c995620289b1e810ea9c7c94ca3dac74e,v2SHA8b891849b4a7b65cc1277af83fc7ce03507752b0f223dbc17bf916a1ee4f77e2. Carry historical_artifact_revisions andhistorical_pin_reconciliation_referenceunchanged. Fullhistoricalverificationreference inherited;verifynew/relevantpinsnotall50k.

Researchvenv /Users/vadimdulub/Library/Application Support/Artline/research-venvs/museum-expansion-20261009/bin/python -B. Proofs/backupsLibrary, realpostgresql://localhost/artlineREADONLY,no fixtures/testDB. CurrentproxyPID19001port55519samebinarySHA47c56cc88acd3250ac90b7ad063532cc22a8cca9dd0896012a2a60d1eab4c159. Noagents/commits/deployment. AGENTSSHAad0d8067ebf9a99e3198d1d6d0c9853e6acdd8932c5a5a0a9e5bb006416d0241. Selectedproductionworkauthorized,noapprovalquestions. Allactivecatalogueunified,membermuseumaccessunchanged. Every-museumgoalACTIVE.'''
    result=dict(prior);result.update(at=m.now(),wave=133,goal_complete=False,goal_status='active',previous_goal_turn='progress',production_only=True,local_unchanged=True,new_additions=115,new_existing_links=0,new_images=64,verification=report['verification'],production_museum_before=report['museum_before'],production_museum_after=report['museum_after'],production_campaign_totals=report['production_campaign_totals'],global_production_counts_refreshed=False,global_production_thresholds_refreshed=False,new_tests_passed=19,plan_sha256=digest,plan_reference=c.ref(a.PLAN),prior_checkpoint_reference=c.ref(c.CP),artifacts=list(pins.values()),external_artifacts=list(external.values()),baseline_reference=c.ref(RUN/'baseline-verification-001.json'),review_reference=c.ref(a.REVIEW),checks_reference=c.ref(RUN/'checks-001.json'),public_delivery_reference=c.ref(RUN/'public-delivery-001.json'),production_institution_register_reference=c.ref(RUN/'production-institution-register-001.json.gz'),priority_museum_queue_reference=c.ref(RUN/'priority-museum-queue-001.json'),protected_production_ids_reference=c.ref(RUN/'protected-production-ids-001.json'),pending_candidates={},pending_candidate_total=0,global_threshold_summary_note='OnlySpathariorefreshed:131catalogue/123numericeligible/71primary,69shortofpreferred200.223inheritedunder100rowsremain,notglobalcensus.',source_availability=report['source_access'],source_access_holds_reference=c.ref(RUN/'source-access-holds-001.json'),inherited_source_holds_reference=c.ref(c.CP),remaining_research_reference=c.ref(RUN/'remaining-research-001.json'),next_source_discovery_reference=c.ref(RUN/'next-source-discovery-001.json.gz'),preferred_target_remaining=dict(institution_id=c.IID,catalogue=131,gap_to100=0,gap_to200=69,target_reached=False,numeric_eligible=123),public_api_date_scope=public['date_scope_note'],next_work=next_work)
    result.pop('previous_research_checkpoint',None);m.save(dest,result)
    m.save(RUN/'final-checkpoint-verification-001.json',dict(at=m.now(),checkpoint=c.ref(dest),verified_new_artifact_pins=len(newpins),verified_new_external_pins=len(newext),inherited_unchanged_artifact_pins=len(pins)-len(newpins),inherited_unchanged_external_pins=len(external)-len(newext),full_historical_proof=prior['initial_full_historical_verification_reference'],plan_sha256=digest,goal_complete=False,actual_added=115,actual_images=64,protected_production_ids=2798,pending_candidates=0,local_unchanged=True,historical_revisions_carried=len(prior.get('historical_artifact_revisions',[]))))
    print(json.dumps(dict(checkpoint=c.ref(dest),artifacts=len(pins),external=len(external),verified_new=len(newpins),verified_external=len(newext),added=115,images=64,pending=0)),flush=True)

if __name__=='__main__':main()
