"""Save source coverage and next object-review tasks without claiming additions."""
import collections,csv,hashlib,importlib.util,io,json
from pathlib import Path
z=importlib.util.spec_from_file_location('m',Path(__file__).with_name('museum-expansion-20261006.py'));m=importlib.util.module_from_spec(z);z.loader.exec_module(m);RUN=m.RUN/'native/kilkis-20261010'
def ref(p):return dict(path=str(p.relative_to(m.ROOT)),sha256=hashlib.sha256(p.read_bytes()).hexdigest())
x=m.load(RUN/'candidate-facts-001.json.gz');rows=x['rows'];assert len(rows)==15
out=io.StringIO(newline='');w=csv.DictWriter(out,fieldnames=['source_id','title','inventory_literal','date_display','native_url','state','next_review']);w.writeheader()
for r in rows:w.writerow(dict(source_id=r['source_id'],title=r['title'],inventory_literal=r['inventory_literal'],date_display=r['date_display'],native_url=r['native_url'],state=r['review_state'],next_review=r['note']))
(RUN/'candidate-ledger-001.csv').write_text(out.getvalue())
leads=[dict(url='https://ejournals.epublishing.ekt.gr/index.php/tekmiria/article/download/19335/17357.pdf',title='Two inscribed funerary monuments from ancient Morrylos',state='search_result_lead_only',next_step='Read the primary scholarly article,identify objectaccessions and explicit holding evidence,compare with native18existingrecords and15candidates. Do not treatregional provenance as museumholding.'),dict(url='https://sitestatic.shopster.gr/6150c0d864787b561e67912f/051223_de.pdf',title='Greek sculpture catalogue excerpt, unidentified publication',state='search_result_lead_only',next_step='Verify publisher,booktitle,authors andsourceprovenance before using this PDF excerpt. Search results credit ministry/Ephorate photos,but this is not yet authenticated object evidence.'),dict(url='https://www.efa-kilkis.gr/drastiriotites/',title='Official events including Metropolis Morrylion exhibition',state='official_page_search_result_lead',next_step='Locate the specific2024exhibitionpublication or objectcatalogue; an exhibition announcement does not establish enduring collectionholding or currentdisplay.')]
m.save(RUN/'remaining-research-001.json',dict(at=m.now(),institution_id='4f3ac99d-d622-591d-8885-ac14362fbb50',goal_complete=False,production_writes=0,last_observed_catalogue_count=18,last_observed_dateeligible_count=0,last_count_date='2026-10-09',fresh_production_counts=False,source_index_items=65,index_states=dict(other_index_record=32,already_in_historical_delivery=18,selected_detail_candidate=15),selected_objects_with_native_pages=15,native_periods=dict(collections.Counter(v['date_display']for v in rows)),native_year_bounds_invented=0,images_downloaded=0,publication_leads=leads,remaining_requirements=['Fresh scopedproduction fullrows,citations,identifiers andinstitutionreconciliation aftergcloudauthentication','Compare all15nativeaccessions andURLs acrossproduction,includingexisting4461 and1593','Review selected referenceimages for fragmented/reassembled physicalunits','Retain periodonlydates unless individual evidence supports numericbounds; unknownscope stillrequireseditorialreview','Review32otherindexcards selectively,without automatically treating everyarchaeologicalartifact as anartwork','Find additionalprimaryobjectpublications:65sourceitems alone cannotprovide100distinctworks','Preserve real localread-onlydatabase,no fixtures,noinvented quota records'],candidate_reference=ref(RUN/'candidate-facts-001.json.gz'),script_reference=ref(Path(__file__).resolve())))
(RUN/'README.md').write_text('''# Archaeological Museum of Kilkis — source research, 10 October 2026

**15 sculpture and relief candidates have individual SearchCulture and native museum pages captured. None have been added to production.** The last dated register observation is18catalogue works and0numerically date-eligible works, from9October; those are not newly refreshed counts.

- [15 candidate records](candidate-ledger-001.csv)
- [Literal facts and source references](candidate-facts-001.json.gz)
- [Remaining review and publication leads](remaining-research-001.json)

The [official collection](https://www.efa-kilkis.gr/artworks/) identifies selected holdings of the Archaeological Museum of Kilkis. Its [SearchCulture index](https://www.searchculture.gr/aggregator/portal/collections/Efa_Kilkis_col?language=en) contains65items. Three index pages were inspected:18sourceIDs already appear in the historical production delivery,15new sculpture/figurine/relief leads were selected,and32other cards remain for selective review. The full65cannot alone establish100distinct eligible artworks. No collection-wide image or detailed-object download was performed.

Native pages provide accession labels and historical periods:sevenHellenistic,sixRoman andtwoByzantine. Numeric creation bounds remain unknown. SearchCulture supplies enriched numerical periods and some questionable geographic mappings; these are retained separately,not silently promoted to original dates or findspots. The Byzantine labels on1400and1404 are explicit source data. The possibly male identification of1404 and probable Aphrodite identification of4460 remain qualified.

Physical identity still needs review. Relief fragments1594(hand)and1595(partialhead)must be compared with existing1593 and their parent furnishing. Grape-cluster fragments5859and5862 have distinct accession labels and different reported thicknesses,but potential joins or a shared parent object need assessment. Figurine4460 is assembled fromtwofragments and counts asoneobject; compare existing4461 rather than merging repeated titles. Four Palatiano statue records must be reconciled by accession and anatomy,not shared group provenance. No creator,material or dimensions have been invented.

Cloud authentication expired during the preceding Kazantzakis continuation. The15Kilkis records remain candidates until fresh scoped production identity checks and physical-object review can run. No images were downloaded. NC/ND labels remain recorded,and museumholding is separate from currentdisplay.

Two publication leads may extend coverage: a primary scholarly article about Morrylos funerary monuments,and a sculpture catalogue excerpt whose publication provenance remains unverified. The official2024Morrylos exhibition may lead to further cataloguedobjects. These are leads,not acceptednewartworks. Continue with those sources while preserving the documented gap to100–200.
''')
print(json.dumps(dict(candidates=15,actual_added=0,source_index=65,existing_source_ids=18,other_cards=32)),flush=True)
