"""Production Brest delivery, complete source ledger and bounded museum priority counts."""
import csv,importlib.util,json
from pathlib import Path
z=importlib.util.spec_from_file_location('a',Path(__file__).with_name('museum-expansion-brest-apply-20261009.py'));a=importlib.util.module_from_spec(z);z.loader.exec_module(a);m=a.m;RUN=a.RUN
def main():
 p,digest=a.validate_plan();receipt=m.load(RUN/(a.KEY+'-applied.json'));checks=m.load(RUN/'checks-001.json');assert receipt['plan_sha256']==digest and checks['offline_tests_passed']==12 and checks['atomic_verification_passed'] and checks['replay_zero_writes']
 counts=m.load(RUN/'production-threshold-audit-001.json.gz');dates=m.load(RUN/'production-date-threshold-audit-001.json.gz');cby={v['id']:v for v in counts['rows']};dby={v['id']:v for v in dates['rows']};assert set(cby)==set(dby) and len(cby)==2135
 for iid in cby:assert dby[iid]['date_eligible_count_to_200']<=cby[iid]['catalogue_count_to_200']
 for iid,c,d in [(a.IID,112,112),('63e38322-d1a4-489c-9b91-ef3876841e04',200,186),('bf33d361-f976-44ac-a51d-7840addd2070',139,113)]:assert (cby[iid]['catalogue_count_to_200'],dby[iid]['date_eligible_count_to_200'])==(c,d)
 prior=m.load(m.RUN/'native/beziers-more-20261009/production-institution-register-001.json.gz');historic={v['id']:v for v in prior['rows']}
 with a.i.prod.connect() as db,db.transaction():
  db.execute('SET TRANSACTION READ ONLY');assert a.counts(db)=={a.IID:dict(linked=112,eligible=112)};register=db.execute('SELECT i.id::text,i.slug,i.name,i.kind,i.status,i.canonical_institution_id::text,i.website_url,p.name city,p.country_code FROM institutions i LEFT JOIN places p ON p.id=i.place_id ORDER BY i.id').fetchall()
 for v in register:
  old=historic.get(v['id'],{});c=cby.get(v['id']);d=dby.get(v['id']);v.update(historical_local_linked_works=old.get('historical_local_linked_works'),historical_local_eligible_works=old.get('historical_local_eligible_works'),historical_local_count_at=old.get('historical_local_count_at'),production_catalogue_count_to_200=c['catalogue_count_to_200'] if c else None,production_catalogue_count_state=c['count_state'] if c else 'not_audited',production_catalogue_count_at=counts['snapshot_started_at'] if c else None,production_date_eligible_count_to_200=d['date_eligible_count_to_200'] if d else None,production_date_eligible_count_state=d['count_state'] if d else 'not_audited',production_date_eligible_count_at=dates['snapshot_started_at'] if d else None,verified_production_works=c['catalogue_count_to_200'] if c and c['count_state']=='exact' else 241 if v['id']=='63e38322-d1a4-489c-9b91-ef3876841e04' else None,verified_production_eligible_works=d['date_eligible_count_to_200'] if d and d['count_state']=='exact' else None)
 m.save(RUN/'production-institution-register-001.json.gz',dict(at=m.now(),rows=register,read_only=True,complete_canonical_museum_thresholds=True,global_exact_counts_refreshed=False,catalogue_threshold_reference=a.reference(RUN/'production-threshold-audit-001.json.gz'),date_threshold_reference=a.reference(RUN/'production-date-threshold-audit-001.json.gz')))
 with (RUN/'production-institution-register-001.csv').open('x',newline='') as fp:w=csv.DictWriter(fp,fieldnames=list(register[0]));w.writeheader();w.writerows(register)
 priority=[dict(v,date_eligible_count_to_200=dby[v['id']]['date_eligible_count_to_200']) for v in counts['rows'] if v['country_code'] in ['GR','CY','RU'] and v['catalogue_count_to_200']<100];priority.sort(key=lambda v:({'GR':0,'CY':1,'RU':2}[v['country_code']],-v['catalogue_count_to_200'],v['id']));m.save(RUN/'priority-museum-queue-001.json',dict(at=m.now(),rows=priority,policy='Fresh under100 leads for existing Greek,Cypriot and Russian priorities. Catalogue directory rows are not sufficient object evidence. All other museums remain in the full threshold ledger.'))
 with (RUN/'added-production-artworks-001.csv').open('x',newline='') as fp:
  w=csv.DictWriter(fp,fieldnames=['artwork_id','institution_id','source_id','title','creator_label','date_display','creation_year_start','creation_year_end','date_precision','work_type','inventory','source_url','status']);w.writeheader()
  for v in p['records']:
   f=v['facts'];w.writerow(dict(artwork_id=v['artwork_id'],institution_id=a.IID,source_id=f['source_id'],title=f['title'],creator_label=f['creator_label'],date_display=f['date_display'],creation_year_start=f['first'],creation_year_end=f['last'],date_precision=f['date_precision'],work_type=f['work_type'],inventory=f['inventory'],source_url=f['source_url'],status='review'))
 decisions={d['source_id']:d for d in m.load(a.REVIEW)['decisions']};facts=m.load(RUN/'candidate-facts-001.json.gz');held={v['source_id']:v for v in facts['held']};known={v['source_id']:v for v in facts['existing']};source=m.load(RUN/'joconde-selected-001.json.gz');assert len(decisions)+len(held)+len(known)==len(source['rows'])==103
 with (RUN/'all-source-decisions-001.csv').open('x',newline='') as fp:
  w=csv.DictWriter(fp,fieldnames=['source_id','title','inventory','state','reason','source_url']);w.writeheader()
  for v in source['rows']:
   rid=v['Reference'];d=decisions.get(rid);state=d['state'] if d else 'already_catalogued' if rid in known else 'source_fact_or_scope_hold';reason=d['basis'] if d else 'Existing national-source identity; catalogue record preserved.' if rid in known else held[rid]['reason'];w.writerow(dict(source_id=rid,title=v['Titre'],inventory=v['Numero_inventaire'],state=state,reason=reason,source_url='https://pop.culture.gouv.fr/notice/joconde/'+rid))
 report=dict(at=m.now(),goal_complete=False,production_only=True,local_unchanged=True,plan_sha256=digest,added=33,existing_links=0,date_eligible_added=33,reviewed_source_records=103,already_catalogued=66,source_fact_or_scope_holds=3,editorial_holds=1,verification=receipt['verification'],museum_before=dict(works=79,eligible_works=79),museum_after=dict(works=112,eligible_works=112),production_campaign_new_artworks=239,production_campaign_museums=3,historical_local_totals_unchanged=dict(new_artworks=11018,existing_links=3036),cross_database_totals_combined=False,production_canonical_museums=2135,global_production_counts_refreshed=False,global_production_thresholds_refreshed=True,catalogue_threshold_summary=counts['summary'],date_eligible_threshold_summary=dates['summary'],remaining_national_records_not_fetched=21,remaining_national_page=source['overall_next'],source_access='National public tabular API and captured municipal collection context available. Native Brest artwork index HTTP500 from preceding discovery retained without retry. Exact uppercase comparator000DE006792 query returned zero rows; two bounded suffix searches yielded unrelated records and did not resolve the Bernard identity. POP pages unavailable in web reader; no new provider access denial. Prior provider holds retained.',preserved_queues_checkpoint=a.reference(a.CHECKPOINT),priority_queue=a.reference(RUN/'priority-museum-queue-001.json'))
 m.save(RUN/'delivery-001.json',report)
 text='''# Brest — production expansion, 9 October 2026

Added **33 production artworks in review**, taking the Musée des Beaux-Arts de Brest from **79 to 112 artworks**. All 33 new creation dates or periods are within scope. The additions comprise 29 drawings, two prints, one painting and one sculpture. The real local database remains unchanged at 79 works.

- [33 delivered artworks](added-production-artworks-001.csv)
- [All 103 source decisions](all-source-decisions-001.csv)
- [Complete production museum threshold audit](production-threshold-audit-001.csv)
- [Creation-date eligibility threshold audit](production-date-threshold-audit-001.csv)
- [Institution register with count precision](production-institution-register-001.csv)
- [Verification and remaining research](delivery-001.json)

Sources are the [museum collection website](https://musee.brest.fr/les-collections), the [national museum record M0197](https://pop.culture.gouv.fr/notice/museo/M0197), and individual Ministry of Culture Joconde object notices. All delivered records retain source identifiers, inventory numbers and literal evidence. Museum holdings do not establish current display, custody or ownership. Historical exhibitions are not treated as current display.

The bounded source selection contains 103 distinct notices: 66 were already catalogued, 33 were added, three remain source/group holds and one remains an editorial identity hold. Another 21 unique national-source records are outside this selection. The direct municipal artwork index returned HTTP 500 during preceding discovery and was not retried; the national metadata source remained accessible. No exhaustive artwork or image download was performed.

The additions include 14 Schuffenecker drawings, 11 Moret drawings and Lacombe’s 1898 mahogany relief *Autoportrait en crucifié*. The relief is distinct from its documentary photograph and the existing *Calvaire* drawing. Jourdan’s two-sided cardboard painting and Moret’s two-sided coastal sheet each count as one physical work. Moret’s similar coastal sheets retain separate inventories, studio numbers, measurements and subjects. A pastel poster design remains a drawing; Jean-Haffen’s SNCF lithographic poster remains a print.

A folded Sérusier support bearing two independently named drawings, two prints sharing one frame, and a documentary photograph remain outside this addition. Bernard’s *Maisons flamandes* remains held because a similarly sized *Les vieilles maisons* needs stronger identity evidence. Coincident inventory numbers at other museums were not merged. Existing dates and metadata were preserved, including broad dates on previously imported works. New period ranges were not shortened using artist lifespans or acquisition dates.

Twelve offline policy checks passed. Successful Cloud SQL backup 1791547970587 preceded atomic application and readback. A repeat application verified the result with zero writes. All 129 existing comparison/museum records and all 206 earlier production additions were preserved. There were no image attachments, artist-authority links, publication changes or current-display claims.

The fresh threshold audits cover all **2,135 active canonical museum records**. Catalogue counts show **1,645 below 100** and **1,913 below 200**, with gaps of **142,796** and **325,202** works respectively. Restricting to eligible creation dates gives **1,712 below 100** and **1,966 below 200**, with gaps of **147,896** and **335,840**. These are counts of direct museum links; they do not prove that each institution has enough eligible artworks available from sources.

Each audit used a read-only repeatable-read snapshot, 50 museums per query and a limit of 200 qualifying works per museum. Values below 200 are exact; 200 means “at least 200.” Larger exact collection totals were not recomputed. The live query plan uses the institution artwork index. These scoped audits replace the missing priority thresholds without retrying the earlier unbounded query, changing indexes or claiming representative 10-million-row load testing. The two audit snapshot times are retained separately.

Brest has reached 100 and needs 88 more works to reach 200. The selected production phase now totals 239 additions across Girodet, Béziers and Brest; historical local-only totals remain separate. The priority queue includes underfilled Greek, Cypriot and Russian museums, while every other canonical museum remains tracked in the full audit. The overall goal is unfinished; records will not be invented to fill quotas.
'''
 dest=RUN/'README.md';assert not dest.exists();dest.write_text(text);print(json.dumps(dict(added=33,after=112,eligible=112,production_new_total=239,catalogue_thresholds=counts['summary'],date_thresholds=dates['summary'])),flush=True)
if __name__=='__main__':main()
