"""Wave123 immutable production checkpoint after verified Chania delivery."""
import hashlib
import importlib.util
import json
from pathlib import Path

spec=importlib.util.spec_from_file_location('d',Path(__file__).with_name('museum-expansion-chania-delivery-20261010.py'))
d=importlib.util.module_from_spec(spec);spec.loader.exec_module(d)
a,c,m,RUN=d.a,d.c,d.m,d.RUN
sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest()

def main():
    dest=RUN/'delivery-checkpoint-001.json';assert not dest.exists()
    report=m.load(RUN/'delivery-001.json');checks=m.load(RUN/'checks-001.json');public=m.load(RUN/'public-delivery-001.json')
    assert report['added']==174 and report['existing_links']==0 and checks['readback_passed'] and checks['replay_zero_writes'] and public['public_image_hashes_matched']==188
    plan,digest=a.validate_plan();assert digest==d.EXPECTED and c.ref(c.CP)['sha256']==c.CP_SHA
    prior=m.load(c.CP);oldpins={v['path']:v for v in prior['artifacts']};oldext={v['path']:v for v in prior['external_artifacts']};pins=dict(oldpins);external=dict(oldext)
    def add(pin,target):
        assert pin['path'] not in target or target[pin['path']]==pin,pin['path']
        target[pin['path']]=pin
    paths={c.CP,c.RESEARCH_CP,a.PLAN,Path(__file__).resolve()}
    paths|={v for v in RUN.rglob('*') if v.is_file()};paths|={v for v in (m.ROOT/'ops').glob('*chania*20261010.py')}
    for path in sorted(paths):add(c.ref(path),pins)
    for pin in plan['evidence']:add(pin,pins)
    for pin in plan['external_evidence']:add(pin,external)
    for path in sorted(m.BACKUP.glob('chania-production-*.json*')):add(dict(path=str(path),sha256=sha(path)),external)
    add(dict(path=plan['backup_path'],sha256=plan['backup_sha256']),external)
    newpins=[v for v in pins.values() if oldpins.get(v['path'])!=v];newext=[v for v in external.values() if oldext.get(v['path'])!=v]
    for pin in newpins:c.checked(pin)
    for pin in newext:assert sha(pin['path'])==pin['sha256'],pin['path']
    protected=m.load(RUN/'protected-production-ids-001.json')['ids'];assert len(protected)==1387 and set(protected)==set(plan['prior_ids'])|{v['artwork_id'] for v in plan['records']}
    pending=report['remaining_pending_candidates'];assert sum(pending.values())==422
    next_work='''Wave123 made verified production progress: Chania174new review artworks and188authentic image attachments. Actual museum18catalogue/0numeric eligible/0primary images to192catalogue/117numeric eligible/183primary-image artworks. Minimum100 reached in both measures; preferred200 still needs8catalogue works. No existing-work links. Campaign1383new+4existing links across9museums,1387protected IDs. Real local catalogue unchanged. Goal ACTIVE and incomplete.

Use this checkpoint/register/230-row under100 priority subset as current production baseline. Only Chania refreshed, not a global census. Immutable plan chania-delivery-20261010/chania-production-001-plan-001.json.gz SHAed0eeef0e9cfb0443445e9a6a8512ddf50bec7798cd36c76730635702bb75ebe. Import ops/museum-expansion-chania-apply-20261010.py directly for validate_plan/verify; no adapter needed. c.snapshot includes media_rights_evidence ordered by actualPKmedia_id. One canonical external identifier per physical artwork/source; all180source records remain in full facts/citations. Backup1791641216707SUCCESSFUL.23offline tests, atomic verification, independent readback, zero-write replay,188public image byte checks and4dated artwork API samples passed.41full existing comparator records and1213previous campaign IDs preserved.

New174types68metalwork54ceramic40sculpture12unknown;117numeric57qualifiedperiod/conflict/unknown. All18old unknown catalogue dates unchanged;16receivefirst primaryimages. Ninequalified workshop labels remain object-level, othermakersanonymous; no artistauthority links, publication or display claims. CauldronΜ825Α–ΣΤ source309+319+322+320+318+321 oneunit/sixviews, unknownnumericdateconflict; gold hairornament pairΜ763Α/Β sources1396+836 oneundatedunit/noimage.188images=183primary+5extra cauldronviews,167new works+16existing. Imageholds38/110/161 (source-image/text mismatch), physical-dateholds67/78/99/187 retained. Old8/20 date-imageholds retained. Hadrian185117–138CE range; Tiberius1971–50CE creation, not reign14–37. Native123/49mixedLatinGreekletters preserved;75titlefromnativebrowser/alt whereheadingblank,inventoryΛ2038notfilenameM. ActualCCBYNCND3.0GR separateGreekpre1955userapproval. Full native frames retained, JPEG<=100000B, no copyright-holder licence or currentdisplay invented.

Fresh global source/accession/translated-title/image search returned41artworks,46citations,10creatorlinks,18existing source matches and0imagechecksumhits. All174candidates remained new. Eight same-title sculptures distinguished by physical dimensions, accessions/provenance/descriptions;5officialAcropolis frames+4Chania frames/contact visuallychecked. ChaniaΛ27678cm basinbearer differs fromNMA91/85/414/294smallfigures;Λ135132cmAsclepius differs fromAcropolisNMA35088cm andPaphosPE1/6748cm;Λ3176portrait56×34cm385–410CE differs fromAIC2002.1164.8×47.6cm140–150CE;Π7247bull43cm withchestholes differs fromCyprusAI155636.2cm withsnakes. Fifteen incidental accession collisions withlaterpaintings/prints notmerged. Focusedwriter001 encountered unrelatedplaintext citation duringJSONparse; v2 skipped that and reused successfulcaptures withoutretryingdownloads. Both writers remain immutable.

NEW source access holds: web.open returned403at https://amch.gr/collection/agalma-asklipiou-l-135 and https://www.artic.edu/artworks/159136/portrait-bust-of-a-woman. No requests/alternateAPI retries or bypass. All212pairedChania object sources and188prepared images were already captured earlier10Oct and revalidated; this legitimate cached evidence supported delivery. AIC/Cyprus source bodies verifiedoffline. Acropolishealthy. Keep these holds with all earlier403/429/timeout restrictions. NativeChania108source records remain unreviewed,14art-scope holds; counts do not imply108eligible newworks. Reaching200needs8additional actualworks, notparts/filler. Do not rewrite originalresearchCP119 orresearchREADMEpendingcounts; thisdelivery supersedesonlythese174pendingcandidates.

Next deliver422reviewed candidates: Zongolopoulos199, Theocharakis197, Kilkis26, after fresh scoped/globalidentity checks using NEW deliveryruns and scripts. CP117zongolopoulos-20261010SHA32b31e616cf63bd20a1edc62468fe01fb6c23fea9a8474e4b8aa91419402582e (49dated); CP118zongolopoulos-paintings-20261010SHAb62abdfbe4fa05e5309431b9e78baae7baea6859403f47f9a4d3d58ef060c49c (150further), two-sided supports countonce,physicalunknownsexplicit,19imagesprepared. CP115theocharakis-20261010SHA111102ce42532f27023cc3b2c22f580a547efc232896982933b4618b499dc8ba (138) and CP116theocharakis-dated-20261010SHA19104950752f9be76c22d8cbf159f569f38ad56ab5c78b24b807ba6e7a5423ec (59), total125numeric72unknown. CP114kilkis-review-20261010SHAb224245951d11814db9dcc2104b868f2b2600c7f7998c066097b4c6000a07f9e,26selected6holds; revisit overlybroad NC/ND imagehold underactualGreeksourcepolicy. Candidate counts are not guaranteed newIDs. Updatecounts only afteractualdelivery.

Afterpending deliveries continueAveroffnative catalogue. Prior fresh discovery: kazantzakis-more-delivery-20261010/next-source-discovery-001.json.gz, native site https://www.averoffmuseum.gr/ advertises>700works versusSC71. Observed /zografiki /glyptiki /haraktiki /shedio /fotografia /nea-mesa-ekfrasis; no objectreview yet. IIDea977842-2f6e-5020-a853-d300b507aca0,last18/9.700iscollectionclaim not eligibleworkcount; shopreproductionsnotoriginalobjects. AthensCityIIDf575847e-47eb-59e4-b558-32d8723bc3c9, SC DigAthensMuseum,last18/16 follows.

Taskproxy127.0.0.1:55519 PID7614 --gcloud-auth checkedliveW123. Existing gcloudidentity works. Leaveunrelated55445/55478proxies/cloudjobs untouched; inspect authoritative process before recovery, neverrestartmerely becauseobservationtimedout. No credential printing, alternateidentity, subagents, commits, deployment, localwrites orfixtures. Executedwriters/pinnedartifacts immutable; versions forcorrections. Inheritfullhistoricalarchive proof rather thanrehashing44kfiles eachwave; verifynewpins/relevantsnapshots. Sourceholds inheritedArtUK,ArCo,Lombardia,MuseiReali,Bristol,Perth,LondonPictureArchive,Smartify,Salford,Glasgow,RCT,IWM,Met,NGA,WatercolourWorld,NationalGalleries,Freiburg,Brest,ElGreco/Commons,Kazantzaki,Anemoyannis,ejournals,Zongolopoulos andLarissanativeimage failures remain. Productionselectedadditions/images alreadyauthorized; no repeatedapproval.'''
    result=dict(prior)
    result.update(at=m.now(),wave=123,goal_complete=False,goal_status='active',previous_goal_turn='progress',production_only=True,local_unchanged=True,new_additions=174,new_existing_links=0,new_images=188,verification=report['verification'],production_museum_before=report['museum_before'],production_museum_after=report['museum_after'],production_campaign_totals=report['production_campaign_totals'],global_production_counts_refreshed=False,global_production_thresholds_refreshed=False,new_tests_passed=23,plan_sha256=digest,plan_reference=c.ref(a.PLAN),prior_checkpoint_reference=c.ref(c.CP),previous_research_checkpoint=c.ref(c.RESEARCH_CP),artifacts=list(pins.values()),external_artifacts=list(external.values()),baseline_reference=c.ref(RUN/'baseline-verification-001.json'),review_reference=c.ref(a.REVIEW),checks_reference=c.ref(RUN/'checks-001.json'),public_delivery_reference=c.ref(RUN/'public-delivery-001.json'),production_institution_register_reference=c.ref(RUN/'production-institution-register-001.json.gz'),priority_museum_queue_reference=c.ref(RUN/'priority-museum-queue-001.json'),protected_production_ids_reference=c.ref(RUN/'protected-production-ids-001.json'),pending_candidates=pending,pending_candidate_total=422,global_threshold_summary_note='Only Chania refreshed to192/117. Other observations retain historicaltimestamps;230priority rows are a subset.',source_availability=report['source_access'],new_source_access_hold_reference=c.ref(RUN/'new-source-access-holds-001.json'),remaining_research_reference=c.ref(m.RUN/'native/zongolopoulos-paintings-20261010/research-checkpoint-001.json'),preferred_target_remaining=dict(institution_id=c.IID,catalogue=192,gap_to200=8,unreviewed_source_records=108),public_api_date_scope=public['date_scope_note'],next_work=next_work)
    for key in ['superseded_plan_reference','identifier_reconciliation_reference','replay_contention_note']:result.pop(key,None)
    m.save(dest,result)
    m.save(RUN/'final-checkpoint-verification-001.json',dict(at=m.now(),checkpoint=c.ref(dest),verified_new_artifact_pins=len(newpins),verified_new_external_pins=len(newext),inherited_unchanged_artifact_pins=len(pins)-len(newpins),inherited_unchanged_external_pins=len(external)-len(newext),full_historical_proof=prior['initial_full_historical_verification_reference'],plan_sha256=digest,goal_complete=False,actual_added=174,actual_existing_links=0,actual_images=188,protected_production_ids=1387,pending_candidates=422,local_unchanged=True))
    print(json.dumps(dict(checkpoint=c.ref(dest),artifacts=len(pins),external=len(external),verified_new=len(newpins),verified_external=len(newext),added=174,images=188,pending=422)),flush=True)

if __name__=='__main__':main()
