"""Document verified wave76 and carry forward every unresolved notice."""
import collections,hashlib,importlib.util,json
from pathlib import Path
z=importlib.util.spec_from_file_location('a',Path(__file__).with_name('museum-expansion-italy-fifth-apply-20261008.py'));a=importlib.util.module_from_spec(z);z.loader.exec_module(a);m=a.m
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 report=m.load(m.RUN/'verification-after-wave-76.json');assert report['verified_new_artworks']==10259;plan,digest=a.validate_plan()
 with m.connect() as db:verified=a.verify(db,plan,digest)
 logsroot=Path('/Users/vadimdulub/Library/Logs');prefix='artline-italy-fifth-';testlog=(logsroot/(prefix+'tests-20261008.log')).read_text();assert 'Ran 13 tests' in testlog and testlog.rstrip().endswith('OK');assert (logsroot/(prefix+'replay-20261008.log')).read_text().strip()=='Unchanged replay: zero writes'
 logs={p.name:dict(path=str(p),sha256=sha(p)) for p in sorted(logsroot.glob(prefix+'*-20261008.log')) if p.name not in [prefix+'delivery-20261008.log',prefix+'checkpoint-20261008.log']}
 ds=m.load(a.REVIEW)['decisions'];states=collections.Counter(v['state'] for v in ds);assert states=={'approved_review_only_addition':211,'editorial_hold':139,'deferred_identity_review':51}
 checks=a.RUN/'checks-001.json';assert not checks.exists();m.save(checks,dict(at=m.now(),new_offline_tests_passed=13,historical_tests_passed=1457,cumulative_verified_tests=1470,historical_tests_rerun=False,replay_zero_writes=True,source_notices_assessed=401,successful_object_responses_reparsed=698,added=211,editorial_holds=139,deferred_identity_candidates=51,logs=logs,other_job_totals_separate=True,test_correction='Initial test expected lowercase tela; corrected expectation to literal source Tela. Initial failed log retained.'))
 original={v['number']:v for v in m.load(a.r.SOURCE/'native-candidates-002.json.gz')['rows']};comps={v['number']:v for v in m.load(a.RUN/'selected-identity-001.json.gz')['comparisons']};queue=[]
 for d in ds:
  if d['state']=='approved_review_only_addition':continue
  row=original[d['number']];queue.append(dict(d,source_issues=row['issues'],source_reference=row.get('source_reference'),source_url=row['index_record']['source_url'],existing_source_hits=comps.get(d['number'],{}).get('source_hits',[])))
 priorq=m.load(a.old.RUN/'remaining-research-001.json.gz');retained=[v for v in priorq['rows'] if v['institution_id'] not in a.r.s.TARGETS];assert len(retained)==162 and len(queue)==190
 m.save(a.RUN/'remaining-research-001.json.gz',dict(at=m.now(),rows=queue+retained,review_reference=a.reference(a.REVIEW),prior_queue_reference=a.reference(a.old.RUN/'remaining-research-001.json.gz'),inventory_audit_reference=a.reference(a.RUN/'comparison-source-context-001.json.gz'),policy='352 notices retained:190 unresolved in this three-museum review and162 unchanged Vicenza/Devanna notices. All five museums now exceed100 eligible works;200 remains preferred. No quota-based approval.'))
 cp=m.load(a.CHECKPOINT);priority=cp['next_museum_pass_reference'];a.checked(priority);oldqueue=m.load(m.ROOT/priority['path']);live={v['id']:v for v in m.load(m.RUN/'after-wave-76.json')['institutions']};nextm=[]
 for v in oldqueue['italian_museums']:
  cur=live[v['institution_id']]
  if cur['eligible_works']<100:nextm.append(dict(v,current_linked=cur['works'],current_eligible=cur['eligible_works']))
 assert len(nextm)==226
 m.save(a.RUN/'next-museum-pass-001.json',dict(at=m.now(),previous_queue_reference=priority,italian_museums=nextm,current_five_museum_research_reference=a.reference(a.RUN/'remaining-research-001.json.gz'),next_targets=[v['institution_id'] for v in nextm[:3]],policy='Continue other underfilled museums from this preserved source queue. All five researched museums exceed100 eligible;200 remains preferred. Cached leads require exact identity, chronology and custody review. Preserve all earlier access holds.',database_writes=0))
 changes=[v for v in report['italy_fifth_museum_changes'] if v['new']];table='| Museum | Added | Linked before → after | Eligible before → after |\n| --- | ---: | ---: | ---: |\n'+'\n'.join('| '+v['name']+' | '+str(v['new'])+' | '+str(v['linked_before'])+' → '+str(v['linked_after'])+' | '+str(v['eligible_before'])+' → '+str(v['eligible_after'])+' |' for v in changes)
 text='''# Fifth Italian minimum pass — 8 October 2026

Added **211 real local artwork records** at three museums, each now above 100 eligible works. Every addition has a national-catalogue identifier, citation and accepted holding assertion. Historical review statuses remain intact; catalogue visibility follows the unified-catalogue policy.

'''+table+'''

All 698 previously captured object facts were reconstructed from exact HTML and ArCo RDF. This review assessed the 401 notices for these three museums; 211 have individual supported decisions in the [editorial review](editorial-reviewed-001.json.gz). The fresh comparison covered 32,224 existing artworks and 66,846 citations. Historical comparison context contains 3,674 object records and 209 recent structured citation contexts, backed by 517 pinned response bodies.

Copies remain distinct from originals; paintings, preparatory models and prints have their own physical identities. Separate fresco fragments require source and support evidence. Multiple figures or scenes on one support count once. Villa Guinigi's two 1843 Lucca plans have different print techniques, dimensions, mounting and inventories. Shared historical inventory66, generic unresolved portraits, the inventory20 collision and ambiguous versions remain in research. Literal creator qualifications, questioned saints, unnamed makers, historical attribution evidence, dates and unknown techniques are preserved. Greco-Adriatic, Veneto-Cretan and Byzantine traditions remain represented.

The [remaining queue](remaining-research-001.json.gz) retains **352 notices**: 190 unresolved in this review and 162 unchanged from Vicenza/Devanna. The [next-museum queue](next-museum-pass-001.json) contains **226 Italian museums below 100 eligible works**. Previous source-access holds remain in force. A low source yield does not establish that a museum has fewer than 100 eligible works.

The [transaction plan](italy-fifth-additions-001-plan-001.json.gz) and [application receipt](italy-fifth-additions-001-applied.json) verify all 211 artworks, identifiers, citations and holding assertions. All 505 initial target-scope records, '''+format(verified['protected_existing_records'],',')+''' scoped comparison records and 10,833 prior campaign records were preserved. A fresh comparison ran inside the transaction. Thirteen offline checks, exact readback and a zero-write replay passed; 1,457 historical checks remain pinned. An initial test case expectation was corrected to preserve the source spelling “Tela”; its log is retained. No images, painter authority links, publication or display claims were added. No commits or deployment.

Campaign totals: **10,259 new artworks and 785 reconciled holding links across '''+str(report['institutions_with_new_records_or_reconciled_holdings'])+''' institutions**. The audit still has **'''+format(report['after']['museums_below_100'],',')+''' canonical museums below 100 linked works** and'''+format(report['after']['museums_below_200'],',')+''' below 200. The all-museum goal remains active. Separate jobs retain separate totals. Future work must rebase the five-museum scope to 716 records and prior campaign protection to 11,044.
'''
 targets=[(a.RUN/'README.md',text)];root=m.RUN/'README.md';pin=next(v for v in cp['artifacts'] if v['path']==str(root.relative_to(m.ROOT)));assert sha(root)==pin['sha256'];before=root.read_text();split=before.index('\n## Added works');intro=before[:split].replace('10,048','10,259').replace('208 local museums',str(report['museums_expanded'])+' local museums').replace('expand 211 institutions','expand '+str(report['institutions_with_new_records_or_reconciled_holdings'])+' institutions').replace('1,250',format(report['after']['museums_below_100'],',')).replace('1,555',format(report['after']['canonical_museums'],',')).replace('after-wave-75','after-wave-76')
 lines=before[split:].splitlines();ix=next(n for n,v in enumerate(lines) if v.startswith('| Italian national catalogue / ArCo — fourth'));lines.insert(ix+1,'| Italian national catalogue / ArCo — fifth minimum pass | 211 | 3 museums |');ix=next(n for n,v in enumerate(lines) if v.startswith('| Distinct new-record campaign total |'));lines[ix]='| Distinct new-record campaign total | **10,259** | **'+str(report['institutions_expanded'])+' collections** |'
 targets.append((root,intro+'\n'+'\n'.join(lines)+'\n\n## Fifth Italian minimum pass\n\nThe [fifth Italian pass](native/italy-fifth-minimum-20261008/README.md) added **211 review-status records**, bringing Cenacolo di Andrea del Sarto, Ala Ponzone and Villa Guinigi above 100 eligible works each.\n\n'+table+'\n\nExact readback, 13 offline checks and zero-write replay passed. The [wave 76 verification](verification-after-wave-76.json) records **10,259 additions and 785 holding reconciliations across '+str(report['institutions_with_new_records_or_reconciled_holdings'])+' institutions**. '+format(report['after']['museums_below_100'],',')+' canonical museums remain below 100 linked works. Continue the next 226 underfilled Italian museums and the wider global queue. The all-museum goal remains unfinished.\n'))
 supers=[]
 for index,(path,contents) in enumerate(targets):
  backup=m.BACKUP/('italy-fifth-readme-before-'+str(index+1).zfill(3)+'.json.gz');assert not backup.exists();oldhash=sha(path);m.save(backup,dict(at=m.now(),path=str(path.relative_to(m.ROOT)),sha256=oldhash,text=path.read_text()));path.write_text(contents);supers.append(dict(path=str(path.relative_to(m.ROOT)),before_sha256=oldhash,after_sha256=sha(path),backup_path=str(backup),backup_sha256=sha(backup)))
 m.save(a.RUN/'readme-supersessions-001.json',dict(at=m.now(),changes=supers,policy='Replace current pass and campaign overview with verified delivery; exact prior texts preserved. External unified-catalogue AGENTS change recorded separately.'))
 print(json.dumps(dict(documented=211,campaign_total=10259,expanded=report['institutions_with_new_records_or_reconciled_holdings'],museums_expanded=report['museums_expanded'],remaining_below100=report['after']['museums_below_100'],next_underfilled_italian_museums=len(nextm))),flush=True)
if __name__=='__main__':main()
