"""Version-aware source facts; source asset IDs never substitute for accession numbers."""
import collections,importlib.util,json
from pathlib import Path
z=importlib.util.spec_from_file_location('old',Path(__file__).with_name('museum-expansion-guildhall-facts-v2-20261009.py'));old=importlib.util.module_from_spec(z);z.loader.exec_module(old)
m=old.m;RUN=old.RUN;ref=old.ref;checked=old.checked;IID=old.IID;body=old.body;creation=old.creation
def newfacts(record):
 p=record['parsed'];assert old.n.g.parsed(body(record['capture']))==p;fields={v['label']:v['value'] for v in p['fields']};assert len(fields)==len(p['fields']);c=record['card'];assert p['headings']==[fields['Title']] and c['title']==fields['Title'] and c['creator']==fields['Creator'];assert record['capture']['receipt']['url']==record['capture']['receipt']['final_url']==c['url'];assert c['source_id']==c['url'].rsplit('/',1)[-1]
 head=p['publisher_heading'];text=p['text'];narr=text[text.index(head)+len(head):].split('Details')[0].strip();museum=fields.get('Location')=='Guildhall Art Gallery' and fields.get('Original Source') in ['https://www.cityoflondon.gov.uk/guildhallartgallery','https://www.cityoflondon.gov.uk/things-to-do/visit-the-city/attractions/guildhall-galleries/Pages/guildhall-art-gallery.aspx'];assert any(v in p['partner_links'] for v in ['/partner/guildhall-art-gallery','/partner/city-of-london-corporation','/partner/dordrechts-museum'])
 return dict(source_id=c['source_id'],source_url=c['url'],title=c['title'],titles=[c['title']],creator_label=c['creator'],source_fields={'ATTRIBUZIONI':c['creator']},date_display=fields.get('Date Created'),**creation(fields.get('Date Created')),inventory=None,medium=fields.get('Medium'),dimensions_text=None,work_type='painting',object_form=None,native_page_urls=[],native_metadata_urls=[],native_fields=fields,narrative=narr,rights=fields.get('Rights'),publisher_heading=head,native_issues=[] if museum else ['Publisher alone does not establish collection membership'],supplemental_references=[],derived_fields=[],source_note='Museum-published metadata; literal fields retained. No image or current-display claim. Historical loans are distinct from collection holdings.')
def rows():
 out=old.rows();by={v['number']:v for v in out};extras=m.load(RUN/'additional-captured-001.json');d=m.load(RUN/'dyce-dated-001.json');dp=d['parsed'];fields={v['label']:v['value'] for v in dp['fields']};dyce=dict(d,card=dict(source_id='qwF9gzxjLpAUCA',url=d['url'],title=fields['Title'],creator=fields['Creator']))
 replacement=[(14,dyce,ref(RUN/'dyce-dated-001.json'))]+[(v['number'],m.load(checked(v['reference'])),v['reference']) for v in extras['rows']]
 for number,rec,source in replacement:
  f=newfacts(rec);prior=by.get(number)
  if prior:
   f['prior_presentation_lead']=dict(source_id=prior['source_id'],source_reference=prior['source_reference'],facts=prior['facts'],identity_status='Research lead only; no assertion that generic asset is the same physical version');f['native_page_urls'].append(prior['facts']['source_url'])
  if number==14:
   sup=m.load(RUN/'dyce-medium-001.json');assert old.n.g.parsed(body(sup['capture']))==sup['parsed'];sf={v['label']:v['value'] for v in sup['parsed']['fields']};assert (sf['Title'],sf['Creator'],sf['Date Created'],sf['Location'],sf['Medium'])==('George Herbert at Bemerton','William Dyce','1860','Guildhall Art Gallery','Oil on canvas');f['medium']=sf['Medium'];f['native_page_urls'].append(sup['url']);f['supplemental_references'].append(ref(RUN/'dyce-medium-001.json'));f['derived_fields'].append('medium_from_matching_dated_City_of_London_presentation')
  else:
   f['supplemental_references'].append(rec['story_reference']);story=m.load(checked(rec['story_reference']));raw=body(story['capture']);assert f['source_url'].replace('https://artsandculture.google.com','').encode() in raw
  if number==20:
   storytext=story['parsed']['text'];assert 'London, Guildhall Art Gallery A spectacular full-sized oil sketch' in storytext;hist=m.load(RUN/'collection-history-001.json');body(hist['capture']);assert 'a full size sketch in oils by John Constable Salisbury Cathedral from the Meadows (1829-31)' in hist['parsed']['text'];f.update(title='Salisbury Cathedral from the Meadows (full-size oil sketch)',titles=['Salisbury Cathedral from the Meadows','Salisbury Cathedral from the Meadows (full-size oil sketch)'],date_display='1829–1831',first=1829,last=1831,date_precision='range',medium='Oil',native_issues=[]);f['supplemental_references'].append(ref(RUN/'collection-history-001.json'));f['derived_fields']+=['qualified_sketch_title_medium_and_creation_range_from_Guildhall_history','explicit_Guildhall_lender_credit_in_Dordrecht_story_not_Dordrecht_holding'];f['source_note']+=' Source asset dated1829; official Guildhall history1829–31 preserved as range. The exact story asset is used; the earlier generic Guildhall asset remains an unverified presentation lead.'
  if number==37:f['titles'].append('An Arabian Encampment at the Wells of Moses')
  v=dict(number=number,source_id=f['source_id'],institution_id=IID,facts=f,source_reference=source,retrieved_at=rec['capture']['receipt']['retrieved_at'],state='candidate' if not f['date_issue'] and not f['native_issues'] else 'source_hold');by[number]=v
 # Do not promote an undated generic asset to the documented watercolour without an exact crosswalk.
 v=by[23]['facts'];v['native_issues']=['Collection history supports a watercolour, but exact generic GAC asset/version mapping is unresolved'];by[23]['state']='source_hold'
 out=[by[k] for k in sorted(by)];assert len(out)==40 and len({v['source_id'] for v in out})==40;return out
def main():
 p=RUN/'native-candidates-003.json.gz';assert not p.exists();rs=rows();m.save(p,dict(at=m.now(),rows=rs,script_reference=ref(Path(__file__).resolve()),prior_candidates_reference=ref(RUN/'native-candidates-002.json.gz'),additional_reference=ref(RUN/'additional-captured-001.json'),policy='40 selected object leads. Dated replacement presentations count once. Exact loan asset tied to explicit Guildhall credit; generic Millais watercolour crosswalk remains held. No images.'));print(json.dumps(dict(rows=len(rs),states=dict(collections.Counter(v['state'] for v in rs)))),flush=True)
if __name__=='__main__':main()
