"""Wave125 checkpoint after verified selected Foundation production delivery."""
import hashlib
import importlib.util
import json
from pathlib import Path
spec=importlib.util.spec_from_file_location('d',Path(__file__).with_name('museum-expansion-zongolopoulos-delivery-20261010.py'))
d=importlib.util.module_from_spec(spec);spec.loader.exec_module(d)
a,c,m,RUN=d.a,d.c,d.m,d.RUN
sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest()

def main():
    dest=RUN/'delivery-checkpoint-001.json';assert not dest.exists();report=m.load(RUN/'delivery-001.json');checks=m.load(RUN/'checks-001.json');public=m.load(RUN/'public-delivery-001.json')
    assert report['added']==198 and report['existing_links']==0 and checks['readback_passed'] and checks['replay_zero_writes'] and public['public_image_hashes_matched']==18 and public['public_artwork_samples']==4
    plan,digest=a.validate_plan();assert digest==d.EXPECTED and c.ref(c.CP)['sha256']==c.CP_SHA
    prior=m.load(c.CP);oldpins={v['path']:v for v in prior['artifacts']};oldext={v['path']:v for v in prior['external_artifacts']};pins=dict(oldpins);external=dict(oldext)
    def add(pin,target):
        assert pin['path'] not in target or target[pin['path']]==pin,pin['path'];target[pin['path']]=pin
    paths={c.CP,c.RESEARCH_CP,c.DATED/'research-checkpoint-001.json',a.PLAN,Path(__file__).resolve()}
    paths|={v for v in RUN.rglob('*') if v.is_file()};paths|={v for v in (m.ROOT/'ops').glob('*zongolopoulos*20261010.py')}
    for path in sorted(paths):add(c.ref(path),pins)
    for pin in plan['evidence']:add(pin,pins)
    for pin in plan['external_evidence']:add(pin,external)
    for path in sorted(m.BACKUP.glob('zongolopoulos-production-*.json*')):add(dict(path=str(path),sha256=sha(path)),external)
    add(dict(path=plan['backup_path'],sha256=sha(plan['backup_path'])),external)
    newpins=[v for v in pins.values() if oldpins.get(v['path'])!=v];newext=[v for v in external.values() if oldext.get(v['path'])!=v]
    for pin in newpins:c.checked(pin)
    for pin in newext:assert sha(pin['path'])==pin['sha256'],pin['path']
    protected=m.load(RUN/'protected-production-ids-001.json')['ids'];assert len(protected)==1782 and set(protected)==set(plan['prior_ids'])|{v['artwork_id'] for v in plan['records']}
    pending=report['remaining_pending_candidates'];assert sum(pending.values())==26
    next_work='''Wave125 made verified production progress: Zongolopoulos198 new review artworks+18authentic primary images. Museum18catalogue/18numeric/6primary to216catalogue/67numeric/24primary. Preferred200catalogue reached; numeric eligibility remains33below100.149new records have unknown dates, not presumed eligible. Campaign1777new+5existing links across11museums;1782protected IDs. Real local unchanged; goal ACTIVE/incomplete.

Plan native/zongolopoulos-delivery-20261010/zongolopoulos-production-001-plan-001.json.gz SHA8a552360c2f84068b390c9da2f29ee080cb981d1f047c24d1c56ff0fbe0f27c8. Use ops/museum-expansion-zongolopoulos-apply-20261010.py directly for validate_plan/verify.20offline tests, atomic apply verification, independent readback, zero-write replay,18public image hashes and4dated API samples passed. Backup1791644051144 SUCCESSFUL, operation697e6c94-cdc1-426e-b041-d2a800000024, end14:55:42.425Z.64focused existing snapshots+1584prior campaign IDs preserved. All18old target rows and6primaries unchanged. No artist links, publication changes, current-display claims, authority creation or catalogue date rewrites.

Prior199candidates revised to198. First-wave source64302(Venice watercolour1953) is newly held: same three-figure foreground gondola, architecture and right curved boat as fuller64304; different framing/colour/perspective do not prove two physical works. Both existing thumbnails and observed SearchCulture public preservation previews were inspected. Keep64304once, no forced alias or alternate image from64302. Earlier61cast/model/version source holds plus painting64218description/image conflict remain; total63source identity holds. Existing source18records include old cast/version duplicate flags;216catalogue records is not a certificate that every older physical holding is distinct. Avoid claiming all museum targets complete.

New198=48first-wave dated+150painting-wave,49numeric149unknown. Types26drawings30sculptures65watercolors63paintings1print13unknown.37anonymous object labels; conflicting George-vs-E.signature64479qualified; unsigned Helen-folder64360qualified; no George/Helen authority found in expanded live names/aliases, no fabricated painter IDs.16two-sided supports countonce, reused canvas once. Print64290signature1933does not date impression17/20; keepnumericnull. Helen64368date1960is source-reported inscription, metadata-only under1955image cutoff. Repeated exportdigits(10921092etc) are literal evidence, neverhalved into accession; canonical inventorynull. All source descriptions/rights/enrichment retained inmetadata. Primary source externalIDonceperwork.18images sourceJPEGbytes unchanged,<=100000B, pre1956, authenticCCBYNCND4.0restricted label plus separateGreekuserapproval. Unknown/post1955works noimages. No inventedcurrentdisplay/fullmonumentholdings.

Read-only globalidentity949artworks672creatorlinks1924citations;936exact-title hits21unlinkedcreatorlabels10literalaccessioncollisions24sourcecites18sourceIDs0imagehashhits. All18oldsourceIDsmatched; no newselectedexactsource match. Focus64=51literalGreektitle(including18target)+3expandedcreator+10accession.32existingprimaryimages+3additionalSCframes inspected;37anonymouscandidateframes checked;19preparedframes+2Venicepreviews checked. NationalGalleryMrsM.K.headlongneck/wavyhair differsfromoldFoundationroundchildhead andnewplaster/Ireneheads. LarissaVouliagmeni1935watercolor33x39.5bluebaybetween2trees differsfromselectedlandscapes; protected. LelaPaschali1950pinesnotHelen. ASFAanonymous horizontalochre/brownbands+verticalyellowline differsfromFoundation64222greenfields/blueband/circle; twoLekakisblackwhiteabstractsdifferentgeometry.12generic-title comparatorslackexposedthumbnail, no visualclaim. GenericEnglishUntitled/Abstractnotgloballyenumerated; no exhaustivedupguarantee. One-offqueryplansnot10Mloadproof.

Both original research checkpoints verified all935artifact339externalpins; earlier45119/3500pins inherited fullarchiveproof. ResearchCP117SHA32b31e616cf63bd20a1edc62468fe01fb6c23fea9a8474e4b8aa91419402582e andCP118SHAb62abdfbe4fa05e5309431b9e78baae7baea6859403f47f9a4d3d58ef060c49c pendingcounts now historical, supersededbydelivery. CP124TheocharakisSHA36cd7e7b1ca4a9ce50552ca5fe2e819677dc5e35fddb3147632f6ba083cd57fb verified baseline. Theo215/137preferredtargetreached. Chania192/117still8below200,108unreviewedsourceentries14scopeholds; no nativeaccessretry. Current228-row priorityqueue is inheritedunder100cataloguesubset, notglobalcensus; removedZongdue216cataloguebutnumericgap33trackedseparately. OnlyZongregisterrowrefreshed.

Next pending26Kilkis candidates at native/kilkis-review-20261010/research-checkpoint-001.json SHAb224245951d11814db9dcc2104b868f2b2600c7f7998c066097b4c6000a07f9e. Reconcilefreshproduction/scopedglobalIDs andimageidentity/date policy. EarlierNCNDimageholdmaybetoobroadunderGreekapproval; actuallabelsremainrestricted. No guarantee26newuntilreconciled. LastKilkis18/0. Sixsourceholdscontinue.

Next freshmuseumAveroffIIDea977842-2f6e-5020-a853-d300b507aca0,last18/9. Discovery native/kazantzakis-more-delivery-20261010/next-source-discovery-001.json.gz, https://www.averoffmuseum.gr/ advertises>700vsSC71. Observed /zografiki /glyptiki /haraktiki /shedio /fotografia /nea-mesa-ekfrasis; noobjectreviewyet.700claimnoteligiblecount;shopreproductionsnotoriginalworks. NEW W125 https://www.averoffmuseum.gr/zografiki web.open returned403. Do not retry this restricted provider or use another access route. Prior retained captures remain usable evidence; use independently available SearchCulture or other legitimate sources. Receipt next-source-access-hold-001.json. AthensCityIIDf575847e-47eb-59e4-b558-32d8723bc3c9SC DigAthensMuseum,last18/16 follows.

Keep ALL inherited provider403/429/timeout restrictions, including zongolopoulos.gr403 and collection.zongolopoulos.gr/eMuseumPlusone timeout plus XML/JSON errorHTML, Chaniaamch.gr403 andArtInstitute159136403W123, Larissanativeimages46/67/92failures andimage7timeout. W125webopens64302/64304reported inaccessible-tool/cache errors, notHTTP403; existing complete200HTML contained observed publicSCviewer links, successfully followed once. No restrictedhostretry/bypass. Backup/source/artifact credentials neverprinted. Taskproxy127.0.0.1:55519PID7614 --gcloud-auth validatedliveW125; leave it and unrelated55445/55478alone. Existinggcloudidentityworking. ResearchPythonLibraryvenv. No subagents, commits,deployment,real-localwrites,fixtures or newtestDB. Executed/pinnedwritersimmutable; newversionsforcorrections. Inheritarchiveproof,verifyonlynewpins/relevantsnapshots. Productionselectedadditions/imagesalreadyauthorized, no repeatedapproval.'''
    result=dict(prior)
    result.update(at=m.now(),wave=125,goal_complete=False,goal_status='active',previous_goal_turn='progress',production_only=True,local_unchanged=True,new_additions=198,new_existing_links=0,new_images=18,verification=report['verification'],production_museum_before=report['museum_before'],production_museum_after=report['museum_after'],production_campaign_totals=report['production_campaign_totals'],global_production_counts_refreshed=False,global_production_thresholds_refreshed=False,new_tests_passed=20,plan_sha256=digest,plan_reference=c.ref(a.PLAN),prior_checkpoint_reference=c.ref(c.CP),previous_research_checkpoint=c.ref(c.RESEARCH_CP),additional_research_checkpoint=c.ref(c.DATED/'research-checkpoint-001.json'),artifacts=list(pins.values()),external_artifacts=list(external.values()),baseline_reference=c.ref(RUN/'baseline-verification-001.json'),review_reference=c.ref(a.REVIEW),checks_reference=c.ref(RUN/'checks-001.json'),public_delivery_reference=c.ref(RUN/'public-delivery-001.json'),production_institution_register_reference=c.ref(RUN/'production-institution-register-001.json.gz'),priority_museum_queue_reference=c.ref(RUN/'priority-museum-queue-001.json'),protected_production_ids_reference=c.ref(RUN/'protected-production-ids-001.json'),pending_candidates=pending,pending_candidate_total=26,global_threshold_summary_note='Only Zongolopoulos refreshed to216catalogue/67numeric eligible. Other observations retain timestamps;228priorityrows are a subset.',source_availability=report['source_access'],remaining_research_reference=c.ref(m.RUN/'native/kilkis-review-20261010/research-checkpoint-001.json'),preferred_target_remaining=dict(institution_id=c.IID,catalogue=216,gap_to200=0,target_reached=True,numeric_eligible=67,numeric_gap_to100=33),public_api_date_scope=public['date_scope_note'],next_work=next_work)
    for key in ['superseded_plan_reference','identifier_reconciliation_reference','replay_contention_note','new_source_access_hold_reference']:result.pop(key,None)
    m.save(dest,result)
    m.save(RUN/'final-checkpoint-verification-001.json',dict(at=m.now(),checkpoint=c.ref(dest),verified_new_artifact_pins=len(newpins),verified_new_external_pins=len(newext),inherited_unchanged_artifact_pins=len(pins)-len(newpins),inherited_unchanged_external_pins=len(external)-len(newext),full_historical_proof=prior['initial_full_historical_verification_reference'],plan_sha256=digest,goal_complete=False,actual_added=198,actual_existing_links=0,actual_images=18,protected_production_ids=1782,pending_candidates=26,local_unchanged=True))
    print(json.dumps(dict(checkpoint=c.ref(dest),artifacts=len(pins),external=len(external),verified_new=len(newpins),verified_external=len(newext),added=198,links=0,images=18,pending=26)),flush=True)

if __name__=='__main__':main()
