"""Document verified wave75 and retain the remaining researched objects."""
import collections,hashlib,importlib.util,json
from pathlib import Path
z=importlib.util.spec_from_file_location('a',Path(__file__).with_name('museum-expansion-italy-fourth-apply-20261008.py'));a=importlib.util.module_from_spec(z);z.loader.exec_module(a);m=a.m
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 report=m.load(m.RUN/'verification-after-wave-75.json');assert report['verified_new_artworks']==10048;plan,digest=a.validate_plan()
 with m.connect() as db:verified=a.verify(db,plan,digest)
 logsroot=Path('/Users/vadimdulub/Library/Logs');prefix='artline-italy-fourth-';testlog=(logsroot/(prefix+'tests-20261008.log')).read_text();assert 'Ran 13 tests' in testlog and testlog.rstrip().endswith('OK');assert (logsroot/(prefix+'replay-20261008.log')).read_text().strip()=='Unchanged replay: zero writes'
 logs={p.name:dict(path=str(p),sha256=sha(p)) for p in sorted(logsroot.glob(prefix+'*-20261008.log')) if p.name not in [prefix+'delivery-20261008.log',prefix+'checkpoint-20261008.log']}
 ds=m.load(a.REVIEW)['decisions'];states=collections.Counter(v['state'] for v in ds);assert states=={'approved_review_only_addition':135,'editorial_hold':253,'deferred_identity_review':310}
 checks=a.RUN/'checks-001.json';assert not checks.exists();m.save(checks,dict(at=m.now(),new_offline_tests_passed=13,historical_tests_passed=1444,cumulative_verified_tests=1457,historical_tests_rerun=False,replay_zero_writes=True,source_notices_assessed=698,successful_object_responses_reparsed=698,added=135,editorial_holds=253,deferred_identity_candidates=310,logs=logs,other_job_totals_separate=True))
 original={v['number']:v for v in m.load(a.RUN/'native-candidates-002.json.gz')['rows']};comps={v['number']:v for v in m.load(a.RUN/'native-identity-002.json.gz')['comparisons']};queue=[]
 for d in ds:
  if d['state']=='approved_review_only_addition':continue
  row=original[d['number']];queue.append(dict(d,source_issues=row['issues'],source_reference=row.get('source_reference'),source_url=row['index_record']['source_url'],existing_source_hits=comps.get(d['number'],{}).get('source_hits',[])))
 m.save(a.RUN/'remaining-research-001.json.gz',dict(at=m.now(),rows=queue,review_reference=a.reference(a.REVIEW),inventory_audit_reference=a.reference(a.RUN/'comparison-source-context-001.json.gz'),policy='563 notices retained. Continue Cenacolo, Ala Ponzone and Villa Guinigi from saved exact sources and historical notes. Shared inventory/support, copies and recatalogue questions need physical identity reconciliation. Ambiguous dates, attribution and custody remain explicit.'))
 cp=m.load(a.CHECKPOINT);priority=cp['next_museum_pass_reference'];a.checked(priority);oldqueue=m.load(m.ROOT/priority['path']);live={v['id']:v for v in m.load(m.RUN/'after-wave-75.json')['institutions']};nextm=[]
 for v in oldqueue['italian_museums']:
  cur=live[v['institution_id']]
  if cur['eligible_works']<100:nextm.append(dict(v,current_linked=cur['works'],current_eligible=cur['eligible_works']))
 m.save(a.RUN/'next-museum-pass-001.json',dict(at=m.now(),previous_queue_reference=priority,italian_museums=nextm,current_five_museum_research_reference=a.reference(a.RUN/'remaining-research-001.json.gz'),next_targets=[v['institution_id'] for v in report['italy_fourth_museum_changes'] if v['eligible_after']<100],policy='Prioritize Cenacolo, Ala Ponzone and Villa Guinigi from existing captured research, then other underfilled museums. Vicenza and Devanna meet100 eligible;200 remains preferred. Cached leads need exact identity and custody checks.',database_writes=0))
 changes=report['italy_fourth_museum_changes'];table='| Museum | Added | Linked before → after | Eligible before → after |\n| --- | ---: | ---: | ---: |\n'+'\n'.join('| '+v['name']+' | '+str(v['new'])+' | '+str(v['linked_before'])+' → '+str(v['linked_after'])+' | '+str(v['eligible_before'])+' → '+str(v['eligible_after'])+' |' for v in changes)
 text='''# Fourth Italian minimum pass — 8 October 2026

Added **135 real local artwork records**: 63 at Vicenza and 72 at Devanna. Both museums now exceed 100 eligible works. Each addition has a national-catalogue identifier, citation and accepted holding assertion. All artworks remain in review.

'''+table+'''

The bounded source selection comprised 698 notices from five museums. All object pages and exact ArCo RDF responses were saved and reconstructed. Missing HTML street addresses were resolved only with the exact object-linked address, agreeing city URI, current museum URI and source coverage. Literal slash date ranges were accepted only when structured endpoints independently agreed; original displays were preserved. Museum storage-room labels do not establish public display.

The final 135-object identity comparison covered 12,666 existing artworks, with 1,581 possible comparison matches and no existing exact source identifiers. The historical-source audit reconstructed 2,250 contexts from 359 pinned response bodies. It found a shared inventory on a deferred Villa Guinigi object; none of the selected additions overlaps a local historical inventory or another selected inventory. Related Florence and Lucca collection scopes are comparison evidence, not institution mergers.

All selected works have individual decisions in the [editorial review](editorial-reviewed-001.json.gz). Creator labels preserve school, workshop, circle, manner and attributed status. Five header labels needed an explicit qualifier from their historical notes; the literal headings remain preserved alongside the derived labels. Greek/Venetian works by the Bizamano workshop, attributed Bathas and attributed El Greco remain qualified. Drawings containing several sketches, pasted architectural flaps, descriptive letters and paintings on the back of engraved copper are counted as single physical objects.

**253 source/editorial holds and 310 deferred identities** remain in the [research queue](remaining-research-001.json.gz). This includes the still-underfilled Cenacolo, Ala Ponzone and Villa Guinigi collections. Their exact sources and historical-note research are preserved for continuation. The [next-museum queue](next-museum-pass-001.json) contains '''+str(len(nextm))+''' Italian museums below 100 eligible works. Existing access holds elsewhere in the campaign remain in force.

The [transaction plan](italy-fourth-additions-001-plan-001.json.gz) and [application receipt](italy-fourth-additions-001-applied.json) verify 135 artworks, identifiers, citations and holding assertions. All 370 initial target-scope records, '''+format(verified['protected_existing_records'],',')+''' scoped comparison records and 10,698 prior campaign records were preserved. A fresh identity comparison ran inside the transaction. Thirteen offline checks and a zero-write replay passed; 1,444 historical checks remain pinned and were not rerun. No images, painter links, publication or display claims were added. No commits or deployment.

Campaign totals: **10,048 new artworks and 785 reconciled holding links across '''+str(report['institutions_with_new_records_or_reconciled_holdings'])+''' institutions**. The audit still has **'''+format(report['after']['museums_below_100'],',')+''' canonical museums below 100 linked artworks**, and '''+format(report['after']['museums_below_200'],',')+''' below 200. The global goal remains active. Separate jobs retain separate totals. Next work must rebase to 505 target-scope records and 10,833 prior campaign records.
'''
 targets=[(a.RUN/'README.md',text)];root=m.RUN/'README.md';pin=next(v for v in cp['artifacts'] if v['path']==str(root.relative_to(m.ROOT)));assert sha(root)==pin['sha256'];before=root.read_text();split=before.index('\n## Added works');intro=before[:split].replace('9,913','10,048').replace('206 local museums',str(report['museums_expanded'])+' local museums').replace('expand 209 institutions','expand '+str(report['institutions_with_new_records_or_reconciled_holdings'])+' institutions').replace('1,250',format(report['after']['museums_below_100'],',')).replace('1,555',format(report['after']['canonical_museums'],',')).replace('after-wave-74','after-wave-75')
 lines=before[split:].splitlines();ix=next(n for n,v in enumerate(lines) if v.startswith('| Italian national catalogue / ArCo — third'));lines.insert(ix+1,'| Italian national catalogue / ArCo — fourth minimum pass | 135 | 2 museums |');ix=next(n for n,v in enumerate(lines) if v.startswith('| Distinct new-record campaign total |'));lines[ix]='| Distinct new-record campaign total | **10,048** | **'+str(report['institutions_expanded'])+' collections** |'
 targets.append((root,intro+'\n'+'\n'.join(lines)+'\n\n## Fourth Italian minimum pass\n\nThe [fourth Italian pass](native/italy-fourth-minimum-20261008/README.md) added **135 review records**, bringing Vicenza and Devanna above 100 eligible works.\n\n'+table+'\n\nExact readback, 13 offline checks and a zero-write replay passed. The [wave 75 verification](verification-after-wave-75.json) records **10,048 additions and 785 holding reconciliations across '+str(report['institutions_with_new_records_or_reconciled_holdings'])+' institutions**. '+format(report['after']['museums_below_100'],',')+' canonical museums remain below 100 linked works. Cenacolo, Ala Ponzone and Villa Guinigi are the next researched targets. The all-museum goal remains unfinished.\n'))
 supers=[]
 for index,(path,contents) in enumerate(targets):
  backup=m.BACKUP/('italy-fourth-readme-before-'+str(index+1).zfill(3)+'.json.gz');assert not backup.exists();oldhash=sha(path);m.save(backup,dict(at=m.now(),path=str(path.relative_to(m.ROOT)),sha256=oldhash,text=path.read_text()));path.write_text(contents);supers.append(dict(path=str(path.relative_to(m.ROOT)),before_sha256=oldhash,after_sha256=sha(path),backup_path=str(backup),backup_sha256=sha(backup)))
 m.save(a.RUN/'readme-supersessions-001.json',dict(at=m.now(),changes=supers,policy='Replace current pass and campaign overview with verified delivery; exact prior texts preserved. Separate external AGENTS change is recorded in policy-change-001.json.'))
 print(json.dumps(dict(documented=135,campaign_total=10048,expanded=report['institutions_with_new_records_or_reconciled_holdings'],museums_expanded=report['museums_expanded'],remaining_below100=report['after']['museums_below_100'],next_underfilled_italian_museums=len(nextm))),flush=True)
if __name__=='__main__':main()
