"""Wave134verified delivery checkpoint; every-museum goal remains active."""
import hashlib,importlib.util,json
from pathlib import Path
spec=importlib.util.spec_from_file_location('d',Path(__file__).with_name('museum-expansion-jewish-delivery-20261010.py'))
d=importlib.util.module_from_spec(spec);spec.loader.exec_module(d)
a,c,m,RUN=d.a,d.c,d.m,d.RUN

def sha(path):return hashlib.sha256(Path(path).read_bytes()).hexdigest()

def main():
    dest=RUN/'delivery-checkpoint-001.json';assert not dest.exists();report=m.load(RUN/'delivery-001.json');checks=m.load(RUN/'checks-001.json');public=m.load(RUN/'public-delivery-001.json')
    assert report['added']==140 and report['new_images']==131 and checks['readback_passed'] and checks['replay_zero_writes'] and checks['local_unchanged'] and checks['offline_tests_passed']==21 and public['public_image_hashes_matched']==131
    p,digest=a.validate_plan();assert digest==d.EXPECTED and c.ref(c.CP)['sha256']==c.CP_SHA;prior=m.load(c.CP)
    oldpins={x['path']:x for x in prior['artifacts']};oldext={x['path']:x for x in prior['external_artifacts']};pins,external=dict(oldpins),dict(oldext)
    def add(pin,target):assert pin['path'] not in target or target[pin['path']]==pin,pin['path'];target[pin['path']]=pin
    paths={c.CP,a.PLAN,Path(__file__).resolve()}|{x for x in RUN.rglob('*') if x.is_file()}|set((m.ROOT/'ops').glob('museum-expansion-jewish-*.py'))
    for path in sorted(paths):add(c.ref(path),pins)
    for pin in p['evidence']:add(pin,pins)
    for pin in p['external_evidence']:add(pin,external)
    for path in sorted({x for x in c.PROOF.rglob('*') if x.is_file()}|set(m.BACKUP.glob('jewish-production-*.json*'))):add(dict(path=str(path),sha256=sha(path)),external)
    newpins=[x for x in pins.values() if oldpins.get(x['path'])!=x];newext=[x for x in external.values() if oldext.get(x['path'])!=x]
    for pin in newpins:c.checked(pin)
    for pin in newext:assert sha(pin['path'])==pin['sha256']
    protected=m.load(RUN/'protected-production-ids-001.json')['ids'];assert len(protected)==2938 and set(protected)==set(p['prior_ids'])|{v['artwork_id'] for v in p['records']}
    queue=m.load(RUN/'priority-museum-queue-001.json');assert len(queue['rows'])==222 and sum(x['country_code']=='GR' for x in queue['rows'])==62
    nextwork='''Wave134complete JewishMuseumofGreece IID760b0104-19ee-5ad1-94f0-0ceb8dcea09e:140newreviewartworkunits preserving143sources,131authenticnativeimages. Museum8catalogue/8eligible/8primary ->148catalogue/142numericdateeligible/139primary.134newnumericeligible,5unknown,1crossing20thcenturyrange. Minimum100met;52catalogueworkgapto200. Every-museumgoalACTIVEunfinished. Campaign2914new+7existinglinks across18museums.2938protectedIDs=2921campaignrecords+17Kilkisoldimageonly.222inheritedunder100rows,62Greek;notglobalcensus. No readyunappliedcandidates.

Use ops/museum-expansion-jewish-apply-20261010.py validate_plan/verify. Plan001 SHA d5fb635cea69eb0001a53898387d2cccd31d0f13fda981fcd869c5e4ea4ed8f9,review001.21checks,atomicverification,readback,zerowritereplay,131publicimagehashes and6publicsamplespassed. Backup1791659842587 opf7c64004-eda7-4824-be6f-0e0600000024 SUCCESSFUL2026-10-10T19:18:53.871Z beforewrite. Storage131newobjects verified. Firstapplyattempttimedout5swaitingforsharedadvisoryimportlock,beforeanywrites. import-lock-observation-001 proves0newartworks/sources/audits,preflightunchanged andnoadvisorylocksremaining. Sameimmutableplan/backup/uploads reusedonlyafterlockcleared; noothertransactioncancelled. After successfulcommit, firstindependentreadbacksession93288couldnotconnectbecauseproxy19001receivedSIGTERM22:26:54local(senderunknown). PID/listenerabsent,CloudSQLRUNNABLE,sameverifiedbinaryrestartedPID26804on127.0.0.1:55519. connection-recovery-001 andLibrarylogtailpreserved;readbackresumedwithoutreimport. Eightoldrecords,2798prior and4additionaltitlecounterparts preserved. Allnewstatusreview,holdingcollectionaccepted,noartistlinks,publication ordisplayclaims. Local0/0readonlyunchanged.

Source discovery: JewishMuseumgeneralcollection13533mixedrecords, nativehttps://artifacts.jewishmuseum.gr/ withpublicHTML, separateDigJewish1044records. Artindex196entries acrosspainting69,print90,drawing29,sculpture5,mosaic3. Twentyindexdatesentirelypost1970excludedbeforeindividualcapture.183fineart/oldcomparatorpagescaptured(176fromindex+7oldcomparators). TextileNeedleworkfacet585entries,463numericindexupperboundsby1955nonphotographleads; first280selectedmetadataonly. V1captured118then3objectHTTP500; previouslyunattempted1136succeeded200,V2captured8morethen3moreHTTP500. Twoearliercachedcanopyrecords1194/1195integrated:128textilepages.311uniqueindividualmetadatarecords reviewed.146selectedtextileleadsunattempted,6failed,305otherindexleads; notwholecollectioncoverage. SourceIDs jewishmuseum/000141-{slug}_ andoldDigJewish/000192-oai%3Anewartifacts.jewishmuseum.gr%3A123456789_{id}. Preserveencodedidentities.

SixnewHTTP500holds: tallit-bag-4_(1132),tallit-bag-22_(1133),tallit-bag-21_(1134),torah-binder-9_(1144),embroidered-textile-4_(1145),bookmark_(1146). Fullreceipts/bodyhashesinsource-access-holds-001. No failedroute retry/alternatehostname. Nativepublicpages and153selectedimages200. Canonicaljewishmuseum.gr highlights page200; earlierwwwdomainwebtoolinternalerrorhadnoHTTPstatus. NoauthenticatedAPIused. Sourcecollection/providerisnotphysicalholding:11MunicipalityMuseumofIoannina/SocietyforEpiroticStudiesobjectsheld.74photograph-*art/buildingprototypesheld, notoriginalartworkholdings oraccuratephotographdates.71otherdate/versionleads retained.176/177cartoons depictMunich1972,excluded. Source1072laceonbobbinheldscope;1117nearidenticalcushion84.124versus1116file84.125helddistinctphysicalidentity despitefilename difference.

Merged1021+1023sameuncutslipperpanelfile80.135and525x370mm;1038+1039samecurtainpanel98.40and45.8x87.9cm;1195+1194samehuppah2005.37and249x245cm,1195decoratedfrontprimary1194liningdetail.1196indexleadstillnotindividuallycaptured. Similarcushions1025/1087/1088visiblydifferent;1117held. Physicaltextiles withdifferentdimensions/fullcomponenttokens notautomaticallymergedfromsharedprovenance.140identifiers/143metadatacitations+131imagecitations/140acceptedholdings. Sourcefilenamesretainedasevidence,accessionfieldNULL. Clothbelt1043withmultipleplaquesonecompositemetalwork. Allothertextiletypespreserveunknownmaker andqualifiedfunction.

Dates:44literal1930s ->1930–1939decade. Late/end19th+early20th ->1871–1930, secondhalf19th+firsthalf20th ->1851–1950; native/literaldatespreserve19thcentury droppedbyaggregator. Fiveunknowncreationunits76,154,1038,1063,1115.76source1811conflictswithW.H.Bartlett1809birthofficialGovernmentArtCollection, no invented1838/1841impressiondate.154seventeenthcenturyalsodepictedperiod,actualwaxedcardboardmountedprintageunknown.1038source1940,1063source1945,1115source1904labelDedicationnotCreate; manufacture/assemblyunknown.1053native20thcenturyversusaggregatorEarly20th ->1901–2000century crossingcutoff,explicitreview. New134eligible,6review. Unknown/crossing and1962works48/192,1959drawing185noimages. Old203medalancientdateversuspendantmanufacture/image-descriptionneedsfutureresearch; unchanged.

153authenticvisualframes reviewed7contactsplus2focusedsheets;131preparedimages reviewed6sheets. All131deliveredfilesfromexactnativeprimaryimg.object-containURL. 52byteunchanged,79compressed/resizedproportionally,max99905B; originalmax638239B. No crop,enlargement,retouching/generatedimages. Somephotographsshowfoldedtextiles/detailviews,viewlabelmakesclearcompleteimageisnotcompleteunfoldedobject. Nativefilesmax1200longedge,originalsLibrary. SourceactualInCopyright(InC),http://rightsstatements.org/vocab/InC/1.0/,museumcopyrightretainedrestricted. Greekworkflowapprovalseparate,notcopyright-holderpermission orpublicdomain. Nativefileimage URLsinclude/uploads/artifacts/ and/2017/09/. SelectionV1incorrectlyclassifiedallnativeobjectsexternalbecauseglobalnavigationcontainsIoannina;V2correctsusingobjectbodyafterVisitMuseumWebsite. V1immutableandneverusedforvisual/delivery. Use selected-source-records-002 andmetadata-visual-selection-002. CollectorV1/V2andallpinnedscriptsimmutable.

Productionidentityreadreturned581artworks,10artistcandidates,767citations,8oldsource/imagehits. ExistingThomasAllom/W.H.Bartlettareprototype/designcreatorleads; jointcreatorlabels retainedwithoutinferredsingleprimaryartistlink. Gillot aliasClaudeGillotunsupportedforlate19thprintlabel; Unknown artistrowneverlinked. DrAbrahamElijahdeCastromakerversuscollectorrolequalified. Fourneweditorialtitlehits notsameobjects:147Gillotphotoengraving differsSargent1905oil/McBey1921drypoint;158TAllom/SFisherc1843engravingdiffersDavidRoberts1839Clevelandlithographs1927.124/1927.118. Fourcounterpartsfullsnapshotprotected. Noexhaustiveglobalduplicate or10millionrowloadclaim. Publicsearchqtruncated160charsbecausebackendlimit200,fulltitleverifiedreturnedIDs. Storagepathuses8charSHA suffixplusuniqueartworkUUID/number;fullSHAchecksallpass.

NEXT freshdiscovery next-source-discovery-001: MOMus7001mixedrecords, https://www.searchculture.gr/aggregator/portal/collections/momus?language=en, initialIIDfbb86dfe-de37-5942-b762-0585ae753b31last11catalogue/7eligible. CollectionspansmultipleMOMusmuseums; cannotassignalltoMuseumofContemporaryArt. Reconcileproductioninstitutionrecords/nativecollectionholdingsfirst; prioritizepre1971paintings/prints/drawingsincludingRussianavantgarde. Nativehttps://www.momus.gr/collections, actualpreviewCCBYSA4.0. Noindividualnextobjects/imagesdownloaded. FaltaitsIID4c0f86b1-db26-5bac-b996-af97707fce2c last7catalogue,DigFaltaits4153mixedfolkloreobjects,nativefaltaits.gr/el/sylloges,sourceCC0; artworkversusutilityscope andphysicalunitsneeded. AgrinioIIDd320a1d9-e80c-5205-823d-fefe07394a03last12/3eligible,165searchablevs160description,1938–2017mainlypostwar,CCBYNC4.0,nativedipinag.gr. Onlylandingpages/first30cardscaptured; additionalnativeMOMuscollectionsHTML200containsobservedmuseumfacetsModern3128,Contemporary1890,Photography870,AlexMylona809 andCostakisCollection1494plusarchives. Thesearefacetcountsnoteligibleartworktotals. next-momus-institution-context-001 andnext-momus-legacy-institutions-001 readonlyname/websitequeriesfoundonlyinitialfbbinstitution,notproofallotherlegacyaliasesabsent. Reconcilecarefullybeforecreating/mappinginstitutions. Firstreadonlyinstitutionquerycitycolumnfailed(noDBwrites),correctedknowncolumnquerycompleted;nativecapturecachednotrefetched. Nikaia101mixedlateworks andTossitzaHTTP500remaininheritedgaps.

Allprioraccessholdsandhistoricalpinreconciliation remain perSpatharioCPchain, nofailedroute retries or bypass. Preserve historical_artifact_revisions andhistorical_pin_reconciliation_reference. LarissacommonhelperslostonefinalLF beforeNHM,causeunknown,ASTsame,oldbytesarchivedLibrary;neverrestorelivehelpers/rewriteoldCP. CurrentcommonSHAeee872b3c26eee76f76901a5f12d460c995620289b1e810ea9c7c94ca3dac74e,v2SHA8b891849b4a7b65cc1277af83fc7ce03507752b0f223dbc17bf916a1ee4f77e2. Verifynew/relevantpins,notallhistorical51k.

Researchpython ~/Library/Application Support/Artline/research-venvs/museum-expansion-20261009/bin/python -B. Realpostgresql://localhost/artlineREADONLY,nofixtures/testDB. Proofs/backupsLibrary. CurrentproxyPID26804at127.0.0.1:55519--gcloud-auth,verifiedbinarySHA47c56cc88acd3250ac90b7ad063532cc22a8cca9dd0896012a2a60d1eab4c159,leavealive;reverifyfreshnextturn. Runtimeproxylog/tmp/artline-jewish-cloud-sql-proxy-20261010.loglive/notpinned;oldSpatharioproxylogstoppedandtailarchived. Noagents/commits/deployment. AGENTSSHAad0d8067ebf9a99e3198d1d6d0c9853e6acdd8932c5a5a0a9e5bb006416d0241. Selectedproductionworkauthorized,noapprovalquestions. Allactivecatalogueunified,membermuseumaccessunchanged. Every-museumgoalACTIVE.'''
    result=dict(prior);result.update(at=m.now(),wave=134,goal_complete=False,goal_status='active',previous_goal_turn='progress',production_only=True,local_unchanged=True,new_additions=140,new_existing_links=0,new_images=131,verification=report['verification'],production_museum_before=report['museum_before'],production_museum_after=report['museum_after'],production_campaign_totals=report['production_campaign_totals'],global_production_counts_refreshed=False,global_production_thresholds_refreshed=False,new_tests_passed=21,plan_sha256=digest,plan_reference=c.ref(a.PLAN),prior_checkpoint_reference=c.ref(c.CP),artifacts=list(pins.values()),external_artifacts=list(external.values()),baseline_reference=c.ref(RUN/'baseline-verification-001.json'),review_reference=c.ref(a.REVIEW),checks_reference=c.ref(RUN/'checks-001.json'),public_delivery_reference=c.ref(RUN/'public-delivery-001.json'),production_institution_register_reference=c.ref(RUN/'production-institution-register-001.json.gz'),priority_museum_queue_reference=c.ref(RUN/'priority-museum-queue-001.json'),protected_production_ids_reference=c.ref(RUN/'protected-production-ids-001.json'),pending_candidates={},pending_candidate_total=0,global_threshold_summary_note='OnlyJewishMuseumrefreshed:148catalogue/142numericeligible/139primary,52shortofpreferred200.222inheritedunder100rowsremain,notglobalcensus.',source_availability=report['source_access'],source_access_holds_reference=c.ref(RUN/'source-access-holds-001.json'),inherited_source_holds_reference=c.ref(c.CP),remaining_research_reference=c.ref(RUN/'remaining-research-001.json'),next_source_discovery_reference=c.ref(RUN/'next-source-discovery-001.json.gz'),preferred_target_remaining=dict(institution_id=c.IID,catalogue=148,gap_to100=0,gap_to200=52,target_reached=False,numeric_eligible=142),public_api_date_scope=public['date_scope_note'],next_work=nextwork)
    result.pop('previous_research_checkpoint',None);m.save(dest,result)
    m.save(RUN/'final-checkpoint-verification-001.json',dict(at=m.now(),checkpoint=c.ref(dest),verified_new_artifact_pins=len(newpins),verified_new_external_pins=len(newext),inherited_unchanged_artifact_pins=len(pins)-len(newpins),inherited_unchanged_external_pins=len(external)-len(newext),full_historical_proof=prior['initial_full_historical_verification_reference'],plan_sha256=digest,goal_complete=False,actual_added=140,actual_images=131,protected_production_ids=2938,pending_candidates=0,local_unchanged=True,historical_revisions_carried=len(prior.get('historical_artifact_revisions',[]))))
    print(json.dumps(dict(checkpoint=c.ref(dest),artifacts=len(pins),external=len(external),verified_new=len(newpins),verified_external=len(newext),added=140,images=131,pending=0)),flush=True)

if __name__=='__main__':main()
