"""Production delivery ledger; historical local counts remain separately labelled."""
import collections,csv,importlib.util,json
from pathlib import Path
z=importlib.util.spec_from_file_location('a',Path(__file__).with_name('museum-expansion-beziers-apply-20261009.py'));a=importlib.util.module_from_spec(z);z.loader.exec_module(a);m=a.m;RUN=a.RUN
def main():
 p,digest=a.validate_plan();receipt=m.load(RUN/(a.KEY+'-applied.json'));checks=m.load(RUN/'checks-001.json');assert receipt['plan_sha256']==digest and checks['offline_tests_passed']==12 and checks['atomic_verification_passed'] and checks['replay_zero_writes']
 with a.i.prod.connect() as db,db.transaction():
  db.execute('SET TRANSACTION READ ONLY');assert a.counts(db)=={a.IID:dict(linked=173,eligible=136)};register=db.execute('SELECT i.id::text,i.slug,i.name,i.kind,i.status,i.canonical_institution_id::text,i.website_url,p.name city,p.country_code FROM institutions i LEFT JOIN places p ON p.id=i.place_id ORDER BY i.id').fetchall()
 historical={v['id']:v for v in m.load(m.RUN/'after-wave-100.json')['institutions']};priorcounts=m.load(RUN/'baseline-verification-001.json')['verification']['current_counts'];verified=dict(priorcounts,**receipt['verification']['current_counts'])
 for v in register:
  local=historical.get(v['id'],{});current=verified.get(v['id'],{});v.update(historical_local_linked_works=local.get('works'),historical_local_eligible_works=local.get('eligible_works'),historical_local_count_at='2026-10-09T10:31:37Z',verified_production_works=current.get('linked'),verified_production_eligible_works=current.get('eligible'),production_count_state='verified_this_pass' if current else 'not_refreshed_this_pass')
 m.save(RUN/'production-institution-register-001.json.gz',dict(at=m.now(),rows=register,read_only=True,global_counts_refreshed=False,diagnostics=a.reference(RUN/'production-count-planner-diagnostics-001.json.gz')))
 with (RUN/'production-institution-register-001.csv').open('x',newline='') as fp:w=csv.DictWriter(fp,fieldnames=list(register[0]));w.writeheader();w.writerows(register)
 with (RUN/'added-production-artworks-001.csv').open('x',newline='') as fp:
  w=csv.DictWriter(fp,fieldnames=['artwork_id','institution_id','source_id','title','creator_label','date_display','creation_year_start','creation_year_end','date_precision','date_scope','work_type','inventory','source_url','status']);w.writeheader()
  for v in p['records']:
   f=v['facts'];w.writerow(dict(artwork_id=v['artwork_id'],institution_id=a.IID,source_id=f['source_id'],title=f['title'],creator_label=f['creator_label'],date_display=f['date_display'],creation_year_start=f['first'],creation_year_end=f['last'],date_precision=f['date_precision'],date_scope='eligible' if f['last'] is not None and f['last']<=1970 else 'review',work_type=f['work_type'],inventory=f['inventory'],source_url=f['source_url'],status='review'))
 decisions={d['source_id']:d for d in m.load(a.REVIEW)['decisions']};facts=m.load(RUN/'candidate-facts-001.json.gz');held={v['source_id']:v for v in facts['held']};known={v['source_id']:v for v in facts['existing']};source=m.load(RUN/'joconde-selected-001.json.gz');assert len(decisions)+len(held)+len(known)==len(source['rows'])==485
 with (RUN/'all-source-decisions-001.csv').open('x',newline='') as fp:
  w=csv.DictWriter(fp,fieldnames=['source_id','title','inventory','state','reason','source_url']);w.writeheader()
  for v in source['rows']:
   rid=v['Reference'];d=decisions.get(rid);state=d['state'] if d else 'already_catalogued' if rid in known else 'source_fact_or_scope_hold';reason=d['basis'] if d else 'Existing national source identity in production museum snapshot; unchanged.' if rid in known else held[rid]['reason'];w.writerow(dict(source_id=rid,title=v['Titre'],inventory=v['Numero_inventaire'],state=state,reason=reason,source_url='https://pop.culture.gouv.fr/notice/joconde/'+rid))
 report=dict(at=m.now(),goal_complete=False,production_only=True,local_unchanged=True,plan_sha256=digest,added=88,existing_links=0,date_eligible_added=52,after_date_added=34,unknown_date_added=1,crossing1970_added=1,reviewed_source_records=485,already_catalogued=83,source_fact_or_scope_holds=314,verification=receipt['verification'],museum_before=dict(works=85,eligible_works=84),museum_after=dict(works=173,eligible_works=136),production_campaign_new_artworks=138,production_campaign_museums=2,historical_local_totals_unchanged=dict(new_artworks=11018,existing_links=3036),cross_database_totals_combined=False,production_canonical_museums=sum(v['kind']=='museum' and v['status']!='archived' and not v['canonical_institution_id'] for v in register),global_production_counts_refreshed=False,remaining_finearts_records_not_fetched=435,remaining_finearts_page=source['finearts_next'],remaining_overall_records_not_fetched=source['overall_total']-len(source['rows']),source_access='NationalAPI and municipal pages accessible. Two malformed-resourceURL400 responses preserved; corrected resourceUUID succeeded. No new provider access hold.',preserved_queues_checkpoint=a.reference(a.CHECKPOINT))
 m.save(RUN/'delivery-001.json',report)
 text='''# Béziers Fine Arts — production expansion, 9 October 2026

Added **88 production artworks in review**, taking the Musée des Beaux-Arts de Béziers from **85 to 173 linked works**. Its count with creation dates within scope rose from **84 to 136**. The additions comprise 73 drawings, nine sculptures and six paintings: 52 have eligible dates, 34 retain an open “after” date, one has a questioned date and one retains a twentieth-century range crossing1970. The real local database remains unchanged at85/84.

- [88 delivered artworks](added-production-artworks-001.csv)
- [All485 discovered object decisions](all-source-decisions-001.csv)
- [Production institution register](production-institution-register-001.csv)
- [Verification and counts](delivery-001.json)
- [Reviewed object identities and source evidence](editorial-reviewed-002.json.gz)

The [Ministry of Culture recordM0467](https://pop.culture.gouv.fr/notice/museo/M0467) identifies the museum. The [city’s Fayet page](https://www.ville-beziers.fr/culture/musee-fayet) describes the Fine Arts collection; [Fabrégat](https://www.ville-beziers.fr/culture/centre-detude-et-de-conservation-fabregat/faq-fabregat) is a study and conservation centre. The planned future merged museum does not change current institution identities. These are holdings, without current-display or ownership claims.

Joconde returned2675 museum records. A bounded400-record discovery pass followed by200 filtered Fine Arts records yielded485 distinct records. Of those,83 were already present,88 were added and314 remain in the source/scope ledger. No exhaustive retrieval or image download was performed. Another435 Fine Arts records remain outside this selection; their next source page is recorded in delivery-001.json. Directory coverage is not complete artwork coverage.

The new drawings include original Jean Moulin/Romanin cartoons. Their 1975 acquisition is not their creation date. Original sheets are distinct from magazine reproductions; alternative captions do not create extra artwork records. Eight recorded “vers” inscriptions retain approximate dates despite unqualified catalogue year fields. The two Bonnes Amies drawings have different inventories, dimensions, captions and publication dates.

The new Injalbert sculptures retain separate object identities: two faun heads differ in height and inventory; the two satyr busts differ from the existing1895 bust. One bust with two faces is one object. A fountain assembled from multiple sculptures, a two-bust group, sketchbooks and loose sketchbook pages remain held pending component reconciliation. The source’s inconsistent Sylvestre birth date is preserved as a research gap. A former Louvre/Fabre portrait and nine state deposits also require identity reconciliation. No unsupported date or artwork was introduced to fill a quota.

The Delacroix Sainte Catherine was already present under a Wikidata source with the same896.1.8inventory and was not recreated. Benson’s proposed attribution remains qualified to the artist or his circle. Jan Bruegel’s elder/younger ambiguity remains unresolved. Anonymous and uncertain works retain object-level creator labels.

Twelve offline policy checks passed. The pinned plan used a successful Cloud SQL backup1791546489193, atomic application/readback and a zero-write replay. Checks preserved271 existing comparator/museum records and all50 prior Girodet additions. The identity capture contains3705 existing artworks and7529 citations. No images, artist-authority links or publication changes were added.

Béziers still needs27 more linked works to reach200, or64 more with eligible dates to reach200 eligible works. The production phase now has138 verified additions across Girodet and Béziers. Historical local-only campaign totals remain separate. A complete institution directory is retained, but global production counts remain unverified after earlier timeouts. This pass captured read-only EXPLAIN plans and statistics without retrying the blanket count; planner estimates are not representative10-million-row load testing. Prior source-access holds and research queues continue from the previous checkpoint.
'''
 for before,after in [('at85/84','at 85/84'),('All485','All 485'),('recordM0467','record M0467'),('returned2675','returned 2,675'),('bounded400-record','bounded 400-record'),('by200','by 200'),('yielded485','yielded 485'),('those,83','those, 83'),('present,88','present, 88'),('and314','and 314'),('Another435','Another 435'),('their1975','their 1975'),('existing1895','existing 1895'),('same896.1.8inventory','same 896.1.8 inventory'),('backup1791546489193','backup 1791546489193'),('preserved271','preserved 271'),('all50','all 50'),('contains3705','contains 3,705'),('and7529','and 7,529'),('needs27','needs 27'),('reach200','reach 200'),('or64','or 64'),('has138','has 138'),('representative10-million-row','representative 10-million-row'),('crossing1970','crossing 1970')]:text=text.replace(before,after)
 dest=RUN/'README.md';assert not dest.exists();dest.write_text(text);print(json.dumps(dict(added=88,after=173,eligible=136,production_new_total=138,canonical_museums=report['production_canonical_museums'])),flush=True)
if __name__=='__main__':main()
