"""Wave94 primary-catalogue additions; retain historical museum coverage and queues."""
import copy,csv,importlib.util,json
from pathlib import Path
z=importlib.util.spec_from_file_location('a',Path(__file__).with_name('museum-expansion-leeds-drawings-apply-20261009.py'));a=importlib.util.module_from_spec(z);z.loader.exec_module(a);m=a.m
def read_csv(path):
 with path.open(newline='') as fp:return list(csv.DictReader(fp))
def write_csv(path,rows):
 assert rows and not path.exists()
 with path.open('x',newline='') as fp:
  w=csv.DictWriter(fp,fieldnames=list(rows[0]));w.writeheader();w.writerows(rows)
def main():
 label='after-wave-94';assert not(m.RUN/('verification-'+label+'.json')).exists();p,digest=a.validate_plan();a.verify_baseline()
 with m.connect() as db:verified=a.verify(db,p,digest)
 live=m.load(m.RUN/(label+'.json'));summary=copy.deepcopy(m.load(m.RUN/'verification-after-wave-93.json'));coverage=read_csv(m.RUN/'museum-coverage-after-wave-93.csv');by={v['id']:v for v in live['institutions']};oldids={v['id'] for v in coverage};assert oldids<=set(by);new=[v for v in live['institutions'] if v['id'] not in oldids];changes=[];external=[];newly=0
 for v in new:
  row={k:'' for k in coverage[0]};row.update(v);row.update(works_before=v['works'],eligible_before=v['eligible_works'],added_this_campaign=0,existing_artworks_linked_this_campaign=0,research_state='external_registry_addition_not_reviewed_by_this_campaign',native_source_probe_status='not_reviewed_by_this_campaign',coverage_baseline_label='first_observed_after_wave_94');coverage.append(row)
 for row in coverage:
  v=by[row['id']]
  if row['id']==a.IID:
   old=p['before_counts'][a.IID];assert (int(row['works']),int(row['eligible_works']))==(old['linked'],old['eligible']);assert (v['works'],v['eligible_works'])==(old['linked']+102,old['eligible']+102);assert v['illustrated_works']==int(row['illustrated_works']) and v['pending_associations']==int(row['pending_associations']);newly=int(int(row['added_this_campaign'])+int(row['existing_artworks_linked_this_campaign'])==0);changes.append(dict(institution_id=row['id'],name=row['name'],new=102,existing_linked=0,linked_before=137,linked_after=239,eligible_before=111,eligible_after=213));row.update(added_this_campaign=int(row['added_this_campaign'])+102,research_state=row['research_state']+'; cotmania_native_object_and_attribution_review',native_source_probe_status='museum_commissioned_native_object_catalogue_reviewed')
  elif row['id'] in oldids:
   delta={k:dict(before=int(row[k]),after=v[k]) for k in ['works','eligible_works','illustrated_works','pending_associations'] if int(row[k])!=v[k]}
   if delta:external.append(dict(institution_id=row['id'],name=row['name'],changes=delta))
  row.update(v)
 growth=a.RUN/'coverage-registry-growth-001.json';m.save(growth,dict(at=m.now(),live_audit_reference=a.reference(m.RUN/(label+'.json')),previous_coverage_reference=a.reference(m.RUN/'museum-coverage-after-wave-93.csv'),added_institutions=new,existing_institution_changes=external,policy='Other jobs and registry changes are separate from campaign.'));write_csv(m.RUN/('museum-coverage-'+label+'.csv'),coverage)
 for name in ['reconciled-artworks','gac-date-enrichments']:write_csv(m.RUN/(name+'-'+label+'.csv'),read_csv(m.RUN/(name+'-after-wave-93.csv')))
 added=read_csv(m.RUN/'added-artworks-after-wave-93.csv');museum=by[a.IID]
 for v in p['records']:
  f=v['facts'];added.append(dict(artwork_id=v['artwork_id'],museum=museum['name'],museum_slug=museum['slug'],title=f['title'],creator_label=f['creator_label'],date_display=f['date_display'],creation_year_start=f['first'],creation_year_end=f['last'],accession=f['inventory'],source_url=f['source_url'],status='review'))
 assert len(added)==len({v['artwork_id'] for v in added})==10623;write_csv(m.RUN/('added-artworks-'+label+'.csv'),added);summary.update(at=m.now(),verified_new_artworks=10623,verified_existing_artworks_linked=2806,after=live['summary'],leeds_cotmania_drawings=verified,leeds_cotmania_drawings_museum_changes=changes,unrelated_coverage_changes_since_prior_report=external,newly_observed_institutions=new,external_registry_growth_reference=a.reference(growth),global_coverage_snapshot_at=live['summary']['at']);summary['by_source'][a.KEY]=dict(new_artworks=102,existing_artworks_linked=0,institutions_expanded=1,newly_expanded_institutions=newly,reviewed_objects=104,editorial_holds=2,existing_gallery_holdings_preserved=137,museum_changes=changes,plan_sha256=digest);summary['verification_components']+=[a.reference(m.RUN/'verification-after-wave-93.json'),a.reference(a.CHECKPOINT),a.reference(a.PLAN),a.reference(a.RUN/(a.KEY+'-applied.json'))];summary['institutions_with_new_records_or_reconciled_holdings']=sum(int(v['added_this_campaign'])+int(v['existing_artworks_linked_this_campaign'])>0 for v in coverage)
 for threshold in [100,200]:summary['museums_crossing_'+str(threshold)]=[dict(name=v['name'],before=int(v['works_before']),after=int(v['works'])) for v in coverage if v['kind']=='museum' and v['status']!='archived' and not v['canonical_institution_id'] and int(v['works_before'])<threshold<=int(v['works'])]
 assert sum(int(v['added_this_campaign']) for v in coverage)==sum(v['new_artworks'] for v in summary['by_source'].values())==10623;assert sum(int(v['existing_artworks_linked_this_campaign']) for v in coverage)==2806;summary['identity_reference_downloads_this_wave']=dict(selected_images=0,selected_source_pdfs=0,catalogue_image_attachments=0);summary['verification_method']='Wave94 adds102 selected Cotmania physical objects after104 native reviews. Two whole-object date holds. Twenty creator-label refinements preserve essay uncertainty and associated/after relationships;1823 inscription qualified unverified. Six individually accessioned thumbnail papers on a shared mount count separately,all multiple sketches or paired sides on one paper count once. Current native0552 standing figure resolves wagon0108a concordance. Fresh bounded identity1334 artworks/3211 citations;93 available comparison raw bodies verified and36 unreconstructed recorded without fresh confirmation. Retained Yale LIDO identifies comparator works as etchings distinct from new graphite drawings. Met429 stopped without retry; prior source holds untouched. All13327 prior campaign records and1334 scoped existing records preserved. Gallery239linked/213eligible,above200 in both measures.24offline checks,atomic readback and zero-write replay. No images,display claims,publication or legacy rewrites. All museum queues preserved;full goal active.';m.save(m.RUN/('verification-'+label+'.json'),summary);print(json.dumps(dict(campaign_new=10623,campaign_links=2806,changes=changes,after=live['summary'],institutions_expanded=summary['institutions_with_new_records_or_reconciled_holdings'],external_changes=len(external))),flush=True)
if __name__=='__main__':main()
