"""Record wave90 outcomes, source access holds and continuing museum research."""
import csv,hashlib,importlib.util,json
from pathlib import Path
z=importlib.util.spec_from_file_location('s',Path(__file__).with_name('museum-expansion-royal-common-20261009.py'));s=importlib.util.module_from_spec(z);z.loader.exec_module(s);m=s.m;RUN=s.RUN;ref=s.ref;KEY='royal-existing-holdings-001';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 report=m.load(m.RUN/'verification-after-wave-90.json');assert(report['verified_new_artworks'],report['verified_existing_artworks_linked'])==(10472,2627);assert sha(s.CP)=='40e55394ef6bf9c536e0ca549d1f901bb388e17c3dad3c162014c374a0454456';cp=m.load(s.CP);applied=m.load(RUN/(KEY+'-applied.json'));assert applied['created']==0 and applied['existing_links']==79 and applied['verification']==report['royal_holdings'];root=m.RUN/'README.md';pin=next(v for v in cp['artifacts'] if v['path']==str(root.relative_to(m.ROOT)));assert sha(root)==pin['sha256'];backup=m.BACKUP/'royal-root-readme-before-001.json.gz';assert not backup.exists()
 for name in ['checks-001.json','remaining-research-001.json.gz','next-museum-pass-001.json','README.md','readme-supersessions-001.json','source-availability-001.json','new-source-access-holds-001.json']:assert not(RUN/name).exists()
 logsroot=Path('/Users/vadimdulub/Library/Logs');test=(logsroot/'artline-royal-tests-20261009.log').read_text();assert 'Ran 23 tests' in test and test.rstrip().endswith('OK');assert(logsroot/'artline-royal-replay-20261009.log').read_text().strip()=='Unchanged replay: zero writes';logs={v.name:dict(path=str(v),sha256=sha(v)) for v in sorted(logsroot.glob('artline-royal-*-20261009.log')) if not any(x in v.name for x in ['delivery','checkpoint'])}
 m.save(RUN/'checks-001.json',dict(at=m.now(),new_offline_tests_passed=23,historical_tests_passed=1756,cumulative_verified_tests=1779,historical_tests_rerun=False,replay_zero_writes=True,source_objects_reviewed=91,new_artworks=0,existing_links=79,preserved_existing_royal_holdings=82,editorial_holds=12,logs=logs,other_job_totals_separate=True,source_refinements='Modern namesake authorities, Cleveley father/son attribution and uncertain physical versions held. Exact retained Walters primary text resolves Byron replica. Lightweight snapshot helper proved equivalent to historical snapshot for173 initial records, avoiding recursive historical imports. Fresh transaction identity and all prior campaign objects verified. No failed write transaction.'))
 access=[dict(host='www.rct.uk',state='access_hold',reason='First official collection context request returned HTTP403. Search and object pages unrequested after refusal.',retry_policy='Do not retry RCT or use royalcollection.org.uk aliases as an access workaround. Use independent available evidence and retain secondary-source limitations.',evidence_reference=ref(RUN/'native-probes-001.json'))];m.save(RUN/'new-source-access-holds-001.json',dict(at=m.now(),rows=access,previous_source_hold_reference=cp['new_source_access_hold_reference'],policy='RCT provider stopped after refusal. Every prior source access hold persists.'))
 m.save(RUN/'source-availability-001.json',dict(at=m.now(),new_source_access_holds=access,new_source_access_hold_reference=ref(RUN/'new-source-access-holds-001.json'),previous_source_availability_reference=cp['source_availability_reference'],previous_source_hold_reference=cp['new_source_access_hold_reference'],native_capture_reference=ref(RUN/'native-probes-001.json'),royal_household_context_reference=ref(RUN/'royal-household-context-001.json'),comparison_context_reference=ref(RUN/'comparison-source-context-001.json.gz'),creator_authority_references=[ref(RUN/n) for n in ['unlinked-creator-authorities-001.json.gz','authority-conflicts-001.json.gz']],browser_state='Not retried this wave; prior browser environment failure remains recorded.',policy='Ordinary public HTTP metadata only. Native RCT403 stopped provider without bypass or aliases. Independent Royal Household overview and selected Wikidata authority records captured.38 retained raw context bodies verified, including one Walters primary page distinguishing a replica. Saved Wikidata object statements reference Royal Collection sources; correlated secondary references are not fresh independent native confirmation. No images downloaded or attached. Institution overview does not establish an individual object holding, ownership,custody,palace or display.'))
 decisions=m.load(RUN/'editorial-reviewed-001.json.gz')['decisions'];held=[v for v in decisions if v['state']=='editorial_hold'];assert len(held)==12;m.save(RUN/'remaining-research-001.json.gz',dict(at=m.now(),rows=held,review_reference=ref(RUN/'editorial-reviewed-001.json.gz'),previous_remaining_research_reference=cp['remaining_research_reference'],royal_linked=161,royal_eligible=151,remaining_to_200_linked=39,remaining_to_200_eligible=49,policy='Twelve exact source,creator or physical-version holds remain unchanged. Do not merge Boy/Boz by title similarity, or separate Sliema/Marsamxett solely by place name. Correct historical maker identities require object evidence. Unknown dates excluded from eligible totals. All previous research queues remain active.'))
 oldq=m.load(m.ROOT/cp['next_museum_pass_reference']['path']);live=m.load(m.RUN/'after-wave-90.json');by={v['id']:v for v in live['institutions']};italian=[dict(v,current_linked=by[v['institution_id']]['works'],current_eligible=by[v['institution_id']]['eligible_works']) for v in oldq['italian_museums']];assert len(italian)==225;excluded=['Glasgow Museums Resource Centre','Kelvingrove Art Gallery and Museum','Burrell Collection','Bristol City Museum & Art Gallery'];nexttargets=sorted([v for v in live['institutions'] if v['kind']=='museum' and v['status']!='archived' and not v['canonical_institution_id'] and v['works']<100 and v['pending_associations']>0 and v['name'] not in excluded],key=lambda v:(-v['pending_associations'],v['id']))[:20];current_ids=sorted({v['id'] for v in oldq['current_museums']}|{s.IID})
 m.save(RUN/'next-museum-pass-001.json',dict(at=m.now(),previous_queue_reference=cp['next_museum_pass_reference'],italian_museums=italian,existing_holding_review_targets=nexttargets,native_addition_targets=[by[v['id']] for v in oldq['native_addition_targets']],current_museums=[by[iid] for iid in current_ids],southampton_pdf_leads_reference=oldq['southampton_pdf_leads_reference'],edinburgh_portrait_leads=oldq['edinburgh_portrait_leads'],remaining_research_reference=ref(RUN/'remaining-research-001.json.gz'),source_availability_reference=ref(RUN/'source-availability-001.json'),policy='Royal161linked/151eligible meets100 but still needs49eligible works for preferred200.12held candidates preserved. Continue independent museum research,prioritizing below100 collections with object leads; do not retry RCT or earlier held providers. Glasgow branch gaps and227 unresolved Resource Centre claims,Southampton15datedPDFleads,Edinburgh88/29,Guildhall115/86,225Italian museums and every earlier queue persist. Full goal active.',database_writes=0))
 total=report['institutions_with_new_records_or_reconciled_holdings'];text=f'''# Royal Collection holding review — 9 October 2026

Linked **79 existing artworks** after reviewing 91 source objects. The Royal Collection increased from **82 to 161 linked records**, and from **75 to 151 works with eligible pre-1971 dates**. Three newly linked works remain undated. Twelve candidates remain held; no new artwork rows were created in this pass.

Evidence consists of exact saved Wikidata artwork identities, creators, collection-qualified inventories and Royal Collection references, with fresh selected authority checks. Confidence is an editorial assessment of 85%, or 90% for the explicitly distinguished Byron original. References are correlated secondary evidence. The RCT website returned 403 on its first collection-context request; subsequent native search and object requests stopped. The [Royal Household overview](https://www.royal.uk/the-royal-collection) supplies context for the distributed collection, not individual artwork confirmation, legal ownership, palace location or current display.

Retained [Walters object 37.217](https://art.thewalters.org/object/37.217/) text explicitly distinguishes its replica from Sanders’s Royal Collection Byron-and-companion original. Physical scale, creator and source relations distinguish Melville’s miniature after Winterhalter and Nowell’s Royal portrait from its Bury derivative. Thorburn’s two pendants and the Jones and Douglas portraits of Persimmon remain separate objects. The [review](editorial-reviewed-001.json.gz) retains those exact identity decisions.

The [12 holds](remaining-research-001.json.gz) include historical works linked to modern Richard Wright, Robert Jones, Peter Graham and George Smith identities; conflicting Spencer chronology; Cleveley father/son attribution; missing exact source identifiers; and unresolved physical versions. Sliema and Marsamxett titles alone cannot establish different paintings. A deprecated RCIN marked for link rot alone cannot disprove an object identity. All original creator labels, dates and pending evidence remain intact.

The [reviewed plan](royal-existing-holdings-001-plan-001.json.gz) and [transaction receipt](royal-existing-holdings-001-applied.json) verify 79 citations and accepted holding assertions, superseding only 79 matching pending assertions. Fresh identity checking covered **12,465 artworks and 26,669 citations**. Preservation checks cover **799 scoped legacy records and all 13,020 previous campaign records**. **23 offline tests, atomic readback and zero-write replay passed.** No artwork metadata, artist links, images or publication states changed.

Campaign totals: **10,472 new artworks + 2,627 existing-artwork reconciliations = 13,099 distinct records across {total} institutions**. **{report['after']['museums_below_100']:,} canonical museums remain below 100 linked records**, and **{report['after']['museums_below_200']:,} below 200**. Royal Collection still needs 39 linked records or 49 eligible dated works to reach 200. [Continuing research](next-museum-pass-001.json) retains every earlier queue and source hold. The all-museum goal remains active.
'''
 m.save(backup,dict(at=m.now(),path=str(root),text=root.read_text(),sha256=sha(root)));(RUN/'README.md').write_text(text);old=root.read_text();intro,rest=old.split('## Added works',1);intro=intro.replace('2,548','2,627').replace('expand 233 institutions',f'expand {total} institutions').replace('1,233','1,232').replace('after-wave-89','after-wave-90').replace('Edinburgh and Glasgow passes','Edinburgh, Glasgow and Royal Collection passes')
 stale='| Distinct new-record campaign total | **10,395** | **213 collections** |';assert stale in rest
 with(m.RUN/'museum-coverage-after-wave-90.csv').open(newline='') as fp:coverage=list(csv.DictReader(fp))
 newinstitutions=sum(int(v['added_this_campaign'])>0 for v in coverage);assert newinstitutions==215;rest=rest.replace(stale,'| Guildhall Art Gallery — selected source-backed artworks | 22 | 1 continuation |\n| Southampton City Art Gallery — selected native artworks | 55 | 1 continuation |\n| Distinct new-record campaign total | **10,472** | **215 collections** |')
 root.write_text(intro+'## Added works'+rest+'\n\n## Royal Collection holdings — wave90\n\nLinked 79 existing works after reviewing 91 exact source objects. Royal Collection now has 161 linked records and 151 with eligible dates, meeting the 100 minimum. Three newly linked dates remain unknown; twelve source,creator or physical-version conflicts remain held. [Evidence and continuing work](native/royal-holdings-20261009/README.md). Campaign: 10,472 new + 2,627 reconciled = 13,099 distinct records across '+str(total)+' institutions. RCT access stopped after HTTP403; retained secondary evidence is explicitly labelled and all earlier source holds persist. The current added-work table also now includes the already verified Guildhall22 and Southampton55 additions. Full all-museum goal remains active.\n');m.save(RUN/'readme-supersessions-001.json',dict(at=m.now(),changes=[dict(path=str(root.relative_to(m.ROOT)),before_sha256=pin['sha256'],after_sha256=sha(root),backup_path=str(backup),backup_sha256=sha(backup))]));print(json.dumps(dict(documented_new_records=0,documented_existing_links=79,held=12,preserved=82,tests=23,institutions_expanded=total,goal_complete=False)),flush=True)
if __name__=='__main__':main()
