"""Document wave92 and retain every earlier museum queue and access hold."""
import collections,hashlib,importlib.util,json
from pathlib import Path
z=importlib.util.spec_from_file_location('s',Path(__file__).with_name('museum-expansion-leeds-common-20261009.py'));s=importlib.util.module_from_spec(z);z.loader.exec_module(s);m=s.m;RUN=s.RUN;ref=s.ref;KEY='leeds-existing-holdings-001';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()

def main():
 report=m.load(m.RUN/'verification-after-wave-92.json');assert(report['verified_new_artworks'],report['verified_existing_artworks_linked'])==(10472,2806);assert sha(s.CP)=='8d0721548ba1f3b8b9164e7417f6d504fe3401987ffd9ee5e5f20bd879174b55';cp=m.load(s.CP);applied=m.load(RUN/(KEY+'-applied.json'));assert applied['created']==0 and applied['existing_links']==80 and applied['verification']==report['leeds_holdings'];root=m.RUN/'README.md';pin=next(v for v in cp['artifacts'] if v['path']==str(root.relative_to(m.ROOT)));assert sha(root)==pin['sha256'];backup=m.BACKUP/'leeds-root-readme-before-001.json.gz';assert not backup.exists()
 for name in ['checks-001.json','remaining-research-001.json.gz','next-museum-pass-001.json','README.md','readme-supersessions-001.json','source-availability-001.json','new-source-access-holds-001.json']:assert not(RUN/name).exists()
 logsroot=Path('/Users/vadimdulub/Library/Logs');test=(logsroot/'artline-leeds-tests-20261009.log').read_text();assert 'Ran 20 tests' in test and test.rstrip().endswith('OK');assert(logsroot/'artline-leeds-replay-20261009.log').read_text().strip()=='Unchanged replay: zero writes';logs={v.name:dict(path=str(v),sha256=sha(v)) for v in sorted(logsroot.glob('artline-leeds-*-20261009.log')) if not any(x in v.name for x in ['delivery','checkpoint'])}
 m.save(RUN/'checks-001.json',dict(at=m.now(),new_offline_tests_passed=20,historical_tests_passed=1804,cumulative_verified_tests=1824,historical_tests_rerun=False,replay_zero_writes=True,source_objects_reviewed=84,new_artworks=0,existing_links=80,preserved_existing_gallery_holdings=8,editorial_holds=4,logs=logs,other_job_totals_separate=True,source_refinements='Eight collection statements cite exact ArtUK URLs rather than the ArtUK identifier reference pattern. These were explicitly reviewed. Three source-authority flags concern preserved object-level labels; two Joy holdings verified and Rhodes remains held for physical identity.22 additional selected GAC objects captured,including a private loan and an internally inconsistent medium. No failed write transaction.'))
 m.save(RUN/'new-source-access-holds-001.json',dict(at=m.now(),rows=[],previous_source_hold_reference=cp['new_source_access_hold_reference'],policy='No new refusals this wave. All prior IWM,RCT,ArtUK,Navigator and other access holds persist without retry or workaround.'))
 m.save(RUN/'source-availability-001.json',dict(at=m.now(),new_source_access_holds=[],new_source_access_hold_reference=ref(RUN/'new-source-access-holds-001.json'),previous_source_availability_reference=cp['source_availability_reference'],previous_source_hold_reference=cp['new_source_access_hold_reference'],native_probe_reference=ref(RUN/'native-probes-001.json'),comparison_context_reference=ref(RUN/'comparison-source-context-001.json.gz'),fresh_authority_reference=ref(RUN/'selected-authorities-001.json.gz'),additional_metadata_reference=ref(RUN/'additional-object-metadata-001.json.gz'),policy='Fresh official Leeds service and HenryMoore context,selected Wikidata creator authorities and two museum-authored GAC stories available.136 unique review raw bodies verified;22 further selected object pages separately checksum-verified as leads. Referenced Wikidata/ArtUK evidence remains secondary and correlated. No browser retry,images or provider workaround. No individual holding inferred from city-wide service or exhibition alone.'))
 decisions=m.load(RUN/'editorial-reviewed-001.json.gz')['decisions'];held=[v for v in decisions if v['state']=='editorial_hold'];assert len(held)==4;leads=m.load(RUN/'additional-lead-review-001.json.gz');assert collections.Counter(v['state'] for v in leads['rows'])=={'selected_further_review':16,'existing_match':2,'source_conflict':1,'incoming_private_loan':1,'holding_source_gap':1,'venue_creator_version_review':1}
 m.save(RUN/'remaining-research-001.json.gz',dict(at=m.now(),rows=held,review_reference=ref(RUN/'editorial-reviewed-001.json.gz'),additional_lead_review_reference=ref(RUN/'additional-lead-review-001.json.gz'),previous_remaining_research_reference=cp['remaining_research_reference'],gallery_linked=88,gallery_eligible=62,remaining_to_100_linked=12,remaining_to_100_eligible=38,remaining_to_200_eligible=138,policy='Four physical-identity holds.22 newly linked dates remain unknown.16 selected further-review leads plus4specific gaps/exclusions and2known existing matches; no lead counted as an artwork addition. Existing eight holdings preserved,not newly revalidated for venue or display. Every older queue persists.'))
 oldq=m.load(m.ROOT/cp['next_museum_pass_reference']['path']);live=m.load(m.RUN/'after-wave-92.json');by={v['id']:v for v in live['institutions']};italian=[dict(v,current_linked=by[v['institution_id']]['works'],current_eligible=by[v['institution_id']]['eligible_works']) for v in oldq['italian_museums']];assert len(italian)==225;excluded=['Glasgow Museums Resource Centre','Kelvingrove Art Gallery and Museum','Burrell Collection','Bristol City Museum & Art Gallery','Imperial War Museum London'];nexttargets=sorted([v for v in live['institutions'] if v['kind']=='museum' and v['status']!='archived' and not v['canonical_institution_id'] and v['works']<100 and v['pending_associations']>0 and v['name'] not in excluded],key=lambda v:(-v['pending_associations'],v['id']))[:20];current_ids=sorted({v['id'] for v in oldq['current_museums']}|set(s.IIDS));native_ids=[v['id'] for v in oldq['native_addition_targets']];native_ids=list(dict.fromkeys([s.IID]+native_ids))
 m.save(RUN/'next-museum-pass-001.json',dict(at=m.now(),previous_queue_reference=cp['next_museum_pass_reference'],italian_museums=italian,existing_holding_review_targets=nexttargets,native_addition_targets=[by[iid] for iid in native_ids],current_museums=[by[iid] for iid in current_ids],southampton_pdf_leads_reference=oldq['southampton_pdf_leads_reference'],edinburgh_portrait_leads=oldq['edinburgh_portrait_leads'],leeds_selected_metadata_reference=ref(RUN/'additional-object-metadata-001.json.gz'),leeds_selected_lead_review_reference=ref(RUN/'additional-lead-review-001.json.gz'),remaining_research_reference=ref(RUN/'remaining-research-001.json.gz'),source_availability_reference=ref(RUN/'source-availability-001.json'),policy='Leeds88linked/62eligible still needs38eligible works for100. Continue selected museum-published GAC leads with exact venue,ownership,creator and duplicate review,then native watercolour/sculpture sources. Four physical identities held. TheBox,York,Harris remain next pending-association targets. IWM133/130,London13/13and88unresolved branchclaims,Royal161/151with12holds,Glasgow branchgaps and227ResourceCentreclaims,Southampton15datedPDFleads,Edinburgh88/29,Guildhall115/86,225Italian museums and every earlier queue/accesshold persist. Full goal active.',database_writes=0))
 total=report['institutions_with_new_records_or_reconciled_holdings'];text=f'''# Leeds Art Gallery holding review — 9 October 2026

Linked **80 existing artworks** after reviewing 84 exact source objects. Leeds Art Gallery increased from **8 to 88 linked records**, including **62 with eligible pre-1971 dates**. Twenty-two newly linked works remain undated. Four candidates remain held. No new artwork rows were created in this pass.

Exact saved Wikidata objects identify the title, maker and gallery-qualified inventory, with ArtUK references by identifier or URL. Fresh creator authorities support the preserved George W. Joy object labels. These are correlated secondary object sources, not fresh primary object confirmations. The official Leeds fine-art overview distinguishes the gallery from Temple Newsam and Lotherton; city-wide membership alone does not allocate a work to this gallery. Prior access holds remain in force.

The [four holds](remaining-research-001.json.gz) concern Frank Avray Wilson's identically sized Object for Meditation I and II, a possible Joseph Rhodes Moot Hall duplicate between Leeds venues, and a generic John Selby-Bigge Composition with an unresolved supplied-CSV record. Distinct Butterfield compositions, Hunter vase paintings and Rhodes sheep paintings were checked using source dimensions, titles and dates. Study and creator qualifications remain unchanged.

The [reviewed plan](leeds-existing-holdings-001-plan-001.json.gz) and [transaction receipt](leeds-existing-holdings-001-applied.json) verify **80 new citations and accepted holdings**, superseding only 80 matching pending gallery assertions. Fresh identity checks covered **7,444 artworks and 15,909 citations**; all prior **13,198 campaign records** and scoped legacy fields were preserved. **20 offline tests, atomic readback and zero-write replay passed.** No artist links, images, date edits, publication or display claims were added.

Two museum-authored Natural Encounters stories led to **22 selected pre-1971-labelled object pages**. [The lead review](additional-lead-review-001.json.gz) separates 16 candidates needing venue and duplicate review, two existing catalogue matches and four specific gaps: an incoming private loan, missing holding provenance, uncertain venue/creator, and an internally inconsistent medium. Italian Landscape's source says1758/1759 but lists digital projections, paraffin wax and metal; this is held rather than copied into the catalogue. Women and Bird is a private loan, and its viewing angles are one sculpture. None of these leads is counted as a new addition.

Campaign totals: **10,472 new artworks + 2,806 reconciled existing artworks = 13,278 distinct records across {total} institutions**. **{report['after']['museums_below_100']:,} canonical museums remain below 100 linked records**, and **{report['after']['museums_below_200']:,} below 200**. Leeds needs 12 more linked records and 38 more eligible dated works for 100. [Continuing research](next-museum-pass-001.json) retains every earlier queue and source hold. The all-museum goal remains active.
'''
 m.save(backup,dict(at=m.now(),path=str(root),text=root.read_text(),sha256=sha(root)));(RUN/'README.md').write_text(text);old=root.read_text();intro,rest=old.split('## Added works',1);intro=intro.replace('2,726','2,806').replace('expand 235 institutions',f'expand {total} institutions').replace('after-wave-91','after-wave-92').replace('Royal Collection and Imperial War Museums passes','Royal Collection, Imperial War Museums and Leeds Art Gallery passes');root.write_text(intro+'## Added works'+rest+'\n\n## Leeds Art Gallery holdings — wave92\n\nLinked80 existing works after reviewing84objects. Gallery totals88linked/62eligible;22newlylinked dates remain unknown. Four physical identities remain held. Captured22selected museum-published GAC object pages:16further reviews,2known matches and4specific gaps/exclusions. [Evidence and continuing work](native/leeds-holdings-20261009/README.md). Campaign:10,472new +2,806reconciled =13,278distinct across '+str(total)+' institutions.20offline checks,atomic readback and zero-write replay passed. Every earlier source hold and queue persists. Full all-museum goal active.\n');m.save(RUN/'readme-supersessions-001.json',dict(at=m.now(),changes=[dict(path=str(root.relative_to(m.ROOT)),before_sha256=pin['sha256'],after_sha256=sha(root),backup_path=str(backup),backup_sha256=sha(backup))]));print(json.dumps(dict(documented_new_records=0,documented_existing_links=80,held=4,preserved_gallery=8,tests=20,institutions_expanded=total,goal_complete=False)),flush=True)
if __name__=='__main__':main()
