#!/usr/bin/env python3
"""Five individual Russian/Greek collection decisions; missing work remains held."""
import importlib.util,json
from pathlib import Path
s=importlib.util.spec_from_file_location('e',Path(__file__).with_name('museum-expansion-detroit-identity-v2-20261007.py'));e=importlib.util.module_from_spec(s);s.loader.exec_module(e);i=e.v;f=i.f;m=f.m;ref=f.ref;RUN=m.RUN/'native/detroit-priority';IID=f.IID
NOTES={
 '163':'Russian tempera panel,17th century,31.8x27cm,inventory65.300,bequest ofJohnS.Newberry with1965-present DIA provenance. Artist is unknown; Russian is the literal source cultural label. Six subject leads were inspected: two later19th-century Pokrov icons have different dimensions and inventories; the other leads are Callot prints,a church view and a French royal almanac. No native ID,URL,title or accession collision.',
 '54996':'School of Moscow painted panel,16th century,44.5x31.1cm,inventory39.607,1939 gift fromZacharieBirtschansky. The school label and separately displayed1500-1600 life-date field remain literal evidence; artwork creation is explicitly16th century. The eighteen VirginAnnunciate subject leads are different Italian,Flemish/German works,prints/studies,or a1900ivory miniature. The oneMoscow-school creator lead is SaintJohnonPatmos inNelson-Atkins,R96-5/1,a different subject. No source ID,URL or accession collision; this panel is counted once.',
 '62943':'Stroganov School painted panel,17th century,35.9x30.8cm,inventory23.2,City ofDetroit purchase1923 fromPrince deGagarin. Fresh identity scope explicitly includesStroganov despite the trailingSchool label and found no creator records. The exact-titleJacquesVillon work is1945,not this17th-century Russian panel. Other creation-of-world leads areTempesta,Giovanni diPaolo and a19th-centurycopy. Inventory23.2also occurs onAnneGoldthwaite’sNewYork doorway print; compact232 is anEdgarBundy work. Inventories are museum-specific, and these are distinct physical objects.',
 '55894':'School ofNovgorod painted panel,15th century,64.8x48.9cm,inventory38.69,purchased1938 fromZacharieBirtschansky using theLauraH.Murphy andWilliamH.Murphy funds. Reviewed59SaintGeorge subject leads. RussianIconMuseum versions have different inventories,dates and panel dimensions,including the15th-century50.6x40.2cm loanL2025.05.06. Toledo1943.30has superficially similar frame dimensions but its retained primary-source citation identifies aFrench oil panel with separateLibbey acquisition,not theNovgorod work. GreekKlontzas,Western named-artist paintings and prints are separate compositions. Compactinventory3869isJamesTissot’sLeDuel. No native ID orURL collision.',
 '46395':'Greek painted panel,18th century,21.6x16.2cm,inventory89.8,JamesE.Scripps gift1889 with1889-presentDIA provenance. Artist is unknown; preserveGreek cultural label without a painter link. NineMercurius/Merkourios subject leads were checked: AthensBXM01444is a63x60cm wall painting,while other entries depict Mercury or named people/texts. Compactinventory898belongs toNeilMurison’sRestlessZebra andPaulDelaroche’sParishemicycle. Neither matches this small Greek saint panel; no native ID,URL or exact-title collision.'}
def build():
 candidate=f.RUN/'native-candidates-002.json.gz';identity=f.RUN/'native-identity-002.json.gz';extension=f.RUN/'identity-extension-002.json';citations=f.RUN/'identity-citations-001.json.gz'
 x=m.load(candidate);f.checked(x['parser_reference']);state=m.load(identity);assert state['candidate_reference']==ref(candidate);f.checked(state['query_reference']);ext=m.load(extension);assert ext['identity_reference']==ref(identity);f.checked(ext['extension_reference']);f.checked(ext['prior_query_reference']);cs=m.load(citations);assert cs['selected_ids']==state['state']['artwork_ids'];assert i.comparisons(x['rows'],state['state'])==state['comparisons'];assert i.params_for(x['rows'])==state['params']
 out=[]
 for row in x['rows']:
  assert f.parse(f.checked(row['source_reference']))==row
  if row['source_id'] not in NOTES:continue
  cm=next(c for c in state['comparisons'] if c['source_id']==row['source_id']);assert not any(cm[k] for k in ['native_scheme_hits','native_url_hits','source_hits','untitled_creator_hits'])
  assert set(row['review_flags'])<={'version_or_qualified_creator_review'};v=row['facts'];assert v['date_issue'] is None and v['inventory'] and v['credit_line'];assert v['first']<=v['last']<=1970
  out.append(dict(row,state='approved_review_only_addition',confidence=.9,basis=NOTES[row['source_id']],limitation='90%editorial confidence for documented collection connection,not calibrated probability. Source cultural and school labels remain object labels. Holding does not establish present physical custody,current display or legal title. Unknown copyright and original dates remain unchanged.',comparison=cm,supplement_references=[ref(p) for p in [candidate,identity,extension,citations]]))
 assert len(out)==5;return out
def main():
 rows=build();m.save(RUN/'editorial-reviewed-001.json.gz',dict(at=m.now(),decisions=rows,reviewer_reference=ref(Path(__file__).resolve()),held=[dict(source_id='54994',reason='DIA provenance explicitly states location unknown since1951. Excluded from current collection additions.'),dict(source_id='54995',reason='Object5timed out; no complete object evidence.'),dict(source_id='44747',reason='Detail qualifies indexFabriano asSchoolofFabriano. Similar named-artist Madonnas need further version checks before a new record.')],policy='Five individually reviewed Russian/Greek panels only. Later selected objects remain outside this batch; no images,new artist records,publication,display claims or existing metadata changes.'))
 print(json.dumps([dict(source_id=r['source_id'],title=r['facts']['title']) for r in rows]),flush=True)
if __name__=='__main__':main()
