"""Document verified wave83, unresolved identities and the continuing museum queue."""
import collections,hashlib,importlib.util,json
from pathlib import Path
z=importlib.util.spec_from_file_location('a',Path(__file__).with_name('museum-expansion-britain-six-apply-20261009.py'));a=importlib.util.module_from_spec(z);z.loader.exec_module(a);m=a.m
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 report=m.load(m.RUN/'verification-after-wave-83.json');assert(report['verified_new_artworks'],report['verified_existing_artworks_linked'],report['institutions_with_new_records_or_reconciled_holdings'])==(10259,2119,226);plan,digest=a.validate_plan()
 with m.connect() as db:verified=a.verify(db,plan,digest)
 assert verified['network_to_branch_refinements']==0 and verified['previously_unlinked']==227 and verified['unknown_date_records_preserved']==137
 cp=m.load(a.CHECKPOINT);root=m.RUN/'README.md';pin=next(v for v in cp['artifacts'] if v['path']==str(root.relative_to(m.ROOT)));assert sha(root)==pin['sha256'];backup=m.BACKUP/'britain-six-root-readme-before-001.json.gz';assert not backup.exists()
 assert all(not(a.RUN/n).exists() for n in ['checks-001.json','remaining-research-001.json.gz','next-museum-pass-001.json','README.md','readme-supersessions-001.json','source-availability-001.json'])
 logsroot=Path('/Users/vadimdulub/Library/Logs');test=(logsroot/'artline-britain-six-tests-20261009.log').read_text();assert 'Ran 29 tests' in test and test.rstrip().endswith('OK');assert(logsroot/'artline-britain-six-replay-20261009.log').read_text().strip()=='Unchanged replay: zero writes'
 logs={v.name:dict(path=str(v),sha256=sha(v)) for v in sorted(logsroot.glob('artline-britain-six-*-20261009.log')) if 'delivery' not in v.name and 'checkpoint' not in v.name}
 native=a.r.native_rows();states=collections.Counter(v['state'] for v in native.values());assert states==dict(captured_exact_inventory=91,no_unique_exact_inventory_result=10)
 m.save(a.RUN/'checks-001.json',dict(at=m.now(),new_offline_tests_passed=29,historical_tests_passed=1586,cumulative_verified_tests=1615,historical_tests_rerun=False,replay_zero_writes=True,source_objects_reviewed=248,new_artworks=0,existing_links=227,previously_unlinked=227,network_to_branch_refinements=0,editorial_holds=21,unknown_dates_preserved=137,logs=logs,other_job_totals_separate=True,ferens_inventory_searches=101,ferens_exact_objects=91,rwa_creator_searches=79,rwa_biographies=16,rwa_exact_objects_corroborated=0,parser_repair='Initial39 selected Ferens searches stopped on three overview-parser assertions. Revised parser follows observed Detailed Record links and reuses verified cached HTTP200 bodies;101 completed without request failures.'))
 m.save(a.RUN/'source-availability-001.json',dict(at=m.now(),new_source_access_holds=[],previous_source_hold_reference=cp['new_source_access_hold_reference'],ferens=dict(published_catalogue='http://museumcollections.hullcc.gov.uk/',current_museum_page='https://www.hullmuseums.co.uk/collections-ferens',http_accessible=True,https_connection_failed=True,access_denial_bypassed=False,probe_references=[a.reference(a.RUN/n) for n in ['ferens-collection-probe-001.json','source-discovery-002.json','hull-form-probe-001.json','hull-form-probe-002.json','selected-interface-followup-001.json','selected-interface-followup-002.json']]),policy='Current museum page directs visitors to its legacy HTTP catalogue while a replacement is developed. Public form requires newsearch=new; earlier omitted-radio probes returned broad results,which were not crawled. All prior ArtUK,ArCo,regional TLS,MuseiReali,Bristol and Perth access holds remain; no denied source was retried or bypassed.'))
 held=[v for v in m.load(a.REVIEW)['decisions'] if v['state']=='editorial_hold'];assert len(held)==21
 m.save(a.RUN/'remaining-research-001.json.gz',dict(at=m.now(),rows=held,review_reference=a.reference(a.REVIEW),previous_remaining_research_reference=a.reference(a.prior.RUN/'remaining-research-001.json.gz'),source_availability_reference=a.reference(a.RUN/'source-availability-001.json'),policy='Preserve21 unresolved creator/attribution,chronology,component and physical-version cases. RWA124 and Ferens13 newly linked works remain undated. Native early creation dates on10 of the13 undated Ferens works are retained as evidence for a separate date review,not silently copied. No placeholder or quota-driven inclusion. Earlier queues and source holds remain active.'))
 oldq=m.load(a.checked(cp['next_museum_pass_reference']));live=m.load(m.RUN/'after-wave-83.json');by={v['id']:v for v in live['institutions']};italian=[dict(v,current_linked=by[v['institution_id']]['works'],current_eligible=by[v['institution_id']]['eligible_works']) for v in oldq['italian_museums']];assert len(italian)==225
 targets=[by[k] for k in ['c519fc6e-b9b4-5037-a4b4-6d4f4a479157','03058adb-4b2a-5a45-849d-2393f4229f9b']];assert all(v['works']<100 and v['pending_associations']>=100 for v in targets)
 m.save(a.RUN/'next-museum-pass-001.json',dict(at=m.now(),previous_queue_reference=cp['next_museum_pass_reference'],italian_museums=italian,existing_holding_review_targets=targets,native_addition_targets=[by[a.IIDS[1]]],remaining_research_reference=a.reference(a.RUN/'remaining-research-001.json.gz'),current_museums=[by[k] for k in a.IIDS],source_availability_reference=a.reference(a.RUN/'source-availability-001.json'),policy='Continue selected Ferens native additions toward100/200; it has92 linked and79 eligible. RWA139 linked/15 eligible still needs dated pre1971 research and61 more linked records for200. Next existing-holding targets Salford101 pending and Guildhall100 pending. Preserve225 Italian museums and every earlier queue/source hold. No automatic inclusion from undated contemporary-artist records.',database_writes=0))
 text=f'''# Royal West of England Academy and Ferens — 9 October 2026

Applied **227 reviewed holding links for existing local artworks**. No new artwork records were created in this pass.

| Museum | Accepted links | Linked before → after | Eligible dates before → after |
| --- | ---: | ---: | ---: |
| Royal West of England Academy | 138 | 1 → 139 | 1 → 15 |
| Ferens Art Gallery | 89 | 3 → 92 | 3 → 79 |

**137 accepted works retain unknown creation dates**: 124 at the Academy and 13 at Ferens. These count as linked review records, but do not establish pre-1971 eligibility. The Academy has passed 100 linked records; its eligible-date total remains only 15. Ferens still needs eight linked records to reach 100. Both remain unfinished toward 200, with date and physical-object scope tracked separately.

The review covers all 248 selected pending associations from 119 saved Wikidata bodies, exact source IDs, museum-qualified inventories and creator identities. Fresh identity comparison covers 18,927 artworks and 39,711 citations. Six unlinked labels were checked against four exact creator authorities without adding painter links. Twenty-four saved comparison contexts for 13 artworks, plus hash-verified Tate and V&A primary records, support version and creator comparisons. Referenced Wikidata and Art UK claims are correlated secondary evidence; Art UK was not fetched through its existing access hold.

The [current Ferens collection page](https://www.hullmuseums.co.uk/collections-ferens) links to its [legacy public catalogue](http://museumcollections.hullcc.gov.uk/) while a replacement is developed. **101 selected inventory searches produced 91 exact native object records**; ten produced no unique match. The form requires its `newsearch=new` radio option. Some object links first return an overview; the revised parser follows their observed Detailed Record links. The initial failed parser run and cached HTTP200 bodies are preserved. The published HTTP endpoint was accessible; HTTPS connection failure was not an access denial. No broad catalogue crawl or image download occurred.

The Academy's [collection overview](https://www.rwa.org.uk/pages/our-collection/1000) and [collection Q&A](https://www.rwa.org.uk/pages/our-collection-q-a) were checked. Seventy-nine selected creator searches returned 16 official biographies. Those pages supply context, **not exact-object confirmation**, and no such confirmation is claimed. Academy holdings use the exact referenced secondary object records at 80% editorial confidence. Confidence is an editorial judgment, not a calibrated probability. The historical transfer of Sharples works to Bristol is not generalized to other Academy works.

The [21 held cases](remaining-research-001.json.gz) include paired recto/verso records sharing one support, diptych/triptych components, unresolved versions, an I. Tudgay/John Lashbrook Tudgay identity question, the Charles Collins/Charles Allston Collins conflict, and attributed Carpenter and Churchyard works. Four Sartorius records repeat a creation year earlier than the supplied artist birth year; both claims remain evidence pending reconciliation. Claude Heath's exact native record dates Head Tilting Forwards II to **2002**, so it remains outside this pre-1971 expansion. The unknown catalogue date was not overwritten.

Hustwick's three Loss of a Merchantman records are individually inventoried panels described by the museum as a series of **three separate paintings**, each with a different narrative scene. They are not an aggregate counted three times. Conversely, Jamieson's Snow in My Garden and Bridge over a River, and Lines's two sides under Academy423, remain held pending representation reconciliation. Eaves's Strata Shadows verso has only one existing representation in the scoped identity pool; no additional recto record was invented.

Native spelling, support and chronology conflicts remain in citations. Examples include Hughes's fruit date field1865 versus description1863, Spence circa1875 versus circa1871, Swift circa1850 versus1860, Appleby1886 versus1888, and Binks1822 versus1830. Exact inventories, named subjects and makers were checked. No catalogue date or medium was silently rewritten. Holdings do not establish ownership, present custody or fresh display; undated legacy display labels remain evidence only.

The [plan](britain-six-existing-holdings-001-plan-001.json.gz) and [transaction receipt](britain-six-existing-holdings-001-applied.json) verify227 new citations and accepted holding assertions, with227 original pending assertions retained as superseded history. The transaction protects {verified['protected_existing_records']:,} scoped records and all12,151 earlier campaign artworks. **29 offline tests and zero-write replay passed**. Metadata, dates, images, creator links, review status and institution records remain unchanged. No commit or deployment.

Campaign totals: **10,259 new artworks and2,119 reconciled existing records across226 institutions**, or **12,378 distinct artwork records**. The latest audit has **{report['after']['museums_below_100']:,} museums below100 linked records** and **{report['after']['museums_below_200']:,} below200**. The [next queue](next-museum-pass-001.json) retains Ferens native additions, selects Salford and Guildhall pending holdings, and preserves the225 Italian museums and every earlier research queue/source hold. The full goal remains active.
'''
 # Keep user-facing prose readable while preserving raw accession/date strings.
 for before,after in [('field1865','field 1865'),('description1863','description 1863'),('Appleby1886','Appleby 1886'),('Binks1822','Binks 1822'),('verify227','verify 227'),('with227','with 227'),('all12,151','all 12,151'),('and2,119','and 2,119'),('across226','across 226'),('below100','below 100'),('below200','below 200'),('the225','the 225'),('Academy423','Academy 423')]:text=text.replace(before,after)
 m.save(backup,dict(at=m.now(),path=str(root),text=root.read_text(),sha256=sha(root)));(a.RUN/'README.md').write_text(text)
 old=root.read_text();intro,rest=old.split('## Added works',1);intro=intro.replace('1,892','2,119').replace('expand 224 institutions','expand 226 institutions').replace('1,238',f"{report['after']['museums_below_100']:,}").replace('after-wave-82','after-wave-83').replace('Williamson and Perth passes','Williamson, Perth, RWA and Ferens passes');root.write_text(intro+'## Added works'+rest+'\n\n## RWA and Ferens — wave83\n\nAccepted 227 links to existing artworks. RWA 139 linked/15 eligible; Ferens 92 linked/79 eligible. Preserve 137 unknown dates and 21 held cases. [Review and evidence](native/britain-six-holdings-20261009/README.md). Ferens remains eight linked records short of 100; the all-museum 100–200 goal remains unfinished.\n')
 m.save(a.RUN/'readme-supersessions-001.json',dict(at=m.now(),changes=[dict(path=str(root.relative_to(m.ROOT)),before_sha256=pin['sha256'],after_sha256=sha(root),backup_path=str(backup),backup_sha256=sha(backup))]));print(json.dumps(dict(documented_existing_links=227,held=21,tests=29,goal_complete=False)),flush=True)
if __name__=='__main__':main()
