"""Freeze wave87 evidence and retain all earlier queues and source holds."""
import csv,hashlib,importlib.util,json
from pathlib import Path
z=importlib.util.spec_from_file_location('a',Path(__file__).with_name('museum-expansion-britain-eight-apply-20261009.py'));a=importlib.util.module_from_spec(z);z.loader.exec_module(a);m=a.m
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 dest=a.RUN/'delivery-checkpoint-001.json';assert not dest.exists();assert sha(a.CHECKPOINT)=='750a1c67d27e1633509c5758bdf1c248b0c08e856f2b071d66e2fdc84f92988b';previous=m.load(a.CHECKPOINT);assert(len(previous['artifacts']),len(previous['external_artifacts']))==(31552,725)
 changes=m.load(a.RUN/'readme-supersessions-001.json')['changes'];changed={v['path']:v for v in changes};assert set(changed)=={str((m.RUN/'README.md').relative_to(m.ROOT))}
 for c in changes:
  assert sha(Path(c['backup_path']))==c['backup_sha256'];x=m.load(Path(c['backup_path']));assert hashlib.sha256(x['text'].encode()).hexdigest()==x['sha256']==c['before_sha256'];assert sha(m.ROOT/c['path'])==c['after_sha256']
 for dep in previous['artifacts']:
  if dep['path'] in changed:assert dep['sha256']==changed[dep['path']]['before_sha256']
  else:a.checked(dep)
 plan,digest=a.validate_plan()
 with m.connect() as db:verified=a.verify(db,plan,digest)
 assert verified['existing_artworks_linked']==184 and verified['prior_campaign_records_preserved']==12714;assert m.load(a.RUN/(a.KEY+'-applied.json'))['plan_sha256']==digest;report=m.load(m.RUN/'verification-after-wave-87.json');assert(report['verified_new_artworks'],report['verified_existing_artworks_linked'],report['institutions_with_new_records_or_reconciled_holdings'])==(10417,2481,230)
 assert verified['current_counts']=={'f751c09d-2023-5b1b-935b-3aae9a3f842a':{'linked':101,'eligible':53},'9c814fd2-038c-582e-b2b0-9dc8c2e0a00b':{'linked':88,'eligible':29}}
 checks=m.load(a.RUN/'checks-001.json');assert(checks['new_offline_tests_passed'],checks['historical_tests_passed'],checks['cumulative_verified_tests'])==(31,1689,1720) and checks['replay_zero_writes'];audit=m.load(m.RUN/'after-wave-87.json');csvcounts={};ids=[]
 for name,count in [('added-artworks-after-wave-87.csv',10417),('reconciled-artworks-after-wave-87.csv',2481),('gac-date-enrichments-after-wave-87.csv',6),('museum-coverage-after-wave-87.csv',len(audit['institutions']))]:
  with(m.RUN/name).open(newline='') as fp:rows=list(csv.DictReader(fp))
  assert len(rows)==count;csvcounts[name]=count
  if name.startswith(('added-artworks','reconciled-artworks')):ids.extend(v['artwork_id'] for v in rows)
 assert len(ids)==len(set(ids))==12898
 external=previous['external_artifacts']+list(checks['logs'].values())+[dict(path=v['backup_path'],sha256=v['backup_sha256']) for v in changes]
 for path in sorted(m.BACKUP.glob(a.KEY+'-*.json.gz')):external.append(dict(path=str(path),sha256=sha(path)))
 assert m.load(m.BACKUP/(a.KEY+'-reviewed-plan-001.json.gz'))==plan;assert m.load(m.BACKUP/(a.KEY+'-transaction-identity-001.json.gz'))['comparisons_equal'];log=Path('/Users/vadimdulub/Library/Logs/artline-britain-eight-delivery-20261009.log');assert '"documented_existing_links": 184' in log.read_text();external.append(dict(path=str(log),sha256=sha(log)));unique={}
 for dep in external:
  assert dep['path'] not in unique or unique[dep['path']]==dep;unique[dep['path']]=dep;assert sha(Path(dep['path']))==dep['sha256']
 a.checked(previous['other_job_status_reference']);paths={m.ROOT/v['path'] for v in previous['artifacts']}|{a.CHECKPOINT,Path(__file__).resolve()};paths|={m.ROOT/v['path'] for v in plan['evidence']};paths|={v for v in a.RUN.rglob('*') if v.is_file()};paths|={v for pattern in ['*britain-eight*20261009.py','*britain_eight*20261009.py'] for v in(m.ROOT/'ops').glob(pattern)};paths|={v for v in m.RUN.glob('*after-wave-87*')};artifacts=[a.reference(v) for v in sorted(paths)]
 assert len(m.load(a.RUN/'remaining-research-001.json.gz')['rows'])==7;nextq=m.load(a.RUN/'next-museum-pass-001.json');assert len(nextq['italian_museums'])==225 and len(nextq['southampton_selected_cards'])==38 and len(nextq['native_addition_targets'])==3;availability=a.RUN/'source-availability-001.json';access=m.load(availability);assert not access['new_source_access_holds'];captured=m.load(a.RUN/'native-objects-001.json');assert len(captured['rows'])==6 and not captured['requests_stopped']
 result=dict(at=m.now(),goal_complete=False,local_only=True,new_additions=0,new_existing_links=184,campaign_new_artworks=10417,campaign_existing_links=2481,distinct_campaign_artwork_ids=12898,institutions_with_new_records_or_reconciled_holdings=230,verification=verified,museum_changes=report['britain_eight_museum_changes'],museums_below_100=report['after']['museums_below_100'],museums_below_200=report['after']['museums_below_200'],global_coverage_snapshot_at=report['global_coverage_snapshot_at'],external_registry_growth_reference=report['external_registry_growth_reference'],new_tests_passed=31,historical_tests_passed=1689,cumulative_verified_tests=1720,plan_sha256=digest,csv_counts_verified=csvcounts,artifacts=artifacts,external_artifacts=list(unique.values()),prior_checkpoint_reference=a.reference(a.CHECKPOINT),prior_artifacts_verified=len(previous['artifacts']),intentional_supersessions=changes,other_job_status_reference=previous['other_job_status_reference'],other_job_totals_separate=True,editorial_holds=7,review_reference=a.reference(a.REVIEW),remaining_research_reference=a.reference(a.RUN/'remaining-research-001.json.gz'),next_museum_pass_reference=a.reference(a.RUN/'next-museum-pass-001.json'),source_availability_reference=a.reference(availability),new_source_access_holds=access['new_source_access_holds'],new_source_access_hold_reference=a.reference(a.RUN/'new-source-access-holds-001.json'),prior_source_access_hold_reference=previous['new_source_access_hold_reference'],native_probe_reference=a.reference(a.RUN/'native-probes-001.json'),runtime=previous['runtime'],next_work='184 verified existing holdings:Southampton101linked/53eligible,Edinburgh City Art Centre88linked/29eligible.104 newly linked unknown dates preserved;7 objects held including3triptych panels,accession/attribution conflicts and unresolved physical versions. No new artwork/image/artist/status changes. Four exact native object corroborations plus Kidner collection-leaflet/estate evidence;179 correlated secondary-evidence links. No new access denials; every earlier access hold persists. Continue selected native additions from38Southampton cards and Edinburgh portrait leads. Preserve225Italian museums,Guildhall17held,Ferens,RWA and every earlier queue. Campaign10417new+2481links=12898distinct across230institutions. All workers terminal before checkpoint. Concrete184-link progress,not a repeated global blocker. Full100minimum/200preferred all-museum goal remains active.')
 m.save(dest,result);print(json.dumps(dict(checkpoint=str(dest.relative_to(m.ROOT)),sha256=sha(dest),artifacts=len(artifacts),external_artifacts=len(unique),new_records=0,new_links=184,campaign_new=10417,campaign_links=2481,below100=result['museums_below_100'])),flush=True)
if __name__=='__main__':main()
