"""Report verified ASFA production delivery and update only this museum's queue row."""
import csv,importlib.util,json
from pathlib import Path
spec=importlib.util.spec_from_file_location('d',Path(__file__).with_name('museum-expansion-asfa-delivery-20261010.py'))
d=importlib.util.module_from_spec(spec);spec.loader.exec_module(d)
a,c,m,RUN=d.a,d.c,d.m,d.RUN

def table(name,rows):
    with (RUN/name).open('x',encoding='utf-8-sig',newline='') as out:
        w=csv.DictWriter(out,fieldnames=list(rows[0]));w.writeheader();w.writerows(rows)

def main():
    assert not (RUN/'delivery-001.json').exists();checks=m.load(RUN/'checks-001.json');read=m.load(RUN/'readback-001.json');public=m.load(RUN/'public-delivery-001.json');assert checks['readback_passed'] and checks['replay_zero_writes'] and checks['local_unchanged'] and public['public_artwork_samples']==6
    p,digest=a.validate_plan();assert digest==d.EXPECTED;prior=m.load(c.CP);at=m.now();assert read['verification']['current_counts']=={c.IID:dict(linked=258,eligible=251)}
    rr=prior['production_institution_register_reference'];register=m.load(c.checked(rr))['rows'];target=next(x for x in register if x['id']==c.IID);assert target['verified_production_works']==8
    target.update(production_catalogue_count_to_200=258,production_date_eligible_count_to_200=251,production_catalogue_count_state='exact',production_date_eligible_count_state='exact',verified_production_works=258,verified_production_eligible_works=251,production_catalogue_count_at=read['at'],production_date_eligible_count_at=read['at'])
    m.save(RUN/'production-institution-register-001.json.gz',dict(at=at,rows=register,previous_register_reference=rr,read_only=True,updated_institutions=[c.IID],global_exact_counts_refreshed=False,global_thresholds_refreshed=False,policy='Only ASFA refreshed:258catalogue,251numeric-date eligible,7unknown/unresolved. Other museum observations retain their own timestamps.'));table('production-institution-register-001.csv',register)
    qr=prior['priority_museum_queue_reference'];queue=m.load(c.checked(qr));assert len(queue['rows'])==227;removed=next(x for x in queue['rows'] if x['id']==c.IID);queue['rows']=[x for x in queue['rows'] if x['id']!=c.IID]
    reached=dict(id=c.IID,at=read['at'],catalogue=258,date_eligible=251,basis='248new artworks and2existing works linked; six new and one old unknown-date records retained. Both100and200catalogue targets reached.')
    queue.setdefault('removed_threshold_reached',[]).append(reached);queue.setdefault('preferred_target_reached',[]).append(reached);queue['latest_removed_threshold_reached']=reached;queue['latest_preferred_target_remaining']=dict(institution_id=c.IID,catalogue=258,gap_to100=0,gap_to200=0,target_reached=True,numeric_eligible=251)
    queue.setdefault('date_research_remaining',[]).append(dict(id=c.IID,catalogue=258,date_eligible=251,unknown_dates=7,reason='Five Kefallinos impressions and one Theofilos-attribution/date conflict plus one original unknown-date record; existingNikolaou1929/source1930disagreement separately retained.'))
    queue.update(at=at,previous_queue_reference=qr,policy='ASFA has reached258catalogueworks and leaves the under100subset.226inherited under-target rows remain,66Greek; this is not a refreshed global census. Other museums still require research.');m.save(RUN/'priority-museum-queue-001.json',queue)
    ledger=[]
    for v in p['records']+p['holdings']:
        f=v['facts'];old=next((x for x in p['before']['artworks'] if x['id']==v['artwork_id']),None)
        ledger.append(dict(artwork_id=v['artwork_id'],institution_id=c.IID,action='existing_holding' if v in p['holdings'] else 'new_record',source_id=f['source_id'],title=old['title'] if old else f['title'],source_title=f['title'],date_display=old['date_display'] if old else f['date_display'],source_date_display=f['date_display'],creation_year_start=old['creation_year_start'] if old else f['first'],creation_year_end=old['creation_year_end'] if old else f['last'],source_url=f['source_url'],status='review'))
    table('delivered-production-artworks-001.csv',ledger)
    table('delivered-production-images-001.csv',[dict(artwork_id=x['artwork_id'],source_id=x['source_id'],number=x['number'],primary=x['set_primary'],storage_path=x['storage_path'],sha256=x['sha256'],bytes=x['bytes'],rights_status=x['rights_status'],rights_label=x['rights_label'],source_url=x['source_url']) for x in p['images']])
    protected=sorted(set(p['prior_ids'])|{x['artwork_id'] for x in p['records']+p['holdings']});assert len(protected)==2277
    m.save(RUN/'protected-production-ids-001.json',dict(at=at,ids=protected,previous_protected_records=2027,new_records=248,new_existing_links=2,composition=dict(campaign_new_artworks=2253,campaign_existing_links=7,additional_existing_image_only_records=17),plan_reference=c.ref(a.PLAN)))
    remaining=dict(at=at,institution_id=c.IID,catalogue=258,preferred200_reached=True,catalogue_gap_to200=0,numeric_date_eligible=251,unknown_numeric_dates=7,new_unknown_numbers=[131,132,133,140,141,199],existing_date_disagreement_number=24,qualified_copy_number=198,source_total=4012,index_cards_reviewed=270,additional_old_comparators=1,individual_objects_reviewed=258,non_art_index_exclusions=13,source_entries_outside_reviewed_index_and_comparators=3741,ready_candidates=0,source_scope='Bounded oldest nine pages;4012source entries and a separate institutional claim of9000physical works are not eligible-import counts.',next_priority='National Historical Museum, IID5d1bc5d4-0e01-5e7b-8669-1411c393a158, last13catalogueworks. SearchCultureEIM4727mixeditems; freshbaseline and selectiveart/date review required.',next_source_reference=c.ref(c.PREVIOUS/'next-source-discovery-001.json.gz'))
    m.save(RUN/'remaining-research-001.json',remaining)
    backup=m.load(RUN/'cloud-backup-001.json');report=dict(at=at,goal_complete=False,production_only=True,local_unchanged=True,plan_sha256=digest,added=248,existing_links=2,date_eligible_new=242,new_unknown_numeric_dates=6,verification=read['verification'],museum_before=dict(works=8,eligible_works=7,primary_images=7),museum_after=dict(works=258,eligible_works=251,primary_images=149),minimum100_catalogue_reached=True,preferred200_catalogue_reached=True,catalogue_gap_to100=0,catalogue_gap_to200=0,production_campaign_totals=dict(new_artworks=2253,existing_links=7,museums=14),historical_local_totals_unchanged=prior['historical_local_campaign_totals'],cross_database_totals_combined=False,new_images=142,new_primary_images=141,new_alternate_images=1,new_artist_links=10,remaining_pending_candidates={},remaining_pending_total=0,global_production_counts_refreshed=False,global_production_thresholds_refreshed=False,backup_id=backup['id'],source_access='258selected SearchCulture and258native object pages;258source thumbnails and148selected native originals; publicterms, Ministrypublicationcontext, threecreator authorities and nineWikiArtcomparators captured. No new provider denial/bypass. An isolated webtool internal fetch error was recovered via the ordinary public page, with no restriction response. All inherited holds remain.',next_work=remaining['next_priority']);m.save(RUN/'delivery-001.json',report)
    (RUN/'README.md').open('x',encoding='utf-8').write(f'''# Athens School of Fine Arts Gallery — 10 October 2026

Added **248 new review artworks**, linked **two existing works** to their documented collection, and delivered **142 authentic images** in production. The gallery increased from **8 to 258 catalogue works**, reaching the preferred 200-item target. It has **251 numeric-date eligible works**, seven with unknown or unresolved dates, and **149 illustrated works**. The real local database is unchanged.

- [Artwork delivery ledger](delivered-production-artworks-001.csv)
- [Image delivery ledger](delivered-production-images-001.csv)
- [Identity review](identity-review-001.json)
- [Verification](checks-001.json)
- [Remaining research](remaining-research-001.json)

The selection used the first nine date-ascending pages of the [museum-supplied SearchCulture collection](https://www.searchculture.gr/aggregator/portal/collections/DigASFA?language=en). Of 270 index entries, thirteen administrative documents or books were excluded before detail capture. The other 257 were artwork leads, including seven existing records; one further existing record was compared. All 258 individual records were checked against their linked [native gallery pages](https://exhibition.asktdigital.gr/). This remains a bounded selection: 3741 of 4012 source entries lie outside the reviewed index and additional comparison. The institution's separate description of over 9000 physical works is not an eligible artwork count.

All source thumbnails, 148 selected native originals, eleven thumbnail contacts, seven original contacts and six prepared contacts were inspected. Three pairs of prints were confirmed as separate impressions using full inventory labels, pencil signatures, paper condition and inking. The two portraits with labels 00752 and 00752_ZOG727 show different people and compositions; their full labels remain intact. Classroom studies of the same model were distinguished by artist, view and execution. Copies of religious, historical and decorative works retain their own dates and makers rather than adopting dates from the prototypes.

Bounded production reconciliation compared 197 artworks and 278 citations and preserved full snapshots. Nine further WikiArt image comparisons found two exact existing works: Mathiopoulos's *Portait of John Polemis* and Nikolaou's *Drawing of a man*. They received holding links rather than duplicate records. The Polemis primary image remains unchanged, with the complete native photograph added as an alternate. Nikolaou received a primary image; its existing 1929 catalogue date remains unchanged while the gallery's 1930 claim is recorded in evidence. All other old metadata, creator links, images and statuses remain preserved.

Ten new creator links use verified existing Moralis and Mathiopoulos records. Their Greek labels and linked person authorities agree with the existing identities and lifespans. Nikolaou's existing link is preserved. Other named creators remain source labels without invented biographies. The label “Orphan” is not treated as a person, and sitter authorities are not treated as makers.

Six new creation dates remain unresolved. Five Kefallinos prints carry source dates of 1953, 1954 or 1954–1957 but relate to the [portfolio published in 1956](https://www.culture.gov.gr/el/information/SitePages/view.aspx?nID=2455); the specific impression or proof has not been established. No 1956 year was invented for those objects. A work attributed to Theofilos is dated 1958, after his death; its date and creator role remain qualified. Another explicitly titled copy preserves its 1958 date with an unidentified copyist after Theofilos. These uncertainties are visible in review records.

The 142 delivered native images preserve full frames, margins, signatures and source markings and are each at most **99807 bytes**. There are 141 new primary images and one alternate. Only verified pre-1956 works were selected for image delivery. Native terms state **CC BY-NC-ND 4.0**, whereas SearchCulture supplies CC BY-SA 4.0 labels; both claims are retained and native images are classified as **restricted**. Existing user approval for the Greek museum image workflow is recorded separately and does not assert copyright-holder permission. Originals and image proofs remain under Library, outside Documents.

Backup **{backup['id']}** succeeded before application. Seventeen offline checks, live preflight, atomic transaction verification, independent readback and a zero-write replay passed. All 142 public image hashes and six public artwork samples were verified. The existing 2027 protected IDs remain intact; the extended protected set now contains 2277 IDs. Plan SHA-256: `{digest}`.

The selected production campaign totals **2253 new artworks and seven existing-work links across 14 museums**. Only ASFA's museum counts were refreshed. The inherited under-100 priority subset now contains 226 rows, including 66 Greek institutions; this is not a new global museum census. The every-museum goal remains active. Next: a fresh baseline and selected object research for the National Historical Museum.
''')
    print(json.dumps(dict(added=248,links=2,images=142,catalogue=258,numeric_eligible=251,protected_ids=2277,priority_rows=226)),flush=True)

if __name__=='__main__':main()
