"""Document verified holdings, exclusions and next native collection additions without losing queues."""
import hashlib,importlib.util,json
from pathlib import Path
z=importlib.util.spec_from_file_location('a',Path(__file__).with_name('museum-expansion-britain-nine-apply-20261009.py'));a=importlib.util.module_from_spec(z);z.loader.exec_module(a);m=a.m;RUN=a.RUN;ref=a.reference;sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 report=m.load(m.RUN/'verification-after-wave-95.json');assert(report['verified_new_artworks'],report['verified_existing_artworks_linked'])==(10623,3035);cp=m.load(a.CHECKPOINT);applied=m.load(RUN/(a.KEY+'-applied.json'));assert applied['created']==0 and applied['existing_links']==229 and applied['verification']==report['britain_nine_holdings'];root=m.RUN/'README.md';pin=next(v for v in cp['artifacts'] if v['path']==str(root.relative_to(m.ROOT)));assert sha(root)==pin['sha256'];backup=m.BACKUP/'britain-nine-root-readme-before-001.json.gz';assert not backup.exists()
 for name in ['checks-001.json','remaining-research-001.json.gz','next-museum-pass-001.json','README.md','readme-supersessions-001.json','source-availability-001.json','new-source-access-holds-001.json']:assert not(RUN/name).exists()
 logsroot=Path('/Users/vadimdulub/Library/Logs');test=(logsroot/'artline-britain-nine-tests-20261009.log').read_text();assert 'Ran 30 tests' in test and test.rstrip().endswith('OK');assert(logsroot/'artline-britain-nine-replay-20261009.log').read_text().strip()=='Unchanged replay: zero writes';logs={v.name:dict(path=str(v),sha256=sha(v)) for v in sorted(logsroot.glob('artline-britain-nine-*-20261009.log')) if not any(x in v.name for x in ['delivery','checkpoint'])};ctx=m.load(RUN/'comparison-source-context-002.json.gz');identity=m.load(RUN/'identity-002.json.gz');citations=m.load(RUN/'identity-citations-002.json.gz');review=m.load(a.REVIEW);decisions=review['decisions'];failures=[];captures=[]
 for name in ['native-probes-001.json','native-extra-001.json.gz','creation-scope-sources-001.json.gz','york-selected-native-001.json.gz','york-followup-native-001.json.gz']:
  x=m.load(RUN/name)
  for v in x.get('rows',[])+x.get('searches',[]):
   if v.get('capture'):captures.append(v['capture'])
   elif v.get('error'):failures.append(dict(artifact_reference=ref(RUN/name),row=v))
 assert len(captures)==31 and len(failures)==4
 m.save(RUN/'checks-001.json',dict(at=m.now(),new_offline_tests_passed=30,historical_tests_passed=1870,cumulative_verified_tests=1900,historical_tests_rerun=False,replay_zero_writes=True,source_objects_reviewed=246,new_artworks=0,existing_links=229,preserved_existing_gallery_holdings=19,editorial_holds=17,identity_artworks=len(identity['state']['artworks']),identity_citations=len(citations['citations']),verified_raw_bodies=review['verified_raw_bodies'],successful_native_html_captures=len(captures),selected_authority_json_captures=1,comparison_raw_bodies=len(ctx['body_references']),comparison_unreconstructed_citations=len(ctx['unreconstructed_bodies']),logs=logs,other_job_totals_separate=True,source_refinements='17holds preserve duplicates,qualified makers,modern dates and panel identity.75unknown-date links remain excluded from eligible totals;154eligible links. Existing published Osborn study stays published; zero new publications. Native York dates and dimension discrepancies retained as evidence without metadata rewrites. Charles Collins biography remains unresolved despite exact native object support.'))
 m.save(RUN/'new-source-access-holds-001.json',dict(at=m.now(),rows=[],previous_source_hold_reference=cp['new_source_access_hold_reference'],policy='No new provider refusal. Two stale Box URLs returned 404; two York searches timed out but other queries and exact native pages succeeded. No bypass or retry of previously held providers.'))
 m.save(RUN/'source-availability-001.json',dict(at=m.now(),new_source_access_holds=[],new_source_access_hold_reference=ref(RUN/'new-source-access-holds-001.json'),previous_source_availability_reference=cp['source_availability_reference'],previous_source_hold_reference=cp['new_source_access_hold_reference'],native_capture_references=[ref(m.ROOT/v['body_path']) for v in captures],selected_authority_reference=ref(RUN/'selected-authorities-001.json.gz'),failed_selected_requests=failures,comparison_context_reference=ref(RUN/'comparison-source-context-002.json.gz'),policy='31successful bounded native HTML captures and1selected Wikidata-authority response.11York exact objects,14search queries with2timeouts,limited museum context and CAS/Foundation scope evidence. No images.351comparison raw bodies reconstructed;13citation bodies unavailable.2Box404URLs are stale selected pages,not a sitewide access refusal. All prior provider holds including Met429 remain active.'))
 held=[v for v in decisions if v['state']=='editorial_hold'];assert len(held)==17;oldremaining=m.load(a.checked(cp['remaining_research_reference']));oldq=m.load(a.checked(cp['next_museum_pass_reference']));live=m.load(m.RUN/'after-wave-95.json');by={v['id']:v for v in live['institutions']};current=[by[iid] for iid in a.IIDS]
 m.save(RUN/'remaining-research-001.json.gz',dict(at=m.now(),rows=held,review_reference=ref(a.REVIEW),previous_remaining_research_reference=cp['remaining_research_reference'],current_museums=current,remaining_to_100_linked={v['id']:max(0,100-v['works']) for v in current},remaining_to_200_linked={v['id']:max(0,200-v['works']) for v in current},remaining_to_100_eligible={v['id']:max(0,100-v['eligible_works']) for v in current},remaining_to_200_eligible={v['id']:max(0,200-v['eligible_works']) for v in current},native_york_reference=ref(RUN/'native-extra-001.json.gz'),native_harris_reference=ref(RUN/'native-probes-001.json'),native_box_reference=ref(RUN/'native-probes-001.json'),policy='TheBox75linked/30eligible,York90/68,Harris83/72 remain under100. Prioritize supported native additions. York public FineArt search is available; Harris66-object curated index exposes9first-page objects. Directory/index size is not eligible artwork coverage. Keep every older queue including225Italian museums and Leeds unresolved versions/GAC leads. No unsupported placeholder objects.'))
 italian=[dict(v,current_linked=by[v['institution_id']]['works'],current_eligible=by[v['institution_id']]['eligible_works']) for v in oldq['italian_museums']];assert len(italian)==225;excluded=['Glasgow Museums Resource Centre','Kelvingrove Art Gallery and Museum','Burrell Collection','Bristol City Museum & Art Gallery','Imperial War Museum London'];nexttargets=sorted([v for v in live['institutions'] if v['kind']=='museum' and v['status']!='archived' and not v['canonical_institution_id'] and v['works']<100 and v['pending_associations']>0 and v['name'] not in excluded and v['id'] not in a.IIDS],key=lambda v:(-v['pending_associations'],v['id']))[:20];native_ids=list(dict.fromkeys([a.IIDS[1],a.IIDS[2],a.IIDS[0]]+[v['id'] for v in oldq['native_addition_targets']]));current_ids=sorted({v['id'] for v in oldq['current_museums']}|set(a.IIDS))
 queue=dict(oldq);queue.update(at=m.now(),previous_queue_reference=cp['next_museum_pass_reference'],italian_museums=italian,existing_holding_review_targets=nexttargets,native_addition_targets=[by[iid] for iid in native_ids],current_museums=[by[iid] for iid in current_ids],current_pass_museums=current,remaining_research_reference=ref(RUN/'remaining-research-001.json.gz'),source_availability_reference=ref(RUN/'source-availability-001.json'),policy='Continue native additions for York90/68,Harris83/72,TheBox75/30 toward100minimum and200preferred. Then Cincinnati,VictoriaGallery,Wolverhampton and other under100 pending targets. All225Italian museum queues and historical source/identity holds persist. Full goal active; no exhaustive index or image downloads.',database_writes=0);queue.pop('completed_target_this_wave',None);m.save(RUN/'next-museum-pass-001.json',queue)
 verified=applied['verification'];rows='\n'.join('| '+v['name']+' | '+str(v['linked_before'])+' → '+str(v['linked_after'])+' | '+str(v['eligible_before'])+' → '+str(v['eligible_after'])+' |' for v in report['britain_nine_museum_changes'])
 text=f'''# The Box, York and Harris holdings — 9 October 2026

Linked **229 existing artworks** after reviewing 246 exact source objects: 75 at The Box, 76 at York Art Gallery and 78 at the Harris Museum. These are reconciled museum associations, not newly created records. **154 links have eligible pre-1971 creation dates; 75 retain explicit date uncertainty.**

| Museum | Linked artworks | Eligible dated artworks |
|---|---:|---:|
{rows}

All three remain below the minimum 100 target. Next work uses the available [York native collection search](https://www.yorkmuseumstrust.org.uk/collections/search/), [Harris fine-art index](https://www.theharris.org.uk/collections/fine-art-collections/) and [The Box collections](https://www.theboxplymouth.com/collections). Index coverage is not artwork coverage.

Seventeen leads remain held: a same-accession John Burton duplicate, two unresolved Clark landscapes, three qualified-maker conflicts, the Lenkiewicz centre panel, source/title and date conflicts, and modern or unresolved creation dates. Fresh York pages date The Reflection to 1991 and Doodle Bug to 1998; the Contemporary Art Society dates Chronic Blue to 1986. These were excluded without overwriting existing unknown fields. Native record 1249 has conflicting Layerthorpe/Acaster Malbis description; record 1250 is a distinct 1829 millboard. The Osborn study is separate from the finished Tate canvas. Charles Collins remains an unresolved object-level maker identity despite exact native object support. [Every decision and limitation is retained](editorial-reviewed-001.json.gz).

**30 offline checks, atomic database readback and zero-write replay passed.** Preserved all {verified['protected_existing_records']:,} scoped existing records, all 13,429 prior campaign records, 19 old museum holdings and every existing metadata/image/status value. The already published Osborn study stayed published; no new publication or current-display claim was made. Verified 383 distinct raw bodies, including 31 fresh HTML pages and one selected authority response. Thirteen older citation bodies could not be reconstructed. Two stale Box URLs returned 404 and two York queries timed out; other queries and exact pages succeeded. No provider refusal was bypassed.

Campaign totals: **10,623 new artworks + 3,035 reconciled existing artworks = 13,658 distinct records across 239 institutions**. **{report['after']['museums_below_100']:,} canonical museums remain below 100 linked works**, and **{report['after']['museums_below_200']:,} below 200**. The full goal remains active. [The continuing queue](next-museum-pass-001.json) preserves all earlier research, 225 Italian museums and every provider hold.
'''
 m.save(backup,dict(at=m.now(),path=str(root),text=root.read_text(),sha256=sha(root)));(RUN/'README.md').write_text(text);old=root.read_text();intro,rest=old.split('## Added works',1);intro=intro.replace('2,806','3,035').replace('13,429','13,658').replace('after-wave-94','after-wave-95').replace('expand 236 institutions','expand 239 institutions').replace('and Leeds Art Gallery passes','Leeds Art Gallery, The Box, York Art Gallery and Harris Museum passes');root.write_text(intro+'## Added works'+rest+'\n\n## The Box, York and Harris holdings — wave95\n\nLinked 229 reviewed existing artworks: 75 at The Box, 76 at York and 78 at the Harris. Counts are now 75/30, 90/68 and 83/72 linked/eligible respectively. The links include 154 eligible and 75 undated works; 17 identity, attribution or date-scope holds remain. Thirty offline checks, atomic readback and zero-write replay passed; no metadata, image, artist or publication changes. [Evidence and remaining work](native/britain-nine-holdings-20261009/README.md). Campaign totals: 10,623 new artworks + 3,035 reconciled works = 13,658 distinct records across 239 institutions. Next: native additions at these three museums toward 100–200. All earlier queues and source holds persist; full goal active.\n');m.save(RUN/'readme-supersessions-001.json',dict(at=m.now(),changes=[dict(path=str(root.relative_to(m.ROOT)),before_sha256=pin['sha256'],after_sha256=sha(root),backup_path=str(backup),backup_sha256=sha(backup))]));print(json.dumps(dict(documented_new_records=0,documented_existing_links=229,held=17,tests=30,institutions_expanded=report['institutions_with_new_records_or_reconciled_holdings'],goal_complete=False)),flush=True)
if __name__=='__main__':main()
