"""Freeze Box continuation accounting and carry every earlier queue forward."""
import collections,gzip,hashlib,importlib.util,json,shutil
from pathlib import Path
z=importlib.util.spec_from_file_location('a',Path(__file__).with_name('museum-expansion-box-continuation-apply-20261009.py'));a=importlib.util.module_from_spec(z);z.loader.exec_module(a);m=a.m;RUN=a.RUN;ref=a.reference;sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 report=m.load(m.RUN/'verification-after-wave-98.json');assert(report['verified_new_artworks'],report['verified_existing_artworks_linked'])==(10875,3035);cp=m.load(a.CHECKPOINT);applied=m.load(RUN/(a.KEY+'-applied.json'));assert applied['created']==21 and applied['verification']==report['box_continuation'];root=m.RUN/'README.md';pin=next(v for v in cp['artifacts'] if v['path']==str(root.relative_to(m.ROOT)));assert sha(root)==pin['sha256'];backup=m.BACKUP/'box-continuation-root-readme-before-001.json.gz';assert not backup.exists()
 for name in ['checks-001.json','remaining-research-001.json.gz','next-museum-pass-001.json','README.md','readme-supersessions-001.json','source-availability-001.json','new-source-access-holds-001.json']:assert not(RUN/name).exists()
 logsroot=Path('/Users/vadimdulub/Library/Logs');test=(logsroot/'artline-box-continuation-tests-20261009-001.log').read_text();assert 'Ran 22 tests' in test and test.rstrip().endswith('OK');assert(logsroot/'artline-box-continuation-replay-20261009-001.log').read_text().strip()=='Unchanged replay: zero writes';logs={p.name:dict(path=str(p),sha256=sha(p)) for p in sorted(logsroot.glob('artline-box-continuation-*-20261009-*.log')) if not any(t in p.name for t in ['delivery','checkpoint'])};ctx=m.load(RUN/'comparison-source-context-002.json.gz');identity=m.load(RUN/'identity-002.json.gz');citations=m.load(RUN/'identity-citations-002.json.gz');ds=m.load(a.REVIEW)['decisions'];caps=[]
 for p in sorted(RUN.glob('*/captures/*.json')):
  rc=m.load(p);body=p.with_suffix('.body.gz');assert hashlib.sha256(gzip.decompress(body.read_bytes())).hexdigest()==rc['sha256'];caps.append(dict(receipt_reference=ref(p),body_reference=ref(body),url=rc['url'],status=rc['status']))
 m.save(RUN/'checks-001.json',dict(at=m.now(),new_offline_tests_passed=22,historical_tests_passed=1961,cumulative_verified_tests=1983,historical_tests_rerun=False,replay_zero_writes=True,selected_candidates=27,new_artworks=21,existing_links=0,already_catalogued=2,editorial_holds=4,source_fact_holds=4,unknown_date_additions=8,date_eligible_additions=13,identity_artworks=len(identity['state']['artworks']),identity_citations=len(citations['citations']),capture_status_counts=dict(collections.Counter(str(v['status']) for v in caps)),comparison_raw_bodies=len(ctx['body_references']),comparison_unreconstructed_citations=len(ctx['unreconstructed_bodies']),logs=logs,other_job_totals_separate=True))
 proofdir=Path('/Users/vadimdulub/Library/Application Support/Artline/research-proofs/box-continuation-20261009');proofdir.mkdir(parents=True,exist_ok=True);proofs=[]
 for v in m.load(RUN/'reynolds-guide-visual-review-001.json')['rendered_proofs']:
  p=Path(v['path']);assert sha(p)==v['sha256'];target=proofdir/p.name;assert not target.exists();shutil.copyfile(p,target);proofs.append(dict(path=str(target),sha256=sha(target),page=v['page']))
 m.save(RUN/'retained-pdf-proofs-001.json',dict(at=m.now(),external_artifacts=proofs,visual_review_reference=ref(RUN/'reynolds-guide-visual-review-001.json'),policy='Four selected source-PDF page proofs retained outside Documents. Not catalogue images.'))
 m.save(RUN/'new-source-access-holds-001.json',dict(at=m.now(),rows=[],previous_source_hold_reference=cp['new_source_access_hold_reference']))
 m.save(RUN/'source-availability-001.json',dict(at=m.now(),new_source_access_holds=[],new_source_access_hold_reference=ref(RUN/'new-source-access-holds-001.json'),previous_source_availability_reference=cp['source_availability_reference'],previous_source_hold_reference=cp['new_source_access_hold_reference'],native_captures=caps,comparison_context_reference=ref(RUN/'comparison-source-context-002.json.gz'),pdf_source_reference=ref(RUN/'reynolds-guide-001.json'),pdf_visual_reference=ref(RUN/'reynolds-guide-visual-review-001.json'),policy='Current public Box WordPress article/media GET metadata and selected ArtFund acquisitions. One10MBmuseumeducationalPDFsuccessfullyretrieved,currentpublicmetadataURL;pages22,23,26,27visuallychecked. Noheldproviderretry,privatefields,credentialedaccessorimageattachments. Allpriorproviderholdspersist.'))
 held=[v for v in ds if v['state']=='editorial_hold'];triage=m.load(RUN/'source-triage-001.json');oldq=m.load(a.checked(cp['next_museum_pass_reference']));live=m.load(m.RUN/'after-wave-98.json');by={v['id']:v for v in live['institutions']};museums=[by[a.IID]]
 m.save(RUN/'remaining-research-001.json.gz',dict(at=m.now(),rows=held,source_fact_holds=triage['holds'],already_catalogued=[v for v in ds if v['state']=='already_catalogued'],review_reference=ref(a.REVIEW),previous_remaining_research_reference=cp['remaining_research_reference'],current_museums=museums,source_gap='Box118linked/56dateeligible.82morelinked neededfor200;44moresupportedcreationdatesneededfor100eligible. Current8unknownrecordsneedfurtherdateevidence. PortEliot23workgroupandunselectednativearticlesremainobjectsourcequeue.',policy='Preserveall4currentversion/factholds,4additionaldocument/scopeleads,2alreadyrepresentedworks andeverypriorqueue. Unknowncreationnoteligibility;noquotaoverridesevidence.'))
 queue=dict(oldq);queue.update(at=m.now(),previous_queue_reference=cp['next_museum_pass_reference'],italian_museums=[dict(v,current_linked=by[v['institution_id']]['works'],current_eligible=by[v['institution_id']]['eligible_works']) for v in oldq['italian_museums']],native_addition_targets=[by[v['id']] for v in oldq['native_addition_targets']],current_museums=[by[v['id']] for v in oldq['current_museums']],current_pass_museums=museums,remaining_research_reference=ref(RUN/'remaining-research-001.json.gz'),source_availability_reference=ref(RUN/'source-availability-001.json'),policy='Boxminimum100linkedmet,but118/56isnot100datedor200linked. Continue82moreBoxholdings,68moreHarris;CityArtCentre88linkedandotherunder100museumsremainpriorities. Preserve225Italianmuseums,Yorkholds,olderqueues,sourceaccessholds. Fullgoalactive.',queue_database_writes=0);m.save(RUN/'next-museum-pass-001.json',queue)
 v=applied['verification'];assert(v['protected_existing_records'],v['prior_campaign_records_preserved'])==(110,13889)
 text=f'''# The Box continuation — 9 October 2026

Added **21 source-backed artworks in review**. The Box now has **118 linked works**, up from 97. Its minimum of 100 linked records is met; the target of 200 remains open.

**13 additions have supported pre-1971 creation dates; eight have dates still unknown.** The museum now has **56 date-eligible works**, up from 43. Unknown dates are not counted as eligible dates.

Selected works include [*Someone Who Waits*](https://theboxplymouth.com/someone-who-waits-by-spencer-gore/), 1907; [*The Bridges by Night*](https://theboxplymouth.com/the-bridges-by-night/), 1965; [*Card Table*](https://theboxplymouth.com/card-table/), 1967–1969; and the [Martinware crab sculpture](https://www.artfund.org/our-purpose/art-funded-by-you/large-anthropomorphic-crab), 1880. The original article URLs are retained in the [decision ledger](editorial-reviewed-001.json.gz).

Two candidates were already represented and were preserved without duplication. Four others remain held for version or source-fact checks: Spencer’s nursery, Olsson’s moonlit Plymouth scene, Williams’s Royal William Yard, and the Drake Cup. Artist lifespans, commission dates, acquisitions and depicted events were not substituted for creation dates. Danckerts and van de Velde attributions remain qualified. Lady Ann Bonfoy belongs to The Box’s Port Eliot collection but remains at Port Eliot; the record makes no claim that it is physically at The Box or currently on display.

The current museum media catalogue provided a working Reynolds educational PDF. Pages 22–23 and 26–27 were rendered and visually checked. The later self-portrait remains a version-comparison lead. The unlocated architectural panel, a bone ship model needing art-scope review and a drawing with unconfirmed holding remain separate research leads. No catalogue images were attached.

**22 offline checks, atomic database readback and zero-write replay passed.** All 110 scoped existing records and all 13,889 prior campaign records were preserved. The identity review retained 9,656 artwork rows and 20,200 citations; 19 raw comparison bodies were reconstructed, with five citation bodies explicitly unavailable. No existing metadata, images, statuses or institution records changed.

Campaign totals: **10,875 new artworks + 3,035 reconciled existing artworks = 13,910 distinct records across 239 institutions**. **{report['after']['museums_below_100']:,} canonical museums remain below 100 linked works** and **{report['after']['museums_below_200']:,} remain below 200**. [The continuing queue](next-museum-pass-001.json) preserves every prior institution and unresolved case. The full goal remains active.
'''
 # Use actual discovered article URLs, not guessed slugs, in the narrative.
 bynum={d['number']:d for d in ds}
 for n,slug in [(1888,'the-bridges-by-night'),(2038,'card-table')]:text=text.replace('https://theboxplymouth.com/'+slug+'/',bynum[n]['facts']['source_url'])
 m.save(backup,dict(at=m.now(),path=str(root),text=root.read_text(),sha256=sha(root)));(RUN/'README.md').write_text(text);old=root.read_text();intro,rest=old.split('## Added works',1);intro=intro.replace('10,854','10,875').replace('1,228','1,227').replace('after-wave-97','after-wave-98').replace('The latest pass adds 21 works with eligible dates and 50 with dates still unknown.','The latest pass adds 13 works with eligible dates and eight with dates still unknown.');table='| Distinct new-record campaign total | **10,854** | **219 collections** |';assert table in rest;rest=rest.replace(table,'| The Box — selected collection continuation | 21 | 1 museum |\n| Distinct new-record campaign total | **10,875** | **219 collections** |',1);root.write_text(intro+'## Added works'+rest+'\n\n## The Box continuation — wave98\n\nAdded 21 real works in review: 13 with documented eligible creation dates and eight with dates unknown. The Box now has 118 linked / 56 date-eligible works, crossing 100 linked. Two existing works were preserved; four version and fact holds remain. Twenty-two offline checks, atomic readback and zero-write replay passed. All 110 scoped existing records and 13,889 prior campaign records were preserved. [Evidence and continuing queue](native/box-continuation-20261009/README.md). Campaign: 10,875 new + 3,035 reconciled = 13,910 distinct records across 239 institutions; 1,227 canonical museums remain below 100. All prior queues and provider holds remain; the goal is active.\n');m.save(RUN/'readme-supersessions-001.json',dict(at=m.now(),changes=[dict(path=str(root.relative_to(m.ROOT)),before_sha256=pin['sha256'],after_sha256=sha(root),backup_path=str(backup),backup_sha256=sha(backup))]));print(json.dumps(dict(documented_new_records=21,held=4,tests=22,goal_complete=False)),flush=True)
if __name__=='__main__':main()
