"""Wave88 evidence register, retained queues and backed-up campaign report update."""
import hashlib,importlib.util,json
from pathlib import Path
z=importlib.util.spec_from_file_location('r',Path(__file__).with_name('museum-expansion-southampton-review-20261009.py'));r=importlib.util.module_from_spec(z);z.loader.exec_module(r);m=r.m;RUN=r.RUN;ref=r.ref;KEY='southampton-native-additions-001';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 report=m.load(m.RUN/'verification-after-wave-88.json');assert(report['verified_new_artworks'],report['verified_existing_artworks_linked'],report['institutions_with_new_records_or_reconciled_holdings'])==(10472,2487,230);cp_path=m.RUN/'native/britain-eight-holdings-20261009/delivery-checkpoint-001.json';assert sha(cp_path)=='168b44d3f9bfaae8029827138dadc0f3cb0c775dddd3f21b232844609273df32';cp=m.load(cp_path);applied=m.load(RUN/(KEY+'-applied.json'));assert applied['created']==55 and applied['existing_links']==6 and applied['verification']==report['southampton_additions'];root=m.RUN/'README.md';pin=next(v for v in cp['artifacts'] if v['path']==str(root.relative_to(m.ROOT)));assert sha(root)==pin['sha256'];backup=m.BACKUP/'southampton-root-readme-before-001.json.gz';assert not backup.exists()
 for name in ['checks-001.json','remaining-research-001.json.gz','next-museum-pass-001.json','README.md','readme-supersessions-001.json','source-availability-001.json','pdf-selected-leads-001.json']:assert not(RUN/name).exists()
 logsroot=Path('/Users/vadimdulub/Library/Logs');test=(logsroot/'artline-southampton-tests-20261009.log').read_text();assert 'Ran 18 tests' in test and test.rstrip().endswith('OK');assert(logsroot/'artline-southampton-replay-20261009.log').read_text().strip()=='Unchanged replay: zero writes';logs={v.name:dict(path=str(v),sha256=sha(v)) for v in sorted(logsroot.glob('artline-southampton-*-20261009.log')) if 'delivery' not in v.name and 'checkpoint' not in v.name}
 m.save(RUN/'checks-001.json',dict(at=m.now(),new_offline_tests_passed=18,historical_tests_passed=1720,cumulative_verified_tests=1738,historical_tests_rerun=False,replay_zero_writes=True,source_objects_reviewed=80,new_artworks=55,existing_links=6,already_catalogued=4,editorial_holds=15,logs=logs,other_job_totals_separate=True,source_refinements='Facts v2 retains PDF/native date discrepancies, explicit circa narratives and comparison-only title aliases. A pre-artifact parser guard failed on PDF OCR spacing ci rca and was corrected against actual text before review,tests or plan. No failed write transaction.'))
 m.save(RUN/'new-source-access-holds-001.json',dict(at=m.now(),rows=[],previous_source_hold_reference=cp['new_source_access_hold_reference'],policy='No new source access holds. Every earlier source hold persists.'))
 m.save(RUN/'source-availability-001.json',dict(at=m.now(),new_source_access_holds=[],new_source_access_hold_reference=ref(RUN/'new-source-access-holds-001.json'),previous_source_availability_reference=cp['source_availability_reference'],previous_source_hold_reference=cp['new_source_access_hold_reference'],native_capture_reference=ref(RUN/'native-captured-001.json.gz'),index_capture_reference=ref(RUN/'additional-indexes-001.json'),pdf_reference=ref(RUN/'exhibition-catalogue-001.json'),selected_image_reference=ref(RUN/'gilman-identity-image-001.json'),policy='80 selected native highlights captured,6 reused from earlier wave and74 new object requests;5 additional historical section pages. One2017 museum exhibition PDF and one selected ClevelandCC0 identity JPEG retained. Selected PDF page rendered and visually checked; no Artline image attachment. Fresh Orsay and Thyssen primary comparison evidence retained. No exhaustive collection/image download or denied source retry.'))
 decisions=m.load(RUN/'editorial-reviewed-001.json.gz')['decisions'];held=[v for v in decisions if v['state']=='editorial_hold'];assert len(held)==15;m.save(RUN/'remaining-research-001.json.gz',dict(at=m.now(),rows=held,review_reference=ref(RUN/'editorial-reviewed-001.json.gz'),previous_remaining_research_reference=cp['remaining_research_reference'],policy='Unknown dates,physical impressions,accession/version conflicts and1981 exclusion remain explicit. Four already-catalogued objects counted separately. Preserve prior Edinburgh,Guildhall and all historical queues.'))
 pdf=m.load(RUN/'exhibition-catalogue-001.json');lead_specs=[(9,'Philip Wilson Steer','Watching Cowes Regatta','1892'),(10,'William Nicholson','The Morris Dancer','1902'),(19,'Percy Wyndham Lewis','Drawing of the Great War No.2','1918'),(19,'Percy Wyndham Lewis','Drawing of the Great War No.1 (The Menin Road)','1918'),(22,'Leslie Cole','Naval Base – Women’s Royal Naval Service Sick Bay','1942'),(25,'Claude Rogers','Miss Lynn','1951'),(26,'John Bratby','Jean and Still Life in Front of Window','1954'),(29,'Henry Lamb','Edie McNeil','1911'),(30,'Matthew Smith','Dulcie','1915'),(31,'Gilbert Spencer','The Rat Catcher','1922'),(32,'Mark Gertler','Seated Nude (Gypsy at her Toilet)','1924'),(36,'Christopher Wood','Breton Woman at Prayer','1930'),(42,'Henri Gaudier-Brzeska','Self Portrait','1913'),(44,'Roger Hilton','Figure and Bird','1963'),(45,'Howard Hodgkin','The Second Visit','1963'),(15,'Alfred Munnings','After the Race',None),(40,'Norman Blamey','Vesting priest with Apparelled Amice','1991'),(46,'Frank Auerbach','JYM1','1981')];leads=[dict(pdf_page_index=p,creator_label=creator,title=title,date_display=date,source_entry_text=pdf['text_pages'][p],state='date_unknown_research' if date is None else 'outside_creation_scope' if int(date)>1970 else 'pending_physical_identity_and_catalogue_reconciliation',source_reference=ref(RUN/'exhibition-catalogue-001.json')) for p,creator,title,date in lead_specs];m.save(RUN/'pdf-selected-leads-001.json',dict(at=m.now(),rows=leads,policy='15 dated pre1971 leads require fresh duplicate,version,provenance and source-field review; not approved additions. One undated and two post1970 works retained separately. Two distinct1918 watercolours on same page need independent physical-object mapping. No accession inferred from page number.'))
 oldq=m.load(r.checked(cp['next_museum_pass_reference']));live=m.load(m.RUN/'after-wave-88.json');by={v['id']:v for v in live['institutions']};italian=[dict(v,current_linked=by[v['institution_id']]['works'],current_eligible=by[v['institution_id']]['eligible_works']) for v in oldq['italian_museums']];assert len(italian)==225;nexttargets=sorted([v for v in live['institutions'] if v['kind']=='museum' and v['status']!='archived' and not v['canonical_institution_id'] and v['works']<100 and v['pending_associations']>0],key=lambda v:(-v['pending_associations'],v['id']))[:20]
 m.save(RUN/'next-museum-pass-001.json',dict(at=m.now(),previous_queue_reference=cp['next_museum_pass_reference'],italian_museums=italian,existing_holding_review_targets=nexttargets,native_addition_targets=[by[v['id']] for v in oldq['native_addition_targets']],current_museums=[by[r.IID]],southampton_reviewed_native_count=80,southampton_pdf_leads_reference=ref(RUN/'pdf-selected-leads-001.json'),edinburgh_portrait_leads=oldq['edinburgh_portrait_leads'],remaining_research_reference=ref(RUN/'remaining-research-001.json.gz'),source_availability_reference=ref(RUN/'source-availability-001.json'),policy='Southampton162linked/114eligible meets100 minimum in both measures; preferred200 remains38 linked or86 date-eligible works away. Continue15 source-dated PDF leads with fresh identity checks. Edinburgh City Art Centre88linked/29eligible and Guildhall115linked/86eligible retain earlier exact-source gaps. Ranked under100 museums with pending evidence are research leads,not automatic matches. Keep225 Italian museums and every historical queue/access hold. Full goal active.',database_writes=0))
 text=f'''# Southampton additions — 9 October 2026

Added **55 source-backed artworks in review** and linked **six existing artworks** to Southampton City Art Gallery. It now has **162 linked records**, up from 101, and **114 with eligible pre-1971 creation dates**, up from 53. The preferred 200 target remains unfinished.

Reviewed 80 native highlights: 55 additions, six existing-object links, 15 held and four already catalogued. New works retain literal native accessions, creator labels, medium, dimensions, source evidence and review status. Existing artwork metadata, artist links and images were preserved.

Sources include the [official object catalogue](https://southamptoncityartgallery.com/collection/) and the [2017 museum exhibition catalogue](https://jcfa.co.uk/usr/library/documents/main/southampton-city-gallery-catalogue.pdf), published for Southampton with its curatorial staff credited. Lowry’s *Floating Bridge* receives the explicit signed 1956 creation date from its exact catalogue entry. The native narrative dates Goswijn van der Weyden’s whole triptych circa 1510; it counts as one object. Dürer and Blake impressions remain held because design or commission dates do not date the physical impressions.

Gilman’s Southampton *Sylvia Gosse* is visually distinct from [Cleveland 1982.125](https://www.clevelandart.org/art/1982.125). Southampton shows a frontal sitter with clasped hands; Cleveland shows a three-quarter view. Native 1912 and catalogue circa 1912–14 remain explicit, as do the 67 × 51 cm versus 67 × 49 cm measurements. Drummond’s *In the Park* retains 1911 or 1912 as conflicting museum dates. Tissot’s native page distinguishes *The Captain’s Daughter* from *The Last Evening*. The PDF’s confused alias was searched for duplicates without importing it as an alternate title. Object URL fragments were not substituted for accession numbers.

Version comparisons also distinguish similar works by Sisley, Pissarro, Monet, Gwen John, Tunnard, Nicholson, Lanyon, Gore and Bonnard. [Thyssen’s Monet thaw painting](https://www.museothyssen.org/en/collection/artists/monet-claude/thaw-vetheuil) measures 60 × 100 cm and differs from Southampton’s 50.5 × 61 cm church painting. The [15 held leads](remaining-research-001.json.gz) include unknown dates, a 1981 work, unresolved print impressions and prior Bigge/Wells conflicts.

The [reviewed plan](southampton-native-additions-001-plan-001.json.gz) and [transaction receipt](southampton-native-additions-001-applied.json) verify 55 artworks, 55 identifiers, 61 citations and 61 accepted collection-holding assertions. Fresh identity checks covered 23,467 existing artworks and 51,405 citations. The transaction preserved 2,256 scoped legacy objects and 12,898 prior campaign objects. **18 offline tests, atomic readback and zero-write replay passed.** One selected Cleveland CC0 JPEG and the exhibition PDF support identity research; no image was attached to the catalogue. Holdings do not establish current display, custody or legal ownership.

Campaign total: **10,472 new artworks + 2,487 reconciled existing artworks = 12,959 distinct records across 230 institutions**. The audit still has **{report['after']['museums_below_100']:,} canonical museums below 100 linked records** and **{report['after']['museums_below_200']:,} below 200**. [Next work](next-museum-pass-001.json) retains 15 further dated Southampton PDF leads, Edinburgh and Guildhall gaps, 225 Italian museums, and all earlier queues and access holds. The all-museum goal remains active. No publication, commit or deployment.
'''
 m.save(backup,dict(at=m.now(),path=str(root),text=root.read_text(),sha256=sha(root)));(RUN/'README.md').write_text(text)
 old=root.read_text();intro,rest=old.split('## Added works',1);intro=intro.replace('10,417 real artwork records across 213 local museums and the Barnes Foundation','10,472 real artwork records').replace('10,417','10,472').replace('2,481','2,487').replace('after-wave-87','after-wave-88');root.write_text(intro+'## Added works'+rest+'\n\n## Southampton additions — wave88\n\nAdded 55 native-source review artworks and linked six existing artworks. Southampton now has 162 linked records and 114 with eligible creation dates, meeting the 100 minimum in both measures. The preferred 200 target remains unfinished. Fifteen held and four already-catalogued highlights remain separately documented. Source date conflicts, whole-triptych identity and similar versions were explicitly reviewed. [Evidence and next leads](native/southampton-additions-20261009/README.md). Campaign: 10,472 new + 2,487 reconciled = 12,959 distinct records across 230 institutions. Full all-museum goal remains active.\n')
 m.save(RUN/'readme-supersessions-001.json',dict(at=m.now(),changes=[dict(path=str(root.relative_to(m.ROOT)),before_sha256=pin['sha256'],after_sha256=sha(root),backup_path=str(backup),backup_sha256=sha(backup))]));print(json.dumps(dict(documented_new_records=55,documented_existing_links=6,held=15,already_catalogued=4,tests=18,goal_complete=False)),flush=True)
if __name__=='__main__':main()
