"""Document verified wave79 and retain the complete unfinished research trail."""
import hashlib,importlib.util,json
from pathlib import Path
z=importlib.util.spec_from_file_location('a',Path(__file__).with_name('museum-expansion-britain-three-apply-20261009.py'));a=importlib.util.module_from_spec(z);z.loader.exec_module(a);m=a.m
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 report=m.load(m.RUN/'verification-after-wave-79.json');assert (report['verified_new_artworks'],report['verified_existing_artworks_linked'],report['institutions_with_new_records_or_reconciled_holdings'])==(10259,1328,219)
 p,d=a.validate_plan()
 with m.connect() as db:verified=a.verify(db,p,d)
 cp=m.load(a.CHECKPOINT);root=m.RUN/'README.md';pin=next(v for v in cp['artifacts'] if v['path']==str(root.relative_to(m.ROOT)));assert sha(root)==pin['sha256'];backup=m.BACKUP/'britain-three-root-readme-before-001.json.gz';assert not backup.exists()
 assert all(not (a.RUN/n).exists() for n in ['checks-001.json','remaining-research-001.json.gz','next-museum-pass-001.json','README.md','readme-supersessions-001.json'])
 logsroot=Path('/Users/vadimdulub/Library/Logs');test=(logsroot/'artline-britain-three-tests-20261009.log').read_text();assert 'Ran 20 tests' in test and test.rstrip().endswith('OK');assert (logsroot/'artline-britain-three-replay-20261009.log').read_text().strip()=='Unchanged replay: zero writes'
 logs={v.name:dict(path=str(v),sha256=sha(v)) for v in sorted(logsroot.glob('artline-britain-three-*-20261009.log')) if 'delivery' not in v.name and 'checkpoint' not in v.name}
 m.save(a.RUN/'checks-001.json',dict(at=m.now(),new_offline_tests_passed=20,historical_tests_passed=1500,cumulative_verified_tests=1520,historical_tests_rerun=False,replay_zero_writes=True,source_objects_reviewed=284,new_artworks=0,existing_links=155,editorial_holds=129,network_holds=123,other_holds=6,unknown_dates_preserved=41,existing_published_record_preserved=1,logs=logs,other_job_totals_separate=True,review_revision_reference=a.reference(a.RUN/'review-revision-001.json'),native_inventory_searches=134,native_exact_object_pages=133))
 held=[v for v in m.load(a.REVIEW)['decisions'] if v['state']=='editorial_hold'];assert len(held)==129
 m.save(a.RUN/'remaining-research-001.json.gz',dict(at=m.now(),rows=held,review_reference=a.reference(a.REVIEW),previous_remaining_research_reference=a.reference(a.prior.RUN/'remaining-research-001.json.gz'),bristol_network_context_reference=a.reference(a.RUN/'bristol-network-context-001.json.gz'),coartist_context_reference=a.reference(a.RUN/'bristol-multiple-creators-context-001.json.gz'),source_access_holds_reference=a.reference(a.RUN/'source-access-holds-001.json'),native_probe_reference=a.reference(a.RUN/'native-probes-001.json'),policy='129 pending branch/object decisions:123 already accepted Bristol network holdings plus six version/attribution cases. Do not treat network and branch as aliases or create duplicate artworks. Preserve the previous9 British holds,6 Verbania holds,352 Italian notices and515 selected source leads through the prior queue. All source access holds remain,including Bristol native403/robots,Art UK403,ArCo timeouts,regional TLS failure and Musei Reali403.'))
 oldq=m.load(a.checked(cp['next_museum_pass_reference']));live=m.load(m.RUN/'after-wave-79.json');by={v['id']:v for v in live['institutions']};italian=[dict(v,current_linked=by[v['institution_id']]['works'],current_eligible=by[v['institution_id']]['eligible_works']) for v in oldq['italian_museums']];assert len(italian)==225
 nextids=['07cb8446-a063-416d-9f23-bb2280532f6e','e9875e7e-6531-50fe-8236-8fc98663ce03','e70682a7-16ed-5ad7-bee5-83773756899c'];targets=[by[k] for k in nextids];assert all(v['works']<100 and v['pending_associations']>0 for v in targets)
 m.save(a.RUN/'next-museum-pass-001.json',dict(at=m.now(),previous_queue_reference=cp['next_museum_pass_reference'],italian_museums=italian,existing_holding_review_targets=targets,remaining_research_reference=a.reference(a.RUN/'remaining-research-001.json.gz'),bristol_branch_remaining=by[a.IIDS[1]],policy='Continue with Museo Nazionale della Scienza e della Tecnologia Leonardo da Vinci,Brighton and Ulster saved-object evidence,subject to current authority,chronology,qualification and version review. Cardiff158linked/112eligible needs more for preferred200. Bristol24linked/21eligible remains under100; its network authority123/111 is distinct. Preserve all earlier queues and access holds. No quota-based approval.',database_writes=0))
 text='''# Cardiff and Bristol holding review — 9 October 2026

Accepted **155 museum-holding links for existing local artworks**. No new artwork records were created.

| Museum | Links accepted | Linked before → after | Eligible dates before → after |
| --- | ---: | ---: | ---: |
| National Museum Cardiff | 131 | 27 → 158 | 19 → 112 |
| Bristol City Museum & Art Gallery | 24 | 0 → 24 | 0 → 21 |

Cardiff now exceeds 100 eligible works; the preferred 200 remains unfinished. Bristol still needs more works. **41 accepted records retain unknown dates**, which do not count toward eligible-date totals. One already published artwork, The Bal Maidens, retains its historical status; this pass publishes nothing.

All 284 pending associations were reviewed using exact saved Wikidata object IDs, titles, creator identities, chronology and museum-qualified inventories from 162 original response bodies. Fresh comparison covered 24,575 existing artworks and 53,070 citations. Additional source context contains 53 entities from 43 bodies; three selected comparison entities were freshly retrieved. Fourteen unlinked creator labels matched nine fresh authority entities, without adding painter links. Correlated secondary claims are not treated as independent museum confirmation. The Art UK access hold remains in force.

The official Museum Wales catalogue was searched for the 134 selected Cardiff inventories, yielding **133 exact object pages**. Every captured object was parsed again from its saved raw response before the transaction. The native inventory, title, creator, dimensions, dates, acquisition and location evidence remain separately identified. Abbreviated creator names and spelling variants were reconciled without rewriting the catalogue. Broad dates and apparent lifespan values in source period fields do not supply invented creation dates. Native loan and storage labels remain evidence, not new ownership, custody or display claims.

The [final decisions](editorial-reviewed-002.json.gz) preserve **123 accepted holdings under the broader Bristol Museums network**, whose 123 linked / 111 eligible works remain unchanged. The network and its specific museum branch are separate authorities. Six additional cases remain pending: two unresolved same-title versions, one verso sharing a base inventory with its recto, one qualified Berchet attribution and two works with missing co-artist labels. The preparation guard found the two native co-artist records before any write; the [earlier draft and its revision](review-revision-001.json) are preserved. Charles Branwhite/J. Hardy and William H. Hopkins/Edmund Havell II require shared-authorship reconciliation. No institution merge or duplicate artwork was used to meet a quota.

The [transaction plan](britain-three-existing-holdings-001-plan-001.json.gz) and [application receipt](britain-three-existing-holdings-001-applied.json) verify 155 new citations and accepted holding assertions, with the original pending assertions superseded and their evidence preserved. Only the artwork museum projection and update timestamp changed. Exact readback protects all scoped target/comparison records, the Bristol network and 11,432 previous campaign records. Twenty offline guards and zero-write replay passed. No artwork metadata, dates, creator links, images or historical statuses changed. No image downloads, commits or deployment.

The [remaining research](remaining-research-001.json.gz) retains all 129 current pending decisions and the earlier research queues. The [next-museum queue](next-museum-pass-001.json) carries forward 225 underfilled Italian museums and identifies Milan's science and technology museum, Brighton and Ulster for review. Bristol native catalogue 403/robots restrictions and all earlier source access holds remain in force.

Campaign totals: **10,259 new artworks plus 1,328 reconciled existing holdings across 219 institutions**, covering **11,587 distinct artwork records**. **1,243 canonical museums remain below 100 linked works**, and **1,389 remain below 200**. The all-museum goal remains active. Backups stay in the designated Application Support directory.
'''
 (a.RUN/'README.md').write_text(text)
 before=root.read_text();split=before.index('\n## Added works');intro=before[:split].replace('1,173 existing','1,328 existing').replace('expand 217 institutions','expand 219 institutions').replace('1,244','1,243').replace('after-wave-78','after-wave-79').replace('Laing and National Army Museum passes','Laing, National Army Museum, Cardiff and Bristol passes')
 contents=intro+before[split:]+'\n\n## Cardiff and Bristol holding reconciliation\n\nThe [Cardiff and Bristol review](native/britain-three-holdings-20261009/README.md) accepted **155 existing-artwork museum links**. Cardiff now has **158 linked works / 112 with eligible dates**; Bristol City Museum & Art Gallery has **24 / 21**. The separate Bristol Museums network remains **123 / 111**. Preserve 123 pending network-to-branch claims and six attribution/version cases. No catalogue metadata, images or historical statuses changed.\n\nThe [wave79 verification](verification-after-wave-79.json) records **10,259 additions and 1,328 holding reconciliations across 219 institutions**. **1,243 canonical museums remain below 100 linked works**. The full goal remains active.\n'
 oldsha=sha(root);m.save(backup,dict(at=m.now(),path=str(root.relative_to(m.ROOT)),sha256=oldsha,text=before));root.write_text(contents);m.save(a.RUN/'readme-supersessions-001.json',dict(at=m.now(),changes=[dict(path=str(root.relative_to(m.ROOT)),before_sha256=oldsha,after_sha256=sha(root),backup_path=str(backup),backup_sha256=sha(backup))]))
 print(json.dumps(dict(documented_existing_links=155,campaign_new=10259,campaign_links=1328,institutions=219,remaining_below100=1243,next_existing_holding_targets=[v['name'] for v in targets])),flush=True)
if __name__=='__main__':main()
