"""Wave129 checkpoint: Athens City exceeds200; wider museum work stays active."""
import hashlib,importlib.util,json
from pathlib import Path
spec=importlib.util.spec_from_file_location('d',Path(__file__).with_name('museum-expansion-athens-city-photographs-delivery-20261010.py'))
d=importlib.util.module_from_spec(spec);spec.loader.exec_module(d)
a,c,m,RUN=d.a,d.c,d.m,d.RUN
sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest()

def main():
    dest=RUN/'delivery-checkpoint-001.json';assert not dest.exists();report=m.load(RUN/'delivery-001.json');checks=m.load(RUN/'checks-001.json');public=m.load(RUN/'public-delivery-001.json');assert report['added']==55 and checks['readback_passed'] and checks['replay_zero_writes'] and public['public_artwork_samples']==4
    plan,digest=a.validate_plan();assert digest==d.EXPECTED and c.ref(c.CP)['sha256']==c.CP_SHA;prior=m.load(c.CP);oldpins={x['path']:x for x in prior['artifacts']};oldext={x['path']:x for x in prior['external_artifacts']};pins=dict(oldpins);external=dict(oldext)
    def add(pin,target):
        assert pin['path'] not in target or target[pin['path']]==pin,pin['path'];target[pin['path']]=pin
    paths={c.CP,a.PLAN,Path(__file__).resolve()};paths|={x for x in RUN.rglob('*') if x.is_file()};paths|={x for x in (m.ROOT/'ops').glob('*athens-city-photographs*20261010.py')};paths|={x for x in (m.ROOT/'ops').glob('*athens_city_photographs*20261010.py')}
    for path in sorted(paths):add(c.ref(path),pins)
    for pin in plan['evidence']:add(pin,pins)
    for pin in plan['external_evidence']:add(pin,external)
    for path in sorted(m.BACKUP.glob('athens-city-photographs-*.json*')):add(dict(path=str(path),sha256=sha(path)),external)
    newpins=[x for x in pins.values() if oldpins.get(x['path'])!=x];newext=[x for x in external.values() if oldext.get(x['path'])!=x]
    for pin in newpins:c.checked(pin)
    for pin in newext:assert sha(pin['path'])==pin['sha256']
    protected=m.load(RUN/'protected-production-ids-001.json')['ids'];assert len(protected)==2027 and set(protected)==set(plan['prior_ids'])|{v['artwork_id'] for v in plan['records']};assert report['remaining_pending_total']==0
    next_work='''Wave129 made verified production progress:55historical photographic works added to Athens City Museum, IID f575847e-47eb-59e4-b558-32d8723bc3c9.153catalogue/63numeric/45primary ->208catalogue/111numeric/45primary. Preferred200catalogue target reached.48new source-dated and7new unresolved-date records.0images,0artistlinks,0existingupdates. Campaign2005new+5existing links across13museums. Preserve2027IDs including17earlier Kilkis image-only updates. LocalDB unchanged; every-museum goal ACTIVE and incomplete. Move to other under-target museums; Athens still has97unknown/unresolved dates, priorart scopeholds and substantial unreviewed collection material.

Use ops/museum-expansion-athens-city-photographs-apply-20261010.py directly for validate_plan/verify. Plan native/athens-city-photographs-20261010/athens-city-photographs-001-plan-001.json.gz SHA60e2a9750ce13beb868e5559ad15e1cd7e57b0029fdbcac53236a8207ba1c6fd.18offline tests, livepreflight, atomicverify, independentreadback, replayzero and4public directorysamples passed. Backup1791649407030 SUCCESSFUL, operationc4bd82a0-8904-41c2-8b8e-d5d100000024, ended2026-10-10T16:25:18.666Z. No storage uploads. New photographerauthority notcreated; museumarchivecreditpreserved indescription/evidence, no unqualifiedmakerassigned. All45existingprimaries and153oldmuseumrecords untouched.1972priorprotectedIDs preserved.

W129source65objectpages fromtwoPhoto indexpages60cards+5extra oldcomparators:55new+all10oldphotographs. All65thumbnails,3contacts andindividual8/48/39/56viewed. Exacthashduplicates0; freshsource/title/creator/imagequery153artworks2creatorlinks198citations, noartist/aliasauthorities, nohashmatches,10oldsourceidentities only. Entire153scoped catalogue fullsnapshot; no exhaustiveglobaldup/10Mclaim. Allsourcepages/thumbnails200. Existing11courtyard,65street differentnew25junction/30church/31sidewalk/56corner; genericseries titles notsamework.8versus48Piraeuschurch viewsdifferentcamerapositions/lamps/foreground;39versus56differentcornerfacades.2/3/35/50Syntagmaviewsdistinct.

All65source medium fields say Ψηφιακή φωτογραφία μόνο (digital photograph only), providerAthensCityMuseum, collectionKoutsaplidonation, archivecredit Φωτογραφικό Αρχείο Γεωργίου Μπακούρου - Λίζας Κουτσαπλή. Catalogued unit is the historic photographic image with documentedmuseumcollectionassociation, not an invented original negative/vintage-print holding. Originalsupport, printdate anddigitisationdateunspecifiedexplicitly. Donor's17Jan2023first-personLiFOinterview corroborates donation of2200printedarchive photographs; it doesnotidentify/dateindividualoriginalsupports. Source:https://www.lifo.gr/culture/photography/i-mystiki-istoria-tis-elladas-se-mia-fotografiki-selida-sto-facebook capturedarchive-context-001.json+HTML. No copyright-generalisation frominterviewused. ActualmuseumCC0labels preserved; noimagesattached because sourcephotodatesafter1955Greekimageworkflow.

New7numbers1–7 datefield1960 conflictsseries title1965–1970:bothkept,numericnull,dateprecisionunknown. DoNOTinvent1960–1970range or silentlychoose1965. Other48sourcephotodates1965 or1965–1970(including21range1965–1968) retained; shorthand1965-70expands1965–1970asexplicitrange, notexact1965frompartialaggregatorenrichment. Modern2019/2025captionremarks,building1910/1866dates,demolition andmuseumdonation date are notphotographcreation. Museumconnectionconcernsphotographnotdepictedstatue/building. Tentativeplaces14/18/27/38/57preserved. Archivecreditnotautomaticallyindividualmaker; architects,donor anddepictedpeople notphotographers. Historicalold10archivecreatorlabelsunchanged.

coverage-clarification-001.json corrects a summary-only sentence inpinnedidentity-review:1634Photo facetentries,60indexcardsselected,5extraoldcompared =>65uniquephotographobjectsreviewed,1569unreviewed(not1574). W127artindex162unique disjoint fromthese65;2178of2405mixedsourceentriesoutside reviewedartindexes/photoobjects.55proposalmetadata/planunchanged. No readycandidatesremain. W128artscopeholds35likely1972menu,942018work,108modernvinylprint remain inathens-city-20261010 namespace, NOTW129photonumbers. W127source42lionthumbnailnonimage200hold remains,no retry. NativeAthensSPA staticJSclientauth mustnotbereusedorprinted; nohighresclaimed.

NEXT source discovery storedthisRUN/next-source-discovery-001.json.gz, twoSCcollectionpages200; object/image downloads0. AthensSchoolofFineArtsGallery IIDfe94f502-f226-56ad-89b1-e6a8fa4dd44e,last8catalogue (historicalcount,needsfreshbaseline). Publiccollection https://www.searchculture.gr/aggregator/portal/collections/DigASFA?language=en observed4012sourceitems; description>9000physicalworks19thcenturytopresent isnot4012eligible/9000importable count. Nativeobserved https://exhibition.asktdigital.gr/ ; institutionhttps://www.asfa.gr/. Defaultindexmostlymodern1990/2008/2009/2020paintings/engravings, someunknown. ActualCC BY-SA4labels. ObserveGET /aggregator/portal/collections/DigASFA/search parameterskeywords[0].value,page.page,resultsMode,sortResults; valuesSCORE,YEAR_ASC,YEAR_DESC,TITLE. UseboundedYEAR_ASC/date/type selection andmetadatafirst, notall4012download. 'Orphan/Ορφανό' creatorlabel isnotautomaticallya person. Collection includesfaculty/studentwork andlaterart; keepcreationcutoff andversionscope. FacetsdynamicendpointobservedHTML concatenationcollectionURL+'/onlyFacetPanel?language='+lang, exactcontrols mustbeobserved. Priorassetplatformsimilarity notproof; no guessedauth/API.

Secondnextsource NationalHistoricalMuseum IID5d1bc5d4-0e01-5e7b-8669-1411c393a158,last13catalogue needsfresh. https://www.searchculture.gr/aggregator/portal/collections/EIM?language=en observed4727mixeditems. Nativeobserved https://www.nhmuseum.gr/tmimata/mesa-stis-sylloges-tou-mouseiou andhttp://www.nhmuseum.gr. Firstpageold1865/1880/1880–1900photographs,pottery1771–1830,etc; actualCC BY4labels,TIFFsource links. GET /aggregator/portal/collections/EIM/search sameobservedsortoptions. Filterselectartworks/decorativeart/photographs beforeimages,don'tpadwithgeneralhistoricaldocuments or depictedbuildingsasobjects. No objectleadsreadyyet. These institutions notchangedthiswave.

OnlyAthensCityregisterrowrefreshed;227under100priorityrowsinheritedsubsetnotglobalcensus,67Greekrows. Athenspreferredtarget208reached appendsqueuepreferred_target_reached,97unknown-date researchremaining. Chania192/117still8short200 with108unreviewed14scopeholds/native403; Theo215/137,Zong216/67targetsmet, Zong149unknown63versionholds. Kilkis56/0/53primary44short100,65publicobjectsreviewed12holdsoldAEMK2imageconflict. Averoff18/9nativezografiki403unchanged; independentSC71available. Allinheritedproviderholds remain(no newdenials/bypass), seepriorcheckpointchain. Do notretry403/429/robots/three-timeoutproviders throughanothermechanism.

Productionproxy127.0.0.1:55519 PID7614 --gcloud-auth revalidatedliveW129, leaveit/unrelated55445/55478alone. Real localpostgresql://localhost/artlineREADONLY, nofixtures/testdatabases. Libraryresearchvenvbs4/PIL/psycopg; proofs/backupsLibrary. Noagents/commits/deployments. AGENTSSHAad0d8067ebf9a99e3198d1d6d0c9853e6acdd8932c5a5a0a9e5bb006416d0241unchanged. Selectedproductionadditions/imagesalready authorized, no repeatedapproval. Executed/pinned scripts/artifactsimmutable; newversionsforcorrections. Historicalarchiveproof a0480d7954d528917245e1a8158bcc542078d9346d5aae701a4ace2666ba3205 inherited; verifynewpins/relevantsnapshots, not46kfilesagain.'''
    result=dict(prior);result.update(at=m.now(),wave=129,goal_complete=False,goal_status='active',previous_goal_turn='progress',production_only=True,local_unchanged=True,new_additions=55,new_existing_links=0,new_images=0,verification=report['verification'],production_museum_before=report['museum_before'],production_museum_after=report['museum_after'],production_campaign_totals=report['production_campaign_totals'],global_production_counts_refreshed=False,global_production_thresholds_refreshed=False,new_tests_passed=18,plan_sha256=digest,plan_reference=c.ref(a.PLAN),prior_checkpoint_reference=c.ref(c.CP),artifacts=list(pins.values()),external_artifacts=list(external.values()),baseline_reference=c.ref(RUN/'baseline-verification-001.json'),review_reference=c.ref(a.REVIEW),checks_reference=c.ref(RUN/'checks-001.json'),public_delivery_reference=c.ref(RUN/'public-delivery-001.json'),production_institution_register_reference=c.ref(RUN/'production-institution-register-001.json.gz'),priority_museum_queue_reference=c.ref(RUN/'priority-museum-queue-001.json'),protected_production_ids_reference=c.ref(RUN/'protected-production-ids-001.json'),pending_candidates={},pending_candidate_total=0,global_threshold_summary_note='Only AthensCity refreshed208catalogue/111numeric eligible. Preferred200reached. Otherobservations retain timestamps;227priorityrows are a subset.',source_availability=report['source_access'],remaining_research_reference=c.ref(RUN/'remaining-research-001.json'),next_source_discovery_reference=c.ref(RUN/'next-source-discovery-001.json.gz'),preferred_target_remaining=dict(institution_id=c.IID,catalogue=208,gap_to100=0,gap_to200=0,target_reached=True,numeric_eligible=111),public_api_date_scope=public['date_scope_note'],next_work=next_work)
    result.pop('previous_research_checkpoint',None);m.save(dest,result)
    m.save(RUN/'final-checkpoint-verification-001.json',dict(at=m.now(),checkpoint=c.ref(dest),verified_new_artifact_pins=len(newpins),verified_new_external_pins=len(newext),inherited_unchanged_artifact_pins=len(pins)-len(newpins),inherited_unchanged_external_pins=len(external)-len(newext),full_historical_proof=prior['initial_full_historical_verification_reference'],plan_sha256=digest,goal_complete=False,actual_added=55,actual_existing_links=0,actual_images=0,protected_production_ids=2027,pending_candidates=0,local_unchanged=True))
    print(json.dumps(dict(checkpoint=c.ref(dest),artifacts=len(pins),external=len(external),verified_new=len(newpins),verified_external=len(newext),added=55,images=0,pending=0)),flush=True)

if __name__=='__main__':main()
