"""Exact source collection labels; acquisition method is not legal ownership or display."""
import gzip,hashlib,importlib.util,json
from pathlib import Path
s=importlib.util.spec_from_file_location('d',Path(__file__).with_name('museum-expansion-france-fourteenth-discovery-20261008.py'));d=importlib.util.module_from_spec(s);s.loader.exec_module(d);m=d.m;RUN=d.RUN;ref=d.prior.reference
CONTEXTS={
'M1108':dict(source='galliera',city='Paris',names=['Palais Galliera, musée de la mode de la Ville de Paris'],locations=['Palais Galliera, musée de la Mode de la Ville de Paris'],mode='named_collection',basis='Exact Museofile code M1108, Paris city, official museum name and current catalogue collection destination identify Palais Galliera. Paris Musées independently identifies its collection. Acquisition-only and blank legal fields are preserved; no item-level legal ownership or current-display claim is inferred.'),
'M1114':dict(source='victor-hugo',city='Paris',names=['maison de Victor Hugo'],locations=['Maison de Victor Hugo - Hauteville House'],mode='named_collection',basis='Exact national museum code M1114 and Paris museum identity correspond to the Paris Musées joint Maisons de Victor Hugo Paris/Guernesey collection. Official operator evidence explicitly describes both sites. The combined collection label supports institutional holding only, never an asserted current physical location in Paris, Guernsey or a gallery. Acquisition-only and blank ownership fields remain literal.'),
'M1113':dict(source='vie-romantique',city='Paris',names=['musée de la vie romantique'],locations=['Musée de la Vie romantique'],mode='named_collection',basis='Exact M1113, Paris, current official museum name and catalogue destination identify this collection. Museofile and Paris Musées separately document it. Acquisition-only or blank legal labels do not establish item-level title and remain unchanged.'),
'M1102':dict(source='balzac',city='Paris',names=['maison de Balzac'],locations=['Maison de Balzac'],mode='named_collection',basis='Exact M1102, Paris and the named Maison de Balzac collection reconcile the national object catalogue to the official museum. Paris Musées confirms its artworks and documents collection. Each drawing, print and bound illustration still requires independent physical-unit review; blank legal fields stay unknown.'),
'M0184':dict(source='auxerre',city='Auxerre',names=["musée d'art et d'histoire Saint-Germain"],locations=["Auxerre ; musée d'art et d'histoire"],mode='municipal_owner',owners=["Auxerre;musée d'art et d'histoire",'Auxerre'],basis='Exact M0184, Auxerre and official Saint-Germain museum identity reconcile the older musée d’Art et d’Histoire destination. Museofile describes the same municipal painting, drawing and archaeological collection. Municipal ownership labels remain literal; generic Auxerre destination is accepted only with the exact source museum code, full official name and separate collection-location field.')}
ACQUISITIONS=['','don manuel','don','legs','achat','achat en vente publique','achat par préemption en vente publique','inscription rétrospective','inscription rétrospective suite au récolement',"mode d'acquisition inconnu","changement d'affectation",'donation (acte notarié)',"achat sur les arrérages d'un legs"]
def main():
    dest=RUN/'museum-name-reconciliation-001.json';assert not dest.exists();x=m.load(d.DISCOVERY);targets={v['slug'].removeprefix('joconde-').upper():v for v in x['targets']};out={}
    operator=RUN/'museum-context-002';operator_refs=[]
    for stem in ['paris-collections','paris-collection-network']:
        p=operator/(stem+'.html.gz');receipt=m.load(operator/(stem+'.receipt.json'));assert receipt['status']==200 and hashlib.sha256(gzip.decompress(p.read_bytes())).hexdigest()==receipt['sha256'];operator_refs += [ref(operator/(stem+ext)) for ext in ['.html.gz','.txt','.receipt.json']]
    operator_text=(operator/'paris-collections.txt').read_text();assert 'La Ville de Paris conserve les deux maisons' in operator_text and 'Hauteville House' in operator_text
    for code,c in CONTEXTS.items():
        target=targets[code];stem=RUN/'museum-context-001'/(c['source']+'-museofile');text=stem.with_suffix('.txt').read_text();receipt=m.load(stem.with_suffix('.receipt.json'));assert receipt['status']==200 and hashlib.sha256(gzip.decompress(stem.with_suffix('.html.gz').read_bytes())).hexdigest()==receipt['sha256'];assert code in text and m.norm(c['city']) in m.norm(text);assert all(m.norm(name) in m.norm(text) for name in c['names'])
        evidence=[ref(stem.with_suffix(ext)) for ext in ['.txt','.html.gz','.receipt.json']]
        if c['mode']=='named_collection':evidence+=operator_refs
        out[code]=dict(c,institution_id=target['id'],owner_prefixes=['propriete de la commune'],accepted_acquisition_labels=ACQUISITIONS if c['mode']=='named_collection' else [],evidence=evidence,legal_title_claim=False,current_display_claim=False)
    m.save(dest,dict(at=m.now(),museums=out,discovery_reference=ref(d.DISCOVERY),reviewer_reference=ref(Path(__file__).resolve()),policy='Exact source-code and named-collection reconciliation. Missing legal ownership is not invented. Acquisition labels are source evidence, not an ownership determination. Joint Hugo catalogue remains a collection holding, without site-specific physical location or display. Object identity, dates and physical units need individual review.'))
    print(json.dumps({code:dict(name=targets[code]['name'],mode=c['mode']) for code,c in out.items()},ensure_ascii=False),flush=True)
if __name__=='__main__':main()
