"""Wave128 checkpoint after verified Athens City production delivery."""
import hashlib,importlib.util,json
from pathlib import Path
spec=importlib.util.spec_from_file_location('d',Path(__file__).with_name('museum-expansion-athens-city-delivery-20261010.py'))
d=importlib.util.module_from_spec(spec);spec.loader.exec_module(d)
a,c,m,RUN=d.a,d.c,d.m,d.RUN
sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest()

def main():
    dest=RUN/'delivery-checkpoint-001.json';assert not dest.exists();report=m.load(RUN/'delivery-001.json');checks=m.load(RUN/'checks-001.json');public=m.load(RUN/'public-delivery-001.json')
    assert report['added']==135 and report['existing_links']==0 and checks['readback_passed'] and checks['replay_zero_writes'];assert public['public_image_hashes_matched']==39 and public['public_artwork_samples']==4
    plan,digest=a.validate_plan();assert digest==d.EXPECTED and c.ref(c.CP)['sha256']==c.CP_SHA;prior=m.load(c.CP);oldpins={v['path']:v for v in prior['artifacts']};oldext={v['path']:v for v in prior['external_artifacts']};pins=dict(oldpins);external=dict(oldext)
    def add(pin,target):
        assert pin['path'] not in target or target[pin['path']]==pin,pin['path'];target[pin['path']]=pin
    paths={c.CP,c.RESEARCH_CP,a.PLAN,Path(__file__).resolve()};paths|={v for v in RUN.rglob('*') if v.is_file()};paths|={v for v in (m.ROOT/'ops').glob('*athens-city*20261010.py')};paths|={v for v in (m.ROOT/'ops').glob('*athens_city*20261010.py')}
    for path in sorted(paths):add(c.ref(path),pins)
    for pin in plan['evidence']:add(pin,pins)
    for pin in plan['external_evidence']:add(pin,external)
    for path in sorted(m.BACKUP.glob('athens-city-production-*.json*')):add(dict(path=str(path),sha256=sha(path)),external)
    add(dict(path=plan['backup_path'],sha256=sha(plan['backup_path'])),external)
    newpins=[v for v in pins.values() if oldpins.get(v['path'])!=v];newext=[v for v in external.values() if oldext.get(v['path'])!=v]
    for pin in newpins:c.checked(pin)
    for pin in newext:assert sha(pin['path'])==pin['sha256'],pin['path']
    protected=m.load(RUN/'protected-production-ids-001.json')['ids'];assert len(protected)==1972 and set(protected)==set(plan['prior_ids'])|{v['artwork_id'] for v in plan['records']};assert report['remaining_pending_total']==0
    next_work='''Wave128 delivered135new review artworks and39authentic primary images to Athens City Museum, IID f575847e-47eb-59e4-b558-32d8723bc3c9.18catalogue/16numeric/6primary ->153catalogue/63numeric/45primary.100minimum reached,47more source-backed works needed for200.47new source-dated and88new unknown-date records.14icons,2existing-artist primary links. No old artwork modified. Campaign1950new+5existing links across13museums; protected1972IDs include17historical Kilkis image-only updates. Real local DB unchanged. Goal ACTIVE and incomplete.

Use ops/museum-expansion-athens-city-apply-20261010.py directly for validate_plan/verify. Plan native/athens-city-delivery-20261010/athens-city-production-001-plan-001.json.gz SHA553ee8bbe15faae6b60abf3415127ce3dab3d8fb1b4ff9f18c2f5577faaad301. Twenty offline tests, live preflight, atomic verification, readback, replayzero,39public image hashes and4public directory samples passed. Initial test harness used draft instead of planned image rows; v2corrected it without writer changes. Keep executed writers/artifacts immutable. Backup/request/storage/apply/readback receipts in deliveryRUN; originals/proofs/backups Library only.

W127research remains immutable native/athens-city-20261010/research-checkpoint-001.json SHA4bbb9a000df2734d1609dac73899ac06ba6eb3d309e50deaf52b7ce309b9479d. All8selected art categories fully indexed: Painting60,Engraving54,Drawing16,Lithography6(overlap),Icon15,Sculpture13,Mixedmedia3,Mosaic1;162unique records across10pages.17explicit post1970 excluded before object/image fetch.145details=135delivered+7oldcomparators+3scopeholds.2405mixed source total is NOT eligible count. Other2243records outside these art types unreviewed. Source facet1634photographs is a research lead, not1634eligible additions. No ready researched candidates remain. New next-photograph-index-001.json.gz contains2observedYEAR_ASCPhoto pages:60cards,5alreadycatalogued,55otherIDs. Indexdate labels1960,1965,1965–1968,1965–1970. Some1960index dates conflict with65–70title wording; preserve the discrepancy and review exact physical/capture dates. Noobjectdetail/imagesdownloadedforthese,0readycandidates. Next review these55metadata leads toward47remaining, applying physical-print/version identity and creation cutoff. Retain museumconnection and unknowncreator support. Do not pad counts with documents/furniture/replicas or use represented-event dates as manufacture.

SearchCulture observed collection https://www.searchculture.gr/aggregator/portal/collections/DigAthensMuseum?language=en ; GET public form /aggregator/portal/collections/DigAthensMuseum/search with facets[ekt_proxy_dc_type_hierarchy_uri].field=ekt_proxy_dc_type_hierarchy_uri,facets[...].values[0].checked=true,facets[...].values[0].value={observedsemanticsURI},resultsMode=GRID,sortResults=TITLE,language=en,page.page=N. Read observed facet controls in research/captures/searchculture-facets-001.body.gz and source-v4 script. Multiple simultaneous categories ANDed and returnedzero; query separately. Single-item/single-page HTML lacks itemsNum; v4handles visible counts. Reuse captures; no pointless retries. Native https://portal.athenscitymuseum.gr/artworks returned200SPA shell. Captured staticJS includes client authorization configuration; do not print or reuse values, call guessed APIs, or claim native highres obtained. Current delivered images are generally380px sourceJPEGs with complete frames retained byte-for-byte, maximum34499B, actualPublicDomainCC0 source labels and userGreekapproval separate.39dated images <=1955. Existing6primaries untouched.

3scopeholds:35menu lithograph inscribedParis14December72, likely1972century/printing date unresolved;94description2018November explicit excluded;108artist-supervised digitalprintonvinyl aftersmalleroriginal, versiondateunknown. Source42lionbiscuitstatuette thumbnail returned200nonimage and isNOT retried; metadata-only delivered, no visualclaim. Source31handcolouredaquatint imageisVERSE, notfront; undated1758–1836isCarleVernetlifespan.31notimaged. Source111Otto around1850 conflictsprototype1853–1854, numericnull.14icons49–62, only61explicitRussiancontext; metalcover/caseoneunit, joinedwoodoneicon.49familyannotation1946,50inscription1863,62dedication1871notassumedcreation.57explicitdate28/06/1858mappedDBexact1858.63decorativeframewithpostcardofTinosiconnotoriginalicon. Source date_precision researchyear mappedDBexact; noinvalidenumwritten.

Creators:103KaraviaChristomanosdrawing primarylink6bc44dd0-9a43-4709-8fd4-454ead88bb15 authority /persons/-1091820013 1871–1960;117Iakovidisfull-lengthThon primarylink5c005acb-575b-44db-97c8-1680d829a479 authority /persons/-1066026377 1853–1932. SittersChristomanos/Thon notmakers. Bothauthorities/aliases/IDs unchanged.133oval1899Cochelwatercolordistinct.109VyronKontopoulos1861–1941 authority1031006912, NOTAlekos; noexistingVyronsafeauthorityfound, objectlabelretained.27NYPLinstitutioncreditand37Kodakmanufacturerlabelnotmakers, creatorNone.84questionedsignatureand87Foltz/T.Foyediscrepancyqualified.31/90/106/111/162designer/engraverrolesunresolved; nofalseprimarylinks(noafter/engraverDBenum).162PinxR.A.notperson.88portraitprivatephone/address omittedpublicdescription butrawsourceauditretained.140–152studentMarkezinisstudies/copies, notoriginalmasters; noadolescentdateinference.65/69/70/75/80two drawingsonesupportcountonce.45vs128cleareddifferentcomposition;10Dunkerquemetadata imageappearsDieppe vs11differentred-sailedship, no title correction guessed.4/5Candia,15/16Brest,138/139Byron,159/160Gudin all distinct sourceobjects.

Freshdelivery identity1740artworks,57artist/aliasIDs,1368creatorlinks,4079citations.135focused fullsnapshots including18oldAthens+exacttitlehits+allIakovidis/Karaviaworks. Threeexistingpublic images+8sourceframes reviewed in contact. ExistingVernet1762LaRochelle/1754Marseillepaintings differ from1776Athensprints. EdwardBrandard B1977.14.13883 Venice727bae1c-b8c0-53f7-9973-caf07b2e792c differscomposition fromAthens162(largeleftdome vsrecedingcanal/rightverticalchurch), notjustanotherimpression. Otherexactport/YoungWoman/Venice hits distinctmaker/medium/source. Broadstem falsepositives notcreatorlinks; no exhaustivevisualclaim for1740 and no10Mloadclaim. All1837priorprotectedIDs and135focuspreserved.

Only Athens register count refreshed;227remaining under100queue rows are inherited subset, notglobalcensus. Chania192/117still8below200,108unreviewedentries14scopeholds; nativeamch403stays. Theo215/137 andZong216/67 catalogue200reached, but Zong149unknown/63versionholds. Kilkis56/0/53primary needs44for100;65publicobjectsallreviewed,12sourceholds andoldAEMK2imageconflict remain;87sculpturebookclaim notcompleteobjectinventory. Averoff18/9 nativezografiki403 remains, independentSC71available. Preserve all inheritedproviderdenials/timeouts, no retries/bypass. No new provider denial thiswave.

Production taskproxy127.0.0.1:55519 PID7614 --gcloud-auth left running; unrelated55445/55478 untouched. Real local postgresql://localhost/artline read-only; nofixtures/testdatabase. ResearchPython Libraryvenv hasbs4/PIL/psycopg. Noagents/commits/deployment. AGENTS SHAad0d8067ebf9a99e3198d1d6d0c9853e6acdd8932c5a5a0a9e5bb006416d0241 unchanged. Selectedproductionadditions/imagesalready authorized; noapprovalrepeat. Inherit fullarchiveproof a0480d7954d528917245e1a8158bcc542078d9346d5aae701a4ace2666ba3205; verifyonlynewpins/relevantsnapshots, not45kfilesagain.'''
    # Carry historical proof and provider history while replacing current delivery pointers.
    result=dict(prior);result.update(at=m.now(),wave=128,goal_complete=False,goal_status='active',previous_goal_turn='progress',production_only=True,local_unchanged=True,new_additions=135,new_existing_links=0,new_images=39,verification=report['verification'],production_museum_before=report['museum_before'],production_museum_after=report['museum_after'],production_campaign_totals=report['production_campaign_totals'],global_production_counts_refreshed=False,global_production_thresholds_refreshed=False,new_tests_passed=20,plan_sha256=digest,plan_reference=c.ref(a.PLAN),prior_checkpoint_reference=c.ref(c.CP),previous_research_checkpoint=c.ref(c.RESEARCH_CP),artifacts=list(pins.values()),external_artifacts=list(external.values()),baseline_reference=c.ref(RUN/'baseline-verification-001.json'),review_reference=c.ref(a.REVIEW),checks_reference=c.ref(RUN/'checks-001.json'),public_delivery_reference=c.ref(RUN/'public-delivery-001.json'),production_institution_register_reference=c.ref(RUN/'production-institution-register-001.json.gz'),priority_museum_queue_reference=c.ref(RUN/'priority-museum-queue-001.json'),protected_production_ids_reference=c.ref(RUN/'protected-production-ids-001.json'),pending_candidates={},pending_candidate_total=0,global_threshold_summary_note='Only Athens City refreshed to153catalogue/63numeric eligible. Other observations retain timestamps;227priority rows are a subset.',source_availability=report['source_access'],remaining_research_reference=c.ref(RUN/'remaining-research-001.json'),preferred_target_remaining=dict(institution_id=c.IID,catalogue=153,gap_to100=0,gap_to200=47,target_reached=False,numeric_eligible=63),public_api_date_scope=public['date_scope_note'],next_work=next_work)
    result.pop('additional_research_checkpoint',None);result.pop('next_source_discovery_reference',None);m.save(dest,result)
    m.save(RUN/'final-checkpoint-verification-001.json',dict(at=m.now(),checkpoint=c.ref(dest),verified_new_artifact_pins=len(newpins),verified_new_external_pins=len(newext),inherited_unchanged_artifact_pins=len(pins)-len(newpins),inherited_unchanged_external_pins=len(external)-len(newext),full_historical_proof=prior['initial_full_historical_verification_reference'],plan_sha256=digest,goal_complete=False,actual_added=135,actual_existing_links=0,actual_images=39,protected_production_ids=1972,pending_candidates=0,local_unchanged=True))
    print(json.dumps(dict(checkpoint=c.ref(dest),artifacts=len(pins),external=len(external),verified_new=len(newpins),verified_external=len(newext),added=135,links=0,images=39,pending=0)),flush=True)

if __name__=='__main__':main()
