"""Wave132: pin WarMuseum delivery and retain every-museum goal and remaining gaps."""
import hashlib,importlib.util,json
from pathlib import Path
spec=importlib.util.spec_from_file_location('d',Path(__file__).with_name('museum-expansion-war-delivery-v2-20261010.py'))
d=importlib.util.module_from_spec(spec);spec.loader.exec_module(d)
a,c,m,RUN=d.a,d.c,d.m,d.RUN

def sha(path):return hashlib.sha256(Path(path).read_bytes()).hexdigest()

def main():
    dest=RUN/'delivery-checkpoint-001.json';assert not dest.exists();report=m.load(RUN/'delivery-001.json');checks=m.load(RUN/'checks-001.json');public=m.load(RUN/'public-delivery-001.json')
    assert report['added']==168 and report['existing_links']==0 and report['new_images']==90 and checks['readback_passed'] and checks['replay_zero_writes'] and checks['local_unchanged']
    assert public['public_artwork_samples']==6 and public['public_image_hashes_matched']==90
    plan,digest=a.validate_plan();assert digest==d.EXPECTED and c.ref(c.CP)['sha256']==c.CP_SHA;prior=m.load(c.CP)
    oldpins={x['path']:x for x in prior['artifacts']};oldext={x['path']:x for x in prior['external_artifacts']};pins,external=dict(oldpins),dict(oldext)
    def add(pin,target):
        assert pin['path'] not in target or target[pin['path']]==pin,pin['path'];target[pin['path']]=pin
    paths={c.CP,a.PLAN,Path(__file__).resolve()}|{x for x in RUN.rglob('*') if x.is_file()}|{x for x in (m.ROOT/'ops').glob('*war*20261010.py')}
    for path in sorted(paths):add(c.ref(path),pins)
    for pin in plan['evidence']:add(pin,pins)
    for pin in plan['external_evidence']:add(pin,external)
    external_paths={x for x in c.PROOF.rglob('*') if x.is_file()}|set(m.BACKUP.glob('war-production-*.json*'))
    for path in sorted(external_paths):add(dict(path=str(path),sha256=sha(path)),external)
    newpins=[x for x in pins.values() if oldpins.get(x['path'])!=x];newext=[x for x in external.values() if oldext.get(x['path'])!=x]
    for pin in newpins:c.checked(pin)
    for pin in newext:assert sha(pin['path'])==pin['sha256'],pin['path']
    protected=m.load(RUN/'protected-production-ids-001.json')['ids'];assert len(protected)==2683 and set(protected)==set(plan['prior_ids'])|{v['artwork_id'] for v in plan['records']}
    queue=m.load(RUN/'priority-museum-queue-001.json');assert len(queue['rows'])==224 and sum(x['country_code']=='GR' for x in queue['rows'])==64 and not any(x['id']==c.IID for x in queue['rows'])
    next_work='''Wave132 delivered168newreviewartworks,90authenticimages and65creatorlinks forAthensWarMuseum IIDa4b7823c-f659-5413-9766-60c2306d8844. Production12catalogue/12numericeligible/12primary ->180catalogue/103numericeligible/102primary. New91eligiblecreationdates,9unknownand68broadsourcecenturyrangescrossing1970. Minimum100cataloguethresholdmet,20morecatalogueworks neededforpreferred200. Older12metadata/date/creator/primary/status/holdingspreserved, including oldmedaleventdateambiguities;103numericcountisclassification,notindependentmanufacturingdatevalidation. No ready/unappliedWar candidatesremain. Every-museumgoalACTIVEandunfinished. Productioncampaign2659new+7existinglinks across16museums;protect2683IDs=2666campaignrecords+17oldKilkisimage-only.224inheritedunder100rowsremain,64Greek,notfreshglobalcensus.

Use ops/museum-expansion-war-apply-v2-20261010.py directly forvalidate_planandverify. Planwar-production-001-plan-002.json.gz SHA458503c6db9c238ec440c52dbb008be08d19130730d3940afc0694e7efefc7a8. Backup1791655912464, operation4d5f4adc-0219-4983-8fba-f1c900000024 succeeded2026-10-10T18:13:23.772Z beforeapply.17offlinechecks,atomicverification,independentreadback,zerowritereplay,90publicimagehashes and6publicsamplespassed. Protected484oldcomparatorsand2515priorcampaignrecordsunchanged;65artistlinks=61existingThaliaFloraKaravia6bc44dd0-9a43-4709-8fd4-454ead88bb15 plus4Roilose17bd3cc-0953-5aa6-9e0e-00a16419379d. Source-linkedSearchCulturepersonauthorities-1091820013and1652662752 matchnamesandlifespans,notusedtoinfercreationdates. No newartist/alias/biography/publication/displayclaims. Localartlinereadonlyunchanged.

WarSourceSearchCultureDigWAR1888mixedentries. Actualadvancedtypefacets independentlyselected:2Dgraphics167,sculpture14,religiousart2,relief2,medals45,maps4;oneoverlap ->233distinctleads,12indexpagesTITLEsort. Combinedfacetv1ANDreturnednoresults;v2fixedindependentcontrols,failedscriptsimmutable. Metadata1–195captured including12old;196–200HTTP500;201–233unattempted. Finalizationv2readcached195pageswithoutnewrequests. FivefailedsourceIDsDigWAR/000181-8472,5334,5343,5341,5340. Noindex-onlyartworkcreation. SourceURL000181-0000islegitimatePetrosSaroglosbust179,notinventory. Nativeexhibition.warmuseumdigital.grTLS hostname mismatchbeforeHTTP;noTLSbypass/HTTPdowngrade/alternatehost. Independentofficialwarmuseum.grAthenspagecaptured200contextonly,noprobativeperobjectdisplayclaim.

All195Greek/Englishmetadataread;Greekprimaryevidencepreservedand mistranslationsrecorded.189decodedthumbnails,8contactsand7focusedframesviewed;6thumbnailresponses200empty103,104,105,138,149,170. No placeholdersattached. Globalidentity484works/1032citations returnedonly12oldsource/exacttitles/images;no additionalestablishedduplicates. SixoldKaraviacompositions(Nikopolisruins,EmminAgaarchedinterior,Tsarouchisportrait,MarieBonaparte,Bizanirockybattery,Troupakiscommander) visuallydistinctfromselectednewworks. Existing21Karavia,3Roilos,28Woodvillerelatedsubjectsreviewed;otherWells/Jansson/Bellini/Florasubstringhitsnotmakers. No exhaustiveglobalduplicateguarantee or10million-rowloadclaim.

168selectednewworksafter15holds. Scopeholds10badge,11Skraand44Eskisehirtechnicalbattlecharts,53militarypennant. Identityholds31artillerytitle/doorwayimage;65artillerytitle/woundedsoldiers;71surgerytitle/activebattle;81mealtitle/convoy;123Ottotitle/femaleportrait;135Byronsittercorroboration;1693DConstantinebustattributedKaravia;132fourphotosphysicalunitunknown;103–105threeGerontasstudiesimagesemptyandphysicalunitsunresolved. Noinventedcounterrecords.133airportentryvisuallyartworkdrawingofplane/tent,soacceptedwithbroad20thdate. Similar3/4/124RoilosEvzonecompositions,87/88Constantinedrawings,107–111nurses,139/140Bursastreets,145/161Mudanyafiguresvisuallydistinct. Oneobjectcompositionpersourcerecord;notoneartworkperfigure/medalview. Album/sheet/rectoversocollationunreported.

Date/makerholdsinsideactualnewreviewrecords:25Coronelli1690–1694captionvs20thcfield;91Sanson20th–21st;150Jansson19th–20th;163VanKeulen20th—actualimpression/reproductiondateunknown.121Orfanidis1919officeyearnotexecution.1891917–18Frenchmedal,190MiddleEast1941–45,194GeorgeI1915,195Epirus1914manufacturedatesunknown.68otherspreservedasliteral20th/19th–20thrangescrossing1970,notnumericeligible,noimages. Early20thliteral+sourcechronology1900–1930qualifiedcirca_range.1Wells1700–1738captionrange;2Senexcirca1725;117Prokopioutitle/descriptionexplicit1928.1912/1921depictionsnotblindlysubstitutedforbroadcreationfields.13/89/151unidentifiedcopyists;115AndrewafterDelacroix,source19thcenturycopy,noDelacroixprimarylink.57photographicreproduction,SCOTTroleunresolved.58N.KesanllisvsNikosKesanlisidentityunresolved,unlinkedobjectlabel.147WoodvilleSr/Jridentityunresolved.152Vemboembroiderer,designmakerunknown,textile.182liturgicalcurtaintextile,183silvercrossmetalwork.184Dexileosmoderncast,185stelemodernreplicacontextnotancientoriginal. Greek194sayswithoutswords,Englishwithswordswrong.95Greek23x24vsEnglish25x24retained.117dimensions024x056unitsunspecified,118dimensions2x1.35withframeunitsunspecified. NoinventoryinventedfromURLIDs.

90selectedpre1956sourceJPEGswerecapturedthroughobservedSearchCulturedigitalfilewrappers,allHTTP200. ALL90BYTEIDENTICALtothumbnails,90digitalframes4contactsviewed. Wrapperdescriptivedimensionsmaydifferfromdecodedpixels,actualpixelsstored. Originals/prepareddeliveriesunchanged,completeframes/margins,noresize/upscale/crop/retouch/generation;max35321bytes. Actualitem-imagepanelanddigitalwrapperCCBYSA4.0rightsnotwebsitefooter;storedcc_by_sawithcredit/license/sourceURL/change notice;userpolicyapproval separate. Oldprimariesuntouched. No imagesforunknown/crosscutoffdateorheldidentity.138dateeligibleunillustrated;149and170alsoemptybutbroad20thrange. ExactcopiesarchivedLibrary. Higherresolutiongap90remains,not falselyclaimedfullresolution. Rightsandheldsourceimageassociationevidencepinned.

NEXTSpatharioShadowTheatreMuseumIIDecc56326-95ff-5063-9e7c-defe30001f0f,last16catalogueworks,requiresfreshlocal/productionbaselineandprotected2683beforework. PriorNHMnext-source-discovery-001.json.gz holds sourcehttps://www.searchculture.gr/aggregator/portal/collections/Mar_Spathareio?language=en,HTTP200at2026-10-10T17:35:55Z,450searchableresultswhileprosedescription453artifacts,1929–2019. ObservedGET/aggregator/portal/collections/Mar_Spathareio/search withkeywords[0].value,page.page,resultsMode,scrollPositionX,sortResults=SCORE/YEAR_ASC/YEAR_DESC/TITLE. ObjectIDsMar_Spathareio/000223-xxx; nativehttps://karagiozismuseum.gr/. First30cardsmixedpost1970and1944/1968/1969shadowpuppets,EvgeniosSpatharis,PNG,CCBYNCSA4.0. Selectactualpre1971artobjectsandqualifiedunknowns,Greekimages<=1955,retainphysicalpuppetcomponent/pair/versionidentity.450noteligiblecount;noindividualSpatharioobjects/imagesdownloadedyet. Originalpuppetsareartisticobjects,notsittersorimaginedhistoricalancientdates. Nikaiaalsodiscovered101entries1924–2016,last16works,mostlypost1970—alternatefuturemuseum,notpromised100eligible.

Inheritedsourceholdsremain:ArtUK403,ArCo3timeouts,LombardiaTLS,MuseiReali403,Bristol403/robots/legacy500,Perth3timeouts,LondonPictureArchive403,Smartify403,Salfordrefusal,GlasgowNavigator3timeouts,www.rct.uk403,www.iwm.org.uk403,Met429W94,nga403W96,watercolourworldrobotsW97,nationalgalleries403W99,FreiburgAccessDenied/AnubisW100,Brestoeuvres500W103,ElGrecoBaptism500/Commons403,kazantzaki.grarchive403,anemoyannis.gr403,ejournals.epublishingarticle19335/PDF17357403,zongolopoulos.gr403,collection.zongolopoulos.gr/eMuseumPlusoneTimeout,SCXML/JSONexportsHTMLerror,Larissanative46/67/92404/SC46nonimage/native7timeout,ChaniaAsklipios403,AIC159136403,Averoffzografiki403,Athensartlion42nonimage. AthensnativeSPAclientauthmustnotreuse/print. NHMEIMfacetonly500,5TIFFwrappers500(22,37–40),HPSdirectConnectionReset54beforeHTTP. No failedroutebypass/alternatemechanism. WaraddsTLSnativeand5object500above,notfilewrapperfailure.

HistoricalpinvariantsunchangedfromNHMW131:Larissacommonandv2eachlostonefinalLFat17:21UTCbeforeNHMplan;causeunknown,ASTsidentical. CurrentNHM-usedhelpersremainunchanged;originalinheritedbytesarchivedexactSHAunderNHMLibraryproofhistorical-helper-variants. historical_artifact_revisionsandhistorical_pin_reconciliation_referencecarriedunchanged. Do notrestoreoldlivehelperbytesorrewriteoldplans/checkpoints. UseWARdirectwriter validator,notoldASFAvalidator. Fullhistoricalarchiveproofinheriteda0480d7954d528917245e1a8158bcc542078d9346d5aae701a4ace2666ba3205;verifynew/relevantpins,notall50koldartifacts.

ProductionproxyPID5785port55519--gcloud-auth,CloudSQLproxy2.26.0SHA47c56cc88acd3250ac90b7ad063532cc22a8cca9dd0896012a2a60d1eab4c159;leaveproxyandunrelatedprocessesalone. Real localpostgresql://localhost/artlineREADONLY;nofixtures/testdatabases. Researchvenv/proofs/backupsLibrary/ApplicationSupport/Artline. Noagents/commits/deployment. Executed/pinnedscriptsimmutable;newversionsforfixes. AGENTSSHAad0d8067ebf9a99e3198d1d6d0c9853e6acdd8932c5a5a0a9e5bb006416d0241. Selectedproductionadditionsandimagesauthorized;norepeatedapproval. Museumlogin/memberpolicyunchanged;activecatalogueunifiedregardlesslegacystatus. Holdingsnotdisplay. Every-museumgoalACTIVE.'''
    next_work+='\n\nWar schema correction: initialplan001 SHAfd55e0a4e9728feba4ad5ec8249e661f613526ce21598964136a26961188aa45 transaction rolledback at184because object_form only allowsicon/null. rolled-back-apply-001 confirms0newartworks/sources/audits and allpreflightstateunchanged. Inlineproof saved correctly but its finalprint had TypeError; saved proof was inspected. Immutable reviewv2/002 and applyv2/plan002 set184/185object_formnull while retaining cast/replica in descriptions/sourcefacts.17offlinechecks include observedobject_formconstraint. Storage-upload-002 verifies/reuses90existinggenerationguardedobjects,0newobjects. Originalplans/writers/tests/receipts preserved; useonlyv2deliverywriter/review002/plan002 for currentvalidation. Backup001 validbeforebothattempts; no failedtransactioncommitted. reportv1/checkpointv1/deliveryv1 were stagedbutneverexecuted;v2 versions describe successfulcorrected delivery.'
    result=dict(prior);result.update(at=m.now(),wave=132,goal_complete=False,goal_status='active',previous_goal_turn='progress',production_only=True,local_unchanged=True,new_additions=168,new_existing_links=0,new_images=90,verification=report['verification'],production_museum_before=report['museum_before'],production_museum_after=report['museum_after'],production_campaign_totals=report['production_campaign_totals'],global_production_counts_refreshed=False,global_production_thresholds_refreshed=False,new_tests_passed=17,plan_sha256=digest,plan_reference=c.ref(a.PLAN),prior_checkpoint_reference=c.ref(c.CP),artifacts=list(pins.values()),external_artifacts=list(external.values()),baseline_reference=c.ref(RUN/'baseline-verification-001.json'),review_reference=c.ref(a.REVIEW),checks_reference=c.ref(RUN/'checks-001.json'),public_delivery_reference=c.ref(RUN/'public-delivery-001.json'),production_institution_register_reference=c.ref(RUN/'production-institution-register-001.json.gz'),priority_museum_queue_reference=c.ref(RUN/'priority-museum-queue-001.json'),protected_production_ids_reference=c.ref(RUN/'protected-production-ids-001.json'),pending_candidates={},pending_candidate_total=0,global_threshold_summary_note='OnlyWarMuseumrefreshed:180catalogue/103numericeligible/102primary,20shortofpreferred200.224inheritedunder100rowsremain,notfreshglobalcensus.',source_availability=report['source_access'],remaining_research_reference=c.ref(RUN/'remaining-research-001.json'),next_source_discovery_reference=c.ref(c.DISCOVERY),preferred_target_remaining=dict(institution_id=c.IID,catalogue=180,gap_to100=0,gap_to200=20,target_reached=False,numeric_eligible=103),public_api_date_scope=public['date_scope_note'],next_work=next_work)
    result.pop('previous_research_checkpoint',None);m.save(dest,result)
    m.save(RUN/'final-checkpoint-verification-001.json',dict(at=m.now(),checkpoint=c.ref(dest),verified_new_artifact_pins=len(newpins),verified_new_external_pins=len(newext),inherited_unchanged_artifact_pins=len(pins)-len(newpins),inherited_unchanged_external_pins=len(external)-len(newext),full_historical_proof=prior['initial_full_historical_verification_reference'],plan_sha256=digest,goal_complete=False,actual_added=168,actual_existing_links=0,actual_images=90,protected_production_ids=2683,pending_candidates=0,local_unchanged=True,historical_revisions_carried=len(prior.get('historical_artifact_revisions',[]))))
    print(json.dumps(dict(checkpoint=c.ref(dest),artifacts=len(pins),external=len(external),verified_new=len(newpins),verified_external=len(newext),added=168,images=90,pending=0)),flush=True)

if __name__=='__main__':main()
