"""Verify and pin wave98 delivery, prior evidence and outstanding research."""
import csv,hashlib,importlib.util,json
from pathlib import Path
z=importlib.util.spec_from_file_location('a',Path(__file__).with_name('museum-expansion-box-continuation-apply-20261009.py'));a=importlib.util.module_from_spec(z);z.loader.exec_module(a);m=a.m;sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 dest=a.RUN/'delivery-checkpoint-001.json';assert not dest.exists();assert sha(a.CHECKPOINT)=='660a70838891789935ac9b024b89d1aa828e6a4fc3677be317a1553f3d096b20';previous=m.load(a.CHECKPOINT);assert(len(previous['artifacts']),len(previous['external_artifacts']))==(35161,962);changes=m.load(a.RUN/'readme-supersessions-001.json')['changes'];changed={v['path']:v for v in changes};assert set(changed)=={str((m.RUN/'README.md').relative_to(m.ROOT))}
 for c in changes:
  assert sha(Path(c['backup_path']))==c['backup_sha256'];x=m.load(Path(c['backup_path']));assert hashlib.sha256(x['text'].encode()).hexdigest()==x['sha256']==c['before_sha256'];assert sha(m.ROOT/c['path'])==c['after_sha256']
 for dep in previous['artifacts']:
  if dep['path'] in changed:assert dep['sha256']==changed[dep['path']]['before_sha256']
  else:a.checked(dep)
 p,digest=a.validate_plan()
 with m.connect() as db:verified=a.verify(db,p,digest)
 assert(verified['verified_new_records'],verified['existing_artworks_linked'],verified['prior_campaign_records_preserved'],verified['protected_existing_records'])==(21,0,13889,110);assert m.load(a.RUN/(a.KEY+'-applied.json'))['plan_sha256']==digest;report=m.load(m.RUN/'verification-after-wave-98.json');assert(report['verified_new_artworks'],report['verified_existing_artworks_linked'])==(10875,3035);checks=m.load(a.RUN/'checks-001.json');assert(checks['new_offline_tests_passed'],checks['historical_tests_passed'],checks['cumulative_verified_tests'])==(22,1961,1983) and checks['replay_zero_writes'];audit=m.load(m.RUN/'after-wave-98.json');csvcounts={};ids=[]
 for name,count in [('added-artworks-after-wave-98.csv',10875),('reconciled-artworks-after-wave-98.csv',3035),('gac-date-enrichments-after-wave-98.csv',6),('museum-coverage-after-wave-98.csv',len(audit['institutions']))]:
  with(m.RUN/name).open(newline='') as fp:rows=list(csv.DictReader(fp))
  assert len(rows)==count;csvcounts[name]=count
  if name.startswith(('added-artworks','reconciled-artworks')):ids.extend(v['artwork_id'] for v in rows)
 assert len(ids)==len(set(ids))==13910;external=previous['external_artifacts']+list(checks['logs'].values())+[dict(path=v['backup_path'],sha256=v['backup_sha256']) for v in changes]
 for v in m.load(a.RUN/'retained-pdf-proofs-001.json')['external_artifacts']:external.append({k:v[k] for k in ['path','sha256']})
 for path in sorted(m.BACKUP.glob(a.KEY+'-*.json.gz')):external.append(dict(path=str(path),sha256=sha(path)))
 assert m.load(m.BACKUP/(a.KEY+'-reviewed-plan-002.json.gz'))==p;identity=m.load(m.BACKUP/(a.KEY+'-transaction-identity-plan-002.json.gz'));assert identity['state_equal'] and identity['citations_equal'] and identity['artwork_count']==9656 and identity['citation_count']==20200;log=Path('/Users/vadimdulub/Library/Logs/artline-box-continuation-delivery-20261009-001.log');assert '"documented_new_records": 21' in log.read_text();external.append(dict(path=str(log),sha256=sha(log)));unique={}
 for dep in external:assert dep['path'] not in unique or unique[dep['path']]==dep;unique[dep['path']]=dep;assert sha(Path(dep['path']))==dep['sha256']
 a.checked(previous['other_job_status_reference']);paths={m.ROOT/v['path'] for v in previous['artifacts']}|{a.CHECKPOINT,Path(__file__).resolve()};paths|={m.ROOT/v['path'] for v in p['evidence']};paths|={v for v in a.RUN.rglob('*') if v.is_file()};paths|={v for v in(m.ROOT/'ops').glob('*box*continuation*20261009.py')};paths|={v for v in m.RUN.glob('*after-wave-98*')};artifacts=[a.reference(v) for v in sorted(paths)];remaining=m.load(a.RUN/'remaining-research-001.json.gz');assert(len(remaining['rows']),len(remaining['already_catalogued']),len(remaining['source_fact_holds']))==(4,2,4);assert len(m.load(a.RUN/'next-museum-pass-001.json')['italian_museums'])==225;availability=a.RUN/'source-availability-001.json';assert not m.load(availability)['new_source_access_holds']
 result=dict(at=m.now(),goal_complete=False,local_only=True,new_additions=21,new_existing_links=0,campaign_new_artworks=10875,campaign_existing_links=3035,distinct_campaign_artwork_ids=13910,institutions_with_new_records_or_reconciled_holdings=report['institutions_with_new_records_or_reconciled_holdings'],verification=verified,museum_changes=report['box_continuation_museum_changes'],museums_below_100=report['after']['museums_below_100'],museums_below_200=report['after']['museums_below_200'],global_coverage_snapshot_at=report['global_coverage_snapshot_at'],external_registry_growth_reference=report['external_registry_growth_reference'],new_tests_passed=22,historical_tests_passed=1961,cumulative_verified_tests=1983,plan_sha256=digest,csv_counts_verified=csvcounts,artifacts=artifacts,external_artifacts=list(unique.values()),prior_checkpoint_reference=a.reference(a.CHECKPOINT),prior_artifacts_verified=len(previous['artifacts']),intentional_supersessions=changes,other_job_status_reference=previous['other_job_status_reference'],other_job_totals_separate=True,editorial_holds=4,source_fact_holds=4,already_catalogued=2,unknown_date_additions=8,date_eligible_additions=13,review_reference=a.reference(a.REVIEW),remaining_research_reference=a.reference(a.RUN/'remaining-research-001.json.gz'),next_museum_pass_reference=a.reference(a.RUN/'next-museum-pass-001.json'),source_availability_reference=a.reference(availability),new_source_access_holds=[],new_source_access_hold_reference=a.reference(a.RUN/'new-source-access-holds-001.json'),prior_source_access_hold_reference=previous['new_source_access_hold_reference'],runtime=previous['runtime'],next_work='Wave98adds21Boxworks:118linked/56eligible,minimum100linkedmet,82shortof200.13dated/8unknown.4currentholds:SpencerNursery,Olssonmoonlight,WilliamsRoyalWilliamYard,DrakeCup;2alreadylinkedPickup/Maeckelberghe.4additionalleads:unlocatedpanel,boneshipmodelscope,Hartdrawingholding,matureReynoldsselfportrait. Onecurrentpublic10MBReynoldsPDFsuccess;pages22,23,26,27visuallycheckedandproofsretainedoutsideDocuments. Noimageattachments.22checks,atomicreadback,zero-writereplaypreserve110existingand13889priorcampaignrecords. Identity9656/20200;19rawcomparisonbodies/5unreconstructedcitations.27selectedcandidatefacts;100historicalpaintingarticlesheaderssurveyedacross5pages,unselectedbodiesremainunreviewed. BoxPortEliot23groupcontains14Reynolds;onlyBonfoyselectedthiswave,remainsphysicallyPortEliot. Ginner1987acquisitionvs1988fundingretained. Rowlandson/Turnerlifespansnotcreation. Allpriorproviderholds,225Italianmuseums,Wave9722holds,York17andolderqueuespersist. ContinueBox200,Harris200,CityArtCentre88linkedandotherunder100museums. Campaign10875new+3035links=13910across239;1227museumsbelow100. Goalactive,thisturnmadeprogress;notblocked. Use lightweightBoxcontinuationhelpers;nohistoricalrecursiveGlasgow/Southamptonimports.')
 m.save(dest,result);print(json.dumps(dict(checkpoint=str(dest.relative_to(m.ROOT)),sha256=sha(dest),artifacts=len(artifacts),external_artifacts=len(unique),new_records=21,campaign_new=10875,campaign_links=3035,below100=result['museums_below_100'])),flush=True)
if __name__=='__main__':main()
