"""Freeze verified wave80 while keeping the all-museum goal and queues active."""
import csv,hashlib,importlib.util,json
from pathlib import Path
z=importlib.util.spec_from_file_location('a',Path(__file__).with_name('museum-expansion-milan-apply-20261009.py'));a=importlib.util.module_from_spec(z);z.loader.exec_module(a);m=a.m
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 dest=a.RUN/'delivery-checkpoint-001.json';assert not dest.exists();assert sha(a.CHECKPOINT)=='dc18a40380accfd7a3bc9171274433d9818357ace77614c014b55e4fd857de06';previous=m.load(a.CHECKPOINT);assert(len(previous['artifacts']),len(previous['external_artifacts']))==(26663,533)
 changes=m.load(a.RUN/'readme-supersessions-001.json')['changes'];changed={v['path']:v for v in changes};assert set(changed)=={str((m.RUN/'README.md').relative_to(m.ROOT))}
 for c in changes:
  assert sha(Path(c['backup_path']))==c['backup_sha256'];x=m.load(Path(c['backup_path']));assert hashlib.sha256(x['text'].encode()).hexdigest()==x['sha256']==c['before_sha256'];assert sha(m.ROOT/c['path'])==c['after_sha256']
 for dep in previous['artifacts']:
  if dep['path'] in changed:assert dep['sha256']==changed[dep['path']]['before_sha256']
  else:a.checked(dep)
 plan,digest=a.validate_plan();assert digest=='9316f8264f56023c745f48f978fc1dd53a71fd06f11006dda6d054c7ad4d53fa'
 with m.connect() as db:verified=a.verify(db,plan,digest)
 assert verified['protected_existing_records']==5545 and verified['prior_campaign_records_preserved']==11587 and verified['current_counts']==dict(linked=147,eligible=87);assert m.load(a.RUN/(a.KEY+'-applied.json'))['plan_sha256']==digest
 report=m.load(m.RUN/'verification-after-wave-80.json');assert(report['verified_new_artworks'],report['verified_existing_artworks_linked'],report['institutions_with_new_records_or_reconciled_holdings'])==(10259,1450,220);mc=report['milan_museum_changes'];assert len(mc)==1 and(mc[0]['existing_linked'],mc[0]['linked_after'],mc[0]['eligible_after'])==(122,147,87)
 checks=m.load(a.RUN/'checks-001.json');assert(checks['new_offline_tests_passed'],checks['historical_tests_passed'],checks['cumulative_verified_tests'])==(18,1520,1538) and checks['replay_zero_writes'];audit=m.load(m.RUN/'after-wave-80.json');csvcounts={};ids=[]
 for name,count in [('added-artworks-after-wave-80.csv',10259),('reconciled-artworks-after-wave-80.csv',1450),('gac-date-enrichments-after-wave-80.csv',6),('museum-coverage-after-wave-80.csv',len(audit['institutions']))]:
  with(m.RUN/name).open(newline='') as fp:rows=list(csv.DictReader(fp))
  assert len(rows)==count;csvcounts[name]=count
  if name.startswith(('added-artworks','reconciled-artworks')):ids.extend(v['artwork_id'] for v in rows)
 assert len(ids)==len(set(ids))==11709
 external=previous['external_artifacts']+list(checks['logs'].values())+[dict(path=v['backup_path'],sha256=v['backup_sha256']) for v in changes]+[dict(path=plan['backup_path'],sha256=plan['backup_sha256'])]
 reviewed=m.BACKUP/(a.KEY+'-reviewed-plan-001.json.gz');assert m.load(reviewed)==plan;external.append(dict(path=str(reviewed),sha256=sha(reviewed)));proof=m.BACKUP/(a.KEY+'-transaction-identity-003.json.gz');x=m.load(proof);assert x['comparisons_equal'] and len(x['comparisons'])==151;external.append(dict(path=str(proof),sha256=sha(proof)))
 log=Path('/Users/vadimdulub/Library/Logs/artline-milan-delivery-20261009.log');assert '"documented_existing_links": 122' in log.read_text();external.append(dict(path=str(log),sha256=sha(log)));unique={}
 for dep in external:
  assert dep['path'] not in unique or unique[dep['path']]==dep;unique[dep['path']]=dep;assert sha(Path(dep['path']))==dep['sha256']
 refs=[]
 for name in ['source-context-001.json.gz','comparison-source-context-001.json.gz','comparison-source-context-002.json.gz','comparison-receipt-context-001.json.gz','comparison-receipt-context-002.json.gz']:refs+=m.load(a.RUN/name)['body_references']
 ds=m.load(a.REVIEW)['decisions'];assert len(ds)==151 and len({d['facts']['native_url'] for d in ds})==151 and len({d['facts']['inventory'] for d in ds})==151;assert sum(v['state']=='approved_existing_holding' for v in ds)==122
 a.checked(previous['other_job_status_reference']);paths={m.ROOT/v['path'] for v in previous['artifacts']}|{a.CHECKPOINT,Path(__file__).resolve()};paths|={v for v in a.RUN.rglob('*') if v.is_file()};paths|={v for pattern in ['*milan*20261009.py'] for v in(m.ROOT/'ops').glob(pattern)};paths|={v for v in m.RUN.glob('*after-wave-80*')};paths|={a.checked(v) for v in refs};artifacts=[a.reference(v) for v in sorted(paths)]
 queue=m.load(a.RUN/'remaining-research-001.json.gz');assert len(queue['rows'])==29;nextq=m.load(a.RUN/'next-museum-pass-001.json');assert len(nextq['italian_museums'])==225 and len(nextq['existing_holding_review_targets'])==2;assert sum(v['n'] for v in nextq['upcoming_pending_by_current_institution'] if v['current_institution_id']=='022bf39a-6bac-5a80-a905-e603077e3718')==53
 result=dict(at=m.now(),goal_complete=False,local_only=True,new_additions=0,new_existing_links=122,campaign_new_artworks=10259,campaign_existing_links=1450,distinct_campaign_artwork_ids=11709,institutions_with_new_records_or_reconciled_holdings=220,verification=verified,museum_changes=mc,museums_below_100=report['after']['museums_below_100'],museums_below_200=report['after']['museums_below_200'],global_coverage_snapshot_at=report['global_coverage_snapshot_at'],external_registry_growth_reference=report['external_registry_growth_reference'],new_tests_passed=18,historical_tests_passed=1520,cumulative_verified_tests=1538,plan_sha256=digest,csv_counts_verified=csvcounts,artifacts=artifacts,external_artifacts=list(unique.values()),prior_checkpoint_reference=a.reference(a.CHECKPOINT),prior_artifacts_verified=len(previous['artifacts']),intentional_supersessions=changes,other_job_status_reference=previous['other_job_status_reference'],other_job_totals_separate=True,editorial_holds=29,duplicate_candidate_holds=23,version_holds=6,unknown_dates_preserved=60,review_reference=a.reference(a.REVIEW),remaining_research_reference=a.reference(a.RUN/'remaining-research-001.json.gz'),next_museum_pass_reference=a.reference(a.RUN/'next-museum-pass-001.json'),new_source_access_hold_reference=previous['new_source_access_hold_reference'],native_probe_reference=a.reference(a.RUN/'native-probes-001.json'),runtime=previous['runtime'],raw_source_body_references_verified=len({v['path'] for v in refs}),next_work='122 verified Milan holding links;0new artworks. Museo Scienza e Tecnologia147linked/87eligible;60unknown dates preserved.23 probable duplicates and6 unresolved versions remain. 151 native museum objects matched with unique IGB inventories, plus unapproved captured addition leads. Campaign10259new+1450links=11709 distinct protected records across220institutions. Continue Brighton and Ulster exact existing-source review;53Ulster claims already belong to National Museums Northern Ireland network and must not be treated as interchangeable branches. Preserve225 Italian museums,all prior queues and every source access hold. Current source workers terminal;concrete122-link progress,no repeated global blocker. The all-museum100minimum/200preferred goal remains active.')
 m.save(dest,result);print(json.dumps(dict(checkpoint=str(dest.relative_to(m.ROOT)),sha256=sha(dest),artifacts=len(artifacts),external_artifacts=len(unique),existing_links=122,campaign_new=10259,campaign_links=1450,below100=result['museums_below_100'])),flush=True)
if __name__=='__main__':main()
