"""Record verified wave81, distinguish branch refinements and preserve all queues."""
import hashlib,importlib.util,json
from pathlib import Path
z=importlib.util.spec_from_file_location('a',Path(__file__).with_name('museum-expansion-britain-four-apply-v2-20261009.py'));a=importlib.util.module_from_spec(z);z.loader.exec_module(a);m=a.m
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 report=m.load(m.RUN/'verification-after-wave-81.json');assert(report['verified_new_artworks'],report['verified_existing_artworks_linked'],report['institutions_with_new_records_or_reconciled_holdings'])==(10259,1668,222);plan,digest=a.validate_plan()
 with m.connect() as db:verified=a.verify(db,plan,digest)
 assert verified['network_to_branch_refinements']==47 and verified['previously_unlinked']==171 and verified['unknown_date_records_preserved']==41
 cp=m.load(a.CHECKPOINT);root=m.RUN/'README.md';pin=next(v for v in cp['artifacts'] if v['path']==str(root.relative_to(m.ROOT)));assert sha(root)==pin['sha256'];backup=m.BACKUP/'britain-four-root-readme-before-001.json.gz';assert not backup.exists()
 assert all(not(a.RUN/n).exists() for n in ['checks-001.json','remaining-research-001.json.gz','next-museum-pass-001.json','README.md','readme-supersessions-001.json'])
 logsroot=Path('/Users/vadimdulub/Library/Logs');test=(logsroot/'artline-britain-four-tests-20261009.log').read_text();assert 'Ran 22 tests' in test and test.rstrip().endswith('OK');assert(logsroot/'artline-britain-four-replay-20261009.log').read_text().strip()=='Unchanged replay: zero writes'
 logs={v.name:dict(path=str(v),sha256=sha(v)) for v in sorted(logsroot.glob('artline-britain-four-*-20261009.log')) if 'delivery' not in v.name and 'checkpoint' not in v.name}
 m.save(a.RUN/'checks-001.json',dict(at=m.now(),new_offline_tests_passed=22,historical_tests_passed=1538,cumulative_verified_tests=1560,historical_tests_rerun=False,replay_zero_writes=True,source_objects_reviewed=239,new_artworks=0,existing_links=218,previously_unlinked=171,network_to_branch_refinements=47,editorial_holds=21,unknown_dates_preserved=41,logs=logs,other_job_totals_separate=True,native_inventory_searches=239,native_exact_objects=179,native_brighton_exact=62,native_ulster_exact=117))
 held=[v for v in m.load(a.REVIEW)['decisions'] if v['state']=='editorial_hold'];assert len(held)==21
 m.save(a.RUN/'remaining-research-001.json.gz',dict(at=m.now(),rows=held,review_reference=a.reference(a.REVIEW),previous_remaining_research_reference=a.reference(a.prior.RUN/'remaining-research-001.json.gz'),network_context_reference=a.reference(a.RUN/'ulster-network-context-001.json.gz'),brighton_branch_context_reference=a.reference(a.RUN/'brighton-branch-context-001.json'),policy='21 pending decisions:7 potential Preston Manor inventories,1 explicit Royal Pavilion department conflict,2 NMNI departments outside Fine Art branch inference,3 qualified makers,1 conflicting maker label,4 unresolved versions and3 date/scope conflicts. Six accepted NMNI network holdings remain unchanged. Preserve prior Milan29 holds and11 unapproved native leads,all earlier queues and all source access holds. No placeholder or quota-based record approval.'))
 oldq=m.load(a.checked(cp['next_museum_pass_reference']));live=m.load(m.RUN/'after-wave-81.json');by={v['id']:v for v in live['institutions']};italian=[dict(v,current_linked=by[v['institution_id']]['works'],current_eligible=by[v['institution_id']]['eligible_works']) for v in oldq['italian_museums']];assert len(italian)==225
 targets=[by[k] for k in ['97f7055a-ac1b-529d-b6b0-1d2865e74650','8ee64e58-9eb2-5c26-82ae-fe6688fa6928']];assert all(v['works']<100 and v['pending_associations']>=100 for v in targets)
 m.save(a.RUN/'next-museum-pass-001.json',dict(at=m.now(),previous_queue_reference=cp['next_museum_pass_reference'],italian_museums=italian,existing_holding_review_targets=targets,remaining_research_reference=a.reference(a.RUN/'remaining-research-001.json.gz'),current_museums=[by[k] for k in a.IIDS+[a.s.NETWORK]],policy='Continue Williamson Art Gallery and Museum and Perth Art Gallery saved-object review with fresh native-source discovery where available. Brighton127linked/105eligible needs73 for preferred200;Ulster116linked/95eligible needs5 more eligible works or separately supported date reconciliation and84 for preferred200. Preserve all prior225 Italian museums and source access holds,including Art UK,ArCo,Bristol,regional TLS and Musei Reali. No blind branch reassignment.',database_writes=0))
 text=f'''# Brighton and Ulster holding review — 9 October 2026

Applied **218 reviewed links for existing local artworks**: **171 previously unlinked works and 47 refinements from the National Museums Northern Ireland group to Ulster Museum**. No new artwork records were created.

| Museum | Accepted links | Linked before → after | Eligible dates before → after |
| --- | ---: | ---: | ---: |
| Brighton Museum & Art Gallery | 109 | 18 → 127 | 16 → 105 |
| Ulster Museum | 109 | 7 → 116 | 7 → 95 |

Both museums now exceed 100 linked records. Brighton also exceeds 100 eligible dates. **41 accepted works retain unknown dates**; Ulster needs five more eligible works or a separately supported date review to reach 100 eligible. The preferred 200 remains unfinished for both museums.

All 239 pending claims were reviewed from 138 original saved Wikidata bodies, exact object IDs, creator identities, museum-qualified inventories and source chronology. Fresh identity comparison covered 24,589 artworks and 51,452 citations. Twenty unlinked labels matched 13 creator authority entities without adding painter links. Additional comparison context retains 56 source contexts for 34 comparison artworks from 49 raw bodies. Correlated secondary claims are identified as such; Art UK was not fetched through its existing access hold.

Selected native inventory searches produced **62 exact Brighton API objects and 117 exact NMNI object pages**. The remaining 60 searches had no exact result; this absence is not treated as a contradiction or native confirmation. Every captured exact object and original source entity was re-parsed from saved raw bytes before the transaction. Native titles, maker roles, dates, materials, dimensions, descriptions and rights labels are retained separately. No images were downloaded or attached.

The 47 Ulster refinements are **editorial inferences**, combining the exact BELUM inventory, native Fine Art:Paintings department, [the official collection policy placing Fine Art under Ulster Museum](https://cms.nationalmuseumsni.org/sites/default/files/2025-01/National%20Museums%20NI%20Collections%20Development%20Policy_updated%202025.pdf) and referenced object-level Wikidata collection/location claims naming that specific branch. A general policy alone does not establish an object's branch. The former group assertions remain intact in audit history, pointing to their replacement assertions; the group and museum authorities are not merged. The group retains six unresolved artworks, four with eligible dates. Holdings do not establish ownership, present custody or current display.

The [21 held cases](remaining-research-001.json.gz) preserve attribution, version, branch and date uncertainty. One native record is dated 1978; one undated object names a creator born 1976; Brighton Castle Hill has a conflicting 1982 native date. No date is invented or changed. A native Brighton object is assigned to the Royal Pavilion department. Seven FAPM inventories need Preston Manor branch work; [the official legacy history locates the Pickle portrait there](https://brightonmuseums.org.uk/discovery/history-stories/preston-manors-lion-dog-from-ancient-china/), without proving every other FAPM assignment or fresh display. Two NMNI departments fall outside this pass's Fine Art branch inference. Three qualified attributions, one conflicting maker label and four version comparisons remain held.

The [plan](britain-four-existing-holdings-001-plan-002.json.gz) and [receipt](britain-four-existing-holdings-001-applied.json) verify 218 new citations and accepted assertions, 218 superseded pending assertions and 47 superseded network assertions. Twenty-one older unaccepted network assertions remain unchanged,including 19 on selected works and 2 on held works. Branch transitions stage the replacement assertion in review,point old assertions to it,and accept it within one transaction,retaining the database constraint of one current accepted holding. Only institution projection and update timestamps changed. Readback protects {verified['protected_existing_records']:,} scoped records and 11,709 earlier campaign records. **22 offline tests and zero-write replay passed**. Metadata, creator links, images and review status remain unchanged; no commits or deployment.

Campaign total: **10,259 new artworks and 1,668 reconciled existing records across 222 institutions**, or **11,927 distinct records**. The current audit has **{report['after']['museums_below_100']:,} museums below 100 linked works** and **{report['after']['museums_below_200']:,} below 200**. [The next queue](next-museum-pass-001.json) selects Williamson and Perth while preserving 225 Italian museums and all earlier evidence, unresolved work and source access holds. The full goal remains active.
'''
 m.save(backup,dict(at=m.now(),path=str(root),text=root.read_text(),sha256=sha(root)));(a.RUN/'README.md').write_text(text)
 old=root.read_text();intro,rest=old.split('## Added works',1);intro=intro.replace('1,450','1,668').replace('expand 220 institutions','expand 222 institutions').replace('1,242',f"{report['after']['museums_below_100']:,}").replace('after-wave-80','after-wave-81').replace('and Milan passes','Milan, Brighton and Ulster passes');intro=intro.replace('after reviewing their museum-holding evidence.','after reviewing their museum-holding evidence. This includes 47 documented refinements from the NMNI group to Ulster Museum; these are existing artworks,not new records.');root.write_text(intro+'## Added works'+rest+'\n\n## Brighton and Ulster — wave81\n\nAccepted 218 existing-record links:171 previously unlinked and47 NMNI-to-Ulster branch refinements. Brighton127linked/105eligible;Ulster116linked/95eligible. Preserve41 unknown dates and21 held branch,creator,version or date cases. [Review and evidence](native/britain-four-holdings-20261009/README.md). The all-museum 100–200 goal remains unfinished.\n')
 m.save(a.RUN/'readme-supersessions-001.json',dict(at=m.now(),changes=[dict(path=str(root.relative_to(m.ROOT)),before_sha256=pin['sha256'],after_sha256=sha(root),backup_path=str(backup),backup_sha256=sha(backup))]));print(json.dumps(dict(documented_existing_links=218,previously_unlinked=171,branch_refinements=47,held=21,tests=22,goal_complete=False)),flush=True)
if __name__=='__main__':main()
