"""Individual decisions on captured source facts and physical identity comparisons."""
HOLDS={
19:'Printed source creation 1893 conflicts with the attached mat label circa 1889. Preserve both; reconcile physical impression chronology before adding.',
30:'Source explicitly describes two prints in one frame, inventory 2011.0.5 (1-2). Component-object identity requires reconciliation; do not count a pair as an arbitrary single artwork.',
}
NOTES={
1:'Signed 1887 watercolour design for Saint-Briac stained glass; 28.4 × 21 cm sheet, distinct from Bernard’s 1888 coastal oil. Design is not the installed window.',
2:'Brest woodcut impression dated 1895, inventory 972.33.1, Foucart gift acquired1971. Saved Pont-Aven primary record1996.12.1/96.13.4 describes its1996 gallery purchase, cream laid paper and red Bernard/dry Estampe originale stamps, dated1891–1892. Separate municipal collection histories and physical labels distinguish impressions. Brest dimensions are not assumed to be whole-sheet measurements; source chronologies are not harmonized.',
3:'1892 signed soft-ground copperplate impression on watermarked support; plate and total sheet measurements distinguish the object. Related composition reference is not a second addition.',
4:'1904 large tracing-paper sanguine/gouache/chalk study mounted on board, for the Quatuor decoration. Other Denis maternity and ceiling studies are different subjects/supports.',
5:'1890 ink/gouache boy’s head on 17.5 × 12.5 cm board with CF monogram; same-title Picasso, Moreau and Ingouf works have different makers/media/sizes.',
6:'Brest 1894 etching impression 2013.0.84 has 45.5 × 62.8 cm total sheet and the Seguin inscription. The other museum’s 1999.15.1 sheet is 38.6 × 56.7 cm; distinguish physical impressions of the same composition.',
7:'One1892 Les Fossiles programme lithograph,23.7 ×31.9 cm, Verneau imprint, Brest984.23.1 municipal purchase1984 and19–20June1984 Boutaric/Sérusier auction stamp. Saved Cleveland primary record1989.108 describes a gift of Dr Gerard and Phyllis Seltzer; dimensions are absent. Separate institutional acquisition histories and Brest physical stamp support separate impressions, without inventing Cleveland measurements.',
8:'Notre-Dame de Châteaulin sheet, second quarter twentieth century, signed and monogrammed. Preserve the source monotype question mark; do not turn generic chapel titles by other creators into a match.',
9:'1898 crayon/pastel Calvaire, 44.4 × 30.8 cm, GL monogram. Barbey’s same-title record is a different creator.',
10:'Small 1903 coastal etching with verso date and distinct plate/sheet measurements; Maufra’s larger Morgat print, drawings and oils are different physical objects.',
11:'Signed and dated 1903 Concarneau boat-return impression, image 11 × 13.8 cm. Other Concarneau titles concern bay and Beuzec-Concq works.',
12:'1895 ink-and-wash frieze, 25.5 × 61.4 cm with PR monogram; one designed sheet, not a set of separate motifs.',
13:'1895 Paysanne au Pouldu etching, 18.4 × 8.6 cm image, with Brest mat label and source inventory. Other Seguin landscape prints differ in subject and format.',
14:'Signed 1893 pastel/gouache Bretonne sheet, 43.2 × 27.3 cm; other artists’ same-title works remain separate.',
15:'Marguerite Sérusier crayon/pastel sheaves, first half twentieth century. Do not assign to Paul Sérusier or merge with his 1919 oil of threshers.',
16:'Signed 1890 Verkade gouache on board with three cows; preserve drawing classification from source domain. Bernier’s same-title oil has different maker/support.',
17:'Signed 1887 apple-harvest watercolour/crayon sheet with hand study on reverse; recto and verso count as one physical sheet.',
18:'Signed 1893 Bernard mezzotint/soft-ground impression on thin board; same-title anonymous seventeenth- and nineteenth-century oils differ physically.',
20:'1914 Nausicaa/Ulysses study in charcoal and chalk on paper mounted to canvas, 79.5 × 147.2 cm. It is the preparatory drawing, not the finished decoration.',
21:'1943 Cap Fréhel gouache model for one of five Rennes geology landscapes; Brest owns the model. Missing dimensions retained; finished Rennes decoration not imported.',
22:'Brest 1901 drypoint Moulin à Morgat 958.6.73, sheet 19.4 × 26 cm. Other museum’s Paysage à Morgat etching 1985.8.2 has 20.8 × 26.3 cm sheet and distinct accession; close composition alone does not identify the same physical print.',
23:'Signed 1928 Locronan charcoal/crayon preparatory drawing with colour annotations, distinct from the resulting colour engraving.',
24:'1943 Traouiros gouache model, signed and 45 × 86 cm, inventory 986.1.2. Distinct site/model in the Rennes commission; no Rennes holding or display claim.',
25:'1943 Pléchatel gouache model, inventory 986.1.3; preserve unknown dimensions. Distinct named landscape from the same commission.',
26:'1943 Le Boel gouache model, inventory 986.1.4; preserve unknown dimensions. Related commission does not collapse this individual model into another site.',
27:'Signed 1943 Camaret/Tas de Pois gouache model, 63 × 179.5 cm, inventory 986.1.5. Distinct physical panorama, not the installed Rennes decoration.',
28:'Inscribed Sainte Barbe woodcut sheet, explicit 1925–1935 range, 52 × 103.5 cm. Do not replace interval with an inferred single date.',
29:'Signed religious-procession print with literal circa 1930 statement, conservatively bounded by the separately supplied source period. Numeric source-ID prefix does not override current M0197 Brest identity.',
31:'One eighteenth-century ivory bas-relief, 20 × 11.2 cm, with anonymous maker retained. Same-title paintings and drawings differ in medium; historic catalogue numbers retained as aliases.',
32:'Allais mezzotint explicitly inscribed engraved 1791 after Callet’s 1775 royal portrait; retain print creation date separately from the model.',
33:'Signed Dunkerque watercolour, 32 × 48 cm, first half twentieth century. Antral’s Dieppe record depicts a different port.',
34:'Benoît Audran print after Le Brun, first quarter eighteenth century, paper sheet and publisher inscriptions retained. Garinet testament provenance does not override explicit current M0307 conservation and municipal holding.',
35:'1693 source-dated attributed Audran print after Coypel, 47 × 61.3 cm sheet. Philadelphia painting and Hermitage reversed copy are contextual models/versions, not this engraving. Attribution remains qualified.',
36:'First-half eighteenth-century Audran Granique print differs from Le Brun’s seventeenth-century Louvre painting by maker role, medium and 28.5 × 51.7 cm sheet.',
37:'1723 Audran etching after Garnier’s bronze, with Poilly design credit; source inscription distinguishes engraved 1723 from monument date 1718. Historical-number 686 collision with Hilaire’s 1952 shipyard oil is unrelated.',
38:'Seventeenth-century Bazin engraving after Dieu, Saint Louis holding crown of thorns. One measured paper impression; Bassel publishing inscription preserved.',
39:'1650 Bignon print after Heince/Vouet, one catalogued portrait sheet made for an illustrated volume. Nancy’s eighteenth-century Guibert version and Louvre oil model are different objects.',
40:'1652 Bolswert print after Jordaens, 37.5 × 48.7 cm sheet; source says figure order reversed relative to 1630 painting. Garinet entry number is historic provenance, not a present-venue assertion.',
41:'Eighteenth-century Bonnet three-colour crayon-manner Nymphe after Natoire; same-title oils have different artists and physical supports.',
42:'Bonnet paper portrait after Louis-Michel Van Loo, eighteenth century; portrait sitter birth 1710 is not creation. Large Carle Van Loo oil and school portrait remain distinct.',
43:'Boulanger printed portrait of Marie Angélique Arnauld, 25.7 × 18.9 cm. Distinct from Catherine Agnès portrait despite shared entry-register number 2239.',
44:'Boulanger print after Champaigne of Catherine Agnès Arnauld, 31 × 22 cm; individual inventory 926.5.4 and sitter distinguish the companion Marie Angélique sheet.',
45:'1628 Burani Bacchanales etching on laid paper. Preserve source’s repeated height label in measurements rather than silently inventing a width; Fragonard set and Boucher-school oil differ.',
46:'Callot signed Pont Neuf/Porte de Nesle etching, seventeenth century, 18.5 × 35.5 cm sheet and smaller plate measurements retained.',
47:'1787 Carré print after Le Barbier of Louis XVI, 61.3 × 43.7 cm; distinct from royal oils. Short historical number 55 collides with Bernay’s Devéria landscape, different full inventory, medium and title.',
48:'Arts attributes oil on canvas, first quarter seventeenth century, 93 × 123 cm. Cerquozzi attribution remains qualified and original Michel Ange des Batailles label retained.',
49:'Chedel print of the devout hermit after Boucher, eighteenth century; model creator remains an after-credit, not an assigned painter authority.',
50:'Cochin Retour de campagne engraving after Watteau, 37.2 × 46 cm sheet. Inscription identifies the model and print publisher; preserve separate physical print identity.',
}
INVENTORY_EXCEPTIONS={37:{'e6dfd8e3-80a1-4be4-b438-19995bef7cf1'},47:{'6a672e97-cf23-4cce-aaf8-29b9bffc4ef2'}}
UNTITLED_EXCEPTIONS={}
QUALIFIED={}
HOLDS.update({
73:'Same-title same-maker sparse existing record bf2e4a46-d92a-4839-aaf8-d7ee4fd50b4b may be this Gael painting; resolve source object identity before adding.',
77:'Large ten-section assembled Ghisi print has de Rubeis publishing inscription. Reconcile the physical impression edition/date against the headline 1545 plate date before adding; do not count ten components separately.',
93:'Inventory explicitly groups parts 1 and 2 while description gives one print. Resolve whether two impressions, components or an original accession alias before counting.',
})
NOTES.update({
51:'Signed Colin burin portrait of bishop Vialar, seventeenth century, 33 × 26.5 cm sheet; distinct from Lombart’s larger mezzotint of the same sitter.',
52:'Eighteenth-century Daullé Racine etching, 12.9 × 8.4 cm image. Individual inventory 926.5.24 retained despite shared entry-register number.',
53:'Demarteau satyr print in black/red/beige crayon manner plus etching, one 15.5 × 21.2 cm sheet, eighteenth-century source period.',
54:'Signed Descourtis Rixe aquatint/etching after Taunay, 35.3 × 24.3 cm. Traversi’s same-title work has a different maker and source identity.',
55:'Desrochers signed/dated 1699 burin portrait; sitter’s 1692 death in the inscription is not the print creation date.',
56:'First-half eighteenth-century Desrochers Le Maître print after Champaigne, 16.2 × 12 cm; different maker, date and size from Lubin’s seventeenth-century portrait.',
57:'Small seventeenth-century Donck Clovis print, 12.9 × 8.9 cm; same-title large oils and later Lacaze drawing are different physical objects.',
58:'Drevet burin portrait of Lecouvreur after Coypel, distinct from painted models, Grateloup reduction and other states discussed in source. Short number 46 matches an unrelated Constable landscape catalogue number.',
59:'Signed and dated 1723 Drevet Bossuet engraving after Rigaud; Louvre inv.7506 is the painted model, not this paper object.',
60:'Eighteenth-century Drevet Mailly engraving after Carle Van Loo; original source roles retained. Other Van Loo family/Choiseul portraits have different sitters.',
61:'Signed and dated 1734 Dupuis Leçon d’amour print after Watteau; engraved reproduction remains a distinct physical paper object from its model.',
62:'Earlom mezzotint after Mengs through Seydelmann design, 66 × 49.4 cm sheet. Preserve second-half eighteenth-century period and 1784 publication inscription as evidence, without silently narrowing the source date.',
63:'Seventeenth-century Edelinck Antoine Arnauld portrait after Jean-Baptiste Champaigne; sitter birth/death dates are inscription context, not invented creation endpoints.',
64:'Edelinck Sainte Marthe portrait after Jouvenet, 20 × 15.1 cm sheet; shared accession-register number does not merge distinct 926.5-series portraits.',
65:'Large Edelinck Saint Louis print after Le Brun, 56.2 × 41.2 cm, distinct from Fragonard’s small pen-and-wash same-subject drawing.',
66:'Edelinck portrait after Le Febvre, 30.6 × 22.5 cm paper; retain literal maker spelling and model credit without new artist authority.',
67:'Seventeenth-century Edelinck Le Tellier print after Mignard with 1692 inscription. Mignard’s portrait model remains a separate medium/object.',
68:'Signed 1757 Fessard Adoration des bergers burin after Natoire, 52.1 × 28.2 cm sheet; not the differently titled Adoration des Rois print.',
69:'Signed and dated 1750 Fessard sleeping-nymph engraving after Carle Van Loo, separately measured sheet and plate.',
70:'Signed 1777 Flipart Gâteau des rois print, Châlons 970.5.41, 56.3 × 66.5 cm sheet. Existing 676 CD/Joëts126 impression measures 57.5 × 68 cm and has distinct collection provenance.',
71:'Flipart shipwreck print dated 1771 after Vernet’s 1764 painting, 57.5 × 74.7 cm sheet. Old number 564 belongs to unrelated Hilaire 1936 Maison italienne oil in another catalogue.',
72:'1722 Freij engraving after the Reni ceiling fresco, 43 × 88.1 cm image; not the architectural painting. Number55 collision is Bernay’s unrelated Devéria oil.',
74:'Gaillard Joly de Fleury portrait after Didier, eighteenth-century paper print. Preserve unusual literal plate measurements and sitter dates without repairing them by guess.',
75:'Galle Immaculée conception paper print with separate sheet/plate measurements and first-half seventeenth-century source attribution/date. Retain literal support description, without inventing edition or state.',
76:'Galle Fathers of the Church print after Rubens with Hendricx imprint, first half seventeenth century. One measured paper impression, not the painted model.',
78:'Anonymous nineteenth-century prison-interior oil in the manner of Granet; 30 × 25 cm wood panel, not Granet’s church-interior painting. Qualification retained.',
79:'Green Roman Charity mezzotint after Van der Werff, eighteenth century with 1785 publisher inscription. Other same-title oils and Ingres drawing differ in medium and creator.',
80:'Attributed Heda seventeenth-century still life on 58 × 46 cm wood panel. Preserve both 2008 title variants, former Aefse/Deheem attributions and comparison to Strasbourg; no attribution upgrade.',
81:'Current source names Horthemels Louise-Magdeleine with lifespan, differing from old index role label. Signed Port-Royal cloister print remains eighteenth century; current literal label retained.',
82:'Jardinier Le Gros portrait, third quarter eighteenth century. Sitter death1751 is not substituted for creation; 42.8 × 28.4 cm sheet retained.',
83:'Signed Kilian Dampierre portrait, seventeenth-century burin sheet 18.5 × 12.7 cm; biographical lettering identifies sitter rather than a new date.',
84:'Larmessin II Colbert/Maulévrier portrait, seventeenth-century laid-paper burin; retain generation II and widow Bertrand publishing imprint.',
85:'1835 impression of Le Pautre’s copperplate on sycamore veneer made through Charles Picot’s printing experiment. Source description establishes later impression separately from historic plate maker; object-level label qualified accordingly.',
86:'Attributed Leblanc crayon-manner academy after Bouchardon, 49.6 × 36.8 cm paper. Uncertain/illegible signatures retained, attribution not promoted.',
87:'Signed and dated1612 Jean Leclerc Joan of Arc print, 16.3 × 11.8 cm; inscription Le Clerc le Jeune retained as source evidence.',
88:'Large Loir Saint Michael/Fall of Rebel Angels print after Le Brun, distinct from source-model oils. Number188 collisions concern Brebiette’s Proserpine oil and Keirincx forest; full inventory and medium distinguish all.',
89:'Lombart mezzotint Vialar portrait after Nanteuil, 40.3 × 32.3 cm sheet; distinct from Colin’s smaller burin sheet in this batch. Unknown Lombart identity is not reconciled to Pierre Lombart.',
90:'Signed Lubin Le Maître portrait, second half seventeenth century, 28.1 × 22.2 cm sheet; distinct from Desrochers’s later smaller sheet.',
91:'Attributed La Touche-Loisy pastel after Drouais, paper mounted on canvas, 64 × 53 cm. Chardin’s same-title work and Boizot engraving are different objects/versions.',
92:'Signed and dated1790 Malbeste Martinet etching, 17.7 × 8.7 cm. Labadye and Voyez signatures retained in evidence; depicted Assembly1789 and sitter birth1753 are not creation.',
94:'Small wooden Troy-fire painting in the manner of François de Nomé, first half seventeenth century; larger same-title oils differ. Short number239 collides with Bourdon’s round Holy Family canvas.',
95:'Montcornet Barberini portrait, seventeenth-century burin on laid paper, 24.6 × 18.3 cm; preserve literal publishing/signature text.',
96:'Montcornet Brulart print after Dumonstier with Daret imprint; retain source sheet/plate measurements even though recorded plate height slightly exceeds sheet height, with no invented correction.',
97:'Edmé Moreau Bergier portrait, one seventeenth-century paper sheet with text on reverse. Verso literary inscription is not a second artwork.',
98:'Morin Robert Arnauld portrait after Champaigne, first half seventeenth century, one paper impression. Champaigne’s later painted portrait is not this engraved sheet.',
99:'Signed and dated1650 Nanteuil Blondel burin print; 1614 biography event stays separate from creation.',
100:'Natalis Jeanne de Valois engraving on parchment, seventeenth century, after Diepenbeeck with Van den Enden printer credit. Sitter death1505 is contextual, not creation.',
101:'Signed Joseph Navlet Bastille Day watercolour/gouache sheet, explicit1882–1889 range; retain range and distinct inventory2009.1.1.',
102:'1873 Victor Navlet pencil/white study on prepared canvas, 131.5 × 196 cm. Description distinguishes1866 painting and Pannini1730 model. Historical number575 collision is Hilaire’s unrelated1937 orchard oil.',
103:'1885–1888 conference-room oil begun by Victor and completed by Joseph Navlet; source explicitly explains sequential participation, so both literal creator labels remain.',
104:'One1787 Mewloud engraving sheet, with later1896 annotation disputing Née’s signature in favour of the Varin brothers. Preserve dispute in qualified object label and evidence; annotation date is not creation.',
105:'1775 Née Châlons town-hall-square print after Lallemand, separately measured sheet/plate and PV stamp. Model maker remains an after-credit.',
106:'Eighteenth-century Nonnotte Moses oil, 46 × 55 cm canvas. Retain spelling variants;1944 lining/restoration inscription does not date creation.',
107:'Signed1716 Pitau Quesnel paper engraving; sitter birth1634 stays biographical evidence.',
108:'Poilly Reims cathedral print after Gentillastre, eighteenth century. Both1718 and1728 architectural inscriptions retained without choosing a fabricated exact creation year.',
109:'Signed Regnesson Buridan portrait, seventeenth-century paper print with separate sheet/plate measurements.',
110:'Anonymous seventeenth-century oil copy after Reni, 60.8 × 51.5 cm canvas; Kassel original and Edelinck engraving are related versions. Other same-title works have different makers/supports.',
111:'Attributed Rottenhammer Adoration on106.3 × 77.5 cm canvas. Source distinguishes Verdun’s Palestra version on wood; former Francken attribution retained, and smaller Francken copper painting is distinct.',
112:'Signed1698 Roullet portrait of Colbert/Villacerf,60.5 × 44.5 cm paper. Distinct sitter/title from Larmessin’s Colbert/Maulévrier print.',
113:'Anonymous sixteenth-century Little Holy Family copy after Raphael on32.5 × 24.5 cm wood panel; after-credit and alternate subject titles preserved.',
114:'Small Saint-Aubin Louis XIV print,13.2 × 12.4 cm sheet, second half eighteenth century. Other1779 impression has larger22.8 ×15.6 cm sheet/21.8 ×14.8 cm plate; Rigaud oil is a different medium.',
115:'Attributed Nicolas de Son Saint-Nicaise facade etching,42.5 ×27.5 cm sheet,17th-century source period,980.12.14. Source records physical entry1980 as Jean Faguier private-collection gift to Châlons. Saved NGA primary record6540 is accessioned1943.3.3422 in the Rosenwald Collection and dated1625, with no dimensions. Distinct collection provenance supports separate impressions; do not transfer the NGA exact year or unqualified maker to this attributed sheet.',
})
INVENTORY_EXCEPTIONS.update({58:{'0c749b8f-0e5e-4c22-a5b1-b24940c4faec'},71:{'4dc11562-484d-4858-9aac-96c461ca4e02'},72:{'6a672e97-cf23-4cce-aaf8-29b9bffc4ef2'},88:{'09f3af3e-32fa-498d-9d3a-20f98bcd6554','7e7014ef-7cc3-4b81-8fe0-9b247d084ede'},94:{'1392041b-d33c-4af5-a870-d9ffa5e54ec3'},102:{'25c47e79-9022-44fc-a55f-432a64975292'}})
QUALIFIED.update({85:('LE PAUTRE Jean (graveur de la plaque; impression de 1835)','Description'),104:('NEE François Denis (signature de graveur contestée par une annotation en faveur des frères Varin);COCHIN Charles Nicolas (d’après)','Historique')})
HOLDS.update({
120:'Medium/description identify a lithograph while history describes a Fiorini copper engraving after a lithograph. Reconcile the physical version before treating the generic Paysage record as a new object.',
131:'Cover inscription describes a series of six etchings under one inventory. Physical portfolio/components require unit reconciliation.',
136:'Cantiques record cites a signed colophon page and related sets86.7.2/3; establish whether a book, suite or single image before counting.',
141:'Two sparse existing Reichel Composition records with unverified dates have no physical descriptions. The newly dated1929 sheet is not safely distinguishable from all existing generic records yet.',
158:'Source lists twelve sheet measurements and a signed colophon. This is a multi-sheet Cantiques grouping requiring component/whole reconciliation.',
159:'1957 dated Reichel Composition sheet cannot yet be excluded from two sparse same-maker same-title records with unverified dates; hold for physical-source comparison.',
167:'Cantiques record cites signed colophon and related86.7.1 without identifying an individual image. Resolve suite/book unit before adding.',
})
NOTES.update({
116:'Signed1945 Bazaine Pommiers watercolour; literal inconsistent image/sheet orientation measurements retained. Intermunicipal Metz ownership accepted only through exact-code context.',
117:'Signed/dated1965 Bertholle drypoint no.107, numbered4/25,9.7 ×11.4 cm plate. Distinct from no.111 Calvaire and1966 Paysage.',
118:'1958 Rose colour etching on BFK, signed Bissière and numbered37/60; Fiorini and Leblanc source credits retained. Same-title unrelated makers excluded.',
119:'Bleue colour etching/aquatint,16/75,explicit1962–1963 range. One measured sheet, with full printer label retained.',
121:'1956 Octobre lithograph120/150 after the1955 oil-on-paper composition identified by the source. Existing1955 October record is model context, not this numbered printed impression.',
122:'1921–1922 Braque Nature morte III artist proof on China paper, Metz75.9.1 acquired1975 from Robert Prouté. Saved Dieppe primary record973.20.2/4804 describes Arches paper, Laurens1973 donation and Braque workshop stamp; different support and provenance distinguish impressions. Literal Charlot label/lifespan anomaly remains source evidence; no creator authority reconciliation.',
123:'1970 Chillida Leku III etching7/50 is at the inclusive cutoff.1984 accession does not date creation; Arte/Maeght credits retained.',
124:'1927 Cournault Jeanne la Fole zinc etching2/50, individually inventoried plateVI; suite membership is context, not an added complete portfolio.',
125:'1856 Fleury oil study of two named sitters, inscription distinguishes creation1856 from gift1902. One catalogue canvas, no invented second portrait.',
126:'Signed1927 Foujita graphite/stumping drawing with slight red highlights, one paper object; preserve factual-title status and literal Tsuguharu label.',
127:'1951 Friedlaender yellow-fish etching61/220 with Guild dry stamp and BFK support; named printer/publisher retained.',
128:'Signed1970 Giguet colour monotype on crumpled paper,85.5 ×60 cm. Creation is eligible at cutoff, despite artist’s later death.',
129:'Signed1956 Hamue sunflower oil. Source explicitly corrects the painted reverse number1721 to inventory1722; retain both evidence and actual catalogue inventory.',
130:'Attributed van Helmont Flemish kermesse canvas120.2 ×172.7 cm. Former Michau attribution searched and preserved, with no attribution upgrade.',
132:'Signed1961 Le Moal Garde-Freinet watercolour29.5 ×28.3 cm; one individually catalogued sheet.',
133:'1953 Léger Constructeurs aquatint with screenprinted colour, trial proof dedicated to André Baron. The1949 gouache and other preparatory works have different medium/size/date.',
134:'1956 Manessier Holland no.3 artist-proof colour lithograph,29 ×23.8 cm sheet. Title and verso proof description identify one image.',
135:'1958 Cantique lithograph65.5.2,50 ×38 cm sheet/33 ×25.5 cm image, seller number2345. Individual sheet distinguished from companion prints and held colophon-bearing suites.',
137:'Signed1958 Manessier Route lithograph31/90,76 ×101.5 cm sheet; same-title records by other makers differ.',
138:'Signed1950 Minaux chair/coffeepot lithograph173/200 with Guild stamp, one sheet with alternate catalogue titles preserved.',
139:'Signed1962 Prassinos Automne artist proof, Lacourière stamp, etching/aquatint/burin. Source’s preparatory-drawing relation does not change this physically described print to a drawing.',
140:'Signed1952 Prassinos crow impression122/200 on Marais paper. Preserve question mark on fourth/final state, without declaring an unqualified edition state.',
142:'Signed1965 Reuter reclining-nude monotype with gouache highlights,48.3 ×65.3 cm sheet; source classifies printed support rather than an oil canvas.',
143:'Rolland pastel self-portrait outdoors, first half nineteenth century,52 ×43 cm image. Description’s portfolio is a depicted prop, not a physical multi-work album.',
144:'1926 Rouault Verlaine lithograph on Vollard-watermarked paper,61.9 ×47.5 cm sheet. Existing1933 print is larger and separately inventoried; uncertain fourth-study label retained.',
145:'1926 Rouault clown lithograph30/50, fourth state, with Frapier/Galerie stamp and distinct verso annotations. Missing frame measures stay unknown.',
146:'1936 Rouault Christ/Mammon black aquatint on Montval paper,45 ×34 cm sheet, Metz66.6.9 acquired1966 from Robert Prouté. Saved NGA primary record39488 is accessioned1950.17.257 Rosenwald Collection trial proof; its measurements are missing. Distinct acquisition provenance supports separate impressions. Metz source says one graphite name is not artist’s signature; preserve that limitation and do not invent edition numbers.',
147:'Signed Metz1853 Sturel-Paigné flower pastel; current hexagonal mounting differs from former oval frame. Count the single pastel, not two framed versions.',
148:'Signed1963 Trum landscape in watercolour/ink/crayon,47 ×65 cm sheet; generic Paysage titles by different makers do not establish a duplicate.',
149:'Signed1955 Ubac Arbres et pierres II colour lithograph57/150,56 ×38 cm sheet; retain series numeralII as identity.',
150:'Seventeenth-century misers canvas44.2 ×54 cm, inventory11429. Source history explicitly qualifies attribution to Gillis van Tilborch; conflicting Egidius/lifespan label retained in raw evidence, without asserting joint authorship.',
151:'1959 Vieira da Silva blue screenprint19/120 on rag paper; one greeting-card impression,19 ×26.1 cm image. Other edition counts are contextual, not separate additions.',
152:'Signed1960 Villon crane landscape oil/ink canvas60 ×92 cm.1959 discussion and series context are background; visible1960 signature/date supports this object.',
153:'Signed1946 Bazaine Bataille watercolour,49 ×32 cm, distinct subject/date/inventory from1945 Pommiers.',
154:'Signed1965 Bertholle no.111 Calvaire drypoint6/17,5 ×8.2 cm plate. Distinct from no.107 and other works named Calvaire.',
155:'1927 Cournault Embarras de Paris zinc etching2/50, plateV, BFK sheet; distinct subject/inventory from plateVI Jeanne la Fole.',
156:'Signed1949 Le Moal Archéologie orientale print14/25, direct acid/burin,17.8 ×8.5 cm plate; one sheet.',
157:'1958 Cantique65.5.3, numbered19/125,50.4 ×38.2 cm sheet/34 ×27.5 cm image and seller2346; distinct from65.5.2/4/5 sheets.',
160:'Signed1970 Reuter Fleur colour lithograph on zinc,32.5 ×25 cm paper; cutoff eligible. Vien’s eighteenth-century watercolour is a different medium/creator.',
161:'Signed1932 Rouault Christ-on-cross lithograph trial proof on Japan laid paper with Frapier SE mark.1936 aquatint comparison differs in medium/format/date.',
162:'1956 Villon ink/crayon sheet explicitly contains two Christ studies on one physical sheet; count once. Window commission and related sheets are not extra records.',
163:'Signed1966 Bertholle Paysage drypoint6/15 on BFK,28 ×38 cm sheet. Illustration for Lescure’s book is one independent catalogued print, not the whole book.',
164:'1936 Cournault Amour manchot etching3/5 artist proof with suite title Méandres. One plate/image, not an entire suite.',
165:'Signed1951 Le Moal Blé artist proof, direct acid on steel,32.7 ×25 cm BFK sheet; source medium retained as print.',
166:'1958 Cantique65.5.4, signed19/125,50.3 ×37.5 cm sheet/33.5 ×25.5 cm image, seller2347; distinct physical sheet from neighbouring accessions.',
168:'Signed1956 Villon Paschal Lamb ink drawing on paper,27 ×20.9 cm. Distinct from83.29.4 tracing-paper variant; design is not installed stained glass.',
169:'Signed1960 Bertholle untitled gouache,36.5 ×53.8 cm sheet; generic title retained without inventing subject.',
170:'Signed1951 Le Moal bird burin16/30,9.9 cm square plate on25.2 ×33 cm BFK paper; distinct from Blé and Archéologie orientale.',
171:'1958 Cantique65.5.5,50.1 ×37.8 cm sheet/34.5 ×26 cm image, seller2348; separate inventoried image, not duplicate ingestion of full suite.',
172:'Signed1956 Villon Paschal Lamb on tracing paper,26.6 ×27 cm, distinct from narrower paper drawing83.29.3.',
173:'1943 Villon chimney/hunting-horn print8/45 on Lana paper,24.3 ×38 cm sheet. Distinct inventory/title; inscriptions preserved.',
174:'Signed1939 Villon Effort/Drame etching/burin20/50,49.5 ×32 cm sheet; alternate title describes same impression, not two works.',
175:'1951 Villon Signature self-portrait etching23/50, final state with date/signature engraved.1959 catalogue-cover reproduction is later use, not creation.',
})
QUALIFIED[150]=('Gillis Van Tilborch (attribué à)','Historique')
HOLDS.update({
184:'Sparse existing Jouanny Arbres et rivière73f6304a-8c61-4224-b867-e16d31499b18 could be this panel or candidate231. Reconcile before adding; diptych relation also preserved.',
188:'Headline attributes the painting to Teniers, while reverse inscription says after Teniers. Resolve creator/version qualification rather than silently asserting an original.',
201:'Source explicitly questions restrike versus photogravure.1889 may date original plate rather than this physical reproduction; hold chronology/version.',
212:'Existing sparse Jouanny Rochers à Saint-Raphaël8a9b796a-2405-4d80-91b0-24a9c6b3e6dc may correspond to this or candidate223. Hold both pending reconciliation.',
218:'Source explicitly says possible restrike and gives1885 without a bounded later-impression date. Do not silently equate plate chronology with physical print.',
223:'Possible duplicate of sparse Jouanny Saint-Raphaël record; cannot choose between933.1.32 and933.1.33 without further physical evidence.',
231:'Possible duplicate of sparse Jouanny Arbres et rivière record; cannot choose between this canvas and candidate184 panel from title alone.',
238:'Sparse existing Jouanny Paysage e1d31461-d415-46cb-883f-47f9b2d8dc9b may be this canvas or other same-title candidates. Physical reconciliation pending.',
245:'Possible match to sparse Jouanny Paysage record; wooden support distinguishes known1885 canvas but not the uncharacterized record.',
250:'Possible match to sparse Jouanny Paysage record; cardboard support distinguishes known1885 canvas but not the uncharacterized record.',
257:'Source assigns fourth-quarter nineteenth-century Vaucanu drawing but dedication reads11June1910, after maker death1896. Clarify later inscription versus misattribution/date.',
})
NOTES.update({
176:'1791 decorated faience plate,22 cm diameter, Fidelitas/pax/concordia legend. Unknown maker retained. Related866.1.246 is not this independently inventoried object.',
177:'Attributed Atalaya Vase ink drawing19 ×16 cm,991.2.257. It depicts a vessel; it is not itself a ceramic. Distinct from smaller attributed and signed sheets.',
178:'Attributed Atalaya Vase ink drawing15.5 ×10.5 cm,991.2.253; separate sheet from991.2.257 and991.2.251, despite generic title.',
179:'Signed Atalaya Medici-plate ink drawing14.5 ×15.5 cm, distinct from printed reproduction991.2.216. Short number12 collision belongs to Goyen’s Dordrecht oil.',
180:'Attributed Brouwer Dentist oil on25 ×31.5 cm wood panel. Short number15 collision concerns an eighteenth-century after-Brouwer inn scene with a different full inventory, subject and size.',
181:'Bon D. ewer ink drawing27.3 ×16.6 cm; instruction to make a15 cm printing block is not the drawing size. Uncertain maker lifespan retained.',
182:'Attributed Dou injured-hand oil on34 ×26 cm wood panel, seventeenth century. Qualified creator remains object-level label.',
183:'1795–1800 reptile-fright canvas41.5 ×33 cm, separately inventoried from storm companion. Girodet attribution is explicitly doubted in source with Sablet comparison; qualify label, preserve old provenance and do not promote either maker.',
185:'Seventeenth-century glazed terracotta oval dish33.6 ×25.5 cm in Palissy manner/school. Same-title Whistler and Callot prints are different media; no Palissy autograph claim.',
186:'Signed Rico crowned-lion object ink drawing19 ×14 cm; the represented lion object is not a sculpture acquisition.',
187:'Attributed Selles nineteenth-century Swiss-guard canvas36 ×21 cm; alternate subject title retained. Short number9 collision concerns Migette’s large1846 Metz procession oil.',
189:'Initialled V.N. Moulin de Côtes graphite sheet27.3 ×34.5 cm; former Vaucanu attribution remains evidence, no identity invention. Short number55 collides with Devéria’s unrelated oil.',
190:'Attributed Vassé eighteenth-century marble child bust,31 cm including11 cm base. One sculpture; short catalogue46 collision is Constable’s unrelated landscape.',
191:'Attributed Vaucanu Manoir de Bernay graphite sheet22.5 ×29.5 cm; location question mark retained. Short number50 collision is Coypel’s large Jesus oil.',
192:'Vaucanu woman/horse on Île de Ré watercolour31 ×23.5 cm, fourth-quarter nineteenth century; doubtful preliminary inventory450 retained literally.',
193:'Vaucanu Danse macabre ink/wash after Rosa,17 ×27 cm, fourth-quarter nineteenth century. Rosa inscription is model credit, not creation by the seventeenth-century painter.',
194:'Vaucanu Milon print after Normand/Mérimée, fourth-quarter nineteenth century.1807 publication belongs to model context; one measured paper impression retained.',
195:'Seventeenth-century pedicure oil after Victoryns, formerly Brouwer. Support is uncertain wood versus copper in source and remains literal; not Degas’s1873 paper work.',
196:'Signed1893 Vaucanu sheep-keeper etching, limited28 impression inscription. Depicted/related bas-relief does not convert the catalogued paper print to sculpture.',
197:'Late-nineteenth-century Vaucanu Mérimée etching after Ingres1820. Model date is not print date. Number158 collision is unrelated Ingres tracing of antique weapons.',
198:'Vaucanu woman portrait trial proof explicitly first state,30.5 ×22.2 cm sheet,991.2.183; source links another physical impression991.2.184 rather than a duplicate source identifier.',
199:'1887 Vaucanu Chevreul-at-work proof before letters,27.4 ×22 cm sheet,991.2.147. Source names Félix Nadar but history says Paul’s1886 photograph; preserve explicit uncertainty in model-maker label. Separate from991.2.244 and156 impressions.',
200:'Signed1887 Vaucanu Pithiviers ruins etching after Ravaut circa1800; retain separate model and print dates,24 ×34.9 cm sheet.',
202:'Attributed Wouwermans seventeenth-century cavalry duel on38.5 ×30 cm wood panel. Source label spelling and qualified attribution retained; depicted wars do not define a new precise year.',
203:'Anonymous seventeenth-century double portrait on97.5 ×87.5 cm canvas. Proposed Navarre provenance remains tentative; short number1 collision is Migette’s1863 Metz history painting.',
204:'Vaucanu late-nineteenth-century printed Selim tomb view after anonymous model,30 ×21.5 cm sheet. One catalogued image; depicted historical subject is not creation.',
205:'Anonymous watercolour caricature datedAugust1862,17.3 ×24.2 cm. Former Vaucanu attribution is rejected by current anonymous source label and preserved in evidence.',
206:'Signed1888 Vaucanu Bosvieux etching after unnamed photographer, first-state inscription,29.5 ×19.7 cm sheet. Photography is model context; physical object is print.',
207:'Anonymous late-seventeenth-century Mancini oil after Egmont1654, formerly Mignard.92 ×75 cm canvas differs from the related La Trémoille double portrait. Literal erroneous-looking récolement number remains uncorrected.',
208:'Anonymous first-half eighteenth-century blue faience plate25 cm, woman beating husband. Glaze number14 is source series mark, not a creation date.',
209:'Attributed Atalaya tobacco-pot ink drawing17.5 ×10.5 cm; the depicted object does not change its drawing type.',
210:'Signed Atalaya circular-plate ink drawing16.5 cm square, distinct subject/inventory from Medici plate sheets.',
211:'1795–1800 storm-fright canvas, companion to reptile-fright with different inventory. Source doubts Girodet and compares Sablet; preserve contested attribution and distinguish pendant works.',
213:'Attributed Vaucanu female portrait graphite sheet20.5 ×15.5 cm, fourth-quarter nineteenth century. Generic title remains; no invented sitter.',
214:'Vaucanu Turreau barracks gouache21 ×27 cm, image17.3 ×23 cm; distinct named Bernay view.',
215:'1888 Vaucanu farm-interior etching991.2.192,27.5 ×36.4 cm sheet.1891–1892 competition explains later title; related other impression is not included automatically.',
216:'Vaucanu female portrait print991.2.184,26.7 ×22 cm sheet with maker/model signatures, separately identified by source as other impression of991.2.183 trial proof.',
217:'1887 Chevreul proof with added wash,23.5 ×18 cm sheet,991.2.244, distinct from147/156.1886 image date is consistent with model-photograph year described in related source. Nadar model-creator name/lifespan discrepancy remains explicit; no authority assignment.',
219:'Anonymous seventeenth-century inn-interior oil on23.5 ×32.5 cm wood, distinct from Boggs gouache and Horemans canvases. Short number16 collision is Gros’s large1817 royal portrait.',
220:'Late-nineteenth-century Vaucanu print after anonymous sixteenth-century Constantinople model. Inscribed1537 is depicted/model year, not actual paper print creation.',
221:'Anonymous1792 three-orders faience plate22.4 cm with L’UTILITE inscription; distinct from1791 Latin-legend plate and later design variants.',
222:'Atalaya printed Medici-plate illustration12 ×15.5 cm,991.2.216; distinct from14.5 cm-high ink drawing991.2.248. Museum owns image sheet, not the represented Davillier porcelain.',
224:'Attributed Vaucanu beggars ink drawing25.5 ×15.5 cm; same-title anonymous seventeenth-century wood oil is a different object.',
225:'Signed Vaucanu Rue de Bernay ink drawing22.5 ×29.5 cm with separately measured image; one original paper sheet.',
226:'Vaucanu girl/dog etching991.2.186,29.7 ×45.7 cm sheet; source distinguishes other impression/stage. Boldini oil and short126 Brebiette inventory collision are different objects.',
227:'Monogrammed1888 large Chevreul portrait print57.5 ×40.7 cm, distinct from smaller portrait234 and table-at-work impressions. Short188 collisions concern Brebiette and Keirincx oils.',
228:'Anonymous seventeenth-century St Paul/Damascus oil68 ×92 cm, formerly Guaspre Poussin. Prior attribution searched; Abbey of Bec label retained without asserting a present holding there.',
229:'Anonymous1790 three-orders faience plate22.8 cm with VLR inscription.1789 political context is not creation; different inscription/dimensions/inventory from other plates.',
230:'Signed Atalaya Vase ink drawing16 ×13 cm,991.2.251; separate from larger177 and narrower178 sheets. Short16 inventory collision is Gros’s royal canvas.',
232:'Late-nineteenth-century Vaucanu printed siege-of-Algiers copy,31.5 ×23.3 cm sheet with dry stamp.1534 is subject/model date. Possible extracted-book origin retained; current object is one loose catalogued sheet.',
233:'Vaucanu seated-woman etching991.2.171,23.2 ×18.4 cm sheet; source explicitly links a separate impression991.2.240 with different sheet measurements.',
234:'Smaller Vaucanu Chevreul print37.6 ×25.7 cm sheet/29.5 ×20.7 cm plate,991.2.149; physically distinct from57.5 cm sheet227 and table portraits.',
235:'Anonymous nineteenth-century marine on21.5 ×40.5 cm wood,887.2.95. Source identifies887.2.96 as a related separate panel; comparison to Morez/Maons is not an attribution assignment.',
236:'Anonymous1791 three-orders plate22 cm with VIVE LA NATION legend and petit-feu decoration. Different decoration/inscription/inventory from the same-size grand-feu Latin-legend plate176.',
237:'Signed Atalaya friendship-goblet ink drawing23 ×19 cm,991.2.252. Distinct from print991.2.214 and the other goblet design249.',
239:'Vaucanu print of an uncertain Algiers street,31.6 ×23.4 cm sheet; possible extracted-book origin and uncertain place kept literal.',
240:'Vaucanu seated-woman impression991.2.240,28 ×19.8 cm sheet; source links other impression991.2.171, not a duplicated source record.',
241:'Signed1887 Chevreul-at-work impression991.2.156,27.5 ×18.5 cm sheet, distinct from147/244. Nadar model credit discrepancy retained as uncertainty rather than resolving a photographer authority.',
242:'Anonymous nineteenth-century marine panel887.2.96, matching format of companion887.2.95 but separately catalogued and cross-referenced as another work. Do not merge pendant panels by dimensions alone.',
243:'Anonymous1793 decorated faience plate24.7 cm with fasces and union motto, distinct from three-orders variants. Depicted emblem supports artwork selection through documented museum holding.',
244:'Signed Atalaya sugar-bowl ink drawing16 ×12.5 cm; type is drawing of vessel, not ceramic vessel.',
246:'Vaucanu Saint-Denis-d’Augerons ink drawing12.5 ×19 cm with title and intertwined initials. Preserve source transcription of monogram without inventing expanded signature.',
247:'Vaucanu Vassivière fountain etching991.2.300,35.9 ×25.7 cm sheet. Referenced other impressions128/129 not automatically counted.',
248:'Anonymous dancer graphite/highlight sheet30 ×20.5 cm, formerly Vaucanu. Current anonymous label retained; former maker included in comparison.',
249:'Signed Atalaya goblet ink drawing24 ×16.5 cm,991.2.258, paired with printed991.2.215. Short25 collisions are unrelated Le Lorrain/Perronneau oils.',
251:'Vaucanu cemetery/death-game ink drawing20 ×31 cm. RAPHAEL inscription retained as unresolved model/inscription context; no Raphael authority assigned.',
252:'Signed Vaucanu Tanger etching28.5 ×44.5 cm; Delacroix’s small1832 same-title watercolour is physically distinct.',
253:'Atalaya goblet print21 ×16 cm,991.2.215, distinct from24 ×16.5 cm original ink drawing249 and friendship-goblet print256.',
254:'Vaucanu Beaumont-le-Roger abbey ink/watercolour18.5 ×26 cm; source calls related records other views, not copies of this record.',
255:'1891 Vaucanu Constantinople-street etching35.5 ×55 cm, documented competition context. Related portrait/drawing is not imported as this physical impression.',
256:'Atalaya friendship-goblet print21 ×17.5 cm,991.2.214, distinct from ink drawing237 and other goblet print253 by inventory/design/size.',
258:'Vaucanu mosque/street etching991.2.61,49.2 ×37.5 cm sheet; uncertain Bayezid identification retained. Source explicitly identifies991.2.62 as another impression.',
259:'Vaucanu siege-of-Algiers ink drawing on tracing paper19 ×24.5 cm, distinct from printed232. Inscribed1534 is depicted history, not drawing date.',
260:'Vaucanu mosque/street etching991.2.62,48.5 ×33.2 cm sheet, distinct from991.2.61 impression; uncertain place stays visible in original title.',
})
INVENTORY_EXCEPTIONS.update({179:{'3979f821-fa35-4e94-aa53-07be437136e7'},180:{'1654d506-533f-5f2b-a7a7-6af24110d015'},187:{'c962df2a-a7f9-41f8-8e5e-6258413440c0'},189:{'6a672e97-cf23-4cce-aaf8-29b9bffc4ef2'},190:{'0c749b8f-0e5e-4c22-a5b1-b24940c4faec'},191:{'d5f2b80a-3b5b-46ce-8076-9ceab68277a2'},197:{'a009e258-4845-4e58-b74d-517debf2212b'},203:{'0bd7dbb7-86f3-42b7-8174-4b33df99e773'},219:{'e0670169-a68d-49c2-a0ef-02f9bcc2072b'},226:{'09f3af3e-32fa-498d-9d3a-20f98bcd6554'},227:{'09f3af3e-32fa-498d-9d3a-20f98bcd6554','7e7014ef-7cc3-4b81-8fe0-9b247d084ede'},230:{'e0670169-a68d-49c2-a0ef-02f9bcc2072b'},249:{'c21b458b-9fb0-411b-b66f-97da2a33e6ad','c4ef7a97-fd9e-40c9-8434-c95b5187e27a'}})
for n in [183,211]:QUALIFIED[n]=('GIRODET DE ROUCY-TRIOSON Anne Louis (attribution contestée);GIRODET-TRIOSON (dit)','Historique')
QUALIFIED[199]=('Vaucanu Émile (1864-1896);Nadar (d’après une photographie; Félix dans Auteur, Paul dans Historique)','Historique')
for n in [217,241]:QUALIFIED[n]=('Vaucanu Émile (1864-1896);Nadar (d’après; prénom et dates biographiques discordants dans la source)','Precisions_sur_l_auteur')
HOLDS.update({
263:'Three existing Pasqua Maria records include two1882 leads17cea854-c640-4a0f-b18f-1c46c116e57a and9333fa51-a3ea-4440-b2aa-977e6522a8b7. Replica history distinguishes1864 original but not existing1882 records; reconcile duplicates first.',
307:'Headline second-half nineteenth-century period conflicts with1840 Villa Medici annotation attributed to Mme Hébert. Do not silently choose a date or alter source chronology.',
334:'Creation field1843 conflicts with explicit15March1848 inscription. Hold the discrepancy rather than guessing which transcription is correct.',
})
NOTES.update({
261:'Attributed Sánchez Coello young-woman canvas45.5 ×37 cm, second half sixteenth century. Qualified attribution retained; RF1983-116 belongs to Paris Hébert collection, not a display claim.',
262:'Diaz partial oil copy after Velázquez/Louvre941,46 ×38 cm canvas, explicitly before1876. Unknown lower bound preserved; Manet’s same-title etching is different.',
264:'Hébert circa1840 wood-panel copy after Andrea del Sarto’s Uffizi young-man portrait,27.5 ×22.5 cm. Source period bounds circa without invented tolerance or replacement by sixteenth-century model date.',
265:'1895 Roman shepherd panel45.2 ×29.8 cm. Inscription explicitly says Parisani copy after Hébert retouched by Hébert; preserve both roles and avoid claiming two separate paintings.',
266:'Lépine watering-place oil71 ×55 cm canvas, explicitly before1892. Lower creation bound stays unknown; painter lifespan does not supply it.',
267:'Attributed Moroni young-man canvas37.5 ×33.5 cm, third quarter sixteenth century. Qualified maker retained; female portrait comparison differs in sitter/size.',
268:'Anonymous nineteenth-century boy portrait pastiche in Le Nain taste,65 ×55 cm canvas. Retain style qualification, do not assign Le Nain as maker.',
269:'Anonymous nineteenth-century bust-length copy after Van Dyck’s full-length future-James-II model,41 ×38 cm canvas. London original is not imported or relinked.',
270:'Anonymous nineteenth-century Infidelity copy after Veronese,273 ×190 cm canvas; sixteenth-century original period stays model evidence.',
271:'Attributed Sánchez Coello boy portrait38 ×32 cm canvas, second half sixteenth century. Distinct from young-woman261 and larger nineteenth-century pastiche268.',
272:'Individual Porto d’Anzio fishermen/net-repair pencil/watercolour sheet18.3 ×26.6 cm, accession MNEH1978.2.1. Shares mount with.2 but has separate sheet dimensions, subject and inventory; count sheet once.',
273:'Anonymous eighteenth-century presumed Aurore de Koenigsmarck portrait37 ×28 cm; sitter identification remains presumed.',
274:'Separate Porto d’Anzio fishermen sheet22.5 ×37.4 cm on buff paper,MNEH1978.2.2. Shared mount with.1 does not merge two independently described drawings.',
275:'Anonymous seventeenth-century reduced Judgment of Paris copy after Rubens,49 ×61 cm wood. Distinct from larger London originals and nineteenth-century Dulwich canvas copy; after-credit made explicit.',
276:'Two fishermen tending pot before three boats,18.3 ×26.6 cm pencil/watercolour sheet,MNEH1978.2.3. Different subject from same-size.1; mount companion.4 separately recorded.',
277:'Anonymous eighteenth-century Venus/Love oil80 ×95 cm canvas, possible copy after Boucher. Preserve uncertainty; larger Boucher oils and small drawing are different physical objects.',
278:'Two beached boats before dark sea,26.1 ×37.4 cm sheet,MNEH1978.2.4, distinct from smaller cooking-fishermen mount companion.',
279:'Anonymous eighteenth-century Jupiter/Mercury oil37 ×59 cm canvas, RF1983-133; preserve anonymous maker and broad source period.',
280:'White building/blue rocky islet pencil-watercolour19.3 ×27.6 cm sheet,.5; separate from mounted Maremma.6 by subject/support/size.',
281:'Maremma watercolour/gouache18.5 ×26.8 cm beige sheet,.6; companion to.5 but independently inventoried and physically described.',
282:'Boat-hauling ink/brown-wash29.2 ×47.9 cm buff sheet,.8; mount relationship to.7 retained without inventing an additional capture for.7.',
283:'Boat-hauling study in pencil/wash/watercolour48 ×29.2 cm buff sheet,.9; distinct medium/orientation/inventory from.8 drawing.',
284:'Nine seated net-mending fishermen18.1 ×26.6 cm mounted buff sheet,.10, carton12 no.4. Distinct from companion.11 sketch.',
285:'Fishermen/net studies25.6 ×35.3 cm mounted buff sheet,.11, carton12 no.11. Several sketches on one described sheet count once.',
286:'Launching two boats24 ×29.1 cm pencil/watercolour buff sheet,.12. Companion.13 is larger hauling scene, not the same object.',
287:'Fishermen hauling boat29.3 ×47.9 cm brown-wash/watercolour sheet,.13, with two Hébert marks. One sheet, not two works because name appears twice.',
288:'Standing fisherman leaning on stern37.4 ×26.8 cm pencil/watercolour white sheet,.14; distinct vertical composition.',
289:'Seated fishermen between boats under sail27.1 ×37.6 cm sheet,.15; distinct inventory/subject from similar-format stern294.',
290:'One watercolour on white-paper sheet showing five boat prows26.8 ×37.4 cm,MNEH1978.2.16. The word suite describes depicted prows, not a five-sheet portfolio. Saved primary record00000055853 for existing Deux barques identifies oil on canvas27.4 ×45.3 cm,RF1978-268,dated28July1872; distinct medium/support/size and inventory establish different physical works.',
291:'Two sailors cooking18 ×26.5 cm mounted beige sheet,.17, carton12 no.8; distinct from fisherman/two-children companion.18.',
292:'Fisherman and two children watching pots26.2 ×37.3 cm beige sheet,.18, carton12 no.10; one sheet despite shared mount.',
293:'Beached boat and fisherman/pot18.5 ×26.8 cm beige sheet,.19; distinct subject/support from.20 companion.',
294:'Covered boat stern27.1 ×37.6 cm sheet,.20, inscribed20August1872. Exact source year retained; shared mount does not import its date to companion.19.',
295:'Water before a coast22.8 ×30.2 cm sheet,.21, carton10 no.119; individually inventoried alongside.22.',
296:'Beached boat in curved bay25.8 ×35.4 cm sheet,.22, carton10 no.120; distinct subject/size from.21.',
297:'Sea toward rocky coast22.7 ×29.2 cm sheet,.23; Ischia location remains uncertain and is not promoted to a definite creation-place field.',
298:'Castel Fusano beach25.2 ×35.2 cm sheet,.24, explicitly dated21April1887. Distinct from mount companion.23.',
299:'Six sailors pushing boat graphite on blue paper27.2 ×41.5 cm,.25; one sheet, damaged/truncated name retained in evidence.',
300:'Capitol from Tarpeian Rock Conté drawing21.6 ×29 cm,.26, circa1840 bounded by literal period. Mme Hébert early-years annotation not treated as autograph date.',
301:'Forum graphite/brush/ink/wash on grey paper29 ×39.3 cm,.27, source1840 with Mme Hébert verso annotation. Distinct from mounted Capitol/temple drawings.',
302:'Trees before Roman temple graphite19.8 ×35.3 cm,.28; uncertain forum identification retained. No date inherited from adjacent sheets.',
303:'Colosseum pencil/watercolour21.1 ×28.7 cm,.29, carton10 no.61; distinct from much smaller.30 same-subject sheet.',
304:'Colosseum pencil/watercolour11.1 ×15.4 cm,.30; one small companion sheet with distinct inventory and dimensions.',
305:'Marcellus theatre shops Conté39.5 ×49.3 cm,.31, carton22 no.1. Near-size companion306 has different carton/inventory and fuller architecture view.',
306:'Marcellus theatre/Orsini-palace Conté39.8 ×49.2 cm,.32, carton22 no.20. Separate source catalogue sheet from.31 despite similar subject/format.',
308:'Trinità dei Monti charcoal/white drawing27.8 ×43.4 cm grey paper,.34, explicit2October1843 inscription; shared mount with.33/.35 does not merge drawings.',
309:'Panorama behind timber framing charcoal/white chalk22.5 ×33.8 cm,.35. Source uncertain medium component and H.HEBERT transcription retained; no new maker inferred.',
310:'Rome view from Villa Medici Conté26.4 ×41 cm,.36, inscribed8September1843; separate from Palatine viewpoint companion.',
311:'Rome from high Palatine Conté/white chalk29 ×44.3 cm,.37, inscribed3March1843; distinct viewpoint and sheet from.36.',
312:'Villa Medici holm-oak wood watercolour29.5 ×23.3 cm,.38, carton10 no.31; distinct from autumn gouache companion.39 and later same-title charcoal sheets.',
313:'Villa Medici autumn coppice watercolour/gouache31.9 ×24.3 cm grey sheet,.39, carton16 no.42; distinct physical sheet from.38.',
314:'Villa Medici wood graphite/watercolour with green gouache border33.3 ×24.2 cm,.40, carton5 no.35; distinct medium/annotation from same-size.41/.42.',
315:'Villa Medici holm oaks charcoal/watercolour33.3 ×24.2 cm,.41, carton5 no.34; source pairs it with.40. Separate from.42 carton5 no.33 and different mount grouping.',
316:'Villa Medici holm oaks charcoal/watercolour33.3 ×24.2 cm,.42, carton5 no.33; separate numbered sheet in mount with.43/.44, not duplicate of.41.',
317:'Bosco trees above stone stair charcoal29.3 ×21.4 cm buff paper,.43, carton15 no.3B; distinct viewpoint/support from.42/.44.',
318:'Bosco behind stair/balustrade charcoal20.5 ×28.7 cm grey sheet,.44; explicit1841 source year and early-years verso annotation retained.',
319:'Villa Medici tree trunks charcoal31.2 ×23.8 cm buff sheet,.46; second-quarter nineteenth-century source period and early-years annotation preserved without invented exact year.',
320:'Roman countryside tree sketch charcoal20.8 ×15.2 cm,.47, explicitly25June1841 with Egeria inscription. Distinct from other mounted tree sheets.',
321:'Two Bosco tree sketches on one28.7 ×21.1 cm charcoal sheet,.48. Count the sheet once; source describes shared mount but gives independent inventory and measurements.',
322:'Villa Medici balustrade fragment watercolour35.3 ×25.2 cm, literal inventory49. Depicted fragment is an architectural subject, not a broken physical artwork.',
323:'Upper balustrade end watercolour25.1 ×45.6 cm, literal inventory50; separate landscape-format companion to49. Short-number collision is Coypel’s large Jesus oil.',
324:'Porta San Lorenzo Conté19.9 ×27.2 cm, inventory51, inscribed30September1843. Shared mount with52/53 preserved.',
325:'Villa Medici loggia interior charcoal26.6 ×31.2 cm, inventory52, second quarter nineteenth century; early-years annotation does not supply invented exact date.',
326:'Fortified-village silhouette Conté18.6 ×29.2 cm, inventory53; distinct subject/dimensions from mounted51/52.',
327:'Ponte Mol(le) low arch pencil/watercolour27.1 ×37.5 cm, inventory54, carton10 no.58. Literal source place spelling retained.',
328:'Porta Furba fountain charcoal/watercolour26.5 ×22.3 cm, inventory55; distinct from17.5 cm watercolour56 and Conté57. Short55 collision is Devéria’s unrelated Bernay oil.',
329:'Porta Furba watercolour17.5 ×12.3 cm, inventory56, carton5 fiche42 no.1; one small separately described sheet.',
330:'Porta Furba Conté28.7 ×19.7 cm, inventory57, carton5 no.19; different medium/size from watercolour56.',
331:'Architecture behind Santa Croce Conté18.7 ×29.5 cm, inventory58, carton15 no.21. Short58 collision is Coypel’s unrelated canvas.',
332:'Santa Croce church/convent Conté11.5 ×27.9 cm, inventory59. Short59 collision belongs to Soulages’s1963 large ink work, a different full inventory and maker.',
333:'Santa Croce convent complex graphite/watercolour29.1 ×35.2 cm, inventory60, carton5 no.22. Early-years annotation retained without selecting a precise date.',
335:'Roman tenuta Conté/watercolour19.9 ×24.8 cm, inventory62, source1885 with Mme Hébert annotation. Shared mount with Ostia63 does not transfer chronology.',
336:'Ostia calm coast charcoal/watercolour22.7 ×29.2 cm, inventory63, explicit16November1889 inscription; distinct from62 tenuta.',
337:'White statue before fence pencil/watercolour28.7 ×21 cm, inventory64; depicted statue is not a sculpture record. Short64 collision is Dupré’s unrelated1860 oak landscape oil.',
338:'Ruins with arch watercolour29.1 ×22.8 cm, inventory65, dated10June1886. Separate from statue64 in shared mount.',
339:'Bridge arch over uncertain Tiber/Anio pencil/watercolour21.1 ×28.6 cm, inventory66. River uncertainty retained; distinct from dated smaller charcoal sheet67.',
340:'Tiber bridge arch charcoal/watercolour20 ×25 cm, inventory67, explicit1885 inscription; separate physical variant from66.',
341:'Aqueduct toward square campanile graphite15.2 ×24 cm, inventory68; separate sheet from wider fortified-building aqueduct69.',
342:'Aqueduct and fortified building graphite23 ×43.7 cm grey paper, inventory69; distinct format/support and subject from68.',
343:'Tiber countryside pencil/watercolour14 ×23 cm, inventory70; independently described small sheet sharing mount with71–73, not the whole mount.',
344:'Buffalo ploughing pencil/watercolour11.1 ×15.5 cm, inventory72; different subject/size from other mounted70–73 sheets.',
345:'Plain and distant mountains pencil/watercolour12.7 ×17.8 cm, inventory73, explicitly18May1890. Do not apply its date to other sheets in shared mount.',
})
INVENTORY_EXCEPTIONS.update({323:{'d5f2b80a-3b5b-46ce-8076-9ceab68277a2'},328:{'6a672e97-cf23-4cce-aaf8-29b9bffc4ef2'},331:{'d5f2b80a-3b5b-46ce-8076-9ceab68277a2'},332:{'519b3362-c71e-411c-9ce3-72344f42b474'},337:{'cf78bb47-d173-43ce-8950-b4c889b42f6b'}})
QUALIFIED.update({268:('anonyme (pastiche dans le goût de Le Nain)','Historique'),275:('anonyme;Rubens (d’après)','Historique'),277:('anonyme;Boucher (d’après ?)','Historique')})
