#!/usr/bin/env python3
"""Individual physical-object and museum-connection decisions for completed BMA pages."""
import importlib.util,json
from pathlib import Path
s=importlib.util.spec_from_file_location('identity',Path(__file__).with_name('museum-expansion-baltimore-identity-v2-20261007.py'));identity=importlib.util.module_from_spec(s);s.loader.exec_module(identity)
f=identity.f;m=f.m;RUN=f.RUN;IID=f.IID;ref=f.ref;checked=f.checked
CANDIDATES=RUN/'native-candidates-001.json.gz';IDENTITY=RUN/'native-identity-002.json.gz';CITATIONS=RUN/'identity-citations-002.json.gz'
HOLDS={15:'Native entry explicitly belongs to an untitled 75-page Benjamin West sketchbook. The binding/leaf identity and counting unit remain unresolved; no separate physical artwork added merely for a leaf-level accession.',23:'Credit explicitly identifies an extended loan from the U.S. General Services Administration. Preserve the completed source as evidence; do not create an accepted Baltimore collection holding from this loan.'}
NOTES={
1:'BMA 2009.112.323 is Sopher’s 1947 pen-and-ink drawing, sheet141 ×154mm, with Martenet-to-BMA bequest provenance. Its source bequest year1957 differs from the accession prefix; retain both literally without inventing an acquisition correction. No Sopher/title/native/inventory counterpart found.',
2:'BMA 2015.216 is Goldthwaite’s circa1928 crayon lithograph, sheet330 ×235mm, image240 ×175mm, Alderson gift2015. Greek Youth and Maiden / Two Lovers has no corresponding object in the85-record creator scope, including translated subject searches. Preserve the signed source sheet as one object.',
3:'BMA 1946.112.12800 is Edward Percy Moran’s 1879 etching,136 ×120mm, Garrett Collection with Claghorn collector mark. The259-record surname scope includes other Moran creators but no Greek/brigand/cave subject counterpart. Do not derive an acquisition date from the accession prefix.',
4:'BMA 1946.112.5506 is the1593 engraving The Greek Before Christ, trimmed sheet231 ×142mm, Garrett Collection. Retain Antonius Wierix II and literal Bernadino Passeri as the two native Artist labels. Wierix/Wierx and Bernardino alias discovery yields no same object: Christ as a Fountain and Bearing the Body of Christ are different compositions. Do not invent an after role from another museum’s different print.',
5:'BMA 1996.48.5551 is one1829–30 crayon-lithograph sheet,215 ×293mm, image142 ×216mm, plate40 of Croquis par divers artistes. Lucas-to-MICA1909-to-BMA1996 provenance establishes its collection connection. AIC1965.160/1965.161 have different sheet/image dimensions and Print and Drawing Club credit; they are separate physical sheets. Keep the literal title spelling dok, source publisher roles and all sketches on this single counted sheet.',
6:'BMA 1996.48.5540 is one1829–30 crayon-lithograph sheet,194 ×267mm, image138 ×215mm, plate51 of Croquis par divers artistes, with Lucas/MICA/BMA provenance. It is separately accessioned from plate40. AIC1965.160/161 are different-size sheets with different credit. Existing WikiArt Albanian Duel is explicitly oil on canvas,1828, whereas this is a lithographed multi-sketch sheet. No conflation with that painting or multiplication by individual sketches.',
7:'BMA 1996.48.17099 is the1829 Young Greek Defending his Father lithograph with chine collé, sheet370 ×301mm, image276 ×220mm, purchased with the Lucas collection1996. Retain both native Artist labels Midy and Ary Scheffer; Lemercier and Rittner remain printer/publisher evidence. No same Greek/father/defending composition found in the205-record creator scope.',
8:'BMA 1996.48.110 is the1828 Aubry-Lecomte lithograph, sheet363 ×262mm, Lucas collection1996. Its inscription explicitly identifies a detail from Gérard’s Corinne; preserve Gérard as an additional native Artist contributor and keep the print distinct from an original painting or detail photograph. The1020-record expanded creator scope has no corresponding physical lithograph.',
9:'BMA 1946.112.4639 is the sixteenth-century Patroclus engraving, trimmed sheet240 ×384mm, Garrett Collection, naming Diana Mantuana and Giulio Romano. Getty ULAN supports the Scultori/Ghisi/Mantovana variants for discovery. The expanded125-record scope has no Patroclus/combat counterpart. Preserve the broad century; no inferred individual print state or unqualified painter authority.',
10:'BMA 2012.270 is Peale’s Erinna,1845, oil on canvas, sight43.2 ×35.6cm, Dorothy McIlvain Scott bequest2012. Its named sitter/title and source inventory have no corresponding Erinna/Erina/poetess match in the1591-record broad Peale/Rembrandt scope. Frame dimensions stay separate from sight dimensions.',
11:'BMA 1955.30.5 is one graphite sheet205 ×286mm, circa1826, Wilmer Hoffman bequest1955. Retain the title’s possible relationship to Count Palatiano, without asserting an exact portrait identity. The Louvre costume-study lead RF3669 is an1822 oil canvas43 ×45.5cm with Koechlin bequest1931; other coin prints and later cavalry paintings are different objects. One sheet of studies counts once.',
12:'BMA 1963.313.37 is the1837 hand-coloured crayon lithograph, sheet196 ×244mm, Caricaturana plate67, Gutman Collection. The3218-record creator scope includes other plates and school/examination subjects, but no corresponding plate67/baccalaureate caption object. Retain the full native dialogue title and hand-colouring; do not infer an acquisition year.',
13:'BMA 1963.313.93 is the1857 Croquis d’été plate20 impression, source sheet261 ×171mm, Gutman Collection. AIC84585/1955.1144 is the same printed composition but a separately accessioned sheet273 ×360mm, Gift of the Print and Drawing Club. Different physical sheet and collection credit support distinct impressions. Preserve Baltimore’s literal dimensions without silently swapping axes or identifying an unrecorded print state.',
14:'BMA 1963.109.131 is the1846 Professeurs et Moutards plate22 impression, sheet197 ×249mm, given in memory of Joseph Katz. AIC76372/1952.39 is a separately accessioned sheet247 ×328mm given by Mr. and Mrs. Carter H. Harrison. The same composition does not collapse these differently documented physical sheets. Retain the full Baltimore caption.',
16:'BMA 1949.62 is the circa1690 oil-on-canvas Siege of Barcelona,35-5/8 ×48-1/2in, Murdoch sisters gift1949, descending from Alexander Fridge. The113-record creator scope contains sieges of other named cities; no Barcelona/Barcelone counterpart. Native provenance establishes this separately accessioned canvas. Preserve the literal date and inches.',
17:'BMA 1946.112.1511 is Erhard’s1816 etching,141 ×191mm, with explicit Garrett gift1946 provenance. Related Met Cossack compositions are separately inventoried Whittelsey prints, not Baltimore’s Garrett object. Exact extent of the unlabelled native dimensions and print state remain unknown; no invented edition/state. Count this one physically documented impression once.',
18:'BMA 1946.112.1513 is Erhard’s1815 etching,138 ×184mm, with explicit Garrett gift1946 provenance, separate from1511 and1515. Related Russian/Cossack creator-scope prints have other inventories, dimensions and collection contexts. Preserve the source’s unlabelled measurements and unknown state; no cross-museum holding merge based on composition alone.',
19:'BMA 1946.112.1515 is Erhard’s1815 etching and drypoint, sheet174 ×221mm, plate154 ×197mm, Garrett gift1946. The close Met368218/49.21.6 is a third-state etching, sheet9 ×12-1/8in, Whittelsey Fund1949. Distinct physical sheet and documented collection credit distinguish the impressions. Do not assign the Met state to the Baltimore object.',
20:'BMA 1996.48.15669 is the circa1836 lithograph, sheet178 ×243mm, Lucas/MICA/BMA1996 provenance, with both Raffet and Charlet named as Artist contributors. Close Louvre lead POP000PE002292/RF2329 is Raffet’s1856 oil canvas65 ×81cm, Strauss gift1921. Different medium, date and physical version; an old Walters exhibition does not transfer the Baltimore holding.',
21:'BMA 1996.48.12699 is Lançon’s circa1870 etching, sheet362 ×256mm, plate319 ×216mm, Lucas collection1996. No matching Prussian/cavalier/soldier work found in the79-record creator/contributor scope. Preserve Alfred Salmon as printer and the Salmon collector stamp as evidence, without creating an artist link for the printer.',
22:'BMA 1996.48.12660 is Lançon’s1880 etching from Les Animaux Chez Eux, sheet264 ×345mm, image194 ×276mm, Lucas collection1996. Native inscription confirms1880. No bear/ours counterpart in the96-record creator/contributor scope. Keep publisher/printer roles and count one physical sheet, not a whole series.'}
def build():
 x=m.load(CANDIDATES);ix=m.load(IDENTITY);cx=m.load(CITATIONS)
 for dep in x['dependencies']+[ix['query_reference'],ix['base_query_reference']]+ix['alias_primary_references']:checked(dep)
 assert ix['candidate_reference']==ref(CANDIDATES) and cx['identity_reference']==ref(IDENTITY)
 assert ix['params']==identity.base.params_for(identity.rows()) and ix['comparisons']==identity.base.comparisons(identity.rows(),ix['state'])
 assert cx['selected_ids']==ix['state']['artwork_ids'];assert x['partial'] and x['capture_count']==23 and x['expected_capture_count']==244
 assert set(NOTES).isdisjoint(HOLDS) and set(NOTES)|set(HOLDS)==set(range(1,24))
 out=[]
 for row,cmp in zip(x['rows'],ix['comparisons']):
  assert row==f.parse(checked(row['source_reference']));n=row['number'];v=row['facts']
  if n in HOLDS:out.append(dict(row,state='editorial_hold',basis=HOLDS[n],comparison=cmp));continue
  assert v['date_issue'] is None and v['first']<=v['last']<=1970 and v['inventory'] and v['credit_line'] and v['creator_label']
  assert set(row['review_flags'])<={'creator_role_requires_review','hero_detail_creator_difference','multiple_creators_or_truncated_heading','physical_version_or_qualified_creator_review'}
  assert not any(cmp[k] for k in ['native_scheme_hits','native_url_hits','source_hits','untitled_creator_hits','exact_title_hits'])
  assert not any(h['relevant'] for h in cmp['inventory_hits'])
  out.append(dict(row,state='approved_review_only_addition',confidence=.88 if n in [17,18] else .90,basis=NOTES[n],comparison=cmp,limitation='Editorial confidence in physical-object identity and documented museum collection connection, not a calibrated probability. Source labels, contributor roles, literal dates/dimensions, provenance and unknown rights retained. No current-display, physical-custody or legal-title assertion. No image attachment or new painter authority; additions remain review. Greek/Russian subject words do not establish creator nationality or cultural tradition.'))
 assert sum(r['state']=='approved_review_only_addition' for r in out)==21
 return out
def main():
 dest=RUN/'editorial-reviewed-001.json.gz';assert not dest.exists()
 paths=[CANDIDATES,IDENTITY,CITATIONS,RUN/'source-access-hold-001.json']+list(RUN.glob('version-web-*.json'))+list(RUN.glob('artic-comparison-*-001.json.gz'))
 m.save(dest,dict(at=m.now(),reviewer_reference=ref(Path(__file__).resolve()),decisions=build(),supplement_references=[ref(p) for p in sorted(paths)],uncaptured_count=221,policy='21 selected additions; two captured holds.244 selected index leads are not244 captured or approved artworks. Native access remains on hold after challenge. Purple Robe sample remains outside this delivery.'))
 print(json.dumps(dict(approved=21,held=2,uncaptured=221)),flush=True)
if __name__=='__main__':main()
