"""Protect selected creator and title comparators; record physical identity decisions."""
import importlib.util,json,re
from pathlib import Path
z=importlib.util.spec_from_file_location('i',Path(__file__).with_name('museum-expansion-rhodes-final-identity-20261009.py'));i=importlib.util.module_from_spec(z);z.loader.exec_module(i);m=i.m;RUN=i.RUN
x=m.load(RUN/'production-identity-001.json.gz');ids={a['id']for c in x['comparisons']for a in c['hits']};links={}
for v in x['state']['links']:links.setdefault(v['artwork_id'],[]).append(v['display_name'])
for a in x['state']['artworks']:
 creator=m.norm(a['unlinked_creator_label']or','.join(links.get(a['id'],[])))
 if re.search('vasili|vassili|βασιλ|vikato|vicato|βικατ|vitsor|βιτσωρ|vourloum|βουρλουμ|byzantio|vyzantio|βυζαντ|gait|γαιτ|galan|γαλαν|germen|ghermen|γερμεν|giannako|yiannako|γιαννακο|giolda|yiolda|γιολδ|ginis|gkinis|γκινη|gounar|γουναρ|giallin|yallin|γιαλλιν|chalep|χαλεπ|δημητρησ δαβ|dimitris dav|daniel daniel|daniil|δανιηλ|diamantop|διαμαντοπ|engonop|eggonop|εγγονοπ|takis ele|τακησ ελευ|zepos|zeppos|ζεπο|zidian|ζιδιαν',creator,re.I):ids.add(a['id'])
ids=sorted(ids)
with i.prod.connect()as db,db.transaction():
 db.execute('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ,READ ONLY');snap=i.s.snapshot(db,ids)
assessments=[
 dict(number=291,existing_id='8a26fdd2-c1a7-5f9e-a234-d67bb658891e',decision='same_physical_work_existing_holding_only',basis='Identical sailboat, pale yellow triangular sails, blue edging, orange-red cabin, ropes and reflections in native and WikiArt reproductions. Greek and English titles agree. Existing date unknown is preserved; native1962 stays cited evidence. No duplicate artwork. Holding to Rhodes supported at0.99 editorial confidence.'),
 dict(number=292,decision='distinct_from_four_wikiart_comparators',basis='Native1957 wide pale green landscape has rocky left ridge, rolling fields, dark cypresses and pale right buildings. Summer in Hydra shows two boys and a rowing boat; Boats Hydra shows close fishing boats; Port shows boats,workers and donkeys; Ydra1959 is a dense ochre/red-roof townscape. No same composition or physical version.'),
 dict(number=320,existing_id='e78f98cd-2310-5f83-8df5-b5ee49f01be5',decision='different_composition',basis='Rhodes1929 Pontikonisi has a foreground causeway and two islet structures below green mountains. National Gallery Landscape Π.4700 has white-sailed boats before a long bare pink mountain range and no causeway. National Gallery Corfu Π.6698 also has substantially different12x28.4cm dimensions versus39x73cm.'),
 dict(numbers=[360,363,364],decision='three_distinct_physical_drawings',basis='1218 shows an older mustached man seated upright looking left with both hands beside his seat;1222 a younger downward-looking man in three-quarter profile with hand on thigh;1223 a frontal man leaning with an arm diagonally across his torso. Different poses, supports and inventory IDs despite similar dates and two near-equal dimensions.'),
 dict(numbers=[324,326],decision='drawings_distinct_from_existing_sculptures',basis='Each source is a24x25cm pencil sheet.326 has front and back images on one physical sheet. The18 existing Chalepas source pages explicitly classify their works as sculpture, including The Hunter and Medea. No sculpture/drawing conflation.'),
 dict(number=314,existing_id='0d0445d9-7c3e-5096-8218-ec75a43f0301',decision='distinct_documented_object',basis='Native Archaic Figures1952,79.7x98.7cm, depicts three veiled female profiles. Goulandris Prometheus circa1948 has different explicit title and89x116cm dimensions; no source or physical match.'),
 dict(numbers=[359,374,376],decision='physical_versions_distinguished',basis='Zepos1217 is a36x46cm plaster-bust study, not existing1243 full-statue drawing120x69cm.1233 is a violin still life despite dimensions copied also to adjacent undated portrait1232; separate subject and inventory, uncertainty retained.1235 Mother is explicitly a13x11cm preparatory oil, not the National Gallery finished painting.')]
m.save(RUN/'subject-comparators-001.json.gz',dict(at=m.now(),ids=ids,snapshot=snap,identity_reference=i.s.ref(RUN/'production-identity-001.json.gz'),script_reference=i.s.ref(Path(__file__).resolve()),assessment='995 bounded candidates and1828 citations reviewed. Exact source IDs have no prior hits. Translated Boat with Sails is linked as an existing work after image confirmation. Other creator/title similarities resolved by individual inventories, physical supports, compositions and creation dates. Broad Davis hits to other artists are unrelated. All existing metadata,media,status,artist and institution rows protected.',read_only=True))
visual=m.load(RUN/'visual-reference-captures-001.json');ydra=m.load(RUN/'ydra-reference-001.json');seen=[dict(number=v['number'],provider=v['provider'],path=v['receipt']['path'],sha256=v['receipt']['sha256'])for v in visual['rows']];seen.append(dict(number=292,provider='wikiart-ydra-current',path=ydra['path'],sha256=ydra['sha256']))
m.save(RUN/'visual-assessment-001.json',dict(at=m.now(),references=[i.s.ref(RUN/v)for v in ['visual-reference-captures-001.json','ydra-reference-001.json','production-identity-citations-001.json.gz']],images_seen=seen,assessments=assessments,policy='12 selected reference images reviewed for identity. No attachments or catalogue image changes. Museum CC0 and WikiArt actual rights labels retained; approved source use is separate from those labels.'))
print(json.dumps(dict(protected_comparators=len(ids),images_seen=len(seen))),flush=True)
