"""Individual physical-object decisions for the three remaining researched museums."""
import importlib.util,json,collections
from pathlib import Path
z=importlib.util.spec_from_file_location('s',Path(__file__).with_name('museum-expansion-italy-fifth-identity-20261008.py'));s=importlib.util.module_from_spec(z);z.loader.exec_module(s)
m=s.m;RUN=s.RUN;SOURCE=s.SOURCE
CEN={
3:'Seventeenth-century copy of Correggio Il Giorno. Jerome and Magdalene accompany the Virgin; individual Magdalenes and other Holy Families returned are different compositions.',
4:'Magdalene with two angels, painted on wood. Related Manetti, Curradi, Cigoli, Furini, Boschi and Sustermans comparators are canvas paintings.',
5:'Flame identifies Vincent Ferrer rather than the former Dominic label. The Parmigianino Philip comparison represents another saint and is a print.',
7:'Wheat ear with Florence view on wood, possibly a Crusca emblem. Van Wittel city view inventory9292 is copper. Emblem identification stays tentative.',
9:'Partial copy on wood after Titian mirror Venus. NGA original is canvas; other Venus and Adonis subjects are different compositions. Count the independently painted copy.',
10:'Good Shepherd inventory6957. Literal1590/1610 range agrees with structured endpoints; returned works have other periods or subjects.',
11:'Man reading, inventory4939. Regnier tavern/card-player scene depicts a group and a different activity. Literal storage-room note is not a display claim.',
12:'Augustine vision with Virgin and Child, heart and pen. Van Loo Virgin/Child and Loir young John compositions have different accompanying figures.',
16:'Annunciate Virgin copy,38x30cm canvas, inventory7265, from Crocetta1867; pendant angel7264 is separate. Curradi6585 came from Monticelli;3217 from Santa Maria degli Angeli/Santa Maria Nuova1900 with different pendant3216. Candido is copper.',
18:'Andrew on wood after Cortona, inventory7402. Furini and Manenti comparators are canvas, Lanfranco is a mural, Domenichino drawing and Callot prints have different supports.',
21:'Bartholomew on wood, inventory7347. Poccetti is an oval fresco; Santi di Tito includes the Virgin and Romualdo; Bronzino Panciatichi is a lay portrait.',
22:'Scholastica on wood, inventory7336. Curradi6430 includes Benedict on canvas; Cecilia and Sebastian title hits are other saints.',
23:'Eustace vision1590s on wood, inventory7316. Carracci quintavalle364 is canvas; Cigoli depicts Stephen stoned.',
24:'Transfiguration1590s on wood, inventory6732. Returned potential comparisons have other periods or different events.',
27:'Lucrezia vision, inventory7323. Cecilia, Tecla and Andrew martyrdom comparisons depict different saints. Preserve source uncertainty.',
28:'Praying nun, inventory6948. Do not infer Catherine. Francis prayer scenes depict a male saint; Dolci Margaret has another named identity.',
29:'Annunciation on one canvas, inventory3541; historical Poggio a Caiano1910 inventories5140/9689 retained. Dolci angel is an individual figure, Dinozzo adds a nun, Dorigny has a different documented maker/inventory1013.',
34:'Marriage of Virgin,51x36cm wood, inventory7598, Monteoliveto provenance. Van Balen1142 has separate grand-ducal inventory history1753/1769/1784/1825. Vignali Passion compositions depict another event.',
38:'Two female hands painted on paper, inventory6514, an independently supported study copying a Titian Magdalene detail; no competing physical identity returned.',
39:'Hercules and Omphale on wood, inventory7703. The7700–7702 companion works depict other mythological subjects; returned comparisons have different periods.',
42:'Young Baptist on canvas, inventory7714. Sarto Palatina272 is wood; Virgin with John and multi-figure scenes differ in composition.',
43:'Female martyr on wood, inventory7350, companion6515 remains a separate object. Nuvolone and Umbro-Corsi comparators are canvas; named other saints differ.',
54:'Mary and angel together on one canvas, inventory6418, after SS Annunziata. Virgin-only7265 and Curradi/Dolci separate figure paintings are not this support.',
55:'Francesca Romana with guardian angel, inventory7548. Returned comparison has a different period and subject.',
59:'Magi canvas, inventory7517, explicitly a copy after Giordano at Lappeggi. Original and other Magi/Shepherd compositions remain separate.',
60:'Fame, inventory7475. Florence, Ignorance, Falsehood and Genius allegories represent different personifications.',
63:'Visual Arts, inventory7509. Pendant6743 is a separate composition; returned comparison periods differ.',
69:'Teresa,1700–1749, inventory7149; former Dorino/Dinozzo Lippi attribution retained as history. Spanish anonymous seventeenth-century comparison has a different period.',
70:'Attributed Botti Virgin and John at the cross, inventory7051. Vignali7236 also includes Magdalene; different composition. Cross attachment traces do not create another catalogue artwork.',
71:'Magdalena de Pazzi, the Carmelite nun, inventory7489. Ordinary Magdalene and Mehus three-Magdalenes compositions are different subjects.',
72:'Country fair with maypole and Grand Duke, inventory7707. Van Valckenborch1249 and Miel1151 have different documented makers and supports.',
81:'Return from Egypt on wood, inventory7260. Rubens Return from the Fields is a different event.',
82:'Music, inventory7567. Current source period supersedes old eighteenth-century inventory dating in source history; other returned allegories depict different personifications.',
86:'Borromeo on wood,45.5x35cm, inventory7251. Other batch Borromeo6652 measures38x22cm with separate historical inventory; Dolci Palatina275 is canvas.',
87:'Hagar and angel on wood, inventory7258. Cerrini6178 is canvas with Ishmael; pendant Rest7584 and self-portrait Hagar are different compositions.',
92:'Thomas Aquinas1600–1624, inventory7081; no same-period physical conflict returned. Santi/Allori stylistic context does not establish authorship.',
93:'Crucifixion with Virgin, Magdalene and John on oil-painted wood, inventory6715. Palmezzano1418 is tempera on wood with additional apostles/roadway. Correct earlier working shorthand that called this canvas.',
98:'Gethsemane on canvas, inventory7414. Dolci Palatina288 is wood; Lippi Christ with a saint depicts another event.',
100:'Rosa of Lima with Child, inventory7069. Dolci Palatina155 is a Rosa portrait; Montini7174 is a single nun from the1671–1673 San Marco commission. Virgin/Child pictures depict another person.',
103:'Canvas copy, inventory7194, explicitly after Cigoli signed1596 wood original at Fuligno. Bril copper and other versions remain different supports.',
104:'Unnamed bishop in oval composition on rectangular canvas, inventory7541. Fratellini pastel named bishops and Pignatta Strozzi portrait are different works; bishop remains unnamed.',
105:'Nun appearing to priest falling from ladder, inventory5633. Canvas applied to board is one work; no competing physical identity returned.',
106:'Woman working in kitchen1690s, inventory6950. Source revises older eighteenth-century dating; returned object has a different maker/period.',
107:'Anne teaching Mary, inventory7329. Hoecke Virgin/Child/Anne and Franchi Anna Maria Medici portrait are different compositions and people.',
108:'Greco-Adriatic Annunciation1590/1610,39.5x33cm wood with gold, inventory7243. Distinct from batch6536 measuring32x27cm. Preserve cultural label and Veronese stylistic reference.',
109:'Veneto-Cretan Annunciation,32x27cm wood, inventory6536, Accademia wax marks. Header Ambito Veneto and qualified historical tradition retained; independent support from7243.',
115:'Redeemer, inventory6473, explicitly a copy after Sarto at SS Annunziata. Other named-maker Redeemers and Christ mocked/with saint are separate objects.',
118:'Borromeo on wood,38x22cm, inventory6652, Accademia1853 and1825 inventory2666. Separate from45.5x35cm7251 and canvas Dolci Palatina275.'}
CRE={
336:'Christ and Peter fresco,180x70cm, surviving part of larger Last Judgment. Count this physical fragment once; Carneo Peter is a later canvas.',
337:'Female saint head fresco,53x32cm; independent measured surviving fragment.',
338:'Virgin/Child/Agnes/Francis fresco,100x172cm, Byzantine Hodegetria tradition retained.',
339:'Saint fresco,72x60cm. Source explicitly compares separate sibling fragments338/341; not an additional record for a whole ensemble.',
340:'Virgin fresco,160x52cm, a distinct measured fragment from133x97cm341.',
341:'Virgin fresco,133x97cm, independent support from160x52cm340.',
342:'Virgin/Child/Omobono fresco,100x88cm. Named accompanying saint distinguishes the composition.',
343:'Bishop head and crozier fragment,60x78cm fresco. Different from full figure43x15cm wood panel418.',
344:'Saints,42x48cm fresco; two figures on one physical fragment count once.',
345:'Virgin/Child fresco,90x60cm,1350–1399; independently catalogued support.',
346:'Francis fresco,140x73cm,1300–1349. Preserve the Byzantine iconographic context.',
347:'Virgin/Child/martyr fresco,100x124cm,ca1415, damaged inscription endingV. Distinct from353 measuring120x121cm and dated1410.',
348:'Master of Parma Baptistery Virgin fresco,111x78cm,1300–1349, geometric border; not a wood-panel Virgin version.',
349:'Male genre figures,105x70cm fresco,1400–1410; count the described physical fragment once.',
350:'Attributed Bonifacio Bembo Annunciation fresco,71x154cm,ca1450. Preserve attributed maker.',
351:'Attributed Bembo Virgin/Cosmas/Damian1448 fresco,123x120cm; different saints from other batch Virgins.',
352:'Virgin in rose garden fresco,143x107cm,1450–1499, independent support.',
353:'Virgin/Child/martyr fresco,120x121cm,1410 inscription recorded in eighteenth-century documentation. Separate from100x124cm347.',
354:'Sepulchral decoration fresco,198x155cm. Three painted compartments on one support count once; possible tomb identification remains qualified.',
356:'Virgin on embossed copper,22x15cm with gold. Retain Veneto-Cretan tradition; physically distinct from wood-panel and fresco Virgins.',
357:'Christ rising from tomb with Passion instruments,38x29cm wood,1430–1440; no competing physical identity returned.',
358:'Bembo Virgin of Mercy fresco,265x118cm,1450–1460. Multiple figures comprise one artwork.',
359:'Bembo central panel Christ and Virgin crowned,104x68cm wood. Source distinguishes the two Denver wings; add this panel only, not the whole triptych.',
390:'Bembo circle monk and two devotees,17x24cm panel fragment,ca1460; no competing physical identity returned.',
394:'Gerolamo Bembo Virgin with angels,140x80cm wood,1468–1469. Corna Virgin/Joseph/saints, Provoost church and Ferrari Bernardino/donor depict different groups.',
395:'Old head with green hat and red/yellow clothing,45x36cm fresco. Different measured fragment from397 with green clothing.',
396:'Virgin/Child/saint fresco,170x132cm. Distinct from398 with Roch and Sebastian,200x130cm.',
397:'Old head with green hat and green garment,50x38cm fresco. Separate sister fragment from45x36cm395.',
398:'Virgin with Roch and Sebastian1490 fresco,200x130cm. Different physical support and saints from396.',
399:'Catherine and Agatha,69x51cm fresco; independent support from matching-size Peter and Paul400.',
400:'Peter and Paul,69x51cm fresco; different people on a separately catalogued support from399.',
401:'Calvary,50x28cm wood,1450–1499. Barbari comparator is later1500–1549.',
404:'Bernardino,58.5x37.8cm wood. Different subject from same-size Virgin403 and different size from26x16cm Bernardino419.',
405:'Enthroned Virgin1480 wood,58x35cm, imposing architectural throne. Provoost church, Ferrari Bernardino and Corna Joseph/saints have other accompanying figures/settings.',
406:'Corna Nativity with young John,60x39cm wood. Bagatti Valsecchi comparison is an influence; the407/408 frescos are independent compositions.',
407:'Corna Raphael and Tobias,188x102cm fresco. Different subject/support from wood Nativity406 and fresco Virgin408.',
408:'Corna Virgin adoring Child,202x136cm fresco with trees and two shields; independent from the Corna wood panel406.',
409:'Virgin/Child,42x28cm wood, fifteenth-century unnamed school, Gothic throne, gold and garden. Preserve school attribution and individual source support; other Vivarini named versions are not asserted identical.',
410:'Nativity,ca1520,40x37cm wood. Distinct from Corna406 by support dimensions, period and source attribution.',
411:'Beci Virgin with Anthony Abbot and Magdalene,140x118cm fresco. Generic wood-panel Virgin412 remains deferred.',
418:'Bishop,43x15cm wood,1450, full figure on gold. Not the60x78cm fresco head343.',
419:'Bernardino,26x16cm wood. Different support size from58.5x37.8cm404.',
420:'Unnamed martyr,70x46cm wood, fifteenth century. Saltire cross may suggest Andrew but no firm identity added.',
425:'Mansueti Trinity with Francis and Bernardino1495,220x158cm wood; no competing physical identity returned.',
428:'Mark Evangelist,136x136cm fresco; one of five explicitly separate measured frescoes427–431, different saints/compositions. No overlapping-period conflict returned.',
429:'Jerome,136x136cm fresco. Other fifteenth-century Jerome hits are panels/prints or other named versions; this separately measured plaster fragment is not the whole cycle.',
431:'Anthony Abbot,136x136cm fresco. Martorelli comparison is a wood panel; separate physical fragment within five-fresco series.',
432:'Cavalier procession,118x107cm fresco. Source identifies three separate fragments;433 is118x103cm,434 is118x197cm with trumpeters/caryatids. No whole-cycle record added.',
433:'Cavalier procession with caparisons,118x103cm fresco. Separate measured fragment from432 and434, although same cycle; count each physical support once.',
434:'Trumpeter procession with flanking caryatids and central loss,118x197cm fresco. Different composition and dimensions from432/433.',
435:'Bembino Virgin/John/Nicholas,197x128cm canvas. Eighteenth-century repair does not change sixteenth-century creation date.',
437:'Camillo Boccaccino Virgin/Michael/Ambrogio1544,200x145cm canvas. Brera1532 composition is explicitly a different altarpiece.',
438:'Bagnacavallo Virgin/Francis/Zacharias/John,57x65cm wood. Giovanni Battista Ramenghi Virgin/John has a different maker and accompanying figures.',
441:'Mazzolino Virgin/Peter/Anne,ca1522–1524,280x170cm wood. Former Dosso attribution checked; Berlin Disputation is another composition.',
442:'Ferrari saint life,75x172cm fresco. Two painted scenes share one support and count once.',
444:'Lazarus1530–1535,72x67cm wood. Separate event from same-size Last Supper445; Parmigianino print is a model, not this support.',
445:'Last Supper1530–1535,72x67cm wood. Separate physical panel from Lazarus444.',
447:'Vincenzo Campi manner Calvary,66x48cm canvas,1550–1599. Christ nailed on ground and two horses differ from Barbari carrying-cross scene and period.',
448:'Aleni blessing Christ,46x25cm wood,1500–1549; no competing same-maker physical identity returned.',
449:'Aleni1515 Virgin/Child/John Evangelist/Anthony/angel,125x125cm wood. Source distinguishes Brera deposit version.',
450:'Galeazzo Campi Virgin/Child/young John/Rosa/Christopher,120x120cm wood. Preserve broad source range despite uncertain inscription; Giulio Campi Anthony/Alberto/donor group differs.',
451:'Altobello Melone Calvary,125x89cm canvas surviving war-damaged131x150cm painting. Count surviving artwork once; Barbari is a different documented maker/version.',
452:'Bembino Virgin/Child/Stephen,101x78.5cm wood. Other local compositions have different accompanying saints.',
453:'Secchi Jerome1535,115x113cm wood, expressly copying Cesare da Sesto Brera with added lion, landscape and fly on skull. Original1515–1520 is another object.',
454:'Gatti Virgin/Sebastian/Roch1525,276x157cm fresco. Former Giulio Campi history retained; Rizzo wood Holy Family/Andrew/John differs.',
455:'Lelio Orsi Margaret,60x36cm wood, sixteenth century. Former Parmigianino attribution retained in source history; no competing same-work identity returned.',
456:'Parmigianino school woman and putto,50x48cm fresco. Independent from Cupid457 measuring43x58cm.',
457:'Cupid,43x58cm fresco, Parmigianino school. Different composition and support from456.',
458:'Gambara Cupid and butterflies,48x95cm fresco fragment,1550–1599; one physical object.',
459:'Romanino female saint head,40x31cm fresco, white/red clothing and parted blond hair. Separate from460 and462; later Muziano heads and full-figure saints differ.',
460:'Romanino Addolorata head in profile,35x51cm fresco. Independent from459 female head and462 apostle; conflicted461 remains held.',
462:'Romanino apostle head,41x34cm fresco, yellow/red ground. Distinct from female heads459/460.',
463:'Magi,51x41cm tempera wood, formerly young El Greco, now unnamed Venetian madonnaro. Preserve revised qualified tradition; Greek-Veneto/Scutellari Shepherds depict a different event.',
464:'Camillo Boccaccino God blessing,50x105cm wood, possible cimasa. Count the panel only; no inferred whole altarpiece.',
465:'Bonifacio Pitati school Supper of Levi,ca1550,118x186cm canvas. Veronese1573 is another maker/date. Literal Tela retained without inventing oil technique.',
466:'Carpioni Bacchanal,75x100cm canvas,seventeenth century. Tavella Storm and generic other-maker mythological scenes are different objects.',
467:'Virgin reads while Child sleeps and saint takes a hand; gestures of silence,150x115cm canvas,1690s. Cantarini cloud/rosary groups differ; Cantarini/Creti stylistic comparison is not authorship.',
468:'Procaccini Joseph and Child1590s,60x52cm canvas. Source distinguishes Scarpa version; Procaccini Virgin/Child has a female adult; Corna multi-saint group is earlier.',
469:'Procaccini Dormition,325x650cm canvas,1600–1649. History dates it to late1610s;1973 is exhibition date. No competing same-maker physical identity returned.'}
GUIN={
470:'Roman Stephen and Borromeo, inventory6/6III/84. Dolci Borromeo alone and unrelated global inventory-number hits differ; historical Gimignani/Trevisani/Romanelli/Brandi suggestions remain qualified.',
471:'Attributed Machiavelli Virgin with Bartholomew, Magdalene, Martin and Anthony. Same-maker Virgin-only comparisons lack this saint group; other-makers groups have different named companions.',
473:'Attributed Parenzano Roch,1480s,panel228,pilgrim exposing right-leg bubo. Independent pendant panel229 depicts Sebastian; no whole altarpiece added.',
474:'Attributed Parenzano Sebastian,panel229,bound to conifer with eight arrows and hands behind back. Roch228 is another panel; other named-maker Sebastian objects and prints stay distinct.',
478:'Attributed Membrini Virgin with Stephen and Jerome, inventory42. Former Perugino/Francia/Brea checked; their compared groups have Francis, young John, angels or different saints.',
480:'Ciampanti manner Francis and orphans,roundel325,painted fruit border. One independently supported panel; preserve manner.',
481:'Zacchia Assumption1527,inventory43,from Sant Agostino. Source distinguishes San Pier Somaldi Assumption and San Salvatore Resurrection; returned Garofalo coin tribute is another event.',
482:'Zuccari Keys to Peter1593,inventory440,San Pier Maggiore Buonvisi altar. Other-date and unrelated inventory hits do not match.',
483:'Attributed Passignano Peter heals1593,inventory455/29. Pushkin72x56.7cm preparatory model expressly differs from finished canvas.',
484:'Guidotti Liberty of Lucca1611,inventory361. Sorri Calling Peter is a separate pendant, not this allegory.',
485:'Lucchese Virgin with bishop and martyr,inventory365,from Pitti1925. Preserve questioned Paolino/Teobaldo identities and former Zacchia/Marti/Malatesta debate. Returned altarpieces have other saint groups.',
486:'Lucchese Virgin with Augustine, Jerome and Monica1559,inventory369. Source copies Sarto group; other returned unknown-date Virgin-only composition and Both landscape differ.',
487:'Fra Paolino Virgin with Catherine, Dominic and Magdalene,ca1534,inventory448. Source distinguishes1538 inner-convent picture now Bibbiena; returned Virgins have different accompanying figures/supports.',
489:'Unnamed pope fresco1340–1360,inventory564,tiara distinguishes former Augustine label. Uncertain Pietrasanta provenance remains qualified.',
490:'Attributed Traini Michael1340–1360,wood657. Former temporary Pisa location retained as history; fresh comparison including Pisa returned no same-period physical conflict.',
491:'Five saints on one extended fresco,inventory464/1. Count one physical support, not five saint records.',
498:'Neroni Birth of Virgin,ca1560–1570,inventory346,Cappella Anziani. Bernabei comparator has another documented maker; Figino Virgin/Martha/Magdalene and Maratta portrait differ.',
499:'Battista Franco Visitation1550–1560,canvas347/III3,formerly Massei. Cambiaso1555 comparison is a pen/wash drawing on paper.',
502:'Mannucci workshop unnamed bishop,canvas455/24. Pendant Jerome455/20 is a separate canvas but remains deferred for versions; do not infer Martin.',
503:'Nicholas of Tolentino extinguishes fire1709,canvas455/71. Depicted Venice1479 is event date, not creation date.',
504:'Nicholas Purgatory1703,canvas235x167cm,455/70,angel raises a soul. Separate from130x148cm508 with monks and arches; five-story series consists of distinct canvases.',
505:'Nicholas ecstasy1707,canvas455/25,organ,viola and music scores. Different episode in independently supported series; stylistic Scorsini reference is not firm authorship.',
506:'Healing Nicholas1704,canvas455/21,Virgin and qualified Augustine/Monica. Separate episode and support.',
507:'Nicholas vision1703,canvas455/10,Christ with cross and crowd. Separate episode/support from other series canvases.',
508:'Nicholas Purgatory1703,canvas130x148cm,455/22,Augustinian monks,arches and vaults. Different dimensions/composition from235x167cm504; back Sant Agostino inscription retained.',
509:'Nicholas tramples demon1700–1710,narrow arched canvas359; one independent support.',
510:'Holy Family with young John,canvas455/46,explicit copy of Trevisani Munich6123. Anthony511 is a separate pendant. Other Holy Families have different documented makers, compositions or supports.',
511:'Anthony of Padua and Child,455/5. Douven Anne presenting Anna Maria Luisa portrait is a different composition.',
512:'Jerome vision,canvas455/4,explicit seventeenth-century copy after Parmigianino1526–1527 London original. Other returned saint visions/martyrdoms depict different events.',
513:'Attributed Isabella Fiorentini Virgin/Barbara/Dominic/two Catherines1632,455/64. Mannucci Catherine marriage and Virgin/John groups depict fewer/different saints. Preserve attribution and Aurelia religious name history.',
514:'Attributed Gherardi Republic of Lucca1675–1699,494,woman with Serchio allegory. Different date and composition from Guidotti1611.',
515:'Farneta Charterhouse view,eighteenth century,380. Medieval building dates in history do not date this canvas; inventory380 global hits are unrelated.',
516:'Mannucci workshop Christ and Samaritan,455/19. Vignali,Giordano,Santacroce,Valentin and Lanfranco have separately documented maker/object identities; source retains workshop qualifier and individual support.',
517:'Flagellation with Catherine,Sebastian,Magdalene,455/3,1700–1749. Composite quotations on one canvas; Crucifixion and Shepherds comparisons depict other events.',
518:'Attributed Sani Guinigi/Orsetti arms,656,two women and unicorn. Marriage occasion stays unknown; global inventory656 portrait differs.',
520:'Attributed Cecchi Massaciuccoli excavations1756,418. Count this painting, not the archaeological objects depicted; unrelated Student inventory418 differs.',
522:'Sorrowing Virgin with nails,455/51. Scaglia363 has seven swords,Joseph,Philip Neri and other figures. InitialsSMF remain unresolved.',
523:'Approval of religious rule,455/68,1700–1749,possibly female Augustinian order. Lombardi Virgin appearing to Nicholas represents another event.',
524:'Bishop Augustine(?),fresco230,transferred to wood1855,from Santa Maria Forisportam. Pontormo comparison8ac617db is second stripping of Augustine HEAD at Boldrone near Quarto; distinct provenance/composition. Questioned saint preserved.',
525:'Zacchia Virgin/Roch/Sebastian,275,Sardini1911. Church replacement copy and preparatory study are separate. Sarto Gambassi includes many more saints; other groups differ.',
526:'Zacchia Nativity,panel32,1500–1524,landscape variation after Spagna Vatican. Other named-maker Nativities are independent versions;1576 former Lorenzo Zacchia confusion is not adopted.',
531:'Return from Egypt,canvas423. Rubens Return from Fields and Bril Return from Hunt are different events; Lines inventory423 unrelated.',
535:'Virgin of Mercy,canvas455/17,explicit later copy after Fra Bartolomeo. Bernabei1071 is fresco transferred to canvas with named donors; other apocalypse/rosary Virgins differ.',
545:'Abbot Capparoni,canvas455/47. Source names sitter; no returned same-sitter identity. Other numbered religious portraits in this group name different people.',
546:'Abbot D. Minutoli,canvas455/48,prelate clothing. No returned same-sitter identity; keep generic source title and source subject in evidence.',
547:'Abbot Buzzaccarini,canvas455/49. No returned same-sitter identity; independently inventoried religious portrait.',
548:'Bishop of Manfredonia,canvas455/50,enlarged and relined. Personal name remains unknown; do not equate with named unrelated bishops or other group portraits.',
551:'Abbot Buzzini,canvas455/54,enlarged and relined. No returned same-sitter identity; distinct from Buzzaccarini455/49.',
552:'Abbot Boccella,canvas455/55,relined. No returned same-sitter identity; named source subject retained in evidence.',
557:'Blessed Arcangelo of Bologna,canvas455/61,relined. No returned same-sitter identity; not one of the unnamed portraits deferred.',
581:'Pietro Testa portrait,engraving121.1/1,Pasquinelli gift,back identifies Cesare engraving. Mansi37d86635 is90x73cm oil canvas260,not this print. Preserve distinct designer/engraver roles.',
584:'Allegorical triumph of InnocentX,etching121.1/4,Pasquinelli gift. Not a portrait or painting; no competing Testa physical identity returned.',
585:'Peter freed by angel,etching121.1/5. No competing Testa-family physical identity returned; painting versions remain separate.',
586:'Sebastian martyrdom,etching/engraving121.1/6,dedication Ghislieri. Separate print support from paintings of this subject.',
587:'Penitent Jerome,engraving/etching121.1/7,Rossi publisher inscription. No competing Testa-family same-title identity in returned comparison; not a Jerome canvas.',
588:'Achilles drags Hector,etching121.1/8,Rossi publisher. No competing same-maker physical identity returned.',
589:'Peace allegory,etching121.1/9,Minerva/Venus. Independent composition from Testa Virtue and other allegories.',
590:'Iphigenia sacrifice,etching/engraving121.1/10. Preserve Testa designer/engraver roles; no competing physical identity returned.',
591:'Attributed Testa Venus restrains Adonis,print121.1/11. Existing953b6f94 is oil canvas, Wouters comparison is wood painting. Preserve attribution.',
592:'Virtue allegory,etching121.1/12,Rondenino dedication,Rossi publisher. Different composition from Peace589.',
593:'Last communion of Jerome,etching121.1/13,Cesare Testa after Domenichino. Distinct physical print from Vatican painting; roles retained.',
594:'Charles Bourbon,Duke of Lucca,lithograph121.1/14,Kruger/Oldermann,Berlin1828 inscription. Source broad nineteenth-century date retained; no competing maker/sitter print returned.',
596:'Carlo Ludovico entry to Lucca1833,lithograph121.1/17,Buonori,Porta San Donato. Separate event/view from maps and portraits.',
597:'Lorenzo Nottolini,lithograph121.1/18,Marsili/Bertini. De Nobili8eb1059b same-sitter portrait is1873 oil canvas.',
598:'San Francesco temporary facade,etching121.1/22,Marsili/De Santi. One print, not the physical facade.',
599:'Lazzaro Papi monument,lithograph1835,121.1/19,Citti. One print, not the monument depicted.',
600:'San Martino square,etching121.1/24,Nerici. Specific cathedral/palace view distinct from other Lucca squares and plans.',
601:'San Michele square,etching121.1/25. Hypothetical Matraja/Nerici authorship stays in history; source school label retained.',
602:'Forisportam square,etching121.1/26,Verico/Matraja. Specific buildings and broken column distinguish other square views.',
603:'San Pietro Somaldi square,etching121.1/27,Verico/Matraja. Separate view and inventory from602/604.',
604:'San Francesco square,etching121.1/28,Verico/Matraja,Stellare and Via Zecca. Separate city view.',
605:'Lucca plan1820,etching121.1/31,Nerici. Distinct date/version from the1843 plans.',
606:'Lucca plan1843,etching273x338mm,121.1/32,cut and applied to vellum,handwritten Sinibaldi congress dedication. Distinct from158x200mm lithograph617.',
607:'Lucca racing amphitheatre1785,etching121.1/36,Nerici/De Santi. Separate subject from street views/maps.',
608:'Carlo Ludovico as child1803,etching121.2/1,Lasinio,lion and kneeling king. Distinct from held595 sitter conflict; retain source date.',
609:'Mansi garden overall view,etching121.2/11,Giusti/Angeli. Inscriptions distinguish large-pond/wood views610/611; count independent print supports.',
610:'Mansi large fishpond and avenue through wood,etching121.2/12. Inscribed view differs from overall609 and pond within wood611.',
611:'Mansi fishpond inside wood,etching121.2/13. Independent inscribed view from609/610.',
612:'Mansi country house FRONT,etching300x445mm,121.2/14,inscription,hunter and dogs. Distinct from REAR613; generic614 deferred.',
613:'Mansi country house REAR,etching300x445mm,121.2/15,inscription,peasants and horse. Distinct from FRONT612.',
615:'Angel with lute,nineteenth-century lithograph,Marsili after Fra Bartolomeo. Print support, not the original painting.',
616:'Magdalene,nineteenth-century engraving,Nocchi/Morghen after Murillo. Different support and period from seventeenth-century Mannucci canvas500.',
617:'Lucca plan1843,Bertini/Sinibaldi lithograph158x200mm,121.2/29. Distinct from273x338mm etching606 mounted on vellum.',
618:'Maria Luisa Carlotta Bourbon,1835 lithograph121.2/30,Vogel/Zoellner,Louise Duchess of Saxony inscription. Nocchi circa1820 Maria Luisa Duchess of Lucca painting concerns another sitter/support; other female portraits have different makers.'}
NOTES={**CEN,**CRE,**GUIN}
HOLDS={57:'Seven-swords Virgin versus generic Addolorata comparisons: more physical/version evidence needed.',68:'Dominic canvas versus Botti ecstasy and other sparse versions needs further identity evidence.',74:'Catherine of Siena versus sparse Nelli comparison unresolved.',111:'Ecce Homo panel versus sparse Farinati/Bassano versions needs further identity evidence.',116:'Header canvas conflicts with history describing a tavola; support needs reconciliation.',355:'Veneto-Cretan wood Virgin versions unresolved; preserve priority for further research.',402:'Erri Virgin versions need physical comparison.',403:'Winking Eyes Master replicas need physical comparison.',412:'Beci generic Virgin wood-panel versions unresolved.',415:'Virgin/Child/John tondo version unresolved.',416:'Bissolo Jerome and former aliases need further physical/version review.',417:'Lodi Jerome and former aliases need further physical/version review.',427:'Separate cycle support established, but Foppa Baptist fresco comparison still needs reconciliation.',430:'Separate cycle support established, but Bergognone Visitation comparison still needs reconciliation.',440:'Attribution relationship with439 remains unresolved.',446:'Sofonisba male portrait/former Vincenzo Campi and sparse portrait versions unresolved.',472:'Generic Virgin versions unresolved.',475:'Local inventory20 collides with existing Reni Crucifixion OA0900067690; this Visitation identity must be reconciled.',495:'Assembled dossal physical-unit scope needs further review.',500:'Mannucci workshop Magdalene versus related canvas versions unresolved.',501:'Mannucci workshop Jerome versus broad same-period canvas versions unresolved.',519:'Cortonesque Holy Family versus sparse same-period versions unresolved.',521:'Perin Lamentation versions unresolved.',529:'Cigoli manner Francis versions unresolved; literal Tela does not establish oil technique.',532:'Holy Family1512 versions unresolved.',536:'Lucchese Deposition versus generic same-period versions unresolved.',538:'Francis ecstasy versions unresolved.',540:'Magdalene relationship to500 needs composition comparison.',565:'Assumption versus sparse same-period versions unresolved.',566:'Generic Virgin versions unresolved.',614:'Generic Mansi Villa view needs physical/composition reconciliation with explicit front/rear prints.'}
for n in [541,542,543,544,549,550,553,554,555,556,558]:HOLDS[n]='Unnamed portrait physical identity remains unresolved against generic portrait comparisons.'
for n in range(559,565):HOLDS[n]='Shared historical inventory66 needs reconciliation despite current A–F suffixes; no quota-based split.'
def main():
 dest=RUN/'source-editorial-working-001.json';assert not dest.exists();old=m.load(SOURCE/'source-editorial-working-002.json');rows={v['number']:v for v in s.rows()};notes={}
 for n,note in NOTES.items():
  assert n in rows and str(n) not in old['holds'];notes[n]=dict(source_id=rows[n]['facts']['source_id'],title=rows[n]['facts']['title'],basis=note,prior_observation=old['observations'].get(str(n)))
 assert not(set(NOTES)&set(HOLDS));m.save(dest,dict(at=m.now(),notes=notes,holds=HOLDS,prior_source_holds=old['holds'],source_working_reference=s.ref(SOURCE/'source-editorial-working-002.json'),script_reference=s.ref(Path(__file__).resolve()),policy='Explicit individual selection after source/history/support and fresh catalogue comparisons. Unselected notices remain research; quotas do not override unresolved identity.'))
 print(json.dumps(dict(selected=len(NOTES),by_museum=dict(Cenacolo=len(CEN),Cremona=len(CRE),Guinigi=len(GUIN)))),flush=True)
if __name__=='__main__':main()
