"""Freeze wave94 delivery notes and retain every prior unresolved museum queue."""
import collections,hashlib,importlib.util,json
from pathlib import Path
z=importlib.util.spec_from_file_location('a',Path(__file__).with_name('museum-expansion-leeds-drawings-apply-20261009.py'));a=importlib.util.module_from_spec(z);z.loader.exec_module(a);m=a.m;RUN=a.RUN;ref=a.reference;sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 report=m.load(m.RUN/'verification-after-wave-94.json');assert(report['verified_new_artworks'],report['verified_existing_artworks_linked'])==(10623,2806);cp=m.load(a.CHECKPOINT);applied=m.load(RUN/(a.KEY+'-applied.json'));assert applied['created']==102 and applied['existing_links']==0 and applied['verification']==report['leeds_cotmania_drawings'];root=m.RUN/'README.md';pin=next(v for v in cp['artifacts'] if v['path']==str(root.relative_to(m.ROOT)));assert sha(root)==pin['sha256'];backup=m.BACKUP/'leeds-drawings-root-readme-before-001.json.gz';assert not backup.exists()
 for name in ['checks-001.json','remaining-research-001.json.gz','next-museum-pass-001.json','README.md','readme-supersessions-001.json','source-availability-001.json','new-source-access-holds-001.json']:assert not(RUN/name).exists()
 logsroot=Path('/Users/vadimdulub/Library/Logs');test=(logsroot/'artline-leeds-drawings-tests-20261009.log').read_text();assert 'Ran 24 tests' in test and test.rstrip().endswith('OK');assert(logsroot/'artline-leeds-drawings-replay-20261009.log').read_text().strip()=='Unchanged replay: zero writes';logs={v.name:dict(path=str(v),sha256=sha(v)) for v in sorted(logsroot.glob('artline-leeds-drawings-*-20261009.log')) if not any(x in v.name for x in ['delivery','checkpoint'])};ctx=m.load(RUN/'comparison-source-context-compact-001.json.gz');identity=m.load(RUN/'identity-002.json.gz');citations=m.load(RUN/'identity-citations-002.json.gz');decisions=m.load(a.REVIEW)['decisions'];caps=[v['capture'] for v in a.r.source_rows()]+[v['capture'] for v in m.load(m.RUN/'native/leeds-additions-20261009/native-probes-001.json')['rows']]+[v['capture'] for v in m.load(RUN/'comparison-native-extra-001.json.gz')['rows']]
 m.save(RUN/'checks-001.json',dict(at=m.now(),new_offline_tests_passed=24,historical_tests_passed=1846,cumulative_verified_tests=1870,historical_tests_rerun=False,replay_zero_writes=True,source_objects_reviewed=104,new_artworks=102,existing_links=0,preserved_existing_gallery_holdings=137,editorial_holds=2,identity_artworks=len(identity['state']['artworks']),identity_citations=len(citations['citations']),verified_native_capture_checks=len(caps),verified_native_raw_bodies=len({v['body_path'] for v in caps}),comparison_raw_bodies=len(ctx['body_references']),comparison_unreconstructed_bodies=len(ctx['unreconstructed_bodies']),logs=logs,other_job_totals_separate=True,source_refinements='Twenty qualified creator/relationship refinements; one unverified1823 inscription qualified. Six individually accessioned mounted papers counted separately; whole-object date uncertainty held for two objects. Met429 is a stopped source,not a successful capture. No images or existing metadata changes.'))
 metpaths=sorted((RUN/'met/captures').glob('*.json'));assert len(metpaths)==1;met=m.load(metpaths[0]);assert met['status']==429;holds=[dict(provider='www.metmuseum.org',url=met['url'],status=429,retrieved_at=met['retrieved_at'],receipt_reference=ref(metpaths[0]),policy='Stop after429; no retry,alternate endpoint,proxy or media workaround in this pass. Existing retained comparison metadata remains explicitly historical.')]
 m.save(RUN/'new-source-access-holds-001.json',dict(at=m.now(),rows=holds,previous_source_hold_reference=cp['new_source_access_hold_reference'],policy='Met429 added; all prior source holds remain active.'))
 m.save(RUN/'source-availability-001.json',dict(at=m.now(),new_source_access_holds=holds,new_source_access_hold_reference=ref(RUN/'new-source-access-holds-001.json'),previous_source_availability_reference=cp['source_availability_reference'],previous_source_hold_reference=cp['new_source_access_hold_reference'],selected_object_reference=ref(RUN/'selected-objects-001.json.gz'),comparison_context_reference=ref(RUN/'comparison-source-context-compact-001.json.gz'),comparison_native_reference=ref(RUN/'comparison-native-extra-001.json.gz'),policy='104 selected Cotmania objects plus exact0552 concordance captured. Bounded search120drawing hits and4remaining watercolour hits,not all744drawings or930catalogue objects. Public frontend search-only config retained. No images or archive pages added.93 comparison bodies verified;36 not reconstructed. Retained Yale raw LIDO etchings distinguish versions. Met429 stopped immediately.'))
 held=[v for v in decisions if v['state']=='editorial_hold'];assert {v['number'] for v in held}=={16,62};oldremaining=m.load(a.checked(cp['remaining_research_reference']));oldq=m.load(a.checked(cp['next_museum_pass_reference']));live=m.load(m.RUN/'after-wave-94.json');by={v['id']:v for v in live['institutions']};selection=m.load(RUN/'object-selection-001.json.gz')
 m.save(RUN/'remaining-research-001.json.gz',dict(at=m.now(),rows=held,review_reference=ref(a.REVIEW),previous_remaining_research_reference=cp['remaining_research_reference'],additional_lead_review_reference=oldremaining['additional_lead_review_reference'],unselected_index_leads=selection['remaining_leads'],gallery_linked=239,gallery_eligible=213,remaining_to_100_linked=0,remaining_to_100_eligible=0,remaining_to_200_linked=0,remaining_to_200_eligible=0,policy='Leeds meets200 in both measures; stop quota-driven expansion here and prioritize under100 museums. Two whole-object date holds,prior missing1973object,four original identity holds,16GACleads/four gaps/two known matches and all earlier queues persist. Nonstandard source date text and unselected hits retained without invented years. No current display inferred.'))
 italian=[dict(v,current_linked=by[v['institution_id']]['works'],current_eligible=by[v['institution_id']]['eligible_works']) for v in oldq['italian_museums']];assert len(italian)==225;excluded=['Glasgow Museums Resource Centre','Kelvingrove Art Gallery and Museum','Burrell Collection','Bristol City Museum & Art Gallery','Imperial War Museum London'];nexttargets=sorted([v for v in live['institutions'] if v['kind']=='museum' and v['status']!='archived' and not v['canonical_institution_id'] and v['works']<100 and v['pending_associations']>0 and v['name'] not in excluded],key=lambda v:(-v['pending_associations'],v['id']))[:20];native_ids=list(dict.fromkeys([v['id'] for v in oldq['native_addition_targets'] if v['id']!=a.IID]));current_ids=sorted({v['id'] for v in oldq['current_museums']}|{a.IID})
 m.save(RUN/'next-museum-pass-001.json',dict(at=m.now(),previous_queue_reference=cp['next_museum_pass_reference'],italian_museums=italian,existing_holding_review_targets=nexttargets,native_addition_targets=[by[iid] for iid in native_ids],completed_target_this_wave=by[a.IID],current_museums=[by[iid] for iid in current_ids],southampton_pdf_leads_reference=oldq['southampton_pdf_leads_reference'],edinburgh_portrait_leads=oldq['edinburgh_portrait_leads'],leeds_selected_metadata_reference=oldq['leeds_selected_metadata_reference'],leeds_selected_lead_review_reference=oldq['leeds_selected_lead_review_reference'],leeds_cotmania_selected_reference=oldq['leeds_cotmania_selected_reference'],leeds_cotmania_extra_selection_reference=oldq['leeds_cotmania_extra_selection_reference'],leeds_drawing_selection_reference=ref(RUN/'object-selection-001.json.gz'),remaining_research_reference=ref(RUN/'remaining-research-001.json.gz'),source_availability_reference=ref(RUN/'source-availability-001.json'),policy='Leeds239linked/213eligible meets200. Prioritize TheBox,York,Harris and other under100 museums using exact native evidence or retained exact-source holding reconciliation; do not exhaust Cotmania. Preserve225Italianmuseum queue and all historical holds. Met429 joins existing provider holds,no bypass. Full all-museum goal active.',database_writes=0))
 counts=collections.Counter(v['facts']['work_type'] for v in decisions if v['state']=='approved_review_only_addition');assert counts=={'watercolor':4,'drawing':98}
 text=f'''# Leeds Art Gallery drawings — 9 October 2026

Added **102 source-backed artworks** from the museum-commissioned [Cotmania catalogue](https://cotmania.org/): **98 drawings and four watercolours**, all in review. Leeds now has **239 linked works, including 213 with eligible pre-1971 creation dates**, up from 137/111. The gallery has reached the preferred 200 target in both measures.

Of 104 selected objects, two remain held: the two-sheet Nautical Subjects group has a securely dated upper drawing but an unresolved lower drawing; the Gillingham Church sheet has a dated recto and an undated boat on its reverse. One 1823 inscription reading is expressly unverified and now qualified. Twenty creator labels preserve the essays' uncertain family attributions, studio labels and relationships to models. Creator lifespans, acquisition years, paper watermarks and source-print dates were not substituted for drawing dates.

Six separately accessioned thumbnail papers on one mount count individually. Multiple sketches or paired sides on one sheet count once. An exact 0552 source check identifies a standing figure, resolving the generic concordance concern for wagon0108a. Yale comparator records describe different etchings. All source titles, original fields and native accession identities remain in the [review](editorial-reviewed-001.json.gz) and [plan](leeds-cotmania-drawings-001-plan-001.json.gz).

**24 offline checks, atomic database readback and zero-write replay passed.** The transaction preserved 1,334 scoped existing artworks and all 13,327 prior campaign records. Raw evidence includes{len(caps)} successful native capture checks and 93 reconstructed comparison bodies; 36 older comparison bodies could not be reconstructed. A Met request returned 429 and was stopped without retry. This limit is recorded; no successful fresh Met capture is claimed. No images, painter links, publication or current-display claims were added.

Campaign totals are **10,623 new artworks and 2,806 reconciled existing works: 13,429 distinct records across 236 institutions**. **{report['after']['museums_below_100']:,} canonical museums remain below 100 linked works**, and **{report['after']['museums_below_200']:,} below 200**. The all-museum goal remains active. [The next queue](next-museum-pass-001.json) prioritizes The Box, York and Harris among other underfilled museums. Every earlier source hold and research queue remains preserved, including Leeds' missing work, prior identity holds and GAC leads.
'''
 m.save(backup,dict(at=m.now(),path=str(root),text=root.read_text(),sha256=sha(root)));(RUN/'README.md').write_text(text);old=root.read_text();intro,rest=old.split('## Added works',1);intro=intro.replace('10,521','10,623').replace('after-wave-93','after-wave-94');root.write_text(intro+'## Added works'+rest+'\n\n## Leeds Art Gallery drawings — wave94\n\nAdded102 selected works in review:98drawings and4watercolours. Leeds239linked/213eligible now exceeds200 in both measures. Two whole-object date holds retained; creator qualifications and separate-paper identity preserved. [Evidence and continuing work](native/leeds-drawings-20261009/README.md). Campaign10,623new +2,806reconciled =13,429distinct across236institutions.24offline checks,atomic readback and zero-write replay passed. Met429 stopped; all earlier queues and source holds persist. Next: under100 museums including TheBox,York,Harris. Full goal active.\n');m.save(RUN/'readme-supersessions-001.json',dict(at=m.now(),changes=[dict(path=str(root.relative_to(m.ROOT)),before_sha256=pin['sha256'],after_sha256=sha(root),backup_path=str(backup),backup_sha256=sha(backup))]));print(json.dumps(dict(documented_new_records=102,documented_existing_links=0,held=2,tests=24,institutions_expanded=236,goal_complete=False)),flush=True)
if __name__=='__main__':main()
