"""Document wave97 counts, source gaps and every inherited research queue."""
import collections,csv,gzip,hashlib,importlib.util,json
from pathlib import Path
z=importlib.util.spec_from_file_location('a',Path(__file__).with_name('museum-expansion-harris-box-additions-apply-v2-20261009.py'));a=importlib.util.module_from_spec(z);z.loader.exec_module(a);m=a.m;RUN=a.RUN;ref=a.reference;sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 report=m.load(m.RUN/'verification-after-wave-97.json');assert(report['verified_new_artworks'],report['verified_existing_artworks_linked'])==(10854,3035);cp=m.load(a.CHECKPOINT);applied=m.load(RUN/(a.KEY+'-applied.json'));assert applied['created']==71 and applied['verification']==report['harris_box_native_highlights'];root=m.RUN/'README.md';pin=next(v for v in cp['artifacts'] if v['path']==str(root.relative_to(m.ROOT)));assert sha(root)==pin['sha256'];backup=m.BACKUP/'harris-box-additions-root-readme-before-001.json.gz';assert not backup.exists()
 for name in ['checks-001.json','remaining-research-001.json.gz','next-museum-pass-001.json','README.md','readme-supersessions-001.json','source-availability-001.json','new-source-access-holds-001.json']:assert not(RUN/name).exists()
 logsroot=Path('/Users/vadimdulub/Library/Logs');test=(logsroot/'artline-harris-box-additions-tests-20261009-002.log').read_text();assert 'Ran 31 tests' in test and test.rstrip().endswith('OK');assert(logsroot/'artline-harris-box-additions-replay-20261009-001.log').read_text().strip()=='Unchanged replay: zero writes';logs={v.name:dict(path=str(v),sha256=sha(v)) for v in sorted(logsroot.glob('artline-harris-box-additions-*-20261009-*.log')) if not any(x in v.name for x in ['delivery','checkpoint'])};ctx=m.load(RUN/'comparison-source-context-002.json.gz');identity=m.load(RUN/'identity-002.json.gz');citations=m.load(RUN/'identity-citations-002.json.gz');decisions=m.load(a.REVIEW)['decisions'];caps=[]
 for path in sorted(RUN.glob('*/captures/*.json')):
  rc=m.load(path);body=path.with_suffix('.body.gz');raw=gzip.decompress(body.read_bytes());assert hashlib.sha256(raw).hexdigest()==rc['sha256'];caps.append(dict(receipt_reference=ref(path),body_reference=ref(body),url=rc['url'],status=rc['status']))
 assert len(ctx['body_references'])==552 and len(ctx['unreconstructed_bodies'])==260
 m.save(RUN/'checks-001.json',dict(at=m.now(),new_offline_tests_passed=31,historical_tests_passed=1930,cumulative_verified_tests=1961,historical_tests_rerun=False,replay_zero_writes=True,selected_candidates=88,new_artworks=71,existing_links=0,already_catalogued=3,editorial_holds=14,source_fact_holds=8,unknown_date_additions=50,date_eligible_additions=21,identity_artworks=len(identity['state']['artworks']),identity_citations=len(citations['citations']),capture_status_counts=dict(collections.Counter(str(v['status']) for v in caps)),comparison_raw_bodies=552,comparison_unreconstructed_citations=260,logs=logs,other_job_totals_separate=True,source_refinements='Paper taxonomy does not establish drawing technique;5work types unknown.1777commission not exact completion.Qualified cast,studio copy,former attribution and date uncertainty explicit. Full Cogle creator-pool review caught possible duplicate missed by lexical comparison.'))
 hold=m.load(RUN/'watercolour-world-access-hold-001.json');newholds=[dict(provider=hold['provider'],state=hold['state'],reason=hold['reason'],evidence_reference=ref(RUN/'watercolour-world-access-hold-001.json'))];m.save(RUN/'new-source-access-holds-001.json',dict(at=m.now(),rows=newholds,previous_source_hold_reference=cp['new_source_access_hold_reference']))
 m.save(RUN/'source-availability-001.json',dict(at=m.now(),new_source_access_holds=newholds,new_source_access_hold_reference=ref(RUN/'new-source-access-holds-001.json'),previous_source_availability_reference=cp['source_availability_reference'],previous_source_hold_reference=cp['new_source_access_hold_reference'],native_captures=caps,comparison_context_reference=ref(RUN/'comparison-source-context-002.json.gz'),pdf_gap_reference=ref(RUN/'reynolds-guide-visual-gap-001.json'),policy='Public read-only WordPress view routes were advertised by museum API roots. No private fields,edit context,revision or credentialed endpoints used. Harris64curatedart objects are a small subset of800+oil paintings and6000+works on paper. Most current narratives omit creation dates/full creator names. Three sampled object pages have the same gaps. Box bounded curated article searches deduplicated by native ID. First ReynoldsPDF404;second guide web text available but6screenshots failed cache miss. PDF discovery only. WatercolourWorld robots refusal stopped;all earlier provider holds persist. No image downloads/attachments.'))
 held=[v for v in decisions if v['state'] in ['editorial_hold','source_fact_hold']];assert len(held)==22;oldq=m.load(a.checked(cp['next_museum_pass_reference']));live=m.load(m.RUN/'after-wave-97.json');by={v['id']:v for v in live['institutions']};museums=[by[iid] for iid in a.IIDS]
 m.save(RUN/'remaining-research-001.json.gz',dict(at=m.now(),rows=held,already_catalogued=[v for v in decisions if v['state']=='already_catalogued'],review_reference=ref(a.REVIEW),previous_remaining_research_reference=cp['remaining_research_reference'],current_museums=museums,source_gap='Harris native API exposes curated narrative objects but no creation-date/creator headers; fuller object metadata needed. Box3morelinked needed for100,103for200. Harris68morelinked needed for200;50newunknown-date records need further research. Neither museum reaches100eligible dates.',named_creator_reconciliation='Source surnames remain unlinked;native biographies and independent primary object evidence should resolve full names in a separately audited enrichment.',exclusions=[dict(source='HarrisArtWellbeing2023–24',reason='19contemporary workshop/community response entries not selected'),dict(source='Box2478/5935/5957',reason='Contemporary EchoesofUs objects excluded;2022Shaw,2018Xa and1980sAllets explicitly beyondcutoff'),dict(source='Box2021 AugustusKeppel',reason='Explicit NationalMaritimeMuseum exhibition loan,notBoxholding'),dict(source='Box1956 ArmadaPortrait',reason='Explicit WoburnAbbey exhibition loan,notBoxholding'),dict(source='Reynolds1755sittersbook',reason='Archival appointment book not counted as artwork or as121sketchbookpages')],policy='No quotas override evidence.3already-linked works receive no duplicate record or metadata overwrite. Keep14current identity/holding holds,8fact/scope holds,York17holds,priorBox/York/Harris17holds,225Italianmuseums and every olderqueue.'))
 italian=[dict(v,current_linked=by[v['institution_id']]['works'],current_eligible=by[v['institution_id']]['eligible_works']) for v in oldq['italian_museums']];assert len(italian)==225;native_ids=list(dict.fromkeys([a.IIDS[1],a.IIDS[0]]+[v['id'] for v in oldq['native_addition_targets']]));queue=dict(oldq);queue.update(at=m.now(),previous_queue_reference=cp['next_museum_pass_reference'],italian_museums=italian,native_addition_targets=[by[iid] for iid in native_ids],current_museums=[by[v['id']] for v in oldq['current_museums']],current_pass_museums=museums,remaining_research_reference=ref(RUN/'remaining-research-001.json.gz'),source_availability_reference=ref(RUN/'source-availability-001.json'),policy='Prioritize TheBox97/43 toward100linked,then200;Harris132/80toward200linked and creation-date research. Continue CityArtCentre88 andotherunder100museums. York250/228alreadymeets200. Preserveallolderinstitutions,225Italianmuseums,sourceholdsandidentityqueues. Noexhaustivecatalogue/image downloads;fullgoalactive.',queue_database_writes=0);queue.pop('completed_target_this_wave',None);m.save(RUN/'next-museum-pass-001.json',queue)
 verified=applied['verification'];assert verified['protected_existing_records']==1458 and verified['prior_campaign_records_preserved']==13818
 text=f'''# Harris Museum and The Box additions — 9 October 2026

Added **71 real artworks in review** from current museum collection pages and articles: **49 Harris Museum** and **22 The Box**. All have source-backed collection associations. Creation-date eligibility remains a separate measure.

| Museum | Linked before | Linked now | Pre-1971 dated before | Pre-1971 dated now |
| --- | ---: | ---: | ---: | ---: |
| Harris Museum | 83 | **132** | 72 | **80** |
| The Box, Plymouth | 75 | **97** | 30 | **43** |

**21 additions have supported eligible creation dates; 50 remain undated in review.** Five works on paper retain unknown technique because the collection category does not distinguish drawing, watercolour and print. Source surnames remain explicit unlinked creator labels pending fuller evidence. No biographies, creation years, artist authorities or image attachments were invented.

Reviewed 88 candidates plus eight source-fact/scope holds. Three artworks already in the catalogue were preserved without duplication. Fourteen further candidates remain held for physical-version or holding checks. The [decision ledger](editorial-reviewed-001.json.gz) retains all evidence and reasons. Cogle’s possible duplicate was caught by reviewing the full creator group even though title similarity missed it.

Selected examples include the Harris’s [*Puck*](https://theharris.org.uk/collection-item/puck/), dated 1841 by its [acquisition funder](https://www.artfund.org/our-purpose/art-funded-by-you/puck), and The Box’s [historical North Hall collection paintings](https://theboxplymouth.com/collections-insight-a-new-display-in-north-hall/). The Harris’s *Gloria Victis* retains the 1880s date of its cast, rather than the earlier model date. The Box’s *Age of Innocence* remains a studio copy with its own unresolved date. One Reynolds sketchbook counts once, not once per drawn side. The hidden portrait beneath his self-portrait remains part of the same canvas.

**31 offline checks, atomic database readback and zero-write replay passed.** All 1,458 scoped existing records and all 13,818 earlier campaign records were preserved. The transaction repeated the bounded identity comparison of 29,734 artwork rows and 61,322 citations. Retained comparison evidence includes 552 raw bodies; 260 citation bodies were not reconstructed and are not claimed as fresh confirmation. An initial transaction rejected empty date labels and rolled back completely; the verified revision supplies “Creation date under review” while preserving unknown numeric dates. Both attempts and rollback evidence are retained.

Harris currently exposes only 64 curated art entries through its public collection interface, many with sparse metadata. The Box’s historical articles provide useful selected objects, but loans were excluded from holdings. Watercolour World refused automated access and was not retried. The older Reynolds guide’s visual pages could not be obtained; its retained text remains discovery evidence. No PDF illustrations or catalogue images were downloaded.

Campaign totals: **10,854 new artworks + 3,035 reconciled existing artworks = 13,889 distinct records across 239 institutions**. **{report['after']['museums_below_100']:,} canonical museum entries remain below 100 linked works**; **{report['after']['museums_below_200']:,} remain below 200**. The Box still needs three supported additions to reach 100, while Harris needs 68 to reach 200. Neither has 100 date-eligible artworks yet. [The continuing queue](next-museum-pass-001.json) preserves all prior museums and unresolved cases. The full goal remains active.
'''
 m.save(backup,dict(at=m.now(),path=str(root),text=root.read_text(),sha256=sha(root)));(RUN/'README.md').write_text(text);old=root.read_text();intro,rest=old.split('## Added works',1);intro=intro.replace('10,783','10,854').replace('13,818','13,889').replace('1,229','1,228').replace('after-wave-96','after-wave-97').replace('Every addition remains in review, with source-backed museum holdings and eligible creation dates.','Every addition remains in review, with source-backed museum holdings; creation-date eligibility is tracked separately. The latest pass adds 21 works with eligible dates and 50 with dates still unknown.');table='| Distinct new-record campaign total | **10,783** | **217 collections** |';assert table in rest;rest=rest.replace(table,'| Harris Museum and The Box — selected native highlights | 71 | 2 museums |\n| Distinct new-record campaign total | **10,854** | **219 collections** |',1);root.write_text(intro+'## Added works'+rest+'\n\n## Harris Museum and The Box additions — wave97\n\nAdded 71 selected real artworks in review: 49 Harris and 22 Box. Harris now has 132 linked / 80 date-eligible works; The Box has 97 / 43. Of the new records, 21 have supported eligible dates and 50 retain unknown dates. Three existing works were preserved, with 14 version/holding and eight source-fact/scope holds. Thirty-one offline checks, atomic readback and zero-write replay passed. Existing metadata, images, statuses and all 13,818 earlier campaign records were preserved. [Evidence, limitations and continuing queue](native/harris-box-additions-20261009/README.md). Campaign: 10,854 new + 3,035 reconciled = 13,889 distinct artworks across 239 institutions. Still 1,228 canonical museums below 100 linked works. Next: complete The Box minimum and continue Harris toward 200. All earlier queues and source holds remain; full goal active.\n');m.save(RUN/'readme-supersessions-001.json',dict(at=m.now(),changes=[dict(path=str(root.relative_to(m.ROOT)),before_sha256=pin['sha256'],after_sha256=sha(root),backup_path=str(backup),backup_sha256=sha(backup))]));print(json.dumps(dict(documented_new_records=71,documented_existing_links=0,held=22,tests=31,institutions_expanded=239,goal_complete=False)),flush=True)
if __name__=='__main__':main()
