"""Document wave77 and preserve unfinished museum research."""
import collections,hashlib,importlib.util,json
from pathlib import Path
z=importlib.util.spec_from_file_location('a',Path(__file__).with_name('museum-expansion-verbania-apply-20261008.py'));a=importlib.util.module_from_spec(z);z.loader.exec_module(a);m=a.m
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 report=m.load(m.RUN/'verification-after-wave-77.json');assert report['verified_new_artworks']==10259 and report['verified_existing_artworks_linked']==940;p,d=a.validate_plan()
 with m.connect() as db:verified=a.verify(db,p,d)
 rootlogs=Path('/Users/vadimdulub/Library/Logs');test=(rootlogs/'artline-verbania-tests-20261008.log').read_text();assert 'Ran 14 tests' in test and test.rstrip().endswith('OK');assert (rootlogs/'artline-verbania-replay-20261008.log').read_text().strip()=='Unchanged replay: zero writes'
 logs={v.name:dict(path=str(v),sha256=sha(v)) for prefix in ['artline-verbania-','artline-italy-sixth-'] for v in sorted(rootlogs.glob(prefix+'*-20261008.log')) if 'delivery' not in v.name and 'checkpoint' not in v.name}
 m.save(a.RUN/'checks-001.json',dict(at=m.now(),new_offline_tests_passed=14,historical_tests_passed=1470,cumulative_verified_tests=1484,historical_tests_rerun=False,replay_zero_writes=True,source_objects_reviewed=161,new_artworks=0,existing_links=155,editorial_holds=6,logs=logs,other_job_totals_separate=True,reporting_correction_reference=a.reference(a.RUN/'report-correction-001.json')))
 ds=m.load(a.REVIEW)['decisions'];held=[v for v in ds if v['state']=='editorial_hold'];assert len(held)==6
 sixth=a.s.start.RUN;sc=m.load(sixth/'source-capture-001.json');assert sc['requests_stopped'] and sc['failure_counters']=={'dati.cultura.gov.it':3};disc=m.load(sixth/'three-museum-discovery-001.json.gz');assert len(disc['rows'])==515
 m.save(a.RUN/'remaining-research-001.json.gz',dict(at=m.now(),rows=held,review_reference=a.reference(a.REVIEW),previous_italian_352_notice_queue_reference=a.reference(a.prior.RUN/'remaining-research-001.json.gz'),pending_515_source_candidates_reference=a.reference(sixth/'three-museum-discovery-001.json.gz'),source_access_hold_reference=a.reference(sixth/'source-capture-001.json'),policy='Six Verbania objects remain pending. Preserve previous352 Italian notices and 515 selected Pavia/Poldi/Sabauda leads. No fresh object facts obtained in the three timed-out ArCo requests. All earlier source-access holds remain.'))
 cp=m.load(a.CHECKPOINT);prevq=cp['next_museum_pass_reference'];q=m.load(m.ROOT/prevq['path']);live=m.load(m.RUN/'after-wave-77.json');by={v['id']:v for v in live['institutions']};nextm=[]
 for v in q['italian_museums']:
  cur=by[v['institution_id']]
  if cur['eligible_works']<100:nextm.append(dict(v,current_linked=cur['works'],current_eligible=cur['eligible_works']))
 candidates=[v for v in live['institutions'] if ('Laing' in v['name'] or v['name']=='National Army Museum') and v['works']<100 and not v['canonical_institution_id']]
 m.save(a.RUN/'next-museum-pass-001.json',dict(at=m.now(),previous_queue_reference=prevq,italian_museums=nextm,existing_holding_review_targets=candidates,remaining_research_reference=a.reference(a.RUN/'remaining-research-001.json.gz'),policy='Continue wider goal via saved source-backed existing-holding evidence for Laing and National Army Museum, subject to current identity and qualifier review. Italian source endpoints currently held after recorded failures; do not restart failed capture loop or bypass access restrictions. Museum100 minimum,200 preferred; no quota-based approval.',database_writes=0))
 sixthtext='''# Sixth Italian minimum research — 8 October 2026

Selected 515 source candidates: 155 Pavia, 180 Poldi Pezzoli and 180 Galleria Sabauda. These are unapproved index leads, not new artwork facts. The exact initial database scope and all discovery rows are preserved.

The first three selected ArCo requests timed out while connecting to dati.cultura.gov.it. Requests stopped after those three failures; no object pages or response facts were captured. The Lombardia native object request failed TLS certificate verification; TLS was not disabled. Browser attempts at selected national catalogue and regional object pages failed; the Musei Reali collection page returned 403. Do not bypass those access outcomes or restart the failed capture loop. Existing saved evidence remains available for other museum work.

No database changes or image downloads resulted from this research. Continue with an independently available source or reviewed cached object evidence; low source availability does not establish a museum collection size. The [Verbania pass](../verbania-holdings-20261008/README.md) separately reconciled 155 already catalogued artworks from saved exact primary evidence.
'''
 assert not (sixth/'README.md').exists();(sixth/'README.md').write_text(sixthtext)
 text='''# Museo del Paesaggio, Verbania — 8 October 2026

Accepted **155 museum-holding links for existing local artwork records**, moving the museum from **0 to 155 linked works**, including **140 with eligible creation dates**. No new artwork records were created. Fifteen approved records retain unknown or qualified dates. Six objects remain pending: two malformed date strings and four unresolved physical-identity comparisons.

The original national-catalogue records name the exact Verbania museum URI, current-location node, physical site and city. Their “proprietà privata” label concerns ownership; it does not negate the separately documented holding. The owner URI and legal labels remain literal evidence. This review makes no ownership or current-display assertion. The source was captured 5 October 2026; review occurred 8 October 2026.

All 161 pending records were reviewed by exact catalogue identifier, supplied creator/title/date and unique OA inventory. The [editorial decisions](editorial-reviewed-001.json.gz) record 88% editorial confidence for the 155 accepted links, with individual comparison notes and limitations; confidence is not a calibrated probability. Source facts were reconstructed from 58 hash-verified original response bodies. Fresh comparison covered 3,154 existing artworks and 6,834 citations. Available source context for same-creator comparisons was reconstructed from 20 response bodies plus structured citation facts; 3 bodies overlap the target captures, giving 75 distinct response bodies overall. Homonymous creators, different supports, specific subjects and separate inventories were distinguished. Multiple figures on one support count once. Source typos and alternative-attribution history remain preserved.

The [transaction plan](verbania-existing-holdings-001-plan-001.json.gz) and [application receipt](verbania-existing-holdings-001-applied.json) verify 155 new citations, 155 accepted holding assertions and 155 superseded pending assertions. The old assertions and citations retain their original evidence. Only the artwork museum projection and update timestamp changed. All other catalogue fields, dates, creator links, images and historical statuses were checked unchanged across 3,154 scoped records and 11,044 prior campaign records. Fourteen offline guard tests, exact readback and zero-write replay passed. No commits or deployment.

The [remaining research](remaining-research-001.json.gz) preserves 6 Verbania holds, references 352 earlier Italian notices and 515 newly selected Pavia/Poldi/Sabauda leads whose source capture failed. Their endpoint holds remain in place. The [next-museum queue](next-museum-pass-001.json) retains underfilled Italian museums and identifies Laing/National Army holdings for fresh review.

Campaign totals: **10,259 new artworks plus 940 reconciled existing holdings across '''+str(report['institutions_with_new_records_or_reconciled_holdings'])+''' institutions**. **'''+format(report['after']['museums_below_100'],',')+''' canonical museums remain below 100 linked works**, and '''+format(report['after']['museums_below_200'],',')+''' remain below 200. The goal is unfinished. Backups are under the designated Application Support directory. Next pass must protect 11,199 distinct campaign artwork records.
'''
 assert not (a.RUN/'README.md').exists();(a.RUN/'README.md').write_text(text)
 root=m.RUN/'README.md';pin=next(v for v in cp['artifacts'] if v['path']==str(root.relative_to(m.ROOT)));assert sha(root)==pin['sha256'];before=root.read_text();split=before.index('\n## Added works');intro=before[:split].replace('785 existing','940 existing').replace('expand 214 institutions','expand '+str(report['institutions_with_new_records_or_reconciled_holdings'])+' institutions').replace('1,247',format(report['after']['museums_below_100'],',')).replace('1,555',format(report['after']['canonical_museums'],',')).replace('after-wave-76','after-wave-77').replace('Detroit and Princeton passes','Detroit, Princeton and Verbania passes')
 contents=intro+before[split:]+'\n\n## Verbania holding reconciliation\n\nThe [Verbania review](native/verbania-holdings-20261008/README.md) accepted **155 existing-artwork museum links**, bringing Museo del Paesaggio to **155 linked works / 140 with eligible dates**. Six unresolved objects remain pending. Private ownership labels remain separate from recorded holdings. No artwork metadata, images or historical statuses changed.\n\nThe [wave77 verification](verification-after-wave-77.json) records **10,259 additions and 940 holding reconciliations across '+str(report['institutions_with_new_records_or_reconciled_holdings'])+' institutions**. '+format(report['after']['museums_below_100'],',')+' canonical museums remain below 100 linked works. The all-museum goal remains active.\n'
 backup=m.BACKUP/'verbania-root-readme-before-001.json.gz';assert not backup.exists();oldhash=sha(root);m.save(backup,dict(at=m.now(),path=str(root.relative_to(m.ROOT)),sha256=oldhash,text=before));root.write_text(contents);m.save(a.RUN/'readme-supersessions-001.json',dict(at=m.now(),changes=[dict(path=str(root.relative_to(m.ROOT)),before_sha256=oldhash,after_sha256=sha(root),backup_path=str(backup),backup_sha256=sha(backup))]))
 print(json.dumps(dict(documented_existing_links=155,campaign_new=10259,campaign_links=940,institutions=report['institutions_with_new_records_or_reconciled_holdings'],remaining_below100=report['after']['museums_below_100'],next_italian_museums=len(nextm),next_existing_holding_targets=[v['name'] for v in candidates])),flush=True)
if __name__=='__main__':main()
