#!/usr/bin/env python3
"""Individual physical-object decisions for five underfilled French museums."""
import copy,importlib.util,json
from pathlib import Path
s=importlib.util.spec_from_file_location('identity',Path(__file__).with_name('museum-expansion-five-museums-identity-20261008.py'));identity=importlib.util.module_from_spec(s);s.loader.exec_module(identity)
f=identity.f;m=f.m;RUN=f.RUN;ref=f.ref;checked=f.checked
CANDIDATES=RUN/'native-candidates-001.json.gz';IDENTITY=RUN/'native-identity-001.json.gz';CITATIONS=RUN/'identity-citations-001.json.gz'
NOTES={
4:'Arnavielle colored etching of Clamecy; existing Arnavielle canvas depicts Rouen. Literal1932 belongs to this print.',
5:'One separately accessioned faience plate, not all plates of the series. Preserve the source warning that Audin attribution rests on oral tradition; no personal artist authority linked.',
6:'Charles Audran engraved portrait of Ange de Joyeuse; broad Audran leads are other subjects and creators. No corresponding named sitter object.',
7:'Alexandre de Bar etched priest in forest; no corresponding object in the broad Bar comparison. Old NG301 retained alongside current inventory.',
8:'One individually catalogued lithographic sheet extracted from Le Nivernois. Separate title, measurements and inventory; do not import the entire book or related Billault sheet.',
9:'One lithographic mineral-water view of Pougues; Bussiere-name leads by Gaston are different creators and subjects.',
11:'One Bautz lithographic portrait of Guy Coquille. No creator/title/native counterpart; literal support measurements retained.',
12:'One Baxter color print of the1851 London exhibition, not the exhibition objects depicted. Other Baxter works show different subjects.',
13:'One hand-colored Becquet lithograph with varnish highlights. Watercolor treatment does not make it an original watercolor; Cereghetti merchant role retained.',
14:'One Baugean engraving after Bence of a Nevers gate; no matching creator/title/native record. Osterwald publisher remains in source label.',
15:'One Baugean etching of the house of Adam Billaut, distinct subject from the Nevers gate. Preserve both maker roles.',
18:'One lithographic sheet after Blondel,17.4 by12cm. Existing named marshal portrait is an oil canvas73 by57cm. Source explicitly identifies another similar impression NG999.0.137; this inventory is .138 and only this physical sheet is selected.',
19:'One intaglio portrait of General Ducrot by Bocourt; no same named sitter/native counterpart.',
20:'One1874 Mac-Mahon lithograph; Chapon-family comparison results have other named creators and subjects. Preserve all contributor roles.',
22:'One Thierry Freres lithograph after Louis Leopold Boilly depicting Mme A. Dupin. No corresponding named sitter/native work in the creator comparison.',
23:'One1815 Claussin etching after Boissieu; several represented figures are one measured sheet, not multiple artworks.',
24:'One Girardet engraved Fauchet portrait after Bonneville; source records related NG242 as similar, this separately inventoried sheet is NG243. Retain literal1791 and source prototype narrative together.',
25:'One Lorieux engraved Chaumette portrait after Bonneville; other Bonneville portraits depict Lameth and Auger, different named sitters.',
26:'One1852 Masson print after Bonvin, whose source painting is dated1850. Preserve print date1852 and the after attribution, without assigning the painting date.',
28:'One Bouroux1908 etching of the mill geese; no existing creator/title/native counterpart.',
29:'One1871 Nevers chromolithograph by Bourra and Barthe & Brulfert. A broad Barthe-name watercolor portrait is another subject and medium.',
32:'One intaglio portrait of Henri Brisson by Brun/Tolmer. No same sitter object; broad Brun leads are other subjects.',
34:'One lithograph after Bonhomme of the Fouchambault forges. The1840 Salon painting is a prototype, not this paper object; retain roles and source narrative.',
35:'One1844 Bonhomme/Desrosiers portrait of Dufetre. Source dimensions contain labels without values; retain that literal text and do not invent measurements.',
40:'One1863 Delauney drypoint after Cambiaso. Existing Cambiaso drawings depict other subjects; preserve current and former accession.',
42:'One1924–25 Carlegle woodcut; exact mythological-scene titles belong to other creators and drawing/painting media. Preserve the two-year range.',
44:'One Benassit lithograph published in Le Boulevard1862; the existing Benassit Absinthe is a different composition. One sheet, not the newspaper series.',
45:'One1968 Jacqueline Besson felt-tip drawing of George reading. Distinct from1970 table drawing in size, date and accession; other Besson-name works do not establish an artist link.',
49:'One1867 Bracquemond etching after Courbet. The existing Young Ladies of the Village is a194.9 by261cm oil canvas; this32 by48.5cm paper sheet is a separate physical version.',
52:'One46.5 by38cm canvas attributed to Brigot. Other Courbet portraits are a110.4 by75.3cm Pata canvas and a Manet paper work. Preserve attributed-to qualification.',
53:'One Clesinger pencil/charcoal sheet depicting pines on Sainte-Marguerite. Existing Rome view and flower sheet have different places/subjects and supports.',
54:'One Cougny terracotta seated Courbet statuette; source documents its1855 Salon label. The marble bust mentioned is another work, not this object.',
59:'One Daumont etching after Courbet,63 by72.5cm sheet. Existing Courbet deer painting is174 by209cm oil canvas; retain print date and after role.',
60:'One Gautier lithographic portrait of Champfleury on chine-colle. Separate from Bracquemond etching selected for hold and the Courbet oil prototype. Source calls it both lithograph and eau-forte: retain generic print and literal medium, not an invented technical correction.',
61:'One Gill ink/color-pencil drawing of Courbet with palette; separate from the landscape-format beer-mug drawing by dimensions, composition and inventory.',
62:'One Gill/Destouches Courbet mason lithograph for Pantheon charivarique. Specific subject and accession separate it from palette drawings.',
63:'One Henner pencil copy after Courbet,33.2 by24.5cm. Courbet original is100 by82cm oil canvas; Vion print is also another version. Current source only removes a duplicated Domaine category; source history preserved.',
64:'One Molinard1897 chalk/pencil portrait of Theodore Duret. Same-title existing record is by Manet; no Molinard counterpart.',
66:'One Ribot black-pencil study of hands. Same-title Ingres, Picasso, Degas, Lesage and Carpeaux works have different makers and physical descriptions.',
67:'One Slom graphite villa view dated1879. Existing Slom Cary Blank is an oil portrait, a different subject and medium.',
68:'One Vernier lithograph after Courbet on51 by72.4cm paper. Source destruction narrative concerns the Dresden painting, not this held print. Existing young stonebreaker is a separate Courbet drawing.',
69:'One Vion1887 etching after Courbet. Keep1887 print date, not1845–46 oil prototype date; separate from the Henner pencil version.',
70:'One1970 Jacqueline Besson felt-tip drawing of George at his table, within cutoff. Distinct from her1968 reading sheet and existing oil-on-cardboard Besson scene.',
72:'One Gill ink/color-pencil drawing for La Lune, Courbet with palette and beer mugs. Different landscape format and accession from palette-only sheet.',
73:'One Slom1877 charcoal deathbed portrait of Courbet. His existing Cary Blank canvas depicts another sitter; Proudhon deathbed print is another sitter, maker and medium.',
74:'One Francesco Amato Holy Family etching. Broad Amato results have other named creators and landscapes; no corresponding print.',
76:'One Audran engraved decorative border glorifying Seguier,208 by176mm. Le Brun chancellor portrait is the related subject/prototype, not evidence of the same border sheet.',
77:'One Barata seventeenth-century etching of ruins, shepherds and goats. No creator/title/native counterpart.',
79:'One separately catalogued sheet from the twelve marine prints, with its own plate measurements and inventory. Count this harbor view once, not the full suite.',
80:'One Baudouins1691 landscape etching with couple and castle. Preserve Van der Meulen publisher role verbatim without creating an artist authority or inferring a personal production date.',
81:'One anonymous reversed copy after Bellange, explicitly distinguished by source as a separate print version. Preserve all three titles, seventeenth-century date and unknown copyist.',
82:'One Bergeret nineteenth-century lithograph about Poussin youth. Existing Montaigne childhood depicts another person; print state remains unknown.',
83:'One Bosse/Mellan1641 Howel portrait. Source identifies the described third state and joint techniques; other Mellan portraits depict different named sitters. Count one sheet, not four states.',
85:'One anonymous control proof pulled before1950 from an older Boucher plate. Use literal first-half twentieth-century creation range, not1630–34 prototype. Separate inventory and described control-proof state; no contemporary maker invented.',
86:'One1669 Louis Boullogne the Elder Holy Family etching with column,170 by238mm image. Other Boullogne results are different works or younger-family creators. Preserve full compound title.',
87:'One1675 Louis Boullogne the Elder Virgin-and-curtain etching,200 by158mm plate. Separate from the1669 landscape-format column sheet; one physical object despite two title variants.',
88:'One anonymous reduced reversed copy of Bourdon Departure of Jacob,103 by77mm plate. Existing Return of Jacob is another composition and27.7 by20.2cm sheet. Preserve copyist anonymity and literal century.',
92:'One nineteenth-century Bracquemond print after Granet, Gazette des Beaux-Arts edition. State and image dimensions are unknown; retain literal mount-only dimensions and do not invent either.',
99:'One vertically formatted engraved sheet,153 by131mm image. The plural book title does not authorize adding a whole book or one record per sultan; source explicitly describes one feuille.',
100:'One portrait sheet of Petrus Apianus attributed to Johann Theodor de Bry; preserve qualification. Existing Edith Bry works have another creator and subject.',
101:'One1896 Bussiere/Keller et Guerin faience vase,113.5cm tall,77.2cm diameter. Ceramic type derives from explicit vessel denomination, ceramic domain and fired-clay medium; not a painting inferred from title.',
102:'One Samuel Boissiere circular Holy Family etching,151mm diameter. Broad Galtier-Boissiere paintings have another creator and medium.',
106:'One Caylus character-head etching,129 by96mm sheet, inventory3608. Separate physical sheet from165 by134mm Vasse-related plate3607 and the3610 group held for further review.',
107:'One Caylus etching of Amphion after Charles Antoine Coypel; no corresponding creator/title/native work. Preserve painter and engraver roles.',
109:'One Caylus/Vasse character-head etching,165 by134mm plate, inventory3607. Separate from3608 sheet and3610 group; retain explicit latter-half eighteenth-century range.',
111:'One Chadel1936 woodcut printed in Japanese manner on141 by186mm paper. Same-title works have other makers. Source montage units look inconsistent (485 by318cm); retain literal text without inventing a correction.',
112:'One separately mounted engraved frontispiece for Maimbourg iconoclast history,208 by158mm image. Count sheet only;1674–75 range preserved alongside1674 book publication evidence.',
113:'One Chauveau/Lochon preaching illustration,216 by164mm image. The book remains unidentified; one individually inventoried print with explicit1676 source date.',
114:'One Chauveau/Richer frontispiece for Lesclache,190 by140mm image. Preserve source creation1652 and historical book publication1651 separately; both precede cutoff, no silent date rewrite.',
115:'One Chauveau/Tournier prodigal-son illustration,213 by164mm image. Same-title records are other creators and paintings; the unknown publisher remains literal.',
116:'One Chauveau illustration of Aeneas in Felicity from Book6, with own inventory and271 by187mm plate. Do not count the book or referenced companion sheets; retain1649–50 creation range.',
117:'One Chauveau vignette extracted from Boileau1674, source describes second state with maker name. One measured plate sheet, not both states.',
118:'One1677 Chauveau Annunciation etching/engraving,169 by112mm plate. Exact-title results have other named creators and paint supports; no matching print.',
119:'One Berchem oil study on paper mounted on canvas,30 by29cm, before1679. Source explicitly distinguishes it from the1679 finished shepherd painting. Title says sheep while description says goats; preserve both statements without rewriting subject.',
120:'One1856 James Bertrand painted copy after Hamman,46 by54cm canvas. Existing Hamman Padua painting is97 by129cm and another physical version; retain copy role and source reference to a possible lithographic intermediary.',
121:'One Bonnart1696 hand-colored/gilded portrait print of Beatrix,38 by24cm. Other Bonnart record depicts Louis XIV on canvas. Historical exhibition remarks do not create an on-view claim.',
124:'One Ernest Jean Chevalier canvas of La Rochelle basin,88 by118cm, source before1914. Other Chevalier-name results do not match this specific harbor/native object.',
125:'One Cornillet beer-drinker costume drawing,2021.7.31,25.8 by17.9cm. Separately catalogued member of a32-drawing acquisition, not the whole lot; other Cornillet sheets have distinct costumes and inventories.',
127:'One Gray nineteenth-century canvas of a meeting at a bivouac,73 by92.5cm, inventory96.1.5. Description of musketeers in snow differs from the companion message scene96.1.4; no existing matching Gray object.',
128:'One Hadol1856 watercolor/ink caricature drawing of resting bohemians,26 by16cm. Source describes the artist-drawn mat; count one object, not represented imperial family members.',
130:'One Jean-Antoine Marc1819 Saint-Etienne view,2021.6.1,19 by24.5cm. Individually dated and measured sheet from a15-drawing purchase; broad Marc-name results are other creators/subjects.',
131:'One Nilouss still life with daisies and ashtray,50 by61cm canvas, before1943. Nilus/Nilous/Nilouss aliases searched; existing blue crockery and peppers is a different still life38.1 by61.2cm.',
132:'One Petitjean Rochebonne/Saint-Malo coastal canvas45 by64cm, before1913. Existing Flessingue ramparts depict another place and132 by200cm canvas.',
134:'One Charles Wittmann1901 charcoal peasant portrait,74 by55cm image. Source documents the sheet in a1909 atelier photograph. Existing Longchamp and boulevard paintings show other subjects; Ernest is another maker.',
138:'One Cornillet Swiss-guard costume drawing Vedette,2021.7.30,25.9 by17.9cm. Separate measured sheet in32-drawing acquisition, distinct from beer-drinker and Absinthe costumes.',
139:'One Gray nineteenth-century Message canvas70 by90cm,96.1.4. Separate from73 by92.5cm bivouac canvas96.1.5, with different title/composition.',
141:'One Marc1819 Point du Jour study,2021.6.2,19.5 by24.3cm. Source dates drawing1August1819; later calvary monuments in narrative are not creation dates. One measured sheet of15 purchased.',
142:'One Nilouss Contrexeville park study on16 by22cm card, before1943. Different site/support from his Paris canvas and existing still life; alias scope retained.',
143:'One Charles Wittmann Pont Marie oil canvas64.5 by65.5cm, before1931, described floating workshops on the Seine. Existing boulevard painting51 by65.5cm has another urban subject.',
144:'One Ernest Wittmann birch watercolor on21 by16cm paper, first quarter twentieth century. Source domain drawing retained. Existing Lucien Lautrec birches use casein and another maker/support size.',
147:'One Cornillet Absinthe costume drawing,2021.7.32,25.7 by18.1cm, before1886. Distinct pose/costume and accession from other two Cornillet sheets; purchase lot is not counted as a separate artwork.',
148:'One Hadol1866 Charivari lithograph on newspaper40.2 by26.8cm, inventory2017.14.1. No creator/title/native counterpart; incomplete placeholder description remains source evidence only.',
149:'One Marc hameau sheet2021.6.3,19.5 by24.5cm, explicitly14August1819. Different site and dated view from his other individually inventoried drawings in the purchase.',
150:'One Nilouss Place de la Contrescarpe canvas60.4 by73.4cm, before1943; source describes rain, shops and frame labels. Exact-title Peter work has a different maker.',
152:'One Hadol1869 Grand derby lithograph on newspaper38.1 by26cm,2017.14.2. Separate from1866 Revue and Don Juan sheets by title, dimensions and accession.',
153:'One Marc aquarelle/ink Parmont view2021.6.6,19.5 by24.5cm, explicitly25September1819. The seventeenth-century camp and later fort are subject history; count only this individual sheet.',
154:'One Nilouss double-sided board37.9 by46.1cm,97.1.4, before1943. Landscape and reverse still life are ONE physical object with compound title; no second artwork for verso. Existing pepper still life is a different canvas.',
156:'One Hadol1866 Don Juan opera lithograph on newspaper27 by39.2cm,2017.14.3. Different composition and landscape orientation from the other Charivari sheets.',
157:'One Bonvin nun-on-stairs drawing25 by13cm, before1867, explicitly a study for a later finished canvas. Existing convent painting66.5 by55.5cm is another physical version.',
158:'One Bon Boullogne Proserpine canvas61 by78cm, seventeenth century. Exact-title Rubens, Loir and dellAbbate works have other creators; no matching Boullogne physical object.',
159:'One Brouardel1909 Casablanca warship watercolor23.5 by14.9cm, M.83.5.2. Source documents12 donated watercolors,7 recovered; this is one of seven individually inventoried sheets, not one of five unlocated works.',
160:'One Liberge Saint-Jacques Lisieux oil on waxed canvas53.8 by44.8cm, before1945. Existing exact-title Dannet is oil on wood73 by54cm; different maker/support.',
161:'One Leon Riesener Romantic Woman in Garden pastel53 by42cm, circa1830 with literal nineteenth-century bounds. Other Riesener portraits/nudes have different subjects or family creators; no matching native object.',
165:'One Brouardel1910 rue Verneuil flood watercolor on card26.8 by18.8cm, M.83.5.3. Shared historical catalogue139 groups the gift; separate modern accession and measured location distinguish this sheet.',
166:'One Leon Riesener child-head pastel18.5 by27.8cm. His existing little-girl oil canvas26.7 by22cm is a different physical work; same-title other artists do not identify this sheet.',
168:'One Brouardel1910 rue Saint-Dominique flood watercolor on card26.8 by18.7cm, M.83.5.4. Separate street/site and inventory from Verneuil despite similar format.',
169:'One Leon Riesener Rosalie1848 pastel21.5 by26.5cm. Preserve named sitter and literal date; no matching named portrait/native object.',
171:'One Brouardel1910 rue Universite watercolor23.5 by14.5cm, M.83.5.5. Individually catalogued recovered sheet; do not infer that the unlocated five watercolors share this holding.',
173:'One Brouardel1910 Valvier on the Seine watercolor18.2 by26.7cm, M.83.5.6. Specific site, measurement and modern inventory distinguish it from the other gift sheets.',
175:'One Brouardel1910 Caen Abbaye aux Hommes watercolor18.7 by26.7cm, M.83.5.7. Separate architecture/site from Paris flood views and seascape; retain group catalogue139 as historical evidence.',
176:'One Brouardel1910 Villers-sur-Mer watercolor26.4 by67.4cm, M.83.5.1. Panoramic seascape is a distinct sheet among seven recovered watercolors; no missing gift objects invented.'
}
HOLDS={
1:'Anonymous applied bronze Virgin: review cast date and generic iconography before selecting this physical version.',
2:'Source explicitly describes a modified later impression from a1660 map plate. Resolve impression date instead of automatically using plate date.',
3:'Related NG300 map impression needs edition and physical-object comparison before selection.',
10:'Existing Baron Les Musiciens has incomplete physical metadata; resolve composition before adding ambulant-musician print.',
16:'Existing Berchem Le gue lacks physical metadata; resolve painting/prototype versus print identity.',
17:'Exact-title Environs de Paris counterpart needs fuller map edition and impression review.',
21:'Exact-title Charles Dupin counterpart needs fuller named-sitter physical comparison.',
27:'Source says Antiope title actually depicts Orpheus/Eurydice. Research both identities before selection; do not silently rename.',
30:'Service Rousseau component NF1690.13 requires assembly/component review against parentNF1690.',
31:'Multiple Assiettes patriotiques impressions share parent inventory; preserve unit and edition ambiguity.',
33:'Bornibus cahier page and related impression need album/sheet unit review.',
36:'Generic Vase title denotes an intaglio print, not vessel. Exact-title/version comparisons retained for further review.',
37:'Putti print after Caldara has multiple exact-title leads; resolve translated and composition variants.',
38:'Print inscription names Le Bas while catalogue identifies Callet; existing Autumn prototype has incomplete physical data. Preserve discrepancy.',
39:'Generic Callot Bossu subject needs fuller composition and impression review.',
41:'Source explicitly says Caraglio model identification needs verification and engraving not found; preserve prototype uncertainty.',
43:'Attributed Cazes Judgment of Paris has several incomplete same-title leads and Charlottenburg narrative; review version/provenance.',
46:'Shared old GAA02464 with six modern subnumbers; review assembled portfolio history and Legros impression before selection.',
47:'Shared six-sheet accession history and another Bracquemond Manet impression; retain physical-unit/edition review.',
48:'Champfleury frontispiece shares GAA02464 group; retain portfolio/sheet review.',
50:'Baudelaire sheet shares six-part GAA02464 history; review physical grouping and impression.',
51:'Vernier portrait shares six-part group and incomplete paper-only medium; retain physical unit review.',
55:'Source alternates photo-gravure(?), eau-forte and drawing narrative; resolve production method and edition date.',
56:'Old PGC01656 also appears on existing Paysage de neige. Current inventory difference alone does not establish separate object.',
57:'Existing Daumier matching composition lacks sheet measurements. Resolve physical impression identity before creating another record.',
58:'Source names an eighteenth-century Martinet printer on nineteenth-century Daumier print. Preserve role/date inconsistency pending review.',
65:'Three existing Ordinaire same-title records lack physical metadata; reconcile duplicates before adding or linking.',
71:'Corot sheet shares six-part GAA02464 history; retain physical grouping/edition review.',
75:'Related numbered Bacchanales impressions and missing image dimensions need version comparison.',
78:'Workshop Barocci version and possible Pellegrini attribution require fuller identity review. Current ownership transfer supersedes historical1803 deposit; neither means current display.',
84:'Reversed-copy Virgin has generic same-title and Boucher-family leads; retain full version comparison.',
89:'Existing Bourdon Holy Family without physical metadata may represent this print; resolve composition.',
90:'Existing Bourdon Flight into Egypt and print impressions require edition/object reconciliation.',
91:'Cochin Charles Nicolas Pere role conflicts with1659 object date; do not resolve by silently replacing creator.',
93:'Abbreviated R. Brant could be read as a Rembrandt signature; preserve literal label and investigate creator identity before adding generic Holy Family.',
94:'1634 is also the model plate date; actual copy impression dating and version need review.',
95:'Existing Brebiette Triumph of Bacchus lacks physical metadata; resolve overlapping composition.',
96:'Source identifies later Bourlier state but1636 refers to first-state inscription. Resolve state dating.',
97:'Two pieces on shared montage and suite numbering need physical-unit review.',
98:'Five mounted friezes and attributed Brebiette1643 need component and attribution/date review.',
103:'Multiple Callot second-version impressions have close measurements; retain detailed edition/physical identity review.',
104:'Generic Carracci Virgin creator leads include incomplete objects; retain version comparison.',
105:'Existing Sainte Madeleine print has near-identical dimensions and related inventory; reconcile before adding.',
108:'Domaine dessin conflicts with explicit eau-forte description; shared3610 group also needs unit review.',
110:'Character-head impression shares3610 group with conflicting-type companion; resolve group and version.',
122:'Generic Burger woman portrait has an incomplete existing Frau Langhammer comparison; identify sitter/composition.',
123:'Several Aligny Italian landscapes need fuller same-object comparison despite differing known formats.',
126:'Existing Diaz Enfants et chiens lacks physical data; retain same-version uncertainty and attributed-to label.',
129:'Rivage title conflicts with desert cavalry description, and compound Lucien-Robert Henri needs supplemental alias search.',
133:'Swanevelt Italian landscape leads lack dimensions; retain composition/version review.',
135:'Bronze described as taille requires material/casting-version review; no cast date inferred.',
136:'Ziem Venice draft has numerous incomplete same-place versions; resolve composition.',
137:'Anonymous1703 Coornhert portrait painted as a print needs former-attribution/identity review; do not classify as actual engraving.',
140:'One boxed32-plate lithographic collection, with duplicate title sheet. No count inflation; retain assembled-object review.',
145:'Ziem Venice has numerous incompletely described existing versions; retain same-work uncertainty.',
146:'Anonymous hunting landscape lacks a secure maker and specific matched identity; retain research record without inventing attribution.',
151:'Anonymous military portrait has an incompletely described named-creator title lead; review identity and paired portrait.',
155:'Second anonymous military portrait differs from its pair but existing Fontaine title lead remains incomplete; retain identity review.',
162:'Teniers-school cabaret has incomplete existing smoking/cabaret versions; preserve school attribution and hold.',
163:'Anonymous washerwomen has multiple named-creator same-title leads; retain attribution/physical identity review.',
164:'Former Arethusa title requires supplemental identity search alongside Pan and Syrinx before selection.',
167:'Fortune-teller sketch has incomplete Colin de La Biochaye exact-title counterpart; retain version review.',
170:'Generic anonymous landscape damaged in2000 fire has hundreds of title leads; resolve current object/custody and identity.',
172:'Existing Riesener Venus and Cupid lacks physical metadata; reconcile original/version before addition.',
174:'Source says this oval sketch relates to Lyon original; existing Riesener title lead needs physical-version reconciliation.'
}
def build():
    x=m.load(CANDIDATES);ix=m.load(IDENTITY);cx=m.load(CITATIONS)
    for dep in x['dependencies']+[x['parser_reference'],ix['query_reference'],ix['base_query_reference']]:checked(dep)
    assert ix['candidate_reference']==ref(CANDIDATES) and cx['identity_reference']==ref(IDENTITY)
    validation=m.load(RUN/'identity-recomputed-001.json');checked(validation['validator_reference'])
    assert validation['comparisons_recomputed_equal'] and validation['identity_reference']==ref(IDENTITY) and validation['candidate_reference']==ref(CANDIDATES)
    assert ix['params']==identity.params_for(x['rows'])
    assert set(NOTES).isdisjoint(HOLDS) and set(NOTES)|set(HOLDS)==set(range(1,177));out=[]
    for row,cmp in zip(x['rows'],ix['comparisons']):
        assert row==f.parse(row['index'],checked(row['source_reference']));assert row['source_id']==cmp['source_id'];n=row['number'];v=copy.deepcopy(row['facts'])
        if n in HOLDS:out.append(dict(row,state='editorial_hold',basis=HOLDS[n],comparison=cmp));continue
        assert v['date_issue'] is None and v['date_precision']!='after'
        assert (v['first'] is None and v['date_precision']=='before' and v['last']<=1971) or (v['first'] is not None and v['first']<=v['last']<=1970)
        assert v['inventory'] and v['credit_line'] and v['creator_label']
        assert not cmp['untitled_creator_hits'] and not any(cmp[k] for k in ['native_scheme_hits','native_url_hits','source_record_hits']) and not any(a['relevant'] for a in cmp['inventory_hits'])
        basis='Official Joconde object '+v['source_id']+', inventory '+v['inventory']+'. '+NOTES[n]+' Literal physical description: '+str(v['medium'])+'; '+str(v['dimensions_text'])+'. Current source ownership/collection: '+v['credit_line']+'.'
        out.append(dict(row,facts=v,state='approved_review_only_addition',existing_artwork_id=None,confidence=.90,basis=basis,comparison=cmp,derived_fields=dict(object_form=None,type_derivations=v['type_derivations']),limitation='Editorial confidence in physical object identity and documented museum connection, not a calibrated probability. Literal source creator roles, dates, unknowns and source labels retained. New record remains review. No artist authority, image, publication or current-display assertion.'))
    return out
def main():
    dest=RUN/'editorial-reviewed-001.json.gz';assert not dest.exists();rows=build()
    paths=[CANDIDATES,IDENTITY,CITATIONS,RUN/'identity-recomputed-001.json']
    m.save(dest,dict(at=m.now(),reviewer_reference=ref(Path(__file__).resolve()),decisions=rows,supplement_references=[ref(p) for p in paths],policy='Individual source-backed physical-object decisions. No quota overrides of dates or identity; unresolved cases remain research holds. Selected new local records remain review.'))
    print(json.dumps(dict(approved=len(NOTES),held=len(HOLDS),by_museum={v['museum']['name']:sum(a['institution_id']==v['institution_id'] and a['state']=='approved_review_only_addition' for a in rows) for v in rows})),flush=True)
if __name__=='__main__':main()
