"""Freeze verified wave92 changes, immutable evidence, source holds and research queues."""
import csv,hashlib,importlib.util,json
from pathlib import Path
z=importlib.util.spec_from_file_location('a',Path(__file__).with_name('museum-expansion-leeds-apply-20261009.py'));a=importlib.util.module_from_spec(z);z.loader.exec_module(a);m=a.m;sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 dest=a.RUN/'delivery-checkpoint-001.json';assert not dest.exists();assert sha(a.CHECKPOINT)=='8d0721548ba1f3b8b9164e7417f6d504fe3401987ffd9ee5e5f20bd879174b55';previous=m.load(a.CHECKPOINT);assert(len(previous['artifacts']),len(previous['external_artifacts']))==(32617,830);changes=m.load(a.RUN/'readme-supersessions-001.json')['changes'];changed={v['path']:v for v in changes};assert set(changed)=={str((m.RUN/'README.md').relative_to(m.ROOT))}
 for c in changes:
  assert sha(Path(c['backup_path']))==c['backup_sha256'];x=m.load(Path(c['backup_path']));assert hashlib.sha256(x['text'].encode()).hexdigest()==x['sha256']==c['before_sha256'];assert sha(m.ROOT/c['path'])==c['after_sha256']
 for dep in previous['artifacts']:
  if dep['path'] in changed:assert dep['sha256']==changed[dep['path']]['before_sha256']
  else:a.checked(dep)
 p,digest=a.validate_plan()
 with m.connect() as db:verified=a.verify(db,p,digest)
 assert verified['verified_new_records']==0 and verified['existing_artworks_linked']==80 and verified['prior_campaign_records_preserved']==13198 and verified['existing_gallery_holdings_preserved']==8;assert m.load(a.RUN/(a.KEY+'-applied.json'))['plan_sha256']==digest;report=m.load(m.RUN/'verification-after-wave-92.json');assert(report['verified_new_artworks'],report['verified_existing_artworks_linked'])==(10472,2806);checks=m.load(a.RUN/'checks-001.json');assert(checks['new_offline_tests_passed'],checks['historical_tests_passed'],checks['cumulative_verified_tests'])==(20,1804,1824) and checks['replay_zero_writes'];audit=m.load(m.RUN/'after-wave-92.json');csvcounts={};ids=[]
 for name,count in [('added-artworks-after-wave-92.csv',10472),('reconciled-artworks-after-wave-92.csv',2806),('gac-date-enrichments-after-wave-92.csv',6),('museum-coverage-after-wave-92.csv',len(audit['institutions']))]:
  with(m.RUN/name).open(newline='') as fp:rows=list(csv.DictReader(fp))
  assert len(rows)==count;csvcounts[name]=count
  if name.startswith(('added-artworks','reconciled-artworks')):ids.extend(v['artwork_id'] for v in rows)
 assert len(ids)==len(set(ids))==13278;external=previous['external_artifacts']+list(checks['logs'].values())+[dict(path=v['backup_path'],sha256=v['backup_sha256']) for v in changes]
 for path in sorted(m.BACKUP.glob(a.KEY+'-*.json.gz')):external.append(dict(path=str(path),sha256=sha(path)))
 assert m.load(m.BACKUP/(a.KEY+'-reviewed-plan-001.json.gz'))==p;identity=m.load(m.BACKUP/(a.KEY+'-transaction-identity-001.json.gz'));assert identity['state_equal'] and identity['citations_equal'] and identity['artwork_count']==7444 and identity['citation_count']==15909;log=Path('/Users/vadimdulub/Library/Logs/artline-leeds-delivery-20261009.log');assert '"documented_existing_links": 80' in log.read_text();external.append(dict(path=str(log),sha256=sha(log)));unique={}
 for dep in external:
  assert dep['path'] not in unique or unique[dep['path']]==dep;unique[dep['path']]=dep;assert sha(Path(dep['path']))==dep['sha256']
 a.checked(previous['other_job_status_reference']);paths={m.ROOT/v['path'] for v in previous['artifacts']}|{a.CHECKPOINT,Path(__file__).resolve()};paths|={m.ROOT/v['path'] for v in p['evidence']};paths|={v for v in a.RUN.rglob('*') if v.is_file()};paths|={v for v in(m.ROOT/'ops').glob('*leeds*20261009.py')};paths|={v for v in m.RUN.glob('*after-wave-92*')};artifacts=[a.reference(v) for v in sorted(paths)];remaining=m.load(a.RUN/'remaining-research-001.json.gz');assert len(remaining['rows'])==4 and remaining['gallery_linked']==88 and remaining['gallery_eligible']==62;nextq=m.load(a.RUN/'next-museum-pass-001.json');assert len(nextq['italian_museums'])==225;availability=a.RUN/'source-availability-001.json';access=m.load(availability);assert not access['new_source_access_holds'];assert m.load(a.RUN/'native-probes-001.json')['stopped_providers']==[]
 result=dict(at=m.now(),goal_complete=False,local_only=True,new_additions=0,new_existing_links=80,campaign_new_artworks=10472,campaign_existing_links=2806,distinct_campaign_artwork_ids=13278,institutions_with_new_records_or_reconciled_holdings=report['institutions_with_new_records_or_reconciled_holdings'],verification=verified,museum_changes=report['leeds_museum_changes'],museums_below_100=report['after']['museums_below_100'],museums_below_200=report['after']['museums_below_200'],global_coverage_snapshot_at=report['global_coverage_snapshot_at'],external_registry_growth_reference=report['external_registry_growth_reference'],new_tests_passed=20,historical_tests_passed=1804,cumulative_verified_tests=1824,plan_sha256=digest,csv_counts_verified=csvcounts,artifacts=artifacts,external_artifacts=list(unique.values()),prior_checkpoint_reference=a.reference(a.CHECKPOINT),prior_artifacts_verified=len(previous['artifacts']),intentional_supersessions=changes,other_job_status_reference=previous['other_job_status_reference'],other_job_totals_separate=True,editorial_holds=4,existing_gallery_holdings_preserved=8,review_reference=a.reference(a.REVIEW),remaining_research_reference=a.reference(a.RUN/'remaining-research-001.json.gz'),next_museum_pass_reference=a.reference(a.RUN/'next-museum-pass-001.json'),source_availability_reference=a.reference(availability),new_source_access_holds=access['new_source_access_holds'],new_source_access_hold_reference=a.reference(a.RUN/'new-source-access-holds-001.json'),prior_source_access_hold_reference=previous['new_source_access_hold_reference'],runtime=previous['runtime'],next_work='80 verified Leeds gallery holdings:58 date-eligible,22unknown. Gallery88linked/62eligible,still38eligible short of100. Four physical-identity holds:Wilson equal-format pair,Rhodes MootHall possible venue duplicate,Bigge generic Composition.16selected GAC leads need exact gallery,creator,version and existing-record review;2other leads already catalogued,4specific gaps/exclusions including private loan and inconsistent historical-work medium.22selected object pages captured;no images or source-hold retries. IWM133/130,London13/13and88unresolved branchclaims,Royal161/151with12holds,Glasgow branchgaps,Southampton15datedPDFleads,Edinburgh88/29,Guildhall115/86,225Italian museums and allpriorqueues persist.13198priorcampaignrecords preserved;cumulative13278distinct. Concrete80-object progress,not repeated global blocker. Continue Leeds selected native leads and other independent museums. Use lightweight Leeds/IWM/Royal helpers,not recursive historical importchains. Full100minimum/200preferred all-museum goal active.');m.save(dest,result);print(json.dumps(dict(checkpoint=str(dest.relative_to(m.ROOT)),sha256=sha(dest),artifacts=len(artifacts),external_artifacts=len(unique),new_records=0,new_links=80,campaign_new=10472,campaign_links=2806,below100=result['museums_below_100'])),flush=True)
if __name__=='__main__':main()
