#!/usr/bin/env python3
"""Build an evidence-backed completion report after delivery and fresh audits."""
import argparse,collections,hashlib,importlib.util,json,time
from pathlib import Path
s=importlib.util.spec_from_file_location('delivery',Path(__file__).with_name('upload-overnight-prepared-images.py'));delivery=importlib.util.module_from_spec(s);s.loader.exec_module(delivery);core=delivery.core
START=1789501601
def journal_state(path):
 state={}
 for line in path.read_text().splitlines():
  row=json.loads(line)
  if row['outcome'] in ('attached','already_attached'):state[row['artwork_id']]=row
  elif row['outcome']=='withdrawn':state.pop(row['artwork_id'],None)
 return state
def audit_matches(audit,count,target,storage=False):
 assert audit['target']==target and not audit['errors'],'Audit has errors or wrong target'
 assert audit['journal_snapshot_artworks']==audit['source_and_file_verified']==audit['db_verified']==count,'Audit snapshot does not cover the complete delivered set'
 if storage:assert audit['google_storage_verified']==count,'Google Storage audit incomplete'
def main():
 p=argparse.ArgumentParser();p.add_argument('--run',type=Path,required=True);p.add_argument('--local-audit',type=Path,required=True);p.add_argument('--production-audit',type=Path,required=True);p.add_argument('--metadata-audit',type=Path,required=True);p.add_argument('--public-check',type=Path,required=True);a=p.parse_args();r=a.run
 assert time.time()-START>=8*3600,'Eight-hour research period is not complete'
 local=json.loads(a.local_audit.read_text());cloud=json.loads(a.production_audit.read_text());metadata=json.loads(a.metadata_audit.read_text());public=json.loads(a.public_check.read_text());journal=journal_state(r/'local-attachments.jsonl');done=delivery.complete_ids(r);assert done==set(journal),'Delivery remains pending or completion receipts disagree'
 audit_matches(local,len(done),'local');audit_matches(cloud,len(done),'cloud',True);assert not metadata['errors'] and metadata['matching_metadata_records']==metadata['metadata_records_expected'] and metadata['new_artist_metadata_matches'],'Metadata comparison incomplete'
 assert public['image_canaries_verified']==public['image_canaries_total'],'Public image delivery canary failed'
 assert json.loads((r/'withdrawn-reference-audit-final.json').read_text())['all_withheld_images_unattached'],'A held image remains attached'
 assert not json.loads((r/'artifact-safety-scan.json').read_text())['credential_pattern_findings'],'Artifact credential scan needs review'
 assert json.loads((r/'shared-image-review-final.json').read_text())['new_groups_since_review']==0,'Shared image review incomplete'
 assert local['by_provider']==cloud['by_provider'] and local['by_work_type']==cloud['by_work_type'],'Target audited counts differ'
 target=r/'approved-image-manifest.jsonl';assert not target.exists();temporary=target.with_suffix('.temporary.jsonl');hashes=set();source_hashes=set();popular=0;bytes_total=0;examples=[]
 with temporary.open('x') as out:
  for aid,j in sorted(journal.items()):
   im=json.loads(Path(j['receipt']).read_text());receipt=r/'production-resume'/im['provider']/'images'/im['provider']/(aid+'.json')
   if receipt.exists():im=json.loads(receipt.read_text())
   assert im['target_ids']['local']==aid and im['target_ids'].get('cloud') and im['provider'] in cloud['by_provider']
   assert delivery.audit.allowed(im['policy_url']) and im['creator_credit'] and im['source_record_url'] and im['rights_verified_at']
   record={'local_artwork_id':aid,'production_artwork_id':im['target_ids']['cloud'],'media_id':im['media_id'],'source_name':im.get('source_name') or core.PROVIDERS.get(im['provider'],im['provider']),'source_record_url':im['source_record_url'],'source_object_id':im.get('source_object_id',im['external_id']),'source_identifier_scheme':im['scheme'],'artist':im['artist'],'title':im['title'],'creation_date':im.get('creation_date',im.get('date_display')),'year_start':im['creation_year_start'],'year_end':im['creation_year_end'],'work_type':im['work_type'],'image_url':im['source_image_url'],'image_source_page':im['page'],'image_license':im['license_label'],'image_license_url':im['policy_url'],'rights_statement':im.get('rights_statement',im['license_label']),'creator_credit':im['creator_credit'],'image_attribution':im['attribution_text'],'retrieved_at':im.get('downloaded_at',im['checked_at']),'rights_verified_at':im['rights_verified_at'],'artline_image_path':im['path'],'google_storage_object':'gs://'+core.BUCKET+im['path'],'image_sha256':im['sha256'],'bytes':im['bytes'],'width':im['width'],'height':im['height'],'status':'review','hasPicture':True}
   out.write(json.dumps(record,ensure_ascii=False,separators=(',',':'))+'\n');hashes.add(im['sha256']);source_hashes.add(im['source_sha256']);bytes_total+=im['bytes'];popular+=bool(im.get('popular'))
   if len(examples)<16 and im['provider'] not in {x['provider'] for x in examples}:examples.append({'provider':im['provider'],'artist':im['artist'],'title':im['title'],'source_url':im['page'],'license_url':im['policy_url']})
 temporary.replace(target)
 with target.open('rb') as f:manifest_sha=hashlib.file_digest(f,'sha256').hexdigest()
 withdrawn=json.loads((r/'withdrawn-images.json').read_text())['records'];counts=metadata['targets']['local']['counts'];hours=(time.time()-START)/3600
 report={'started_at':'2026-09-15T19:46:41Z','completed_at':core.now(),'elapsed_hours':round(hours,3),'requested_minimum_hours':8,'requested_image_target':50000,'artwork_image_attachments_verified_both_targets':len(done),'unique_delivered_image_sha256':len(hashes),'unique_downloaded_source_sha256':len(source_hashes),'target_50000_unique_image_bytes_reached':len(hashes)>=50000,'popular_painter_image_attachments':cloud['popular_painter_images'],'by_work_type':cloud['by_work_type'],'by_provider':cloud['by_provider'],'by_exact_image_license':cloud['by_image_license'],'by_holding_museum':cloud['by_holding_museum'],'by_holding_country':cloud['by_holding_country'],'institution_count':len(cloud['by_holding_museum']),'new_artworks_both_targets':counts['new'],'existing_artwork_metadata_enrichments':counts['existing_enriched'],'new_artists_both_targets':metadata['new_artists_checked_each_target'],'new_artist_country_affiliations_verified':True,'image_bytes_total':bytes_total,'source_image_associations_withdrawn':len(withdrawn),'unresolved_origin_public_images_retired':json.loads((r/'commons-origin-withdrawal-completed.json').read_text())['count'],'unresolved_photo_credit_images_retired':json.loads((r/'cc-attribution-holds-completed.json').read_text())['count'],'photographer_credits_corrected_each_target':json.loads((r/'cc-attribution-corrections-verified.json').read_text())['corrections_each_target'],'physical_artworks_deleted_or_merged':0,'records_remain_in_review':True,'new_schema_migrations':0,'art500k_used':False,'evidence':{'local_image_audit':a.local_audit.name,'production_image_storage_audit':a.production_audit.name,'metadata_parity_audit':a.metadata_audit.name,'public_canaries':a.public_check.name,'withdrawals':'withdrawn-images.json','manifest':target.name,'manifest_sha256':manifest_sha},'public_checks':{k:public[k] for k in ('image_canaries_verified','image_canaries_total','api_checks_verified','api_checks_total')},'source_examples':examples,'limits':['Artwork attachments, unique compressed image hashes and unique downloaded source hashes are different counts; shared views of museum sets/parts are retained only with documented review.','Most additions include prints and drawings; paintings and painted works are reported separately.','All automated source/rights/database/storage checks are complete; visual inspection was sampled, supplemented by duplicate-image review.','Country totals describe museum locations, using an institution place or unanimous known venue countries. They are never painter-nationality inferences.','Historical local/production catalogue differences are outside this campaign; imported metadata and delivered images were explicitly matched.','Museum detail routes previously timed out during heavier ingestion. Current canaries and any remaining failures are recorded. A UUID-scoped performance fix is prepared but remains undeployed pending explicit deployment authorization.']}
 core.save_new(r/'final-aggregate-report.json',report)
 lines=['# Overnight image research and delivery','',f"Completed {report['completed_at']} after {hours:.2f} hours. Both databases and Google Storage were checked after delivery.",'',f"- **{len(done):,} artwork image attachments** verified in local and production.",f"- **{len(hashes):,} unique delivered image files by SHA-256**; {cloud['popular_painter_images']:,} attachments belong to popular painters.",f"- **{counts['new']:,} new artworks**, {counts['existing_enriched']:,} existing metadata enrichments and **{metadata['new_artists_checked_each_target']:,} new artists** verified in both databases.",f"- New artist country affiliations are source-backed. All additions remain **in review**.",f"- {len(withdrawn)} image associations with identity, origin or attribution concerns withheld; physical artworks and evidence preserved.",'','| Artwork type | Delivered images |','| --- | ---: |']
 lines.extend(f"| {kind} | {count:,} |" for kind,count in sorted(cloud['by_work_type'].items()));lines+=['','| Source adapter | Delivered images |','| --- | ---: |'];lines.extend(f"| {name} | {count:,} |" for name,count in sorted(cloud['by_provider'].items(),key=lambda x:-x[1]));lines+=['','Files:', '', '- [Aggregate results](final-aggregate-report.json)', '- [Approved image manifest](approved-image-manifest.jsonl)',f'- [Local audit]({a.local_audit.name})',f'- [Production and storage audit]({a.production_audit.name})',f'- [Metadata and country audit]({a.metadata_audit.name})',f'- [Public delivery checks]({a.public_check.name})','- [Shared-image review](shared-image-review-final.json)','- [Final catalogue statistics](catalogue-statistics-final.json)','- [Campaign artifact scan](artifact-safety-scan.json)','- [Test evidence locations](test-log-locations.json)','- [Withheld image associations](withdrawn-images.json)','- [Unresolved-origin public copy retirement](commons-origin-withdrawal-completed.json)','- [Photographer credit corrections](cc-attribution-corrections-verified.json)','- [Unresolved photographer credit holds](cc-attribution-holds-completed.json)','- [Prepared API performance fix](api-detail-fix/review.json)','','Validation and limits:',''];lines.extend('- '+note for note in report['limits']);lines+=['','Recovery and resumption:','','Recovery manifests and per-batch preimages are under `~/Library/Application Support/Artline/backups/overnight-images-20260915/`. The run stores immutable selected-source receipts, image files and append-only outcome journals. `apply-night-prepared-local.py --once` attaches pending prepared local images; `upload-overnight-prepared-images.py --once` delivers a bounded pending page. Both need `--run` and a future `--deadline`; rerun fresh audits before regenerating a completion report. Never replace evidence files to hide failed or superseded checks.','','No commit, Terraform apply, deployment or change from review to published status was performed by this campaign. ART500K and the cancelled private reference dataset were not used.']
 (r/'README.md').write_text('\n'.join(lines)+'\n');print(json.dumps({k:report[k] for k in ('elapsed_hours','artwork_image_attachments_verified_both_targets','unique_delivered_image_sha256','popular_painter_image_attachments','new_artworks_both_targets','new_artists_both_targets')},indent=2))
if __name__=='__main__':main()
