#!/usr/bin/env python3
import importlib.util,sys,json,time
from pathlib import Path
import psycopg
ROOT=Path(__file__).resolve().parents[1];sys.path.insert(0,str(ROOT/'ops'))
assert not (ROOT/'docs/research/books-5000bce-1850-20261004/plan.json').exists(), 'Preserve the completed campaign; use a new campaign for new research.'
s=importlib.util.spec_from_file_location('r',ROOT/'ops/research-early-books-20260923.py');r=importlib.util.module_from_spec(s);s.loader.exec_module(r)
r.OUT=ROOT/'docs/research/books-5000bce-1850-20261004'
titles=['Instructions of Amenemhat','Instruction of Amenemope','The Maxims of Ptahhotep','Instructions of Shuruppak','Lament for Ur','Enmerkar and the Lord of Aratta','Lugalbanda in the Mountain Cave','Lugalbanda and the Anzud Bird','Hymn to Enlil','The Debate between Bird and Fish','The Poor Man of Nippur','Ludlul bēl nēmeqi','Atra-Hasis','Descent of Inanna','Advice to a Prince','Works and Days','The Shield of Heracles','Hymn to Demeter','On the Sacred Disease','On Airs, Waters and Places','On the Nature of Man','On the Crown','Anabasis (Xenophon)','Cyropaedia','Memorabilia (Xenophon)','Oeconomicus','Hiero (Xenophon)','Agesilaus (Xenophon)','De rerum natura','De officiis','De finibus bonorum et malorum','De natura deorum','Tusculan Disputations','On the Sublime','De aquaeductu','The Art of Cookery (Apicius)','De agricultura','Res rustica','The Ten Books on Architecture','The Book of Healing','The Canon of Medicine','Kitab al-Hayawan','Book of Roads and Kingdoms (Ibn Khordadbeh)','The Meadows of Gold','The Book of the Thousand Nights and One Night','The Tale of the Bamboo Cutter','Tosa Nikki','The Gossamer Years','The Pillow Book','Narrow Road to the Interior','The Book of Five Rings','The Life of an Amorous Man','The Great Mirror of Male Love','The Peach Blossom Fan','The Peony Pavilion','The Palace of Eternal Life','The Scholars (novel)','Six Records of a Floating Life','Strange Tales from a Chinese Studio','The Plum in the Golden Vase','Journey to the West','Water Margin','The Story of the Western Wing','Dream of the Red Chamber','Romance of the Three Kingdoms','Observations upon Experimental Philosophy','Philosophical Letters','Poems and Fancies','The Female Academy','The Convent of Pleasure','The Description of a New World, Called The Blazing-World','The Unfortunate Traveller','The English Rogue','The Pilgrim’s Progress','The Holy War','The Compleat Angler','The New Atlantis','New Atlantis','Religio Medici','The Life and Opinions of Tristram Shandy, Gentleman','A Sentimental Journey Through France and Italy','A Simple Story (novel)','Nature and Art','The Old English Baron','The Castle of Otranto','The Female Quixote','The Spiritual Quixote','The Vicar of Wakefield','The Man of Feeling','The Man of the World (novel)','The Expedition of Humphry Clinker','The Adventures of Ferdinand Count Fathom','The Adventures of Peregrine Pickle','The Adventures of Roderick Random','The Adventures of Sir Launcelot Greaves','The History of Rasselas, Prince of Abissinia','The History of Nourjahad','The Female American','Zofloya','The Swiss Family Robinson','The Last of the Mohicans','The Prairie','The Pioneers (novel)','The Spy (Cooper novel)','The Pilot: A Tale of the Sea','The Deerslayer','The Pathfinder, or The Inland Sea','The Betrothed (Manzoni novel)','The Scarlet Letter','David Copperfield','The Prelude','Villette','Sylvie']
titles += ['De magnete', 'Micrographia', 'Sidereus Nuncius', 'Astronomia nova', 'Harmonices Mundi', 'Mysterium Cosmographicum', 'Selenographia', 'Uranometria', 'Musurgia Universalis', 'Mundus Subterraneus', 'Ars Conjectandi', 'Introductio in analysin infinitorum', 'Institutiones calculi differentialis', 'Traité de mécanique céleste', 'Mécanique analytique', 'On the Connexion of the Physical Sciences', 'Preliminary Discourse on the Study of Natural Philosophy', 'The Temple (poetry collection)', 'Hesperides (poetry collection)', 'Silex Scintillans', 'Lyrical Ballads', 'Elegy Written in a Country Churchyard', 'The Seasons (poem)', 'The Task (poem)', 'The Deserted Village', 'The Borough (poem)', 'The Village (poem)', 'The Giaour', 'The Corsair', 'The Bride of Abydos', 'Lalla Rookh', 'The Lady of the Lake (poem)', 'Marmion (poem)', 'The Lay of the Last Minstrel', 'Evangeline', 'Goblin Market', 'The Princess (Tennyson poem)']
with psycopg.connect('postgres://localhost/artline',options='-c default_transaction_read_only=on') as db: existing=dict(db.execute('select source_id,id from book_records'))
candidates=[]
for offset in range(0,len(titles),15):
 data,proof=r.capture('en.wikipedia.org',{'action':'query','titles':'|'.join(titles[offset:offset+15]),'redirects':1,'prop':'pageprops|extracts|revisions|images','ppprop':'wikibase_item','exintro':1,'explaintext':1,'exlimit':20,'rvprop':'ids|timestamp','imlimit':50})
 for p in data['query']['pages']:
  q=p.get('pageprops',{}).get('wikibase_item')
  if q and not p.get('missing'):candidates.append({'title':p['title'],'qid':q,'extract':p.get('extract',''),'revision':p.get('revisions',[{}])[0].get('revid'),'images':p.get('images',[]),'source':proof,'existing':existing.get(q)})
 print('Captured',offset+15,flush=True)
(r.OUT/'candidates-intro.json').write_text(json.dumps(candidates,ensure_ascii=False,indent=2)+'\n')
entities={};wanted=sorted({c['qid'] for c in candidates if not c['existing']})
for offset in range(0,len(wanted),10):
 data,proof=r.capture('www.wikidata.org',{'action':'wbgetentities','ids':'|'.join(wanted[offset:offset+10]),'props':'info|labels|descriptions|claims','languages':'en','sitefilter':'enwiki'})
 entities.update({q:{'entity':e,'source':proof} for q,e in data['entities'].items()})
for c in candidates:c['wikidata']=entities.get(c['qid'])
r.OUT.mkdir(parents=True,exist_ok=True);(r.OUT/'candidates.json').write_text(json.dumps(candidates,ensure_ascii=False,indent=2)+'\n')
for c in candidates:
 if not c['existing']:print(c['qid'],c['title'],c['extract'][:850].replace('\n',' '),flush=True)
